prow-configurations/README.md, prow-configurations/install-prow.sh, prow-configurations/remove-prow.sh
- Add installation script for Prow
- Add removal script
- Add Readme to explain how it works
Implements #8
=> Add installation script for Prow

README.md
Add documentation about development workflow for Prow.
Resolves #24
=> Define development workflow for Prow.

prow-configurations/create-gcp-secrets.sh, prow-configurations/install-prow.sh
- Read secrets from GCS in installation script
#26
=> Read secrets from GCS in installation script

integration-job/README.md
- To be consistent with other documents and Google documentation, fixed minor terminology discrepancies.
=> Add minor fixes in terminology

prow-configurations/install-prow.sh
=> Fix for secrets management

prow-configurations/README.md
- Extend note about bot account 
See also #20
=> Improve bot account note

prow-configurations/README.md, prow-configurations/config.yaml.tpl, prow/config.yaml
- Added placeholder job that activates on pull request comment
=> Placeholder job for provisioning GKE cluster for integration tests

integration-job/provision_vm_and_start_kyma.sh, prow-configurations/config.yaml.tpl, prow/config.yaml
- Fix null arg issue for the postsubmit jobs
- Bump up the image version 
=> Fix null argument issue

development/README.md, development/install-prow.sh, prow/README.md
- Remove default values for BUCKET_NAME, KEYRING_NAME, and ENCRYPTION_KEY_NAME from the install-prow.sh script
- Update docu
See #68
=> Remove default values from the install prow script

prow/scripts/create-dns-entry.sh
- Added script that generate type a dns record on given project and zone
=> Generate type A DNS record

prow/scripts/provision-vm-and-start-kyma.sh
- Fix insufficient permission issue by explicit authentication.
Fixes #103
=> Fix insufficient permission issue

prow/config.yaml, prow/images/bootstrap/Makefile, prow/images/buildpack-golang/Makefile, prow/images/buildpack-node/Makefile, prow/images/cleaner/Makefile, prow/jobs/test-infra/buildpack.jobs.yaml, prow/jobs/test-infra/test-infra.jobs.yaml, prow/scripts/library.sh, prow/scripts/pipeline.sh, prow/scripts/publish-buildpack.sh
- Creates jobs to publish buildpacks
- Adds makefile to all the image folders
See #54
=> Create jobs for publishing buildpacks

prow/README.md, prow/scripts/README.md, prow/scripts/cluster-integration/README.md
- Added minor fixes in the Prow documentation
=> Add minor fixes

prow/README.md
- Added the smallest change in the world
=> Add a minor fix

development/tools/jobs/test_job_definitions_test.go, development/tools/jobs/tester/tester.go, prow/jobs/test-infra/test-job-definitions.yaml
-   fix run_if_changed field
- added tests
=> test-jobs-yaml-definitions - fix run_if_changed field

docs/prow/prow-installation-on-forks.md
- Added minor changes in the installation guide for forks.
=> Add changes in the instruction for forks

development/tools/Gopkg.lock, development/tools/Gopkg.toml, development/tools/Makefile, development/tools/before-commit.sh, development/tools/cmd/configuploader/main_test.go, development/tools/jobs/binding_usage_controller_test.go, development/tools/jobs/tester/tester.go, development/tools/jobs/tools_test.go, development/tools/jobs/ui_api_layer_test.go, development/tools/pkg/file/file.go, development/validate-scripts.sh, prow/jobs/test-infra/development/tools/tools.yaml
- Added `tools` project validation
- Fixed test for `test-infra` repository
See #134
=> Add tools validation

prow/README.md, prow/cluster/04-branchprotector_cronjob.yaml, prow/cluster/README.md, prow/config.yaml, prow/install-prow.sh, prow/plugins.yaml
- Added Branch Protector CronJob
- Defined protection for `test-infra` repository
- Simplified plugins configuration
To test Branch Protector bot needs to has access to repository settings.
See #131
=> Add branch protection

prow/jobs/kyma/kyma-integration.yaml, prow/scripts/cluster-integration/pr-gke-integration.sh
- add testing.sh to the GKE integration pipeline
- change bootstrap to bootstrap-helm image
#139
=> Add testing.sh to the GKE integration pipeline

development/tools/jobs/console/brokers_test.go, development/tools/jobs/console/catalog_test.go, development/tools/jobs/console/content_test.go, development/tools/jobs/console/instances_test.go, development/tools/jobs/kyma/binding_usage_controller_test.go, development/tools/jobs/kyma/remote_environment_broker_test.go, development/tools/jobs/kyma/ui_api_layer_test.go, development/tools/jobs/testinfra/buildpack_test.go, docs/prow/kyma-release-process.md, docs/prow/migration-guide.md, prow/README.md, prow/config.yaml, prow/jobs/console/brokers/brokers.yaml, prow/jobs/console/catalog/catalog.yaml, prow/jobs/console/content/content.yaml, prow/jobs/console/instances/instances.yaml, prow/jobs/kyma/components/binding-usage-controller/binding-usage-controller.yaml, prow/jobs/kyma/components/remote-environment-broker/remote-environment-broker.yaml, prow/jobs/kyma/components/ui-api-layer/ui-api-layer.yaml, prow/jobs/kyma/kyma-integration.yaml, prow/jobs/test-infra/buildpack.yaml, prow/jobs/test-infra/development/tools/tools.yaml, prow/jobs/test-infra/test-job-definitions.yaml, prow/jobs/test-infra/validation.yaml
- Rename all the jobs by using `-` instead of `/`
- Update the documentation
See #186
=> Rename the jobs

prow/config.yaml
- Removed slash from job name in branch protection
=> Fix job name in branch protection

docs/prow/kyma-release-process.md, docs/prow/migration-guide.md, docs/prow/production-cluster-configuration.md, docs/prow/prow-installation-on-forks.md, docs/prow/prow-secrets-management.md, prow/README.md, prow/images/README.md
- Change Prow jobs into ProwJobs
- Removed capitalization from an event
=> Update the resource name

development/tools/jobs/kyma/helm_broker_test.go, prow/jobs/kyma/components/helm-broker/helm-broker.yaml
- Added job for helm broker
#142
=> Add job for Helm Broker

development/tools/jobs/console/react_components_test.go, prow/jobs/console/react-components/react-components.yaml
- Add react-components.yaml with presubmits
Resolves #155
=> Add react-components.yaml with presubmits

docs/prow/prow-architecture.md
- Removed capitalization from headers.
=> Remove capitalization from headers

development/tools/jobs/kyma/tools/etcd_backup_test.go, prow/jobs/kyma/tools/etcd-backup/etcd-backup.yaml
=> Add jobs for etcd backup tool

development/tools/jobs/kyma/stability_checker_test.go, prow/jobs/kyma/tools/stability-checker/stability-checker.yaml
- Added job for tools/stability-checker
=> Add job for Stability Checker

development/tools/jobs/kyma/acceptance_tests_test.go, docs/prow/migration-guide.md, prow/jobs/kyma/tests/acceptance/acceptance.yaml
- Added a prow job for the acceptance tests
=> Add job for acceptance tests

development/tools/jobs/kyma/tools/alpine_net_test.go, prow/jobs/kyma/tools/alpine-net/alpine-net.yaml
- Add job for tools/alpine-net
=> Add job for tools/alpine-net

development/tools/jobs/console/core_test.go, prow/jobs/console/core/core.yaml
- added config for console core to work with prow.
- added tests for jobs
=> Prow migration console core

development/tools/jobs/kyma/environments_test.go, prow/jobs/kyma/components/environments/environments.yaml
- Added presubmit and postsubmit jobs for environments component
- Added test of environments jobs
#192
=> Add presubmit and postsubmit job for environments component

development/tools/jobs/console/core_test.go, development/tools/jobs/tester/tester.go, prow/jobs/console/brokers/brokers.yaml, prow/jobs/console/catalog/catalog.yaml, prow/jobs/console/content/content.yaml, prow/jobs/console/core/core.yaml, prow/jobs/console/instances/instances.yaml, prow/jobs/console/react-components/react-components.yaml, prow/jobs/examples/call-ec/call-ec.yaml, prow/jobs/examples/event-email-service/event-email-service.yaml
- Update all console components with the newest node buildpack
See also #249
=> Prow migration console

prow/scripts/cluster-integration/pr-gke-integration.sh
- Fix bug that caused connector-service-tests to fail
#242
=> GKE integration pipeline: fix connector-service-tests bug

docs/prow/prow-architecture.md
- Added Branch Protector description
#131
=> Add Branch Protector description

development/tools/jobs/kyma/connector_service_test.go, development/tools/jobs/kyma/connector_service_tests_test.go, prow/jobs/kyma/components/connector-service/connector-service.yaml, prow/jobs/kyma/tests/connector-service-tests/connector-service-tests.yaml
- Added jobs for Connector Service and Connector Service Tests
=> Add jobs for Connector Service and Connector Service Tests

development/tools/jobs/kyma/connection_token_handler_test.go, prow/jobs/kyma/components/connection-token-handler/connection-token-handler.yaml
- Added jobs for connection-token-handler component
=> Jobs for connection token handler

development/tools/jobs/kyma/proxy_service_test.go, prow/jobs/kyma/components/proxy-service/proxy-service.yaml
=> Jobs for proxy-service

prow/jobs/kyma/components/connection-token-handler/connection-token-handler.yaml
- Fix typo in job definition for connection-token-handler
=> Fix typo in job definition for connection-token-handler

development/checker/Gopkg.lock, development/checker/Gopkg.toml, prow/cluster/starter.yaml
- Update component versions in starter.yaml
See #247
=> Update component versions

prow/jobs/kyma/tests/ui-api-layer-acceptance-tests/ui-api-layer-acceptance-tests.yaml
- Introduce UI API Layer acceptance tests job
See https://github.com/kyma-project/test-infra/issues/158
=> Introduce UI API Layer acceptance tests job

development/tools/jobs/incubator/varkes/app_connector_client_test.go, development/tools/jobs/incubator/varkes/odata_mock_test.go, development/tools/jobs/incubator/varkes/openapi_mock_test.go, prow/jobs/incubator/varkes/app-connector-client/app-connector-client.yaml, prow/jobs/incubator/varkes/odata-mock/odata-mock.yaml, prow/jobs/incubator/varkes/openapi-mock/openapi-mock.yaml
- Migrate components under [kyma-incubator/varkes](https://github.com/kyma-incubator/varkes) to Prow
See [#82](https://github.com/kyma-incubator/varkes/issues/82)
=> Migrate varkes to Prow

development/tools/jobs/console/lambda_test.go, development/tools/jobs/kyma/kubeless_integration_tests_test.go, development/tools/jobs/kyma/kubeless_tests_test.go, development/tools/jobs/kyma/logging_tests_test.go, development/tools/jobs/kyma/test_logging_monitoring_test.go, prow/jobs/console/lambda/lambda.yaml, prow/jobs/kyma/tests/kubeless-integration/kubeless-integration.yaml, prow/jobs/kyma/tests/kubeless/kubeless.yaml, prow/jobs/kyma/tests/logging/logging.yaml, prow/jobs/kyma/tests/test-logging-monitoring/test-logging-monitoring.yaml
- Migrate kubeless, logging, monitoring and lambda to Prow
Resolves [#358]( https://github.com/kyma-project/console/issues/358) #257 #241 #240 #239
=> Migrate kubeless, logging, monitoring and lambda to Prow

prow/cluster/starter.yaml, prow/config.yaml
- Enable spyglass for easy-access to job details
See #57
=> Add tooling for easy-access to job details

development/tools/jobs/kyma/event_service_test.go, development/tools/jobs/kyma/k8s_dashboard_proxy_test.go, prow/jobs/kyma/components/event-service/event-service.yaml, prow/jobs/kyma/components/k8s-dashboard-proxy/k8s-dashboard-proxy.yaml
- add prow jobs for event-service component
- add prow jobs for k8s-dashboard-proxy component
https://github.com/kyma-project/test-infra/issues/234
=> Add prow jobs for event-service and k8s-dashboard-proxy components

development/tools/jobs/kyma/docs_test.go, development/tools/jobs/kyma/ui_api_layer_acceptance_tests_test.go, development/tools/jobs/tester/tester.go, prow/jobs/kyma/docs/docs.yaml
- Define Kyma docs job
- Add missing `ui-api-layer-acceptance-tests` test
#215
=> Define Kyma docs job

prow/jobs/website/website.yaml
- Add security context for website
=> Add security context for website

development/tools/jobs/kyma/event_bus_test.go, prow/jobs/kyma/components/event-bus/event-bus.yaml
event-bus component build job
`Resolves #234 `.
=> Event Bus component build job

development/tools/jobs/website/website_test.go, development/tools/jobs/website/website_tools_documentation_generator_test.go, prow/config.yaml, prow/jobs/website/tools/documentation-generator/website-tools-documentation-generator.yaml, prow/jobs/website/website.yaml
- Added branch protection for `website` repository
As `website` repository is fully moved to Prow it should be protected by Prow 😄 
=> Add branch protection for website repository

docs/prow/prow-installation-on-forks.md
- Update documentation to mention the needed permissions for Spyglass to display the logs.
See #57
=> Update documentation for bucket permissions

prow/scripts/cluster-integration/create-image.sh
- Adapt test-infra repo to new kyma-installer dir 
#1296
=> Adapt test-infra repo to new kyma-installer dir

development/tools/jobs/kyma/docsbuilder_test.go, prow/jobs/kyma/tools/docsbuilder/docsbuilder.yaml
- Define pipeline for DocsBuilder tool
#215
=> Define pipeline for DocsBuilder tool

development/tools/jobs/incubator/vstudio-extension/vstudio_extension_test.go, prow/jobs/incubator/vstudio-extension/vstudio-extension.yaml
- Migrate VStudio extension to Prow  
See [#1](https://github.com/kyma-incubator/vstudio-extension/issues/1)
=> Migrate vstudio-extension to Prow

prow/config.yaml, prow/jobs/website/website.yaml
- Add Kyma Bot username and email for jobs
Resolves https://github.com/kyma-project/test-infra/issues/156
=> Add Kyma Bot username and email for jobs

prow/config.yaml, prow/jobs/test-infra/test-infra-governance.yaml, prow/jobs/website/website-governance.yaml
- Removed Jenkins from `website` repository
- Sets governance job as required
=> Set governance job as required

development/tools/jobs/kyma/api_controller_test.go, prow/jobs/kyma/components/api-controller/api-controller.yaml
- Pre and postsubmit jobs are create for api-controller
- There are tests for those jobs
=> Migrate api-controller to prow

development/tools/jobs/kyma/istio_kyma_patch_test.go, prow/jobs/kyma/components/istio-kyma-patch/istio-kyma-patch.yaml
- Create pre and post submit jobs for istio-kyma-patch
=> Migrate istio-kyma-patch to prow

development/tools/jobs/kyma/gateway_tests_test.go, prow/jobs/kyma/tests/gateway-tests/gateway-tests.yaml
- Migrate gateway-tests to Prow
Resolves [#2001](https://github.com/kyma-project/kyma/issues/2001)
=> Migrate gateway-tests to Prow

development/tools/jobs/bundles/bundles_test.go, prow/jobs/bundles/bundles.yaml
- Created job for the Bundles repo
=> Add job for Bundles repo

development/tools/jobs/kyma/application_broker_test.go, prow/jobs/kyma/components/application-broker/application-broker.yaml
- updated jobs and tests
* https://github.com/kyma-project/kyma/issues/1819
=> Change REB to AB

development/tools/cmd/diskscollector/README.md, docs/prow/README.md, docs/prow/prow-installation-on-forks.md, prow/README.md
=> Add minor fixes in docs

development/tools/jobs/kyma/configurations_generator_test.go, prow/jobs/kyma/components/configurations-generator/configurations-generator.yaml
- Pre and postsubmit jobs are create for configurations-generator
- There are tests for those jobs
Implements #224
=> Migrate configurations-generator to prow

prow/jobs/kyma/kyma-integration.yaml
- Fixed a typo in a periodic job name
=> Fix periodic job name

development/tools/jobs/kyma/tools/static_users_generator_test.go, prow/jobs/kyma/tools/static-users-generator/static-users-generator.yaml
- Create pre and post submit jobs for static-users-generator
- Create tests for jobs for static-users-generator
#310
=> Migrate static-users-generator to prow

development/tools/jobs/kyma/docs_test.go, prow/jobs/kyma/docs/docs.yaml
- Modifying docs generation yaml
https://github.com/kyma-project/website/issues/126
=> Add extra_ref for docs generation

prow/scripts/governance.sh
- Fix link validation for PRs with deleted files
Resolves #326
=> Fix link validation for PRs with deleted files

development/tools/jobs/kyma/application_registry_test.go, development/tools/jobs/kyma/application_registry_tests_test.go, prow/jobs/kyma/components/application-registry/application-registry.yaml, prow/jobs/kyma/tests/application-registry-tests/application-registry-tests.yaml
- Add  application-registry  component (part of renaming metadata-service)
=> Add application-registry component

prow/plugins.yaml
- Disable ok-to-test for kyma-project and kyma-incubator
See #50
=> Disable ok-to-test

prow/scripts/cluster-integration/delete-image.sh
- Fixed `kyma-gke-integration` job
#166
=> Fix kyma-gke-integration job

prow/config.yaml
=> Fix branch protection on Kyma repository

development/tools/jobs/testinfra/branchprotector_test.go
- Fixed Branch Protector tests
- ...
- ...
=> Fix Branch Protector tests

development/tools/jobs/kyma/installer_test.go, prow/jobs/kyma/components/installer/installer.yaml
- Installer component release job
Closes #194
=> Installer component release job

development/tools/jobs/kyma/failery_test.go, prow/jobs/kyma/tools/failery/failery.yaml
- Add job for failery tool
See https://github.com/kyma-project/kyma/issues/1883
=> Add job for failery tool

development/tools/jobs/community/governance_test.go, development/tools/jobs/testinfra/branchprotector_test.go, prow/config.yaml, prow/jobs/community/community-governance.yaml
=> Disable Jenkins in community repository

development/tools/jobs/kyma/tools/alpine_net_test.go, development/tools/jobs/kyma/tools/ark_plugins_test.go, development/tools/jobs/kyma/tools/etcd_tls_setup_test.go, prow/jobs/kyma/tools/alpine-net/alpine-net.yaml, prow/jobs/kyma/tools/ark-plugins/ark-plugins.yaml, prow/jobs/kyma/tools/etcd-tls-setup/etcd-tls-setup.yaml
- Add release jobs for tools: alppine-net, ark-plugins, etcd-tls-setup
=> Add release jobs for tools: alppine-net, ark-plugins, etcd-tls-setup

prow/config.yaml
- Extended max concurrency to 30
As autoscaling is enabled on the cluster we can allow more jobs.
=> Extend max concurrency to 30

development/tools/jobs/kyma/knative_serving_acceptance_test.go, prow/jobs/kyma/tests/knative-serving-acceptance/knative-serving-acceptance.yaml
- pre and postsubmit jobs for knative-serving-acceptance
Depends on: kyma-project/kyma#1949
=> Create prow jobs for knative-serving-acceptance

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml
- Switch VM instances cleanup periodic job to production configuration
See also #177
=> Switch vm instances cleanup job to production config

development/tools/cmd/diskscollector/main.go, development/tools/pkg/diskscollector/collector.go, development/tools/pkg/diskscollector/collector_test.go
- Improve disk cleaner logs, unify output with other tools
See also #273
=> Improve disks cleaner logs

development/tools/jobs/kyma/xip_patch_test.go, prow/jobs/kyma/components/xip-patch/xip-patch.yaml
- Added prowjob for the new component xip-patch - please check [Add xip patch component #2055
](https://github.com/kyma-project/kyma/pull/2055)
[#1871](https://github.com/kyma-project/kyma/issues/1871)
=> Add prowjob for xip-patch component

docs/prow/offboarding-checklist.md
- Add an offboarding checklist
See #175
=> Add an offboarding checklist

development/tools/jobs/kyma/namespace_controller_test.go, development/tools/jobs/kyma/test_namespace_controller_test.go, prow/jobs/kyma/components/namespace-controller/namespace-controller.yaml, prow/jobs/kyma/tests/test-namespace-controller/test-namespace-controller.yaml
- `environments` component renamed to `namespace-controller`
- `test-environments` component renamed to `test-namespace-controller`
=> Rename environments to namespace-controller

development/tools/jobs/examples/call_ec_test.go, development/tools/jobs/examples/event_email_service_test.go, development/tools/jobs/examples/governance_test.go, development/tools/jobs/examples/http_db_service_test.go, development/tools/jobs/examples/monitoring_custom_metrics_test.go, development/tools/jobs/examples/tests/http_db_service_acceptance_tests_test.go, development/tools/jobs/examples/tracing_test.go, prow/config.yaml, prow/jobs/examples/call-ec/call-ec.yaml, prow/jobs/examples/event-email-service/event-email-service.yaml, prow/jobs/examples/examples-governance.yaml, prow/jobs/examples/http-db-service/http-db-service.yaml, prow/jobs/examples/monitoring-custom-metrics/monitoring-custom-metrics.yaml, prow/jobs/examples/tests/http-db-service-acceptance-tests/http-db-service-acceptance-tests.yaml, prow/jobs/examples/tracing/tracing.yaml
- Reporting enabled for all jobs in examples repository
- `examples` added to list of protected repositories
#419
=> Disable Jenkins for kyma-project/examples repository

development/tools/jobs/kyma/kyma_integration_test.go, development/tools/jobs/tester/tester.go, prow/jobs/kyma/kyma-integration.yaml
`kyma-integration` should be executed always on PR to release branch.
=> Run kyma-integration on PR to release branch

prow/scripts/governance.sh
- Update `milv` to `0.0.7-alpha` version: Add `black-list-internal` and `black-list-external` flags for not checking relative and external links in provided path.
See https://github.com/kyma-project/website/issues/103
=> Update milv image

prow/scripts/library.sh
- Added git configuration to `library.sh`
kyma-project/website#126
=> Add git configuration to library.sh

prow/plugins.yaml
enable temporary trigger plugin for aszecowka repo
=> enable temporary trigger plugin for aszecowka repo

development/tools/jobs/kyma/connection_token_handler_test.go, prow/jobs/kyma/components/connection-token-handler/connection-token-handler.yaml
- Add job for releasing connection-token-handler component
See #383
=> Add job for releasing connection-token-handler

development/tools/jobs/kyma/application_registry_test.go, prow/jobs/kyma/components/application-registry/application-registry.yaml
- Add job for releasing application-registry component
See also #380
=> Add job for releasing application-registry

development/tools/jobs/kyma/application_registry_tests_test.go, prow/jobs/kyma/tests/application-registry-tests/application-registry-tests.yaml
- Add job for releasing application-registry-tests component
See also #385
=> Add job for releasing application-registry-tests

docs/prow/migration-guide-release.md
- Fix typo in migration-guide-release.md file
See also #387
=> Fix typo in migration-guide-release.md file

development/tools/jobs/kyma/logging_tests_test.go, prow/jobs/kyma/tests/logging/logging.yaml
- Release pipeline for Logging
Fixes: https://github.com/kyma-project/kyma/issues/2099
=> Release jobs for Logging

development/tools/jobs/incubator/kymactl/kymactl_test.go, development/tools/jobs/incubator/service-catalog-tester/service_catalog_tester_test.go, development/tools/jobs/incubator/vstudio-extension/vstudio_extension_test.go, development/tools/jobs/testinfra/branchprotector_test.go, docs/prow/kyma-release-process.md, docs/prow/migration-guide-release.md, docs/prow/migration-guide.md, prow/config.yaml, prow/jobs/incubator/kymactl/kymactl.yaml, prow/jobs/incubator/service-catalog-tester/service-catalog-tester.yaml, prow/jobs/incubator/vstudio-extension/vstudio-extension.yaml
- Enabled reporting
- Updated examples in documentation
- Updated tests
- Defined branch protection
#432 
#433 
#434 
#435
=> Enable Prow in kyma-incubator

development/tools/jobs/kyma/application_proxy_test.go, prow/jobs/kyma/components/application-proxy/application-proxy.yaml
- Add job for releasing application-proxy
See also #381
=> Add job for releasing application-proxy

development/tools/jobs/kyma/application_operator_test.go, prow/jobs/kyma/components/application-operator/application-operator.yaml
- Add job for releasing application-operator
See also #379
=> Add job for releasing application-operator

development/tools/jobs/kyma/application_operator_tests_test.go, prow/jobs/kyma/tests/application-operator-tests/application-operator-tests.yaml
- Add job for releasing application-operator-tests
See also #386
=> Add job for releasing application-operator-tests

development/tools/jobs/bundles/governance_test.go, prow/jobs/bundles/bundles-governance.yaml
- Add presubmit and periodic governance jobs for bundles repository.
- Add relevant unit tests.
Resolves #427
=> Add governance jobs for bundles repository

development/tools/jobs/bundles/bundles_test.go, development/tools/jobs/bundles/governance_test.go, development/tools/jobs/community/governance_test.go, development/tools/jobs/console/governance_test.go, development/tools/jobs/examples/governance_test.go, development/tools/jobs/kyma/docs_test.go, development/tools/jobs/kyma/governance_test.go, development/tools/jobs/kyma/ui_api_layer_acceptance_tests_test.go, development/tools/jobs/kyma/ui_api_layer_test.go, development/tools/jobs/tester/tester.go, development/tools/jobs/testinfra/governance_test.go, development/tools/jobs/website/governance_test.go, prow/jobs/kyma/components/ui-api-layer/ui-api-layer.yaml, prow/jobs/kyma/docs/docs.yaml, prow/jobs/kyma/tests/ui-api-layer-acceptance-tests/ui-api-layer-acceptance-tests.yaml
- Release pipelines for ui-api-layer, ui-api-layer-acceptance-tests and docs.
- Update relevant tests for release pipelines.
Resolves #439 
Resolves #440 
Resolves #441
=> Release pipelines for ui-api-layer, ui-api-layer-acceptance-tests and docs

development/tools/jobs/kyma/knative_serving_acceptance_test.go, prow/jobs/kyma/tests/knative-serving-acceptance/knative-serving-acceptance.yaml
=> Add knative-serving-acceptance release jobs

development/tools/jobs/kyma/xip_patch_test.go, prow/jobs/kyma/components/xip-patch/xip-patch.yaml
- Add release job for xip-patch
- Adjust xip-patch tests for release
[#1871](https://github.com/kyma-project/kyma/issues/1871)
=> Define the release job for xip-patch

development/tools/jobs/kyma/event_bus_test.go, development/tools/jobs/kyma/event_service_test.go, development/tools/jobs/kyma/gateway_tests_test.go, development/tools/jobs/kyma/k8s_dashboard_proxy_test.go, development/tools/jobs/kyma/test_event_bus_test.go, prow/jobs/kyma/components/event-bus/event-bus.yaml, prow/jobs/kyma/components/event-service/event-service.yaml, prow/jobs/kyma/components/k8s-dashboard-proxy/k8s-dashboard-proxy.yaml, prow/jobs/kyma/tests/event-bus/test-event-bus.yaml, prow/jobs/kyma/tests/gateway-tests/gateway-tests.yaml
Add prow release jobs and tests for:
- components/event-bus
- components/event-service
- components/k8s-dashboard-proxy
- tests/event-bus
- tests/gateway-tests
https://github.com/kyma-project/test-infra/issues/444
=> Add prow release jobs and tests

prow/scripts/cluster-integration/kyma-gke-integration.sh
- add a timeout on kyma installation on prow
See also [#kyma/2087](https://github.com/kyma-project/kyma/issues/1610)
=> Add timeout on is-installed.sh script

development/tools/jobs/kyma/kyma_artifacts_test.go, prow/jobs/kyma/kyma-artifacts.yaml, prow/plugins.yaml
Prepare to test changelog release functionality
Remove changes after tests!
=> Prepare to test changelog generator

development/tools/jobs/kyma/kyma_artifacts_test.go, prow/jobs/kyma/kyma-artifacts.yaml, prow/plugins.yaml, prow/scripts/build-kyma-artifacts.sh, prow/scripts/changelog-generator.sh
Changelog genererator for releases
=> Add release changelog file generator

development/tools/jobs/kyma/kyma_integration_test.go, prow/config.yaml, prow/jobs/kyma/kyma-integration.yaml, prow/scripts/cluster-integration/kyma-gke-nightly.sh
- New pipeline script for the nightly build
Implements #454
=> Create nighty build in prow

development/tools/Gopkg.lock, development/tools/Gopkg.toml, development/tools/cmd/configuploader/main.go, development/tools/cmd/configuploader/main_test.go, development/tools/cmd/githubrelease/README.md, development/tools/cmd/githubrelease/main.go, development/tools/cmd/secretspopulator/main_test.go, development/tools/pkg/file/file.go, development/tools/pkg/githubrelease/github.go, development/tools/pkg/githubrelease/release.go, development/tools/pkg/githubrelease/storage.go
- Tool for creating a github release
Part of #372
=> Tool for creating a github release

prow/jobs/kyma/kyma-github-release.yaml
- Kyma github release job - fix
=> Kyma github release job - fix

prow/jobs/kyma/kyma-github-release.yaml
=> GitHub release fix

prow/jobs/kyma/kyma-integration.yaml
=> Nightly build branch

development/tools/jobs/kyma/kyma_github-release_test.go, prow/jobs/kyma/kyma-github-release.yaml, prow/plugins.yaml
- Kyma github release job - switch conf to kyma-project
See #372
=> Kyma github release job - switch conf to kyma-project

development/tools/jobs/kyma/kyma_artifacts_test.go, prow/jobs/kyma/kyma-artifacts.yaml
- Enable reporting for kyma-artifacts job
=> Enable reporting for kyma-artifacts job

prow/cluster/resources/monitoring/values.yaml
- Fix a problem leading to empty alerts
=> Fix notifications

prow/scripts/cluster-integration/kyma-gke-nightly.sh
- Add cluster name for nightly build
blocked until stability-checker bump after this PR: https://github.com/kyma-project/kyma/pull/2235
=> Add cluster name for nightly build

prow/cluster/resources/monitoring/templates/prometheus-rule.yaml
- Fix job names for notifications
=> Fix job names for notifications

prow/cluster/resources/monitoring/templates/prometheus-rule.yaml
- Update links on notifications
=> Update links on notifications

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml, prow/scripts/cluster-integration/kyma-gke-upgradeability.sh
- Add upgradeability script and jobs - first phase
- https://github.com/kyma-project/kyma/issues/2259
=> Add upgradeability script and jobs - first phase

prow/images/buildpack-golang/Dockerfile, prow/images/buildpack-golang/Makefile, prow/images/buildpack-golang/README.md
- Updated Go to version `1.11.4`
- Updated Dep to version `0.5.0`
- Introduced new tag for `buildpack-golang` - `go1.11`
Resolves #115
=> Update Go and Dep version in buildpack-golang

development/tools/jobs/kyma/asset_controller_test.go, development/tools/jobs/tester/tester.go, prow/jobs/kyma/components/asset-controller/asset-controller.yaml
- Added job for the new controller - `asset-controller`
kyma-project/kyma#2270
=> Add job for asset-controller

prow/scripts/provision-vm-and-start-kyma.sh
- Use prow folder from the new path
=> Use prow folder from the new path

prow/scripts/cluster-integration/helpers/create-dns-record.sh, prow/scripts/cluster-integration/helpers/delete-dns-record.sh, prow/scripts/cluster-integration/kyma-gke-upgrade.sh
- Fix the DNS record creation/deletion if GKE plans
- https://github.com/kyma-project/test-infra/issues/525
=> Fix the dns record creation/deletion if GKE plans

prow/scripts/cluster-integration/kyma-gke-nightly.sh
=> Stability checker - fix

prow/config.yaml
- Change zone for integration jobs
Kubernetes `1.10.7` is not available in zone `europe-west3-a` anymore.
In zone `europe-west3-b` it is still available:
=> Change zone for integration jobs

development/tools/jobs/incubator/kyma-cli/kyma-cli_test.go, prow/jobs/incubator/kyma-cli/kyma-cli.yaml
We will rename kymactl to kyma-cli. That PR will cover the changes to test-infra
=> renaming kyma-cli

prow/scripts/cluster-integration/helpers/provision-gke-cluster.sh
- GKE cluster version param fix
Closes #536
=> GKE cluster version param fix

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml
- Add regex for the GKE upgrade plan
I've checked that regex against real names extracted from kyma-prow gcp project
- disks: https://regex101.com/r/DZcC7d/1
- clusters: https://regex101.com/r/hKzq53/1
- https://github.com/kyma-project/kyma/issues/2259
=> Add regex for the gke upgrade plan

prow/jobs/kyma/kyma-artifacts.yaml, prow/jobs/kyma/kyma-integration.yaml, prow/plugins.yaml
- Add jobs for testing release on mszostok repo
- https://github.com/kyma-project/kyma/issues/2353
=> Add jobs for testing release on mszostok repo

prow/jobs/kyma/kyma-integration.yaml
- Fix testing release jobs
- https://github.com/kyma-project/kyma/issues/2353
=> Fix testing release jobs

development/tools/pkg/release/github.go, development/tools/pkg/release/mock.go, development/tools/pkg/release/options.go, development/tools/pkg/release/version.go, development/tools/pkg/release/version_test.go
- add tests for version reader
- add comments for exported funcs
=> Github release tool: tests for version reader

development/tools/jobs/kyma/tools/ark_plugins_test.go, prow/jobs/kyma/tools/ark-plugins/ark-plugins.yaml
=> update buildpack image for ark-plugins

prow/config.yaml, prow/jobs/kyma/kyma-artifacts.yaml, prow/jobs/kyma/kyma-integration.yaml, prow/plugins.yaml
- Revert jobs created for testing release process. Test ended with success and those jobs can be removed.
- https://github.com/kyma-project/kyma/issues/2353
=> Revert jobs created for testing release process

prow/scripts/governance.sh
- Create `temp` dir after copy files for checking external links on PRs.
Resolves #551
=> Fix bug with governance.sh

development/custom-image/install-deps-debian.sh, prow/scripts/cluster-integration/helpers/provision-gke-cluster.sh
- Minikube - v0.33.0
- K8S - 1.11.5
=> Upgrade minikube and k8s version

development/tools/jobs/common/common_test.go, prow/jobs/kyma/common/common.yaml
- Add pipeline for common dir in kyma
=> Add pipeline for common dir in kyma

prow/cluster/07-kube-system_poddisruptionbudgets.yaml, prow/cluster/README.md, prow/config.yaml, prow/install-prow.sh
- Add PodDisrutptionBudget to rebalance kube-system pods from nodes during downscale.
- Set max pod age to 5h to make sure, they are garbage collected frequently.
This will fix #467
=> Add PodDisruptionBudgets and set max pod age to 5h

prow/images/buildpack-golang-kubebuilder/Dockerfile, prow/images/buildpack-golang-kubebuilder/Makefile, prow/images/buildpack-golang-kubebuilder/README.md
- Added buildpack-golang-kubebuilder
kyma-project/kyma#2270
=> Add buildpack-golang-kubebuilder

prow/images/buildpack-golang-kubebuilder/Makefile
- Fixed docker push directory for Kubebuilder buildpack
=> Fix docker push directory for Kubebuilder buildpack

development/tools/jobs/kyma/assetstore_controller_manager_test.go, development/tools/jobs/tester/tester.go, prow/jobs/kyma/components/assetstore-controller-manager/assetstore-controller-manager.yaml
- Changed buildpack for Asset Store
kyma-project/kyma#2270
=> Change buildpack for Asset Store

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml, prow/scripts/cluster-integration/kyma-gke-fluentd.sh
- create job which creates cluster with stability-checker and fluentd
=> Add job with flunetd testing cluster

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml
- Granted the `cluster-access` team access to the clusters
=> Grant the cluster-access team access to the clusters

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml
- Removed `developers` teams from accessing clusters
=> Remove developers teams from accessing clusters

development/dns-cleanup.sh, development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml
- Create prowjob for the dnscollector 
Waits for #572
=> Create prowjob for dnscollector

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml
- Add missing preset to dnscollector
=> Add missing presets

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml
=> Disable dry-run for dnscollector

development/tools/jobs/testinfra/prow_addons_ctrl_manager_test.go, docs/prow/presets.md, docs/prow/prow-installation-on-forks.md, prow/cluster/required-secrets.yaml, prow/config.yaml, prow/jobs/test-infra/prow-addons-ctrl-manager.yaml
- Add prow-addons-ctrl job and slack token secret information and checks
-  #466
=> Add prow-addons-ctrl job and slack token secret information and checks

development/tools/jobs/testinfra/prow_addons_ctrl_manager_test.go, prow/jobs/test-infra/prow-addons-ctrl-manager.yaml
- Fix the prow-addons-ctrl-manager.yaml job definition
=> Fix the prow-addons-ctrl-manager.yaml job definition

prow/images/buildpack-golang-kubebuilder/Dockerfile, prow/images/buildpack-golang-kubebuilder/README.md
- Add Kustomize to kubebuilder buildpack
- * #466
=> Add Kustomize to kubebuilder buildpack

prow/scripts/provision-vm-and-start-kyma.sh
- Move custom image check to run only if the `--image` flag was set
=> Fix kyma-integration job 

development/tools/jobs/tester/tester.go, prow/jobs/kyma/components/assetstore-controller-manager/assetstore-controller-manager.yaml, prow/jobs/test-infra/prow-addons-ctrl-manager.yaml
=> Bump kubebuilder version

prow/scripts/governance.sh
- Bump image of milv to `0.0.7-beta`:
- add `basePath` feature: checking relative links with additional prefix and/or suffix.
See also https://github.com/kyma-project/kyma/issues/2243
=> Bump image of milv

prow/scripts/provision-vm-and-start-kyma.sh
=> Revert custom image patch

prow/jobs/kyma/components/assetstore-controller-manager/assetstore-controller-manager.yaml
- Adds missing base_href for assetstore component
=> Add missing base_href for assetstore

prow/jobs/kyma/components/assetstore-controller-manager/assetstore-controller-manager.yaml
- Change preset build for assetstore
=> Change preset build for assetstore component

prow/jobs/kyma/kyma-github-release.yaml
- Change target commit to `release-0.7`
=> Change target commit to 0.7 version

development/prow-addons-ctrl-manager/pkg/slack/reporter.go
- Fix env default values for Slack reporter
=> Fix env default values for slack reporter

prow/cluster/08-prow-addons-ctrl-manager.yaml
- Bump prow addons ctrl manager
=> Bump prow addons ctrl manager

prow/jobs/kyma/kyma-integration.yaml
- Make kyma-gke-upgrade plan as required
=> Make kyma-gke-upgrade plan as required

development/tools/jobs/kyma/asset_upload_service_test.go, prow/jobs/kyma/components/asset-upload-service/asset-upload-service.yaml
- Define Asset Upload Service job
https://github.com/kyma-project/kyma/issues/2653
=> Define Asset Upload Service job

development/tools/jobs/kyma/asset_upload_service_test.go, prow/jobs/kyma/components/asset-upload-service/asset-upload-service.yaml
- Make Asset Upload Service job optional
=> Make Asset Upload Service job optional

prow/jobs/incubator/kyma-cli/kyma-cli.yaml, prow/jobs/incubator/service-catalog-tester/service-catalog-tester.yaml, prow/jobs/incubator/varkes/app-connector-client/app-connector-client.yaml, prow/jobs/incubator/varkes/examples/combined-odata-mock/examples-combined-odata-mock.yaml, prow/jobs/incubator/varkes/examples/combined-openapi-mock/examples-combined-openapi-mock.yaml, prow/jobs/incubator/varkes/examples/odata-mock/examples-odata-mock.yaml, prow/jobs/incubator/varkes/examples/openapi-mock/examples-openapi-mock.yaml, prow/jobs/incubator/varkes/odata-mock/odata-mock.yaml, prow/jobs/incubator/varkes/openapi-mock/openapi-mock.yaml, prow/jobs/incubator/vstudio-extension/vstudio-extension.yaml
- Disable the slack notification for jobs in kyma-incubator
=> Disable the slack notification for jobs in kyma-incubator

development/tools/jobs/kyma/connectivity_certs_controller_test.go, prow/jobs/kyma/components/connectivity-certs-controller/connectivity-certs-controller.yaml
- Add job for a new component Connectivity Certs Controller
=> Add job for Connectivity Certs Controller

development/tools/jobs/kyma/kubeless_images_test.go, prow/jobs/kyma/components/kubeless-images/kubeless-images-nodejs.yaml, prow/jobs/kyma/components/kubeless-images/kubeless-images.yaml
Add prow image pipelines for kubeless images
=> Add kubeless images test

development/tools/jobs/kyma/end_to_end_backup_restore_test_test.go, prow/jobs/kyma/tests/end-to-end/backup-restore-test/backup-restore-test.yaml
- backup restore did not block github PRs
=> enable reporting of backup-restore e2e test

development/tools/jobs/incubator/varkes/examples_kyma_mock_test.go, prow/jobs/incubator/varkes/examples/kyma-mock/examples-kyma-mock.yaml
Added new pipeline for kyma-mock example in varkes repo of kyma-incubator. Project is currently in a PR only, not yet on master
=> new pipeline for kyma-mock

prow/jobs/kyma/components/assetstore-controller-manager/assetstore-controller-manager.yaml
- Added more resources to Asset Store job
See https://github.com/kyma-project/test-infra/issues/645#issuecomment-466311824
=> Add more resources to Asset Store job

prow/config.yaml, prow/scripts/cluster-integration/kyma-gke-end-to-end-test.sh
Solved issue related to the wrong configuration of Ark when Kyma is installed  in the cluster.
=> fix creation of end to end cluster

prow/images/README.md, prow/images/vulnerability-scanner/Dockerfile, prow/images/vulnerability-scanner/Makefile, prow/images/vulnerability-scanner/README.md
- add vulnerability scanner image
#607
=> Add vulnerability scanner image

development/tools/jobs/kyma/vulnerability_scanner_test.go, development/vulnerabilities-scanner.sh, prow/jobs/kyma/kyma-vulnerability-scanner.yaml
=> Vulnerabilities scanner fix

development/tools/jobs/kyma/vulnerability_scanner_test.go, prow/jobs/kyma/kyma-vulnerability-scanner.yaml
- Vulnerabilities scanner job updated schedule
=> Vulnerabilities scanner job updated schedule

prow/images/kyma-cluster-infra/Dockerfile
Related to [#2608](https://github.com/kyma-project/kyma/issues/2608)
=> Add az to kyma-cluster-infra image

CODEOWNERS
- Added kyma-project/developers as code owners of prow/scripts dir
=> Add kyma-project/developers to CODEOWNERS

prow/jobs/kyma/kyma-integration.yaml
- path_alias typo  fix in central job
=> path_alias typo  fix in central job

development/tools/jobs/kyma/monitoring_test.go, prow/jobs/kyma/tests/monitoring/monitoring.yaml
- Renaming folder `tests/test-logging-monitoring` to `tests/monitoring`
Fixes [#697](https://github.com/kyma-project/kyma/issues/697)
=> Rename tests for monitoring

prow/config.yaml
- Add branch-protection for octopus
=> Add branch-protection for octopus

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml, prow/scripts/cluster-integration/kyma-gke-central.sh
- Add kyma-gke-central script
- Add job definition for pre-master-kyma-gke-central
- Add job definition for post-master-kyma-gke-central
=> Add kyma-gke-central script

prow/cluster/required-secrets.yaml
=> Remove load test secret as it isn't used

development/tools/jobs/kyma/end_to_end_kubeless_integration_tests_test.go, prow/jobs/kyma/tests/end-to-end/kubeless-integration/kubeless-integration.yaml
- Restructured folder structure for kubeless integration test folder
Fixes [#697](https://github.com/kyma-project/kyma/issues/697)
=> Restructure kubeless integration test folder

development/tools/jobs/kyma/apiserver_proxy_test_test.go, prow/jobs/kyma/tests/apiserver-proxy-tests/apiserver-proxy-test.yaml
- Added prowjob for new apiserver-proxy test
- Added test to that job
[#1989](https://github.com/kyma-project/kyma/issues/1989)
=> Add prowjob for apiserver-proxy-test

development/tools/jobs/kyma/end_to_end_kubeless_integration_tests_test.go, prow/jobs/kyma/tests/end-to-end/kubeless-integration/kubeless-integration.yaml
- Fix the name of the job and path it should scan for changes
=> Fix the name of the job and path it should scan for changes

development/tools/jobs/kyma/asset_store_integration_test.go, development/tools/jobs/kyma/asset_upload_service_test.go, prow/jobs/kyma/components/asset-upload-service/asset-upload-service.yaml, prow/jobs/kyma/tests/asset-store/asset-store.yaml
- Add Asset Store integration job definition
- Require asset-upload-service build check
https://github.com/kyma-project/kyma/issues/2656
=> Add Asset Store integration job definition

development/tools/jobs/kyma/application_gateway_test.go, prow/jobs/kyma/components/application-gateway/application-gateway.yaml
- Rename Application Proxy to Application Gateway
#2819
=> Rename Application Proxy to Application Gateway

docs/prow/authorization.md, docs/prow/prow-installation-on-forks.md
- adjust service account privileges in the docs
=> Adjust docs about Prow service accounts

development/tools/jobs/kyma/apiserver_proxy_test_test.go, prow/jobs/kyma/tests/apiserver-proxy-tests/apiserver-proxy-test.yaml
- Changed the buildpack in apiserver-proxy test job
=> Change buildpack in apiserver-proxy test job

development/tools/jobs/kyma/cms_controller_manager_test.go, prow/jobs/kyma/components/cms-controller-manager/cms-controller-manager.yaml
- Added job for CMS Controller Manager
The job is optional, as sources are not merged to master branch yet.
kyma-project/kyma#2657
=> Add job for CMS Controller Manager

development/custom-image/install-deps-debian.sh, prow/scripts/cluster-integration/helpers/provision-gke-cluster.sh
See also kyma-project/kyma#2153
=> Upgrade to K8S version 1.12

prow/jobs/kyma/kyma-github-release.yaml
- set targetcommit as environment variable
#620
=> Release variable name

prow/scripts/cluster-integration/helpers/provision-gke-cluster.sh
- Limit cluster IPv4 addresses to /24
=> Limit cluster IPv4 addresses to /24

prow/scripts/cluster-integration/helpers/provision-gke-cluster.sh
=> Limit cluster IPv4 CIDR /19

prow/scripts/cluster-integration/helpers/provision-gke-cluster.sh
- Revert limiting cluster IPv4 to /19
=> Revert limiting cluster IPv4 to /19

prow/jobs/kyma/kyma-integration.yaml, prow/scripts/cluster-integration/helpers/create-network.sh, prow/scripts/cluster-integration/helpers/delete-network.sh, prow/scripts/cluster-integration/helpers/provision-gke-cluster.sh, prow/scripts/cluster-integration/kyma-gke-network-test.sh
- Create network before cluster provisioning
=> Create network before cluster provisioning

prow/scripts/cluster-integration/helpers/create-network-with-subnet.sh, prow/scripts/cluster-integration/helpers/delete-network-with-subnet.sh
=> Remove region from network

prow/scripts/cluster-integration/kyma-gke-upgrade.sh
- Fix project name in gke-upgrade
=> Fix project name in gke-upgrade

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml
- Make backup test run on every Fridays for now
=> Make backup test run on every Fridays for now

development/tools/jobs/kyma/asset_store_integration_test.go, development/tools/jobs/kyma/cms_controller_manager_test.go, prow/jobs/kyma/components/cms-controller-manager/cms-controller-manager.yaml, prow/jobs/kyma/tests/asset-store/asset-store.yaml
- Set CMS and Asset Store Integration Tests as required
=> Set CMS and Asset Store Integration Tests as required

prow/scripts/cluster-integration/kyma-gke-integration.sh, prow/scripts/cluster-integration/kyma-gke-upgrade.sh
- In Kyma 0.9 apiserver-proxy has its own load balancer andd needs to be exposed under different domain name.
=> Create apiserver-proxy domain if it is exposed

prow/scripts/cluster-integration/kyma-gke-central.sh
Followup to #719 with forgotten integration job
=> Set apiserver-proxy domain in central-connector test

development/tools/jobs/kyma/cms_controller_manager_test.go, prow/jobs/kyma/components/cms-controller-manager/cms-controller-manager.yaml, prow/jobs/kyma/kyma-development-artifacts.yaml
- Add release job for CmsControllerManager
=> Add release job for CmsControllerManager

prow/jobs/kyma/tools/load-test/load-test.yaml
- change release preset for load test release to build-release
=> change release preset for load test release to build-release

prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
- Fix network removal for long-lasting clusters
=> Fix network removal for long-lasting clusters

development/tools/jobs/kyma/end_to_end_upgrade_test.go, prow/jobs/kyma/tests/end-to-end/upgrade/upgrade.yaml
- Add prow job for e2e upgrade test
- https://github.com/kyma-project/kyma/issues/3044
=> Add prow job for e2e upgrade test

development/tools/jobs/kyma/end_to_end_upgrade_test.go, prow/jobs/kyma/tests/end-to-end/upgrade/upgrade.yaml
- Change buildpack version for upgrade test prowjob
- https://github.com/kyma-project/kyma/issues/3044
=> Change buildpack version for upgrade test prowjob

development/tools/jobs/kyma/monitoring_test.go, prow/jobs/kyma/tests/monitoring/monitoring.yaml
- Fix logging path along the lines of https://github.com/kyma-project/test-infra/blob/9beb7add05e2d257c19f3eed7b75d4d114053e17/prow/jobs/kyma/tests/monitoring/monitoring.yaml#L51
=> Fix logging path

prow/config.yaml
- Extended grace period to 10 min
=> Extend grace period to 10 min

prow/scripts/cluster-integration/kyma-gke-central.sh, prow/scripts/cluster-integration/kyma-gke-integration.sh, prow/scripts/cluster-integration/kyma-gke-upgrade.sh, prow/scripts/provision-vm-and-start-kyma.sh
- Add INT (interrupt) signal as a trigger for cleanup script
Implement #751
=> Expand trap handling

development/tools/jobs/kyma/application_gateway_tests_test.go, prow/jobs/kyma/tests/application-gateway-tests/application-gateway-tests.yaml
- Add jobs for Application Gateway Tests
=> Add jobs for Application Gateway Tests

prow/jobs/kyma/components/asset-store-controller-manager/asset-store-controller-manager.yaml
- Temporary reverted Asset Store job
=> Temporary revert Asset Store job

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml
=> Change notification channel

development/tools/jobs/kyma/asset_store_controller_manager_test.go, prow/jobs/kyma/components/asset-store-controller-manager/asset-store-controller-manager.yaml
- Remove temporary jobs
https://github.com/kyma-project/kyma/issues/3104
=> Remove temporary jobs for asset-store-controller-manager

docs/prow/prow-installation-on-forks.md
update the embedded url to redirect to install-prow.sh in development folder
update the embedded url to redirect to install-prow.sh in development folder
=> Update the link to install prow.sh

prow/scripts/cluster-integration/kyma-gke-upgrade.sh
Related to [#3044](https://github.com/kyma-project/kyma/issues/3044)
This part is responsible for run upgrade e2e test in all upgrade prow jobs
=> Add e2e upgrade test to the upgrade jobs

prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
- Added dns record for apiserver-proxy IP address
[#3138](https://github.com/kyma-project/kyma/issues/3138)
=> Add dns record for apiserver-proxy ip

prow/scripts/cluster-integration/kyma-aks-long-lasting.sh, prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
- Fixed bug with deleting apiserver dns record on aks-long-lasting cluster
- Added creating apiserver dns record on gke-long-lasting cluster
[#3138](https://github.com/kyma-project/kyma/issues/3138)
=> Fix apiserver dns record

development/tools/jobs/kyma/connection_token_handler_test.go, development/tools/jobs/kyma/connection_token_handler_test_test.go, prow/jobs/kyma/tests/connection-token-handler-tests/connection-token-handler-tests.yaml
- Jobs for Connection Token Handler tests 
https://github.com/kyma-project/kyma/issues/2910
=> Added job for connection token handler tests

development/tools/jobs/kyma/asset_metadata_service_test.go, prow/jobs/kyma/components/asset-metadata-service/asset-metadata-service.yaml
- Add Asset Metadata Service job
See https://github.com/kyma-project/kyma/issues/3231
=> Add Asset Metadata Service job

prow/scripts/build.sh
- Enable releasing from other repos as in the current version, we can only release from kyma-project/kyma.
=> Enable releasing from other repos

prow/scripts/cluster-integration/kyma-gke-central.sh
- Added value for tests of connection token handler
=> Added value to central connector service configmap

development/tools/jobs/testinfra/buildpack_test.go, prow/images/alpine-kubectl/Dockerfile, prow/images/alpine-kubectl/Makefile, prow/images/alpine-kubectl/README.md, prow/jobs/test-infra/buildpack.yaml
- Add new image for in cluster operations
- Add prowjob for the image
- Add tests for prowjob
=> Create new lightweight image for cluster operations

prow/images/alpine-kubectl/Dockerfile
=> Fix source label in kubectl image

docs/prow/prow-installation-on-forks.md, prow/cluster/required-secrets.yaml, prow/config.yaml, prow/scripts/cluster-integration/helpers/generate-cluster-backup-config.sh
- Fix bucket configurations for backup restore test
Fixes #783 and #782
=> Fix backup restore bucket

prow/scripts/cluster-integration/helpers/get-helm-certs.sh, prow/scripts/cluster-integration/helpers/install-kyma.sh, prow/scripts/cluster-integration/kyma-aks-long-lasting.sh, prow/scripts/cluster-integration/kyma-gke-central.sh, prow/scripts/cluster-integration/kyma-gke-end-to-end-test.sh, prow/scripts/cluster-integration/kyma-gke-integration.sh, prow/scripts/cluster-integration/kyma-gke-load-test.sh, prow/scripts/cluster-integration/kyma-gke-long-lasting.sh, prow/scripts/cluster-integration/kyma-gke-upgrade.sh
- Modify all pipelines to retreive Helm client certs from the cluster
https://github.com/kyma-project/kyma/pull/3223
=> Enable TLS in Tiller

prow/scripts/cluster-integration/kyma-gke-upgrade.sh
- Move tiller upgrade to better spot
=> Fix upgrade plan

prow/scripts/cluster-integration/kyma-gke-upgrade.sh
- Modify upgrade plan to use the release version of tiller, rather than the local one
Quickfix for #811
=> Change upgrade pipeline

prow/create-secrets-for-workload-cluster.sh
- Fix variable in workload script
=> Fix variable in workload script

development/tools/jobs/kyma/event_bus_test.go, development/tools/jobs/kyma/test_event_bus_test.go, prow/jobs/kyma/components/event-bus/event-bus.yaml, prow/jobs/kyma/tests/event-bus/test-event-bus.yaml
- Update go and dep versions for the event-bus jobs
=> Update go and dep versions for the event-bus jobs

development/custom-image/create-custom-image.sh, prow/scripts/cluster-integration/helpers/provision-gke-cluster.sh, prow/scripts/provision-vm-and-start-kyma.sh
- Increase disk size and machine-type for Knative
See [#3017](https://github.com/kyma-project/kyma/issues/3017)
=> Increase disk size and machine type for Knative

development/checker/Gopkg.lock, development/checker/Gopkg.toml, prow/cluster/04-branchprotector_cronjob.yaml, prow/cluster/starter.yaml, prow/config.yaml
- Bump Prow images
- Needed for ok-to-test fix
See #403
=> Bump Prow images

prow/config.yaml
added keyring variable to fix issue with nightly builds
- ...
- ...
- ...
fixes https://github.com/kyma-project/kyma/issues/3425
=> added keyring variable to config.yaml

prow/jobs/test-infra/watch-pods.yaml
- Add release 0.9 job for watch-pods
https://github.com/kyma-project/kyma/issues/3330
=> Add release 0.9 job for watch-pods

prow/scripts/cluster-integration/kyma-gke-upgrade.sh
- Fix error handling for testing kyma in upgrade plan
=> Fix error handling for testing kyma in upgrade plan

docs/prow/prow-architecture.md, prow/scripts/build-kyma-development-artifacts.sh
- Add tiller.yaml artifact for on-demand package
=> Add tiller.yaml artifact for on-demand package

prow/jobs/kyma/components/asset-store-controller-manager/asset-store-controller-manager.yaml
- Temporary added more resources to Asset Store job
=> Temporary add more resources to Asset Store jobs

prow/scripts/build.sh
- Fix release for watch-pods
https://github.com/kyma-project/kyma/issues/3330
=> Fix release for watch-pods

prow/scripts/cluster-integration/kyma-gke-upgrade.sh
- Check if TLS is enabled when performing end2end tests
Needed for https://github.com/kyma-project/kyma/pull/3223
=> Enable TLS in end2end tests

prow/scripts/cluster-integration/kyma-gke-upgrade.sh
=> Fix linesplit for end2end test

prow/scripts/cluster-integration/kyma-gke-upgrade.sh
- Fix upgrade plan after introducing tiller TLS
=> Fix upgrade plan after introducing tiller TLS

prow/scripts/build-kyma-artifacts.sh
- Add tiller.yaml artifact in build-kyma-artifacts.sh
=> Add tiller.yaml artifact in build-kyma-artifacts.sh

docs/prow/production-cluster-configuration.md
- Update commit SHA of prow
#403
=> Update commit SHA of prow

prow/config.yaml
- Changing GCP zone to eu west 3a to tackle `code: CodeValueValuesEnum(GCE_STOCKOUT, 1)`
=> Change cluster creation zone to euwest3a

development/tools/jobs/kyma/kyma_integration_test.go, development/tools/pkg/firewallcleaner/cleaner.go, prow/jobs/kyma/kyma-integration.yaml
temporary disable fw cleaner to investigate deletion of nightly/weekly fw rules
- `dryRun=true`
=> temp disable cleaner

development/tools/jobs/kyma/kyma_integration_test.go, development/tools/pkg/firewallcleaner/cleaner.go, prow/jobs/kyma/kyma-integration.yaml
change runtime to 1h temporarily
- `45 */1 * * 1-5`
=> Temp disable fw cleaner

development/tools/jobs/kyma/knative_serving_acceptance_test.go, prow/jobs/kyma/tests/knative-serving/knative-serving.yaml
- folder tests/knative-serving-acceptance does not follow the new rules and has to be renamed to tests/knative-serving
kyma-project/kyma#3498
=> rename knative-serving-acceptance to knative-serving

development/tools/jobs/kyma/apiserver_proxy_test_test.go, development/tools/jobs/kyma/application_broker_test.go, development/tools/jobs/kyma/application_gateway_test.go, development/tools/jobs/kyma/application_gateway_tests_test.go, development/tools/jobs/kyma/application_proxy_test.go, development/tools/jobs/kyma/asset_metadata_service_test.go, development/tools/jobs/kyma/asset_store_controller_manager_test.go, development/tools/jobs/kyma/asset_store_test_test.go, development/tools/jobs/kyma/asset_upload_service_test.go, development/tools/jobs/kyma/cluster_users_test.go, development/tools/jobs/kyma/cms_controller_manager_test.go, development/tools/jobs/kyma/connection_token_handler_test_test.go, development/tools/jobs/kyma/connectivity_certs_controller_test.go, development/tools/jobs/kyma/console_backend_service_test.go, development/tools/jobs/kyma/console_backend_service_test_test.go, development/tools/jobs/kyma/end_to_end_backup_restore_test_test.go, development/tools/jobs/kyma/end_to_end_kubeless_integration_tests_test.go, development/tools/jobs/kyma/end_to_end_upgrade_test.go, development/tools/jobs/kyma/knative_serving_acceptance_test.go, development/tools/jobs/kyma/monitoring_test.go, development/tools/jobs/kyma/stability_checker_test.go, development/tools/jobs/kyma/tools/gcp_broker_provider_test.go, development/tools/jobs/kyma/watch_pods_test.go, development/tools/jobs/tester/tester.go, development/tools/jobs/testinfra/branchprotector_test.go, development/tools/jobs/testinfra/stability_checker_test.go, development/tools/jobs/testinfra/watch_pods_test.go, prow/jobs/kyma/components/application-broker/application-broker.yaml, prow/jobs/kyma/tests/knative-serving/knative-serving.yaml, prow/jobs/test-infra/stability-checker.yaml
- Change base image for application broker job
- https://github.com/kyma-project/kyma/issues/3285
=> Change base image for application broker job

prow/scripts/cluster-integration/kyma-gke-upgrade.sh
- Fix logging for kyma-gke-upgrade.sh
#3320
=> Fix kyma-gke-upgrade.sh

prow/cluster/04-branchprotector_cronjob.yaml, prow/cluster/09-gce-ssd-retain_storageclass.yaml, prow/cluster/10-ghproxy.yaml, prow/cluster/README.md, prow/cluster/starter.yaml, prow/install-prow.sh
=> Add ghproxy

prow/scripts/cluster-integration/kyma-gke-load-test.sh
=> Add missing tls flag

prow/scripts/cluster-integration/kyma-gke-upgrade.sh
- Fix GKE upgrade script - adapt logging
#3320
=> Fix GKE upgrade script

development/tools/jobs/kyma/application_broker_test.go, prow/jobs/kyma/components/application-broker/application-broker.yaml
- Change buildpack for release 1.0 in app broker
=> Change buildpack for release 1.0 in app broker

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml, prow/scripts/cluster-integration/kyma-gke-integration-xip.sh, prow/scripts/cluster-integration/update-kyma-gke-integration.sh
=> Introduce new xip pipeline

development/tools/cmd/enablegithubauth/README.md
- add link to GitHub connector docs in tool which enables it on cluster
=> Add link to Github connector docs

prow/scripts/cluster-integration/kyma-gke-upgrade-xip.sh
=> pipeline fix

prow/scripts/cluster-integration/kyma-gke-upgrade-xip.sh
=> Fix GCP auth

development/tools/jobs/console/add-ons_test.go, prow/jobs/console/add-ons/add-ons.yaml
- Add job and test for add-ons-ui
See also https://github.com/kyma-project/console/issues/751
=> Add job and test for add-ons-ui

prow/scripts/cluster-integration/kyma-gke-upgrade-xip.sh
=> XIP pipeline fix

prow/jobs/kyma/kyma-integration.yaml
In this PR I introduce temporary job to test if implementation proposed by #904 works correctly
=> Introduce temporary job to test jobguard

prow/config.yaml, prow/scripts/cluster-integration/helpers/decrypt.sh, prow/scripts/cluster-integration/helpers/encrypt.sh, prow/scripts/cluster-integration/helpers/get-letsencrypt-cert.sh, prow/scripts/cluster-integration/kyma-aks-long-lasting.sh, prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
- `live` directory for the domain shouldn't exist when the certificate is generated.
- Fixed encryption key preset
To speed up fix, documentation (roles for SA) will be updated in separate PR.
=> Fix logic responsible for generating certificates

prow/jobs/kyma/kyma-integration.yaml, prow/scripts/cluster-integration/kyma-gke-long-lasting-aw-test.sh
- End2end tests for service-catalog
* https://github.com/kyma-project/kyma/issues/3047
=> Add test version of e2e test for service catalog

prow/jobs/kyma/kyma-integration.yaml, prow/scripts/cluster-integration/kyma-gke-long-lasting-aw-test.sh
- End2end tests for service-catalog
* https://github.com/kyma-project/kyma/issues/3047
=> Add test version of e2e test for service catalog - fix

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml
Related to [PR](https://github.com/kyma-project/test-infra/issues/684)
=> Enable cluster notification for slack channel

development/tools/jobs/kyma/kyma_integration_test.go, prow/config.yaml, prow/jobs/kyma/kyma-integration.yaml
- updates regex in kyma-integration for diskcollector to remove additional disks
- adds preset-kyma-keyring for encryption(change is in additional pr awaiting review)
#828
=> Update Regex for disk collector to remove nightly,weekly,central disks

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml
Revert this [PR](https://github.com/kyma-project/test-infra/pull/946)
=> Disable cluster notification for slack channel

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml
- Change repository from origin to fork
Required by https://github.com/kyma-project/kyma/issues/3622
=> Change repo refs in minikube verification 

stability-checker/deploy/chart/stability-checker/values.yaml
- bump stability-checker version - use new image with the #943 changes
#943
=> Bump stability checker version - all logs must be JSON

README.md
=> Fix readme 

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml
- Fix backup-restore cron, now it will be executed `"At 05:00 on every day-of-week from Monday through Friday."`
=> Fix backup-restore cron

prow/jobs/kyma/kyma-integration.yaml
- added flag to enable override
- changed channel name
* https://github.com/kyma-project/kyma/issues/3047
=> Service Catalog nightly job - update

prow/scripts/cluster-integration/kyma-gke-upgrade.sh
- global.domainName is not necessary and is removed
- e2e test is run before testing.sh to get quicker feedback
kyma-project/kyma#3486
=> Cleanup in upgrade script

prow/config.yaml
revert incubator branch protection to status before update
=> make incubator less strict

prow/scripts/cluster-integration/kyma-gke-minio-gateway.sh
- Removed external endpoint configuration from MinIO Gateway job
It needs to be removed as GCS requires more policies for public access, but when communication is handled by MinIO Gateway it works.
=> Remove external endpoint from MinIO Gateway job

development/tools/jobs/kyma/kyma_release_candidate_test.go, prow/jobs/kyma/kyma-release-candidate.yaml, prow/scripts/cluster-integration/helpers/generate-and-export-letsencrypt-TLS-cert.sh, prow/scripts/cluster-integration/helpers/install-kyma.sh, prow/scripts/cluster-integration/kyma-gke-release-candidate.sh, prow/workload-cluster/required-secrets.yaml
As a release improvement, we want to automatically create a cluster after creating RC.
- Added job for RC in 1.1 version
- Added required secret
#925
=> Add job for provisioning RC cluster

development/tools/jobs/website/website_test.go, prow/jobs/website/website.yaml
- Add temporary periodic job for website for publishing website once a hour. 
Issue: https://github.com/kyma-project/website/issues/278
Epic: https://github.com/kyma-project/website/issues/258
=> Add temporary periodic job for website

prow/config.yaml
- Move cluster prow plans to euwest 3b
=> Move cluster prow plans to euwest 3b

development/assetstore-gcp-bucket-cleaner.sh, development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml
- fix failing assetstore-gcp-bucket-cleaner script
=> fix failing assetstore-gcp-bucket-cleaner script

development/assetstore-gcp-bucket-cleaner.sh, development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml
- fix missing dependencies in assetstore-gcp-bucket-cleaner script
=> fix missing dependencies in assetstore-gcp-bucket-cleaner script

development/tools/jobs/cli/cli_test.go, prow/jobs/cli/cli.yaml
- Update the Kyma CLI prow job to build the new repo
Part of kyma-project/kyma#4044
=> Move Kyma CLI prow job to build the new repo

prow/config.yaml
- Added `compass` repository from `kyma-incubator` organization to config.yaml file
[#2](https://github.com/kyma-incubator/compass/issues/2)
=> Add compass repository to prow config

development/tools/jobs/testinfra/branchprotector_test.go, prow/config.yaml
- Add netlify jobs in website branch-protection
=> Add netlify jobs in website branch-protection

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml
=> Remove verification job

development/tools/jobs/kyma/tools/ark_plugins_test.go, development/tools/jobs/kyma/tools/velero_plugins_test.go, prow/jobs/kyma/tools/ark-plugins/ark-plugins.yaml, prow/jobs/kyma/tools/velero-plugins/velero-plugins.yaml
- Change ark plugins to velero plugins
Fixes https://github.com/kyma-project/kyma/issues/3760
Related to: https://github.com/kyma-project/kyma/pull/3783/files
=> Changed ark plugins to velero plugins

performance-tools/performance-cluster/runner.sh
https://github.com/kyma-project/kyma/issues/3521
=> Set default namespace in the kubernetes context

prow/jobs/kyma/tools/velero-plugins/velero-plugins.yaml
- Make velero plugins job optional
=> Make velero plugins job optional

development/tools/jobs/kyma/application_connectivity_validator_test.go, prow/jobs/kyma/components/application-connectivity-validator/application-connectivity-validator.yaml
- Add jobs for Application Connectivity Validator
https://github.com/kyma-project/kyma/issues/1608
=> Add jobs for Application Connectivity Validator

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml, prow/scripts/cluster-integration/helpers/create-config-map.sh, prow/scripts/cluster-integration/kyma-gke-integration.sh
Removed refererence to **kyma-config-cluster.yaml** from **kyma-gke-integration.sh** script.
Changes due to simplified installation procedure.
- Removed refererence to **kyma-config-cluster.yaml** from **kyma-gke-integration.sh** script.
See also #1024
=> Simplify installation gke integration

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml
- Dont run kyma integration builds if only docs were changed
=> Dont run kyma integration builds if only docs were changed

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml, prow/scripts/cluster-integration/kyma-gke-central.sh
- Simplify installation: kyma-gke-central script
#1024 
see also #1037
=> Simplify installation: kyma-gke-central script

development/tools/jobs/kyma/etcd_backup_job_test.go, development/tools/jobs/kyma/etcd_tls_setup_job_test.go, development/tools/jobs/kyma/helm_broker_test.go, development/tools/jobs/kyma/service_binding_usage_controller_test.go, development/tools/jobs/kyma/tools/gcp_broker_provider_test.go, development/tools/jobs/testinfra/stability_checker_test.go, development/tools/jobs/testinfra/watch_pods_test.go, prow/jobs/kyma/components/etcd-backup-job/etcd-backup-job.yaml, prow/jobs/kyma/components/etcd-tls-setup-job/etcd-tls-setup-job.yaml, prow/jobs/kyma/components/helm-broker/helm-broker.yaml, prow/jobs/kyma/components/service-binding-usage-controller/service-binding-usage-controller.yaml, prow/jobs/kyma/tools/gcp-broker-provider/gcp-broker-provider.yaml, prow/jobs/test-infra/stability-checker.yaml, prow/jobs/test-infra/watch-pods.yaml
- Updated gophers components to use the newest buildpack
=> Use newest buildpack for gophers components

stability-checker/Gopkg.lock, watch-pods/Gopkg.lock
- synced dep for gophers project
=> One dep version for gophers components

prow/jobs/kyma/kyma-integration.yaml
Make test gke-upgrade job optional (Fix)
#1024
=> Fix gke upgrade test job optional

stability-checker/deploy/chart/stability-checker/templates/role.yaml
- Fix error in cluster role
Fixes https://github.com/kyma-project/kyma/issues/4183
=> Fix access to cm for stability-checker

development/tools/cmd/dnscollector/main.go
- Fixing DNS cleaner regexp so that is also matches `gke-central`
=> DNS cleaner regexp fix

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml, prow/scripts/cluster-integration/kyma-gke-central.sh, prow/scripts/cluster-integration/kyma-gke-integration.sh, prow/scripts/cluster-integration/kyma-gke-upgrade.sh
- Simplify installation: kyma-gke-upgrade script
#1024
=> Simplify installation: kyma-gke-upgrade script

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml, prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
- change the cluster size
- configure slack channel for notification
Related: #684 
Resolves: #1034
=> Make aks-nightly stable

prow/jobs/kyma/tools/velero-plugins/velero-plugins.yaml
- Removed optional param for velero-plugins job
=> Removed optional param for velero-plugins job

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml
We remove all usages of template file kyma-config-cluster.yaml from Kyma installation process. It requires changes in scripts used by several Prow Jobs.
- Add a Job for testing new version of **install-kyma.sh**.
- #1024 
- https://github.com/kyma-project/kyma/pull/4118
=> Added test job for kyma-load-tests-weekly (install-kyma.sh)

performance-tools/docs/performance-test-execution.md, performance-tools/performance-cluster/job/performance-tests-k6-runner-cronjob.yaml, performance-tools/performance-cluster/runner.sh
* Add yaml for the creation of the kuberbetes job.
* Update performance-test-execution.md
=> k8s cron job for performance tests

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml, prow/scripts/cluster-integration/helpers/install-kyma.sh
- Simplify installation: install-kyma script 
#1024
=> Simplify installation: install-kyma script 

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml
- .Simplify installation: add test kyma-aks-long-lasting job
#1024 
#1057
=> Simplify installation: kyma-aks-long-lasting job

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml
- Simplify installation: add test kyma-gke-end-to-end-test job
#1024
#1052
=> Simplify installation: add test kyma-gke-end-to-end-test job

prow/jobs/kyma/kyma-integration.yaml
=> Fix test aks-nightly

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml, prow/scripts/cluster-integration/kyma-gke-end-to-end-test.sh
- Simplify installation: kyma-gke-end-to-end-test
#1024
=> Simplify installation: kyma-gke-end-to-end-test

prow/jobs/kyma/kyma-integration.yaml, prow/scripts/cluster-integration/kyma-gke-central-xip.sh, prow/scripts/cluster-integration/kyma-gke-integration-xip.sh, prow/scripts/cluster-integration/kyma-gke-upgrade-xip.sh
- remove usage of kyma-config-cluster.yaml in xip jobs
See also #1024
=> Simplify installation: xip scripts

prow/jobs/kyma/kyma-integration.yaml
- ...
- ...
- ...
See also #1024
=> Simplify installation: use proper scripts for xip jobs

prow/scripts/cluster-integration/kyma-gke-upgrade-xip.sh
- add overwrite for `cluster-users.users.adminGroup` for backward compatibility
See also #1024
=> Simplify installation: fix backward compatibility issue

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml
=> Change aks cluster notification channel

development/tools/jobs/kyma/application_connector_tests_test.go, prow/jobs/kyma/tests/application-connector-tests/application-connector-tests.yaml, prow/scripts/cluster-integration/kyma-gke-central.sh
- Added jobs for Application Connector Tests
- Added additional override for Central Connector integration job
=> Add jobs for Application Connector Tests

prow/scripts/cluster-integration/kyma-gke-minio-gateway.sh
- Simplify installation: modify kyma-gke-minio-gateway script
#1024
=> Simplify installation: kyma-gke-minio-gateway script

prow/scripts/cluster-integration/kyma-gke-minio-gateway.sh
- Fix minio-gateway pipeline: secret creation
#1024
=> Fix minio-gateway pipeline

prow/config.yaml
- Enabled protection for `kyma-incubator/marketplaces` repository
=> Enable protection for kyma-incubator/marketplaces repository

prow/jobs/kyma/kyma-integration.yaml
- Fix aks-nightly-nosed test job
#1024
=> Fix aks-nightly-nosed test job

stability-checker/README.md, watch-pods/README.md
- Provide documentation about prerequisites for gophers components
=> Provide documentation about prerequisites

prow/jobs/kyma/kyma-integration.yaml
- Bump azure-cli version
#1024
=> Bump azure-cli version in AKS test pipeline

prow/scripts/cluster-integration/README.md, prow/scripts/cluster-integration/helpers/generate-cluster-backup-config.sh
- Upgrade Ark to Velero
Fixes https://github.com/kyma-project/kyma/issues/3760
=> Upgrade Ark to Velero

prow/images/kyma-cluster-infra/Dockerfile
- Bump azure-cli version
#1024
=> Bump azure-cli version

prow/scripts/cluster-integration/kyma-gke-upgrade-xip.sh, prow/scripts/cluster-integration/kyma-gke-upgrade.sh
- testing bundles for upgrade are injected in the script
=> Inject testing bundles for upgrade

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml, prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
- Simplify installation: kyma-aks-long-lasting
#1024
=> Simplify installation: kyma-aks-long-lasting

prow/scripts/cluster-integration/kyma-gke-upgrade-xip.sh, prow/scripts/cluster-integration/kyma-gke-upgrade.sh
Reverts kyma-project/test-infra#1072
=> Revert Inject testing bundles for upgrade

prow/scripts/cluster-integration/kyma-gke-release-candidate.sh
- Simplify installation: modify kyma-gke-release-candidate.sh
#1024
=> Simplify installation: modify kyma-gke-release-candidate.sh

prow/jobs/kyma/kyma-integration.yaml
Add job for testing the upgrade after AC migration to Istio.
- Add temporary test job
https://github.com/kyma-project/kyma/issues/1608
=> Add job for testing upgrade after AC migration to Istio

development/tools/cmd/jobguard/run.sh
- Extract the JOB_NAME_PATTERN param to environment variable
- #978
=> Extract the JOB_NAME_PATTERN param to environment variable

prow/config.yaml
- Add new github bot account for the job guard integration
- https://github.com/kyma-project/test-infra/issues/978
=> Add new github bot account for the job guard integration

development/assetstore-gcp-bucket-cleaner.sh
- fix assetstore-gcp-bucket-cleaner
=> fix assetstore-gcp-bucket-cleaner

development/assetstore-gcp-bucket-cleaner.sh, development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml
- Refactor assetstore gcp bucket cleaner
=> Refactor assetstore gcp bucket cleaner

development/tools/cmd/githubrelease/README.md, development/tools/cmd/githubrelease/main.go, development/tools/pkg/release/release_test.go, docs/prow/prow-architecture.md, prow/scripts/build-kyma-artifacts.sh, prow/scripts/build-kyma-development-artifacts.sh
- Remove references to the "kyma-config-cluster.yaml" file in test-infra
#1096 https://github.com/kyma-project/kyma/issues/4329
=> Remove cluster config template in test-infra

development/custom-image/install-deps-debian.sh
- Undo fluentd installation on minikube as it is impacting kyma tests and troubleshooting capabilities.
=> Undo fluentd installation

stability-checker/deploy/chart/stability-checker/templates/role.yaml, stability-checker/local_helm_install.sh, stability-checker/local_minikube_build.sh
- Fixed roles for stability checker
=> Fix roles for stability checker

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml
- .enable pre-master-kyma-gke-minio-gateway job
=> Enable pre-master-kyma-gke-minio-gateway job

prow/images/bootstrap/Dockerfile, prow/images/bootstrap/README.md
- Added `gettext` to bootstrap image
kyma-project/kyma#4130
=> Add gettext to bootstrap image

prow/scripts/cluster-integration/kyma-gke-central-xip.sh, prow/scripts/cluster-integration/kyma-gke-central.sh, prow/scripts/cluster-integration/kyma-gke-integration-xip.sh, prow/scripts/cluster-integration/kyma-gke-integration.sh, prow/scripts/cluster-integration/kyma-gke-minio-gateway.sh, prow/scripts/cluster-integration/kyma-gke-upgrade-xip.sh, prow/scripts/cluster-integration/kyma-gke-upgrade.sh, prow/scripts/provision-vm-and-start-kyma.sh
- Temporarily disable the Job Guard
=> Temporarily disable the Job Guard

development/tools/cmd/jobguard/run.sh, prow/scripts/cluster-integration/kyma-gke-central-xip.sh, prow/scripts/cluster-integration/kyma-gke-central.sh, prow/scripts/cluster-integration/kyma-gke-integration-xip.sh, prow/scripts/cluster-integration/kyma-gke-integration.sh, prow/scripts/cluster-integration/kyma-gke-minio-gateway.sh, prow/scripts/cluster-integration/kyma-gke-upgrade-xip.sh, prow/scripts/cluster-integration/kyma-gke-upgrade.sh, prow/scripts/provision-vm-and-start-kyma.sh
- Reenable the job guard, 
- fix the test infra path, 
- fix the GitHub token name
=> Reenable the job guard, fix the test infra path, fix the github token name

development/tools/jobs/incubator/marketplaces/marketplaces_test.go, development/tools/jobs/tester/tester.go, development/tools/jobs/testinfra/branchprotector_test.go, prow/config.yaml, prow/jobs/incubator/marketplaces/marketplaces.yaml
- Added Marketplaces jobs
- Cleanup of branch protector configuration
kyma-project/kyma#4130
=> Add Marketplaces jobs

prow/jobs/kyma/kyma-integration.yaml, prow/jobs/kyma/tests/application-connector-tests/application-connector-tests.yaml, prow/scripts/cluster-integration/helpers/cleanup-cluster.sh, prow/scripts/cluster-integration/helpers/create-cluster.sh, prow/scripts/cluster-integration/helpers/install-kyma.sh, prow/scripts/cluster-integration/kyma-gke-long-lasting.sh, prow/scripts/cluster-integration/kyma-gke-minio-gateway.sh, prow/scripts/cluster-integration/kyma-gke-release-candidate.sh
- Remove remaining REMOTEENV_IPS
- Remove migration test job
https://github.com/kyma-project/kyma/issues/1608
=> Cleanup jobs after Istio migration

development/tools/jobs/incubator/compass/connector_test.go, prow/jobs/incubator/compass/components/connector/connector.yaml
- Add job for compass connector component
=> Add job for compass connector component

development/tools/jobs/cli/cli_test.go, prow/config.yaml, prow/jobs/cli/cli.yaml
- Add kyma cli release jobs
See https://github.com/kyma-project/kyma/issues/4045
=> Add kyma cli release jobs

prow/jobs/kyma/kyma-integration.yaml
- Added MinIO Gateway job to Release 1.2
=> Add MinIO Gateway job to Release 1.2

development/tools/jobs/testinfra/branchprotector_test.go, prow/config.yaml
- Added MinIO Gateway job to branch protector for Release 1.2
=> Add MinIO Gateway job to branch protector for Release 1.2

development/tools/jobs/testinfra/branchprotector_test.go, prow/config.yaml, prow/jobs/kyma/kyma-integration.yaml
- cherry-pick miniO release job
=> Cherry pick minio job

prow/jobs/kyma/kyma-integration.yaml
- moving test job to the new cluster
=> New Prow workload cluster

prow/config.yaml
- Add GITHUB_TOKEN environment variable
See kyma-project/kyma#4045
=> Add GITHUB_TOKEN environment variable

prow/config.yaml, prow/jobs/kyma/kyma-integration.yaml
=> Prow workloads

prow/jobs/kyma/kyma-integration.yaml, prow/scripts/cluster-integration/kyma-gke-central-xip.sh, prow/scripts/cluster-integration/kyma-gke-integration-xip.sh, prow/scripts/cluster-integration/kyma-gke-upgrade-xip.sh
- Updating XIP job configuration (installation simplification)
https://github.com/kyma-project/test-infra/issues/362
=> update and retest xip jobs

prow/jobs/incubator/marketplaces/marketplaces.yaml
=> Fix bootstrap image in Marketplaces governance job

development/tools/jobs/incubator/marketplaces/marketplaces_test.go, prow/jobs/incubator/marketplaces/marketplaces.yaml, prow/scripts/library.sh
- Fixed governance job
- Fixed docker authentication
=> Fix governance job for Marketplaces repository

prow/scripts/library.sh
=> Fix docker in docker

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml, prow/scripts/cluster-integration/kyma-gke-minio-gateway-migration.sh, prow/scripts/cluster-integration/kyma-gke-minio-gateway.sh
Create an automated test for migrating Minio from persistence to gateway mode
- Create an automated test for migrating Minio from persistence to gateway mode
See also: kyma-project/kyma#4374
=> Create test for migrating Minio from persistence to gateway mode

prow/scripts/cluster-integration/kyma-gke-minio-gateway-migration.sh
- Fix invalid base64 flag
See also: kyma-project/kyma#4374
=> Fix invalid base64 flag

prow/scripts/cluster-integration/kyma-gke-minio-gateway-migration.sh, prow/scripts/cluster-integration/kyma-gke-minio-gateway.sh
- Change COMMIN_NAME for kyma-gke-minio-gateway-migration
=> Change COMMIN_NAME for kyma-gke-minio-gateway-migration

prow/scripts/cluster-integration/kyma-gke-upgrade.sh
=> Add testingbundles operations to upgrade plan

prow/scripts/cluster-integration/kyma-gke-minio-gateway-migration.sh, prow/scripts/cluster-integration/kyma-gke-minio-gateway.sh
=> Fix migration test job

prow/scripts/cluster-integration/kyma-gke-minio-gateway-migration.sh
- Update minIO GCS migration script
=> Update minIO GCS migration script

development/tools/jobs/kyma/iam-kubeconfig-service_test.go, prow/jobs/kyma/components/iam-kubeconfig-service/iam-kubeconfig-service.yaml
- Job for new component (iam-kubeconfig-service renamed from configurations-generator)
see https://github.com/kyma-project/kyma/issues/4438
=> Add optional job for iam-kubeconfig-service

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml
- Add backup test presubmit job
See https://github.com/kyma-project/kyma/issues/4500
=> Add backup test presubmit job

prow/scripts/cluster-integration/kyma-gke-upgrade.sh
=> Add testingbundles operations to upgrade plan (#1145)

development/tools/jobs/kyma/dex_static_user_configurer_test.go, prow/jobs/kyma/components/dex-static-user-configurer/dex-static-user-configurer.yaml
- ...
- ...
- ...
Fix for https://github.com/kyma-project/kyma/issues/4439
=> Set dex-static-user-configurer to be optional

development/tools/jobs/kyma/integration_dex_test.go, prow/jobs/kyma/tests/dex/dex.yaml
- Add new pipeline for renamed test
Implements https://github.com/kyma-project/kyma/issues/4440
=> Add pipelines for renamed dex tests

prow/jobs/kyma/tests/integration/dex/dex-integration.yaml
- Remove `optional: true`
Implements https://github.com/kyma-project/kyma/issues/4440
=> Remove optional flag from integration dex tests

prow/jobs/kyma/kyma-integration.yaml
=> fix periodic job

development/tools/jobs/kyma/development_artifacts_test.go, development/tools/jobs/kyma/kyma_operator_test.go, prow/jobs/kyma/components/kyma-operator/kyma-operator.yaml, prow/jobs/kyma/kyma-development-artifacts.yaml
- Add optiona job for kyma-operator
see kyma-project/kyma#4437
=> Add optiona job for kyma-operator

prow/jobs/kyma/components/dex-static-user-configurer/dex-static-user-configurer.yaml
=> Remove optional flag from dex component

development/tools/jobs/kyma/gateway_test.go, prow/jobs/kyma/tests/gateway/gateway-tests.yaml
- Rename the gateway-tests to gateway.
https://github.com/kyma-project/kyma/issues/3023
=> Rename gateway-tests to gateway

prow/scripts/build-kyma-development-artifacts.sh
- Kyma-operator development artifatcs update
see kyma-project/kyma#4437
=> Kyma-operator development artifatcs update

prow/jobs/kyma/kyma-integration.yaml
- disable slack reports
- add extra refs to XIP periodic job
=> Periodic xip

prow/jobs/kyma/kyma-integration.yaml
=> add missing variable

prow/scripts/cluster-integration/kyma-gke-integration.sh
New `--concurrency` flag has been introduced in kyma-project/kyma#4596. In this PR it is used in gke-integration job.
=> Use --concurrency from testing.sh in gke-integration

development/tools/jobs/kyma/application_connectivity_certs_setup_job_test.go, prow/jobs/kyma/components/application-connectivity-certs-setup-job/application-connectivity-certs-setup-job.yaml
- Add job for Application Connectivity Certs Setup Job
https://github.com/kyma-project/kyma/issues/4375
=> Add job for Application Connectivity Cert Setup Job

prow/scripts/cluster-integration/kyma-gke-integration.sh
Reverts kyma-project/test-infra#1161
=> Revert "Use --concurrency from testing.sh in gke-integration"

development/tools/jobs/kyma/development_artifacts_test.go, prow/jobs/kyma/kyma-development-artifacts.yaml, prow/scripts/build-kyma-development-artifacts.sh
- remove installer from  development artifatcs job
see kyma-project/kyma#4437
=> remove installer from  development artifatcs job

prow/scripts/cluster-integration/kyma-gke-central.sh, prow/scripts/cluster-integration/kyma-gke-integration.sh
-revert XIP implementation https://github.com/kyma-project/test-infra/pull/1180
=> Revert XIP implementation

development/tools/jobs/kyma/integration_cluster_users_test.go, prow/jobs/kyma/tests/integration/cluster-users/cluster-users-integration.yaml
- Create new optional job
Implements https://github.com/kyma-project/kyma/issues/4443
=> Create new jobs for cluster-user tests

prow/jobs/kyma/kyma-integration.yaml
- Update periodic job configuration: remove branches, add base_ref
=> Remove branches, add base_ref

prow/scripts/cluster-integration/kyma-gke-integration.sh
Reverts kyma-project/test-infra#1205
=> Revert "Revert "Use --concurrency from testing.sh in gke-integration""

prow/jobs/incubator/compass/compass-integration.yaml
- Add compass integration job
https://github.com/kyma-project/kyma/issues/4685
=> Add test compass integration job

development/tools/jobs/kyma/test_integration_event_service_test.go, prow/jobs/kyma/tests/integration/event-service/test-event-service.yaml
- Rename tests/gateway to tests/integration/event-service
kyma-project/kyma#3023
=> Rename tests/gateway to tests/integration/event-service

prow/jobs/kyma/kyma-integration.yaml
- Added envs with repo owner and repo name to job
=> Fix kyma-compass-integration-periodic job

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml
- Changed test infra extra_ref for testing purposes
=> Change extra_refs for compass periodic job

prow/jobs/incubator/compass/compass-integration.yaml, prow/scripts/provision-vm-compass.sh
- Add extra ref to compass integration job
kyma-project/kyma#4685
=> Add extra ref to compass integration job

prow/jobs/kyma/kyma-integration.yaml
- Disabled slack notifications for compass periodic job
=> Disable slack notifications for compass periodic job

prow/scripts/cluster-integration/kyma-gke-upgrade-xip.sh, prow/scripts/cluster-integration/kyma-gke-upgrade.sh
- remove redundant overrides
see #1090
=> remove redundant overrides

prow/jobs/kyma/kyma-integration.yaml
- Added preset-build-master to compass periodic job
=> Add build-master preset to compass periodic job

prow/scripts/library.sh
- Removed readonly from licence puller path
=> Remove readonly from variable

prow/jobs/incubator/compass/compass-integration.yaml, prow/scripts/provision-vm-compass.sh
- Change CLI repo reference to test compatibility with linux
kyma-project/kyma#4685
=> Add compass integration jobs

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml
- Disable notifications sent to #c4core-kyma-gopher-pr
=> disable notifications

development/tools/jobs/incubator/compass/runtime-agent_test.go, prow/jobs/incubator/compass/components/runtime-agent/runtime-agent.yaml
- Job for building compass runtime-agent added
=> Job for runtime-agent added

development/tools/jobs/console/compass_test.go, prow/jobs/console/compass/compass.yaml
- Add Prow job
- Add tests
Resolves [#958](https://app.zenhub.com/workspaces/kyma---all-repositories-5b6d5985084045741e744dea/issues/kyma-project/console/958)
[console](https://github.com/kyma-project/console/pull/1046)
=> CI build pipeline for Compass UI

prow/jobs/incubator/compass/compass-integration.yaml, prow/jobs/kyma/kyma-integration.yaml
- Added additional necessary labels to compass periodic job
=> Add additional labels to compass job

prow/jobs/incubator/compass/compass-integration.yaml, prow/jobs/kyma/kyma-integration.yaml
- Added necessary labels for the Compass periodic job
=> Add additional labels for the Compass periodic job

prow/jobs/kyma/kyma-github-release.yaml
- release-target set to commit from 1.3.0 branch
* https://github.com/kyma-project/kyma/issues/4447
=> Fix release target for release 1.3

prow/config.yaml
- Create new service account for knative testing
=> sa necessary for knative testing

development/tools/jobs/incubator/compass/schema-migrator_test.go, development/tools/jobs/tester/tester.go, prow/jobs/incubator/compass/components/schema-migrator/schema-migrator.yaml
- Add compass schema-migrator component build job
kyma-incubator/compass#81
=> Add compass schema-migrator component build job

prow/jobs/kyma/components/compass-runtime-agent/compass-runtime-agent.yaml
- Make Compass Runtime Job required
=> Make Compass Runtime Job required

development/tools/jobs/kyma/knative_build_acceptance_test.go, prow/jobs/kyma/tests/knative-build/knative-build.yaml
Prow job for build component
https://github.com/kyma-project/kyma/issues/4496
=> Add prow job for build component

prow/jobs/kyma/tests/knative-build/knative-build.yaml
- Set pipeline to `optional` during development to not mess up other peoples PRs
- ...
- ...
=> Fix broken job

development/tools/jobs/kyma/end_to_end_external_solution_integration_test.go, prow/jobs/kyma/tests/end-to-end/external-solution-integration/external-solution-integration.yaml
- Add job for `tests/end-to-end/external-solution-integration`
=> Add job for e2e external-solution-integration

development/tools/jobs/kyma/end_to_end_external_solution_integration_test.go, prow/jobs/kyma/tests/end-to-end/external-solution-integration/external-solution-integration.yaml
- Use latest buildpack-golang in e2e test job
=> Update e2e test buildpack

development/tools/jobs/kyma/helm_broker_test.go, prow/jobs/kyma/components/helm-broker/helm-broker.yaml
- Helm-Broker build needs a buildpack with kubebuilder because of integration-test added in https://github.com/kyma-project/kyma/pull/4951
related: https://github.com/kyma-project/kyma/issues/4485
=> Use buildpack with kubebuilder for helm-broker

prow/jobs/incubator/compass/compass-integration.yaml
- Added presubmit job for testing purposes
[#146](https://github.com/kyma-incubator/compass/issues/146)
=> Add compass job for testing purposes

development/tools/jobs/kyma/knative_function_controller_test.go, prow/jobs/kyma/components/knative-function-controller/knative-function-controller.yaml
Prow job for Knative Function Controller component
kyma-project/kyma#4803
**Related Epic**
kyma-project/console#804
=> Prow job for Function Controller component

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml, prow/scripts/cluster-integration/kyma-gke-backup-test.sh
- Improve the backup tests naming
See https://github.com/kyma-project/kyma/issues/4836
=> Improve the backup tests naming

development/tools/jobs/cli/cli_integration_test.go, prow/jobs/cli/cli-integration.yaml, prow/scripts/provision-vm-cli.sh
- Add Kyma CLI integration job
See https://github.com/kyma-project/kyma/issues/4048
=> Add Kyma CLI integration job

prow/images/buildpack-node/Dockerfile
- add yarn to node buildpack so that it can be used in https://github.com/kyma-incubator/documentation-component/pull/17 and https://github.com/kyma-incubator/documentation-component/issues/13
Resolves https://github.com/kyma-project/test-infra/issues/1281
=> Add yarn to node buildpack

prow/jobs/incubator/gcp-service-broker/gcp-service-broker.yaml
- added job definition for gcp-service-broker
* https://github.com/kyma-project/bundles/issues/94
=> Job definition for gcp-service-broker

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml, prow/scripts/cluster-integration/kyma-gke-backup-test.sh
- Add missing env vars for backup nightly
See #4836
=> Add missing env vars for backup nightly

development/tools/jobs/incubator/gcp-service-broker/gcp_service_broker_test.go, development/tools/jobs/testinfra/branchprotector_test.go, prow/config.yaml, prow/jobs/incubator/gcp-service-broker/gcp-service-broker.yaml
- added tests
* https://github.com/kyma-project/bundles/issues/94
=> Add tests for GCP service broker

prow/jobs/kyma/kyma-compass-integration.yaml
- Change extra refs in on-demand compass periodic job test from temporary values
kyma-incubator/compass#146
=> Fix compass periodic job refs

stability-checker/deploy/chart/stability-checker/templates/role.yaml
- add ClusterAddonsConfiguration RBAC for testing sh script
Related: https://github.com/kyma-project/kyma/issues/4430
=> Add ClusterAddonsConfiguration RBAC for testing.sh script

prow/scripts/provision-vm-cli.sh
- Add kyma test command to the integration test
See https://github.com/kyma-project/kyma/issues/4048
=> Add kyma test command to the CLI integration test

stability-checker/deploy/chart/stability-checker/templates/role.yaml
- add "get clusteraddonsconfiguration" permission for stability checker role
=> Add get clusteraddonsconfigurations permission for stability checker

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml
- Add backup test release job
See #612
=> Add backup test release job

prow/jobs/kyma/tests/compass-runtime-agent/compass-runtime-agent-test.yaml
- Make Compass Runtime Agent Tests job required
[#4926](https://github.com/kyma-project/kyma/issues/4926)
=> Make Compass Runtime Agent Tests job required

prow/scripts/cluster-integration/kyma-gke-upgrade.sh, stability-checker/deploy/chart/stability-checker/templates/role.yaml
- Aligned stability-checker role
- Changed injectTestingBundles function to deprecated
=> Fixes after renaming bundles to addons

development/tools/jobs/kyma/cms_services_test.go, prow/jobs/kyma/components/cms-services/cms-services.yaml
- Added job for CMS Services
kyma-project/kyma#4960
=> Add job fo CMS Services

prow/images/buildpack-golang/Dockerfile, prow/images/buildpack-golang/Makefile, prow/images/buildpack-golang/README.md
=> Bump Golang and Dep in golang buildpack

development/tools/jobs/kyma/cms_services_test.go, development/tools/jobs/tester/tester.go, prow/jobs/kyma/components/cms-services/cms-services.yaml
=> Change go version in cms-services

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml
- europe-west4-a is not available for creating new clusters so I am changing it temporarily to europe-west4-c
=> Implement workaround

prow/scripts/provision-vm-compass.sh
- Resizing VM instance so that it consumes less resources.
All the VMs are oversized
Suggested settings from GCP
=> Compass Integration adjust VM settings

prow/scripts/provision-vm-compass.sh
=> Adjust compass integration vm settings

prow/scripts/cluster-integration/kyma-gke-backup-test.sh
- Change backup namespace
See https://github.com/kyma-project/kyma/issues/4970
=> Change backup namespace

development/tools/jobs/incubator/podpreset-crd/podpreset_crd_test.go, development/tools/jobs/testinfra/branchprotector_test.go, prow/config.yaml, prow/jobs/incubator/podpreset-crd/podpreset-crd.yaml
- added job for podpreset
- ...
- ...
https://github.com/kyma-project/kyma/issues/3235
=> Add job for podpreset

prow/scripts/provision-vm-compass.sh
- Revert changes to VM settings due to failing job
=> Revert "adjust VM settings (#1311)"

development/tools/jobs/incubator/podpreset-crd/podpreset_crd_test.go, prow/jobs/incubator/podpreset-crd/podpreset-crd.yaml
https://github.com/kyma-project/kyma/issues/3235
=> Fix podpreset job

development/tools/jobs/kyma/asset_metadata_service_test.go, development/tools/jobs/kyma/cms_services_test.go, prow/jobs/kyma/components/asset-metadata-service/asset-metadata-service.yaml, prow/jobs/kyma/components/cms-services/cms-services.yaml, prow/jobs/kyma/kyma-integration.yaml
- Marked jobs as required- ...
=> Mark jobs as required

development/tools/jobs/kyma/integration_gateway_test.go, prow/jobs/kyma/tests/integration/gateway/gateway-integration.yaml
- Fix integration-gateway tests release job
=> Fix integration-gateway tests release job

prow/scripts/cluster-integration/kyma-gke-backup-test.sh
=> Fix backup test

prow/scripts/cluster-integration/kyma-gke-backup-test.sh
=> Fix backup test (#1327) for release-1.4

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml
- Run central connector plan on changes in e2e tests
=> Run central connector plan on changes in e2e tests

prow/scripts/cluster-integration/kyma-gke-backup-test.sh
=> Fix backup release job

development/tools/jobs/cli/cli_integration_test.go, prow/jobs/cli/cli-integration.yaml
- Run CLI integration post-submit only on master
=> Run CLI integration post-submit only on master

prow/scripts/cluster-integration/kyma-gke-backup-test.sh
=> Fix backup release job (#1331)

development/tools/cmd/dnscollector/main.go, development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml
- Add backup cluster to cleanup regexes
=> Add backup cluster to cleanup regexes

prow/jobs/kyma/kyma-vulnerability-scanner.yaml
Job config was missing workspace mapping
- add workspace mapping to job config
=> fix workspace mapping for job

prow/jobs/helm-broker/helm-broker.yaml
=> Update helm-broker job

development/tools/jobs/testinfra/buildpack_test.go, prow/images/buildpack-golang-kubebuilder2/Dockerfile, prow/images/buildpack-golang-kubebuilder2/Makefile, prow/images/buildpack-golang-kubebuilder2/README.md, prow/jobs/test-infra/buildpack.yaml
- Add new buildpack
- Add job for buildpack
=> Create new buildpack for kubebuilder2.0

development/tools/jobs/kyma/helm_broker_test.go, prow/jobs/kyma/components/helm-broker/helm-broker-deprecated.yaml
Related [#5219](https://github.com/kyma-project/kyma/issues/5219)
=> Restore kyma component helm-broker job

prow/images/buildpack-golang-kubebuilder2/README.md
=> Trigger test for kubebuilder2 buildpack

development/tools/jobs/kyma/kyma_compass_integration_test.go, prow/jobs/kyma/kyma-compass-integration.yaml, prow/scripts/cluster-integration/kyma-gke-compass-integration.sh
- Run `kyma-gke-compass-integration` job on every PR if Compass resources changed
- Make `kyma-gke-compass-integration` required on PRs
- Delete periodic `kyma-gke-compass-integration` job
- Add postsubmit `kyma-gke-compass-integration` job running after every merge
See the issue #1335
=> Adjust kyma-compass-integration job

development/tools/jobs/kyma/kyma_compass_integration_test.go, prow/jobs/kyma/kyma-compass-integration.yaml
- Change test_infra_ref in kyma-gke-compass-integration job
See the issue #1335
=> Change test_infra_ref in kyma-gke-compass-integration job

prow/scripts/cluster-integration/kyma-gke-upgrade.sh
- Removed deprecated function after 1.4 release
=> Remove deprecated function

prow/scripts/provision-vm-compass.sh
- Use makefile instead of building cli directly
=> Fix compass integration script

prow/scripts/build-kyma-artifacts.sh, prow/scripts/build-kyma-development-artifacts.sh, prow/scripts/provision-vm-compass.sh
- Modifies `build-kyma-artifacts.sh` and `build-kyma-development-artifacts.sh` to also copy compass and compass-runtime-agent related installer artifacts
kyma-project/kyma#5243
=> Copy compass artifacts

development/tools/jobs/kyma/function_controller_test.go, prow/jobs/kyma/components/function-controller/function-controller.yaml
- Currently the PR: https://github.com/kyma-project/kyma/pull/5121 fails as the path has been changed.
https://github.com/kyma-project/kyma/issues/4803
https://github.com/kyma-project/kyma/pull/5121
=> Rename function controller job

prow/scripts/cluster-integration/kyma-gke-compass-integration.sh
- Fix overrides used in root `application-connector` and `core` charts in `kyma-gke-compass-integration` pipeline
See the issue #1335
=> Fix overrides in kyma-gke-compass-integration pipeline

prow/jobs/kyma/kyma-integration.yaml
=> Fix scanners

development/tools/Gopkg.lock, development/tools/Gopkg.toml, development/tools/before-commit.sh, stability-checker/Gopkg.lock, stability-checker/Gopkg.toml, stability-checker/before-commit.sh, watch-pods/Gopkg.lock, watch-pods/Gopkg.toml, watch-pods/before-commit.sh
- Fix golint version in `watch-pods`, `stability-checker` and in `development/tools`
=> Fix golint in watch-pods, stability-checker and in development/tools

prow/scripts/cluster-integration/kyma-gke-upgrade.sh
- Cherry-pick of Remove deprecated function (#1360)
=> Fix kyma-gke-uprade test for Kyma 1.4.1 release

prow/jobs/website/website-governance.yaml, stability-checker/Gopkg.lock, stability-checker/Gopkg.toml, stability-checker/before-commit.sh, watch-pods/Gopkg.lock, watch-pods/Gopkg.toml, watch-pods/before-commit.sh
- Fix version of `golint` in `stability-checker` and `watch-pods`
=> Fix golint in every package in stability-checker and watch-pods

development/checker/Gopkg.lock, development/checker/Gopkg.toml
- Fix golint issue for checker
=> Fix golint issue for the checker

development/tools/jobs/kyma/end_to_end_kubeless_integration_tests_test.go, development/tools/jobs/kyma/event_service_test.go, development/tools/jobs/kyma/k8s_dashboard_proxy_test.go, development/tools/jobs/kyma/knative_build_acceptance_test.go, development/tools/jobs/kyma/knative_serving_acceptance_test.go, development/tools/jobs/kyma/kubeless_images_test.go, development/tools/jobs/kyma/kubeless_tests_test.go, development/tools/jobs/kyma/test_integration_event_service_test.go, prow/jobs/kyma/components/event-service/event-service.yaml, prow/jobs/kyma/components/k8s-dashboard-proxy/k8s-dashboard-proxy.yaml, prow/jobs/kyma/components/kubeless-images/kubeless-images-nodejs.yaml, prow/jobs/kyma/tests/end-to-end/kubeless-integration/kubeless-integration.yaml, prow/jobs/kyma/tests/integration/event-service/test-event-service.yaml, prow/jobs/kyma/tests/knative-build/knative-build.yaml, prow/jobs/kyma/tests/knative-serving/knative-serving.yaml, prow/jobs/kyma/tests/kubeless/kubeless.yaml
- Update the go buildpack version.
=> Update the EventService buildpack version to go1.11

prow/jobs/cli/cli-integration.yaml, prow/jobs/kyma/kyma-integration.yaml, prow/scripts/metadata-governance.sh
=> Fix metadata governance job

prow/scripts/metadata-governance.sh
- Add an extra check to governance job
=> Add an extra check to governance job

prow/scripts/cluster-integration/helpers/start-wssagent.sh
Missing script directory var
- add logic to add script directory
=> whitesource script dir fix

prow/scripts/cluster-integration/helpers/cleanup-cluster.sh, prow/scripts/cluster-integration/kyma-aks-long-lasting.sh, prow/scripts/cluster-integration/kyma-gke-backup-test.sh, prow/scripts/cluster-integration/kyma-gke-central.sh, prow/scripts/cluster-integration/kyma-gke-compass-integration.sh, prow/scripts/cluster-integration/kyma-gke-integration.sh, prow/scripts/cluster-integration/kyma-gke-long-lasting.sh, prow/scripts/cluster-integration/kyma-gke-minio-gateway-migration.sh, prow/scripts/cluster-integration/kyma-gke-minio-gateway.sh, prow/scripts/cluster-integration/kyma-gke-release-candidate.sh, prow/scripts/cluster-integration/kyma-gke-upgrade.sh
Added required arguments for delete-dns-record.sh execution.
Fixes #1390
=> Added mandatory arguments for delete-dns-record.sh script execution.

development/tools/jobs/kyma/api_controller_test.go, development/tools/jobs/kyma/api_controller_tests_test.go, development/tools/jobs/kyma/apiserver_proxy_test.go, development/tools/jobs/kyma/apiserver_proxy_tests_test.go, development/tools/jobs/kyma/iam-kubeconfig-service_test.go, development/tools/jobs/kyma/integration_dex_test.go, development/tools/jobs/kyma/kyma_operator_test.go, prow/jobs/kyma/components/api-controller/api-controller.yaml, prow/jobs/kyma/components/apiserver-proxy/apiserver-proxy.yaml, prow/jobs/kyma/components/iam-kubeconfig-service/iam-kubeconfig-service.yaml, prow/jobs/kyma/components/kyma-operator/kyma-operator.yaml, prow/jobs/kyma/tests/integration/api-controller/api-controller-integration.yaml, prow/jobs/kyma/tests/integration/apiserver-proxy/apiserver-proxy-integration.yaml, prow/jobs/kyma/tests/integration/dex/dex-integration.yaml
Use newer buildpack-golang version in components:
- api-controller
- apiserver-proxy
- iam-kubeconfig-service
- kyma-operator
and tests:
- api-controller-integration
- apiserver-proxy-integration
- dex-integration
=> Use newer buildpack-golang image

development/tools/jobs/kyma/development_artifacts_test.go, prow/jobs/kyma/kyma-development-artifacts.yaml
Use newer buildpack-golang version in development-artifacts job (used to release kyma-operator)
=> Use newer buildpack-golang image in development-artifacts job

prow/scripts/cluster-integration/helpers/provision-gke-cluster.sh, prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
- Migrated pipelines to Kubernetes 1.13
kyma-project/kyma#5077
=> Migrate pipelines to Kubernetes 1.13

development/tools/jobs/kyma/asset_store_controller_manager_test.go, development/tools/jobs/kyma/cms_controller_manager_test.go, development/tools/jobs/tester/tester.go, prow/jobs/incubator/api-gateway/api-gateway.yaml, prow/jobs/kyma/components/asset-store-controller-manager/asset-store-controller-manager.yaml, prow/jobs/kyma/components/cms-controller-manager/cms-controller-manager.yaml
- Changed Kubebuilder version
kyma-project/kyma#5257
=> Change kubebuilder version

development/tools/jobs/incubator/terraform-provider-gardener/terraform_provider_gardener_test.go, prow/jobs/incubator/terraform-provider-gardener/terraform-provider-gardener.yaml
- Add jobs for the terraform provider gardener
See https://github.com/kyma-project/kyma/issues/5491
=> Add jobs for the terraform provider gardener

prow/jobs/kyma/kyma-integration.yaml
missing presets on prow job
prow job is missing some more presets to work
=> add more presets to prow job

development/resources-cleanup.sh, prow/scripts/cluster-integration/helpers/cleanup-cluster.sh, prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
- Use separate script for cleaning purposes
- Implement deletion of DNS and networks even if cluster does not exists.
The plan it to implement the same cleaner in other pipelines in the future.
=> Improve nightly cleaners

development/tools/cmd/dnscollector/main.go
cleaner regex does not catch a lot of the newer resources.
- extending cleaner regex
=> extending default cleaner regex

README.md
=> Remove test line

prow/jobs/test-infra/watch-pods.yaml
- Remove extra_refs from watch-pods job
=> Remove extra_refs from watch-pods job

prow/scripts/cluster-integration/helpers/cleanup-cluster.sh, prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
- Providing full DNS name necessary to cleanup resources
=> DNS cleanup fix

development/tools/jobs/kyma/vulnerability_scanner_test.go, prow/jobs/kyma/kyma-vulnerability-scanner.yaml
Wrong base container used, fixing
- change from boostrap to newer golang container.
=> change to 4 am every day, change run container to golang

prow/scripts/cluster-integration/helpers/cleanup-cluster.sh
- DNS name still could not be found, I suspect we are missing dot at the end of DNS name.
=> fix dns name

prow/scripts/cluster-integration/helpers/cleanup-cluster.sh
- Fetch  DNS record IP that should be cleaned up
=> Fetch proper IP

prow/scripts/cluster-integration/helpers/cleanup-cluster.sh, prow/scripts/cluster-integration/helpers/reserve-ip-address.sh, prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
=> IP-cleanup fixes

prow/scripts/cluster-integration/helpers/cleanup-cluster.sh, prow/scripts/cluster-integration/helpers/reserve-ip-address.sh
- Setting up GATEWAY_IP_ADDRESS
=> Gateway IP

prow/scripts/cluster-integration/helpers/cleanup-cluster.sh, prow/scripts/cluster-integration/helpers/reserve-ip-address.sh, prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
=> reverting changes

prow/jobs/kyma/kyma-integration.yaml, prow/scripts/cluster-integration/helpers/start-wssagent.sh, templates/templates/kyma-integration.yaml
Dryrun set to false, to run wss now.
=> dryrun parameter

development/tools/jobs/incubator/compass/provisioner_test.go, development/tools/jobs/incubator/compass/provisioner_tests_test.go, prow/jobs/incubator/compass/components/provisioner/provisioner.yaml, prow/jobs/incubator/compass/tests/provisioner/provisioner-tests.yaml
- Added necessary files for compass provisioner and provisioner tests
=> Provisioner pipeline

development/tools/jobs/kyma/kyma_integration_test.go, development/tools/jobs/kyma/kyma_release_candidate_test.go, prow/jobs/kyma/kyma-integration.yaml, prow/jobs/kyma/kyma-release-candidate.yaml, templates/templates/kyma-integration.yaml, templates/templates/kyma-release-candidate.yaml
- changing europe-west4-c to europe-west4-a zone
=> changing europe-west4-c to europe-west4-a zone

templates/templates/kyma-integration.yaml
- Adding test job configuration that will take configuration from my branch
=> Adding nightly test job

prow/scripts/cluster-integration/kyma-gke-backup-test.sh
- Improve backup error message
See https://github.com/kyma-project/kyma/issues/5434
=> Improve backup error message

prow/jobs/kyma/kyma-integration.yaml, templates/templates/kyma-integration.yaml
- Adding new test job
- Disabling notifications for whitesource
- Removing test job configuration from /templates
=> New test job

prow/jobs/kyma/kyma-integration.yaml
- Changing from post to presubmit job (this is a test job)
=> Changing from post to presubmit job

prow/scripts/cluster-integration/helpers/start-wssagent.sh
changes java_opts parameter to report when none are set, also not passing empty string which would result in "ClassNotFound" error.
=> add java_opts check

prow/images/whitesource-scanner/wss-unified-agent.config
Removing comment in front of the key that is provided.
=> uncomment userkey

prow/jobs/kyma/kyma-integration.yaml, prow/scripts/cluster-integration/helpers/start-wssagent.sh
Use new whitesource container, as well as manual change to project directory to scan correct folder.
=> update container version and change directory to project dir

development/tools/jobs/testinfra/branchprotector_test.go, prow/config.yaml, templates/config.yaml
- Add backup job to branch protection
=> Add backup job to branch protection

prow/scripts/cluster-integration/helpers/reserve-ip-address.sh
- Add retries when creating IP addresses
https://github.com/kyma-project/test-infra/issues/1446
=> add retries

prow/scripts/cluster-integration/helpers/reserve-ip-address.sh
Reverts kyma-project/test-infra#1447
=> Revert "add retries"

development/tools/jobs/incubator/hydroform/hydroform_test.go, prow/jobs/incubator/hydroform/hydroform.yaml
- Add jobs for hydroform
See kyma-project/kyma#5492
=> Add jobs for hydroform

prow/jobs/kyma/components/console-backend-service/console-backend-service-generic.yaml, templates/templates/generic-component.yaml
=> Make generic CBS job optional

prow/scripts/cluster-integration/helpers/cleanup-cluster.sh
Reverts kyma-project/test-infra#1458
=> Revert "delete APIserver proxy ip from DNS"

prow/scripts/cluster-integration/helpers/create-dns-record.sh, prow/scripts/cluster-integration/helpers/reserve-ip-address.sh
Reverts kyma-project/test-infra#1457
=> Revert "reserve-ip-address.sh returns the reserved IP on stdout"

prow/scripts/build-generic.sh
- Export DOCEKR_TAG env from build-generic.sh
#
=> Export DOCKER_TAG from build-generic.sh

development/tools/jobs/kyma/components_test.go, development/tools/jobs/tester/genericcomponentsuite.go, development/tools/jobs/tester/jobsuite/config.go, development/tools/jobs/tester/jobsuite/options.go, prow/jobs/kyma/components/console-backend-service/console-backend-service-generic.yaml, templates/config.yaml, templates/templates/generic-component.yaml
- Add parameter `optional` to generic component config
- Test it
- Disable slack reporter if job is optional
=> Add tests for optional and do not send slack reports

development/tools/jobs/tester/componentsuite.go, templates/templates/component.yaml
- Add the "optional" flag to the component template, same as in #1463 
=> Optional in component template

development/tools/jobs/console/compass_test.go, prow/jobs/console/compass/compass.yaml
- Make compass ui jobs required
=> Compass UI is not optional, trust me

CODEOWNERS
=> Update tempaltes codeowners

prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
Fixed failing kyma_aks_nightly builds.
- Typos correction.
- Added checks for steps execution.
- Improved output format for better reading.
Fixes #1446
=> Kyma aks nightly fail #1446

prow/scripts/cluster-integration/helpers/start-wssagent.sh
sed script is complaining about an option that is not used in the script. trying to clean things up more.
=> Make sed a one-liner

prow/scripts/cluster-integration/helpers/provision-gke-cluster.sh, prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
=> Bump Kubernetes version to 1.14

prow/scripts/cluster-integration/helpers/provision-gke-cluster.sh, prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
This reverts commit 328499f2eb365b2068097e5b836eb35ded9eedef.
- Tiller installation is failing on GKE 1.14
=> Revert "Bump Kubernetes version to 1.14 (#1487)"

prow/cluster/resources/monitoring/dashboards/grafana-prow.json
Corrected section title in Grafana dashboard.
Fixes #1269
=> Corrected dashboard section title.

prow/jobs/kyma/kyma-integration.yaml, templates/templates/kyma-integration.yaml
- enable Slack notifications for Whitesource scans 
=> Enable Slack notifications for Whitesource scans 

development/tools/jobs/console/core_ui_test.go, prow/jobs/console/core-ui/core-ui.yaml, templates/config.yaml
=> Add job for core-ui

prow/images/buildpack-golang-toolbox/Dockerfile
- Remove dependency to `failery` from toolbox image
https://github.com/kyma-project/test-infra/issues/1502
=> Remove Kyma source from toolbox

development/tools/jobs/kyma/components_test.go, development/tools/jobs/kyma/tests_test.go, prow/jobs/kyma/components/console-backend-service/console-backend-service-generic.yaml, prow/jobs/kyma/tests/console-backend-service/console-backend-service-tests-generic.yaml, templates/config.yaml
- generic_kyma_component runs if scripts is changed
- cbs and cbs-tests are regenerated. their tests are updated
=> Generic kyma component triggers on changes in scripts directory

CODEOWNERS
=> Add missing TW code owners

development/tools/jobs/kyma/kyma_release_pr_image_guard_test.go, prow/jobs/kyma/kyma-release-pr-image-guard.yaml, prow/scripts/pr-image-guard.sh
- Add job that fails when the images contain PR-* tag when releasing
=> Add pr images guard job on release branches

prow/scripts/cluster-integration/kyma-gke-minio-gateway-migration.sh, prow/scripts/cluster-integration/kyma-gke-minio-gateway.sh
- Execute only Asset Store tests for MinIO Gateway modes
=> Execute only Asset Store tests for MinIO Gateway modes

prow/images/buildpack-golang-toolbox/Dockerfile, prow/images/buildpack-golang-toolbox/license-puller.sh
- license-puller.sh is included in toolbox image
kyma-project/kyma#5762
=> Include license-puller.sh in go toolbox image

prow/jobs/kyma/kyma-release-pr-image-guard.yaml, prow/scripts/pr-image-guard.sh
- Print PR images inf pr guard job
- make the job optional
=> Print failed images in job guard

prow/jobs/kyma/kyma-development-artifacts-idk.yaml, prow/scripts/build-kyma-development-artifacts.sh
=> development artifacts temp generic job

prow/jobs/kyma/kyma-development-artifacts-idk.yaml
- Dev artifacts fix
- changed image to bootstrap
=> Dev artifacts fix

prow/jobs/kyma/kyma-development-artifacts-tmp.yaml, prow/scripts/build-kyma-development-artifacts-tmp.sh
This is an optional (!!!) temporary job to build dev artifacts. 
=> development artifacts temp generic job again

prow/images/buildpack-golang-toolbox/Dockerfile
- merged image layers into one golang-toolbox docker image
=> Remove unneccesary layers in golang-toolbox docker image

development/tools/jobs/cli/cli_integration_test.go, development/tools/jobs/cli/cli_test.go, development/tools/jobs/incubator/hydroform/hydroform_test.go, development/tools/jobs/incubator/terraform-provider-gardener/terraform_provider_gardener_test.go, prow/jobs/cli/cli-integration.yaml, prow/jobs/cli/cli.yaml, prow/jobs/incubator/hydroform/hydroform.yaml, prow/jobs/incubator/terraform-provider-gardener/terraform-provider-gardener.yaml
- Activate go modules for the relevant projects migrating to them
=> Activate go modules in prow jobs

development/tools/jobs/console/core_ui_test.go, prow/jobs/console/core-ui/core-ui.yaml, templates/config.yaml
- Remove 'optional: true' property in core-ui
- Update tests
=> Make core UI job non-optional

development/tools/jobs/kyma/components_test.go, prow/jobs/kyma/components/api-controller/api-controller-generic.yaml, prow/jobs/kyma/components/api-controller/api-controller.yaml, templates/config.yaml
- api-controller switch to generic component
=> api-controller switch to generic component

prow/images/buildpack-node/Dockerfile
- Update Node version to 12 in buildpack-node
=> Update Node version to 12 in buildpack-node

development/tools/jobs/kyma/components_test.go, prow/jobs/kyma/components/iam-kubeconfig-service/iam-kubeconfig-service-generic.yaml, prow/jobs/kyma/components/iam-kubeconfig-service/iam-kubeconfig-service.yaml, templates/config.yaml
- iam-kubeconfig-service switch to generic component
=> iam-kubeconfig-service switch to generic component

development/tools/jobs/console/core_test.go, development/tools/jobs/console/core_ui_test.go, development/tools/jobs/console/logging_test.go, development/tools/jobs/console/react_components_test.go, development/tools/jobs/examples/event_email_service_test.go, development/tools/jobs/incubator/varkes/varkes_test.go, development/tools/jobs/incubator/vstudio-extension/vstudio_extension_test.go, development/tools/jobs/tester/tester.go, prow/jobs/console/add-ons/add-ons.yaml, prow/jobs/console/compass/compass.yaml, prow/jobs/console/content/content.yaml, prow/jobs/console/core-ui/core-ui.yaml, prow/jobs/console/core/core.yaml, prow/jobs/console/lambda/lambda.yaml, prow/jobs/console/logging/logging-ui.yaml, prow/jobs/console/service-catalog-ui/service-catalog-ui.yaml, prow/jobs/console/tests/console-tests.yaml
- Update node build pack version for prow jobs building UI components (as a result of https://github.com/kyma-project/test-infra/pull/1568)
https://github.com/kyma-project/test-infra/pull/1568
=> Update node version in node buildpack for ui components

development/tools/jobs/tester/tester.go, prow/jobs/console/add-ons/add-ons.yaml, prow/jobs/console/compass/compass.yaml, prow/jobs/console/content/content.yaml, prow/jobs/console/core-ui/core-ui.yaml, prow/jobs/console/core/core.yaml, prow/jobs/console/lambda/lambda.yaml, prow/jobs/console/logging/logging-ui.yaml, prow/jobs/console/service-catalog-ui/service-catalog-ui.yaml, prow/jobs/console/tests/console-tests.yaml
- Fixed path to node build pack image
=> Fix node buildpack path

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml
- Run backup tests when the chart is modified
See https://github.com/kyma-project/kyma/issues/5941
=> Run backup tests when the chart is modified

prow/jobs/kyma/kyma-compass-integration.yaml
- Prepare a temporary job for Provisioner tests
=> Prepare temporary job for Provisioner tests

development/tools/jobs/console/core_test.go, development/tools/jobs/console/logging_test.go, prow/jobs/console/core/core.yaml, prow/jobs/console/logging/logging-ui.yaml
- Change version of Console Core & Logging buildpack to Chromium one.
=> Change version of Console Core & Logging buildpack

development/tools/jobs/kyma/components_test.go, prow/jobs/kyma/components/xip-patch/xip-patch-generic.yaml
=> xip-patch generic fix

development/tools/jobs/kyma/components_test.go, prow/jobs/kyma/components/xip-patch/xip-patch-generic.yaml, prow/jobs/kyma/components/xip-patch/xip-patch.yaml, templates/config.yaml
=> xip-patch generic switch

development/tools/jobs/kyma/components_test.go, prow/jobs/kyma/components/istio-kyma-patch/istio-kyma-patch-generic.yaml, prow/jobs/kyma/components/istio-kyma-patch/istio-kyma-patch.yaml, templates/config.yaml
- Istio-patch: switch to generic
https://github.com/kyma-project/kyma/issues/5481 https://github.com/kyma-project/kyma/issues/5763
#1588
=> Istio-patch: switch to generic

development/tools/jobs/cli/cli_integration_test.go, development/tools/jobs/cli/cli_test.go, development/tools/jobs/incubator/hydroform/hydroform_test.go, development/tools/jobs/incubator/octopus/octopus_test.go, development/tools/jobs/incubator/terraform-provider-gardener/terraform_provider_gardener_test.go, prow/jobs/cli/cli-integration.yaml, prow/jobs/cli/cli.yaml, prow/jobs/incubator/hydroform/hydroform.yaml, prow/jobs/incubator/octopus/octopus.yaml, prow/jobs/incubator/terraform-provider-gardener/terraform-provider-gardener.yaml, prow/jobs/kyma/components/asset-store-controller-manager/asset-store-controller-manager.yaml, prow/jobs/kyma/components/cms-controller-manager/cms-controller-manager.yaml, prow/jobs/kyma/components/compass-runtime-agent/compass-runtime-agent.yaml, templates/config.yaml
- Revert go proxy usage as it does not work with 1.12
=> Revert go proxy usage

stability-checker/deploy/chart/stability-checker/templates/role.yaml
=> Fix SC rbac roles

prow/jobs/kyma/kyma-compass-integration.yaml
Due to issue with the updated version of  Oathkeeper compass-integration job is failing and blocking megres to master.
- Mark `pre-master-compass-gke-integration` as optional
=> Mark compass integration as optional

development/tools/jobs/incubator/compass/compass_integration_test.go, prow/jobs/incubator/compass/compass-integration.yaml, templates/templates/compass-integration.yaml
- Adapt cli changes in the compass integration
=> Adapt cli changes in the compass integration

prow/jobs/incubator/compass/compass-integration.yaml, templates/templates/compass-integration.yaml
- Enable go mod in gopath compass integration
=> Enable go mod in gopath compass int

development/tools/cmd/jobguard/run.sh
- Disable gomod when running jobguard
=> Disable gomod when running jobguard

prow/images/buildpack-golang-toolbox/Dockerfile, prow/images/buildpack-golang-toolbox/README.md
- Added rsync
- Added procps
#1470
=> Add rsync and procps to Golang Toolbox image

prow/jobs/incubator/compass/tests/end-to-end/end-to-end-generic.yaml, templates/templates/generic-component.yaml
- Turn off temporarily slack reports for compass e2e generic job
=> Turn off slack raports

CODEOWNERS, prow/config.yaml, prow/jobs/test-infra/test-infra-kind.yaml
- Added pre/post submit jobs that build Kubernetes image
- Added periodic job that tests Kyma on kind
#1470
=> Add jobs for Kind environment

prow/jobs/test-infra/test-infra-kind.yaml
- Set missing security context
- Added missing preset
#1470
=> Fix kind periodic job

development/tools/jobs/kyma/components_test.go, development/tools/jobs/kyma/tools_test.go, prow/jobs/kyma/components/backup-plugins/backup-plugins.yaml, templates/config.yaml
- Move backup plugin jobs
See https://github.com/kyma-project/kyma/issues/5899
=> Move backup plugin jobs

development/tools/jobs/kyma/tests_test.go, prow/jobs/kyma/tests/integration/apiserver-proxy/apiserver-proxy-tests-generic.yaml, prow/jobs/kyma/tests/integration/apiserver-proxy/apiserver-proxy-tests.yaml, templates/config.yaml
- apiserver-proxy integration tests: switch to generic
https://github.com/kyma-project/kyma/issues/5481
https://github.com/kyma-project/kyma/issues/5763
https://github.com/kyma-project/kyma/pull/6012
=> apiserver-proxy integration tests: switch to generic

development/tools/jobs/kyma/components_test.go, prow/jobs/kyma/components/backup-plugins/backup-plugins-generic.yaml, prow/scripts/cluster-integration/kyma-gke-backup-test.sh, templates/config.yaml
- Update backup plugin image in use
See https://github.com/kyma-project/kyma/issues/5899
=> Update backup plugin image in use

development/tools/jobs/kyma/tests_test.go, prow/jobs/kyma/tests/integration/dex/dex-tests-generic.yaml, prow/jobs/kyma/tests/integration/dex/dex.yaml, templates/config.yaml
=> tests-dex generic switch

development/tools/jobs/kyma/tests_test.go, prow/jobs/kyma/tests/integration/cluster-users/cluster-users-tests-generic.yaml, prow/jobs/kyma/tests/integration/cluster-users/cluster-users-tests.yaml, templates/config.yaml
- cluster-users integration tests: switch to generic jobs
https://github.com/kyma-project/kyma/issues/5481
https://github.com/kyma-project/kyma/issues/5763
https://github.com/kyma-project/kyma/pull/6027
=> cluster-users integration tests: switch to generic jobs

development/tools/jobs/kyma/tests_test.go, prow/jobs/kyma/tests/service-catalog/service-catalog-tests-generic.yaml, templates/config.yaml
- Added optional flag to service catalog acceptance tests
- ...
- ...
=> Add optional flag to service catalog acceptance tests.

prow/scripts/cluster-integration/helpers/install-stability-checker.sh, stability-checker/.gitignore, stability-checker/README.md, stability-checker/deploy/chart/stability-checker/templates/role.yaml
- Fix Stability Checker logging
- Updated SC chart with newest testing scripts and RBAC roles for Octopus
=> Improve stability checker directory

development/tools/jobs/helm-broker/helm_broker_test.go, prow/jobs/helm-broker/helm-broker.yaml
- Added job for helm-broker releasing
=> Add job for helm-broker releasing

development/tools/jobs/cli/cli_test.go, prow/jobs/cli/cli.yaml
- Disable go modules to get the 1.6 release through.
=> Temporary disable go modules for CLI

development/tools/jobs/cli/cli_test.go, prow/jobs/cli/cli.yaml
- Enable go modules again after release 1.6 is through.
=> Enable go modules again for CLI

templates/config.yaml
- Remove duplicate kyma-operator job from config.yaml
- Make application-broker non-optional again
=> Fix broken jobs for kyma-operator and application-broker

prow/scripts/cluster-integration/kyma-gke-minio-gateway-migration.sh
Fix GREEN: unbound variable error
See also:  https://github.com/kyma-project/test-infra/issues/1632
=> Fix GREEN: unbound variable error

development/tools/jobs/helm-broker/helm_broker_test.go, prow/jobs/helm-broker/helm-broker.yaml
- Create a test release pipeline for HB
=> Create test release pipeline for HB

development/tools/jobs/helm-broker/helm_broker_test.go, prow/jobs/helm-broker/helm-broker.yaml
- Removed temporary HB job definition
=> Remove temporary HB job definition

prow/jobs/kyma/kyma-compass-integration.yaml
- Make Compass integration job required again
=> Make Compass integration job required again

development/tools/Gopkg.lock, prow/jobs/test-infra/validation.yaml, prow/scripts/library.sh, prow/scripts/validate-generated.sh
- enhance library.sh
- fix validate-generated.sh
=> Enhance library.sh, change buildpack for generated file validations

prow/jobs/incubator/marketplaces/marketplaces.yaml
- add ability to run bigger tests for marketplace repository by improving jobs in yaml file
Related: [#19](https://github.com/kyma-incubator/marketplaces/issues/19)
=> Enable kind environment in marketplaces jobs

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml, templates/templates/kyma-integration.yaml
- extended regex in disk cleaner job
=> Clean up disks used by compass clusters

prow/jobs/test-infra/validation.yaml
- make the pre-master-test-infra-validate-generated-files job required
Related: https://github.com/kyma-project/test-infra/issues/1460
=> Make the job pre-master-test-infra-validate-generated-files required

prow/jobs/helm-broker/helm-broker.yaml
=> Fix HB latest release

prow/scripts/cluster-integration/kyma-gke-backup-test.sh
This reverts commit 072e10a1d4b7e90a00563bb739757489957c6388.
- revert velero plugin
=> Revert "Velero plugin to fix-backup-restore-event-bus (#1656)"

prow/scripts/cluster-integration/kyma-gke-backup-test.sh
This reverts commit 072e10a1d4b7e90a00563bb739757489957c6388.
- ...
- ...
- ...
=> Revert "Velero plugin to fix-backup-restore-event-bus (#1656)" (#1677)

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml, templates/templates/kyma-integration.yaml
- Extended disk cleaner regex to include 'restore' cluster.
=> Add 'restore' cluster to disk cleaner

docs/prow/prow-jobs.md
=> Update mkpj documentation

.gitignore, kind/scripts/install-kyma.sh, prow/jobs/kyma/kyma-kind-integration.yaml, prow/scripts/kind-install-kyma.sh, prow/scripts/kind/cluster.yaml, prow/scripts/kind/resources/01-metrics-server.yaml, prow/scripts/kind/resources/02-local-path-provisioner.yaml, prow/scripts/lib/docker.sh, prow/scripts/lib/junit.sh, prow/scripts/lib/kind.sh, prow/scripts/lib/kubernetes.sh, prow/scripts/lib/kyma.sh, prow/scripts/lib/log.sh, prow/scripts/library.sh
- Added scripts
- Added job definition
- Notifications to GH are disabled
- Scripts are working also on a local computer, not only in the Prow environment
As this is the first attempt, so documentation is missing and for sure Kyma Lite is supported.
#1654
=> Add pre-submit Kyma Lite on kind job

prow/set-up-workload-cluster.sh, prow/workload-cluster/03-kube-dns-stub-domains-patch.yaml
- added patch for stubDomains
https://github.com/kyma-project/test-infra/issues/1681
=> Add stubDomains to the workload cluster 

development/tools/jobs/kyma/kyma_release_upgrade_test.go, prow/jobs/kyma/kyma-release-upgrade.yaml, prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh
- add release-to-release upgrade pipeline
#1671
=> add release-to-release upgrade pipeline

prow/scripts/cluster-integration/kyma-gke-backup-test.sh
- Bump backup plugin image
Fixes https://github.com/kyma-project/kyma/issues/5942
=> Bump backup plugin image

prow/scripts/cluster-integration/kyma-gke-upgrade.sh
- Migrated upgrade test to octopus
=> Migrate upgrade test to octopus

prow/config.yaml
- configure branch protection for dex and api-controller repositories
Related to [#kyma/6118](https://github.com/kyma-project/kyma/issues/6118)
=> Configure branch protection for dex and api-controller repos

templates/templates/prow-config.yaml
=> Fix configuration of branch protection for dex and api-controller repos

prow/jobs/test-infra/validation.yaml
- Added missing autogenerated files to changes tracking in validation job
- ...
- ...
Prevents situations like this: #1708 when autogenerated file was overwritten and validate job didn't trigger.
=> Add missing autogenerated files to tracking for validation prow job.

development/tools/jobs/kyma/tests_test.go, prow/jobs/kyma/tests/service-catalog/service-catalog-tests-generic.yaml, templates/config.yaml
- Removed flag 'optional' from service catalog test job.
- ...
- ...
=> Remove optional flag from service catalog test job.

prow/jobs/rafter/rafter.yaml
Create build pipelines for Rafter
- build pipelines for Rafter
Do not merge before: https://github.com/kyma-project/rafter/pull/15/files
see also: https://github.com/kyma-project/rafter/issues/3
=> Create build pipelines for Rafter

prow/jobs/rafter/rafter.yaml
Update buildpack image for rafter jobs
=> Update buildpack image for rafter jobs

prow/jobs/rafter/rafter.yaml
=> Update release-rafter job

prow/images/buildpack-golang/Dockerfile, prow/images/buildpack-golang/Makefile, prow/images/buildpack-golang/README.md
- Add Golang buildpack from version 1.13
=> Add Golang buildpack 1.13

prow/scripts/resources/prometheus-operator-stackdriver-patch.yaml
Adding metric filter to limit volume of data send to stackdriver.
Resolves #1730
=> Added metrics filter.

prow/jobs/kyma/kyma-kind-integration.yaml, prow/scripts/README.md, prow/scripts/kind-install-kyma.sh, prow/scripts/kyma-testing.sh, prow/scripts/lib/docker.sh, prow/scripts/lib/host.sh, prow/scripts/lib/junit.sh, prow/scripts/lib/kind.sh, prow/scripts/lib/kubernetes.sh, prow/scripts/lib/kyma.sh, prow/scripts/lib/log.sh, prow/scripts/lib/testing-helpers.sh
- Added descriptions to functions in lib directory
- Download kubectl to a temporary directory
#1684
=> Migrate Kyma GKE pipeline to kind

prow/scripts/lib/junit.sh
- Replacing invalid characters in JUnit reports
=> Fix JUnit report generation

prow/images/bootstrap/Dockerfile
- Bump cloud SDK
https://github.com/kyma-project/test-infra/issues/1733
=> Bump cloud SDK to 272.0.0 in bootstrap image

prow/jobs/kyma/kyma-release-upgrade.yaml
- Fix rel2rel post release pipeline
https://github.com/kyma-project/test-infra/pull/1698
=> Fix rel2rel post release pipeline

prow/images/buildpack-golang/Dockerfile
- Bump cloud SDK
https://github.com/kyma-project/test-infra/issues/1733
=> Bump bootstrap image (updated cloud SDK to 272.0.0) 

prow/images/kyma-cluster-infra/Dockerfile
- Bump cloud SDK
https://github.com/kyma-project/test-infra/issues/1733
=> Bump buildpack-golang image (updated cloud SDK to 272.0.0)

prow/jobs/rafter/rafter.yaml
- Add preset-kind-volume-mounts for Rafter label
See also https://github.com/kyma-project/rafter/issues/5
=> Add preset-kind-volume-mounts for Rafter

prow/jobs/kyma/kyma-compass-integration.yaml, prow/jobs/kyma/kyma-integration.yaml, prow/scripts/cluster-integration/kyma-gke-central.sh, prow/scripts/cluster-integration/kyma-gke-compass-integration.sh, prow/scripts/cluster-integration/kyma-gke-integration.sh, prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh, prow/scripts/cluster-integration/kyma-gke-upgrade.sh, templates/templates/kyma-integration.yaml
- Added JUnit reports for tests
- Enabled TestGrid support in integration postsubmit jobs
PR on k8s test-infra: https://github.com/kubernetes/test-infra/pull/15337
Sample executions: https://status.build.kyma-project.io/?pull=6321
https://github.com/kyma-project/test-infra/issues/831
https://github.com/kyma-project/test-infra/issues/830
=> Add JUnit reports to GKE jobs

development/tools/jobs/cli/cli_integration_test.go, prow/jobs/cli/cli-integration.yaml, prow/scripts/cluster-integration/kyma-gke-integration-cli.sh, prow/scripts/provision-vm-cli.sh
- Add cli - kyma master integration job
See https://github.com/kyma-project/cli/issues/18
=> Add cli - kyma master integration job

prow/jobs/rafter/rafter.yaml
- add new job for rafter to execute integration test on `make integration-test`
See also https://github.com/kyma-project/rafter/issues/5
=> Add integration test target

prow/jobs/rafter/rafter.yaml
- add lacking `common_config` in pre-rafter job :tada:
=> Fix Rafter job config

prow/scripts/kyma-testing.sh
- Made suite name fixed.
Name cannot be dynamic because it will look like that in TestGrid:
=> Fix test suite name

prow/scripts/kyma-testing.sh, prow/scripts/lib/junit.sh
- Removed executions from JUnit test names.
If the names are dynamic we are losing ability to compare changes in TestGrid
=> Fix JUnit integration tests naming

prow/scripts/kyma-testing.sh
- removed check for require-static-user test as the label got removed
- ...
- ...
https://github.com/kyma-project/kyma/issues/825
=> removed static-user-check
