kyma-project/test-infra

- prow/scripts/kyma-testing.sh
Beause of the comment introduced in: https://github.com/kyma-project/test-infra/pull/1756/files the line is not skipped and jobs are failing.
- move comment to fix line skipping
> Move comment to fix line skipping

- development/tools/jobs/cli/cli_test.go
- prow/config.yaml
- prow/jobs/cli/cli.yaml
- templates/templates/prow-config.yaml
- Add kyma CLI stable binary job
See https://github.com/kyma-project/cli/issues/294
> Add kyma CLI stable binary job

- prow/scripts/kyma-testing.sh
- Replace Kyma CLI download URL
See https://github.com/kyma-project/cli/issues/294
> Replace Kyma CLI download URL

- prow/config.yaml
- templates/templates/prow-config.yaml
- improved version of clonerefs image
https://github.com/kyma-project/test-infra/issues/1198
> Bump clonerefs image

- prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh
- change container name as per https://github.com/kyma-project/test-infra/commit/395f784db48f81b734bbc37ac1ea805b17fd3031
> Fix release-2-release upgrade pipeline

- prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh
- Fix rel2rel pipeline: remove redundant call to is-ready.
> Fix rel2rel pipeline: remove is-ready

- prow/jobs/kyma/kyma-kind-integration.yaml
> Change Kyma on kind resources

- prow/config.yaml
- templates/templates/prow-config.yaml
- added presets for integration with gardener
- ...
- ...
> Configure preset for gardener

- development/tools/jobs/incubator/kyma-dns-webhook/kyma_dns_webhook_test.go
- prow/config.yaml
- prow/jobs/incubator/dns-webhook/dns-webhook.yaml
- prow/jobs/incubator/kyma-dns-webhook/kyma-dns-webhook.yaml
- templates/templates/prow-config.yaml
- Add new prowjobs for dns components
- Implements https://github.com/kyma-incubator/kyma-dns-webhook/issues/12
> Add prowjobs for dns components

- prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
- Do not run console tests on long-lasting clusters until https://github.com/kyma-project/kyma/issues/6416 is fixed
https://github.com/kyma-project/kyma/issues/6416
> Disable console tests on long-lasting clusters

- prow/config.yaml
- templates/templates/prow-config.yaml
- Due to higher ProwJob demand and free cluster resources we can increase the limit.
- Today there were 50 concurrent jobs running and 50 jobs queued.
> increase ProwJob limit

- development/tools/jobs/rafter/rafter_test.go
- development/tools/jobs/tester/tester.go
- prow/jobs/rafter/rafter.yaml
Update rafter jobs: add missing `base_ref` to test-infra with sha
> Update rafter jobs: add missing base_ref to test-infra with sha

- development/tools/jobs/rafter/rafter_test.go
- prow/jobs/rafter/rafter.yaml
- Add missing preset to rafter jobs for minio gcs gateway mode
> Add missing preset to rafter jobs for minio gcs gateway mode

- prow/scripts/kind-install-kyma.sh
- prow/scripts/lib/kind.sh
- add new parameter to `kind::export_logs` function, instead of global variable
See https://github.com/kyma-project/rafter/pull/24#discussion_r350568167, https://github.com/kyma-project/rafter/issues/5
> Parametrize kind::export_logs function

- development/tools/jobs/rafter/rafter_test.go
- prow/jobs/rafter/rafter.yaml
- update base_sha to pin test-infra to newer commit, to incorporate https://github.com/kyma-project/test-infra/pull/1775
- make gateway and migration jobs optional
See also https://github.com/kyma-project/rafter/issues/5
> [Rafter] update base_sha and make gateway and migration jobs optional

- prow/scripts/cluster-integration/kyma-gke-integration-cli.sh
- Remove kyma uninstallation from the nightly job
> Remove kyma uninstallation from the nightly job

- prow/jobs/kyma/kyma-integration-k8s-1-14.yaml
- The kyma jobs running on k8s 1.14 should not run automatically or when a file changed. Instead it should only be triggerable manually with `/test`
> Do not automatically run k8s 1.14 jobs

- prow/config.yaml
- templates/templates/prow-config.yaml
- added more presets for integration with gardener
https://github.com/kyma-project/test-infra/issues/1757
> Add gardener presets for kyma_prow project 

- development/tools/jobs/kyma/components_test.go
- development/tools/jobs/kyma/tools_test.go
- prow/jobs/kyma/components/health-check-proxy/health-check-proxy.yaml
- templates/config.yaml
- Changed the directory of the `health-check-proxy` from `/tools` to `/components`
> Move health-check-proxy to components

- prow/jobs/kyma/kyma-integration-k8s-1-14.yaml
- In order to work with k8s 1.14 clusters we need [kubectl version 1.12, 1.13 or 1.14](https://v1-14.docs.kubernetes.io/docs/setup/release/version-skew-policy/)
> kubectl is supported at 1.14, 1.13, and 1.12
- The kubectl version used before was 1.10
I used the newst kyma-cluster-infra available on out gcr repo:
```console
gcloud container images list-tags --project kyma-project eu.gcr.io/kyma-project/test-infra/kyma-cluster-infra
DIGEST        TAGS                TIMESTAMP
e4b53d83b493  v20191120-66b27aac  2019-11-20T16:41:45 <- we are upgrading to this one
b3b12ec693f5  v20190927-2687a99   2019-09-27T22:29:29
44a120508c2b  v20190528-8897828   2019-05-28T15:55:48
e98d6bc12a1d  v20190227-a4164f9   2019-02-27T10:05:53
74eaaf3f981f …
```
> Update kyma-cluster-infra images for k8s 1.14 jobs to use kubectl version 1.14

- development/tools/jobs/rafter/rafter_test.go
- prow/jobs/rafter/rafter.yaml
- Make required Rafter MinIO Gateway jobs
> Make required Rafter MinIO Gateway jobs

- development/tools/jobs/rafter/rafter_test.go
- prow/jobs/rafter/rafter.yaml
- Add `tolerations` to Rafter jobs
> Add tolerations to Rafter jobs

- prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh
- prow/scripts/cluster-integration/kyma-gke-upgrade.sh
- Add opt to inject addons only if necessary for upgrade plans
- https://github.com/kyma-project/kyma/issues/6253
> Add opt to inject addons only if necessary for upgrade plans

- prow/jobs/kyma/kyma-compass-integration-1-14.yaml
- Make pre-master-kyma-gke-compass-integration-k8s-1-14 job optional and do not run automatically
> Make pre-master-kyma-gke-compass-integration-k8s-1-14 job optional and do not run automatically

- prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh
- prow/scripts/cluster-integration/kyma-gke-upgrade.sh
- Fix logging in upgrade scripts
> Fix logging in upgrade scripts

- prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh
- prow/scripts/cluster-integration/kyma-gke-upgrade.sh
- Revert injecting addons only if necessary
> Revert injecting addons only if necessary

- prow/scripts/cluster-integration/kyma-gke-upgrade.sh
- Remove addons if necessary in upgrade plan
> Remove addons if necessary in upgrade plan

- development/tools/jobs/kyma/tests_test.go
- prow/jobs/kyma/tests/knative-build/knative-build-tests-generic.yaml
- prow/jobs/kyma/tests/knative-build/knative-build.yaml
- prow/jobs/kyma/tests/knative-serving/knative-serving-tests-generic.yaml
- prow/jobs/kyma/tests/knative-serving/knative-serving.yaml
- templates/config.yaml
- disable old jobs
- enable new generic jobs
> Enable generic knative jobs

- prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
- prow/scripts/resources/prometheus-operator-stackdriver-patch.yaml
- Added config mandatory for generic monitored resources.
- Added filters to export apiserver metrics.
- Changed prometheus resources name to align to new kube-prometheus deployment app name.
> Added filters to export apiserver metrics.

- development/github-stats.sh
- development/tools/Gopkg.lock
- development/tools/cmd/githubstats/README.md
- development/tools/cmd/githubstats/main.go
- development/tools/jobs/kyma/kyma_integration_test.go
- docs/prow/prow-jobs.md
- prow/jobs/kyma/kyma-integration-k8s-1-14.yaml
- prow/jobs/kyma/kyma-integration.yaml
- templates/templates/kyma-integration.yaml
- created tool for gathering statistics from github (types of issues)
https://github.com/kyma-project/kyma/issues/5476
> Add github-stats tool

- development/tools/jobs/kyma/kyma_integration_test.go
- prow/jobs/kyma/kyma-integration.yaml
- templates/templates/kyma-integration.yaml
> Fix backup/restore job

- prow/jobs/incubator/knative-kafka/channel.yaml
- prow/jobs/incubator/knative-kafka/controller.yaml
- prow/jobs/incubator/knative-kafka/dispatcher.yaml
- prow/jobs/incubator/knative-kafka/knative-kafka-common.yaml
- templates/config.yaml
Make the knative-kafka jobs required
> Make knative-kafka jobs required

- development/prow-installer/cmd/storage/main.go
- development/prow-installer/go.sum
- development/prow-installer/pkg/secrets/secrets.go
- development/prow-installer/pkg/storage/storage.go
created a toolset to create/delete/write/read buckets, rewrote the secret tool to use this tool.
- add gcs toolkit
> Gcs bucket tool

- development/tools/jobs/testinfra/branchprotector_test.go
- prow/config.yaml
- templates/templates/prow-config.yaml
- update branchprotector settings
> branchprotector

- development/tools/cmd/jobguard/run.sh
- Jobguard will wait for component jobs to finish
> Extend regex for jobguard to wait for component jobs

- prow/scripts/cluster-integration/kyma-gke-integration-cli.sh
- Remove global addons injection as it's not needed anymore
> Remove global addons injection as it's not needed anymore

- prow/jobs/kyma/kyma-integration-gardener.yaml
- prow/scripts/cluster-integration/kyma-gardener-integration.sh
- Increase the timeout of the gardener nightly job to allow tests to finish
#1757
> Increase gardener nightly job timeout and test timeout

- development/tools/jobs/kyma/kyma_compass_integration_test.go
- prow/jobs/kyma/kyma-compass-integration.yaml
- Make the `gke-compass-integration` job trigger on every pr
#[6381](https://github.com/kyma-project/kyma/issues/6381)
> Change the gke-compass-integration job to run on every pr

- development/tools/jobs/kyma/kyma_integration_test.go
- prow/jobs/kyma/kyma-integration.yaml
- templates/templates/kyma-integration.yaml
- Remove the `strategy` flag 
[Issue #1750](https://github.com/kyma-project/test-infra/issues/1750)
> Remove the strategy flag 

- development/tools/jobs/kyma/kyma_gardener_integration_test.go
- development/tools/jobs/tester/preset/preset.go
- prow/config.yaml
- prow/jobs/kyma/kyma-integration-gardener-azure.yaml
- prow/scripts/cluster-integration/kyma-gardener-integration.sh
- templates/templates/prow-config.yaml
- Now kyma commands are printed in the logs.
- Made gardener presets, job and scripts generic to be able to have more jobs with other providers.
#1757
> Parametrize gardener jobs and presets and improve script

- development/tools/jobs/kyma/tests_test.go
- prow/jobs/kyma/tests/end-to-end/backup-restore-test/backup-restore-test-generic.yaml
- prow/jobs/kyma/tests/end-to-end/backup-restore-test/backup-restore-test.yaml
- templates/config.yaml
> disable old backup-restore-job, require new generic-backup-restore-job

- development/tools/jobs/testinfra/branchprotector_test.go
- prow/config.yaml
- templates/config.yaml
- Removed MinIO related jobs from release 1.9
> Remove not existing jobs from Branch Protector configuration

- prow/jobs/kyma/tests/rafter/rafter-tests-generic.yaml
- templates/config.yaml
- Make Rafter job required to pass
See also https://github.com/kyma-project/kyma/issues/6632
> Make Rafter job required

- prow/images/bootstrap-helm/Dockerfile
> use image with updated kubectl

- development/tools/jobs/kyma/kyma_release_candidate_test.go
- development/tools/jobs/tester/tester.go
- prow/jobs/kyma/kyma-release-candidate.yaml
- templates/templates/kyma-release-candidate.yaml
> Bump release image

- prow/scripts/cluster-integration/kyma-gke-backup-test.sh
- Upgrade Velero to 1.2.0
See https://github.com/kyma-project/kyma/issues/6672
> Upgrade Velero to 1.2.0

- development/tools/jobs/incubator/fluentbit/fluentbit_test.go
- prow/jobs/incubator/fluentbit/fluentbit.yaml
- Add jobs for fluentbit repo
See https://github.com/kyma-project/kyma/issues/6121
> Add jobs for fluentbit repo

- prow/jobs/scans/whitesource-periodics.yaml
- templates/templates/whitesource-periodics.yaml
Name of the environment variable is wrong. Regenerated the job file from template.
#1849
> env variable is wrong

- development/tools/jobs/incubator/components_test.go
- prow/jobs/incubator/compass/components/kyma-environment-broker/kyma-environment-broker-generic.yaml
- templates/config.yaml
- Removed optional flag from the KEB job definition
> Make KEB not optional

- prow/scripts/cluster-integration/helpers/start-wssagent.sh
Another env var that got a renaming.
#1849
> env var naming problem

- prow/scripts/cluster-integration/kyma-gke-backup-test.sh
- Added Rafter's resources to the 1st restoring phase
Buckets and Assets must be restored before AssetGroups.
kyma-project/kyma#6539
> Add Rafter's resources to the 1st restoring phase

- prow/jobs/test-infra/buildpack.yaml
- added  prow job for clonerefs
https://github.com/kyma-project/test-infra/issues/1198
> Prowjob for clonerefs

- development/vulnerabilities-scanner.sh
* Added logic for checking if `snyk test` found actual vulnerabilities for Slack notification
* JSON collecting for `snyk test` results for affected components
Fixes #1909
> kyma-vulnerabilities-scanner: Send Slack notification if any vulnerabilities found.

- prow/scripts/cluster-integration/kyma-gke-backup-test.sh
- Delete disks during the backup test
> Delete disks during the backup test

- prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh
- prow/scripts/cluster-integration/kyma-gke-upgrade.sh
- prow/scripts/kyma-upgrade-testing.sh
- Disable failing upgrade tests
> Disable failing upgrade tests

- prow/scripts/kyma-upgrade-testing.sh
> Enable upgrade test

- development/tools/jobs/helm-broker/helm_broker_test.go
- prow/jobs/helm-broker/helm-broker.yaml
- Change base image for hb job it's needed for this pr: https://github.com/kyma-project/helm-broker/pull/82
- https://github.com/kyma-project/kyma/issues/6644
> Change base image for hb job

- prow/scripts/cluster-integration/kyma-gke-backup-test.sh
- Fix backup disk deletion phase
> Fix backup disk deletion phase

- development/tools/jobs/kyma/kyma_integration_test.go
- prow/jobs/kyma/kyma-integration.yaml
- templates/templates/kyma-integration.yaml
- add experimental prow job which will execute upgrade of compass component.
See https://github.com/kyma-incubator/compass/issues/431
> Compass upgrade prototype job

- development/tools/jobs/kyma/tests_test.go
- prow/jobs/kyma/tests/end-to-end/backup/backup-generic.yaml
- templates/config.yaml
- Make backup test non-optional
> Make backup test non-optional

- development/tools/jobs/kyma/kyma_integration_test.go
- prow/jobs/kyma/kyma-integration.yaml
- templates/templates/kyma-integration.yaml
- fix path which is executed at pre-master-compass-prototype-gke-upgrade job.
> Fix execution path in pre-master-compass-prototype-gke-upgrade

- development/tools/jobs/kyma/components_test.go
- prow/jobs/kyma/components/permission-controller/permission-controller-generic.yaml
- templates/config.yaml
- mandatory permission-controller pipeline
https://github.com/kyma-project/kyma/issues/6905
> mandatory permission-controller pipeline

- development/tools/jobs/kyma/kyma_gardener_integration_test.go
- prow/jobs/kyma/kyma-integration-gardener-azure.yaml
Signed-off-by: Borja Clemente <borja.clemente.castanera@sap.com>
- Now the gardener integration job will run at 11:00 to raise more awareness.
> Change gardener schedule to run daily at 11

- development/tools/jobs/kyma/kyma_integration_test.go
- prow/jobs/kyma/kyma-integration.yaml
- templates/templates/kyma-integration.yaml
- Remove prototype compass upgrade job
> remove prototype upgrade job

- prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
- Remove invalid IPRanges 
- Fixes https://github.com/kyma-project/kyma/issues/6942
> Remove obsolete value for AKS nightly

- prow/images/bootstrap/Dockerfile
- Match kubectl version with the cluster version.
> Kubectl version

- prow/images/buildpack-golang/Dockerfile
- Bump buildpack-golang image
**Related PR**
https://github.com/kyma-project/test-infra/pull/1943
> Bump buildpack-golang image

- prow/images/kyma-cluster-infra/Dockerfile
> Bump cluster-infra image

- prow/images/bootstrap/Dockerfile
- Prepare Google SDK version with kubectl 1.16
- Adjust cluster version 
https://github.com/kyma-project/test-infra/issues/1859
> Update SDK and cluster version

- prow/images/buildpack-golang/Dockerfile
- Buildpack Golang with CLUSTER_VERSION=1.16 and kubectl 1.16
> buildpack-golang 1.16

- prow/images/buildpack-golang/Dockerfile
Reverts kyma-project/test-infra#1953
> Revert "buildpack-golang 1.16"

- prow/scripts/provision-vm-cli.sh
> Remove uninstall command

- .github/stale.yml
- Do not stale issues with "ci/future" label
> Do not stale issues with "ci/future" label

- development/tools/jobs/incubator/tests_test.go
- prow/jobs/incubator/compass/tests/kyma-environment-broker/e2e-provisioning/e2e-provisioning-test-generic.yaml
- templates/config.yaml
- Created a job for e2e-provisioning test
> Create a job for e2e-provisioning test

- development/tools/jobs/incubator/tests_test.go
- prow/jobs/incubator/compass/tests/e2e/provisioning/provisioning-test-generic.yaml
- templates/config.yaml
- Changed path of the e2e-provisioning test
> Change path of the e2e-provisioning test

- development/tools/cmd/dnscollector/main.go
> Dns cleaner

- development/tools/jobs/kyma/tests_test.go
- prow/jobs/kyma/tests/end-to-end/external-solution-integration/external-solution-integration-tests-generic.yaml
- prow/jobs/kyma/tests/end-to-end/external-solution-integration/external-solution-integration.yaml
- templates/config.yaml
- deactivate non generic external solution test after release 1.9
- require generic external solution test starting release 1.10
> Switch external solution test to generic makefile

- development/tools/jobs/kyma/tests_test.go
- prow/jobs/kyma/tests/contract/knative-channel-kafka/knative-channel-kafka-tests-generic.yaml
- templates/config.yaml
- In [this previous PR](https://github.com/kyma-project/kyma/pull/6999) (see job with name `pre-kyma-tests-contract-knative-channel-kafka Job succeeded.
`) we checked if the newly added job works (it was optional)
- Now that we are sure that it works, let's make it a non-optional job
> Make knative-channel-kafka prow job non optional

- prow/scripts/cluster-integration/kyma-gke-backup-test.sh
- Revert https://github.com/kyma-project/test-infra/pull/1973
See also https://github.com/kyma-project/kyma/issues/6539
> Revert changes to backup tests

- development/tools/jobs/kyma/kyma_github-release_test.go
- prow/jobs/kyma/kyma-github-release.yaml
- templates/templates/kyma-github-release.yaml
> temporary job removal

- development/tools/jobs/kyma/kyma_github-release_test.go
- prow/jobs/kyma/kyma-github-release.yaml
- templates/templates/kyma-github-release.yaml
This reverts commit bbc25b1c967e820127509ab0a1e2c1fe0f5d1def.
- Revert commit
> Revert "temporary job removal (#1980)"

- development/tools/jobs/kyma/kyma_integration_test.go
- prow/jobs/kyma/kyma-integration.yaml
- templates/templates/kyma-integration.yaml
- Switched to Rafter related resource group
> Fix Storage Account cleaner

- prow/jobs/kyma/kyma-kind-integration.yaml
- Switched to @michal-hudy fork
> Switch Kind jobs to Michal's repo

- development/prow-addons-ctrl-manager/pkg/slack/reporter.go
- development/tools/cmd/dnscollector/main.go
- development/tools/pkg/clusterscollector/collector.go
- development/tools/pkg/diskscollector/collector.go
- development/tools/pkg/dnscollector/collector.go
- development/tools/pkg/dnscollector/collector_test.go
- development/tools/pkg/gcscleaner/cleaner_test.go
- development/tools/pkg/gcscleaner/storage/bucket.go
- development/tools/pkg/vmscollector/collector.go
- development/tools/pkg/vulnerabilitycollector/vulnerabilitycollector.go
- stability-checker/internal/notifier/templates.go
Correcting unintentional changes placed in strings and comments.
> Correct unintentional changes.

- prow/scripts/cluster-integration/kyma-gardener-integration.sh
- Removed injecting testing addons in integration job
- ...
- ...
#1993
> Remove AddonsConfiguration injection from scripts.

- development/tools/jobs/kyma/kyma_compass_integration_test.go
- prow/jobs/kyma/kyma-compass-integration.yaml
Add optional Compass integration job for development of tests for Azure on Gardener.
- Added `pre-master-kyma-gke-compass-integration-provisioner-test` optional job.
Tests #azure
> Add optional Compass integration job for development of tests for Azure on Gardener

- development/create-service-accounts-for-fork.sh
- development/tools/jobs/releases/releases.go
- development/tools/pkg/clusterscollector/collector.go
> Fix tests 2

- prow/jobs/kyma/kyma-compass-integration.yaml
- Fix optional Compass Provisioner job extra_ref path_alias
See also [compass#613](https://github.com/kyma-incubator/compass/pull/613)
> Fix optional Compass Provisioner job extra_ref path_alias

- prow/jobs/kyma/kyma-integration.yaml
- prow/scripts/provision-vm-and-start-kyma.sh
- templates/templates/kyma-integration.yaml
> Make Minikube an optional

- prow/scripts/provision-vm-and-start-kyma.sh
> Revert fix

- prow/jobs/kyma/kyma-integration-gardener-azure.yaml
- prow/scripts/cluster-integration/kyma-gardener-integration.sh
- Use production profile on Gardener job
See https://github.com/kyma-project/test-infra/issues/1998
> Use production profile on Gardener job

- development/prow-installer/cmd/installer/main.go
- development/prow-installer/config/prow-installer-config.yaml
- development/prow-installer/pkg/cluster/cluster.go
- development/prow-installer/pkg/cluster/wrapped.go
- development/prow-installer/pkg/config/config.go
Rewritten cluster package for cluster creation based on a config file. Tests will be written in a followup PR.
- Rewritten cluster package for cluster creation based on a config file.
#2022
> Cluster pkg extend

- prow/jobs/scans/whitesource-periodics.yaml
- templates/config.yaml
Adding knative-kafka whitesource scans
> Adding knative-kafka whitesource scan

- prow/scripts/cluster-integration/kyma-gardener-integration.sh
- Change vnet cidr to gardener defaults.
> Change vnet cidr to gardener default

- prow/scripts/cluster-integration/helpers/provision-gke-cluster.sh
- prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
- prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
- Use production profiles on long-lasting clusters
See https://github.com/kyma-project/test-infra/issues/1998
> Use production profiles on long-lasting clusters

- development/container-vulnerabilities.sh
- development/tools/Gopkg.lock
- development/tools/Gopkg.toml
- development/tools/cmd/vulnerabilitycollector/README.md
- development/tools/cmd/vulnerabilitycollector/main.go
- development/tools/pkg/vulnerabilitycollector/vulnerabilitycollector.go
- prow/jobs/kyma/kyma-vulnerability-scanner.yaml
GCP Vulnerability collector has an issue. I assume it was because of the dryRun flag missing. I also changed it to run twice a month now instead of only once.
- add dryRun flag
- change from running once a month to (about) every 14 days
#2016
> Fix gcp vulnerability collector

- development/container-vulnerabilities.sh
vendor dir is missing
- add vendor download
#2019
> add vendor checkout

- development/prow-installer/cmd/installer/main.go
- development/prow-installer/config/prow-installer-config.yaml
- development/prow-installer/pkg/config/config.go
- development/prow-installer/pkg/storage/storage_test.go
Create buckets based on a list. This adds the ability to create multiple buckets instead of one.
- bucket creation based on a list from config yaml
- fix tests for storage package
> Multiple buckets creation based on a config

- prow/scripts/cluster-integration/helpers/cleanup-cluster.sh
- prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
- prow/scripts/cluster-integration/kyma-gardener-integration.sh
- prow/scripts/cluster-integration/kyma-gke-integration-cli.sh
- prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
- Use CLI to install Kyma on long-lasting clusters
See https://github.com/kyma-project/kyma/issues/7221
> Use CLI to install Kyma on long-lasting clusters

- development/prow-installer/config/prow-installer-config.yaml
- development/prow-installer/pkg/config/config.go
> updated prow-installer-config.yaml

- prow/scripts/cluster-integration/kyma-gardener-integration.sh
- Increase node count for gardener job
> Increase node count for gardener job

- prow/scripts/cluster-integration/kyma-gardener-integration.sh
- Change Gardener cluster version
> Change Gardener cluster version

- development/tools/jobs/incubator/tests_test.go
- prow/jobs/incubator/compass/tests/connectivity-adapter/connectivity-adapter-tests-generic.yaml
- templates/config.yaml
- Make Connectivity Adapter Tests job required
> Make Connectivity Adapter job required

- development/prow-installer/cmd/installer/main.go
- development/prow-installer/config/prow-installer-config.yaml
> Config fix

- prow/jobs/kyma/kyma-kind-integration.yaml
- Disabled to not waste resources
> Disable kind jobs on PRs

- prow/scripts/cluster-integration/kyma-gke-backup-test.sh
- Bump default backup-plugins image for this [PR](https://github.com/kyma-project/kyma/pull/7137/files)
- Image hash can be retrieved from this log: <https://storage.googleapis.com/kyma-prow-logs/logs/post-kyma-components-backup-plugins/1230904068168224768/build-log.txt>
Backup/Restore documentation can be found here: https://kyma-project.io/docs/components/backup/#tutorial-tutorial
https://github.com/kyma-project/kyma/pull/7137/files
https://github.com/kyma-project/kyma/issues/7294
> Bump backup-plugins image

- prow/cluster/00-deck-patch.yaml
> Update deck-patch to include build-cluster config

- prow/jobs/test-infra/buildpack.yaml
- Create template for newly created image. 
> buildpack java-node fix

- prow/jobs/test-infra/buildpack.yaml
> postsubmit job

- prow/images/whitesource-scanner/Dockerfile
- Use new base image adjusted to node.js
https://github.com/kyma-project/test-infra/issues/2061
> Update Whitesource image

- prow/cluster/04-branchprotector_cronjob.yaml
> Update branchprotector image version

- development/prow-installer/cmd/k8s/main.go
- development/prow-installer/pkg/roles/roles_test.go
- development/prow-installer/pkg/serviceaccount/mocks/IAM.go
- development/prow-installer/pkg/serviceaccount/serviceaccount_test.go
> Fixed failing prow-installer tests

- prow/scripts/cluster-integration/kyma-gardener-integration.sh
- Add Zone to kyma gardener job
#2086
> Add zones to azure

- prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
- prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
- Apply Github connector override
https://github.com/kyma-project/test-infra/issues/2063
> Dex overrides

- development/prow-installer/Makefile
- development/prow-installer/before-commit.sh
- development/prow-installer/pkg/secrets/secrets_test.go
- prow/jobs/test-infra/validation.yaml
Make script and job to validate prow installer code.
- Make script and job to validate prow installer code.
Resolves #2091
> Validation job for prow installer

- prow/scripts/cluster-integration/helpers/deprovision-gardener-cluster.sh
- Speedup gardener jobs by not waiting for deletion as it might take a very long time.
https://github.com/kyma-project/kyma/issues/7068
> Speedup gardener jobs by not waiting for deletion

- prow/jobs/scans/whitesource-periodics.yaml
- prow/scripts/cluster-integration/helpers/start-wssagent.sh
- templates/templates/whitesource-periodics.yaml
- Update whitesource image
- Resolve console dependencies
https://github.com/kyma-project/test-infra/issues/2061
> Console-whitesource scan

- development/tools/jobs/console/console_tests_test.go
- prow/jobs/console/tests/console-tests.yaml
- Run Whitesource job when kyma-project/console packages are changed.
> Console-Whitesource job

- development/tools/jobs/console/console_tests_test.go
- prow/jobs/console/tests/console-tests.yaml
- Fix presets for Whitesource job
> Fix presets

- development/tools/jobs/console/console_tests_test.go
- prow/jobs/console/tests/console-tests.yaml
> optional job

- prow/jobs/scans/whitesource-periodics.yaml
- templates/config.yaml
-Add whitesource jobs (api-gateway, dex)
> Add new scans

- prow/jobs/incubator/compass/compass-integration.yaml
- templates/templates/compass-integration.yaml
This issue is connected with: https://github.com/kubernetes/test-infra/pull/16602
> Add test-grid annotation for compass integration job

- prow/jobs/scans/whitesource-periodics.yaml
- templates/config.yaml
- templates/templates/whitesource-periodics.yaml
Go modules support for whitesource scan on api-gateway and dex.
- modified prow jobs to support go modules scan
- added `base_ref` in config.yaml for defining base branch of a project
- updated templates for tests
> dex and apigateway job set to golang-mod

- development/tools/jobs/incubator/tests_test.go
- prow/jobs/incubator/compass/tests/e2e/provisioning/provisioning-test-generic.yaml
- templates/config.yaml
- e2e-provisioning test required
> Make e2e-provisioning test required

- prow/jobs/incubator/compass/compass-integration.yaml
- prow/scripts/provision-vm-compass.sh
- templates/templates/compass-integration.yaml
In jobs `pre-master-compass-integration` we run Kyma inside VM and execute tests.
Tests publish artifacts, but to display them on PRow, we need to copy them from VM to Prow container.
If this change succeed, I will remove TODO from code.
> Publish artifacts in compass vm integration

- prow/scripts/cluster-integration/kyma-integration-gardener-gcp.sh
- Fix wrong documentation on permissions needed to run a GCP gardener cluster
https://github.com/kyma-project/kyma/issues/7068
> Correct permission docs for gardener gcp job

- prow/jobs/scans/whitesource-periodics.yaml
- templates/config.yaml
- Create two separate jobs for Kyma whitesource scan (mod, dep)
> Whitesource scan

- development/tools/jobs/incubator/third-party-images/fluent-bit/fluent_bit_test.go
- development/tools/jobs/incubator/third-party-images/kiali/kiali_test.go
- development/tools/jobs/incubator/third-party-images/prometheus-node-exporter/prometheus_node_exporter_test.go
- prow/jobs/incubator/third-party-images/fluent-bit/fluent-bit.yaml
- prow/jobs/incubator/third-party-images/kiali/kiali.yaml
- prow/jobs/incubator/third-party-images/prometheus-node-exporter/prometheus-node-exporter.yaml
- Add jobs for Kiali and Node Exporter images
> Add jobs for Kiali and Node Exporter images

- prow/jobs/incubator/compass/compass-integration.yaml
- prow/scripts/provision-vm-compass.sh
- templates/templates/compass-integration.yaml
- added new, optional job `pre-master-compass-integration-stable-cli`, if everything will be fine, then changes will be applied to `pre-master-compass-integration` 
> Run compass integration jobs using stable kyma cli

- prow/images/alpine-kubectl/Dockerfile
> Fix wget command in alpine-kubectl

- development/tools/jobs/incubator/compass/compass_integration_test.go
- prow/jobs/incubator/compass/compass-integration.yaml
- templates/templates/compass-integration.yaml
> Cleanup compass integration tests after switching to stable Kyma CLI

- prow/jobs/incubator/third-party-images/docker-registry/registry.yaml
- add job to generate images for docker-registry in third-party-images repo
> Add job for Docker Registry in third-party-images repo

- prow/scripts/cluster-integration/helpers/start-wssagent.sh
> Whitesource

- prow/scripts/cluster-integration/kyma-gke-compass-integration.sh
- Enable Packages for kyma-gke-compass-integration
- Disable legacy E2E tests for Packages
https://github.com/kyma-incubator/compass/pull/892
> Enable Packages for kyma-gke-compass-integration

- prow/images/alpine-kubectl/Dockerfile
- Bumped kubectl to 1.17
Related image bump PR: https://github.com/kyma-project/kyma/pull/7571
> Bumped kubectl to 1.17

- development/tools/jobs/incubator/third-party-images/docker-registry/docker_registry_test.go
- development/tools/jobs/incubator/third-party-images/minio-mc/minio_mc_test.go
- development/tools/jobs/incubator/third-party-images/minio/minio_test.go
- prow/jobs/incubator/third-party-images/minio-mc/minio-mc.yaml
- prow/jobs/incubator/third-party-images/minio/minio.yaml
- update config for docker-registry
- add job for MinIO image
- add job for MinIO mc image
> Add job for MinIO and MinIO mc in third-party-images repo

- prow/config.yaml
- templates/templates/prow-config.yaml
- Add branch protection for third-party-images
> Add branch protection for third-party-images

- prow/scripts/cluster-integration/kyma-gke-compass-integration.sh
Reverts kyma-project/test-infra#2138
> Revert "Enable Packages for kyma-gke-compass-integration"

- development/tools/jobs/kyma/kyma_integration_test.go
- prow/jobs/kyma/kyma-integration.yaml
- templates/templates/kyma-integration.yaml
- Run integratiom tests after` kyma-installer` changes.
> Kyma installer integration jobs

- development/tools/jobs/kyma/kyma_compass_integration_test.go
- prow/jobs/kyma/kyma-compass-integration.yaml
Reverts kyma-project/test-infra#2089
> Make pre-master-gke-compass-integration job required

- prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
- prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
- prow/scripts/library.sh
- Update stackdriver-metadata-agent memory settings
https://github.com/kyma-project/test-infra/issues/2105
> Update memory settings

- docs/prow/README.md
- docs/prow/prow-naming-convention.md
- First version of the document describing naming convention for GCP resources.
https://github.com/kyma-project/test-infra/issues/1945
> GCP resources naming

- prow/jobs/console/tests/console-tests.yaml
- prow/jobs/scans/whitesource-periodics.yaml
- prow/scripts/cluster-integration/helpers/start-wssagent.sh
- templates/templates/whitesource-periodics.yaml
- Bump Whitesource images
- Change paths to absolute
> Bump Whitesource images

- prow/jobs/incubator/compass/tests/provisioner-tests/provisioner-whitesource.yaml
- Add WhiteSource job for Runtime Provisioner
Refers to https://github.com/kyma-incubator/compass/issues/1011
> Provisioner optional WhiteSource job on PR

- prow/jobs/incubator/compass/tests/provisioner-tests/provisioner-whitesource.yaml
- Adjust the job to work on Runtime Provisioner component level.
Refers to https://github.com/kyma-incubator/compass/issues/1011
> Fix Provisioner WhiteSource job

- prow/jobs/incubator/compass/tests/provisioner-tests/provisioner-whitesource.yaml
Refers to https://github.com/kyma-incubator/compass/issues/1011
> Add kyma-incubator ref to Provisioner WhiteSource job

- prow/scripts/cluster-integration/kyma-gke-compass-integration.sh
- GKE Compass Integration job modified to pass disableLegacyConnectivity flag
> Added flag for disabling legacy connectivity

- prow/jobs/kyma/kyma-github-release.yaml
- prow/jobs/kyma/kyma-release-candidate.yaml
- prow/jobs/kyma/kyma-release-upgrade.yaml
- templates/templates/kyma-github-release.yaml
- templates/templates/kyma-release-candidate.yaml
> Disable release jobs for changes in documentation

- development/tools/jobs/kyma/kyma_integration_test.go
- prow/jobs/kyma/kyma-integration.yaml
- templates/templates/kyma-integration.yaml
> Make backup job optional

- prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh
- prow/scripts/cluster-integration/kyma-gke-upgrade-xip.sh
- prow/scripts/cluster-integration/kyma-gke-upgrade.sh
- Delete the previous kyma-installer during upgrade
> Delete the previous kyma-installer during upgrade

- prow/config.yaml
- templates/templates/prow-config.yaml
> Add preset for AWS on gardener

- development/tools/Dockerfile
There was a possible name conflict between the our prebuilt tools directory and prow tools directory. The folder got replaced by k8s prow tools directory. This PR changes naming for directory of our prebuilt tools in an image.
- Rename /tools to /prow-tools in development/tools/Dockerfile
> Rename /tools to /prow-tools in development/tools/Dockerfile

- development/tools/build-cleaners.sh
Adding CGO_ENABLED=0 makes the linked C part also static into the binary, reducing compatibility risk.
More info: https://medium.com/@diogok/on-golang-static-binaries-cross-compiling-and-plugins-1aed33499671
- ...
- ...
- ...
> Add CGO_ENABLED=0 to prow tools

- prow/scripts/cluster-integration/helpers/create-azure-event-hubs-secret.sh
Change the output of the azure-event-hubs overrides file to adapt to the new Chart structure
See also https://github.com/kyma-project/kyma/issues/7507
> Change the output of the azure-event-hubs overrides file to adapt to the new Chart structure

- prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
Enabled provisioning ingressgateway IP in all availibility zones.
Added console URL test.
See #2212
> Changed ingressgateway IP to Standard SKU.

- prow/scripts/cluster-integration/helpers/install-kyma.sh
- prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
- prow/scripts/cluster-integration/kyma-gke-backup-test.sh
- prow/scripts/cluster-integration/kyma-gke-compass-integration.sh
- prow/scripts/cluster-integration/kyma-gke-integration.sh
- prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
- prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh
- prow/scripts/cluster-integration/kyma-gke-upgrade-xip.sh
- prow/scripts/cluster-integration/kyma-gke-upgrade.sh
- Add Application Registry detailed error override
See the issue [#7767](https://github.com/kyma-project/kyma/issues/7767)
> Add Application Registry detailed error override

- prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
Upgraded DNS operations for AKS long lasting cluster builds.
- added logging functions
- getting IPs from cloudDNS with gcloud
See #2205
> Added logging functions

- prow/jobs/kyma/kyma-compass-integration.yaml
- Add a temporary Compass job for release 1.11
https://github.com/kyma-project/kyma/issues/7707
> Add temporary Compass job for 1.11 release

- development/assetstore-gcp-bucket-cleaner.sh
- development/tools/jobs/kyma/kyma_integration_test.go
- prow/jobs/kyma/kyma-integration.yaml
- templates/templates/kyma-integration.yaml
Edited assetstore-gcp-buckets-cleaner.sh to run a binary instead of building and vendoring tools.
- ...
- ...
- ...
> Assetstore cleaner job binary execution

- development/github-stats.sh
- development/tools/jobs/kyma/kyma_integration_test.go
- prow/jobs/kyma/kyma-integration.yaml
- templates/templates/kyma-integration.yaml
Edited GitHub-stats job to use prebuilt binary instead of building one.
- ...
- ...
- ...
> GitHub-stats job update

- prow/scripts/cluster-integration/kyma-integration-gardener-azure.sh
- prow/scripts/cluster-integration/kyma-integration-gardener-gcp.sh
- Fix Gardener cluster version
> Fix Gardener cluster version

- prow/jobs/kyma/kyma-integration.yaml
- templates/templates/kyma-integration.yaml
Cleaner jobs were requesting too much resources(1Gi memory, 400m CPU). Since we are using prebuilt binaries right now it's best to squish those numbers to reasonable ones. Changed the values to 100Mi memory and 50m CPU. 
- changed resources requests down to 100Mi Memory and 50m CPU.
> Resources requests edit in cleaner jobs.

- prow/images/clonerefs/Dockerfile
Preparation for prow upgrade. Upgrade clonerefs base image.
See #2230
> Updated base image to version v20200319-1aea24112

- development/tools/jobs/testinfra/branchprotector_test.go
- prow/config.yaml
- prow/jobs/kyma/kyma-integration.yaml
- templates/config.yaml
- templates/templates/kyma-integration.yaml
- Make release backup job optional
> Make release backup job optional

- development/tools/build-cleaners.sh
Added logic to omit files with `nobuild.lock` file.
- ...
- ...
- ...
> Build fix of build-cleaners.sh in test-infra-prow-tools job

- development/tools/jobs/tester/tester.go
- prow/jobs/cli/cli-integration.yaml
- prow/jobs/incubator/api-gateway/api-gateway.yaml
- prow/jobs/incubator/compass/compass-integration.yaml
- prow/jobs/incubator/octopus/octopus.yaml
- prow/jobs/rafter/rafter.yaml
- templates/config.yaml
- templates/templates/compass-integration.yaml
> Update buildpack-golang-kubebuilder2 image

- development/tools/jobs/testinfra/validate_test.go
- prow/jobs/test-infra/validation.yaml
> validate-configs job bump image to go1.13

- prow/scripts/cluster-integration/kyma-integration-gardener-aws.sh
- prow/scripts/cluster-integration/kyma-integration-gardener-azure.sh
- prow/scripts/cluster-integration/kyma-integration-gardener-gcp.sh
- Increase gardener jobs min autoscaler
> Increase min. autoscaler value for gardener jobs

- prow/cluster/components/33-crier_deployment.yaml
- prow/cluster/components/34-crier_rbac.yaml
- prow/config.yaml
- templates/templates/prow-config.yaml
Adding crier config and deployment yaml files. We are going to replace prow-addons-ctrl-manager slack notification feature with crier slack reporter.
> Crier deployment

- development/tools/Makefile
- prow/images/prow-tools/Dockerfile
- prow/images/prow-tools/Makefile
- prow/images/prow-tools/README.md
- prow/jobs/test-infra/buildpack.yaml
> Move prow-tools Dockerfile to prow/images

- docs/prow/production-cluster-configuration.md
Updated revision from which we are using prow images after upgrade.
> Update upstream compatibile revision

- prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh
- prow/scripts/cluster-integration/kyma-gke-upgrade-xip.sh
- prow/scripts/cluster-integration/kyma-gke-upgrade.sh
> Update job definition

- prow/jobs/kyma/kyma-compass-provisioner-tests.yaml
- Skip report of Provisioner job
> Skip report of Provisioner job

- development/README.md
Updated development dir readme to match recent changes and agreements.
> readme update

- prow/images/prow-tools/Dockerfile
- prow/jobs/test-infra/buildpack.yaml
> add jobguard build to prow-tools Dockerfile

- prow/scripts/cluster-integration/kyma-integration-gardener-aws.sh
- prow/scripts/cluster-integration/kyma-integration-gardener-gcp.sh
- Remove prod profile from aws & gcp gardener jobs
> Remove prod profile from aws & gcp gardener jobs

- prow/branchprotector-config.yaml
Updated branchprotector-config to match new release.
kyma-project/kyma#8252
> updated branchprotector config

- prow/images/buildpack-node/Dockerfile
- prow/images/buildpack-node/license-puller.sh
- Add license puller  to node buildpack
https://github.com/kyma-project/console/issues/1744
> Add license puller to node buildpack

- development/tools/jobs/kyma/kyma_gardener_integration_test.go
- prow/jobs/kyma/kyma-integration-gardener-azure.yaml
- prow/scripts/cluster-integration/kyma-integration-gardener-aws.sh
- prow/scripts/cluster-integration/kyma-integration-gardener-azure.sh
- prow/scripts/cluster-integration/kyma-integration-gardener-gcp.sh
- Adapt to kyma provision command changes
See https://github.com/kyma-project/cli/issues/355
> Adapt to kyma provision command changes

- development/tools/jobs/kyma/kyma_gardener_integration_test.go
- prow/jobs/kyma/kyma-integration-gardener-azure.yaml
- Run Gardener Azure job more frequently
> Run Gardener Azure job more frequently

- development/tools/jobs/incubator/third-party-images/jaeger-operator/jaeger_operator_test.go
- prow/jobs/incubator/third-party-images/jaeger-operator/jaeger-operator.yaml
- Add Jaeger operator custom image jobs
> Add Jaeger operator custom image jobs

- prow/scripts/cluster-integration/helpers/create-azure-event-hubs-secret.sh
- the knative-eventing-channel-kafka component has been renamed to knative-eventing-kafka
this PR will update this component name also in the azure secret generation script
kyma-project/kyma#7248
> change component name for knative kafka override

- development/tools/jobs/incubator/third-party-images/kiali-operator/kiali_operator_test.go
- prow/jobs/incubator/third-party-images/kiali-operator/kiali-operator.yaml
- Add Kiali operator custom image jobs
> Add Kiali operator custom image jobs

- prow/images/alpine-kubectl/Dockerfile
- prow/images/alpine-kubectl/README.md
- Update outdated readme
- Add grep
> Update alpine-kubectl image

- prow/scripts/validate-generated.sh
> Remove `make resolve` stage in validate-generated.sh

- development/tools/jobs/kyma/tests_test.go
- prow/jobs/kyma/tests/integration/cluster-users/cluster-users-tests-generic.yaml
- templates/config.yaml
- Set prowjobs to `until: 1.12`
- Implements https://github.com/kyma-project/kyma/issues/8168
> Remove cluster-users from master branch

- prow/branchprotector-config.yaml
- prow/config.yaml
- templates/templates/prow-config.yaml
- enabled dismiss-stale-reviews option for test-infra, cli and rafter
- ...
- ...
https://github.com/kyma-project/test-infra/issues/2327
> Enable dismiss-stale-reviews

- prow/plugins.yaml
This reverts commit 3536597d03c63a83531a4b35cf604377b6fc88d1.
- Reverted as it doesn't work...
> Revert "Enable project plugin (#2333)"

- prow/plugins.yaml
https://github.com/kyma-project/test-infra/pull/2331
> Added branchprotector-config to config update plugin

- prow/images/prow-tools/Dockerfile
Updated Golang to version 1.14.2 in build stage of prow-tools and added /prow-tools directory to PATH for better access to the binaries.
- ...
- ...
- ...
> bump golang to version 1.14.2 and add prow-tools dir to PATH

- prow/branchprotector-config.yaml
- prow/config.yaml
- templates/templates/prow-config.yaml
- removed duplicate statements
- ...
- ...
> Remove duplicate statements for branch-protector

- development/tools/jobs/incubator/components_test.go
- prow/jobs/incubator/compass/components/external-services-mock/external-services-mock-generic.yaml
- templates/config.yaml
- Set external-services-mock job as required
> Make external-services-mock job required

- development/tools/jobs/console/console_test.go
- prow/jobs/console/core/core-tmp.yaml
- templates/config.yaml
- new console core job is optional
> Core job is optional

- prow/config.yaml
- templates/templates/prow-config.yaml
- Authentication that allows to rerun jobs.
> Github authentication

- docs/prow/prow-jobs.md
> Removed fixed commit, added link to current commit sha

- prow/images/whitesource-scanner/Dockerfile
> New Whitesource agent

- prow/config.yaml
- templates/templates/prow-config.yaml
This PR adds report template for Crier.
- ...
- ...
- ...
> Add report template for Crier

- prow/scripts/cluster-integration/helpers/generate-and-export-letsencrypt-TLS-cert.sh
Added mising escape slash in docker run
> Fix_certbot_docker_run

- prow/config.yaml
- templates/templates/prow-config.yaml
> Crier postsubmit report fix

- prow/scripts/cluster-integration/helpers/get-letsencrypt-cert.sh
Our nightly cluster is not working https://console.nightly.a.build.kyma-project.io/  NET::ERR_CERT_COMMON_NAME_INVALID
- fixed regression from https://github.com/kyma-project/test-infra/commit/3166960dca25f7ab579eb569c40d94293c890fe0
> Add wildcard to certbot domain

- prow/scripts/cluster-integration/helpers/generate-and-export-letsencrypt-TLS-cert.sh
- prow/scripts/cluster-integration/helpers/get-letsencrypt-cert.sh
Too soon, too fast: https://github.com/kyma-project/test-infra/pull/2374
- fixed the domain name
> Fix wildcard [again]

- prow/config.yaml
- templates/templates/prow-config.yaml
It was meant to add this change along with the other changes for slack reporter.
- Added ShortSHA printing instead of full SHA in slack report.
#2286
> ShortSHA print for slack report

- prow/config.yaml
- templates/templates/prow-config.yaml
Added reports to slack for batch jobs
> Report batch failures to slack

- prow/cluster/components/14-deck_rbac.yaml
- prow/cluster/components/15-deck_deployment.yaml
- prow/config.yaml
- templates/templates/prow-config.yaml
- Enable Prowjobs rerun feature for [cluster-access team](https://github.com/orgs/kyma-project/teams/cluster-access)
> Enable job rerun

- prow/scripts/cluster-integration/kyma-gke-compass-integration.sh
- Enable Pushgateway for Kyma GKE Compass Integration
https://github.com/kyma-incubator/compass/issues/1235
> Enable Pushgateway for Kyma GKE Compass Integration

- prow/scripts/cluster-integration/kyma-gke-compass-integration.sh
- Increased timeout for Provisioner test to 3h
> Increased timeout for Provisioner test

- development/tools/jobs/kyma/kyma_integration_test.go
- prow/config.yaml
- prow/jobs/kyma/kyma-integration.yaml
- templates/templates/kyma-integration.yaml
- templates/templates/prow-config.yaml
- Slack changes related to the move from CX to T&I workspace
> Slack updates

- prow/scripts/provision-vm-cli.sh
**Related issues**
https://github.com/kyma-project/cli/issues/433
> re-try for gcloud commands failing due permission denied

- prow/branchprotector-config.yaml
- templates/config.yaml
> fix typo in jobname

- development/tools/jobs/kyma/kyma_gke_compass_integration_test.go
- prow/branchprotector-config.yaml
- prow/jobs/kyma/kyma-gke-compass-integration.yaml
- templates/config.yaml
- templates/templates/kyma-gke-compass-integration.yaml
- Make kyma-gke-compass-integration optional for releases
> Make kyma-gke-compass-integration optional for releases

- prow/scripts/lib/testing-helpers.sh
- stability-checker/deploy/chart/stability-checker/values.yaml
- stability-checker/deploy/stability-checker/testing-helpers.sh
> Fix script

- prow/jobs/cli/cli.yaml
- Add privileged mode to CLI jobs to run DinD, needed for changelog generation on releases.
https://github.com/kyma-project/cli/issues/465
> Add privileged mode to CLI jobs to run DinD

- stability-checker/cmd/stability-checker/main.go
- stability-checker/deploy/chart/stability-checker/values.yaml
- stability-checker/internal/notifier/notifier.go
- Fixed constructor in stability-checker
> Fix constructor in stability-checker

- development/tools/cmd/certbotauthenticator/main.go
- development/tools/go.sum
Improved logging of executed actions and confirmation message. Resolves #2370
> Certbot authenticator logging improvement

- prow/jobs/incubator/compass/components/metris/metris-generic.yaml
- prow/jobs/kyma/components/api-gateway-migrator/api-gateway-migrator-generic.yaml
- prow/jobs/kyma/components/nats-init/nats-init-generic.yaml
- prow/jobs/kyma/kyma-gke-compass-integration.yaml
- prow/jobs/kyma/kyma-kind-integration.yaml
- prow/jobs/kyma/tests/function-controller/function-controller-tests-generic.yaml
- prow/jobs/kyma/tools/event-subscriber/event-subscriber-generic.yaml
- templates/templates/component.yaml
- templates/templates/generic-component.yaml
- templates/templates/knative-kafka-component.yaml
- templates/templates/kyma-gke-compass-integration.yaml
Defined dummy channel override for Crier's Slack reporter.
- ...
- ...
- ...
#2311
> Dummy channel override instead of skip_report:true

- prow/images/alpine-kubectl/Dockerfile
- prow/images/alpine-kubectl/README.md
- Update readme
- Add helm3
- Required for https://github.com/kyma-project/kyma/issues/8517
> Add helm3 to alpine-kubectl

- prow/jobs/kyma/kyma-gke-compass-integration.yaml
- templates/templates/kyma-gke-compass-integration.yaml
- Added jobs for testing `kyma-gke-compass-integration`
For testing https://github.com/kyma-project/test-infra/pull/2406
> Add jobs for testing compass-integration script

- development/tools/jobs/kyma/kyma_gke_compass_integration_test.go
- prow/branchprotector-config.yaml
- prow/jobs/kyma/kyma-gke-compass-integration.yaml
- prow/scripts/cluster-integration/kyma-gke-compass-integration.sh
- templates/config.yaml
- templates/templates/kyma-gke-compass-integration.yaml
- Fix kyma-gke-compass-integration script
Fixes https://github.com/kyma-project/test-infra/issues/2226
> Fix kyma-gke-compass-integration script

- development/tools/jobs/incubator/compass/development_artifacts_test.go
- prow/jobs/incubator/compass/compass-development-artifacts.yaml
- prow/scripts/build-compass-development-artifacts.sh
- Prepare job and scripts for building Compass artifacts, required for PoC of separating Compass installation from Kyma
PR to Compass repo with code required to generate artifacts: https://github.com/kyma-incubator/compass/pull/1405
> Prepare job for building Compass artifacts

- development/tools/go.mod
- development/tools/go.sum
- prow/jobs/kyma/kyma-integration.yaml
- prow/scripts/cluster-integration/kyma-gke-upgrade-e2e.sh
- templates/templates/kyma-integration.yaml
Add a prow job for Kyma end to end upgrade test.
- https://github.com/kyma-project/kyma/issues/7512.
> Add E2E upgrade job

- docs/prow/authorization.md
- docs/prow/crier.md
> Crier documentation

- prow/scripts/build-compass-development-artifacts.sh
- Remove timestamp from PR artifacts docker tags
> Remove timestamp from Compass PR artifacts docker tags

- prow/images/prow-tools/Dockerfile
Additional PR resolving conversation in #2385. Added checkconfig binary and unique-jobs-name binary to prow-tools image.
The image will be used additional in `pre-test-infra-validate-configs` job
- ...
- ...
- ...
#2339
> add checkconfig and unique-jobs-name compiling to prow-tools image

- development/tools/go.sum
- development/tools/jobs/kyma/kyma_integration_test.go
- development/tools/jobs/tester/preset/preset.go
- prow/config.yaml
- prow/jobs/kyma/kyma-integration.yaml
- templates/templates/kyma-integration.yaml
- templates/templates/prow-config.yaml
Replaced sa for cleaner due to security hardening
> Switch assetstore bucket cleaner to sa-prow-job-resource-cleaner

- prow/scripts/cluster-integration/kyma-gke-upgrade-e2e.sh
- Provide the domain value for the E2E upgrade test.
https://github.com/kyma-project/kyma/issues/7512
> Provide the domain value for the E2E upgrade test

- prow/branchprotector-config.yaml
- templates/templates/branchprotector-config.yaml
- enabled 'dismiss_stale_reviews'
https://github.com/kyma-project/test-infra/issues/2327
> Enable 'dismiss_stale_reviews' on both orgs

- development/tools/jobs/tester/tester.go
- prow/jobs/cli/cli.yaml
- Use latest toolbox for CLI jobs
> Use latest toolbox for CLI jobs

- prow/config.yaml
- prow/scripts/cluster-integration/helpers/start-wssagent.sh
- templates/templates/prow-config.yaml
> Added env to preset.

- prow/config.yaml
- prow/scripts/cluster-integration/helpers/start-wssagent.sh
- templates/templates/prow-config.yaml
> var name correction

- prow/config.yaml
- templates/templates/prow-config.yaml
Switch preset to use sap-prow-workloads KMS.
See #2399
> Move to workloads kms.

- prow/scripts/cluster-integration/helpers/create-image.sh
Added missing dolar sign.
See #2399
> Added missing dolar sign.

- prow/scripts/cluster-integration/helpers/create-image.sh
Exported credentials variable.
See #2399
> export credentials variable

- prow/scripts/cluster-integration/kyma-integration-gardener-azure.sh
- do not use exit in a cleanup function
Resolves kyma-project/kyma#8700
> Fix azure namespace cleanup

- prow/scripts/build-kyma-development-artifacts.sh
- removed building kyma-operator from pipeline
> removed building kyma-operator from pipeline

- prow/config.yaml
- templates/templates/prow-config.yaml
Changed gcp project name where KMS keys are located
> Change project name for KMS preset

- development/tools/jobs/kyma/kyma_gke_separate_compass_integration.go
- prow/jobs/kyma/kyma-gke-separate-compass-integration.yaml
- templates/templates/kyma-gke-separate-compass-integration.yaml
- Add missing preset to Kyma GKE Separate Compass integration
> Add missing preset to Kyma GKE Separate Compass integration

- development/tools/cmd/githubstats/main.go
> Fix linter errors for githubstats

- prow/scripts/cluster-integration/kyma-gke-separate-compass-integration.sh
- Make is-installed.sh script executable for Separate Compass pipeline
> Make is-installed.sh script executable for Separate Compass pipeline

- prow/images/alpine-kubectl/Dockerfile
- base image for alpine-kubectl updated to alpine:3.12.0
> Update alpine-kubectl to alpine 3.12.0

- prow/scripts/cluster-integration/kyma-gke-separate-compass-integration.sh
- Add missing override for separate Compass pipeline
> Add missing override for separate Compass pipeline

- prow/scripts/cluster-integration/kyma-gke-separate-compass-integration.sh
- Separate Ingress overrides to additional ConfigMap in Compass GKE Job
> Separate Ingress overrides to additional ConfigMap in Compass GKE Job

- prow/scripts/cluster-integration/kyma-gke-separate-compass-integration.sh
- Add missing overrides for GKE Separate Compass job
> Add missing overrides for GKE Separate Compass job

- development/tools/jobs/kyma/kyma_gardener_integration_test.go
- prow/jobs/kyma/kyma-integration-gardener.yaml
- prow/scripts/cluster-integration/kyma-integration-gardener-azure.sh
- templates/templates/kyma-integration-gardener.yaml
- Create new names for EventHubs for pre-submit jobs
See https://github.com/kyma-project/kyma/issues/8699
> Create new names for EH in pre submit job

- prow/scripts/cluster-integration/kyma-gke-upgrade-e2e.sh
- Update the upgrade test script to run both the e2e-upgrade test and the e2e-external-solution test.
Fixes https://github.com/kyma-project/kyma/issues/8799
> Run the e2e-upgrade test and the e2e-external-solution test as part of the upgrade job

- prow/scripts/build-compass-development-artifacts.sh
> Copy  KymaInstaller artifacts to Compass bucket

- prow/jobs/incubator/compass/compass-gke-integration.yaml
- prow/jobs/kyma/kyma-gke-separate-compass-integration.yaml
- templates/templates/compass-gke-integration.yaml
- templates/templates/kyma-gke-separate-compass-integration.yaml
Fix failing tests due to changes in storage permissions
> Add preset-sa-test-gcr-push

- prow/scripts/cluster-integration/helpers/delete-image.sh
- prow/scripts/library.sh
Fixed access denied error when deleting not used image in gcr.
See #2399
> Fix delete image access denied

- prow/scripts/cluster-integration/kyma-integration-gardener-azure.sh
- Update kyma cli usage with the new flag
https://github.com/kyma-project/cli/pull/474
> Update kyma cli usage with the new flag

- development/image-syncer/README.md
- ...
- ...
- ...
https://github.com/kyma-project/test-infra/issues/2426
> Add documentation to image-syncer

- prow/jobs/kyma/kyma-integration-gardener.yaml
- templates/templates/kyma-integration-gardener.yaml
> add missing environment variables to azure job

- prow/scripts/assetstore-gcp-bucket-cleaner.sh
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/orphaned-assetstore-gcp-bucket-cleaner/1275026869925711872
- ...
- ...
- ...
> Assetstore cleaner job fixup

- development/tools/jobs/addons/governance_test.go
- development/tools/jobs/community/governance_test.go
- development/tools/jobs/console/governance_test.go
- development/tools/jobs/incubator/documentation-component/documentation-component_test.go
- development/tools/jobs/incubator/marketplaces/marketplaces_test.go
- development/tools/jobs/kyma/governance_test.go
- development/tools/jobs/testinfra/governance_test.go
- development/tools/jobs/website/governance_test.go
- prow/jobs/addons/addons-governance.yaml
- prow/jobs/community/community-governance.yaml
- prow/jobs/console/console-governance.yaml
- prow/jobs/incubator/documentation-component/documentation-component.yaml
- prow/jobs/incubator/marketplaces/marketplaces.yaml
- prow/jobs/kyma/kyma-governance.yaml
- prow/jobs/test-infra/test-infra-governance.yaml
- prow/jobs/website/website-governance.yaml
- Reschedule jobs to avoid `HTTP 429 too many requests` error.
> Governance nightly

- prow/scripts/assetstore-gcp-bucket-cleaner.sh
Added `kyma-prow-access-storage-logs` to the excluded bucket list. There will be stored access logs to buckets in given project. 
- ...
- ...
- ...
> Add kyma-prow-access-storage-logs to the excluded bucket list

- prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
- prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
- prow/scripts/library.sh
- Change the way of passing overrides
Related to https://github.com/kyma-project/cli/pull/470
> Change the way of passing overrides

- development/image-syncer/external-images.yaml
- ...
- ...
- ...
https://github.com/kyma-project/test-infra/issues/2426
> Add sb-proxy to image-syncer

- development/tools/jobs/control-plane/development_artifacts_test.go
- prow/jobs/control-plane/kcp-development-artifacts.yaml
- prow/scripts/build-kcp-development-artifacts.sh
> Add KCP artifacts jobs

- prow/config.yaml
- templates/templates/prow-config.yaml
- Fixed control-plane docker push preset
> Fix control-plane docker push preset

- prow/scripts/assetstore-gcp-bucket-cleaner.sh
> Add kyma-prow-workloads-logs to the excluded bucket list

- prow/jobs/kyma/kyma-compass-provisioner-tests.yaml
> Add missing env to Provisioner tests

- prow/scripts/build-kyma-artifacts.sh
- prow/scripts/build-kyma-development-artifacts.sh
> Remove the Compass Dependencies artifacts

- prow/scripts/build.sh
- Don't execute job guard on helm-broker release
> Don't execute job guard on helm-broker release

- development/tools/jobs/kyma/kyma_gardener_integration_test.go
- prow/jobs/kyma/kyma-integration-gardener.yaml
- templates/templates/kyma-integration-gardener.yaml
- partially revert changes done in #2505
> use scripts from kyma-project for gardener jobs

- prow/scripts/cluster-integration/control-plane-gke-integration.sh
- Fix TMP_DIR redefinition for GKE KCP job
> Fix TMP_DIR redefinition for GKE KCP job

- docs/prow/test-clusters.md
- docs/prow/workload-clusters.md
Documentaition about shiny new workload clusters.
See #2482
> Workloads clusters docs

- development/tools/jobs/control-plane/control_plane_gke_provisioner_integration_test.go
- development/tools/jobs/control-plane/development_artifacts_test.go
- prow/jobs/control-plane/control-plane-gke-provisioner-integration.yaml
- prow/jobs/control-plane/kcp-development-artifacts.yaml
- Change gke-provisioner-integration path
> Change gke-provisioner-integration path

- prow/scripts/cluster-integration/control-plane-gke-integration.sh
- Bring provisioner back to gke-control-plane.sh
> Bring provisioner back to gke-control-plane.sh

- prow/scripts/cluster-integration/control-plane-gke-integration.sh
- Enable provisioning in gke-provisioning.sh
> Enable provisioning in gke-provisioning.sh

- development/tools/jobs/control-plane/control_plane_gke_integration_test.go
- development/tools/jobs/control-plane/control_plane_gke_provisioner_integration_test.go
- prow/jobs/control-plane/control-plane-gke-integration.yaml
- prow/jobs/control-plane/control-plane-gke-provisioner-integration.yaml
- Update Provisioner integration tests job trigger
> Update Provisioner integration tests job trigger

- development/image-syncer/external-images.yaml
- update to newest gatekeeper
- removal of kiwigrid as we build it on our own
- update to newest grafana
> updated 3party dependencies

- prow/scripts/cluster-integration/control-plane-gke-integration.sh
- Disable E2E provisioning test on KCP GKE
> Disable E2E provisioning test on KCP GKE

- development/tools/jobs/control-plane/components_test.go
- development/tools/jobs/control-plane/tests_test.go
- prow/jobs/control-plane/components/kubeconfig-service/kubeconfig-service-generic.yaml
- prow/jobs/control-plane/components/kyma-environment-broker/kyma-environment-broker-generic.yaml
- prow/jobs/control-plane/components/metris/metris-generic.yaml
- prow/jobs/control-plane/components/provisioner/provisioner-generic.yaml
- prow/jobs/control-plane/components/schema-migrator/schema-migrator-kcp-generic.yaml
- prow/jobs/control-plane/tests/e2e/provisioning/provisioning-test-generic.yaml
- prow/jobs/control-plane/tests/provisioner-tests/provisioner-tests-generic.yaml
- templates/config.yaml
> Fix Kyma Control Plane jobs

- prow/scripts/cluster-integration/kyma-integration-gardener-aws.sh
- prow/scripts/cluster-integration/kyma-integration-gardener-azure.sh
- prow/scripts/cluster-integration/kyma-integration-gardener-gcp.sh
- prow/scripts/cluster-integration/kyma-upgrade-gardener-azure.sh
- Decrease the minimum node count on Gardener jobs
> Decrease minimum node count on Gardener jobs

- development/tools/jobs/control-plane/control_plane_gke_provisioner_integration_test.go
- prow/jobs/control-plane/control-plane-gke-provisioner-integration.yaml
> Fix control-plane-gke-provisioner-integration job

- prow/jobs/test-infra/buildpack.yaml
> Add build job for Probot Stale

- prow/cluster/resources/probot-stale/Chart.yaml
- prow/cluster/resources/probot-stale/README.md
- prow/cluster/resources/probot-stale/templates/_helpers.tpl
- prow/cluster/resources/probot-stale/templates/deployment.yaml
- prow/cluster/resources/probot-stale/templates/ingress.yaml
- prow/cluster/resources/probot-stale/templates/service..yaml
- prow/cluster/resources/probot-stale/values.yaml
> Add Probot Stale chart

- prow/jobs/test-infra/testgrid-automation.yaml
> Make pre-test-infra-validate-testgrid-config optional

- development/image-syncer/external-images.yaml
- update grafana to latest patch version
- ...
- ...
> update grafana to latest patch version

- prow/images/buildpack-node/Dockerfile
> Add prow-tools to buildpack-node image

- development/tools/jobs/tester/tester.go
- prow/jobs/console/components/react/react-components.yaml
- prow/jobs/examples/event-email-service/event-email-service.yaml
- prow/jobs/incubator/varkes/varkes.yaml
- prow/jobs/incubator/vstudio-extension/vstudio-extension.yaml
> Bump buildpack-node image with prow-tools

- development/tools/jobs/tester/tester.go
- prow/jobs/console/components/react/react-components.yaml
- prow/jobs/examples/event-email-service/event-email-service.yaml
- prow/jobs/incubator/varkes/varkes.yaml
- prow/jobs/incubator/vstudio-extension/vstudio-extension.yaml
> Fix wrong in buildpack-node image path

- prow/scripts/build.sh
- Run Jobguard only for release jobs 
> build.sh fix

- development/tools/jobs/tester/tester.go
- prow/images/buildpack-node/Dockerfile
- prow/jobs/console/components/react/react-components.yaml
- prow/jobs/examples/event-email-service/event-email-service.yaml
- prow/jobs/incubator/varkes/varkes.yaml
- prow/jobs/incubator/vstudio-extension/vstudio-extension.yaml
> Revert buildpack node changes

- prow/jobs/test-infra/buildpack.yaml
Fixed wrong image tag in bootstrap image.
> Fixed wrong image tag.

- development/tools/pkg/pjtester/pjtester.go
Moved checking of env vars presence to call it earlier.
> Setup logging in pjtester.

- prow/images/prow-tools/Makefile
Fixed arg var name in docker build.
> fix build arg key

- prow/jobs/test-infra/pjtester.yaml
Changed cluster to trusted-workload.
> Changed cluster.

- development/tools/pkg/pjtester/pjtester.go
Added configPath to pjtester.yaml to support override prow config if needed.
> Added default pjpath and configpath.

- prow/jobs/test-infra/pjtester.yaml
Added missing env var to pjtester prowjob.
> Added missing env var.

- prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
- prow/scripts/cluster-integration/kyma-gke-release-candidate.sh
> Update images list artifact - add initContainers

- prow/scripts/build-kyma-artifacts.sh
- prow/scripts/build.sh
- prow/scripts/cluster-integration/kyma-gke-central.sh
- prow/scripts/cluster-integration/kyma-gke-external-registry.sh
- prow/scripts/cluster-integration/kyma-gke-integration.sh
- prow/scripts/cluster-integration/kyma-gke-upgrade.sh
> Revert changes

- prow/scripts/build-kyma-artifacts.sh
- prow/scripts/build.sh
- prow/scripts/cluster-integration/kyma-gke-central.sh
- prow/scripts/cluster-integration/kyma-gke-external-registry.sh
- prow/scripts/cluster-integration/kyma-gke-integration.sh
- prow/scripts/cluster-integration/kyma-gke-upgrade.sh
> release fixes cherry picks

- prow/jobs/kyma/kyma-artifacts.yaml
- templates/templates/kyma-artifacts.yaml
> Missing Preset

- prow/jobs/kyma/kyma-artifacts.yaml
- templates/templates/kyma-artifacts.yaml
> Missing Preset (#2598)

- development/image-syncer/external-images.yaml
- Upgrade Jaeger image
See https://github.com/kyma-project/kyma/issues/8925
> Upgrade Jaeger image

- prow/jobs/scans/whitesource-periodics.yaml
- templates/config.yaml
Add config to scan control-plane with Whitesource
> Add whitesource scan for control-plane

- docs/prow/prow-installation-on-forks.md
> Remove the dead link

- development/tools/pkg/pjtester/pjtester.go
Added function for rewriting refs.
> Added function for rewriting prowjob to test refs.

- development/tools/jobs/control-plane/control_plane_gke_integration_test.go
- development/tools/jobs/kyma/kyma_upgrade_gardener_test.go
- prow/jobs/control-plane/control-plane-gke-integration.yaml
- prow/jobs/kyma/kyma-compass-provisioner-tests.yaml
- prow/jobs/kyma/kyma-gke-compass-integration.yaml
- prow/jobs/kyma/kyma-gke-external-registry.yaml
- prow/jobs/kyma/kyma-release-candidate.yaml
- prow/jobs/kyma/kyma-release-upgrade.yaml
- prow/jobs/kyma/kyma-upgrade-gardener.yaml
- prow/scripts/cluster-integration/helpers/provision-gke-cluster.sh
- templates/templates/kyma-gke-compass-integration.yaml
- templates/templates/kyma-gke-external-registry.yaml
- templates/templates/kyma-release-candidate.yaml
- Migrate recent K8s 1.15 pipelines to 1.16
- Migrate CLUSTER_VERSIONs to 1.16
> K8s116 configs

- development/image-syncer/external-images.yaml
- Bump ServiceCatalog image for image syncer to the latest master
> Bump ServiceCatalog image for image syncer

- prow/images/prow-tools/Dockerfile
- prow/jobs/test-infra/pjtester.yaml
Added always pull image policy.
Fixed setting ARG build var.
> Pjtester always pull

- docs/prow/production-cluster-configuration.md
> Fix dead link

- prow/jobs/kyma/kyma-release-candidate.yaml
- prow/jobs/kyma/kyma-release-upgrade.yaml
- templates/templates/kyma-release-candidate.yaml
Added preset with credentials to GCR.
> Added preset-sa-gcr-push

- prow/jobs/kyma/kyma-release-candidate.yaml
- prow/jobs/kyma/kyma-release-upgrade.yaml
- templates/templates/kyma-release-candidate.yaml
* Added preset-sa-gcr-push
* Replaced preset with docker-push-repository.
* Rendered templates.
* Added docker registry preset.
- ...
- ...
- ...
> Added preset-sa-gcr-push (#2618)

- prow/jobs/incubator/compass/compass-integration.yaml
- prow/jobs/kyma/kyma-integration.yaml
- prow/jobs/test-infra/testgrid-automation.yaml
- templates/templates/compass-integration.yaml
- templates/templates/kyma-integration.yaml
> Add days-of-results override to the prow annotations in integration jobs

- docs/prow/prow-k8s-testgrid.md
Added small explanation on how the Testgrid update process works. 
- ...
- ...
- ...
> Add small explanation on PRs to the TestGrid.

- prow/jobs/kyma/kyma-integration.yaml
- prow/scripts/cluster-integration/kyma-gke-upgrade-for-debug.sh
- templates/templates/kyma-integration.yaml
- introduce new optional test for upgrade test debugging. this one executes the test suit also before the cluster was upgraded 
> Add new upgrade job for debugging

- prow/scripts/cluster-integration/helpers/provision-gke-cluster.sh
- Fait for `kube-dns` Configmap to be created
> "kube-dns" not found

- prow/jobs/kyma/kyma-github-release.yaml
- prow/jobs/kyma/kyma-release-candidate.yaml
- templates/templates/kyma-github-release.yaml
- templates/templates/kyma-release-candidate.yaml
> Add 90 days_of_results to the release jobs.

- prow/jobs/kyma/kyma-integration.yaml
- templates/templates/kyma-integration.yaml
> Change upgrade cluster to regional

- prow/scripts/cluster-integration/kyma-gke-upgrade-for-debug.sh
- some tests do not work if the testing addons are already installed. so we remove them before executing the tests
> remove testing addons before upgrade

- prow/jobs/kyma/kyma-integration.yaml
- templates/templates/kyma-integration.yaml
> make debug cluster regional

- prow/jobs/kyma/kyma-integration.yaml
- templates/templates/kyma-integration.yaml
> Change upgrade cluster to regional (#2628)

- prow/jobs/kyma/kyma-integration.yaml
- templates/templates/kyma-integration.yaml
This is a test to validate if increasing CPU in upgrade jobs will decrease instability in our tests.
- ...
- ...
- ...
> Change VM type for upgrade job to "n1-highcpu-16"

- development/tools/jobs/testinfra/branchprotector_test.go
- prow/branchprotector-config.yaml
- prow/images/kyma-integration/Dockerfile
- prow/images/kyma-integration/Makefile
- prow/jobs/test-infra/pjtester.yaml
- prow/scripts/vpathguard.sh
- templates/templates/branchprotector-config.yaml
Added required context vpathguard, for securing mater branch from polution from pjtester.
Added current tag for kyma-integration image.
> Added vpathguard test.

- development/tools/jobs/common/common_test.go
- prow/jobs/kyma/common/common.yaml
- templates/config.yaml
- Update golang in the `common` package
> Update golang in the `common` package

- prow/scripts/cluster-integration/helpers/provision-gke-cluster.sh
Pipe all output to /dev/null to surpass all output from a command
- ...
- ...
- ...
#2616
> Pipe stderr to /dev/null in kube-dns patch

- prow/config.yaml
- templates/templates/prow-config.yaml
- ...
- ...
- ...
https://github.com/kyma-project/kyma/issues/8783
> Add preset for gardener logs

- prow/scripts/vpathguard.sh
> Corrected log.sh source path.

- prow/scripts/vpathguard.sh
Add missing lib directory to path.
> Add missing directory to path.

- prow/jobs/kyma/kyma-integration-gardener.yaml
- templates/templates/kyma-integration-gardener.yaml
- vpath/pjtester.yaml
Added preset with credentials for sa-gcr-push-kyma-project@sap-kyma-prow.iam.gserviceaccount.com
> fix gcr access in pre-master-kyma-gardener-azure-integration

- development/tools/pkg/pjtester/pjtester.go
- development/tools/pkg/pjtester/pjtester_test.go
- development/tools/pkg/pjtester/test_artifacts/pjtester.yaml
- development/tools/pkg/pjtester/test_artifacts/test-job.yaml
- prow/jobs/kyma/kyma-integration.yaml
- Added testing multiple jobs on one commit.
- Added doc comments.
- Removed unused code.
See #2500
> Pjtester test few prowjobs

- development/tools/jobs/kyma/components_test.go
- prow/jobs/kyma/components/function-runtimes/function-runtimes-generic.yaml
- templates/config.yaml
- as in title
https://github.com/kyma-project/kyma/issues/9055
> Make function-runtimes pre-master and post-master jobs required

- prow/jobs/kyma/kyma-integration.yaml
- prow/scripts/cluster-integration/helpers/install-test-log-collector.sh
- prow/scripts/cluster-integration/kyma-gke-integration.sh
- templates/templates/kyma-integration.yaml
- vpath/pjtester.yaml
- update test log collector to run only on post-masters
> Update test-log-collector configuration

- development/tools/pkg/pjtester/pjtester.go
- development/tools/pkg/pjtester/pjtester_test.go
- development/tools/pkg/pjtester/test_artifacts/pjtester.yaml
- development/tools/pkg/pjtester/test_artifacts/test-job.yaml
- Added support for running prowjob tests on PR on other repositories.
- Made pjtester message formating more human friendly.
- Set reporting to false as default.
Resolves #2667 #2651
> Run prowjob test on PR on other repository.

- prow/jobs/test-infra/pjtester.yaml
Enabled pjtester to use ghproxy.
> Added github endpoint flags.

- prow/jobs/test-infra/pjtester.yaml
> Fixed pjtester args.

- development/tools/jobs/examples/orders_service_test.go
- prow/jobs/examples/orders-service/orders-service.yaml
> Update buildpack image in orders-service job

- prow/scripts/cluster-integration/control-plane-gke-integration.sh
- Increase Provisioner Tests timeout
> Increase Provisioner Tests timeout

- prow/images/kyma-integration/Dockerfile
- Update the Image tag so that the release artifacts on github release page are now separate.
kyma-project/kyma#8360
> Update image tag for the release artifact changes

- prow/scripts/build-kyma-development-artifacts.sh
- Fix typo for master tag.
kyma-project/kyma#8360
> Fix the master tag artifacts

- prow/jobs/scans/whitesource-periodics.yaml
- templates/config.yaml
- change language type for whitesource scans
- ...
- ...
> Fix whitesource scans for HB (golang-mod)

- prow/scripts/build-kyma-artifacts.sh
- prow/scripts/build-kyma-development-artifacts.sh
- prow/scripts/cluster-integration/compass-gke-integration.sh
- prow/scripts/cluster-integration/control-plane-gke-integration.sh
- prow/scripts/cluster-integration/kyma-gke-central.sh
- prow/scripts/cluster-integration/kyma-gke-compass-integration.sh
- prow/scripts/cluster-integration/kyma-gke-external-registry.sh
- prow/scripts/cluster-integration/kyma-gke-integration-xip.sh
- prow/scripts/cluster-integration/kyma-gke-integration.sh
- prow/scripts/cluster-integration/kyma-gke-minio-gateway-migration.sh
- prow/scripts/cluster-integration/kyma-gke-minio-gateway.sh
- prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh
- prow/scripts/cluster-integration/kyma-gke-release-candidate.sh
- prow/scripts/cluster-integration/kyma-gke-upgrade-for-debug.sh
- prow/scripts/cluster-integration/kyma-gke-upgrade-xip.sh
- prow/scripts/cluster-integration/kyma-gke-upgrade.sh
- prow/scripts/cluster-integration/kyma-upgrade-gardener-azure.sh
- prow/scripts/kind-install-kyma.sh
- prow/scripts/kind-upgrade-kyma.sh
- prow/scripts/lib/kyma.sh
> Remove Tiller

- prow/scripts/pr-image-guard.sh
> Fix pr-image-guard script

- prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh
- prow/scripts/kind-upgrade-kyma.sh
> Fix helm args

- prow/jobs/test-infra/buildpack.yaml
- prow/jobs/test-infra/image-syncer.yaml
- prow/jobs/test-infra/stability-checker.yaml
- prow/jobs/test-infra/test-infra-governance.yaml
- prow/jobs/test-infra/test-log-collector.yaml
- prow/jobs/test-infra/testgrid-automation.yaml
- prow/jobs/test-infra/validation.yaml
- prow/jobs/test-infra/watch-pods/watch-pods.yaml
- prow/jobs/website/website-governance.yaml
- templates/config.yaml
- templates/templates/component.yaml
Move test-infra, website jobs to new workload clusters.
> Move jobs to new clusters

- prow/scripts/cluster-integration/control-plane-gke-integration.sh
- Remove tiller from control-plane-gke-integration script
> Remove tiller from control-plane-gke-integration script

- prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh
- prow/scripts/cluster-integration/kyma-gke-upgrade-xip.sh
> Fix helm test command - leftovers

- prow/jobs/kyma/kyma-release-upgrade.yaml
> Add post-kyma-release-upgrade job to test-grid

- prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh
- prow/scripts/cluster-integration/kyma-gke-release-candidate.sh
- prow/scripts/cluster-integration/kyma-gke-upgrade-xip.sh
- prow/scripts/cluster-integration/kyma-gke-upgrade.sh
- Dont use kyma-installer.yaml from the github relerase artifacts instead use the separate yamls.
> Dont use kyma-installer.yaml from the github relerase artifacts instad use the separate yamls.

- prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh
- prow/scripts/cluster-integration/kyma-gke-release-candidate.sh
- prow/scripts/cluster-integration/kyma-gke-upgrade-xip.sh
- prow/scripts/cluster-integration/kyma-gke-upgrade.sh
- Dont use kyma-installer.yaml from the github relerase artifacts instead use the separate yamls.
> Fix rc rel branch

- prow/jobs/kyma/kyma-release-upgrade.yaml
> Update post-kyma-release-upgrade config

- prow/scripts/cluster-integration/kyma-gke-integration.sh
- prow/scripts/cluster-integration/kyma-gke-upgrade.sh
- Revert changes to traps in integration jobs
> Revert changes to traps in integration jobs

- development/image-syncer/external-images.yaml
- ...
- ...
- ...
https://github.com/kyma-project/kyma/issues/731
> Update images in image-syncer - follow up

- prow/jobs/test-infra/image-syncer.yaml
- prow/scripts/lib/docker.sh
- prow/scripts/library.sh
The function is based on the one in https://github.com/kyma-project/test-infra/blob/4d06bf0b22870fbbab41779fa30888810914c662/prow/scripts/library.sh#L61
I've modified it to accept an argument for perform easy user switch.
- add docker::authenticate function to lib/docker.sh
Closes #2631
> Add docker::authenticate for authentication to Docker registry

- prow/scripts/cluster-integration/kyma-gke-upgrade.sh
- vpath/pjtester.yaml
- use cli in upgrade job only when build type is master
#2604
>  Use CLI in upgrade job only when build type is master

- prow/scripts/cluster-integration/kyma-gke-integration.sh
- prow/scripts/cluster-integration/kyma-gke-upgrade.sh
> Enable test-log-collector for integration and upgrade jobs

- development/image-syncer/external-images.yaml
- migrate image used in rafter and in cbs tests to gcr
https://github.com/kyma-project/kyma/issues/731#issuecomment-683650979
> Add mockice test image to external image list

- development/image-syncer/external-images.yaml
> Remove busybox from syncer

- prow/jobs/kyma/kyma-gke-external-registry.yaml
- templates/templates/kyma-gke-external-registry.yaml
Run `gke-external-registry` with changes on resources/serverless
> Run gke-external-registry with changes on resources/serverless

- development/image-syncer/external-images.yaml
- bump postgres version to 11.9
> Bump postgres version to 11.9

- prow/scripts/cluster-integration/kyma-integration-minikube.sh
- prow/scripts/provision-vm-and-start-kyma.sh
- ...
- ...
- ...
Closes #2735 
Closes #2671
> Use Kyma-cli in the kyma-integration job.

- development/tools/jobs/kyma/tests_test.go
- prow/jobs/kyma/tests/application-gateway-legacy-tests/application-gateway-legacy-tests-generic.yaml
- templates/config.yaml
- Make application-gateway-legacy-tests job required
See the issue [#9094](https://github.com/kyma-project/kyma/issues/9094)
[Here](https://github.com/kyma-project/kyma/pull/9394/files) you can find the `tests/application-gateway-legacy-tests` component addition
> Make application-gateway-legacy-tests job required

- prow/jobs/control-plane/tests/provisioner-tests/provisioner-whitesource.yaml
- prow/jobs/scans/whitesource-periodics.yaml
- templates/templates/whitesource-periodics.yaml
> Bump wss agent image to the one with go and dep binaries.

- development/tools/jobs/kyma/components_test.go
- prow/jobs/kyma/components/event-publisher-proxy/event-publisher-proxy-generic.yaml
- templates/config.yaml
- Remove optional param for event-publisher-proxy
> Remove optional param for event-publisher-proxy

- prow/scripts/cluster-integration/kyma-gke-integration-cli.sh
- vpath/pjtester.yaml
- Fix CLI-GKE integration job
See https://github.com/kyma-project/kyma/issues/9460
> Fix CLI-GKE integration job

- development/image-syncer/external-images.yaml
- Add two versions of alpine-based Application Gateway and Application Connectivity Validator images
> Add Application Connector alpine images

- development/tools/jobs/control-plane/components_test.go
- prow/jobs/control-plane/components/subscription-cleanup-job/subscription-cleanup-job-generic.yaml
- templates/config.yaml
- Subscription-cleanup-job is now required
> Make subscription-cleanup-job job required

- prow/scripts/build-kyma-development-artifacts.sh
- Copy config file for local installation to buckets
> Copy config file for local installation to buckets

- development/tools/jobs/kyma/tests_test.go
- prow/jobs/kyma/tests/function-controller/function-controller-tests-generic.yaml
- templates/config.yaml
- make serverless test component build required.
> Make fucntion-serverless test build job as required

- development/image-syncer/external-images.yaml
Add governance image to image-syncer.
> Add governance image to image-syncer

- prow/jobs/scans/whitesource-periodics.yaml
- templates/config.yaml
- kyma uses knative kafka v0.12.3, but master was scanned. In order to synchronize the source with the scan we need to change the branch
- ...
- ...
> update knative-kafka whitesource scan branch

- prow/scripts/governance.sh
Switch governance image to gcp-internal.
> Switch governance image to gcp-internal

- prow/scripts/cluster-integration/kyma-gke-integration-for-testing.sh
- Add operator fix to missing pipeline
- Followup to #2782
> IstioOperator fix followup

- prow/scripts/cluster-integration/kyma-gke-upgrade.sh
> Restore istio helm values for upgrade pipeline

- prow/config.yaml
- templates/templates/prow-config.yaml
GKE 1.16 has ben removed from REGULAR channel.
- ...
- ...
- ...
> Remove RELEASE_CHANNEL from `preset-gke-ver-stable`

- prow/scripts/cluster-integration/compass-gke-integration.sh
- reverts changes from #2782 in compass-gke-integration job
partially reverts #2782
> Revert change in istio overrides for compass-gke-integration job

- prow/scripts/cluster-integration/kyma-gke-release-candidate.sh
> Extend TTL Release candidate to 7 days

- prow/images/alpine-kubectl/Dockerfile
- upgrade alpine packages for alpine-kubectl image build
- ...
- ...
> upgrade alpine packages for alpine-kubectl image build

- development/prowjobparser/main.go
Added cluster filter. It will print prowjobs with provided cluster name.
> Added cluster filter to prowjobparser.

- development/tools/cmd/enablegithubauth/README.md
- Fix a dead link found by the governance prow job 
n/a
> Fix a dead link

- development/image-syncer/external-images.yaml
- Bumped `sb-proxy-k8s` image to latest verision (`v0.8.8`)
> Bump sb-proxy-k8s image

- prow/images/alpine-kubectl/Makefile
- prow/images/bootstrap-helm/Makefile
- prow/images/bootstrap/Makefile
- prow/images/buildpack-golang-kubebuilder/Makefile
- prow/images/buildpack-golang-kubebuilder2/Makefile
- prow/images/buildpack-golang-toolbox/Makefile
- prow/images/buildpack-golang/Makefile
- prow/images/buildpack-java-node/Makefile
- prow/images/buildpack-java/Makefile
- prow/images/buildpack-node/Makefile
- prow/images/cleaner/Makefile
- prow/images/clonerefs/Makefile
- prow/images/kyma-cluster-infra/Makefile
- prow/images/kyma-integration/Makefile
- prow/images/probot-stale/Makefile
- prow/images/prow-tools/Makefile
- prow/images/whitesource-scanner/Makefile
- prow/scripts/publish-buildpack.sh
Added conditional tagging image with PR tag for postsubmit builds.
See #2693
> Added tagging with post PR tag.

- development/image-syncer/external-images.yaml
- Bumped etcd image to `v3.4.13`
> Bump etcd image used in helm-broker

- development/tools/cmd/pjtester/README.md
> Removed duplicated text.

- prow/images/bootstrap/Dockerfile
- prow/images/bootstrap/Makefile
Rebuilding bootstrap image without pr tag bug.
> Rebuild without prtag bug.

- development/tools/jobs/tester/tester.go
- prow/jobs/test-infra/buildpack.yaml
- templates/config.yaml
Update buildpack.yaml jobs to new bootstrap image.
> Update bootstrap image tag in test-infra buildpack.yaml

- prow/images/alpine-kubectl/Dockerfile
- prow/images/alpine-kubectl/Makefile
- prow/images/bootstrap-helm/Dockerfile
- prow/images/bootstrap-helm/Makefile
- prow/images/bootstrap/Makefile
- prow/images/buildpack-golang-kubebuilder/Dockerfile
- prow/images/buildpack-golang-kubebuilder/Makefile
- prow/images/buildpack-golang-kubebuilder2/Dockerfile
- prow/images/buildpack-golang-kubebuilder2/Makefile
- prow/images/buildpack-golang-toolbox/Dockerfile
- prow/images/buildpack-golang-toolbox/Makefile
- prow/images/buildpack-golang/Dockerfile
- prow/images/buildpack-golang/Makefile
- prow/images/buildpack-java-node/Dockerfile
- prow/images/buildpack-java-node/Makefile
- prow/images/buildpack-java/Dockerfile
- prow/images/buildpack-java/Makefile
- prow/images/buildpack-node/Dockerfile
- prow/images/buildpack-node/Makefile
- prow/images/cleaner/Dockerfile
- prow/images/cleaner/Makefile
- prow/images/clonerefs/Makefile
- prow/images/kyma-cluster-infra/Dockerfile
- prow/images/kyma-cluster-infra/Makefile
- prow/images/kyma-integration/Dockerfile
- prow/images/kyma-integration/Makefile
- prow/images/probot-stale/Makefile
- prow/images/prow-tools/Makefile
- prow/images/whitesource-scanner/Dockerfile
- prow/images/whitesource-scanner/Makefile
Rebuild test-infra images with fixed prtagbuilder.
> Testing with first image.

- prow/images/alpine-kubectl/Makefile
- prow/images/bootstrap-helm/Makefile
- prow/images/bootstrap/Makefile
- prow/images/buildpack-golang-kubebuilder/Makefile
- prow/images/buildpack-golang-kubebuilder2/Makefile
- prow/images/buildpack-golang-toolbox/Makefile
- prow/images/buildpack-golang/Makefile
- prow/images/buildpack-java-node/Makefile
- prow/images/buildpack-java/Makefile
- prow/images/buildpack-node/Makefile
- prow/images/cleaner/Makefile
- prow/images/clonerefs/Makefile
- prow/images/kyma-cluster-infra/Makefile
- prow/images/kyma-integration/Makefile
- prow/images/probot-stale/Makefile
- prow/images/prow-tools/Makefile
- prow/images/whitesource-scanner/Makefile
- prow/scripts/publish-buildpack.sh
Disabling prtagbuilder due to some unidentified bug in the tool.
> Disabled prtagbuilder.

- development/tools/pkg/prtagbuilder/prtagbuilder.go
Removed creating client with ghproxy.
Corrected regex for matching pr number.
Limited match to the first line of commit message.
> Fixed matching regex

- prow/images/alpine-kubectl/Dockerfile
- prow/images/bootstrap-helm/Dockerfile
- prow/images/bootstrap/Dockerfile
- prow/images/buildpack-golang-kubebuilder/Dockerfile
- prow/images/buildpack-golang-kubebuilder2/Dockerfile
- prow/images/buildpack-golang-toolbox/Dockerfile
- prow/images/buildpack-golang/Dockerfile
- prow/images/buildpack-java-node/Dockerfile
- prow/images/buildpack-java/Dockerfile
- prow/images/buildpack-node/Dockerfile
- prow/images/cleaner/Dockerfile
- prow/images/kyma-cluster-infra/Dockerfile
- prow/images/kyma-integration/Dockerfile
- prow/images/whitesource-scanner/Dockerfile
> Updated prow-tools image tag.

- development/tools/jobs/tester/tester.go
- prow/jobs/test-infra/buildpack.yaml
- templates/config.yaml
Fixing prtagbuilder in test-infra.
> Updated bootstrap image.

- development/tools/jobs/kyma/kyma_upgrade_gardener_test.go
- prow/jobs/kyma/kyma-upgrade-gardener.yaml
- prow/scripts/cluster-integration/kyma-integration-gardener-azure.sh
- prow/scripts/cluster-integration/kyma-upgrade-gardener-azure.sh
- vpath/pjtester.yaml
Use one Azure Eventhubs ResourceGroup for Gardner jobs.
- Fixes https://github.com/kyma-project/test-infra/issues/2848.
> Use one Azure Eventhubs ResourceGroup for Gardner jobs

- prow/scripts/lib/log.sh
- as ansi color codes make logs hard to read (if not evaluated by a terminal) these will be removed
> remove color codes from log:: output

- development/tools/pkg/prtagbuilder/README.md
Added documentation for prtagbuilder tool.
See #2693
> Docs for prtagbuilder.

- prow/images/alpine-kubectl/Dockerfile
> Fix security issues in alpine kubectl

- prow/scripts/cluster-integration/kyma-integration-minikube.sh
> Fix selector

- prow/jobs/kyma/kyma-integration.yaml
- templates/config.yaml
- templates/templates/kyma-integration.yaml
GKE integration job that runs integration tests for GKE version 1.17 and 1.18. Reapply previous config after `kyma-gke-integration.sh` rewrite.
- ...
- ...
- ...
#2822
> Add pre/post GKE integration job for multiple GKE versions.

- prow/images/kyma-integration/Dockerfile
> Bumg gcloud version to 314.0.0 in kyma-integration image

- prow/scripts/cluster-integration/helpers/provision-gke-cluster.sh
> Re-add --release-channel variable to provision-gke-cluster.sh

- prow/scripts/cluster-integration/kyma-gke-upgrade.sh
- Reenable istioOperator override
- Change upgrade job to run from the last RC
- ...
> Modify upgrade job for istio 1.7

- prow/jobs/scans/whitesource-periodics.yaml
- templates/config.yaml
- templates/templates/whitesource-periodics.yaml
> Add whitesource jobs for release branch

- development/image-syncer/external-images.yaml
- add etcd v 3.3.25 to the syncer
> Add etcd v3.3.25 to the syncer config

- prow/images/buildpack-node-chromium/Dockerfile
- Update chromium version in console dockerfile
> Update chromium version in console dockerfile

- development/image-guard/Dockerfile
- development/image-guard/Makefile
- prow/jobs/test-infra/buildpack.yaml
- templates/config.yaml
Add buildpack prowjob for image-guard admission controller
- ...
- ...
- ...
#2599
> Buildpack for image-guard

- prow/jobs/kyma/kyma-integration.yaml
- prow/scripts/cluster-integration/kyma-gke-upgrade.sh
- templates/templates/kyma-integration.yaml
- vpath/pjtester.yaml
- Change scenario for the `pre-master-kyma-gke-upgrade` (install -> upgrade -> upgrade)
- Change scenario for the `post-master-kyma-gke-upgrade` (install -> test -> upgrade -> test)
https://github.com/kyma-project/kyma/issues/8463
> Divide the upgrade test for pre and post functionality

- prow/jobs/incubator/third-party-images/k8s-tools/k8s-tools.yaml
> Add jobs for k8s-tools

- prow/jobs/kyma/kyma-integration.yaml
- templates/config.yaml
> Bump gke to 1.17.12-gke.1504

- templates/templates/kyma-integration.yaml
Removed release jobs templates for unsupported kyma versions.
> Removed code for rendering prowjobs for not supported releases.

- prow/jobs/kyma/kyma-integration.yaml
- templates/config.yaml
> Update 1.18 gke version.

- prow/scripts/cluster-integration/helpers/create-dns-record.sh
> Change default TTL to 60

- prow/jobs/cli/cli-compatibility.yaml
> Skip report for cli compatibility

- prow/scripts/cluster-integration/compass-gke-integration.sh
- prow/scripts/cluster-integration/control-plane-gke-integration.sh
- prow/scripts/cluster-integration/helpers/deprovision-gke-cluster.sh
- prow/scripts/cluster-integration/kyma-gke-central.sh
- prow/scripts/cluster-integration/kyma-gke-compass-integration.sh
- prow/scripts/cluster-integration/kyma-gke-external-registry.sh
- prow/scripts/cluster-integration/kyma-gke-integration.sh
- prow/scripts/cluster-integration/kyma-gke-upgrade.sh
> Disable cleaners in gke jobs

- development/tools/jobs/kyma/kyma_integration_test.go
- prow/jobs/kyma/kyma-integration.yaml
- prow/scripts/cluster-integration/compass-gke-integration.sh
- prow/scripts/cluster-integration/control-plane-gke-integration.sh
- prow/scripts/cluster-integration/helpers/delete-dns-record-gcloud.sh
- prow/scripts/cluster-integration/kyma-gke-compass-integration.sh
- prow/scripts/cluster-integration/kyma-gke-external-registry.sh
- prow/scripts/cluster-integration/kyma-gke-integration-cli.sh
- prow/scripts/cluster-integration/kyma-gke-integration-for-testing.sh
- prow/scripts/cluster-integration/kyma-gke-integration-xip.sh
- prow/scripts/cluster-integration/kyma-gke-minio-gateway-migration.sh
- prow/scripts/cluster-integration/kyma-gke-minio-gateway.sh
- prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh
- prow/scripts/cluster-integration/kyma-gke-upgrade-xip.sh
- prow/scripts/library.sh
- templates/templates/kyma-integration.yaml
> Fix cleanup procedure in gke jobs

- prow/scripts/cluster-integration/helpers/deprovision-gardener-cluster.sh
`confirmation.garden.sapcloud.io` is deprecated with https://github.com/gardener/gardener/pull/1833 and will be removed in a future release of gardener/gardener.
/kind cleanup
> Do not use the deprecated confirmation annotation

- prow/scripts/cluster-integration/helpers/delete-dns-record.sh
- prow/scripts/cluster-integration/kyma-gke-integration.sh
- prow/scripts/library.sh
> Add TTL parameter to dns cleaner

- prow/scripts/cluster-integration/helpers/create-dns-record.sh
- vpath/pjtester.yaml
Added commands to debug dns resolution issues.
> Added debugging commands.

- development/image-syncer/external-images.yaml
- add httpbin image to image syncer
> Add httpbin image to image syncer

- prow/scripts/cluster-integration/helpers/deprovision-gke-cluster.sh
- prow/scripts/cluster-integration/kyma-gke-central.sh
- prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
- prow/scripts/cluster-integration/kyma-gke-minio-gateway-migration.sh
- prow/scripts/cluster-integration/kyma-gke-minio-gateway.sh
- prow/scripts/cluster-integration/kyma-gke-upgrade.sh
- prow/scripts/library.sh
> Re-enable dns cleanup

- prow/scripts/cluster-integration/helpers/deprovision-gke-cluster.sh
Params to the gcloud commends are broken, clusters are not removed:
https://status.build.kyma-project.io/log?job=kyma-gke-nightly&id=1323837576565493763
- ...
- ...
- ...
> Fix GKE cluster cleanup

- development/test-log-collector/chart/test-log-collector/files/config.yaml
> Update test-log-collector config

- development/tools/jobs/kyma/components_test.go
- prow/jobs/kyma/components/eventing-controller/eventing-controller-generic.yaml
- templates/config.yaml
- Make eventing-controller job mandatory
> Make eventing-controller job mandatory

- prow/scripts/cluster-integration/helpers/create-dns-record.sh
> Skip DNS verification after it fails

- prow/branchprotector-config.yaml
- templates/templates/branchprotector-config.yaml
> Update branch-protector for compass-ui

- prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh
The same changes as in https://github.com/kyma-project/test-infra/pull/2876
- ...
- ...
- ...
> Fix rel2rel upgrade in Kyma 1.17

- prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh
> Hardcoded Kyma source version for rel2rel upgrade

- development/tools/jobs/kyma/components_test.go
- prow/jobs/kyma/components/istio-kyma-patch/istio-kyma-patch-generic.yaml
- templates/config.yaml
- Make istio-kyma-patch deprecated
https://github.com/kyma-project/kyma/issues/4380
> Deprecate istio-kyma-patch

- prow/jobs/kyma/kyma-integration.yaml
- templates/config.yaml
> Bump gke version to 1.18.10-gke.601

- prow/scripts/cluster-integration/kyma-gke-integration-cli.sh
- prow/scripts/cluster-integration/kyma-integration-gardener-azure.sh
- prow/scripts/provision-vm-cli.sh
- vpath/pjtester.yaml
- Add new commands to Kyma CLI integration tests
See https://github.com/kyma-project/cli/issues/629
> Add new commands to Kyma CLI integration tests

- prow/jobs/test-infra/pjtester.yaml
Removed unsupported pjtester arguments.
> Removed unsuported pjtester arguments.

- prow/scripts/cluster-integration/kyma-gke-upgrade.sh
- Enable test run after the second update in the `pre` scenario
https://github.com/kyma-project/test-infra/pull/2872
> Run test on the pre-upgrade scenario

- development/tools/cmd/pjtester/README.md
- development/tools/pkg/pjtester/pjtester.go
Documentation update to reflect recent changes in a tool.
Removed duplicated documentation section.
> Pjtester docs update

- development/tools/cmd/prtagbuilder/main.go
- development/tools/pkg/prtagbuilder/README.md
Updated documentation to match recent changes.
> Added description accepted flags. Removed deprecated data.

- prow/images/alpine-kubectl/Dockerfile
- prow/images/bootstrap-helm/Dockerfile
- prow/images/bootstrap/Dockerfile
- prow/images/buildpack-golang-kubebuilder/Dockerfile
- prow/images/buildpack-golang-kubebuilder2/Dockerfile
- prow/images/buildpack-golang-toolbox/Dockerfile
- prow/images/buildpack-golang/Dockerfile
- prow/images/buildpack-java-node/Dockerfile
- prow/images/buildpack-java/Dockerfile
- prow/images/buildpack-node/Dockerfile
- prow/images/cleaner/Dockerfile
- prow/images/kyma-cluster-infra/Dockerfile
- prow/images/kyma-integration/Dockerfile
- prow/images/whitesource-scanner/Dockerfile
pjtester and prtagbuilder code cleanup.
> Update prow-tools version.

- prow/jobs/kyma/kyma-integration.yaml
- templates/config.yaml
> Bump gke version to 1.18.10-gke.2101

- prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
- prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
- As we are already passing the override through production config we should update the
override here since passing it as a separate override would lead to inconsistent behaviour
depending on which override is applied first
> Update the override in the production config file

- prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
- prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
- We need to update the limitranges before the installation starts as the prometheus-istio pod needs more that 4 Gi of memory. So increase the max memory in limitrange via override.
> Add overrides for limitranges

- prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
- prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
> Fix indentation

- prow/scripts/cluster-integration/kyma-gke-integration-cli.sh
- prow/scripts/provision-vm-cli.sh
- Increase timeout for the function creation
> Increase timeout for the function creation

- prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
- prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
> Adapt sed command as now the production profile has 4Gi for prometheus-istio

- prow/scripts/compatibility-cli.sh
- Add handling of special releases in compatibility job
> Add handling of special releases in compatibility job

- prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
- prow/scripts/cluster-integration/kyma-gke-central.sh
- prow/scripts/cluster-integration/kyma-gke-integration-cli.sh
- prow/scripts/cluster-integration/kyma-gke-integration.sh
- prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
- Change `tlsCert` and `tlsKey` flags in the scripts to be `tls-cert` and `tls-key` respectively. This is due to this change in CLI: kyma-project/cli#650
kyma-project/cli#431
> Consistent flag naming

- prow/scripts/lib/azure.sh
Initial azure library for future azure-related jobs rewrite. This one allows using JSON file to login.
- add `azure.sh` library script for azure-related helper functions.
> Add azure.sh library script for Azure-related jobs.

- development/image-syncer/external-images.yaml
Add kaniko image with this patch https://github.com/GoogleContainerTools/kaniko/compare/v1.3.0...aerfio:cred_linux_patch, taken from this comment https://github.com/GoogleContainerTools/kaniko/issues/1287#issuecomment-637634928 in order for this PR https://github.com/kyma-project/test-infra/pull/2939 to work.
https://github.com/kyma-project/test-infra/pull/2939
> Add patched kaniko image to external-images.yaml

- prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
- prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
> Change file to edit in istio-ingressgateway patch

- prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
- prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
Reverts kyma-project/test-infra#2970
> Revert "Change file to edit in istio-ingressgateway patch"

- development/tools/jobs/kyma/components_test.go
- prow/jobs/kyma/components/k8s-dashboard-proxy/k8s-dashboard-proxy.yaml
- templates/config.yaml
- k8s-dashboard-proxy is gone from kyma repo, so we do not need its build jobs anymore
> remove jobs for k8s-dashboard-proxy

- development/image-syncer/external-images.yaml
- Update prometheus pushgateway image to latest.
https://github.com/kyma-project/kyma/issues/9897
> Update prometheus pushgateway image

- prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
> Fix kyma-aks-long-lasting.sh

- prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
- prow/scripts/cluster-integration/kyma-gke-central.sh
- prow/scripts/cluster-integration/kyma-gke-integration-cli.sh
- prow/scripts/cluster-integration/kyma-gke-integration.sh
- prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
- ...
- ...
- ...
https://github.com/kyma-project/kyma/issues/9833
> Change tlsCert and tlsKey to tls-cert and tls-key (#2966)

- prow/scripts/cluster-integration/kyma-gke-upgrade.sh
> Fix upgrade job for 1.17 - set last Kyma version

- development/image-syncer/external-images.yaml
> Bump kube-state-metrics image

- prow/jobs/kyma/kyma-gke-compass-integration.yaml
- templates/templates/kyma-gke-compass-integration.yaml
- Make compass integration job optional
> Make compass integration job optional

- prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
- prow/scripts/cluster-integration/kyma-gke-integration-cli.sh
- prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
- prow/scripts/cluster-integration/kyma-integration-gardener-aws.sh
- prow/scripts/cluster-integration/kyma-integration-gardener-azure.sh
- prow/scripts/cluster-integration/kyma-integration-gardener-gcp.sh
- latest-published source flag will no longer exist for the CLI. So, its usage is replaced with the new `master` source flag
kyma-project/cli#501
> Replace latest-published source flag with master source flag

- development/image-syncer/external-images.yaml
Bump grafana image to the newest version
> Bump grafana image

- development/test-log-collector/chart/test-log-collector/files/config.yaml
-  Configure log collector for Console and Console Backend Service
> Configure log collector for Console and Console Backend Service

- development/dns-debug-role.yaml
- prow/jobs/incubator/compass/compass-gke-integration.yaml
- prow/jobs/kyma/kyma-gke-compass-integration.yaml
- prow/jobs/kyma/kyma-gke-external-registry.yaml
- prow/jobs/kyma/kyma-integration-gardener.yaml
- prow/jobs/kyma/kyma-integration.yaml
- prow/jobs/kyma/kyma-upgrade-gardener.yaml
- prow/scripts/cluster-integration/helpers/create-dns-record.sh
- templates/templates/compass-gke-integration.yaml
- templates/templates/kyma-gke-compass-integration.yaml
- templates/templates/kyma-gke-external-registry.yaml
- templates/templates/kyma-integration-gardener.yaml
- templates/templates/kyma-integration.yaml
- vpath/pjtester.yaml
Added additional debugging commands requested by google support.
> More dns debug

- prow/branchprotector-config.yaml
- templates/templates/branchprotector-config.yaml
> Add kyma-incubator/pamela to branchprotector-config.yaml

- prow/jobs/incubator/pamela/pamela.yaml
> Always run Pamela job

- prow/jobs/kyma/kyma-integration-gardener.yaml
- prow/scripts/cluster-integration/kyma-integration-gardener-azure.sh
- templates/templates/kyma-integration-gardener.yaml
- vpath/pjtester.yaml
- new job `kyma-integration-evaluation-gardener-azure`
- tests for evaluation profile are taken from `local-kyma` repo (until we have replacement)
https://github.com/kyma-project/test-infra/issues/2918
> Add test job for evaluation profile

- prow/jobs/kyma/kyma-integration.yaml
- templates/config.yaml
> Bump gke version to latest default from channels

- development/tools/jobs/kyma/kyma_gke_compass_integration_test.go
- prow/jobs/kyma/kyma-gke-compass-integration.yaml
- templates/templates/kyma-gke-compass-integration.yaml
- ...
- ...
- ...
https://github.com/kyma-project/kyma/issues/10118
> Make pre-rel kyma-gke-compass-integration optional (#3003)

- development/test-log-collector/Dockerfile
- development/test-log-collector/chart/test-log-collector/values.yaml
- development/test-log-collector/cmd/app/mainerr.go
- development/test-log-collector/go.mod
- development/test-log-collector/pkg/config/config.go
- development/test-log-collector/pkg/slack/slack.go
- there were some problems with logs send to wrong channel, so I'm adding more logs to see what's happening
> Add more logs to test-log-collector

- prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
- prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
- Reduce Sample limits to prevent prometheus istio server restarts
> Reduce  sample limits to prevent restarts on prometheus istio server

- prow/scripts/cluster-integration/kyma-gke-upgrade.sh
> Fix upgrade job (get last release)

- prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
- prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
> Fix overrides make it string

- prow/images/kyma-integration/Dockerfile
- ...
- ...
- ...
https://github.com/kyma-project/test-infra/issues/3010
> Add node.js to integration image

- prow/images/prow-tools/Dockerfile
- Bump Prow tools' Dockerfile base image to v.1.15.5
> Bump Prow tools GoLang version to v1.15.5

- prow/branchprotector-config.yaml
- templates/config.yaml
> Remove compass-integration and old unused jobs

- prow/images/buildpack-golang/Dockerfile
- prow/images/buildpack-golang/Makefile
- Bump prow buildpack-golang version to 1.15.5
> Bump go version of prow buildpack

- prow/images/buildpack-golang-toolbox/Dockerfile
- Bump buildpack-golang and prow-tools versions to contain GoLang v1.15.5
> Bump buildpack-golang and prow-tools versions

- prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh
> Fix source version in gke-rel2rel upgrade

- prow/scripts/cluster-integration/control-plane-gke-integration.sh
- prow/scripts/cluster-integration/kyma-gke-central.sh
- prow/scripts/cluster-integration/kyma-gke-compass-integration.sh
- prow/scripts/cluster-integration/kyma-gke-integration.sh
- prow/scripts/lib/docker.sh
Fixing `log::error` typo in several scripts.
- ...
- ...
- ...
> Fix typo in several scripts

- prow/jobs/kyma/kyma-integration.yaml
- templates/config.yaml
> Bump GKE rapid version to 1.18.12-gke.300

- prow/scripts/lib/gcloud.sh
This PR adds more functionality to the `gcloud.sh` library which was implemented before in the `cluster-integration/helpers` directory. This PR aims to reduce the number of gcloud-related scripts in favour of specific libraries that are sourced in the parent directories.
- ...
- ...
- ...
#2754
> Add more functionality to gcloud.sh lib

- prow/jobs/console/core/core.yaml
- templates/config.yaml
> Fix core console build

- prow/scripts/cluster-integration/kyma-gke-compass-integration.sh
> Add missing log.sh source to kyma-gke-compass-integration.sh

- prow/scripts/cluster-integration/control-plane-gke-integration.sh
- prow/scripts/cluster-integration/kyma-gke-central.sh
- prow/scripts/cluster-integration/kyma-gke-compass-integration.sh
- prow/scripts/cluster-integration/kyma-gke-integration.sh
- prow/scripts/cluster-integration/kyma-gke-upgrade.sh
- prow/scripts/cluster-integration/kyma-integration-gardener-azure.sh
- prow/scripts/cluster-integration/kyma-integration-gardener-gcp.sh
- prow/scripts/cluster-integration/kyma-upgrade-gardener-azure.sh
- prow/scripts/library.sh
- vpath/pjtester.yaml
- Do not fail if no log collector in the master job
`kyma-gke-compass-integration-daily` job has been failing on `line 28: log:error: command not found` since [this PR](https://github.com/kyma-project/test-infra/pull/2987)
> Do not fail if no log collector in the master job

- development/tools/jobs/kyma/kyma_integration_test.go
- prow/jobs/kyma/kyma-integration.yaml
- prow/scripts/README.md
- prow/scripts/cluster-integration/kyma-integration-k3s.sh
- prow/scripts/provision-vm-and-start-kyma-k3s.sh
- templates/templates/kyma-integration.yaml
- vpath/pjtester.yaml
> Run fast integration job on k3s

- development/tools/jobs/kyma/kyma_integration_test.go
- prow/jobs/kyma/kyma-integration.yaml
- templates/templates/kyma-integration.yaml
- Add post-master integration job on k3s
> Add post-master integration job on k3s

- prow/scripts/cluster-integration/kyma-integration-k3s.sh
- vpath/pjtester.yaml
- Refactor k3s integration after changes in custom-image
Do not merge before https://github.com/kyma-project/test-infra/pull/3042
> Refactor k3s integration after changes in custom-image

- prow/jobs/kyma/kyma-integration.yaml
- templates/config.yaml
Bump gke rapid version to 1.18.12-gke.1201
- ...
- ...
- ...
> Bump gke rapid version to 1.18.12-gke.1201

- prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
- prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
`yq` has been updated to version 4.0.0 which introduced new syntax for the expressions. The pipeline does not yet support new expressions so we need to use v3 version of `yq`.
- ...
- ...
- ...
> Set static version of yq to version 3.4.1

- prow/jobs/kyma/kyma-integration-gardener.yaml
- prow/scripts/cluster-integration/kyma-integration-gardener-azure.sh
- templates/templates/kyma-integration-gardener.yaml
> Switch to fast integration tests

- prow/scripts/cli-tests/test-function.sh
- prow/scripts/cli-tests/test-runtest.sh
- prow/scripts/cli-tests/test-version.sh
- prow/scripts/cli-tests/testsuite-alpha.sh
- prow/scripts/cli-tests/testsuite-default.sh
- prow/scripts/lib/clitests.sh
- prow/scripts/provision-vm-cli.sh
- vpath/pjtester.yaml
Adjusting existing Prow integration test for minikube to support K3s.
https://github.com/kyma-project/cli/issues/671
> Add clitest lib and split test cases

- development/jobguard/scripts/run.sh
- prow/jobs/scans/protecode-guard.yaml
- templates/config.yaml
- templates/templates/protecode-guard.yaml
> Fix protecode-guard

- prow/scripts/build-addons.sh
- prow/scripts/build-compass-development-artifacts.sh
- prow/scripts/build-generic.sh
- prow/scripts/build-kcp-cli.sh
- prow/scripts/build-kcp-development-artifacts.sh
- prow/scripts/build-kyma-artifacts.sh
- prow/scripts/build.sh
- prow/scripts/cluster-integration/compass-gke-integration.sh
- prow/scripts/cluster-integration/control-plane-gke-integration.sh
- prow/scripts/cluster-integration/helpers/start-wssagent.sh
- prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
- prow/scripts/cluster-integration/kyma-gke-compass-integration.sh
- prow/scripts/cluster-integration/kyma-gke-external-registry.sh
- prow/scripts/cluster-integration/kyma-gke-integration-cli.sh
- prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
- prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh
- prow/scripts/cluster-integration/kyma-gke-release-candidate.sh
- prow/scripts/cluster-integration/kyma-integration-gardener-azure.sh
- prow/scripts/governance.sh
- prow/scripts/metadata-governance.sh
- prow/scripts/publish-buildpack.sh
> scripts: remove init

- prow/scripts/cluster-integration/kyma-integration-gardener-azure.sh
Added one too many lines, it doesn't use Google authentication.
- fix `prow/scripts/cluster-integration/kyma-integration-gardener-azure.sh`
#2974, #3063
> scripts: fix gardener azure integration

- development/tools/jobs/kyma/kyma_integration_test.go
- prow/jobs/kyma/kyma-integration.yaml
- templates/templates/kyma-integration.yaml
- Add k3s integration test changes to trigger the test
> Add k3s integration test changes to trigger the test

- prow/scripts/lib/docker.sh
Now it loads log before using it
- `lib/docker` now imports log on its own
#2974
> scripts: fix docker lib

- development/tools/jobs/incubator/third-party-images/cloudsql-proxy/cloudsql_proxy_test.go
- prow/jobs/incubator/third-party-images/cloudsql-proxy/cloudsql-proxy.yaml
- Add cloudsql-proxy image jobs
> Add cloudsql-proxy image jobs

- prow/jobs/scans/protecode-guard.yaml
- templates/templates/protecode-guard.yaml
> Fix run-if-changed for p-guard

- prow/branchprotector-config.yaml
- prow/jobs/pamela/pamela.yaml
- prow/jobs/scans/protecode-guard.yaml
- templates/config.yaml
- templates/templates/branchprotector-config.yaml
- Update pamela repo from kyma-incubator to kyma-project
> Update pamela repo from kyma-incubator to kyma-project

- development/image-syncer/external-images.yaml
- Add alpine 3.12.3 version to the GCR
> Add alpine 3.12.3 version to the GCR

- development/image-syncer/external-images.yaml
- Add Golang new version to the GCR
> Add Golang new version to the GCR

- prow/jobs/scans/protecode-guard.yaml
- templates/templates/protecode-guard.yaml
> Add 'main' branch to protecode guard config

- prow/cluster/components/13-sinker_deployment.yaml
- prow/cluster/components/15-deck_deployment.yaml
- prow/cluster/components/30-crier_deployment.yaml
> Remove non-existent secret from prow deployments

- development/image-syncer/external-images.yaml
- Add new version of service catalog
> Add new version of service catalog

- prow/scripts/lib/gcloud.sh
- Remove EXIT_STATUS from `gcloud::cleanup`
#2974
> scripts: fix gcloud::cleanup

- prow/images/whitesource-scanner/Dockerfile
Related issues:
https://github.com/kyma-project/test-infra/pull/3092
> Bump Whitesource Scanner buildpack

- prow/scripts/cluster-integration/kyma-integration-gardener.sh
- removed `log::info` as it is already in `gardener::provision_cluster`
#2974
> scripts: remove doubled log::info

- prow/scripts/build-kyma-artifacts.sh
> Fix gcloud::authenticate in build-kyma-artifacts.sh

- prow/scripts/build-generic.sh
- prow/scripts/build-kyma-artifacts.sh
- vpath/pjtester.yaml
> Fix build artifacts

- development/tools/jobs/cli/cli_integration_test.go
- prow/jobs/cli/cli-integration.yaml
- prow/scripts/cluster-integration/kyma-cli-alpha-upgrade.sh
- prow/scripts/lib/cli-alpha.sh
- vpath/pjtester.yaml
- Add new pipeline for cli alpha features
- Pipeline workflow:
- Compile cli from master
- Provision gardener cluster from cli
- Install kyma  stable release with `alpha deploy`
- Run test suite
- Update kyma to latest master
- Run test suite
> **NOTE:** console-web tests are failing constantly and were disabled for this pipeline
- Implements #3057
> Add pipeline for kyma cli alpha feature - upgrade

- prow/jobs/incubator/compass-console/compass/compass-ui.yaml
- prow/jobs/incubator/compass/compass-gke-integration.yaml
- prow/jobs/incubator/compass/compass-integration.yaml
- prow/jobs/incubator/compass/components/connectivity-adapter/connectivity-adapter-generic.yaml
- prow/jobs/incubator/compass/components/connector/connector-generic.yaml
- prow/jobs/incubator/compass/components/director/director-generic.yaml
- prow/jobs/incubator/compass/components/external-services-mock/external-services-mock-generic.yaml
- prow/jobs/incubator/compass/components/gateway/gateway-generic.yaml
- prow/jobs/incubator/compass/components/healthchecker/healthchecker-generic.yaml
- prow/jobs/incubator/compass/components/pairing-adapter/pairing-adapter-generic.yaml
- prow/jobs/incubator/compass/components/schema-migrator/schema-migrator-generic.yaml
- prow/jobs/incubator/compass/components/system-broker/system-broker-generic.yaml
- prow/jobs/incubator/compass/components/tenant-fetcher/tenant-fetcher-generic.yaml
- prow/jobs/incubator/compass/tests/connectivity-adapter/connectivity-adapter-tests-generic.yaml
- prow/jobs/incubator/compass/tests/connector-tests/connector-tests-generic.yaml
- prow/jobs/incubator/compass/tests/director/director-generic-approach.yaml
- prow/jobs/incubator/compass/tests/ord-service/ord-service-tests-generic.yaml
- prow/jobs/incubator/compass/tests/tenant-fetcher/tenant-fetcher-tests-generic.yaml
- prow/jobs/incubator/ord-service/components/ord-service/ord-service-generic.yaml
- templates/config.yaml
- templates/templates/compass-gke-integration.yaml
- templates/templates/compass-integration.yaml
- templates/templates/generic-compass-component.yaml
- introduced enriched Compass generic templates which contain `^hotfix-.*$` branch rule
- regenerated all jobs to start taking into account hotfix branches
> Run Compass jobs on PRs against hotfix branches

- prow/scripts/build-kyma-artifacts.sh
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-kyma-artifacts/1348654244953067520
- ...
- ...
- ...
> remove readonly variable from copy_artifacts

- prow/jobs/incubator/compass/compass-gke-integration.yaml
- templates/templates/compass-gke-integration.yaml
Related issue: https://github.com/kyma-project/test-infra/pull/3099
> Ensure Compass GKE integration test job is executed for hotfix PRs

- prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
- prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
-10k sample limit is not enough to prevent the prometheus from OOM. Reducing sample limit to 8k and also increasing memory to 8Gi
> Reduce the sample limits to 8000

- development/tools/jobs/kyma/kyma_artifacts_test.go
- prow/jobs/kyma/kyma-artifacts.yaml
- prow/jobs/kyma/kyma-integration.yaml
- prow/scripts/provision-vm-and-start-kyma-minikube.sh
- templates/templates/kyma-artifacts.yaml
- templates/templates/kyma-integration.yaml
> Fix artifacts extra_ref

- development/tools/jobs/kyma/kyma_integration_test.go
- prow/jobs/kyma/kyma-integration.yaml
- templates/templates/kyma-integration.yaml
> Change label to preset-build-pr: "true" in release integration jobs

- prow/scripts/build-kyma-artifacts.sh
> workaround for release presubmits - rollback release kyma-installer to develop for the PRs

- development/tools/jobs/kyma/kyma_artifacts_test.go
- development/tools/jobs/kyma/kyma_integration_test.go
- docs/prow/prow-architecture.md
- prow/jobs/incubator/compass/compass-development-artifacts.yaml
- prow/jobs/kyma/kyma-artifacts.yaml
- prow/jobs/kyma/kyma-integration.yaml
- prow/scripts/build-kyma-artifacts.sh
- prow/scripts/provision-vm-and-start-kyma-minikube.sh
- templates/templates/kyma-artifacts.yaml
- templates/templates/kyma-integration.yaml
> Sync changes from master to release-1.19 branch

- prow/scripts/cluster-integration/compass-gke-integration.sh
- prow/scripts/cluster-integration/control-plane-gke-integration.sh
- prow/scripts/cluster-integration/helpers/cleanup-cluster.sh
- prow/scripts/cluster-integration/helpers/create-cluster.sh
- prow/scripts/cluster-integration/helpers/get-letsencrypt-cert.sh
- prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
- prow/scripts/cluster-integration/kyma-gke-central.sh
- prow/scripts/cluster-integration/kyma-gke-compass-integration.sh
- prow/scripts/cluster-integration/kyma-gke-external-registry.sh
- prow/scripts/cluster-integration/kyma-gke-integration-cli.sh
- prow/scripts/cluster-integration/kyma-gke-integration.sh
- prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
- prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh
- prow/scripts/cluster-integration/kyma-gke-release-candidate.sh
- prow/scripts/cluster-integration/kyma-gke-upgrade.sh
- prow/scripts/lib/gcloud.sh
- prow/scripts/lib/utils.sh
- vpath/pjtester.yaml
- update `kyma-gke-integration.sh` to utilise `gcloud::` functions
-  fix typo in `gcloud::provision_gke_cluster`
- deprecate some of `prow/scripts/cluster-integration/helpers` in favour of `gcloud::` alternatives:
- `encrypt` and `decrypt`
- `create-dns-record` and `delete-dns-record`
- `reserve-ip-address` and `release-ip-address`
- `create-network-with-subnet` and `network-exists`
- `provision-gke-cluster` and `deprovision-gke-cluster`
- deprecate some of `prow/scripts/cluster-integration/helpers` in favour of `utils::` alternatives:
- `generate-self-signed-cert` with `utils::generate_self_signed_cert`
#2974
> Gcloud lib integration

- prow/jobs/kyma/kyma-integration-gardener.yaml
- prow/scripts/lib/gardener/azure.sh
- templates/templates/kyma-integration-gardener.yaml
- Run gardener-azure-evaluation pipeline every hour
- Increase kyma installation timeout
> Gardener azure evaluation changes

- prow/jobs/kyma/kyma-integration.yaml
- templates/config.yaml
> Bump GKE regular version to 1.17.14-gke.1200

- prow/jobs/kyma/kyma-gke-compass-integration.yaml
- prow/jobs/kyma/kyma-release-pr-image-guard.yaml
- prow/jobs/kyma/kyma-release-upgrade.yaml
- prow/scripts/build-generic.sh
- prow/scripts/build-kyma-artifacts.sh
- templates/templates/kyma-gke-compass-integration.yaml
- templates/templates/kyma-release-upgrade.yaml
Follow-up PR with fixes for release jobs.
- rollback `pre-release-pr-image-guard` to be required
- fix typo in `build-kyma-artifacts.sh` script
- run `post-relXXX-kyma-gke-release-upgrade` jobs after GitHub release.
> Followup fixes and improvements for release jobs and scripts

- prow/jobs/scans/whitesource-periodics.yaml
- templates/config.yaml
- Add whitesource scan job for the repo github.com/kyma-incubator/podpreset-crd
> Configure whitesource scan job for podpreset-crd repo

- prow/jobs/kyma/kyma-release-pr-image-guard.yaml
> Make pre-release-pr-image-guard required again.

- prow/scripts/cluster-integration/helpers/create-azure-event-hubs-secret.sh
- prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
- prow/scripts/lib/kyma.sh
- vpath/pjtester.yaml
- integrate `install-test-log-collector` helper into `kyma::run_test_log_collector`
- use `az::create_resource_group` when possible
#2974
> Scripts:refactor helpers

- prow/jobs/kyma/kyma-integration-gardener.yaml
- prow/scripts/cluster-integration/kyma-integration-gardener.sh
- prow/scripts/lib/gardener/azure.sh
- templates/templates/kyma-integration-gardener.yaml
- Add pipeline to periodically run fast-integration tests on azure with production profile
> Run fast-integration on azure production periodically

- prow/scripts/lib/gardener/azure.sh
- Add missing production overrides to cli install call
> Add missing production overrides to cli install call

- prow/scripts/lib/gardener/azure.sh
- Remove production overrides to cli install call
> Remove production overrides to cli install call

- development/tools/jobs/kyma/kyma_integration_test.go
- prow/jobs/kyma/kyma-integration.yaml
- templates/templates/kyma-integration.yaml
> Add k3s periodic job

- development/tools/jobs/incubator/components_test.go
- development/tools/jobs/incubator/tests_test.go
- prow/jobs/incubator/compass/components/tenant-fetcher/tenant-fetcher-generic.yaml
- prow/jobs/incubator/compass/tests/tenant-fetcher/tenant-fetcher-tests-generic.yaml
- templates/config.yaml
> Make Tenant Fetcher component & test jobs mandatory

- prow/scripts/build-generic.sh
- prow/scripts/build-kyma-artifacts.sh
> Fix build.sh on 1.18

- prow/scripts/lib/docker.sh
> Fix docker.sh

- prow/scripts/cluster-integration/kyma-gke-upgrade.sh
- prow/scripts/lib/azure.sh
- prow/scripts/lib/cli-alpha.sh
- prow/scripts/lib/clitests.sh
- prow/scripts/lib/common.sh
- prow/scripts/lib/gardener/aws.sh
- prow/scripts/lib/gardener/azure.sh
- prow/scripts/lib/gardener/gcp.sh
- prow/scripts/lib/gcloud.sh
- prow/scripts/lib/kyma.sh
- prow/scripts/lib/utils.sh
- prow/scripts/provision-vm-and-start-kyma-minikube.sh
> Fix libs directory

- prow/scripts/lib/gcloud.sh
The release channel for gcloud container did not include the `--security-group` flag. This one is needed for the release clusters.
- ...
- ...
- ...
> Use beta channel for cluster creation.

- prow/jobs/kyma/kyma-github-release.yaml
- prow/jobs/kyma/kyma-release-candidate.yaml
- prow/scripts/lib/gcloud.sh
- templates/templates/kyma-github-release.yaml
- templates/templates/kyma-release-candidate.yaml
> Remove run_if_changed from release jobs

- prow/scripts/lib/README.md
- prow/scripts/lib/github.sh
-add readme for `prow/scripts/lib` directory
#2974, #3140
> scripts: add readme for lib

- prow/scripts/provision-vm-and-start-kyma-minikube.sh
> Fix provision-vm-and-start-kyma-minikube.sh on release-1.18

- prow/jobs/kyma/kyma-integration-gardener.yaml
- templates/templates/kyma-integration-gardener.yaml
- Add profiles integration jobs to testgrid
> Add profiles integration jobs to testgrid

- development/image-syncer/external-images.yaml
Add images for Istio 1.8.2 to image syncer list
- Add images for Istio 1.8.2 to image syncer list
> Extend image-syncer with istio 1.8.2 images

- prow/scripts/cluster-integration/kyma-gke-upgrade.sh
> static last release version 1.17.1

- prow/jobs/kyma/kyma-integration-gardener.yaml
- prow/scripts/lib/gardener/azure.sh
- templates/templates/kyma-integration-gardener.yaml
- Flag to clean only succeeded clusters
> Flag to clean only succeeded clusters

- prow/scripts/cluster-integration/helpers/cleanup-cluster.sh
- prow/scripts/cluster-integration/helpers/get-letsencrypt-cert.sh
- prow/scripts/cluster-integration/helpers/install-kyma.sh
- prow/scripts/cluster-integration/kyma-gke-release-candidate.sh
- prow/scripts/cluster-integration/minio/azure-cleaner.sh
- prow/scripts/lib/utils.sh
- vpath/pjtester.yaml
- change `generate-and-export-letsencrypt-TLS-cert` to `utils::generate_letsencrypt_cert`
- performance cluster was removed in #2565, remove `PERFORMACE_CLUSTER_SETUP` as it's never being set
- `delete-disks` is only used by one scripts, so it might be as well just integrated with that file
#2974
> scripts: integrate helpers

- prow/scripts/cluster-integration/helpers/cleanup-gardener.sh
- prow/scripts/cluster-integration/kyma-upgrade-gardener-azure.sh
- prow/scripts/lib/gardener/aws.sh
- prow/scripts/lib/gardener/azure.sh
- prow/scripts/lib/gardener/gcp.sh
- prow/scripts/lib/utils.sh
- prow/scripts/unstale-gardener-project.sh
- replace `deprovision-gardener-cluster` with `utils::deprovision_gardener_cluster`
#2974
> scripts: refactor deprovision-gardener-cluster

- prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
- ...
- ...
- ...
https://github.com/kyma-project/kyma/issues/9531
> Add kubeaudit to nightly and weekly

- development/tools/jobs/kyma/kyma_integration_test.go
- development/tools/jobs/tester/tester.go
- prow/jobs/kyma/kyma-integration.yaml
- templates/templates/kyma-integration.yaml
> Update VM cleaner image

- prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
> Fix kubeaudit in nightly

- prow/jobs/scans/protecode-guard.yaml
- templates/data/protecode-guard-data.yaml
> Fix protecode guard - add missing variable

- prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
> Update kubeaudit in long lasting cluster

- prow/jobs/kyma/kyma-integration.yaml
- templates/config.yaml
> bump gke version in rapid and regular channels

- prow/scripts/lib/utils.sh
- change readonly variable to local
> Fix utils::deprovision_gardener_cluster

- prow/scripts/cluster-integration/serverless-integration-k3s.sh
- vpath/pjtester.yaml
- as in desccription, installation of helm and jq is causing crashes https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/10436/pre-master-serverless-integration-k3s/1353709993345421312
> Use helm that is already in the vm in serverless-integration-k3s.sh

- prow/jobs/incubator/marketplaces/marketplaces.yaml
> reduce marketplaces.yaml requests to 800mi/1.5Gi

- prow/scripts/cluster-integration/helpers/cleanup-gardener.sh
- Cleanup Gardener clusters after 12h
> Cleanup Gardener clusters after 12h

- prow/config.yaml
- templates/templates/prow-config.yaml
> Switch stability-checker notification to new workspace

- development/tools/cmd/pjtester/README.md
- Fix typo in the  pjtester readme
> Fix pjtester readme typo

- prow/jobs/pamela/pamela.yaml
- prow/jobs/scans/protecode-guard.yaml
- templates/data/buildpack-node-data.yaml
- templates/data/protecode-guard-data.yaml
Since changes in the prowjobs templates some variables were missing which prevented from Pamela jobs to run
- ...
- ...
- ...
> Restore missing variables in Pamela prowjobs

- prow/jobs/kyma/kyma-integration-gardener.yaml
- prow/scripts/cluster-integration/helpers/cleanup-gardener.sh
- templates/templates/kyma-integration-gardener.yaml
- Remove gardener clusters after failed tests
- Cleanup gardener clusters after 4h
> Remove gardener clusters after failed tests

- prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh
> Bump kyma previous version to 1.17.1 in kyma-gke-rel2rel-upgrade.sh

- prow/scripts/cluster-integration/control-plane-gke-integration.sh
- Adjust to the changes in Provisioner's chart
> Take into account change in Provisioner's chart

- prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
- prow/scripts/resources/azure-knative-eventing-logging.yaml
- disable knative-eventing logging
kyma-project/kyma#10466
> aks nightly: disable knative-eventing logging

- prow/scripts/cluster-integration/helpers/fluent-bit-stackdriver-logging.sh
- Adapt Fluent Bit overrides after https://github.com/kyma-project/kyma/commit/6865a964804a38032ace3755bf8805174d55203d
> Adapt Fluent Bit overrides

- prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh
Removed function `remove_addons_if_necessary` from kyma-gke-rel2rel-upgrade.sh because it caused the post-release-upgrade pipeline to fail.
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-rel118-kyma-gke-release-upgrade/1354386329386881024
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-rel119-kyma-gke-release-upgrade/1353713139249582080
> Remove duplicated and unnecessary function from kyma-gke-rel2rel-upgrade.sh

- prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh
> Remove duplicated and unnecessary function from kyma-gke-rel2rel-upgrade.sh (#3218)

- development/test-log-collector/chart/test-log-collector/files/config.yaml
- Set new channel id for prow alerts
> Set new channel id for prow alerts

- prow/scripts/cluster-integration/kyma-cli-alpha-upgrade.sh
- remove execution of test of non existing component (apiserver-proxy)
- remove execution of super slow test (cluster-users)
> fixing constantly red kyma alpha deploy pipeline

- prow/jobs/kyma/kyma-release-candidate.yaml
- templates/templates/kyma-release-candidate.yaml
> Regional cluster for Kyma RC (#3189)

- prow/scripts/cluster-integration/helpers/fluent-bit-stackdriver-logging.sh
- Enable fluentbit to log everything
> Enable fluentbit to log everything

- prow/scripts/cluster-integration/kyma-cli-alpha-upgrade.sh
- removing test for non existing component
> Alpha deploy fix

- prow/scripts/cluster-integration/protecode-guard.sh
> Fix protecode guard script

- prow/scripts/lib/utils.sh
> Fix typo in utils::generate_letsencrypt_cert

- prow/jobs/scans/protecode-guard.yaml
- templates/data/protecode-guard-data.yaml
> Fix protecode guard labels

- prow/scripts/cluster-integration/serverless-integration-k3s.sh
- vpath/pjtester.yaml
- bump k3s version to newest one
kyma-project/kyma#8196
> k3s: bump version to 1.19.7

- prow/scripts/cluster-integration/kyma-cli-alpha-uninstall.sh
- removing test for non existing component kyma alpha uninstall pipeline
> removing test for non existing component kyma alpha uninstall pipeline

- prow/images/kyma-integration/Dockerfile
- prow/images/kyma-integration/Makefile
- prow/jobs/kyma/kyma-integration.yaml
- templates/templates/kyma-integration.yaml
- vpath/pjtester.yaml
With just one digit I can bring this component into modern times!
- bump up Google Cloud SDK version
- remove k8s 1.14 and 1.15
> bump gcloud sdk version to 324

- prow/scripts/cluster-integration/serverless-integration-k3s.sh
> Change docker registry to gcr

- development/tools/jobs/kyma/kyma_integration_test.go
- prow/jobs/kyma/kyma-integration.yaml
- templates/templates/kyma-integration.yaml
- vpath/pjtester.yaml
- ...
- ...
- ...
kyma-project/kyma#8196
> AKS: bump k8s to 1.19

- prow/scripts/lib/gardener/azure.sh
- see title
See https://github.com/kyma-project/kyma/pull/10507
> Fix fast-integration for kyma-evaluation-gardener-azure pipeline - test-infra part

- development/tools/jobs/incubator/components_test.go
- prow/jobs/incubator/compass/components/system-broker/system-broker-generic.yaml
- templates/config.yaml
- Make System Broker Prow job mandatory
- Add scripts folder change trigger
> Make System Broker Prow job mandatory and add trigger for scripts folder change

- prow/jobs/test-infra/testgrid-automation.yaml
- templates/data/testgrid-automation-data.yaml
- templates/templates/generic.tmpl
Add missing volumes in testgrid automation.
Fix volumes section in generic.tmpl
> Fix volumes section in generic.tmpl

- development/tools/jobs/kyma/kyma_integration_test.go
- prow/jobs/kyma/kyma-integration.yaml
- prow/scripts/cluster-integration/kyma-cli-alpha-uninstall.sh
- prow/scripts/cluster-integration/kyma-cli-alpha-upgrade.sh
- prow/scripts/cluster-integration/kyma-upgrade-gardener-azure.sh
- templates/templates/kyma-integration.yaml
> k8s: use new version in Gardener  and Azure jobs

- prow/jobs/kyma/kyma-integration.yaml
- prow/scripts/cluster-integration/kyma-gke-integration.sh
- prow/scripts/lib/gcloud.sh
- templates/config.yaml
- templates/templates/kyma-integration.yaml
- remove old channels
- replace hardcoded version with newest one
> gke: simplify channel k8s versioning

- prow/jobs/control-plane/control-plane-gke-integration.yaml
- prow/jobs/incubator/compass/compass-gke-integration.yaml
- prow/jobs/kyma/kyma-gke-compass-integration.yaml
- templates/templates/compass-gke-integration.yaml
- templates/templates/kyma-gke-compass-integration.yaml
- add renamed GKE_CLUSTER_VERSION variable
- jobs without this variable would default to k8s 1.17
> fix compass and control-plane jobs

- prow/jobs/kyma/kyma-compass-provisioner-tests.yaml
- provide `GKE_CLUSTER_VERSION` explicitly to use k8s 1.16 instead of default 1.17
> fix kyma-gke-compass-provisioner-tests jobs

- development/tools/jobs/control-plane/control_plane_gke_integration_test.go
- development/tools/jobs/control-plane/control_plane_gke_provisioner_integration_test.go
- development/tools/jobs/incubator/compass/compass_gke_integration_test.go
- development/tools/jobs/kyma/kyma_compass_provisioner_tests_test.go
- development/tools/jobs/kyma/kyma_gke_compass_integration_test.go
- prow/jobs/control-plane/control-plane-gke-integration.yaml
- prow/jobs/control-plane/control-plane-gke-provisioner-integration.yaml
- prow/jobs/incubator/compass/compass-gke-integration.yaml
- prow/jobs/kyma/kyma-compass-provisioner-tests.yaml
- prow/jobs/kyma/kyma-gke-compass-integration.yaml
- templates/templates/compass-gke-integration.yaml
- templates/templates/kyma-gke-compass-integration.yaml
- use `preset-cluster-version`
> k8s: use new version in Compass and control plane jobs

- development/tools/README.md
- tools directory now uses Go modules instead of old GOPATH dependencies
> tools: update readme

- prow/scripts/lib/gcloud.sh
- remove quotes from returned version string
> gcloud: remove quotes from k8s channel version

- prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh
- prow/scripts/cluster-integration/kyma-gke-upgrade.sh
- prow/scripts/cluster-integration/kyma-upgrade-gardener-azure.sh
- prow/scripts/lib/kyma.sh
- vpath/pjtester.yaml
- updated API calls to use HTTP headers authorisation
#2603
> GitHub: use HTTP headers authorisation

- prow/jobs/scans/protecode-guard.yaml
- templates/data/protecode-guard-data.yaml
> Make protecode-guard mandatory

- prow/config.yaml
- prow/jobs/cli/cli-integration.yaml
- prow/jobs/control-plane/control-plane-gke-integration.yaml
- prow/jobs/control-plane/control-plane-gke-provisioner-integration.yaml
- prow/jobs/incubator/compass/compass-gke-integration.yaml
- prow/jobs/kyma/kyma-compass-provisioner-tests.yaml
- prow/jobs/kyma/kyma-gke-compass-integration.yaml
- prow/jobs/kyma/kyma-gke-external-registry.yaml
- prow/jobs/kyma/kyma-integration.yaml
- prow/jobs/kyma/kyma-release-candidate.yaml
- prow/jobs/kyma/kyma-release-upgrade.yaml
- prow/scripts/lib/gcloud.sh
- templates/templates/compass-gke-integration.yaml
- templates/templates/kyma-gke-compass-integration.yaml
- templates/templates/kyma-gke-external-registry.yaml
- templates/templates/kyma-integration.yaml
- templates/templates/kyma-release-candidate.yaml
- templates/templates/kyma-release-upgrade.yaml
- templates/templates/prow-config.yaml
- vpath/pjtester.yaml
- enable PSP for all GKE jobs
#3260
> Enable PSP for GKE jobs

- prow/jobs/cli/cli-integration.yaml
> Disable reports for kyma-cli-alpha

- prow/jobs/incubator/compass/compass-gke-integration.yaml
- prow/jobs/kyma/kyma-compass-provisioner-tests.yaml
- prow/jobs/kyma/kyma-gke-compass-integration.yaml
- prow/jobs/kyma/kyma-integration.yaml
- templates/templates/compass-gke-integration.yaml
- templates/templates/kyma-gke-compass-integration.yaml
- templates/templates/kyma-integration.yaml
- vpath/pjtester.yaml
- All jobs that use older version of Kyma are failing with PSP enabled
#3270
> PSP: disable for integration jobs

- development/tools/jobs/incubator/third-party-images/grafana_test.go
- prow/jobs/incubator/third-party-images/third-party-images.yaml
- templates/data/incubator-third-party-images-data.yaml
- Add jobs for custom Grafana image
See https://github.com/kyma-project/kyma/issues/10344
> Add jobs for custom Grafana image

- prow/jobs/control-plane/control-plane-gke-integration.yaml
- prow/jobs/control-plane/control-plane-gke-provisioner-integration.yaml
> PSP: disable for control plane jobs

- development/image-syncer/external-images.yaml
- Remove external Grafana image
See https://github.com/kyma-project/kyma/issues/10344
> Remove external Grafana image

- prow/jobs/cli/cli-integration.yaml
Check if this will disable reporting.
> test if report: false works
