CODEOWNERS

- Add technical writers as codeowners to md files

Add technical writers as codeowners to md files

---

prow-configurations/config.yaml.tpl

To test it, you can change command for "ui-api-layer" presubmit job to:
```
command: ["sleep","120"]
```
and then add such comment many times:
```/test all```
After changes proposed in this PR, old job will be terminated and new one created; previously we ends up with many the same jobs running for the same PR.

Setup allow cancellation flag

---

prow-configurations/config.yaml.tpl
prow/config.yaml

- kyma-integration job runs on PR only if there were some changes to `resources` or `installation` directories
- kyma-integration runs on master branch after commit
As for now with job per component approach, it is not possible to run kyma-integration job only in case all components jobs succeeded.
#46

Run kyma-integration selectively

---

development/create-gcp-secrets.sh
development/install-prow.sh
prow/config.yaml
prow/jobs/kyma/kyma-integration.yaml

Checkout kyma for kyma integration job

---

prow/scripts/reserve-ip-address.sh

- Added script that reserve static IP address on GCP

Reserve static IP address on GCP

---

prow/images/cleaner/Dockerfile
prow/images/cleaner/README.md
prow/images/cleaner/cleaner.sh
prow/jobs/kyma/kyma-integration.yaml

Problem is described here: https://stackoverflow.com/questions/53180624/gcloud-cannot-provision-many-vm-using-one-service-account
Proposed solution: run periodic jobs that perform cleanups once a day

Fix error on running integration tests: Login profile size exceeds 32 KiB

---

prow/scripts/generate-self-signed-cert.sh

- Added script that generates a self signed certificate 

Generate self signed certificate

---

prow/scripts/cluster-integration/create-dns-record.sh

- gcloud DNS transaction will be aborted if create-dns-entry.sh script fails
- moved create-dns-entry.sh script to cluster-integration directory

Abort gcloud DNS transaction if create-dns-entry.sh script fails

---

README.md
development/README.md
docs/prow/README.md
docs/prow/kyma-release-process.md
docs/prow/production-cluster-configuration.md
docs/prow/prow-installation-on-forks.md
docs/prow/prow-secrets-management.md
prow/README.md
prow/cluster/README.md
prow/images/README.md
prow/images/bootstrap/README.md
prow/images/buildpack-golang/README.md
prow/images/buildpack-node/README.md
prow/scripts/README.md
prow/scripts/cluster-integration/README.md

- Reworked the main installation and secret management documents to provide a clear order of guides.
- Corrected wrong script paths in the above-mentioned document (upon consultation).
- Extracted the installation docs and the document on secret management to the `docs/prow` subfolder.
- Added folder structure for the main `README.md` documents in the repository.
- Provided an explanation of what Prow is, what purpose it serves and what basic configuration it consists of.
Refers to #70 and #69

Restructure documentation in test-infra

---

prow/jobs/test-infra/buildpack.jobs.yaml

- Run buildpack jobs only on master
See #54

Run buildpack jobs only on master

---

development/install-prow.sh

- Increase hmac token to 32 bytes
See #174

Increase hmac token to 32 bytes

---

prow/scripts/cluster-integration/create-dns-record.sh
prow/scripts/cluster-integration/delete-dns-record.sh
prow/scripts/cluster-integration/pr-gke-integration.sh

- generate correct self-signed certificate
- change the way IP_ADDRESS_NAME (and thus domain) is created:
IP_ADDRESS_NAME=~~"pr-${PULL_NUMBER}-job-${PROW_JOB_ID}"~~ -> IP_ADDRESS_NAME="pr-${PULL_NUMBER}-${BUILD_ID}". 
Since domains accepted by openssl must be shorter than 64 chars, PROW_JOB_ID turns out to be too long. For now, BUILD_ID is used. This is subject to further changes (e.g. BUILD_ID can be replaced by five-digit random int).
result of #20 
fixes #213 
results in #242 
** Follow-up **
- connector-service-tests fail. See #242

GKE integration pipeline: fix wrong DNS name in UI tests

---

development/tools/jobs/kyma/tools/gcp_broker_provider_test.go
prow/jobs/kyma/tools/gcp-broker-provider/gcp-broker-provider.yaml

Related to #164 
Connected with https://github.com/kyma-project/kyma/pull/1873
Plus rename incorrect `etcd backup test` function name.

Add jobs for gcp broker provider tool

---

prow/images/buildpack-node/Dockerfile

- added `libfontconfig` & `procps`, both required to run PhantomJS
See also #249

support PhantomJS in node-buildpack

---

development/tools/jobs/kyma/docs_test.go
prow/jobs/kyma/docs/docs.yaml

- Replace docs job image to Golang buildpack
#215

Replace docs job image to Golang buildpack

---

prow/cluster/05-limit-range.yaml
prow/cluster/README.md
prow/config.yaml
prow/install-prow.sh

This PR limits concurrent ProwJobs to 10. 
In the current setup, our cluster consists of 2 nodes with 4CPUs and 15GB RAM each. Our jobs require a lot of memory and CPU (golang compiliation). On the basis of `kubectl top pods` I saw that they consume 0.8CPU and <2GB memory, and because of that, I set ProwJob limit to 10. Resource consumption of Prow components is small.
In this PR I also introduced limtRange. It should prevent from running jobs on heavily loaded nodes (such Pod can exit with an error code and will not be restarted).

Limit concurrent prow jobs and define limit range.

---

prow/config.yaml
prow/jobs/test-infra/test-infra-governance.yaml
prow/jobs/website/website-governance.yaml

Interesting fact:
- all jobs that have ContextRequired() set to true are also treated as required_status_checks.
```
func (ps Presubmit) ContextRequired() bool {
if ps.Optional || ps.SkipReport {
return false
}
return true
}
```
In this PR I set `optional` flag to true for ` test-infra-governance` and `website-governace`.
Additionally, I reduced the list of `required_status_checks` for `branch-protection` to checks that are not derived from presubmit jobs configuration.  
TODO: After merging PR enable cronjob

Checks: test-infra-governance and website-governace should not be marked as required

---

development/README.md
development/clusters-cleanup.sh
development/disks-cleanup.sh
development/loadbalancer-cleanup.sh
development/resources-cleanup.sh
development/tools/cmd/diskscollector/main.go
development/tools/cmd/orphanremover/main.go
development/tools/jobs/kyma/kyma_integration_test.go
development/tools/jobs/tester/tester.go
prow/jobs/kyma/kyma-integration.yaml

- Introduces periodic job for removal of orphaned cluster
- Unifies scripts for launching tools (clusters, disks, load balancers)
- Adds tests for periodic jobs
Note for the reviewer: This PR changes jobs configuration to safe mode, dryRun = true.
This is on purpose because the changes can be tested only when they're merged on the master branch.
Once it's merged and a few runs on master confirm that configuration of jobs is correct, we'll switch the configuration to a "production" one with one subsequent PR.
See also #177

Orphaned clusters removal periodic job

---

development/README.md
development/tools/jobs/kyma/kyma_integration_test.go
development/vms-cleanup.sh
prow/jobs/kyma/kyma-integration.yaml

- Introduces periodic job for removal of orphaned VM instances in SAFE MODE (dryRun=true)
Note for the reviewer: Once this PR is merged and a few runs on master confirm that the configuration of the job is correct, it will be switched to a "production" mode with one subsequent PR.
See also #177

Add VM instances cleanup prowjob in dryrun mode.

---

docs/prow/prow-monitoring.md
prow/cluster/resources/monitoring/templates/prometheus-rule.yaml
prow/cluster/resources/monitoring/values.yaml

- Create alert rules on Prometheus for integration test failures 
- Add Slack configurations to Alertmanager
- Update documentation
See #15

Create alert rules for integration tests

---

development/tools/cmd/configuploader/main.go
development/tools/cmd/configuploader/main_test.go
development/tools/cmd/secretspopulator/main_test.go
development/tools/jobs/kyma/kyma_installer_test.go
development/tools/jobs/testinfra/branchprotector_test.go
prow/config.yaml
prow/jobs/kyma/kyma-installer.yaml

- Update branch protection rules for release 0.6. 
- Kyma-installer shoul be run manually because it has to build after component/installer

Update branch protection rules for release 0.6. 

---

prow/jobs/kyma/kyma-integration.yaml

- Disable auto trigger of the gke-upgradeability job
- https://github.com/kyma-project/kyma/issues/2259

Disable auto trigger of the gke-upgradeability job

---

prow/scripts/cluster-integration/kyma-gke-upgrade.sh

- Hot fix for:
```
#################################################################################################
Tue Jan 22 11:20:01 UTC 2019
/home/prow/go/src/github.com/kyma-project/test-infra/prow/scripts/cluster-integration/kyma-gke-upgrade.sh: line 282: COMMIT_ID: readonly variable
```

Hotfix for readonly property in gek-upgrade plan

---

development/tools/jobs/testinfra/buildpack_test.go
prow/images/bootstrap-helm/README.md
prow/jobs/test-infra/buildpack.yaml

In this PR new prowjobs were created to publish a new image "kyma-cluster-infra".
Purpose of a new image is to have all tools needed for managing Kyma Cluster:
- gcloud
- helm
- go
- dep
In a next PR I am going to add Dockerfiles

Add new prowjob for image "kyma-cluster-infra"

---

development/tools/jobs/kyma/ui_api_layer_acceptance_tests_test.go
development/tools/jobs/kyma/ui_api_layer_test.go
prow/jobs/kyma/components/ui-api-layer/ui-api-layer.yaml
prow/jobs/kyma/tests/ui-api-layer-acceptance-tests/ui-api-layer-acceptance-tests.yaml

- Change golang buildpacks in ui-api-layer and ui-api-layer acceptance tests to use Go 1.11
kyma-project/kyma#2113

Change golang buildpacks in ui-api-layer and acceptance tests

---

development/tools/cmd/clusterscollector/README.md
development/tools/cmd/clusterscollector/main.go
development/tools/pkg/clusterscollector/collector.go
development/tools/pkg/clusterscollector/collector_test.go
prow/scripts/cluster-integration/helpers/provision-gke-cluster.sh

Cluster collector removes clusters with a name that matches regexp. In addition to that, collector took into account label "job" which had a default value `^kyma-gke-integration`.
Currently, clusters are provisioned by many plans:
- kyma-gke-integrarion
- kyma-gke-upgrade
- weekly cluster
- nightly cluster
Some time ago, we fixed `provision-gke-cluster.sh` to use real name of the job - weekly cluster should not have label: `job:kyma-gke-integration`. This change caused that collector stopped to work. 
In this PR, all clusters provisioned by our scripts are marked with label "volatile=true" and collector can remove only volatile clusters.

Fix clusters removal process

---

development/github-release.sh
prow/scripts/build.sh

- In case of release jobs, check if the release version was already published in github
Fixes https://github.com/kyma-project/test-infra/issues/364

Verify that release was not published before creating release images

---

prow/scripts/provision-vm-and-start-kyma.sh

Adding a new flag --image to provision-vm-and-start-kyma script
- Adding a new flag --image that allows to manually specify the image to be used upon the creation of the VM using provision-vm-and-start-kyma.sh, if no image is provided, the latest default custom image will be automatically selected

Adding a new flag --image to provision-vm-and-start-kyma script

---

development/custom-image/README.md
development/custom-image/create-custom-image.sh

Updating create-custom-image with option --default to label the created custom image as default
- Add the flag --default to allow specifying the created custom image as one of the default images by adding the label "default : yes"

Adding the option to label the custom image as default

---

development/tools/pkg/release/version.go
development/tools/pkg/release/version_test.go

- fix the regexp that matches RELEASE_VERSION

Release tool: fix RELEASE_VERSION regexp

---

development/tools/Gopkg.lock
development/tools/cmd/secretspopulator/main.go
development/tools/cmd/secretspopulator/main_test.go

- Remove unnecessary update call when Secret data wasnt changed. 
- `oauth-token` already present in k8s and same as in bucket
- `hmac-token` already present in k8s but different than the one in bucket
- `kyma-alerts-slack-api-url` not defined in k8s
previously:
```
INFO[0002] Reading object [oauth-token.encrypted] from bucket [kyma-prow-secrets]
INFO[0002] Updating k8s secret [oauth-token] with key [oauth]
INFO[0002] Reading object [hmac-token.encrypted] from bucket [kyma-prow-secrets]
INFO[0002] Updating k8s secret [hmac-token] with key [hmac]
INFO[0005] Reading object [kyma-alerts-slack-api-url.encrypted] from bucket [kyma-prow-secrets]
INFO[0005] Creating k8s secret [kyma-alerts-slack-api-url] with key [secret]
```
currently:
``` …
```

Remove unnecessary update call when data are the same

---

prow/jobs/kyma/components/assetstore-controller-manager/assetstore-controller-manager.yaml

- Makes assetstore job run always, not on changes only

Fix for assetstore, always run job

---

development/tools/jobs/website/website_tools_content_loader_test.go
prow/jobs/website/tools/website-tools-content-loader.yaml

- Add job for new website tool - `content-loader`. This tool is to enable only fetching content for website, like a documentation from root repository, or (in the future) issues for roadmap section.
After resolving https://github.com/kyma-project/website/issues/196 `documentation-generator` job must be removed, because it will not be needed anymore.
- https://github.com/kyma-project/website/issues/196

Add job for website tool - content-loader

---

prow/scripts/cluster-integration/kyma-gke-long-lasting.sh

- Fix the installation of the stability checker after refactoring in Kyma repo, see: https://github.com/kyma-project/kyma/pull/2646/files
currently in logs we can see:
```
Start test
Test end with error [start time: 2019-02-19 08:44:56.671759519 +0000 UTC m=+14401.893771668, duration: 42.981965ms]
/data/input/testing.sh: line 4: /data/input/testing-common.sh: No such file or directory
-------------------------------
- Ensure test Pods are deleted
-------------------------------
/data/input/testing.sh: line 10: cleanupHelmTestPods: command not found
/data/input/testing.sh: line 13: cleanupHelmTestPods: command not found
/data/input/testing.sh: line 16: cleanupHelmTestPods: command not found
/data/input/testing.sh: line 19: …
```

Fix the installation of the stability checker after refactoring in Kyma repo

---

development/tools/jobs/kyma/development_artifacts_test.go
docs/prow/prow-architecture.md
prow/jobs/kyma/kyma-development-artifacts.yaml

- documentation for pre-master-kyma-development-artifacts and its postsubmit counterpart
- changed configuration that job on PR is executed only when any relevant changes to kyma were introduced that have an impact on the installed kyma. So if you changed only your component (for example helm-broker) but you have not updated charts, presubmit job will not be triggered.

Document generation of development  artifacts

---

development/tools/jobs/incubator/octopus/octopus_test.go
prow/jobs/incubator/octopus/octopus.yaml

- Add prow job for kyma-incubator/octopus
> **Note:** I've configured the job with `always_run: true` cause its separate repo not like in mono-repo Kyma. Of course, we can hardcode for some folders like *pkg*, *cmd* etc, but IMO it's easy to get out of sync and skip job check on some PR.
- https://github.com/kyma-project/kyma/issues/2639

Add prow job for kyma-incubator/octopus

---

prow/config.yaml

- Extended max concurrency to 50
We have more long running jobs (4) and prow is not ready for that:
I also extended autoscalling to 20 nodes. 

Extend max concurrency

---

prow/scripts/provision-vm-and-start-kyma.sh

Adding a new flag --image that allows to manually specify the image to be used upon the creation of the VM using provision-vm-and-start-kyma.sh, if no image is provided, the latest default custom image will be automatically selected

Adding --image flag to provision-vm-and-start-kyma.sh

---

development/tools/jobs/kyma/kyma_integration_test.go
prow/jobs/kyma/kyma-integration.yaml
prow/scripts/cluster-integration/kyma-gke-end-to-end-test.sh

- Fix deletetion of docker image in gke cluster script 
- Ignore errors from script to trigger the expected cleanup
- Set periodic job (kyma-gke-end-to-end-test-backup-restore) to be executed every hour

Delete docker image

---

development/tools/jobs/kyma/console_backend_service_test.go
development/tools/jobs/kyma/console_backend_service_test_test.go
development/tools/jobs/tester/tester.go
development/tools/jobs/testinfra/validate_test.go
prow/jobs/kyma/components/console-backend-service/console-backend-service.yaml
prow/jobs/kyma/tests/console-backend-service/console-backend-service-test.yaml

- Rename UI API Layer job to Console Backend Module
- Rename UI API Layer Acceptance Test job to Console Backend Module
https://github.com/kyma-project/kyma/issues/3104

Rename UI API Layer job to Console Backend Module

---

development/tools/jobs/kyma/asset_store_controller_manager_test.go
prow/jobs/kyma/components/asset-store-controller-manager/asset-store-controller-manager.yaml

- Reverted postsubmit job for old Asset Store location
- Made presubmit job for old Asset Store location as optional

Revert postsubmit Asset Store job and make old presubmit job as optional

---

development/tools/jobs/kyma/kyma_integration_test.go
prow/jobs/kyma/kyma-integration.yaml
prow/scripts/cluster-integration/kyma-aks-long-lasting.sh

In this PR I extended timeouts for Kyma and Stability Checker Installation, and change region where a cluster is provisioned. On old and new region time required for Kyma installation seems to be similar. Additionally, a new Azure subscription is used (changes on the bucket with encrypted secrets). 
To get more information about the root cause, see comments https://github.com/kyma-project/kyma/issues/3170

Change timeout fot AKS nightly cluster

---

prow/scripts/cluster-integration/kyma-gke-upgrade.sh

After upgrade of istio to version 1.1 15 minutes is not sufficient for upgrade
- extend timeout for kyma upgrade in kyma-gke-upgrade job from 15 to 25 minutes

Extend timeout for kyma upgrade in kyma-gke-upgrade job

---

development/tools/pkg/release/version.go
development/tools/pkg/release/version_test.go

Github release job is pretty dumb and it fails if RELEASE_VERSION file contains a newline at the end. As many text editors (including GitHub) automatically add newline at the end of the file, I thought we could make it more liberal. 

Allow newline in RELEASE_VERSION file

---

development/tools/cmd/dnscollector/main.go

- Add load-test and e2etest clusters in the dns cleanup cron 
**Reason**
-  DNS records:`*.load-test.build.kyma-project.io.` `gateway.load-test.build.kyma-project.io` `gateway.e2etest.build.kyma-project.io` `*.e2etest.build.kyma-project.io` are not cleaned up
- External IP: `e2etest` `remoteenvs-e2etest``load-test` `remoteenvs-load-test` are not cleaned up

Add load test and e2etest clusters to the cleaner

---

prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
prow/scripts/cluster-integration/kyma-gke-long-lasting.sh

Rolling back to old certificate retrieval to unblock nightly and weekly builds
- Changing back to this commit: https://github.com/kyma-project/test-infra/tree/3ae46fbf8391c5663bc03605c703e0db29e5a55f/prow/scripts/cluster-integration
#646

rollback to old certificate retrieval

---

development/tools/cmd/clusterscollector/README.md
development/tools/cmd/clusterscollector/main.go
development/tools/pkg/clusterscollector/collector.go
development/tools/pkg/clusterscollector/collector_test.go
prow/scripts/cluster-integration/helpers/provision-gke-cluster.sh

The pull request allows to the change of the filter strategy, based on which test-clusters get deleted. It also enables creation of `ttl` and `created-at` labels on clusters that will be affected by this, once the prow job uses this strategy.
- provide an alternative filter strategy for cluster deletion
- add `ttl` and `created-at` labels to gke integration clusters
#565

Cluster cleanup

---

prow/jobs/kyma/kyma-github-release.yaml

- Fix pointing Github release tag for 0.9

Fix pointing Github release tag for 0.9

---

prow/scripts/cluster-integration/kyma-gke-upgrade.sh

Add set variable **global.domainName** containing the domain.
It is required for upgrade function test

Add domain name to script kyma-gke-upgrade.sh.

---

prow/scripts/cluster-integration/kyma-gke-upgrade.sh

```
#################################################################################################
#################################################################################################
Mon Apr  8 17:51:04 UTC 2019
Error: transport is closing
```
**Related issues**
Fixes #845

Fix GKE upgrade plans: get helm certs before creating test resources

---

prow/scripts/cluster-integration/helpers/install-kyma.sh
prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
prow/scripts/cluster-integration/kyma-gke-central.sh
prow/scripts/cluster-integration/kyma-gke-end-to-end-test.sh
prow/scripts/cluster-integration/kyma-gke-integration.sh
prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
prow/scripts/cluster-integration/kyma-gke-upgrade.sh

Kyma logging solution loki usses some kubernetes CRI functionalities which changed in kubernetes version 1.14.X and 1.12.6-gkeX, this changes will deploy kyma logging with specific kubernetes CRI settings.
For details see https://github.com/kyma-project/kyma/issues/3652

GKE k8s version 1.12.6-gkeX specific logging deployment changes

---

stability-checker/deploy/chart/stability-checker/templates/deploy.yaml

- configure stability-checker Pod template to work with readiness/liveness probes without k8s service
Resolves: #897

Fix stability-checker deployment - enable for istio sidecar

---

stability-checker/internal/printer/export_test.go
stability-checker/internal/printer/printer.go
stability-checker/internal/printer/printer_test.go

- enhance stability-checker to not fails if a log entry is not a valid JSON

Stability-checker reads non json log entries

---

prow/scripts/cluster-integration/helpers/cleanup-cluster.sh
prow/scripts/cluster-integration/kyma-gke-long-lasting.sh

We changed the labels for cleanup of leftovers and preserved the old value under `created-at-readable`. PR changes long-lasting cleaners to use this label.
- use `created-at-readable` label, as containers are tagged with this on the registry
#936

use readable label for old deletion

---

prow/config.yaml

Update branch protection for release branches.
- Add branch protector to release branches (in sync with protection of kyma repo)
#494

add test-infra branch protection for release branches, same as kyma repo

---

stability-checker/deploy/chart/stability-checker/templates/deploy.yaml

Comment inside `command` section of deployment containers caused yaml file could not be parse properly. This PR removes comment, fixes the `deploy.yaml` file and yaml can be parse without error.

Fix stability checker deployment yaml

---

docs/prow/prow-jobs.md

Adds documentation to describe how to manually trigger a new run (with changed code).
- modify docs to describe manual job run
#939

add documentation for manual job trigger (#939)

---

development/tools/cmd/clusterscollector/main.go
development/tools/jobs/kyma/kyma_integration_test.go
development/tools/pkg/clusterscollector/collector.go
development/tools/pkg/clusterscollector/collector_test.go
prow/jobs/kyma/kyma-integration.yaml

When I added a new "long-living cluster" it was removed by the clustercollector. It was a little bit surprising... 
Changes introduced in this PR:
- Remove not used strategy - it only mistook me, because where I saw:
```
if nameMatches && isVolatileCluster && ageMatches {
```
I thought my cluster should not be removed, but this strategy is not used. 
- Whitelisted clusters configurable; previously it was hardcoded in the go code, now I make it configurable to make it visible from Prow configuration
- Improve logging
Currently, I set `dryRun` flag to true, because I was not able to test it manually. 
If everything will work fine I will create another PR to set it to false.

Simplify cluster removal tool

---

prow/scripts/cluster-integration/helpers/install-kyma.sh
prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
prow/scripts/cluster-integration/kyma-gke-central-xip.sh
prow/scripts/cluster-integration/kyma-gke-central.sh
prow/scripts/cluster-integration/kyma-gke-end-to-end-test.sh
prow/scripts/cluster-integration/kyma-gke-integration-xip.sh
prow/scripts/cluster-integration/kyma-gke-integration.sh
prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
prow/scripts/cluster-integration/kyma-gke-minio-gateway.sh
prow/scripts/cluster-integration/kyma-gke-release-candidate.sh
prow/scripts/cluster-integration/kyma-gke-upgrade-xip.sh
prow/scripts/cluster-integration/kyma-gke-upgrade.sh

Add `--overwrite` flag to the `kubectl label installation kyma-installation action=install` commands.
The `action=install` label is to be added to the `installer-cr.yaml.tpl` file. As a result, the custom resource doesn't have to be labelled manually ever time the installation is triggered.
Once the relevant PR is merged, the commands will be entirely removed. 
https://github.com/kyma-project/kyma/issues/3932

Add --overwrite flag to 'kubectl label installation' command

---

prow/scripts/cluster-integration/helpers/install-stability-checker.sh
stability-checker/deploy/chart/stability-checker/templates/role.yaml

- Add roles for stability-checker
This PR should resolve this problem:
```
Error from server (Forbidden): configmaps \"dex-config\" is forbidden: User \"system:serviceaccount:kyma-system:stability-checker\" cannot get resource \"configmaps\" in API group \"\" in the namespace \"kyma-system\"
WARNING: following tests will be skipped due to the lack of static users:
Error from server (Forbidden): testdefinitions.testing.kyma-project.io is forbidden: User \"system:serviceaccount:kyma-system:stability-checker\" cannot list resource \"testdefinitions\" in API group \"testing.kyma-project.io\" at the cluster scope
```

Add roles for stability-checker

---

prow/scripts/cluster-integration/kyma-gke-release-candidate.sh

Due to Custom Resource Definitions and Custom Resources being applied in a single file, applying `kyma-installer-cluster.yaml` often fails. Adding retry should make sure that the resources would be applied correctly and the job will not fail.
- Add retries to RC provisioning job

Add retries to RC provisioning job

---

development/custom-image/install-deps-debian.sh
prow/config.yaml

There were changes made on organisation lever so that we can setup resources only on `europe-west5`.

GCP constraints issue (temporary fix)

---

development/tools/jobs/kyma/kyma_integration_test.go
prow/jobs/kyma/kyma-integration.yaml

We're removing all usages of template file **kyma-config-cluster.yaml** from Kyma installation process. It requires changes in scripts used by several Prow Jobs.
- Add a Job for testing new version of pre-master-kyma-gke-integration.
See also: 
- #1024 
- https://github.com/kyma-project/kyma/pull/4118

GKE integration test job added

---

development/tools/jobs/kyma/kyma_integration_test.go
prow/jobs/kyma/kyma-integration.yaml

We're removing all usages of template file kyma-config-cluster.yaml from Kyma installation process. It requires changes in scripts used by several Prow Jobs.
- Add a Job for testing new version of **pre-master-kyma-gke-central-connector**.
See also:
- #1024 
- https://github.com/kyma-project/kyma/pull/4118

GKE central connector test job added

---

development/tools/jobs/kyma/kyma_integration_test.go
prow/jobs/kyma/kyma-integration.yaml

We remove all usages of template file **kyma-config-cluster.yaml** from Kyma installation process. It requires changes in scripts used by several Prow Jobs.
- Add a Job for testing new version of **kyma-gke-upgrade.sh**.
See also:
- #1024 
- https://github.com/kyma-project/kyma/pull/4118

Add kyma-gke-upgrade presubmit test job

---

performance-tools/performance-cluster/Dockerfile

- Use [gcloud sdk version 247.0.0](https://cloud.google.com/sdk/docs/release-notes)
- Remove duplicate kubectl commands (one installed by gcloud, one installed via curl)
- Use kubectl provided by gcloud only
- The newer kubectl version provides the `kubectl wait` command which is useful for https://github.com/kyma-project/kyma/pull/4156
```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.8-dispatcher", GitCommit:"1215389331387f57594b42c5dd024a2fe27334f8", GitTreeState:"clean", BuildDate:"2019-05-13T18:09:56Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

Use latest gcloud sdk version for performance tests

---

development/tools/jobs/kyma/kyma_integration_test.go
prow/jobs/kyma/kyma-integration.yaml

We remove all usages of template file **kyma-config-cluster.yaml** from Kyma installation process. It requires changes in scripts used by several Prow Jobs.
- Add a Job for testing new version of **gke-long-lasting.sh**
See also #1024

Added test job for gke-long-lasting (copy of nightly cluster)

---

development/tools/jobs/kyma/kyma_integration_test.go
prow/jobs/kyma/kyma-integration.yaml

- Limit the `pre-master-kyma-gke-central-connector` job to run on the `resources/application-connector` images change instead of all `resources` images
See the issue #1015

Limit central-connector job to run on application-connector images change

---

performance-tools/performance-cluster/Dockerfile

Prevent error happening in:
```
kubectl get -n kyma-installer secret helm-secret -o jsonpath="{.data['global\.helm\.ca\.crt']}" | base64 --decode > "$(helm home)/ca.pem"
kubectl get -n kyma-installer secret helm-secret -o jsonpath="{.data['global\.helm\.tls\.crt']}" | base64 --decode > "$(helm home)/cert.pem"
kubectl get -n kyma-installer secret helm-secret -o jsonpath="{.data['global\.helm\.tls\.key']}" | base64 --decode > "$(helm home)/key.pem"
```
**helm command not found.**

Add helm installation to the Dockerfile

---

prow/scripts/cluster-integration/kyma-gke-upgrade-xip.sh
prow/scripts/cluster-integration/kyma-gke-upgrade.sh

- Ensure backward compatibility in upgrade jobs: restore CR labelling
caused by #1085

Ensure backward compatibility in upgrade jobs: restore CR labelling

---

development/tools/jobs/kyma/apiserver_proxy_new_test_test.go
prow/jobs/kyma/tests/apiserver-proxy-tests/apiserver-proxy-test-new.yaml
prow/jobs/kyma/tests/integration/apiserver-proxy/apiserver-proxy-integration.yaml

Copy apiserver-proxy integration tests to new destination directory.
- New job definition for tests in the new location in Kyma sources
- Test for new job definition
Implements #https://github.com/kyma-project/kyma/issues/4441
See also #https://github.com/kyma-project/kyma/issues/4662

Add prowjob for moved apiserver-proxy tests

---

prow/set-up-workload-cluster.sh

- Replace default config map with new one 
was `nodesPerReplica: 16` new settings `nodesPerReplica: 8`
https://github.com/kyma-project/test-infra/issues/1198

Overwrite kube-dns-autoscaler config map

---

development/tools/jobs/kyma/knative_function_controller_test.go
prow/jobs/kyma/components/knative-function-controller/knative-function-controller.yaml

Update the prow job with right golang image.
The prow job fails because of the wrong golang image. 
kyma-project/kyma#4803

Add the right buildpack-golang-kubebuilder image in the prow job

---

prow/jobs/kyma/kyma-integration.yaml

Job failed due to workspace not being properly mapped.
- map workspace ref

Whitesource job is missing the workspace mapping

---

development/tools/jobs/incubator/hack-showcase/hack_showcase_test.go
prow/jobs/incubator/hack-showcase/hack-showcase.yaml

During the process of connecting our repository to Prow, we found a problem with jobs triggering caused by a wrong path in field "run_if_changed". To fix this problem and allow Prow to react on every change in our repository (triggering on every PR) we were advised to change this field to "always_run". 
- Change the way of triggering jobs for [hack-showcase](https://github.com/kyma-incubator/hack-showcase)
- Add appropriate tests for this change
**Related issue**
https://github.com/kyma-incubator/hack-showcase/issues/39

Fix problem with jobs in hack-showcase

---

prow/scripts/cluster-integration/kyma-gke-compass-integration.sh

- Disable the tests manipulating the Application resource in `kyma-gke-compass-integration` pipeline. These tests will fail due to the fact that Runtime Agent deletes the Applications if they don't exist in the Director Component.
See the issue [#1335 ](https://github.com/kyma-project/test-infra/issues/1335)

Disable the tests manipulating the Application resource in kyma-gke-compass-integration

---

prow/jobs/kyma/kyma-compass-integration.yaml

**Do not merge until `pre-master-kyma-gke-compass-integration` is stable!**
- Make `pre-master-kyma-gke-compass-integration` job required
- Do not skip Slack reports in `kyma-gke-compass-integration` jobs
See the issue #1335

Adjust kyma-gke-compass-integration jobs after stabilization

---

prow/scripts/cluster-integration/helpers/start-wssagent.sh

Service account not logged in in gcloud
- unauthenticated gcloud not allowed, so we authenticate now

init sa account

---

prow/scripts/cluster-integration/helpers/start-wssagent.sh

Contrary to my thinking yesterday, I missed that there is actually no `source` of the library, it is just checking the path.

source library missing

---

prow/jobs/incubator/compass/components/connector/connector-old-releases.yaml
prow/jobs/incubator/compass/components/connector/connector.yaml
prow/jobs/incubator/compass/components/director/director-old-releases.yaml
prow/jobs/incubator/compass/components/director/director.yaml
prow/jobs/incubator/compass/components/gateway/gateway-old-releases.yaml
prow/jobs/incubator/compass/components/gateway/gateway.yaml
prow/jobs/incubator/compass/components/healthchecker/healthchecker-old-releases.yaml
prow/jobs/incubator/compass/components/schema-migrator/schema-migrator-old-releases.yaml
prow/jobs/incubator/compass/components/schema-migrator/schema-migrator.yaml
prow/jobs/incubator/compass/tests/end-to-end/end-to-end-old-releases.yaml
prow/jobs/incubator/compass/tests/end-to-end/end-to-end.yaml
prow/jobs/test-infra/watch-pods.yaml
templates/config.yaml
templates/templates/compass-integration.yaml
templates/templates/component.yaml

- Every compass component is split into two files with jobs: one for releases 1.3 (suffix `old-releases`) and one for master pre and post submits  
- Components from test infra no longer have extra-ref for test infra. That includes watch-pods for now. 
#1416

Fix compass and watch-pods templates configuration

---

prow/scripts/cluster-integration/helpers/create-dns-record.sh
prow/scripts/cluster-integration/helpers/reserve-ip-address.sh

Redoing #1447. Since reserve-ip-address is returning the reserved IP address on stdout, there can be no other output on this script.
- refactor of the previously proposed changes

reserve-ip-address.sh returns the reserved IP on stdout

---

prow/scripts/cluster-integration/helpers/cleanup-cluster.sh

Based on my findings, APIserver DNS entries are only created but not cleaned up as @kasiakepka suggested here: #1446 
- delete dns entries for APIserver before deleting any other DNS entries

delete APIserver proxy ip from DNS

---

prow/scripts/cluster-integration/helpers/start-wssagent.sh

Scan results of the "full" project scan are useless. splitting up into component scans.
- loop over components
- scan installation and commons

Whitesource component split

---

prow/scripts/cluster-integration/helpers/start-wssagent.sh

Collision of .bak files was introduced in a previous before, this is fixed in this PR, as well as an `sed` side-effect with forward slashes.
- `sed` to ignore forward slash
- collision of .bak files

fix collision of bak files, update sed to ignore slashes

---

prow/scripts/cluster-integration/helpers/start-wssagent.sh

Dependencies were not resolved properly. This PR changes the dependency manager config from `godep` to `dep` on scan.
- `go.dependencyManager=godep` to `go.dependencyManager=dep`

change dependency manager to dep

---

prow/scripts/cluster-integration/kyma-gke-backup-test.sh

Added missing parameters for release IP script execution. This was not critical error for job. Job failed because backup reported failed status.
Backup issues must be analysed.
Closes #1495

Added required arguments for release-ip-address.sh script execution.

---

prow/scripts/cluster-integration/helpers/start-wssagent.sh

scanning works in a way, that the other scan should be irrelevant.
- disable running on subfolders.

dont run on folders other than root

---

development/tools/cmd/dnscollector/main.go
development/tools/jobs/kyma/kyma_integration_test.go
prow/config.yaml
prow/jobs/kyma/kyma-integration.yaml
prow/workload-cluster/required-secrets.yaml
templates/templates/kyma-integration.yaml
templates/templates/prow-config.yaml

PR removes `kyma-gke-service-catalog-crd-periodic` jobs which test periodically new version of ServiceCatalog  with CRDs.

remove kyma-gke-service-catalog-crd-periodic job

---

prow/images/kyma-cluster-infra/Dockerfile

- Bumped kubectl
As Kubernetes 1.14 is available on AKS and GKE, we can set it as a default version.

Bump kubectl to 1.14.6 cluster image

---

development/custom-image/README.md

- Remove the non-existent anchor in the link to Google documentation on images. 
None

Fix a non-existent anchor in a link

---

development/tools/jobs/incubator/github-slack-connectors/github_connector_test.go
development/tools/jobs/incubator/github-slack-connectors/slack_connector_test.go
prow/jobs/incubator/github-slack-connectors/github-connector/github-connector.yaml
prow/jobs/incubator/github-slack-connectors/slack-connector/slack-connector.yaml

- rename hack-showcase jobs to github-slack-connectors

Rename hack showcase into github-slack-connectors

---

development/tools/jobs/incubator/octopus/octopus_test.go
prow/jobs/incubator/octopus/octopus.yaml

- Migrated octopus to go modules:
- Changed image to kubebuilder2
- Added GO111MODULE env for octopus jobs

Migrate octopus to go modules

---

development/provision-cluster.sh
prow/images/buildpack-golang-toolbox/Dockerfile
prow/images/buildpack-golang-toolbox/README.md

- Added kind
- Added high load node pool to workload cluster
The high load pool is needed for testing Kyma on kind, and building kubernetes image with kind. This node pool will scale to zero (max 5 nodes). Thanks to taints (https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/) configuration only pods with proper (see below) toleration will be scheduled in this pool.
```yaml
tolerations:
- key: resources-usage
value: high
operator: Equal
effect: NoSchedule
```
#1470

Add kind to toolbox image and high load node pool to workload cluster

---

development/tools/jobs/kyma/tests_test.go
prow/jobs/kyma/tests/integration/api-controller/api-controller-tests-generic.yaml
prow/jobs/kyma/tests/integration/api-controller/api-controller-tests.yaml
templates/config.yaml

- add missing "until" to apiserver-proxy and api-controller components
- switch to generic prow jobs for api-controller tests
See also kyma-project/kyma#5763

Switch to generic prow job for api-controller tests

---

prow/scripts/cluster-integration/kyma-gke-backup-test.sh

Velero plugin to set the Owner Reference of the NATS Channel Services.
See also:
Issue: https://github.com/kyma-project/kyma/issues/5942
PR: https://github.com/kyma-project/kyma/pull/6050

fix-backup-restore-event-bus

---

prow/jobs/incubator/dex/dex.yaml

Concurrent rename of dex tests job and introduction of dex job made configmap update not proper, what can be seen [here](https://github.com/kyma-project/test-infra/pull/1704#issuecomment-550229261).
Hopefully, this PR will trigger the update again.
- dummy change in dex job
See also #1704

Dummy change in dex job for configmap update

---

prow/scripts/kind-install-kyma.sh
prow/scripts/kyma-testing.sh
prow/scripts/lib/kyma.sh
prow/scripts/lib/log.sh
prow/scripts/lib/testing-helpers.sh

- Add JUnit XML reports per Kyma integration tests
This PRs add the kyma-testing.sh script which is using the Kyma CLI to execute Kyma integration tests and generate JUnit XML report which is consumed by Prow Job.
If this solution will be stable that we will move other jobs to also use the `kyma-testing.sh` script from test-infra instead of using `testing.sh` script from kyma repo.
Here you can find information about the next changes that are planned:
https://gist.github.com/mszostok/497fcee59651220920477260607153e3
- https://github.com/kyma-project/test-infra/issues/1636

Add JUnit XML reports per Kyma integration tests

---

prow/jobs/rafter/rafter.yaml

Enable go modules on rafter build job
See also: #3

Enable go modules on rafter build job

---

prow/jobs/kyma/kyma-integration-k8s-1-14.yaml

Fix the **pre-master-kyma-gke-backup-k8s-1-14** job by adding the missing `extra_refs`.
https://github.com/kyma-project/kyma/pull/6265

Fix the pre-master-kyma-gke-backup-k8s-1-14 job

---

prow/scripts/kyma-testing.sh

Currently, we need to have transition phase. In test-infra we will check if the injecting addon is still necessary if some TD will be discovered then it will be injected if not then it will be skipped.
- Add opt to inject addons only if necessary
**Blocked by:** https://github.com/kyma-project/kyma/pull/6491
- https://github.com/kyma-project/kyma/issues/6253

Add opt to inject addons only if necessary

---

prow/scripts/resources/prometheus-operator-stackdriver-patch.yaml

Fixed wrong volume name with prometheus db in stackdriver collector sidecar container.

Corrected volume name with prometheus db.

---

prow/scripts/cluster-integration/kyma-gke-release-candidate.sh

write out images and their tags running in the cluster, write them to artifacts folder
- when release cluster is deployed, query running cluster for images running in that cluster

Add artifact trace of images contained in release

---

prow/scripts/cluster-integration/kyma-aks-long-lasting.sh

- The nightly-aks job fails if there is no previous cluster to cleanup
- Make whole cleanup of the old cluster best-effort (allowed to fail)
**What Happened**
The nightly-aks job failed [today](https://storage.googleapis.com/kyma-prow-logs/logs/kyma-aks-nightly/1204249446955618305/build-log.txt) with the following error message:
```
#################################################################################################
#################################################################################################
%ERROR: Deployment failed. Correlation ID: 6d04def2-c83d-41b5-9f0c-649e95a98129. We are unable to serve this request due to an internal error, Correlation ID: bf900714-c095-44d3-93e7-18aa1a8163c8, Operation ID: …
```

Best-effort cleanup of nightly-aks cluster resources

---

milv.config.yaml

- Added the monitoring dashboard links to the white list as they regularly failed with the "certificate has expired or is not yet valid" error in the nightly governance job.

Add monitoring links to the white list

---

prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh
prow/scripts/cluster-integration/kyma-gke-upgrade-xip.sh

- Apply the same `remove_addons_if_necessary` function before final e2e testing for the two remaining upgrade jobs
https://github.com/kyma-project/kyma/issues/6740

Clean up test addons before e2e tests for remaining upgrade jobs

---

milv.config.yaml

Reverts kyma-project/test-infra#1876
Certificate on monitoring.build.kyma-project.io is replaced with valid one. No need to whitelist this URL as it should not fail anymore.

Revert "Add monitoring links to the white list"

---

development/vulnerabilities-scanner.sh

In order to show/update component security scans reports in Snyk the command `snyk monitor` needs to be executed during each component scan regardless of the scan result.
* added executing `snyk monitor` command during component scan
* added Snyk API error handling
Fixes #1807

Vulnerability scanner fix

---

development/tools/jobs/incubator/tests_test.go
prow/jobs/incubator/compass/tests/director-tests/director-tests-generic.yaml
templates/config.yaml

In Compass, we are going to rename `tests/end-to-end` to `tests/director-tests` to be consistent with other tests. In this PR, we add a new job that builds `director-tests` when it's code is changed, or `components/director` is modified (tests use Director code directly, not from vendored director).
For a transition phase, jobs `director-tests` and `end-to-end` are optional.

Adjust jobs definition after refactoring compass test directors

---

prow/jobs/scans/whitesource-periodics.yaml
prow/scripts/cluster-integration/helpers/start-wssagent.sh
templates/templates/whitesource-periodics.yaml

An unused if-else was throwing an error, also the passed variable has the wrong folder in case the incubator org is part of the scan.

Remove unused code

---

prow/images/buildpack-golang-kubebuilder2/Dockerfile

- add goimports to kubebuilder buildpack image

Extend kubebuilder buildpack image: add goimports

---

prow/images/buildpack-golang-toolbox/Dockerfile

Upgrade buildpack-golang-toolbox to go 1.13
- Upgrade buildpack-golang-toolbox to go 1.13

Upgrade buildpack-golang-toolbox to go 1.13

---

development/tools/jobs/kyma/vulnerability_scanner_test.go
prow/jobs/kyma/kyma-vulnerability-scanner.yaml

Reschedule vulnerabilities scanner to work every 1st and 14th day of month instead of every day.
* Reschedule kyma-vulnerabilities-scan job

cron reschedule

---

prow/images/buildpack-golang-kubebuilder2/Dockerfile

Compass Provisioner in the new version needs buildpack image with Go 1.13 and Kubebuilder. The newest `golang-toolbox` image already has Go 1.13
- Use newer toolbox with Go 1.13 in Kubebuilder image

Use newer toolbox with Go 1.13 in Kubebuilder image

---

prow/scripts/cluster-integration/kyma-gke-upgrade.sh

When `kubectl` logs command is called with `-l` flag, sometimes for long content, logs are truncated:
```
kubectl logs -l <labelKey>=<labelValue> -c <containerName>
```
I couldn't find any related issue in `kubectl` but you can easily check it with some pods where logs are long (e.g. service-catalog controller manager on Kyma)
In the proposed PR new way of display logs are implemented.
[6676](https://github.com/kyma-project/kyma/issues/6676)

Fix logs display for prepare data upgrade test pod

---

prow/jobs/kyma/kyma-integration-gardener-azure.yaml
prow/scripts/cluster-integration/kyma-gardener-integration.sh

- Recent jobs on for [nightly gardener job](https://status.build.kyma-project.io/job-history/kyma-prow-logs/logs/kyma-gardener-azure-integration) are failing because of kyma installation timeout. It works locally for me, but just takes ages. Let's increase it and check if we have a general problem with gardener or if everything is just slow
maybe related to these issues:
https://github.com/kyma-project/kyma/issues/6950
https://github.com/kyma-project/kyma/issues/6876

Increase kyma timeout for gardener to 60m

---

prow/scripts/cluster-integration/kyma-gke-backup-test.sh

- introduce order of restoring resources (taken from backup chart) in order to satisfy our need in Rafter to restore clusterassetgroups and assetgroups custom resources as last ones
See also https://github.com/kyma-project/kyma/issues/6539

Correct order in which resources are restored in backup test

---

prow/jobs/kyma/kyma-integration.yaml
templates/templates/kyma-integration.yaml

Since https://github.com/kyma-project/kyma/issues/7132 is solved we can revert the workaround. 
-  minikube integration test is mandatory again
- ...
- ...
https://github.com/kyma-project/kyma/issues/7132

Make integration job on minikube NOT optional (revert)

---

prow/scripts/cluster-integration/kyma-gke-backup-test.sh

Currently it is almost impossible to test a new velero plugin image on prow during a PR. This PR tries to fix this by loading the image name from the kyma-project/kyma repository
the env file will be loaded from
kyma/installation/scripts/e2e-testing.env (as the script thats called
for backups is e2e-testing.sh)
the current configuration defaults to what was set before

make velero plugins configurable via env file in kyma-repository

---

development/container-vulnerabilities.sh
development/tools/cmd/vulnerabilitycollector/main.go
development/tools/pkg/vulnerabilitycollector/vulnerabilitycollector.go
prow/config.yaml
prow/jobs/kyma/kyma-vulnerability-scanner.yaml
templates/templates/prow-config.yaml

Job was missing service account with enough permissions to read vulnerabilities, as well as the Slack messaging would never have worked with the way how it was setup.
- fix slack messaging
- add service account
#2019

Service Account and Slack fixes for reporting

---

prow/scripts/cluster-integration/kyma-aks-long-lasting.sh

Kyma installation on `kyma-aks-nightly` fails with
```
message: '0/3 nodes are available: 3 Insufficient cpu.'
reason: Unschedulable
status: "False"
```
in `application-registry-66786bffff-hslc2`
Cluster state:
[describe-nodes.txt](https://github.com/kyma-project/test-infra/files/4203679/describe-nodes.txt)
- VM type has changed

Change VM type for AKS to Standard_F8s_v2

---

development/prow-installer/cmd/cluster/main.go
development/prow-installer/cmd/installer/main.go
development/prow-installer/cmd/secrets/main.go
development/prow-installer/cmd/storage/main.go
development/prow-installer/config/prow-installer-config.yaml
development/prow-installer/pkg/cluster/cluster.go
development/prow-installer/pkg/cluster/cluster_test.go
development/prow-installer/pkg/cluster/mock_api.go
development/prow-installer/pkg/cluster/wrapped.go
development/prow-installer/pkg/config/config.go
development/prow-installer/pkg/storage/storage.go
development/prow-installer/pkg/storage/storage_test.go
development/prow-installer/pkg/storage/wrapped.go

Cleaned up unused variables in prow installer configuration files.
- removed ZoneID usage from cluster client
- removed LocationID usage from storage client

Removed unused variables from config file in prow installer

---

prow/config.yaml
prow/jobs/kyma/kyma-vulnerability-scanner.yaml
templates/templates/prow-config.yaml

Created a new service account for gcp-vulnerability scan on kyma-project to be used in kyma-prow.
- moving away from gke-integration account for scanner job to separate scanning account
#2019

use newly created service account

---

development/prow-installer/cmd/installer/main.go
development/prow-installer/cmd/storage/main.go
development/prow-installer/config/prow-installer-config.yaml
development/prow-installer/pkg/config/config.go
development/prow-installer/pkg/storage/automock/api.go
development/prow-installer/pkg/storage/storage.go
development/prow-installer/pkg/storage/storage_test.go
development/prow-installer/pkg/storage/wrapped.go

Buckets were creating in the us region by default. This PR adds ability to create storage in defined region.
- added ability to optionally define bucket region in config

ability to optionally define bucket region in config

---

prow/workload-cluster/required-secrets.yaml

workload cluster has no reference of vulnerability service account
- add sa from #2044 to workload-cluster

add secret to workload cluster

---

prow/config.yaml
templates/templates/prow-config.yaml

If not configured, tide will query all of GitHub with this query to check for open PRs: `"query":"is:pr state:open sort:updated-asc "`. This minimal config should limit the query to `kyma-project` and `kyma-incubator` organisations and avoid filling tide logs with errors.
- limit tide query to our own organisations

Add minimal tide config

---

prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
prow/scripts/cluster-integration/kyma-gke-release-candidate.sh

- list of images is now saved in csv file for rc, weekly and nightly clusters

Gather list of images from long running clusters

---

prow/images/buildpack-java-node/Dockerfile
prow/images/buildpack-java-node/Makefile
prow/images/buildpack-java-node/README.md
prow/jobs/test-infra/buildpack.yaml

This will enable us to rebuild the wssagent image with this image as base-image.
- create a new image for nodejs and java so whitesource can use npm
#2061

add new buildpack to use as baseimage for whitesource

---

development/tools/jobs/kyma/kyma_compass_integration_test.go
prow/jobs/kyma/kyma-compass-integration.yaml

Currently we're facing problems with stability of Compass-related tests. That's why we decided to make the pipeline optional (temporarily, of course).
- Make pre-master-gke-compass-integration job optional

Make pre-master-gke-compass-integration job optional

---

prow/scripts/cluster-integration/kyma-integration-gardener-azure.sh
prow/scripts/cluster-integration/kyma-integration-gardener-gcp.sh

- Reduce the cluster name length so that the full domain fits in 64 chars.
Otherwise API server certificate creation fails with the following error:
```
the Common Name is limited to 64 characters (X.509 ASN.1 specification), but first given domain <my-long-gardener-domain> has 67 characters
```
https://github.com/kyma-project/kyma/issues/7068

Reduce gardener cluster name length

---

prow/scripts/cluster-integration/kyma-integration-gardener-azure.sh
prow/scripts/cluster-integration/kyma-integration-gardener-gcp.sh

- Show test summary also in case the kyma test command exits with error.
Currently, when tests timeout, no logs are shown.
https://github.com/kyma-project/kyma/issues/7068

Show test summary also if test cmd has error

---

prow/images/alpine-kubectl/Dockerfile

We need to provide a common image with kubectl and some helper commands for all kyma components.
Unfortunately compas entrypoints require jq: 
https://github.com/kyma-project/kyma/blob/master/resources/compass/templates/agent-configuration-job.yaml
That makes [this](https://github.com/kyma-project/kyma/pull/7511/files) PR hard to merge :/
- added jq to the image
- ...
- ...

Add jq to alpine-kubectl image

---

development/update-jobs.sh
prow/cluster/resources/monitoring/templates/prow_prometheusrules.yaml
prow/config.yaml
templates/templates/prow-config.yaml

- Added missing plank config option to enable plank push metrics to pushgateway.
- Defined alert rule for number of running prowjobs.
Resolves #1563

Fix prowjobs count grafana chart 1563

---

prow/scripts/cluster-integration/kyma-integration-gardener-azure.sh
prow/scripts/cluster-integration/kyma-integration-gardener-gcp.sh

- Gardener jobs were green when failing due to wrong exit code intercept.

Intercept exit status correctly on cleanup

---

prow/scripts/license-puller.sh

We've been struggling with extremely long job logs in Console for ages. Around 1000 of the 3000 lines were `Copying license xxx to yyy...` which gives absolutely no benefit.
This PR removes these echos by default but also introduces the `--verbose` flag which brings them back, just in case anyone finds them useful.
Here are the logs from my `make` command that uses the script following way:
```bash
bash $(LICENSE_PULLER_PATH) --dirs-to-pulling="../,../common,../components/react,../components/shared"
```
executed with a command:
`LICENSE_PULLER_PATH=/Users/parostatkiem/test-infra/prow/scripts/license-puller.sh make ci-pr`
- [without `--verbose` flag ](https://github.com/kyma-project/test-infra/files/4343406/non-verbose.log)
- [with `--verbose` …

Display "Copying license..." message only if --verbose flag is set

---

docs/prow/prow-installation-on-forks.md

- Fix a broken link to a guide on how to set up a Prow webhook in GitHub.
[Build log](https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/test-infra-governance-nightly/1240443004662059009)

Fix a broken Prow webhook link

---

prow/scripts/cluster-integration/kyma-aks-long-lasting.sh

AKS nighlty job is failing on kyma installation with timeouts in connections to k8s master. Increasing master nodes capacity and enabling ha.
- Enabled deploying ask master nodes in three zones.

Enabled ha for aks master nodes.

---

prow/images/kyma-integration/Dockerfile

Added copying prebuilt tools from prow-tools image as described in #2189. The tools will be needed by integration jobs so it's mandatory that the integration image includes all precompiled tools.
- ...
- ...
- ...

Copy tools from prow-tools image to kyma-integration image

---

prow/images/kyma-integration/Dockerfile
prow/images/kyma-integration/Makefile

Define build argument and tagging for building images for different versions of kubernetes.
- add ARG parameter K8S_VERSION in Dockerfile with default value 1.16 if no --build-arg is defined.

Define build argument for kyma integration image

---

prow/jobs/test-infra/buildpack.yaml

Edited prow-tools build job regexp to run only when go files from cmd/pkg are modified.
https://regex101.com/r/2iLu9X/1
- ...
- ...
- ...
Closes #2232

Fix prow-tools build job regexp

---

development/github-release.sh
development/tools/jobs/kyma/kyma_github-release_test.go
prow/jobs/kyma/kyma-github-release.yaml
templates/templates/kyma-github-release.yaml

Edited `GitHub-release` job to use pre-built binary without the need to build it on every run.
- edited GitHub-release.sh to run a binary instead of build source.

GitHub-release job optimisation 

---

prow/scripts/cluster-integration/helpers/create-azure-event-hubs-secret.sh

- Make kafka.brokers.port value a string
- Problem: stringData is only accepting strings as values, see https://kubernetes.io/docs/concepts/configuration/secret/#creating-a-secret-manually
Some context on the problem:
If you run `createK8SSecretFileBroken` and `createK8SSecretFileFixed` and check the created overrides, you will see the following diff:
broken:
```
stringData:
kafka.brokers.port: 9093
```
When you try to create the file with `kubectl apply`, you will get the error message mentioned in the ticket.
fixed:
```
kafka.brokers.port: "9093"
```
```bash
primaryConnectionString="Endpoint=sb://azure-gardener.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=somekey=" …
```

Use string values for stringData in knative-eventing-kafka overrides

---

prow/jobs/test-infra/validation.yaml

Disabling because of issues with building dependency and vendoring for checkconfig packae from k8s test-infra. Never version which causes issues with dep ensure is required by new prow config. For the purpose of upgrade prow config will be checked manually. Check will be enabled after solving issues. Work to solve dependency issue will be done right after upgrade.

Make prow-config check optional

---

development/prow-addons-ctrl-manager/Makefile
development/tools/jobs/testinfra/prow_addons_ctrl_manager_test.go
prow/jobs/test-infra/prow-addons-ctrl-manager.yaml

Upgraded prow-addons-ctrl-manager build image.
Disabled dep checks from Makefile.

Moved prow-addons-ctrl to golang 1.13 image.

---

development/tools/jobs/kyma/kyma_github-release_test.go
prow/jobs/kyma/kyma-github-release.yaml
templates/templates/kyma-github-release.yaml

The image prow-tools didn't have curl and golang which result in failed job. Changed image to `eu.gcr.io/kyma-project/test-infra/kyma-integration:v20200406-36a2a4f6-k8s1.15` because it has golang, tools binaries, dep and curl.
- ...
- ...
- ...

change image of github-release job to kyma-integration:k1.15

---

milv.config.yaml

The `https://status.build.kyma-project.io/hook` hook link requires an HTTP method different than GET. As a result, it caused the pipeline job to fail. 
- Whitelist the `https://status.build.kyma-project.io/hook` hook link.

Whitelist the hook link

---

prow/cluster/components/15-deck_deployment.yaml

sa-gcs-credentials mount was added as part of prow upgrade as it was needed on upgrade instance to correctly dispaly logs stored in a bucket. In prod instance this appears not needed as everything seems working fine, whereas the secret needed for mount doesn't exist. moreover, serviceaccount which credentials were suppose to store within a secrete doesn't have any permissions assigned in GCP IAM.

removed sa-gcs-credentials arg and mount from deck deployment.

---

prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh
prow/scripts/cluster-integration/kyma-gke-upgrade-xip.sh
prow/scripts/cluster-integration/kyma-gke-upgrade.sh

- Added waiting for tiller upgrade rollout status
**Context:**
In the below issue, there was a need to upgrade tiller,however, I have discovered that upgrade jobs are not waiting for tiller upgrade to finish.
Now there can be a situation, that happened on my PR, that there was old tiller pod running, installer pod connected to it then k8s terminated old pod once new was running and `connection closed` error occurred (expected in such case). 
To make sure that we will not go further (apply new deployment)  until rollout completes (at least new pod will be in status RUNNING) I have additional command.
https://github.com/kyma-project/kyma/issues/7725

Wait for tiller rollout status

---

prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
prow/scripts/cluster-integration/kyma-integration-gardener-aws.sh
prow/scripts/cluster-integration/kyma-integration-gardener-azure.sh
prow/scripts/cluster-integration/kyma-integration-gardener-gcp.sh

- Use latest published master on periodic clusters to avoid pull backoff errors when artifacts are not there for the most recent commit.

Use latest published master on periodic clusters

---

prow/images/buildpack-golang-toolbox/Dockerfile
prow/images/buildpack-golang-toolbox/license-puller.sh

the license puller was not able to download licenses for import paths using go's vanity import paths
using pup and a bit of other shell commands this can be implemented
>***NOTE:*** `go help importpath` to the rescue
1. append ?go-get=1 to the importpath when curling it
2. extract the meta tag with name=go-import
3. extract the repository url
kyma-project/kyma#7992

go vanity import path support

---

prow/images/buildpack-golang/Dockerfile
prow/images/buildpack-golang/Makefile
prow/images/buildpack-golang/README.md

Update buildpack-golang to go 1.14

---

prow/images/buildpack-golang-toolbox/Dockerfile

- Upgrade buildpack-golang-toolbox to go 1.14

Upgrade buildpack-golang-toolbox to go 1.14

---

prow/scripts/cluster-integration/kyma-integration-gardener-azure.sh

According to the documentation on azure we should use "Standard_D8_v3"
https://kyma-project.io/docs/root/kyma#installation-install-kyma-on-a-cluster
- updated default vm size

Change VM type on integration-gardener-azure

---

prow/images/buildpack-golang-kubebuilder2/Dockerfile
prow/images/buildpack-golang-kubebuilder2/README.md

Compass Provisioner in the new version needs buildpack image with Go 1.14 and Kubebuilder. The newest `golang-toolbox` image already has Go 1.14
- Use newer toolbox with Go 1.14 in Kubebuilder image

Use newer toolbox with Go 1.14 in Kubebuilder image

---

prow/plugins.yaml

- Enabled plugin
- Defined default column for the Wookiee project
As a team, we would like to work with GitHub projects. For everyone that is outside of our team, the project will be read-only. The only way for people that have read-only access to assign an Issue/PR to it will be by the command `/project Wookiee`.

Enable project plugin

---

prow/jobs/incubator/compass/components/metris/metris-generic.yaml
prow/jobs/kyma/components/api-gateway-migrator/api-gateway-migrator-generic.yaml
prow/jobs/kyma/components/nats-init/nats-init-generic.yaml
prow/jobs/kyma/tests/function-controller/function-controller-tests-generic.yaml
prow/jobs/kyma/tools/event-subscriber/event-subscriber-generic.yaml
templates/templates/component.yaml
templates/templates/generic-component.yaml
templates/templates/knative-kafka-component.yaml

It seems that just adding the empty channel doesnt work so we'll explicitly set the report to false.
- set `report: false` on jobs that set the empty channel
#2311

report: false to jobs that should not report to slack

---

prow/images/kyma-integration/Dockerfile

As most of the images use Go in version 1.14.2 it's good to bump the version of Go in kyma-integration image from 1.13.4 to 1.14.2.
- bumped Go version to 1.14.2
- added /prow-tools to PATH

bump golang to version 1.14.2 in kyma-integration image

---

prow/cluster/resources/monitoring/dashboards/grafana-prow.json
prow/cluster/resources/monitoring/templates/prow_prometheusrules.yaml

Enabled github token usage monitoring and alerting.
Removed tide and prow-addons-ctrl-manager from endpoint and services graphs.
Aligned graphs formating.
See #1162

GitHub quota monitoring #1162

---

prow/cluster/components/33-crier_deployment.yaml

This change should enable crier to also report on jobs that never started (as long as they have a job id).
As of https://kubernetes.slack.com/archives/CDECRSC5U/p1587663764198900
>  if the pod never starts -- say there's a typo in the image name -- then make sure you enabled the gcsreporter in crier, which will tell you on that page why the pod didn't start
https://github.com/kubernetes/test-infra/blob/1424cf49538c10a8061f4a78a0e202e70192eeff/config/prow/cluster/crier_deployment.yaml#L45
- change crier to also enable a gcs reporter

Add gcs reporter to crier for jobs that never started

---

prow/jobs/cli/cli.yaml

- setting the `preset-dind-enabled` label to be `true` in order to allow for running docker inside a docker during the CLI release
#465

enable docker in docker for cli release

---

prow/jobs/kyma/kyma-metadata-governance.yaml

Job is failing because it was not migrated to go modules. This PR is only a quick fix.
Logs:
```
Initializing
Docker in Docker enabled, initializing...
================================================================================
Starting Docker: docker.
================================================================================
/root/.docker/config.json configured to use this credential helper for GCR registries
Done setting up docker in docker.
Vendoring 'tools'
/home/prow/go/src/github.com/kyma-project/test-infra/development/tools /home/prow/go/src/github.com/kyma-project/kyma
could not find project Gopkg.toml, use dep init to initiate a manifest
```

Quick fix for kyma-metadata-schema-governance job

---

development/tools/jobs/kyma/metadata_governance_test.go
development/update-config.sh
development/update-jobs.sh
development/update-plugins.sh
prow/jobs/kyma/kyma-metadata-governance.yaml
prow/scripts/cluster-integration/helpers/aks-library.sh
prow/scripts/metadata-governance.sh

Fix in #2412 for `kyma-metadata-schema-governance` job intended to use previous revision of a repository before using modules. This rewrites scripts to fetch dependencies using go modules with latest revision of test-infra repo.
Also addresses multiple usages of `dep` in other scripts in a repository.
- revert #2412 
- remove fetching dependencies using dep
- use `enablegithubauth` binary in aks-library.sh

Move dependencies resolving to go modules

---

prow/cluster/resources/monitoring/dashboards/grafana-prow.json

Removed timeFrom override from Grafana dashboard panels in order to restore ability to access metrics from different time ranges
- removed timeFrom override from dashboard's panels
- added GitHub token usage time series for monitoring usage over time

GitHub token monitoring dashboard changes

---

prow/jobs/test-infra/validation.yaml

Job `pre-test-infra-validate-configs` was set to optional because of an issue after switching to go modules. This PR restores the job to be required again.
- ...
- ...
- ...

Make pre-test-infra-validate-configs required again

---

prow/jobs/kyma/kyma-integration-gardener.yaml
templates/templates/kyma-integration-gardener.yaml

- periodic [kyma-integration-gardener-azure](https://github.com/kyma-project/test-infra/blob/56ae24e5b3b64058fdf927b11e916dbb4d699b2a/prow/jobs/kyma/kyma-integration-gardener.yaml#L179) job uses 4h timeout, because cluster provisioning has timeout of 90m and kyma installation adds another 90m. That hopefully leaves enough time for cleanup. Default timeout value seems to be [2h](https://github.com/kyma-project/test-infra/blob/master/prow/config.yaml#L487) which is too low.
Hopefully improves/fixes #8700

Use consistent timeout for gardener azure job

---

prow/config.yaml
prow/jobs/incubator/compass/tests/provisioner-tests/provisioner-whitesource.yaml
prow/jobs/scans/whitesource-periodics.yaml
prow/scripts/cluster-integration/helpers/start-wssagent.sh
templates/templates/prow-config.yaml
templates/templates/whitesource-periodics.yaml

Created preset to mount wssagent api and user keys.
Enabled whitesource scans prowjobs to use new preset.
Enabled start-wssagent.sh to use mounted keys.
See #2399

Enable start-wssagent.sh to use mounted keys.

---

prow/scripts/cluster-integration/helpers/start-wssagent.sh

Whitesource scans failing due to no access to user and api keys because of typo in file name.

Fix typo in file name.

---

prow/jobs/kyma/kyma-integration.yaml
templates/templates/kyma-integration.yaml

- Skip the new E2E upgrade job by default.
https://github.com/kyma-project/kyma/issues/7512.

Skip the new E2E upgrade job by default

---

prow/scripts/library.sh

Some scripts doesn't need authenticate docker in gcr whereas still use DinD.
- Added support for no docker authentication in gcr.
See #2399

Added case with no docker authentication.

---

prow/jobs/test-infra/validation.yaml

The jobs were optional because there were code formatting errors that made the job fail. Right now these errors are fixed so the jobs can be required.
This PR sets the `pre-master-test-infra-validate-prow-jobs` and `pre-master-test-infra-validate-prow-tools` required to merge.
- remove `optional: true` setting from `pre-master-test-infra-validate-prow-jobs` and `pre-master-test-infra-validate-prow-tools` jobs.
#2407

Make validate-prow-jobs and prow-tools required

---

prow/cluster/components/32-prowjob-scheduler_rbac.yaml

Added definition of serviceaccount with required rbac to allow scheduling prowjobs from outside of the cluster. Serviceaccount has permissions to work with prowjobs only.
See #2489

Added serviceaccount for scheduling prowjobs.

---

prow/scripts/cluster-integration/kyma-integration-gardener-azure.sh

this had side effects on other simultaneously running tests
- do not remove the resource group as this kills all eventhubs (even the ones that are not used by the current test)

disable cleanup of azure eventhub resource group

---

prow/jobs/control-plane/control-plane-gke-integration.yaml
prow/jobs/control-plane/control-plane-gke-provisioner-integration.yaml
prow/jobs/control-plane/control-plane-integration.yaml
prow/jobs/incubator/compass/compass-gke-integration.yaml
prow/jobs/incubator/compass/compass-integration.yaml
prow/jobs/kyma/kyma-github-release.yaml
prow/jobs/kyma/kyma-gke-compass-integration.yaml
prow/jobs/kyma/kyma-integration-gardener.yaml
prow/jobs/kyma/kyma-integration.yaml
prow/jobs/kyma/kyma-release-candidate.yaml
prow/jobs/test-infra/testgrid-automation.yaml
prow/testgrid-default.yaml
templates/templates/compass-gke-integration.yaml
templates/templates/compass-integration.yaml
templates/templates/kyma-github-release.yaml
templates/templates/kyma-gke-compass-integration.yaml
templates/templates/kyma-integration-gardener.yaml
templates/templates/kyma-integration.yaml
templates/templates/kyma-release-candidate.yaml
templates/templates/testgrid-default.yaml

This PR addresses failing tests in https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/pr-logs/pull/kyma-project_test-infra/2563/pre-test-infra-validate-testgrid-config/1281656258767622144.
- add prefixes to the dashboard names
- move `compass` to the `Kyma` dashboard

TestGrid dashboard renames

---

prow/jobs/test-infra/pjtester.yaml

Fixed vpathguard required test. It's not allowed to clone same repo twice with clonerefs.

Removed extra_refs.

---

prow/scripts/cluster-integration/kyma-gke-compass-integration.sh

- Enable Agent preconfiguration for Kyma Compass integration
Explanation: Default value for the Compass Agent preconfiguration is changed  to `false`.

Enable Agent preconfiguration for Kyma Compass integration

---

prow/scripts/cluster-integration/kyma-gke-compass-integration.sh

The Compass chart is installed from the `master` branch. Recent changes to the Compass chart caused job to need an additional override. For the release job to work properly we need to cherry-pick the change to release branch.
Change in Compass: https://github.com/kyma-incubator/compass/pull/1505/files
Adjustment in Test Infra: https://github.com/kyma-project/test-infra/pull/2645
- Cherry-pick fix to Compass Integration job

Enable Agent preconfiguration for Kyma Compass integration (#2645)

---

prow/scripts/cluster-integration/kyma-upgrade-gardener-azure.sh
vpath/pjtester.yaml

- Problem: This [PR](https://github.com/kyma-project/kyma/pull/9165) did not make it into Kyma 1.14, hence we need to disable stackdriver installation overrides  in upgrade test until Kyma 1.15 is out
- There is a reminder to re-enable once Kyma 1.15 is out: https://github.com/kyma-project/test-infra/issues/2674
- Job can't be fully tested with pjtester, because https://github.com/kyma-project/kyma/issues/9210 is failing the upgrade
https://github.com/kyma-project/kyma/issues/8783

Fix logging overrides for kyma-upgrade-gardener-azure job

---

development/tools/cmd/pjtester/main.go
development/tools/pkg/pjtester/pjtester.go
development/tools/pkg/pjtester/pjtester_test.go

- Fixed parsing flags.
- Added author to tested prowjob name.

Pjtester fix flags

---

development/tools/jobs/kyma/kyma_upgrade_gardener_test.go
prow/jobs/kyma/kyma-upgrade-gardener.yaml
prow/scripts/cluster-integration/kyma-upgrade-gardener-azure.sh
vpath/pjtester.yaml

- The reason it failed was the knative-kafka chart was not installed whereas the default webhook config was using KafkaChannels. Hence the channels were never ready.
See https://github.com/kyma-project/kyma/issues/9210

Fix prepare data stage for eventmesh upgrade in kyma-upgrade-gardener-azure job

---

prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
prow/scripts/cluster-integration/kyma-gke-release-candidate.sh

The list will be a JSON array with objects defined as below:
```json
[
{
"owner_ref": "tiller-deploy-548dd6998b",
"image": "eu.gcr.io/kyma-project/alpine-net:2fbe4fd3",
"image_id": "docker-pullable://eu.gcr.io/kyma-project/alpine-net@sha256:01f3cd28bb37d8d88686745f532cb4d3f827bf028e19775ecd76799e0806f67c"
},
...
]
```
The `unique` command should filter all the direct duplicates of objects, e.g. those which "owner_ref", "image" and "image_id" are exactly the same.
- add additional creation of json list with images

add generation of image list in json

---

prow/images/whitesource-scanner/Dockerfile

As stated in #2728 the whitesource unified agent was having an issue resolving the dependency graph due to missing go and dep binaries. This PR adds the missing binaries to the image and updates whitesource unified agent to the latest version available.
- add go 1.14.2
- add dep 0.5.4
- update Unified Agent to v20.8.2
#2728

Add go and dep to the whitesource scanner image.

---

prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
prow/scripts/cluster-integration/kyma-gke-long-lasting.sh

Right now the clusters fail to provision because of the `kcproxy` pod cannot access address "https://dex.nightly.a.build.kyma-project.io/.well-known/openid-configuration" (or similar). Due to changes in [this file](https://github.com/kyma-project/kyma/commit/19e240cd79041e8f82b5f3c90e39bc64406f7b08#diff-36ea24c083a451c0d26fd76a526e7566) helm-like overrides do not work anymore so the override value `gateways.istio-ingressgateway.loadBalancerIP: "${GATEWAY_IP_ADDRESS}"` is not used. That leads to GKE/AKS loadbalancer to assign random IP address instead of the pre-generated one. This leads to host not reachable when using DNS entry. New format requires yaml file to be passed as a configuration. Additionally currently kyma installer, which we are using, does not have …

Workaround for assigning LoadBalancer IP in nightly and weekly clusters.

---

development/tools/jobs/control-plane/development_artifacts_test.go
development/tools/jobs/tester/tester.go
prow/jobs/cli/cli.yaml
prow/jobs/control-plane/kcp-development-artifacts.yaml
prow/scripts/build-kcp-development-artifacts.sh

New skr CLI tool is being developed in control-plane repo. 
Dependent PR for Makefile:
https://github.com/kyma-project/control-plane/pull/227
- Add building and uploading skr CLI binaries to kyma-development-artifacts bucket as part of kcp-development-artifacts job
https://github.com/kyma-project/control-plane/issues/212

Build and publish skr CLI to development artifacts

---

prow/jobs/kyma/kyma-integration.yaml
prow/scripts/cluster-integration/helpers/provision-gke-cluster.sh
templates/config.yaml
templates/templates/kyma-integration.yaml
vpath/pjtester.yaml

It's needed to test Kyma GKE jobs on different cluster versions that are available on rapid channel. This PR adds the functionality of generating prowjobs that use specific version of GKE K8s from different release channels provided.
If you want to add a new release channel just add a new entry under `gkeVersions` struct in templates/config.yaml:
```yaml
gkeVersions:
- version: 1.18.6-gke.4504
channel: rapid
jobs: ["presubmit"]
- channel: stable
jobs: ["presubmit", "postsubmit"]
```
both `channel` and `jobs` are required.
If you want to add job for gke version generation please refer to the file in this PR.
- add generation of prowjobs based on the release version
- add label generation for each of the release version
- make jobs …

Add pre-master-kyma-gke* jobs which use new GKE K8s version.

---

prow/config.yaml
prow/jobs/cli/cli-integration.yaml
prow/jobs/control-plane/control-plane-gke-integration.yaml
prow/jobs/incubator/compass/compass-gke-integration.yaml
prow/jobs/kyma/kyma-gke-compass-integration.yaml
prow/jobs/kyma/kyma-gke-external-registry.yaml
prow/jobs/kyma/kyma-integration.yaml
prow/scripts/cluster-integration/helpers/provision-gke-cluster.sh
templates/templates/compass-gke-integration.yaml
templates/templates/kyma-gke-compass-integration.yaml
templates/templates/kyma-gke-external-registry.yaml
templates/templates/kyma-integration.yaml
templates/templates/prow-config.yaml

GKE 1.16 is the default value on regular channel. I think it's safe to use default version from channel.
```yaml
- channel: REGULAR
defaultVersion: 1.16.13-gke.401
validVersions:
- 1.17.9-gke.1504
- 1.16.13-gke.401
```
- ...
- ...
- ...

Remove --cluster-version param from provision gke scripts

---

prow/scripts/cluster-integration/kyma-upgrade-gardener-azure.sh

- Problem: Upgrade job has to install installation overrides/configuration from the kyma version which gets installed
- However, the version from master is always taken. This worked for some while until a change in the config file was introduced with the [Istio 1.5 introduction](https://github.com/kyma-project/kyma/pulls?page=2&q=is%3Apr+istio+is%3Aclosed)
A proof that the problem is fixed can be seen in [this PR](https://github.com/kyma-project/test-infra/pull/2722/files). It has the same code change. A pipeline was triggered with the pjtester tool: <https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_test-infra/2722/nachtmaar_test_of_prowjob_pre-master-kyma-upgrade-gardener-azure/1311738848375476224/build-log.txt> …

Fix istio installation error

---

prow/scripts/cluster-integration/kyma-upgrade-gardener-azure.sh

- Set correct domain in core-test-external-solution test for `kyma-upgrade-gardener-azure` test
See this [PR with pjtester](https://github.com/kyma-project/test-infra/pull/2722/files) for a proof that the provided solution works
Fixes https://github.com/kyma-project/kyma/issues/9604

Set domain in helm install command for `kyma-upgrade-gardener-azure` test

---

development/tools/jobs/cli/cli_integration_test.go
prow/jobs/cli/cli-integration.yaml

After adding a new preset the job started to fail due to outdated `gcloud` CLI in `buildpack-golang-kubebuilder2:v20200124-69faeef6` image. This changes the job's image to the latest zkyma-integration`. Test run https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-cli-integration-gke/1313065980812857344
- ...
- ...
- ...

Edit image for kyma-cli-integration-gke to use kyma-integration image.

---

prow/config.yaml
prow/jobs/cli/cli-integration.yaml
prow/jobs/control-plane/control-plane-gke-integration.yaml
prow/jobs/incubator/compass/compass-gke-integration.yaml
prow/jobs/kyma/kyma-gke-compass-integration.yaml
prow/jobs/kyma/kyma-gke-external-registry.yaml
prow/jobs/kyma/kyma-integration.yaml
prow/scripts/cluster-integration/helpers/provision-gke-cluster.sh
templates/config.yaml
templates/templates/compass-gke-integration.yaml
templates/templates/kyma-gke-compass-integration.yaml
templates/templates/kyma-gke-external-registry.yaml
templates/templates/kyma-integration.yaml
templates/templates/prow-config.yaml

The multiple gke jobs caused a lot of errors on the prow instances. The integration is not yet stable to use it in production.
* GKE Integration jobs fail because there are several different pipelines that build installer image under the same image tag. This causes the image to be tagged improperly. We should consider using Kyma CLI for the install job.
* we cannot use default version of the GKE release channel because our images have CLUSTER_RELEASE hardly defined in the image along with the kubectl command. Additionally the scripts are not flexible enough to use them with different versions of GKE.
- revert https://github.com/kyma-project/test-infra/commit/319ff3f0f5a286c061c8345d0d88cada5cab26dd
- revert …

Revert multiple gke tests

---

prow/scripts/cluster-integration/control-plane-gke-integration.sh

- use old format of istio overrides as kyma 1.16 is not yet released

Revert old istio overrides format

---

prow/images/buildpack-golang-toolbox/Dockerfile

Add counterfeiter to buildpack-golang-toolbox image as it is needed for some of the compass components.

Add counterfeiter to buildpack-golang-toolbox

---

prow/jobs/cli/cli-compatibility.yaml

- Disable reporting to `ci-force` for compatibility jobs since they have false negatives.
https://github.com/kyma-project/cli/issues/584

Disable reports to ci-force for compatibility jobs

---

prow/scripts/cluster-integration/helpers/start-wssagent.sh
vpath/pjtester.yaml

currently whitesource tries to scan godep based subfolders in the gomod scan and vice versa, in the log this results in the following message:
```
[INFO] [2020-10-07 04:02:31,333 +0000] - Trying to resolve GO dependencies
[INFO] [2020-10-07 04:02:31,559 +0000] - topFolder = /home/prow/go/src/github.com/kyma-project/kyma/components/event-service
[INFO] [2020-10-07 04:02:31,563 +0000] - Resolve dependencies - START - modules
[WARN] [2020-10-07 04:05:03,574 +0000] - CommandLineProcess - executeProcessCommand - error in execute command 'go build', Exit Status 1
[WARN] [2020-10-07 04:05:33,950 +0000] - CommandLineProcess - executeProcessCommand - error in execute command 'go mod vendor', Exit Status 1
[WARN] [2020-10-07 04:05:33,950 +0000] …
```

exclude go.mod based folders in godep scan and vice versa

---

development/tools/cmd/prtagbuilder/main.go

Removed printing image commit env variable by prtagbuilder. Tool was initial intent to run in separate image.

Added tagging with post PR tag.

---

prow/images/prow-tools/Makefile

Disabled pr tag to let prow-tools image rebuild with fixed prtagbulder tool

Disabled pr tag for prow-tools image.

---

prow/cluster/components/11-plank_deployment.yaml

Removed cluster secret from plank deployment. Secret is not needed because workload-cluster was deleted.

Removed cluster secret from plank.

---

prow/scripts/cluster-integration/kyma-gke-integration.sh
prow/scripts/kyma-testing.sh
prow/scripts/lib/kyma-cli.sh

The kyma-gke-* jobs were using the old method of installing Kyma cluster in their scripts - they were building Kyma-installer image and pushing it to a registry. If there was multiple jobs doing the same thing on a commit it generated the problems where the image was improperly tagged, resulting the job to fail. 
This PR targets the rewrite of installation process of Kyma using Kyma-cli and its flag `-s` which allows to define the source of Kyma - PR, master commit or release version built by separate prowjob.
It additionally targets the deprecation of `library.sh` and sources needed scripts from `prow/scripts/lib/` directory.
- rewrite kyma-gke-integration.sh to utilise Kyma-cli for installing Kyma on GKE cluster
- remove usage of …

Rewrite kyma-gke-integration.sh to use kyma-cli

---

prow/cluster/resources/probot-stale/values.yaml

`cert-manager` couldn't refresh SSL certificate for our stalebot deployment. We have been cutting all traffic from HTTP in the ingress configuration so HTTP URL for stalebot was returning 404, instead of 200 thus resulting in broken HTTP challenge.
- remove `allow-http: false` annotation from ingress deployment in stalebot chart.

Remove `allow-http` annotation from stalebot chart

---

prow/scripts/build-kcp-development-artifacts.sh

Authenticate with GCS bucket SA before generating KCP installer artifacts since the script might download from gs://kyma-prow-artifacts

Fix fetching Kyma release artifacts for KCP

---

prow/scripts/cluster-integration/kyma-gke-central.sh

Next part of GKE integration scripts rewrite. This one addresses rewriting the kyma-gke-cental-connector jobs. As kyma-gke-integration jobs it uses Kyma CLI and externally prebuilt artifacts for given PR/master/release to install and test Kyma.
- Rewrite kyma-gke-central.sh to use pre-built artifacts and Kyma CLI
- remove usage of deprecated `library.sh`
- use internal log.sh library for logging
**Successful runs**
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/9400/pre-master-kyma-gke-central-connector/1318880113407823872
#2822 #2761

Rewrite kyma-gke-central.sh to use pre-built artifacts and Kyma CLI.

---

prow/scripts/provision-vm-and-start-kyma.sh

This PR addresses #2882 by fetching JUnit report in trap function. We make sure the fetching happens everytime the script fails or not. Additionally remove usage of deprecated `library.sh` from the script in favour of scripts from `lib/` directory.
- move fetching JUnit report to cleanup function
- remove usage of deprecated `library.sh`
Fixes #2882

Rewrite provision-vm-and-start-kyma.sh to fix fetching JUnit report

---

development/image-guard/image-guard/values.yaml
prow/scripts/cluster-integration/kyma-gke-long-lasting.sh

Add helm command to `kyma-gke-long-lasting.sh` script to install image-guard in nightly and weekly clusters.
- Add installing image-guard to nightly and weekly cluster
#2599

Add installing image-guard to nightly and weekly cluster

---

prow/branchprotector-config.yaml
templates/templates/branchprotector-config.yaml

We want to require branches to be up to date before merging into master for the Compass repository.
Currently our manual setting gets overridden by Prow constantly so this change tries to fix that by configuring Prow with our desired branch protection.
Reference GitHub API link (Properties of the **required_status_checks** object -> **strict** should be `true` in our case): https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#update-branch-protection 
- configure `branchprotector-config.yaml` template file
- regenerate actual `prow/branchprotector-config.yaml` file

Require branches to be up to date before merging into Compass master

---

prow/scripts/build-kcp-development-artifacts.sh

- Rename control plane CLI to `kcp`
https://github.com/kyma-project/control-plane/pull/270

Rename SKR CLI to KCP CLI

---

prow/scripts/cluster-integration/helpers/create-dns-record.sh

DNS debug produce a lot logs. Redirected output to separate file.

Redirect dns debug data to separate file.

---

development/tools/cmd/prtagbuilder/main.go
development/tools/pkg/prtagbuilder/prtagbuilder.go

Added support for finding PR number for branch HEAD provided as cli flags.
With flag -O prtagbuilder print pr number only.

Add flags to prtagbuilder

---

prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
prow/scripts/cluster-integration/kyma-gke-long-lasting.sh

- Increase the memory as due to envoy bug in istio telemetry v2 prometheus-istio server is scraping old metrics from pods. So increase the memory

Increase the memory limit for prometheus-istio in nightly and weekly cluster

---

development/tools/jobs/control-plane/cli_test.go
prow/jobs/control-plane/kcp-cli.yaml
prow/jobs/control-plane/kcp-development-artifacts.yaml
prow/scripts/build-kcp-cli.sh
prow/scripts/build-kcp-development-artifacts.sh

KCP CLI is moved out from KEB codebase to `tools/cli`

KCP CLI: move out from KEB

---

prow/jobs/kyma/kyma-integration.yaml
prow/scripts/cluster-integration/serverless-integration-k3s.sh
prow/scripts/provision-vm-and-start-serverless-k3s.sh
templates/templates/kyma-integration.yaml
vpath/pjtester.yaml

There needs to be a bit of explanation as to why I'm using my own kaniko image: due to https://github.com/GoogleContainerTools/kaniko/issues/1287 I needed to resort to apply changes from [this comment](https://github.com/GoogleContainerTools/kaniko/issues/1287#issuecomment-637634928), because it wasn't working with either internal docker registry (run using plain `docker run`) or gcr supplied from Prow's infrastructure.
https://github.com/GoogleContainerTools/kaniko/compare/v1.3.0...aerfio:cred_linux_patch
- add k3s job that installs serverless chart and runs special version of serverless tests
https://github.com/kyma-project/kyma/issues/10001

Introduce k3s pipeline for serverless integration jobs

---

development/image-syncer/external-images.yaml

The bump is necessary because the currently used version (11.9) contains vulnerabilities that are fixed in 11.10.
- Uncomment and bump version of postgresql in image-syncer

Uncomment and bump version of postgresql in image-syncer

---

development/tools/jobs/kyma/kyma_gke_compass_integration_test.go
prow/jobs/kyma/kyma-gke-compass-integration.yaml
templates/templates/kyma-gke-compass-integration.yaml

This job is broken, on pre-masters its already optional. It was failing during previous release as well
- pre-relXX-kyma-gke-compass-integration is now optional
- ...
- ...

Make pre-rel kyma-gke-compass-integration optional

---

CODEOWNERS

Since Barbara Sz. (@bszwarc) left us in September and is no longer an active contributor, she should be removed from CODEOWNERS.  
At the same time, Justyna Sz. (@superojla) joined us in September and has been contributing to Kyma documentation, so it's time to add her to CODEOWNERS. 
- Remove @bszwarc from documentation CODEOWNERS
- Add @superojla to documentation CODEOWNERS

Update test-infra documentation CODEOWNERS

---

prow/jobs/kyma/kyma-integration-gardener.yaml
prow/scripts/cluster-integration/kyma-integration-gardener-azure.sh
templates/templates/kyma-integration-gardener.yaml
vpath/pjtester.yaml

This PR adds prow jobs testing kyma hibernation scenario on Gardener based clusters.
Job is periodic, runs 4x per day, uses the same machine type as job for evaluation profile (single node, Standard_D4_v3).
Job in an overview performs following actions : 
1. Provision Kyma cluster
2. Hibernate cluster checking first if it's possible
3. Wake up cluster
4. Run tests from evaluation profile scenario
Note :  hibernation for now is enabled only with evaluation profile.
- Added periodic job testing kyma hibernation scenario on Gradener (Azure)

Add hibernation job

---

development/custom-image/install-deps-debian.sh

The path `/usr/local/bin` needs privileged permissions to write files there. Helm installation was failing because the script didn't have proper permissions to it.
- download helm to temporary repository then copy it with privileged permissions.

Fix bug in installing helm binary in install-deps-debian.sh

---

development/image-syncer/external-images.yaml

- Bump ServiceCatalog image for image syncer to latest master `v0.3.1-3-g87e8bc4-dirty`

Bump ServiceCatalog image for image syncer

---

prow/scripts/build-compass-development-artifacts.sh

Missing import of docker lib makes the checks on this https://github.com/kyma-incubator/compass/pull/1665 to fail

Add docker lib import

---

prow/images/buildpack-java/Dockerfile
prow/images/buildpack-java/README.md
vpath/pjtester.yaml

- Add Maven to Java Buildpack
- Download whole Java JDK (as opposed to just JRE as it was before)

Add Maven to Java Buildpack

---

prow/jobs/incubator/compass/compass-development-artifacts.yaml
prow/scripts/build-compass-development-artifacts.sh

- Modify `compass-development-artifacts` job to run when new tags are created

Build Compass Installer images on tag creation

---

prow/scripts/build-kyma-artifacts.sh

The reworked build-kyma-artifacts.sh script was pushing post submit artifacts to wrong path which Kyma-cli couldn't find. We need to push script to paths `master-{COMMIT_SHA}` instead of `{COMMIT_SHA}`
- ...
- ...
- ...

fix bucket path for postsubmit artifacts

---

docs/prow/prow-architecture.md

- Removed sentence that included link to a deleted file.

Remove sentence with incorrect link

---

prow/scripts/lib/gcloud.sh

`gcloud::encrypt` and `gcloud::decrypt` were failing due to setting readonly variable for arguments. 
- Rename readonly parameters to local in gcloud.sh encrypt/decrypt functions

Rename readonly parameters to local in gcloud.sh encrypt/decrypt functions

---

prow/scripts/cluster-integration/compass-gke-integration.sh
prow/scripts/cluster-integration/control-plane-gke-integration.sh
prow/scripts/cluster-integration/helpers/create-cluster.sh
prow/scripts/cluster-integration/kyma-gke-compass-integration.sh
prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
prow/scripts/lib/gcloud.sh

- Improve `gcloud::provision_gke_cluster` as discussed here: https://github.com/kyma-project/test-infra/pull/3056#discussion_r556864989
- remove `ADDITIONAL_LABELS` sa they were just setting `created-at` label that gets overwritten with UNIX time anyway
#3056, #2974

scripts: additional labels as optional argument for gcloud::provide_gke_cluster

---

prow/scripts/cluster-integration/control-plane-gke-integration.sh

- Add `tracing-overrides` to `control-plane-gke-integration` (install Kyma section) job. Override is necessary to install Kyma 1.16 for KCP.

Adjust GKE integration job to install KCP with Kyma 1.16

---

prow/scripts/cluster-integration/kyma-cli-alpha-uninstall.sh
prow/scripts/cluster-integration/kyma-cli-alpha-upgrade.sh
prow/scripts/lib/cli-alpha.sh

Caused by changes made to the alpha-cli deploy command the existing alpha-cli test jobs were failing. This is fixing these issues.

Fix alpha CLI calls

---

prow/scripts/cluster-integration/helpers/cleanup-gardener.sh

- Increase failed gardener clusters deletion period to 24h. Right now it is only 4 hours, it is not enough for use to debug failed clusters, especially those provisioned during the night.

Increase failed gardener clusters deletion period

---

prow/scripts/provision-vm-and-start-kyma-k3s.sh
vpath/pjtester.yaml

Price comparison (europe-west1):
- n1-standard-4	4	15GB	$0.2092
- n2-standard-4	4	16GB	$0.213668
Performance:
- N1 - https://cloud.google.com/compute/docs/benchmarks-linux#n1_standard_machine_types
n1-standard-4 | Skylake | 4 | 54,678
- N2 https://cloud.google.com/compute/docs/benchmarks-linux#n2_standard_machine_types
n2-standard-4 | Cascade Lake | 4 | 69,020
Performance in prowjob:
Test job: https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/adamwalach_test_of_prowjob_kyma-integration-k3s/1352364217889460224
Before introducing changes: https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-integration-k3s/1352361700979904512
Looks like we get >30s, that's worth the 1cent of price difference.
- VM type …

Change VM type to N2 in k3s jobs

---

development/tools/pkg/vmscollector/collector.go
prow/scripts/provision-vm-and-start-kyma-k3s.sh
vpath/pjtester.yaml

VM is not deleted now, only stopped:
```
2021/01/22 10:39:22 UTC [INFO] Stopping instance kyma-integration-test-f3add759
2021/01/22 10:39:22 UTC [INFO] It will be removed automatically by cleaner job
Stop instance in progress for [https://www.googleapis.com/compute/v1/projects/sap-kyma-prow-workloads/zones/europe-west4-a/operations/operation-xxxxxxxx].
Use [gcloud compute operations describe URI] command to check the status of the operation(s).
2021/01/22 10:39:23 UTC [INFO] End of cleanup
```
Cleaner logs:
https://storage.googleapis.com/kyma-prow-logs/logs/adamwalach_test_of_prowjob_orphaned-vms-cleaner/1352585805377310720/build-log.txt
- ...
- ...
- ...

Make VM cleanup async in k3s jobs

---

prow/images/buildpack-golang-toolbox/Dockerfile

- Bump version of buildpack-golang used in buildpack-golang-toolbox to 1.15.7

Bump base image version of buildpack-golang-toolbox

---

development/tools/jobs/control-plane/control_plane_gke_integration_test.go
prow/jobs/control-plane/control-plane-gke-integration.yaml

Make `pre-master-control-plane-gke-integration` job as optional till https://github.com/kyma-project/control-plane/pull/401 will be merged.

Make pre-master-control-plane-gke-integration job as optional

---

prow/scripts/cluster-integration/control-plane-gke-integration.sh

Add override for KEB in `control-plane-gke-integration` : parameter `disableProcessOperationsInProgress` is set to true

Add override for KEB in control-plane-gke-integration

---

prow/scripts/cluster-integration/compass-gke-integration.sh
prow/scripts/kyma-testing.sh

Currently, compass e2e tests are not concurrency safe.

Fix compass-gke-integration

---

prow/scripts/cluster-integration/kyma-upgrade-gardener-azure.sh
vpath/pjtester.yaml

Test installs the latest Kyma release and executes before-upgrade tests. Then Kyma is upgraded to the latest commit on master and after-upgrade tests are run. Post-upgrade tests take longer than 2h to finish, with the cluster-users test alone taking over 1h to finish. 
- Delete cluster-users test definition
#3037

Remove cluster-users test definition 

---

development/tools/jobs/control-plane/control_plane_gke_integration_test.go
prow/jobs/control-plane/control-plane-gke-integration.yaml

Make `pre-master-control-plane-gke-integration` job as required because kyma-project/control-plane#401 is merged.
https://github.com/kyma-project/test-infra/pull/3214

Make pre-master-control-plane-gke-integration job as required

---

prow/scripts/build-kcp-development-artifacts.sh

- Add `kyma-kcp-installer.yaml` to `build-kcp-development-artifacts.sh`. Now local/prow installation kcp is difference than mps installation so diffrent cr-installer is needed. New `kyma-kcp-installer.yaml` file is generated by script in KCP (check related PR section)
**Related PR(s)**
https://github.com/kyma-project/control-plane/pull/482

Add kyma-kcp-installer to build-kcp-development-artifacts

---

prow/scripts/cluster-integration/compass-gke-integration.sh
vpath/pjtester.yaml

- Enable holdApplicationUntilProxyStarts Istio flag (compass-gke-integration)

Enable holdApplicationUntilProxyStarts on compass-gke-integration

---

prow/scripts/cluster-integration/kyma-cli-alpha-upgrade.sh

Fix syntax issue in alpha-cli upgrade job.

 Use exit instead of return outside of fcts

---

prow/jobs/test-infra/image-syncer.yaml
templates/data/image-syncer-data.yaml

After switching to the templates for image-syncer prowjobs the job is broken. The `GOOGLE_APPLICATION_CREDENTIALS` variable is missing.
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/pr-logs/pull/kyma-project_test-infra/3278/pre-master-test-infra-image-syncer-dry-run/1359497777565929472
- add/remove missing or not needed presets for image-syncer prowjobs.

Add missing presets to image-syncer-data.yaml

---

prow/scripts/compatibility-cli.sh

- It is possible to have a patch release after a higher major or minor release (e.g. chronologically: 1.0.1, 1.1.0, 1.0.0).
Sorting the releases fixes this issue when backtracking for compatibility.
https://github.com/kyma-project/test-infra/issues/3229

Sort releases in compatibility job

---

templates/config.yaml
templates/data/examples-data.yaml
templates/data/image-syncer-data.yaml
templates/data/incubator-third-party-images-data.yaml
templates/data/react-components-data.yaml
templates/data/stability-checker-data.yaml
templates/data/test-log-collector-data.yaml
templates/data/testgrid-automation-data.yaml
templates/data/watch-pods-data.yaml

Separate TestGrid configuration from default post submit config. It seems the annotations for the testgrid are merged and that not wanted behaviour.
- Separate testgrid annotations from jobConfig_default
- 

Separate testgrid annotations from jobConfig_default

---

prow/cluster/components/11-plank_deployment.yaml
prow/cluster/components/30-crier_deployment.yaml
prow/config.yaml
templates/templates/prow-config.yaml

k8s testgrid instance require podinfo.json file to render test results. This file is provided by crier gcs kubernetes reporter.

Enable podinfo reporter

---

prow/scripts/resources/debug-container.yaml
vpath/pjtester.yaml

For some containers, cgroup path container leading space. This breaks path to the cgroup in a container.

Fix oom debug

---

prow/cluster/components/30-crier_deployment.yaml
prow/jobs/kyma/kyma-integration-gardener.yaml
templates/templates/kyma-integration-gardener.yaml
vpath/pjtester.yaml

Enabling pubsub reporter in crier to offload prowjob postprocessing outside prowjob context.

enable pubsub reporter

---

prow/images/buildpack-golang-toolbox/Dockerfile

Issue in mockery: https://github.com/vektra/mockery/issues/364
```
Step 8/16 : RUN go get github.com/vektra/mockery
---> Running in 4292f0f7d46d
[91mcannot find package "github.com/hashicorp/hcl/hcl/printer" in any of:
/usr/local/go/src/github.com/hashicorp/hcl/hcl/printer (from $GOROOT)
/workspace/go/src/github.com/hashicorp/hcl/hcl/printer (from $GOPATH)
```
- GO111MODULE="on" enabled for mockery

Fix toolbox image dependency

---

prow/images/buildpack-golang-toolbox/Dockerfile
prow/images/buildpack-golang-toolbox/Makefile
prow/images/buildpack-golang-toolbox/README.md

- Add golangci-lint to golang-toolbox image
https://github.com/kyma-incubator/hydroform/issues/221

Add golangci-lint to golang-toolbox image

---

development/tools/pkg/pjtester/pjtester.go

Podinfo lens provide usefull data for troubleshooting and testing of prowjob. This data should be provided for jobs tested by pjtester.
Podinfo data is provided by crier reporter, when all reporting is disabled podinfo was not generated. We can enable all reporting and redirect slack notifications to kyma-prow-dev-null channel to avoid false positive and garbage on ci-force channel.

slack reporting to dev null

---

docs/prow/prow-monitoring.md
milv.config.yaml

- A [Prow job error](https://storage.googleapis.com/kyma-prow-logs/logs/test-infra-governance-nightly/1376398803283742721/build-log.txt) found links with the error `"https://monitoring.build.kyma-project.io":  x509: certificate has expired or is not yet valid` 
- The reason is that these are not "real" links but something the user should run locally after setting up [monitoring](https://github.com/kyma-project/test-infra/blob/main/docs/prow/prow-monitoring.md#prow-cluster-monitoring-setup). This is indicated by the links being written in `code font`. However, Prow job checks them anyway because they start with `https://` 
- This PR adds the links to the MILV list so they will be ignored

Fix Prow monitoring links

---

prow/scripts/lib/utils.sh

Cleanup function should search for oom events always when describe nodes is called. Adding grep which was removed by mistake.

search for oom events by default

---

prow/branchprotector-config.yaml
templates/templates/branchprotector-config.yaml

- Protect only the `main` branches in `compass`, `compass-console`, and `ord-service` - the team often works in pairs and in topic branches, which is more complicated with forks

Adjust kyma-incubator/compass branch protection rules

---

prow/jobs/kyma/kyma-integration.yaml
templates/templates/kyma-integration.yaml

Due to issues on compass dev instance our compass-dev related pipelines are failing. To release development making presubmit and posubmit as optional, decreasing periodic to one run per day.

suppress k3s integration with compass

---

prow/branchprotector-config.yaml
templates/templates/branchprotector-config.yaml

Reverts kyma-project/test-infra#3484
With current used branchprotector version we can't have requried jobs defined by prow on repositories/branches which are not protected.
Newer version of branchprotector allow for such configuration when allow_disabled_job_policies flag is set.

Revert "Adjust kyma-incubator/compass branch protection rules"

---

development/tools/jobs/testinfra/validate_test.go
prow/jobs/test-infra/validation.yaml
templates/data/validation-data.yaml
vpath/pjtester.yaml

Checkconfig is and external tool from kubernetes/test-infra.
Right now we are using prow tools and vendored checkconfig code to check images. With this PR we switch `pre-test-infra-validate-configs` to external image that is rebuild in daily basis. We should use this image if we want to introduce Prow autobumper
Successful run
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_test-infra/3595/pre-test-infra-validate-configs/1386673916583350272
#3370

Use `gcr.io/k8s-prow/checkconfig:v20210407-51f95c2d52` for checking Prow config files.

---

prow/config.yaml
prow/jobs/test-infra/branchprotector.yaml
templates/templates/prow-config.yaml

Tide is spitting errors for the release branch PR:
```
{"component":"tide","controller":"sync","duration":"1.194371396s","file":"prow/tide/tide.go:362","func":"k8s.io/test-infra/prow/tide.(*Controller).Sync.func1","level":"info","msg":"Synced","severity":"info","time":"2021-04-28T11:19:27Z"}
{"branch":"release-1.22","component":"tide","controller":"status-update","error":"failed to set up context register: contexts pre-rel122-kyma-gke-integration, pre-rel122-kyma-gke-upgrade, pre-rel122-kyma-integration are defined as required and required if present","file":"prow/tide/status.go:371","func":"k8s.io/test-infra/prow/tide.(*statusController).setStatuses.func1","level":"error","msg":"getting expected status","org":"kyma-project","pr":11194,"repo":"kyma","severity":"error","sha" …
```

Remove remove release branch protection config from kyma

---

prow/cluster/components/pjtester_prowjob-scheduler_rbac.yaml

Adding missing service account and rbac for pjtester to start test prowjobs.
We lost this during prow upgrade.

Missing service account and rbac for pjtester on new prow

---

prow/jobs/test-infra/buildpack.yaml
templates/data/buildpack-data.yaml

pubsub-connector and github-connector are now separated from slack-connector. Moved to new directories.
Updating paths in prowjobs definitions.
See #3701

update pubsub-connector and github-connector paths

---

prow/scripts/cluster-integration/compass-gke-benchmark.sh

Benchmark tests should be executed on one and the same node in order to have stable results.

Execute benchmarks on a specific node

---

prow/scripts/cluster-integration/compass-gke-integration.sh
vpath/pjtester.yaml

Benchmark tests should not be executed on gke-integration job.

Omit benchmarks on integration tests

---

prow/scripts/cluster-integration/compass-gke-benchmark.sh
vpath/pjtester.yaml

As there is variable load on each node and this makes benchmark tests flapping we need to dedicate a whole clean node for them.

Execute benchmark tests on a dedicated node

---

prow/images/buildpack-golang/Makefile

Bump Go version to the latest 1.16.4 for buildpack image

Bump Go version to latest 1.16.4

---

prow/images/buildpack-golang-kubebuilder2/Dockerfile

Bump buildpack kubebuillder2 image (`prow/images/buildpack-golang-kubebuilder2/Dockerfile` file) to the latest `v20210601-19326f24` version

Bump buildpack kubebuillder2 image

---

prow/scripts/cluster-integration/compass-gke-integration.sh

**Enable ext svc mock auditlog for tests**
- Enabled external services mock's auditlog tests for compass by settings an override

Enable ext svc mock auditlog for tests

---

prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
stability-checker/deploy/chart/stability-checker/templates/deploy.yaml

When `holdApplicationUntilProxyStarts: true` is set in in istio configuration installation of stability-checker broke. It was caused by disabled Envoy readiness probe annotation `status.sidecar.istio.io/port: "0"` set in a chart. Because of that kubelet was returning errors:
```
Warning  FailedPostStartHook  7m6s (x66 over 6h50m)  kubelet  (combined from similar events): Exec lifecycle hook ([pilot-agent wait]) for Container "istio-proxy" in Pod "stability-checker-59b8dd9f44-2jnrg_kyma-system(4cef429c-cb71-4fca-b843-b7a5649ca8b6)" failed - error: command 'pilot-agent wait' exited with 255: Error: timeout waiting for Envoy proxy to become ready. Last error: HTTP status code 503
, message: "2021-06-08T11:35:26.086996Z\tinfo\tWaiting for Envoy proxy to be ready (timeout: 60 …
```

Remove readiness probe disablement from stability-checker helm chart

---

prow/autobump-config/prow-cluster-autobump-config.yaml
prow/jobs/test-infra/prow-periodics.yaml
templates/data/prow-periodics-data.yaml

Initial prow autobump configuration based on the https://github.com/kubernetes/test-infra/tree/master/prow/cmd/generic-autobumper. For now without auto bump postsubmit - it should only open PR with bumps automatically.
The binary should iterate over the entire test-infra repository and look for images with given prefix ("gcr.io/k8s-prow/" in this case) and bump all the images to the latest tag available on the registry. Additionally it can exclude some directories from bumping, see the config.
#3498
/hold

Initial Prow autobump configuration

---

prow/scripts/cluster-integration/kyma-integration-gardener.sh
prow/scripts/lib/gardener/aws.sh
prow/scripts/lib/gardener/azure.sh
prow/scripts/lib/gardener/gcp.sh
vpath/pjtester.yaml

If gardener provision cluster failed and script tries provision second fresh cluster, cleanup function called by trap on INT and EXIT was trying to clean first cluster again. This cluster didn't exist already and second cluster was not cleaned.

fix cleanup second failed cluster.

---

prow/scripts/cluster-integration/compass-gke-benchmark.sh

**Enable ext svc mock auditlog for tests**
- Enabled external services mock's auditlog tests for compass by settings an override

Enable auditlog secret for benchmark tests

---

prow/cluster/components/deck_service.yaml

Ingress is complaining:
```
Translation failed: invalid ingress spec: service "default/deck" is type "ClusterIP", expected "NodePort" or "LoadBalancer"
```

Change deck service type from not working ClusterIP to NodePort

---

prow/plugins.yaml

After merging #3733 job-config couldn't be updated due to the following error:
```
{"component":"unset","configmap":{"cluster":"default","name":"job-config","namespace":"default"},"error":"update config map err: ConfigMap \"job-config\" is invalid: []: Too long: must have at most 1048576 bytes","file":"/Users/i531931/go/src/k8s.io/test-infra/prow/cmd/config-bootstrapper/main.go:155","func":"main.run","level":"error","msg":"failed to update config on cluster","severity":"error","time":"2021-06-18T11:15:40+02:00"}
```
Possible solution:
https://github.com/kubernetes/test-infra/blob/master/prow/plugins/config.go#L452

GZIP job-config

---

prow/scripts/cli-tests/test-function.sh
prow/scripts/compatibility-cli.sh

Description
This fixes the pipeline failure.
Greetings from Icke :)
- 1 in COMPAT_BACKTRACK refers to current release. 2 refers two previous release. In the old version, the value 1 was not fetching the current release version, but backtracking one major version
- Change node runtime to v12 when creating kyma functions in the tests
...
Related issue(s)
kyma-project/cli#921

CLI compatibility script: check 2 latest kyma versions and set node runtime

---

development/tools/cmd/rendertemplates/main.go

Add `show-output-dir` flag to allow printing generated files to the stdout during template generation. It's useful to know the output directories that were added in specific workloads.

Add `show-output-dir` flag to rendertemplates

---

development/image-syncer/external-images.yaml

Bump `service-manager-proxy` external image from `v0.8.18` to `v0.9.0`

Bump service manager proxy external image

---

prow/config.yaml
prow/scripts/cluster-integration/kyma-gke-integration.sh
prow/scripts/resources/containerd-gke-patch.tpl.yaml
templates/templates/prow-config.yaml
vpath/pjtester.yaml

Enable tests on GKE with containerd images
- Enable tests on GKE with containerd images
- Bump GKE cluster version to 1.19
- Add a patch to apply the following on test clusters
- Run the injection script in a privileged container
- Add new privileged PSP with hostPID/network allowed
- Add related clusterrole/clusterrolebinding to use it
- Update the certs injection script to handle both containerd and docker.
- Allow the injection SA to get/list nodes
https://github.com/kyma-project/kyma/issues/10842

Enable tests on GKE with containerd images

---

prow/images/bootstrap/Dockerfile

As part of securing the images, we are adding cosign to the bootstrap
image. This will allow the signing of the images.
The version is hard-coded to prevent any future new breaking updates and using v0.2.0.
Signed-off-by: Youssef Azrak yazrak.tech@gmail.com

Adding Cosign to bootstrap image

---

development/image-syncer/external-images.yaml
development/image-syncer/main.go

- add support for SHA digests
- if the `source` field contains SHA256 checksum, then `tag` field is required, as the target will get tagged with tag instead of the digest
- check if tag and digest matches for new images, but don't exit the program if they don't
#3861

Image syncer: allow for SHA digests

---

prow/jobs/kyma/kyma-integration.yaml
prow/scripts/cluster-integration/kyma-gke-integration.sh
prow/scripts/resources/containerd-gke-patch.tpl.yaml
templates/data/kyma-integration-data.yaml
vpath/pjtester.yaml

Enable tests on GKE with containerd images
- Enable tests on GKE with containerd images
- Bump GKE cluster version to 1.19
- Add a patch to apply the following on test clusters
- Run the injection script in a privileged container
- Add new privileged PSP with hostPID/network allowed
- Add related clusterrole/clusterrolebinding to use it
- Update the certs injection script to handle both containerd and docker.
- Allow the injection SA to get/list nodes
https://github.com/kyma-project/kyma/issues/10842

[release-1.23] Enable tests on GKE with containerd images

---

prow/scripts/cluster-integration/control-plane-gke-integration.sh
vpath/pjtester.yaml

rm the step of `installCompass` in the `control-plane-gke-integration.sh`
[PR861](https://github.com/kyma-project/control-plane/pull/861) failed at the compass install phase in the https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/861/pre-main-control-plane-gke-integration/1418488550575312896/build-log.txt

rm installCompass from pre-main-control-plane-gke-integration testing case

---

prow/scripts/cluster-integration/compass-gke-integration.sh
vpath/pjtester.yaml

The new approach for running "down" migrations in Compass requires a Persistent Volume, which is bound to two jobs - the one that will execute the "up" migrations, and the one that will execute the "down" migration before the helm roll-back.
The pods of those jobs can be scheduled on different nodes, and GKE does not support ReadWriteMany access type for storages, hence, we need to make sure that the pods of those jobs will run on the same node.
- Label GKE node for Compass integration tests
**Related PR(s)**
- https://github.com/kyma-incubator/compass/pull/1948

Compass down migrations

---

development/custom-image/install-deps-debian.sh

- Changes pending in https://github.com/kyma-project/test-infra/pull/4023 require that k3d is present on the VM image for Kyma to be able to provision a k3d cluster
* #4023
* https://github.com/kyma-project/kyma/issues/11668

Add dependency k3d for fast-integration tests to VM image

---

prow/scripts/cluster-integration/fast-integration-test.sh
prow/scripts/lib/gardener/azure.sh
prow/scripts/lib/gardener/gcp.sh

Since Kyma is installed on the pipeline for fast-integration tests all make targets are running tests without installation from test code. To remove target `ci-no-install` it is replaced here with `ci` since both are currently doing the same and `ci-no-install` should be deleted from tests/fast-integration in kyma repository.
- Replace all occurences of `make ci-no-install` with `make ci`
* https://github.com/kyma-project/kyma/issues/11668

Replace occurences of ci-no-install make target with ci

---

prow/scripts/cluster-integration/kyma-integration-k3d-compass-components.yaml
prow/scripts/cluster-integration/kyma-integration-k3d.sh
prow/scripts/provision-vm-and-start-kyma-k3d.sh
vpath/pjtester.yaml

It seems that the `--component` flag of `kyma deploy` can only be used to patch existing Kyma installations.
Listing components via this flag made tests flaky because istio is a prereq and the order of installed components matters.
To fix this for the compass test scenario where some components are skipped and compass-runtime-agent needs to be added it is more reasonable to use a components file.
- Replace specification of components for compass scenario by `--components-file`
* https://github.com/kyma-project/kyma/pull/11879
* https://github.com/kyma-project/kyma/issues/11668

Provide components for compass tests via file

---

prow/jobs/incubator/compass/compass-integration-no-dump.yaml
prow/jobs/incubator/compass/compass-integration.yaml
prow/scripts/provision-vm-compass.sh
templates/data/compass-integration-data.yaml
templates/data/compass-integration-no-dump.yaml

Some tests need to be executed on clusters that are not previously populated with dump. This PR introduces a second compass-integration job which will execute such tests in a cluster which is not populated by db-dump.

Introduce compass integration without db-dump

---

prow/scripts/cluster-integration/compass-gke-benchmark.sh

Due to recently changed compass-migration job in the compass repository, the deletion of this job is no longer managed by Helm and in the benchmark test, the second compass installation fails due to K8s job patching failure. To solve this problem we manually delete the compass-migration job before the second installation.
- Delete compass-migration job before the second compass installation

Fix sequential compass installations in benchmark tests

---

prow/scripts/provision-vm-cli.sh

gcloud labels do not support dots as characters. Env `PULL_BASE_REF` will contain dots if the job is run against `release-x.xx` branch. The dot character has to be replaced with either dash or underscore.

Replace dot to dash provision-vm-cli.sh labels

---

prow/images/kyma-integration/Dockerfile
prow/images/kyma-integration/Makefile

- Updates kubectl version to 1.18 in kyma-integration
- Updates Helm version to 3.6.2 in kyma-integration
- kubectl v1.18 is needed for [reconciler e2e testing](https://github.com/kyma-project/test-infra/pull/4071)

Bump kubectl to v1.18 and helm to v3.6.2 in kyma-integration

---

development/image-syncer/external-images.yaml

Regarding this [Protecode issue](https://github.tools.sap/kyma/security-scans/issues/8486) we need to update the alertmanager image.
- Changed alertmanager image for imagesyncer to `v0.23.0`, which is the newest stable release

Update Prometheus Alertmanager to Version 0.23.0

---

prow/jobs/scans/whitesource-periodics.yaml
templates/data/whitesource-periodics-data.yaml

The `kyma-whitesource-scan` runs only against `kyma/tools/failery` which still operates on go-dep, where the rest of Kyma is already on go mod. This tool is not updated for 14 months and the result scan report is broken. This PR disables the job.
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-whitesource-scan/1440163893530857472
```
[WARN] [2021-09-21 04:00:58,204 +0000] - CommandLineProcess - executeProcessCommand - error in execute command 'go build', Exit Status 1
```

Disable kyma-whitesource-scan

---

prow/scripts/lib/docker.sh

We noticed these random errors on some of our build jobs:
```
[0133] | (12/14) Installing gcc (10.2.1_pre1-r3)
[0133] | (13/14) Installing musl-dev (1.2.2-r1)
[0133] | (14/14) Installing libc-dev (0.7.2-r3)
[0133] | Executing busybox-1.32.1-r6.trigger
[0133] | OK: 127 MiB in 28 packages
[0135] | Removing intermediate container 3fb9e61ed85a
[0135] | ---> fdf6f04e21d8
[0135] | Step 4/15 : RUN apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community libgit2-dev=${LIBGIT2_VERSION}
[0135] | ---> Running in 37e0dc189ab2
[0135] | fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
```
According to this comment, https://github.com/gliderlabs/docker-alpine/issues/307#issuecomment-721636132
we should set MTU value for docker to …

Fix docker MTU

---

prow/jobs/scans/whitesource-periodics.yaml
templates/data/whitesource-periodics-data.yaml

After https://github.com/kyma-incubator/podpreset-crd was migrated to Go Mod, the whitesource scanner failed to provide the proper scan for dependencies using Go Mod package manager.

Fix whitesource scan for podpreset project

---

development/tools/jobs/cli/cli_integration_test.go
prow/jobs/cli/cli-integration.yaml
prow/scripts/provision-vm-cli.sh
templates/data/cli-data.yaml
vpath/pjtester.yaml

- Rename cli integration jobs in `cli-integration-kyma-1` (which uses `kyma install` on minikube) and `cli-integration-kyma-2` (which uses `kyma deploy` on k3d)
- No pipelines added, just renamed

Rename cli integration pipelines

---

prow/scripts/cluster-integration/kyma-busola-long-lasting.sh
prow/scripts/cluster-integration/kyma-integration-gardener.sh
prow/scripts/lib/kyma.sh

Regarding [this change](https://github.com/kyma-project/cli/pull/1000) `kyma delete` is not available anymore.
Kyma gets now installed with `kyma deploy` (based on reconciler) and uses `kyma undeploy` to remove kyma from a running K8s cluster.

Adapt kyma delete to undeploy

---

development/tools/jobs/incubator/reconciler/reconciler_test.go
development/tools/jobs/kyma/kyma_gardener_cleanup_test.go
prow/jobs/incubator/reconciler/reconciler.yaml
prow/jobs/kyma/kyma-gardener-cleanup.yaml
prow/scripts/cluster-integration/helpers/reconciler.sh
prow/scripts/resources/reconciler/shoot-template.yaml
templates/data/incubator-buildpack-data.yaml
templates/data/kyma-gardener-cleanup-data.yaml
vpath/pjtester.yaml

- Re-enable nightly-main-reconciler-e2e
- Make pre-main-reconciler-integration-k3d job non-optional
See https://github.com/kyma-project/test-infra/issues/4240

Re-enable reconciler nightly and make e2e job non-optional

---

development/image-syncer/external-images.yaml

Previous golang-runtime 1.16.4 contains vulnerabilities
CVE-2021-38297
CVE-2021-33195
CVE-2021-33194
CVE-2021-34558

update golang image to 1.17.3 in syncer

---

development/image-syncer/main.go
development/image-syncer/pkg/common.go
development/image-syncer/util.go
development/image-url-helper/cmd/check.go
development/image-url-helper/cmd/list.go
development/image-url-helper/cmd/promote.go
development/image-url-helper/pkg/check/filecheck.go
development/image-url-helper/pkg/list/imagelister.go
development/image-url-helper/pkg/list/outputjson.go
development/image-url-helper/pkg/promote/externalsyncer.go
development/image-url-helper/pkg/promote/promote.go

- flags
- make `target-container-registry` flag mandatory
- add `dry-run` flag to skip updating `value.yaml` files
- add `sign` flag for the generated YAML file
- `image-syncer` compatiblity
- Add YAML generation in format understood by the image-syncer
- edit image-syncer to be able to have YAML structs as a package
- refactor `image-url-helper` to reuse parts of the `list` subcommand
#4443

Image-url-helper: add external images yaml output to promote command

---

prow/scripts/cluster-integration/compass-gke-benchmark.sh

**move compass gke-benchmark overrides in separate file**
Fixes failing installation for benchmark tests. Compass migration job was failing because no node was available for schedule.

move compass gke-benchmark overrides in separate file

---

prow/config.yaml
prow/jobs/incubator/reconciler/reconciler.yaml
prow/scripts/reconciler-publish-unstable-cli.sh
templates/data/incubator-buildpack-data.yaml
templates/templates/prow-config.yaml
vpath/pjtester.yaml

Create CI pipeline to generate nightly CLI builds using the latest reconciler
- A nightly pipeline job to create unstable Kyma builds
Closes https://github.com/kyma-incubator/reconciler/issues/283
Requires https://github.com/kyma-project/cli/pull/1099 to be merged first.

Pipeline job to create unstable Kyma CLI upon Reconciler changes

---

development/image-url-helper/cmd/promote.go
development/image-url-helper/excludes_promote.yaml
development/image-url-helper/pkg/list/imagelister.go
development/image-url-helper/pkg/promote/promote.go

- Add `excludes-list` flag for `promote` command
- join old registry to the new one in `values.yaml` file so the structure reflects promoted images 
- fix map of inconsistent images
Blocked by #4479

Image-URL-helper: add option to exclude images from being promoted

---

prow/scripts/cluster-integration/busola-integration-test-k3s.sh
prow/scripts/provision-vm-and-start-busola-k3s.sh
vpath/pjtester.yaml

As we were talking yesterday we don't have to copy `nbusola` to `kubeconfig-2` so we have to delete it.
- Deleted changes from PR #4516

Removed copying nbusola

---

prow/scripts/lib/kyma.sh

- Version can be provided, allowing to return release number for a given major version
Based on observation in #4544, we don't have any way to retrieve a latest release for a given major version

Scripts: make Kyma version retrieval more universal

---

prow/jobs/kyma/releases/kyma-release-20.yaml
prow/scripts/cluster-integration/kyma-gke-release-candidate.sh
templates/data/kyma-integration-data.yaml
templates/data/kyma-release-data.yaml
vpath/pjtester.yaml

Updated a kyma-release-candidate.sh script to use `kyma deploy` command and install the version from the new tag.
Additionally after talk with @pxsalehi the ci-eventing fast-integration test was removed. The eventing team will just run the automated test manually.

Fix RC cluster

---

prow/scripts/cluster-integration/compass-gke-benchmark.sh

Loki and Prometheus expect the node in `europe-west4-b` to be schedulable as the PVs have nodeAffinity rules.

Do not make the PV zone node unschedulable

---

prow/scripts/cluster-integration/compass-gke-benchmark.sh
prow/scripts/cluster-integration/compass-gke-integration.sh

Revert to zonal clusters to avoid PV replication across zones and nodeAffinity conflicts.

Revert compass jobs to use zonal clusters

---

CODEOWNERS

Piotr left Kyma and he's no longer an active contributor so, according to the [guidelines](https://kyma-project.io/community/governance/01-governance/#when-does-a-maintainer-lose-the-maintainer-status), he can be removed from the codeowners.
- Remove Piotr (`jasiu001 `) from codeowners

Remove Piotr from codeowners

---

prow/scripts/cluster-integration/reconciler-e2e-upgrade-gardener.sh
prow/scripts/lib/gardener/gcp.sh
vpath/pjtester.yaml

the kyma1-kyma2 reconciler upgrade pipeline fails.
The reason seems to be that kyma1 is installed without any profile, while kyma2 is installed using evaluation profile.
- install kyma1 in the pipeline using explicitly configured "evaluation" profile
https://github.com/kyma-incubator/reconciler/issues/595

Fix kyma1-kyma2-upgrade plan

---

prow/config.yaml
templates/templates/prow-config.yaml

We cannot protect private repositories created in kyma-project. That breaks branch protection updates. This PR explicitly excludes the private repository from default branch protection.

Disable branch protection for private repo.

---

prow/scripts/provision-vm-and-start-busola-docker.sh
prow/scripts/provision-vm-and-start-busola-k3s.sh

We found that prowjob scripts are not calling cleanup function through the trap when prow abort prowjob execution. Testing support for additional signals.
- Change trap definition to call it for signals 0, 1  and 2.

call cleanup on EXIT, HUP and INT

---

OWNERS
prow/labels.yaml

Add area labels to sync across all repos. Those labels are used by OWNERS.
Is something is missing it should be added in follow-up PRs.
/hold

Add initial area labels to `label_sync`.

---

OWNERS_ALIASES

As @grego952 has been working with Kyma for over 3 months as a Technical Writer and has gained expertise in this domain, he should be added to the documentation OWNERS.
- Add @grego952 to `test-infra` documentation OWNERS in OWNERS_ALIASES
**Related issue**
[#13077 ](https://github.com/kyma-project/kyma/issues/13077)

Add grego952 in OWNERS_ALIASES as a documentation OWNER in `test-infra`

---

prow/plugins.yaml

`milestone` allows to set milestone for issues and PRs.
`override` allows repo admins to override the github status
`retitle` allows to change PR or issue title
`lifecycle` closes/reopens/flags issue based on the comment
`transfer-issue` transfers issue between repositories on the same org
`projects` allows team members to add issue/PR to the project
More information about plugins: https://status.build.kyma-project.io/plugins

Enable additional useful plug-ins for test-infra

---

prow/config.yaml
prow/plugins.yaml
templates/templates/prow-config.yaml

Since Prow takes cares of approvals and people have write access revoked `reviewApprovedRequired: true` is not needed.
/cc @Halamix2
/kind feature

Remove requiring GitHub review from test-infra context

---

prow/plugins.yaml

New functionality has been added to Prow which resolves problem with GitHub Apps not being trusted and ignore requesting review on draft PRs.
Resolves #4798 
Resolves #4625

Use trusted_apps and ignore_drafts

---

development/tools/jobs/testinfra/branchprotector_test.go
prow/config.yaml
templates/templates/prow-config.yaml

Remove requiring pull request review from code owners on test-infra repo. Not needed since test-infra works with Prow approval flow. 
/area prow
/kind cleanup

Disable required_pull_request_reviews for test-infra

---

development/external-plugins/cla-assistant/main.go
development/external-plugins/cla-assistant/main_test.go
prow/cluster/components/cla-assistant_external-plugin.yaml
prow/images/cla-assistant-external-plugin/Dockerfile
prow/plugins.yaml

This plugin allows easy CLA recheck once it gets stuck on `Expected - Waiting for status to be reported`. It only works on comments made in PRs.
Fixes #4624

Recheck CLA Assistant status plugin

---

prow/scripts/cluster-integration/kyma-upgrade-gardener-kyma-to-kyma2.sh
prow/scripts/cluster-integration/kyma-upgrade-gardener-kyma2-to-main.sh
vpath/pjtester.yaml

The working directory needs to be differenet than the extra_Ref directory - Because when using `--source` flag with anything different than `local`, it cleans up the directory afterwards. 
In those two pipeline we need multiple versions of Kyma, due to the upgrade scenario, plus we need the fast-integration tests. Thus, we will use source flag for the Kyma version and the external_refs for the fast-integration test.
- ...
- ...
- ...

Fix Upgrade Gardener Pipelines

---

prow/scripts/cluster-integration/kyma-gke-release-candidate.sh

Added Cluster Role Binding for kyma_developers GCP group for release cluster. This role binding should effectively add cluster-admin access for all people in kyma_developers GCP group, allowing then to modify all kubernetes resources.
Additionally added creation of admin-user service account with cluster-admin role and add kubeconfig as secret. This will resolve problem where people have to manually fetch access tokens for their connection with Busola
Fixes #4851

cluster-admin kubeconfig generation login for release GKE cluster

---

prow/scripts/cluster-integration/helpers/start-wssagent.sh

- The `modules` option  for the unified agent config property `go.dependencyManager=` is not supported anymore
- Since [Whitesource Unified Agent version 21.3.2](https://whitesource.atlassian.net/wiki/spaces/WD/pages/33718455/WhiteSource+Server+Release+Notes#Version-21.3.2-(11-April-2021)) there are dedicated `go.modules.*` config properties:
- go.modules.resolveDependencies
- go.modules.ignoreSourceFiles
- go.modules.removeDuplicateDependencies
- go.modules.includeTestDependecies
The variables `GO_CONFIG_PATH` and `JAVASCRIPT_CONFIG_PATH` were adjusted to use pre-configured `TEST_INFRA_SOURCES_DIR`

Adjust whiteource unified agent config for scan language `golang-mod`

---

prow/labels.yaml

`label` plugin allows managing the labels based on the command.
`/kind` command denotes usage of all `kind/` related labels.
Those define the PR or issue of specific kind. It's useful for Issue/PR management.

Add various kind/ labels.

---

prow/labels.yaml

The list should contain field marshal able to Label struct, not string.
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/ci-prow-label-sync/1491008381987590144
/cc @Halamix2

Fix labels.yaml unmarshal issue

---

prow/scripts/cluster-integration/helpers/start-wssagent.sh

According to the [WS documentation](https://whitesource.atlassian.net/wiki/spaces/WD/pages/33718455/WhiteSource+Server+Release+Notes#Version-21.3.2-(11-April-2021)):
>To use the enhanced Modules dependencies detection, it is recommended to turn on the new resolver by setting go.modules.resolveDependencies=true and disable the current Go resolver by setting go.resolveDependencies=false

Adjust go.modules configurations for WS Unified Agent

---

prow/config.yaml
prow/images/bootstrap/Dockerfile
prow/scripts/resources/busola/cluster-busola.yaml
prow/scripts/resources/busola/cluster-kyma.yaml
prow/scripts/resources/reconciler/shoot-template.yaml
templates/templates/prow-config.yaml
vpath/pjtester.yaml

- All hyperscaler should use 1.21 as the base version k8s api server version

Update jobs to use the 1.21 k8s server version

---

prow/scripts/cluster-integration/kyma-gke-upgrade.sh

The `kyma::get_last_release_version` script is incorrectly picking up 1.23.1 as last released version. This is incorrect.
The usual way of upgrading should be latest release, eg. 1.24.10 to latest version to be released, eg 1.24.11.
As a workaround hardcode release version until possibly we backport the changes to this function from main branch.
Need manual approved label.
/cc @Halamix2 
/cc @dekiel

Hardcode last release version to 1.24.10

---

development/tools/jobs/kyma/kyma_gardener_cleanup_test.go
prow/jobs/kyma/kyma-gardener-cleanup.yaml
templates/data/kyma-gardener-cleanup-data.yaml

Due to some load tests, we have a long running cluster which should not be deleted by the Gardener Cleaner job.
- Exclude `rec-wkly-lt` from cleaner
- ...
- ...

Exclude recon wkly from cleaner job

---

development/tools/jobs/incubator/compass/compass_gke_integration_test.go
prow/jobs/incubator/compass/compass-gke-integration.yaml
templates/data/compass-gke-integration-data.yaml
vpath/pjtester.yaml

- Specify kubernetes version used when creating gke cluster for compass e2e tests

Specify k8s version for compass gke tests cluster

---

prow/jobs/incubator/compass/compass-gke-benchmark.yaml
templates/data/compass-gke-benchmark-data.yaml
vpath/pjtester.yaml

- Fix kubernetes version used for compass benchmark tests to 1.20

Specify k8s version for benchmark tests

---

development/tools/jobs/incubator/compass/compass_gke_integration_test.go
prow/jobs/incubator/compass/compass-gke-benchmark.yaml
prow/jobs/incubator/compass/compass-gke-integration.yaml
templates/data/compass-gke-benchmark-data.yaml
templates/data/compass-gke-integration-data.yaml

With this [PR in CMP](https://github.com/kyma-incubator/compass/pull/2226) the k8s version of the tests cluster no longer needs to be fixed so this PR enables back automatic use of the latest k8s version.
- Revert #5008 
- Revert #5011

Revert fixed k8s version for compass gke and benchmark tests

---

prow/scripts/cluster-integration/helpers/reconciler.sh
prow/scripts/cluster-integration/reconciler-e2e-nightly-gardener.sh
prow/scripts/cluster-integration/reconciler-gardener-long-lasting.sh
vpath/pjtester.yaml

Currently,[nightly-main-reconciler-e2e](https://status.build.kyma-project.io/?job=nightly-main-reconciler-e2e) job failed due to can't find cluster which created by [nightly-main-reconciler](https://status.build.kyma-project.io/?job=nightly-main-reconciler), the reason is recent change brings inconsistent naming issue.

bug fixing: nightly main reconciler e2e can't connect to cluster

---

prow/images/bootstrap/Dockerfile

**Description:**
With one of our latest changes, we need the yq tool in our installation scripts in [compass](https://github.com/kyma-incubator/compass). Since there are quite a few tools in the bootstrap image I think that yq will be a good fit for it and can also be useful in other places

Install yq in bootstrap image

---

prow/jobs/kyma/kyma-integration.yaml
templates/data/kyma-integration-data.yaml

I need to change the logging level on the periodic `kyma-integration-k3d` job because I can not reproduce or trace the error using pjtester.
- set the environmental variable `DEBUG=true`
See also [this](https://github.com/kyma-project/kyma/issues/13563) related issue

Set the debug mode on the periodic kyma-integration-k3d job

---

prow/jobs/kyma/kyma-integration.yaml
templates/data/kyma-integration-data.yaml

I no longer need the verbose logging level on the periodic kyma-integration-k3d job.
- delete the environmental variable `DEBUG=true`

Delete the debug mode on the periodic kyma-integration-k3d job

---

prow/plugins.yaml

This is small feat. which enables some of the plugins we tested on the test-infra for all orgs.This will not affect the usual workflow. Generally these changes allow to add labels based on OWNERS files, use lifecycle plugin which recently had updates to work with stalebot and verify owners files.

Enable additional plugins for Kyma organizations

---

prow/config.yaml
prow/plugins.yaml
templates/templates/prow-config.yaml

Since kyma-incubator/compass already doesn't CODEOWNERS we need to enable Prow approval flow there https://github.com/kyma-incubator/compass/pull/2262. @NickyMateev please confirm.
Additionally I've consolidated 2 redundant queries for the organisations. 
/cc @dekiel

Enable approve plugin for kyma-incubator/compass

---

prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
prow/scripts/cluster-integration/kyma-gke-release-candidate.sh
prow/scripts/cluster-integration/reconciler-component-integration.sh

In 2.1 Istio-configuration got renamed to just istio, making the current overrides not working anymore for RC and long-running GKE clusters. This PR fixes the logic and makes the overrides working with new naming.
@jeremyharisch please confirm if this behaviour needs to be changed also for reconciler. If not the I will revert the changes in the script.
/kind bug
/assign @jeremyharisch
/hold

Fix istio configuration in kyma GKE RC and long-running clusters

---

prow/plugins.yaml

`require_self_approval` enforces that the author must explicitly approve their PR. That means if approver of the repo creates a PR their PR will not be auto-approved and would require separate approve from the other approver.

Add `approve` configuration for kyma and compass

---

prow/labels.yaml

Updates in labels config that reflects changes in Kyma migration to OWNERS files and adds some labels that are supposed to be managed by Prow in compass repo

Labels update

---

prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
prow/scripts/cluster-integration/kyma-gke-release-candidate.sh
prow/scripts/cluster-integration/reconciler-component-integration.sh

Since 2.1 `Istio-configuration` is renamed to `Istio`. That broke the overrides in GKE scripts. Cherry-picked fixes from main.
/kind bug
/label tide/merge-method-merge

Cp fix istio pipeline

---

prow/scripts/cluster-integration/kyma-upgrade-gardener-kyma2-to-main.sh
prow/scripts/cluster-integration/kyma-upgrade-k3d-kyma2-to-main.sh
prow/scripts/cluster-integration/reconciler-upgrade-kyma2-latest-to-main-gardener.sh

Remove obsolete migration script from reconciler pipelines
This script was required for upgrade scenarios between Kyma 2.0 and Kyma 2.1, but the pipelines now install Kyma 2.1 first, and the script is failing, causing entire plan to fail.
- Remove obsolete migration script from reconciler pipelines
**Links to failed pipelines**
- https://storage.googleapis.com/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-to-main-reconciler-main/1508413740670783488/build-log.txt
- https://storage.googleapis.com/kyma-prow-logs/logs/kyma-upgrade-k3d-kyma2-to-main/1508413740792418304/build-log.txt

Remove obsolete migration script

---

prow/plugins.yaml

Forgot to add actual approve and blunderbuss plugins to kyma

Enable approve for kyma-project/kyma

---

prow/scripts/cluster-integration/protecode-guard.sh

Right now the `protecode-guard` pipeline is often failing because of timeout ([example](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/13708/pre-main-kyma-protecode-guard/1509480329897840640)) to avoid situations like this, I'd like to propose increasing the timeout.

Increase timeout for protecode guard

---

development/image-syncer/external-images.yaml

- Bumped NATS prometheus exporter image 0.9.0 to a specific SHA.

Bumped NATS prometheus exporter image 0.9.0 on image-syncer

---

prow/config.yaml
templates/templates/prow-config.yaml

We need to have 2 default queries in Tide:
```
- labels:
- lgtm
missingLabels:
- needs-rebase
- do-not-merge/hold
- do-not-merge/work-in-progress
- do-not-merge/invalid-owners-file
- do-not-merge/invalid-commit-message
orgs:
- kyma-project
- kyma-incubator
excludedRepos:
- kyma-project/test-infra # handled in separate query specifically for approve plugin
- kyma-project/third-party-images
- kyma-project/cli
- kyma-project/kyma
- kyma-incubator/compass # handled in separate query specifically for approve plugin
reviewApprovedRequired: true
- labels:
- lgtm
- approved
missingLabels:
- needs-rebase
- do-not-merge/hold
- do-not-merge/work-in-progress
- do-not-merge/invalid-owners-file
- do-not-merge/invalid-commit-message
- do-not-merge/missing-docs-review
repos:
- kyma-project/test-infra
- …
```

Fix missing tide queries

---

development/tools/cmd/rendertemplates/main.go

Fix for #5260 
- Add file name to rendertemplates YAML parsing error message
#5260

Add file name to rendertemplates YAML parsing error message

---

development/tools/jobs/incubator/reconciler/reconciler_test.go
prow/jobs/incubator/reconciler/reconciler.yaml
templates/data/incubator-buildpack-data.yaml

fixes #5263 
- The `pre-main-reconciler-integration-k3d` job should run when the go.mod or go.sum files change.
#5263

pre-main-reconciler-integration-k3d trigger on go.mod or go.sum changes

---

prow/config.yaml
prow/jobs/kyma/kyma-integration-gardener.yaml
prow/scripts/cluster-integration/kyma-integration-gardener-eventing.sh
prow/scripts/lib/gardener/gcp.sh
templates/data/kyma-integration-gardener-data.yaml
templates/templates/prow-config.yaml
test-inventory-integration.md
vpath/pjtester.yaml

Add a prow-job to run JetStream E2E fast integration tests.
**Successful runs**
- https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/13779/marcobebway_test_of_prowjob_pre-main-kyma-gardener-gcp-eventing/1513920647124750336
- https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/13779/marcobebway_test_of_prowjob_pre-main-kyma-gardener-gcp-eventing/1513910509819138048
- https://github.com/kyma-project/kyma/issues/13739
- https://github.com/kyma-project/kyma/pull/13779

Add a prow-job to run JetStream E2E fast integration tests

---

development/image-syncer/external-images.yaml

This PR bumps `golang` to `1.18.1` to prevent security vulnerabilities:
https://hub.docker.com/layers/golang/library/golang/1.18.1-alpine3.15/images/sha256-f94174c5262af3d8446833277aa27af400fd1a880277d43ec436df06ef3bb8ab?context=explore

bump golang-alpine to golang 1.18.1

---

development/tools/cmd/githubrelease/README.md

Our [governance job](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/test-infra-governance-nightly/1517005402045157376) detected a broken anchor in a link to GitHub documentation on creating a release. This PR is fixing the link. 
- Fix a broken anchor to GitHub documentation on creating a release in the [README](https://github.com/kyma-project/test-infra/blob/main/development/tools/cmd/githubrelease/README.md).
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/test-infra-governance-nightly/1517005402045157376

Fix a broken anchor to GitHub documentation on creating a release

---

prow/config.yaml
templates/templates/prow-config.yaml

Auto merging without human review for bots must be disabled. This feature together with write access would allow anyone in organisation to push changes without review.
Parent: #5312

Disable automerging without review

---

prow/config.yaml
prow/plugins.yaml
templates/templates/prow-config.yaml

Removed settings for prow approval flow in kyma repository.
See: #5324

Revert prow approval flow in third-party-images

---

development/tools/jobs/testinfra/branchprotector_test.go
prow/config.yaml
prow/plugins.yaml
templates/templates/prow-config.yaml

Removed settings for prow approval flow in kyma repository.
See: #5323

Revert prow approval flow in test-infra

---

prow/scripts/cluster-integration/reconciler-e2e-gardener.sh
vpath/pjtester.yaml

- create a new variable based on cluster name for access in the cleanup script
- relates to a change made in https://github.com/kyma-project/test-infra/pull/5332 which enables the actual cleanup
- part of https://github.com/kyma-project/kyma/issues/13855

fix cleanup for pre-main-control-plane-reconciler-e2e

---

development/tools/jobs/kyma/kyma_integration_test.go
prow/jobs/kyma/kyma-integration.yaml
templates/data/kyma-integration-data.yaml

The kyma-integration-k3d-telemetry jobs were executed on component and chart change. However, only changing the component would still run the job with the old telemetry-operator image. Changing the CRD did not trigger the job and was added.
- Remove components/telemetry-operator from run_if_changed list
- Add telemetry CRDs to trigger job

Run kyma-integration-k3d-telemetry jobs if chart or crds changed

---

development/external-plugins/needs-tws/plugin.go
development/external-plugins/needs-tws/plugin_test.go

The problem is that working code for loading repo aliases already performs normalization when the file gets loaded. That means all usernames in the `RepoAliases` map are lower-cased and stripped from unnecessary prefixes. That means all usernames in the `handlePullRequestReview` function have to be normalized beforehand.
This behaviour was not visible through the test because fakes implement the struct as-is, so explanation comment was added on how the fake OwnersAliases struct should look like to make the test relevant.
/kind bug
/area tooling
Closes #5037

Normalize GitHub names and safe expand OWNERS_ALIASES

---

prow/scripts/lib/gardener/aws.sh
prow/scripts/lib/gardener/azure.sh
prow/scripts/lib/gardener/gcp.sh

- add verbose option to the provisioning command
- skip second attempt as the proper cleanup is not in place
https://github.com/kyma-project/kyma/issues/13855

One verbose attempt for gardener provisioning

---

development/image-syncer/external-images.yaml

this pr bumps the golang image to [golang:1.18.2-alpine3.15](https://hub.docker.com/layers/golang/library/golang/1.18.2-alpine3.15/images/sha256-3765360960a954c24b215518a41b0bf8e9e2fe3bd142b6f782fa56f8e00b8d21?context=explore)

bump golang image to 1.18.2-alpine3.15

---

prow/config.yaml
templates/templates/prow-config.yaml

We want to disable the strict requirement for an up-to-date main branch in order to speed up our contributions, since if there are no conflicts the changes were in different components. (We have versions that are bumped)

Do not require up-to-date branch for compass repo

---

prow/jobs/incubator/compass/compass-development-artifacts.yaml
templates/data/compass-development-artifacts-data.yaml

In CMP(UCL) we want to use github pre-releases and for that we need additional regex to match the tags
- add new pre-release regex

Add new job regex for release candidate

---

development/image-syncer/external-images.yaml

- Bumped NATS config reloader image tag

Bumped NATS config reloader image tag to 0.7.0 in image-syncer

---

prow/jobs/kyma/tests/fast-integration/fast-integration-image-generic.yaml
templates/data/kyma-fast-integration-data.yaml

the job `fast-integration-image` should only get executed on release after 2.2, because of the change of file structure that is needed for the job.

moved `fast-integration-image` up to release 2.3

---

development/image-syncer/external-images.yaml

bumps the golang image to alpine-3.16 (golang 1.18.2) 
https://hub.docker.com/layers/golang/library/golang/alpine3.16/images/sha256-76dfe4aee4c0bf1ecd9666d29d22087eae592f697f449a88c0c7fc81a82faa01?context=explore

bump golang image to alpine-3.16

---

prow/config.yaml
templates/templates/prow-config.yaml

Part of secret security hardening for compliance with SLC-29. Initial configuration, we might want to fine-tune it per ProwJob.
Closes #5250

Enable Prow secret censoring

---

prow/jobs/kyma/kyma-integration-gardener.yaml
prow/scripts/cluster-integration/kyma-integration-gardener-eventing-upgrade.sh
templates/data/kyma-integration-gardener-data.yaml
vpath/pjtester.yaml

Make the `pre-main-kyma-gardener-gcp-eventing-upgrade` job required:
- https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/14399/marcobebway_test_of_prowjob_pre-main-kyma-gardener-gcp-eventing/1534154833542516736
- https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/14481/marcobebway_test_of_prowjob_pre-main-kyma-gardener-gcp-eventing/1534143096349003776
- https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/14481/marcobebway_test_of_prowjob_pre-main-kyma-gardener-gcp-eventing/1534119950170460160
- https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/14481/marcobebway_test_of_prowjob_pre-main-kyma-gardener-gcp-eventing/153 …

Make the Eventing upgrade job required

---

development/image-syncer/external-images.yaml

image used https://hub.docker.com/layers/golang/library/golang/alpine3.16/images/sha256-725f8fd50191209a4c4a00def1d93c4193c4d0a1c2900139daf8f742480f3367?context=explore

bump golang version golang1.18.3:alpine3.16

---

development/tools/jobs/control-plane/control_plane_reconciler_integration_test.go
prow/jobs/control-plane/control-plane-reconciler-integration.yaml
templates/data/control-plane-integration-data.yaml

make pre-main-control-plane-reconciler-e2e optional temporarily so that not block other component release on control-plane https://github.com/kyma-project/control-plane/pull/1782

make pre-main-control-plane-reconciler-e2e optional

---

prow/plugins.yaml

The skip plugin allows users to clean up GitHub stale commit statuses for non-blocking jobs on a PR.
Command: `/skip`

Enable skip plugin on all repos

---

prow/scripts/cluster-integration/helpers/reconciler.sh

The pipeline `pre-main-control-plane-reconciler-e2e-latest-release` is failing since Kyma 2.4.0 release - Due to the reason that `helm-broker`, `service-catalogue`, and `service-catalogue-addons` have been removed. The PR https://github.com/kyma-project/control-plane/pull/1829 introduces a new template for Kyma versions >= 2.4.x. This PR makes use of the new template.
Please first merge https://github.com/kyma-project/control-plane/pull/1829

Using body template for Kyma2.4.x

---

development/image-syncer/external-images.yaml

This PR bumps the golang image to [`golang 1.19.0`](https://go.dev/blog/go1.19)-[`alpine 3.16`](https://alpinelinux.org/posts/Alpine-3.16.0-released.html)

bump golang image

---

prow/jobs/kyma/kyma-integration.yaml
templates/data/kyma-integration-data.yaml

There are constant problems with random errors reported by this job.  It seems we cannot merge anything without running it few dozens times.
The fast way to mitigate this problem to deliver important fixes is to make it optional.
In the future we will either fix this job or we will replace it with component tests for more granular verification of `application-connectivity` components.

Make pre-main-kyma-integration-k3d-central-app-connectivity-compass job optional

---

prow/scripts/cluster-integration/reconciler-e2e-gardener.sh

Disabling the defensive error handling for the E2E test of reconciler as we have failing pipelines.

Disabling set-e option for reconciler e2e pipeline

---

prow/jobs/incubator/compass-console/compass/compass-ui.yaml
prow/jobs/incubator/compass/components/connectivity-adapter/connectivity-adapter-generic.yaml
prow/jobs/incubator/compass/components/connector/connector-generic.yaml
prow/jobs/incubator/compass/components/director/director-generic.yaml
prow/jobs/incubator/compass/components/external-services-mock/external-services-mock-generic.yaml
prow/jobs/incubator/compass/components/gateway/gateway-generic.yaml
prow/jobs/incubator/compass/components/hydrator/hydrator-generic.yaml
prow/jobs/incubator/compass/components/operations-controller/operations-controller-generic.yaml
prow/jobs/incubator/compass/components/pairing-adapter/pairing-adapter-generic.yaml
prow/jobs/incubator/compass/components/schema-migrator/schema-migrator-generic.yaml
prow/jobs/incubator/compass/components/system-broker/system-broker-generic.yaml
prow/jobs/incubator/compass/tests/compass-e2e-tests/compass-e2e-tests.yaml
prow/jobs/incubator/ord-service/components/ord-service/ord-service-generic.yaml
templates/data/generic_component_compass_data.yaml

- Add Timeout to Compass component jobs
- This will help us [remove the proprietary change](https://github.com/kyma-incubator/compass/pull/2460) that we made to our `make release` target which also costed us waiting at minimum 15minutes for a component job to finish
https://github.com/kyma-incubator/compass/pull/2571

Add Timeout to Compass component jobs

---

development/image-syncer/external-images.yaml

bump `nats-config-reloader` to [`0.7.2`](https://hub.docker.com/layers/nats-server-config-reloader/natsio/nats-server-config-reloader/0.7.2/images/sha256-7e660b7c8e7dd54b982e38c3d3440a46fa60e9505e9164fd26d5515129e84cd9?context=explore) and `nats-prometheus-exporter` to [`0.10.0`](https://hub.docker.com/layers/prometheus-nats-exporter/natsio/prometheus-nats-exporter/0.10.0/images/sha256-5400de7cf9cd9fbda4ef3d6f5d236560e43bc6d1bf09b021ce4611d0dc4ff21a?context=explore) to prevent potential security vulnerabilities.

Bump `nats-config-reloader` and `nats-prometheus-exporter` images

---

prow/jobs/incubator/compass/tests/compass-e2e-tests/compass-e2e-tests.yaml
templates/data/generic_component_compass_data.yaml

- 20 minutes seems not to be enough sometimes: https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-incubator_compass/2570/pre-compass-tests/1560516977976414208
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-incubator_compass/2570/pre-compass-tests/1560516977976414208

Bump Compass E2E tests component job timeout

---

prow/jobs/kyma-operator/kyma-operator.yaml
prow/jobs/kyma-watcher/kyma-watcher.yaml
prow/jobs/manifest-operator/manifest-operator.yaml
templates/data/kyma-operator-data.yaml
templates/data/kyma-watcher-data.yaml
templates/data/manifest-operator-data.yaml

Creates Pipelines for Post-Submit actions that run the `build-generic.sh` script for building an image based on SHA.
- post-main-kyma-operator-build
- post-main-manifest-operator-build
- post-main-kyma-watcher-kcp-build
- post-main-kyma-watcher-skr-build
https://github.com/kyma-project/test-infra/issues/5859

Setup operator image build post-submits

---

development/gcbuild/tools/gcbuild-lint/main_test.go
prow/jobs/test-infra/go-validation.yaml

It's a tiny PR that only adds a job which run `go test ./...` on test-infra go codebase on PRs. I kind of got fed up with manually running the tests and I believe we need such job if we want to switch to new build solution, ultimately ditching out legacy scripts.
/area prow

Create job that run unit tests across entire test-infra

---

prow/scripts/cluster-integration/reconciler-e2e-gardener.sh

Reverts kyma-project/test-infra#5959
Analysis is finished and clusters can be cleaned up again.

Revert "Do not cleanup defective Gardener cluster - Analysis of VPN seed issue"

---

prow/scripts/cluster-integration/kyma-integration-k3d.sh
vpath/pjtester.yaml

Change of entry point for execution of all application connector component tests: 
Adjustments to new makefile structure updates made in [Kyma PR 15380 ](https://github.com/kyma-project/kyma/pull/15380)

Updating makefile calls for app connector tests

---

prow/jobs/kyma/kyma-integration.yaml
templates/data/kyma-integration-data.yaml
test-inventory-integration.md
vpath/pjtester.yaml

Restoring following jobs to execute component tests for application connectivity validator:
- pre-main-kyma-integration-k3d-app-conn-validator
- post-main-kyma-integration-k3d-app-conn-validator
Tests executed by pipelines have been merged in: https://github.com/kyma-project/kyma/pull/14912

Restore validator testing pre and post jobs

---

development/kaniko-build/config.go
development/kaniko-build/config_test.go
prow/jobs/test-infra/buildpack.yaml
templates/data/buildpack-data.yaml

During refactoring and moving registry to the cluster config, one value unintentionally got renamed.
/area ci
/kind bug

Fix naming in kaniko-build config.go

---

development/kaniko-build/main.go
prow/jobs/test-infra/buildpack.yaml
templates/data/buildpack-data.yaml

Builds in kaniko fail if multiple kaniko executors try to edit the layer files stored locally. Until we find a better solution I have to disable concurrent builds. Fortunately with caching I believe it won't increase times by too much.
/area ci
/kind bug

Remove concurrent builds from kaniko-build logic

---

prow/scripts/cluster-integration/compass-gke-benchmark.sh

Since September 2022 the 1.21.12 version is no longer provided by GCP.
- Adjust version to latest supported: https://cloud.google.com/kubernetes-engine/docs/release-notes

Update cluster version

---

development/tools/pkg/release/options.go

Program checks if given release changelog name is present as a file if it's not then uses old logic of getting changelog from GCS as fallback. If changelog is present in local filesystem, use this file instead of fetching it from GCS.
/kind feature
/area ci

prefer local changelog file githubrelease

---

development/kaniko-build/config.go
development/kaniko-build/config_test.go
development/kaniko-build/main.go
development/kaniko-build/main_test.go

/kind feature
/area ci
This small update addresses an issue where it is required to push one image to multiple destinations under the same tag. 
Add ability to define `registry` and `dev-registry` field in the config as either *string*, or *sequence* to define multiple registry addresses to push the image. It will not break current config.yaml and will give transitioning to artifact registry desired grace period without any additional tooling.

Implement using multiple repos to push in kaniko-build

---

configs/kaniko-build-config.yaml

This makes some problems with generic-autobumper. It requires more investigation. Probably we will have to remove all images that contain timestamps so our current autobumper solution works
/area ci
/kind bug

Disable timestamp stripping when building images

---

development/kaniko-build/main.go
development/kaniko-build/main_test.go

It's never intended for it to be required, as it only defines the subpath of the image on registry. Remove the check and update tests

kaniko-build: make directory option optional

---

prow/images/buildpack-golang/Dockerfile

Error when building multi-arch image:
```
Error: failed to solve: failed to load LLB: runtime execution on platform linux/arm64 not supported
```
idk if it will work let's see

Install qemu for multi-arch builds

---

prow/jobs/lifecycle-manager/lifecycle-manager.yaml
prow/jobs/module-manager/module-manager.yaml
prow/jobs/runtime-watcher/runtime-watcher.yaml
templates/data/lifecycle-manager-data.yaml
templates/data/module-manager-data.yaml
templates/data/runtime-watcher-data.yaml
vpath/pjtester.yaml

- changes module-manager to only use kaniko builds
- changes runtime-watcher (skr & kcp operators) to only use kaniko builds
- unifies naming of runtime watcher jobs to be suffix based

setup kaniko for module manager and runtime watcher

---

development/image-syncer/external-images.yaml

go 1.19.2 was released.
this is the new alpine image: https://hub.docker.com/layers/library/golang/1.19.2-alpine3.16/images/sha256-45d14bdb069fd5e1fee50160a3e15752038f0fabf339a5ed7f342b84701ed3d6?context=explore

bump to go image to golang:1.19.2-alpine3.16

---

prow/config.yaml
templates/templates/prow-config.yaml

Builds don't work because batches aren't considered as presubmits for tide when it merges PRs. That breaks image building, because it relies on JOB_TYPE=presubmit env variable This will slow down merging a bit, but will fix problem of not merging batches

Disable batch_size_limit for all repos in Kyma

---

prow/images/buildpack-golang/Dockerfile

- Place kubebuilder path at the end of PATH env variable to prevent overriding paths of base image tools
- Resolves #5441

Move kubebuilder path to end of PATH in go-builder

---

development/image-builder/README.md
development/image-builder/main.go
development/image-builder/main_test.go

Closes #6130 
/area ci
/kind deprecation
Remove `--directory` flag to avoid confusion and treat `--name` as go-to flag to define image name with full subpath to image.

Remove `--directory` flag in favour of using `--name`

---

development/image-syncer/external-images.yaml

bump the image of `nats-config-reloader` to `v0.7.4`
https://hub.docker.com/layers/natsio/nats-server-config-reloader/0.7.4/images/sha256-b8c42f0dc7cb4de5749bd1a3040f2e298cbf961397ec85f29c39ad098508faf1?context=explore

bump image nats-config-reloader to v0.7.4

---

development/image-syncer/external-images.yaml

Title says it all.
docker repo: https://hub.docker.com/layers/natsio/prometheus-nats-exporter/0.10.1/images/sha256-37a39c6aa042b203af7e55c5cf7db3858f93f3236b8ad4b66d93769652fdcdc0?context=explore
release notes: https://github.com/nats-io/prometheus-nats-exporter/releases/tag/v0.10.1

bump image of prometheus-nats-exporter to v0.10.1

---

development/image-syncer/external-images.yaml

docker repo: https://hub.docker.com/_/nats/
release notes: https://github.com/nats-io/nats-server/releases/tag/v2.9.5

bump nats server to v2.9.5-alpine3.16

---

development/image-builder/main.go

/kind bug
/area tools
os.DirFS() requires to provide a path to the directory which is treated as FS. At first it was simply "/", which caused issue because env file could not be found. RIght now it opens FS in the build context, so all files in the build context are accessible.

bug: fix logic of getting env files

---

development/image-builder/main.go

/kind bug
/area tools
if build is successful, then return early

bug: add missing return statement at the end of build

---

prow/jobs/incubator/reconciler/reconciler.yaml
templates/data/incubator-buildpack-data.yaml

- Make the failing test optional until the fix arrives
https://github.com/kyma-project/kyma/issues/15994

Make reconciler-cli-kyma-prev-to-last-release-upgrade-k3d optional

---

prow/jobs/lifecycle-manager/lifecycle-manager.yaml
prow/jobs/module-manager/module-manager.yaml
prow/jobs/template-operator/template-operator.yaml
templates/data/lifecycle-manager-data.yaml
templates/data/module-manager-data.yaml
templates/data/template-operator-data.yaml

- Introduce pipelines for template operator
- Rename pipelines of lifecycle- and module-manager
- Since prow does not distinguish between Repositories in the job history if the y have the same naming
- Example: https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pull-lint
This history includes jobs for lifecycle-manager, module-manager, as well as runtime-watcher, because the jobs have the same name

Introduce template operator pipeline

---

prow/cluster/components/crier_deployment.yaml
prow/cluster/components/crier_rbac.yaml
prow/cluster/components/deck_rbac.yaml
prow/cluster/components/halogen.yaml
prow/cluster/components/tide_rbac.yaml
prow/cluster/resources/external-secrets/external_secrets_prow.yaml
prow/cluster/resources/external-secrets/values_prow.yaml
prow/config.yaml
templates/templates/prow-config.yaml

- Bound `crier`, `deck`, `halogen`, `tide` to the `control-plane` GCP service-account
- removed GCP service account credentials from `crier` deployment

Migrate Prow to workload identity

---

prow/jobs/incubator/reconciler/reconciler.yaml
templates/data/incubator-buildpack-data.yaml

- adds missing always run to img-builds for pre/post submits on reconciler image build jobs
[](https://github.com/kyma-project/test-infra/pull/6403)

fix: add always_run to reconciler image build jobs

---

prow/jobs/kyma/kyma-integration-gardener.yaml
templates/data/kyma-integration-gardener-data.yaml

These tests are flaky but are blocking e.g. changes in skr-tests (see https://github.com/kyma-project/kyma/pull/16048) despite only ski-tests are changed and eventing test do not provision any SKR.
- `pre-main-kyma-gardener-gcp-eventing` optional
- `pre-main-kyma-gardener-gcp-eventing-upgrade` optional

Make gcp-eventing and gcp-eventing-upgrade tests optional

---

prow/jobs/kyma/kyma-integration.yaml
templates/data/kyma-integration-data.yaml

- We want to increase the interval for telemetry integration test runs to "every 2 hours" for a couple of weeks to analyse flakiness

Increase test run interval for telemetry-integration-k3d

---

prow/jobs/module-manager/module-manager.yaml
templates/data/module-manager-data.yaml

- Move module-manager up by one level by removing the 'operator' folder
https://github.com/kyma-project/module-manager/issues/156

refactor: remove module-manager 'operator' folder

---

development/image-syncer/external-images.yaml

[image](https://hub.docker.com/layers/library/golang/1.19.4-alpine3.17/images/sha256-f33331e12ca70192c0dbab2d0a74a52e1dd344221507d88aaea605b0219a212f?context=explore)
[rel notes go 1.19.4](https://go.dev/doc/devel/release#go1.19.minor)

bump golang image to 1.19.4-alpine1.17

---

development/custom-image/install-deps-debian.sh

- Switch back Debian 11 to use cgroups v1. Minikube is not compatible with cgroups v2 which is a default version for debian 11.
See #6596

Switch Debian 11 back to cgroups v1

---

prow/jobs/kyma/kyma-integration-gardener.yaml
templates/data/kyma-integration-gardener-data.yaml

This reverts commit fcb84dceea29523032362b7074258e3c197ac883.
- Revert making eventing jobs optional

Revert make gcp-eventing and gcp-eventing-upgrade tests optional

---

prow/jobs/kyma/kyma-integration-gardener.yaml
templates/data/kyma-integration-gardener-data.yaml

- eventing-upgrade currently blocks multiple prs. this pr makes it optional and will be reverted as soon as possible
- ...
- ...

make pre-main-kyma-gardener-gcp-eventing-upgrade optional

---

prow/jobs/kyma/kyma-integration-gardener.yaml
templates/data/kyma-integration-gardener-data.yaml

This reverts commit 979dcc213e65beef95e9601cd98898b18c676daf.
- the test needs to be required again.
- the test was only optional to allow merging a different pr

Revert "make pre-main-kyma-gardener-gcp-eventing-upgrade optional (#6632)"

---

development/gcp/pkg/logging/client.go
development/tools/cmd/usersmapchecker/main.go

- Fixed prowjob logger contructor function to pass correct value for google project id.

Client constructor function was getting log name instead project name.

---

configs/gencred-config.yaml
prow/jobs/test-infra/test-infra-trusted-jobs.yaml
prow/workload-cluster/trusted-workload/gencred-refresher_serviceaccount.yaml

Part 1 of #6622
* Add new jobs that rotate kubeconfigs every 6 hours
* Add trusted workload serviceacount with workload identity mapping
* Add configuration file for all workload clusters - trusted, untrusted and nekton that pushes new kubeconfigs as secrets to the secret manager

Add gencred jobs for workload clusters

---

configs/gencred-config.yaml
prow/cluster/components/crier_deployment.yaml
prow/cluster/components/deck_deployment.yaml
prow/cluster/components/hook_deployment.yaml
prow/cluster/components/prow_controller_manager_deployment.yaml
prow/cluster/components/sinker_deployment.yaml
prow/cluster/resources/external-secrets/external_secrets_prow.yaml

#6622 
* Split one kubeconfig for workload cluster into multiple kubeconfigs
* use KUBECONFIG env for defining path to all kubeconfigs
* update external secrets
* fix gencred-config.yaml naming to follow old names for workloads

Add Prow connection to workload clusters with gencred configs

---

development/image-syncer/external-images.yaml

[image](https://hub.docker.com/layers/library/golang/alpine/images/sha256-27a9653759f44afd08c94418307a26d2db9cf78af12933200bc2ca63c4844316?context=explore#!)
[release notes](https://go.dev/doc/devel/release#go1.19)

Bump golagn image to v1.19.5 multiplatform

---

prow/jobs/incubator/compass/components/schema-migrator/schema-migrator-generic.yaml
templates/data/generic_component_compass_data.yaml

So far Schema Migrator build was only for architecture AMD64 due to used binaries in docker build. We now introduce ARM build for this component.
- ARM build for schema migrator

ARM build for schema migrator

---

development/image-builder/images/buildkit/Dockerfile

Update Buildkit image version to latest available:
https://hub.docker.com/r/moby/buildkit/tags?page=1&name=rootless
- Update buildkit base image version

Update buildkit base image version

---

development/tools/cmd/pjtester/main.go
development/tools/pkg/pjtester/pjtester.go
development/tools/pkg/pjtester/pjtester_test.go

At some point of work pjtester was losing information about authentication, so it was always using anonymous GitHub client.
* Remove usage of bugged GithubClientConfig in favor to use native GitHubClient function from prow.k8s.io
Closes #6728

Fix ProwJob authentication

---

prow/jobs/kyma-project/warden/integration-test.yaml

Since warden requires only simple k8s cluster (no need to use Kyma), I used the ability to run K8s inside ProwJob with k3d. It worked flawlessly. Time - around 2 minutes of execution with entire cluster provision. Size - 8 lines of shell script. We reserve 1Gi of memory for the job, although less should be possible.
ProwJob does the following:
* starts Docker daemon
* provisions k3s cluster with k3d
* installs warden using `make install`
* runs test using `make run-integration-tests`
* destroys k3s cluster
* returns exit value of `make` and fails if command finished with an error
Delta - we have to use privileged mode. This is something that we cannot work around, we have to work with it.

Add warden in-cluster integration test

---

prow/images/golangci-lint/Dockerfile

- Upgrade `golangci/golangci-lint` from `1.51.0` to `1.51.1`
**Reason**
https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pull-lifecycle-mgr-lint is failing with a false positive for the `musttag` linter which was fixed in `golangci-lint` latest image.

Bump golangci-lint image to 1.51.1

---

development/image-builder/main.go
development/image-builder/main_test.go
development/image-builder/sign/sign.go

This PR adds ability to enable specific signer service only for specific ProwJob type. When the signer configuration contains a job-type field, it is considered as CI-based service. Its invocation is only restricted to CI mode for a specific repository, or globally.
* If signer contains a job-type field, and is running in Prow, image-builder will determine if this service should sign an image based on the value of job-type and env variable `JOB_TYPE`
* If signer contains job-type field, but it's not running on CI, image-builder ignores signing using this service
* If signer doesn't contain a job-type field it will be used and enabled by default
This approach allows to pin specific notary service to each of job-types, eg. prod service only for postsubmit jobs, and dev service for all types …

image-builder: pin notary signers to specific job types

---

development/gcp/cloud-run/create-github-issue/create-github-issue.go
development/gcp/cloud-run/search-github-issue/search-github-issues.go
development/gcp/pkg/cloudfunctions/logging.go
development/github/pkg/client/client.go

Search and create github issue services call GitHub API as authenticated user. A token is delivered from secrete manager directly to the cloud run instance and is automatically updated once new version is added in secret manager. However token is not loaded by clients running in cloud run instances, because clients are created at container boot. To use new token, clients will react on 401 bad credentials http error returned by github API. Clients will read token again and replace client instance with new one with new token. Replacement will happen only if new and old tokens are different. Token is stored as hmac+sha256 hash.
Support for 401 bad credentials http error let clients react correctly on planned token rotation as well …

Reauthenticate client on passwd change

---

configs/terraform/secrets-leaks-log-scanner/gcs-bucket-mover.tf
configs/terraform/secrets-leaks-log-scanner/github-issue-creator.tf
configs/terraform/secrets-leaks-log-scanner/github-issue-finder.tf
configs/terraform/secrets-leaks-log-scanner/main.tf
configs/terraform/secrets-leaks-log-scanner/secrets-leak-log-scanner.tf
configs/terraform/secrets-leaks-log-scanner/slack-message-sender.tf
development/gcp/pkg/cloudfunctions/logging.go

Use labels on structured log entries.
Add Terraform config creating gcp log based alerting policy for all log scanner services.
Policy will alert on slack channel on error log messages. Notification will be replied every 6 hours and auto closed after 4 days.
Log messages from golang services will use LogEntry.Labels field instead jsonPayload level field.

Alert when error is logged for secrets leak detector services.

---

development/github/pkg/client/v2/client.go

Moreover parsing flags with empty list of args broke pjtester.
Changes made in GitHub constructor function wre not used in final solution. Moreover parsing flags with empty list of args broke constructing client with flags provided as cli args.

Reverting changes as they were not used in final solution.

---

prow/jobs/btp-manager/btp-manager-build.yaml
templates/data/btp-manager-build.yaml

Presubmit job creating and pushing to registry OCI module image.
- job definition

Presubmit job building module image

---

tekton/deployments/dashboard_release.yaml

tekton dashboard: restrict access to default namespace

---

development/image-syncer/external-images.yaml

remove outdated fluent-bit
- update alpine to 3.17.2
- removed outdated fluenbit image
- ...

update alpine to 3.17.2

---

development/tools/pkg/pjtester/test_artifacts/test-prow-config.yaml
prow/config.yaml
prow/staging/config.yaml
templates/templates/prow-config.yaml

This field is no longer available
```
{"component":"unset","file":"checkconfig/main.go:91","func":"main.reportWarning","level":"warning","msg":"unknown fields or bad config in prow/config.yaml: error unmarshaling JSON: while decoding JSON: json: unknown field \"allow_cancellations\"","severity":"warning","time":"2023-02-22T14:15:34+01:00"}
```

remove `allow_cancellations` field from prow config.yaml

---

prow/scripts/cluster-integration/control-plane-gke-integration.sh

In [PR-2500](https://github.com/kyma-project/control-plane/pull/2500/files) there is a requirement added into Provisioner deployment that it will not start without existence of a secret `kcp-provisioner-database-encryption`. 
This PR adds the secret to resources created in this pipeline.

Add dummy secret for control-plane-gke-integration pipeline required for provisioner

---

prow/jobs/template-operator/template-operator.yaml
templates/data/template-operator-data.yaml

To fix the pipeline failing in [template-operator](https://github.com/kyma-project/template-operator/pull/27) because of signning errors
```
sign images using services signify-dev,signify-prod
sign encountered error: signer init: open /secret-prod/secret.yaml: no such file or directory
```
https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_template-operator/27/pull-build-template-operator/1630456536729915392/build-log.txt

replace local signify-secret config to global kaniko_buildpack

---

development/secrets-rotator/cloud-run/rotate-service-account/rotateserviceaccount.go
development/secrets-rotator/cloud-run/service-account-keys-cleaner/Dockerfile
development/secrets-rotator/cloud-run/service-account-keys-cleaner/serviceaccountcleaner.go
development/secrets-rotator/cloud-run/service-account-keys-cleaner/serviceaccountcleaner_test.go

- Refactored cloud function code to run as cloud-run service.
- Added Dockerfile for building service image.
- Files were copied to the dedicated secret-rotator application directory.

Migrate rotate secrets service account cleaner to cloud run

---

prow/jobs/control-plane/components/kyma-environment-broker/kyma-environment-broker-build.yaml
templates/data/control-plane-build.yaml

at the moment, there are PRs that for some reason require passing run of `post-keb-trial-cleanup-job-build`:
* https://github.com/kyma-project/control-plane/pull/2551
* https://github.com/kyma-project/control-plane/pull/2550
* https://github.com/kyma-project/control-plane/pull/2549

Fix post-keb-trial-cleanup-job-build trigger

---

prow/jobs/btp-manager/btp-manager-build.yaml
templates/data/btp-manager-build.yaml

`pull-btp-manager-build` should always run to create a new PR image for e2e tests.

Fix pull-btp-manager-build to always run

---

development/gcp/cloud-run/gardener-sa-rotate/gardener-sa-rotate_test.go
development/gcp/pkg/pubsub/types.go
development/secrets-rotator/cloud-run/rotate-service-account/rotateserviceaccount.go

- Using a github.com/kyma-project/test-infra/development/gcp/pkg/pubsub.Mesage type for unmarshaling http request body.
- Using a google pubsub Message type as a replacement for kyma-project MessagePayload type. We were duplicating an existing type in upstream package.
- Dumping http request and printing in case of error when reading http request body.

Fixed usage of wrong type to load http request body to.

---

configs/gencred-config.yaml

Go's `time.Duration` does not include `days` parameter, so Days need to be changed to hours.
/priority critical
/kind bug
/area ci

Change error in gencred config

---

prow/scripts/cluster-integration/control-plane-gke-integration.sh
prow/scripts/kyma-testing.sh
prow/scripts/lib/kyma.sh

In #7256 we have upgraded the Kyma Cli version. In the latests version there is no `kyma test` command that the `pre-main-control-plane-gke-integration` relies on. The PR reverts the change from #7256 to make the tests functional again.
- Revert to old CLI in `pre-main-control-plane-gke-integration`

Revert to Old Cli

---

prow/config.yaml
prow/scripts/resources/busola/cluster-busola.yaml
prow/scripts/resources/busola/cluster-kyma.yaml
prow/scripts/resources/reconciler/shoot-template.yaml
prow/scripts/resources/skr-test/shoot-template.yaml
templates/templates/prow-config.yaml

- Revert K8s 1.26.1 to 1.25.6 for Gardener clusters
https://github.com/kyma-project/test-infra/issues/7190

Revert K8s 1.26 for Gardener clusters

---

tekton/deployments/config_defaults.yaml

- Using volumeClaimTemplate as default workspace implementation provided by taskrun. Expecting this will be used the most.
- Aligned default tekton task timeout with timeout of prowjob running on kubernetes agent.
See #6798

Update tekton default config.

---

prow/jobs/modules/internal/serverless-manager.yaml
templates/data/generic_module_data.yaml

- make sure module artefacts are build when module version is bumped
Same as #7378

Include .env in serverless module job triggers

---

prow/jobs/control-plane/components/kyma-environment-broker/kyma-environment-broker-build.yaml
templates/data/control-plane-build.yaml

post-keb-deprovision-retrigger-job-build is missing a label, and the image is not signed. This PR fixes it.
- Add `preset-signify-prod-secret` label

Add missing label for post-keb-deprovision-retrigger-job-build

---

prow/jobs/test-infra/image-syncer.yaml
templates/data/image-syncer-data.yaml

Not used anymore, so not needed.

Remove docker from image-syncer jobs

---

prow/scripts/cluster-integration/compass-gke-benchmark.sh

We (CMP) introduced a new component called ias-adapter which comes with it's own k8s migration job. But because of sequential Compass installations, the compass-gke-benchmark job now fails because it tries to patch the new k8s job (which is immutable)
- delete ias-adapter-migration job before installing Compass

Delete ias-adapter-migration job before installing Compass in compass-gke-benchmark job

---

prow/autobump-config/control-plane-autobump-reconciler-config.yaml

- Update registry reference prefix for reconciler autobump config from `eu.gcr.io/kyma-project` to `europe-docker.pkg.dev/kyma-project/prod`
* https://github.com/kyma-project/lifecycle-manager/issues/523

Update prefix in autobump config to new registry

---

prow/config.yaml

/area ci
/kind feature
This quality gate is to ensure that Tide blocks PR merge unless it contains `area/` and `kind/` labels. For now it will work only for test-infra, because we have automation that manages this label.

Block PR merge when PR has `needs-kind` and `needs-area` labels

---

prow/jobs/istio/istio-integration.yaml

/area ci
/kind feature
Added integration test for istio. Test runs on k3d locally with registry, and runs makefile targets `docker-build docker-push istio-integration-tests`. It's self-contained job and uses current source (eg. current PR code) to execute tests.
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_istio/133/pull-istio-integration/1655927861103562752#1:build-log.txt%3A1002
https://github.com/kyma-project/istio/issues/58

Istio integration tests job

---

CODEOWNERS

Removed neighbors-dev-bot from lines where kyma-project/prow group is present. If bot account was added explicitly it was requested for review because our GitHub settings require review from codeowners. Because bot account is a member of prow group, automated review assignment requested only one additional prow group member for review to reach two reviewers from prow group.
With this change a bot will be explicitly added to the reviewers list only if pull request contains changes in path where kyma-project/prow is not an owner and neighbors-dev-bot is an owner. If the pull request will contain changes for paths where one has kyma-project/prow as owner and second one has a neighbors-dev-bot as owner, only one human member of …

Fix review assignments.

---

task/clone-refs/0.1/clone-refs.yaml

Added workaround that changes file permissions to 777 and sets owner/group to 1000:1000 so files are accessible by non-root users
/area ci
/kind bug

add file permission workaround to clone-refs.yaml

---

prow/jobs/modules/external/keda-manager.yaml
templates/data/generic_module_data.yaml

Updates to match with Keda Manager release naming convention
&
Adds secondary job that builds new image to be used in release process
https://github.com/kyma-project/keda-manager/issues/129

Updated Expression to better match release version and added a secondary job to build the new image

---

CODEOWNERS
prow/jobs/nats-manager/nats-manager-generic.yaml
templates/data/nats-manager-data.yaml

`pull-nats-manager-unit-test` was not getting triggered on nats-manager PRs. The regex pattern needed to be slightly changed to fix the trigger.
The job will now get triggered if the following files are changed:
- {any folder structure}/file.go
- go.mod
- go.sum

Fix trigger for nats-manager unit test job

---

prow/jobs/istio/istio-integration.yaml
prow/jobs/modules/internal/istio-manager.yaml
templates/data/istio-module-data.yaml
vpath/pjtester.yaml

- Run Istio tests on GCP
- https://github.com/kyma-project/test-infra/issues/7564

Istio gcp integration test

---

prow/jobs/test-infra/prow-periodics.yaml
templates/data/prow-periodics-data.yaml

Invalid command name cause image-detector job to fail constantly. This is simple fix for it.
- Remove "-" from command used by image detector prow job

Fix command used by image-detector

---

images/e2e-dind-k3d/init.sh
prow/config.yaml

/kind feature
/area ci
This PR adds additional logic of provisioning k3d cluster with registry inside of e2e-dind-k3d image.
This is roughly based on implementation in https://github.com/kyma-project/test-infra/pull/7741/files
This will give the ability to provide entire k8s environment without additional effort.

Add automatic provisioning of k3d in e2e-k3d image

---

images/e2e-dind-nodejs/Dockerfile
images/e2e-dind-nodejs/init.sh

/area ci
/kind feature
add additional debian-based image that contains nodejs16, docker, k3d and chrome browser. It's meant to be used with Cypress-based UI tests
TODO stays for future reference
#7862

Add initial e2e-dind-nodejs image

---

prow/jobs/test-infra/prow-periodics.yaml
templates/config.yaml
templates/data/prow-periodics-data.yaml

- Add extra-refs, so periodic image detection for scanners can access configs from tes-infra repo

Add extra-refs to image-detector periodic prow job

---

development/image-detector/main.go

Current behavior require list of repositories containing only repos with valid inrepo config, proposed changes change behavior to warn and not fail if inrepo config is not found.
- Warn instead of fail on not found prow in-repo config

Not fail on not found inrepo config

---

prow/jobs/kyma/components/compass-runtime-agent/compass-runtime-agent-tests.yaml

https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-kyma-integration-k3d-runtime-agent is failing constantly right now.
- pre-main-kyma-integration-k3d-runtime-agent not watching installation directory
- ...
- ...

pre-main-kyma-integration-k3d-runtime-agent not watching installation directory

---

images/e2e-dind-k3d/init.sh
images/e2e-dind-nodejs/init.sh

/area ci
/kind bug
For some reason trap does not get executed. Probably TERM also needs to be handled, so I've added it.
Additionally cleanup cleans up only Docker configuration, because k3d runs on this Docker, everything cluster-related will be removed as well.

Adjust cleanup and add TERM to trap

---

images/e2e-dind-k3d/init.sh
images/e2e-dind-nodejs/init.sh

/kind bug
/area ci
/cc halamix2
This should be handled by Linux. Prow's Entrypoint takes care of process signal propagation so everything should be scraped.

Remove cleanup logic

---

images/buildpack-go/Dockerfile
images/e2e-garden/Dockerfile
images/e2e-gcloud/Dockerfile

/kind bug
/area ci
Currently when Prow uses git to copy references, it uses Linux's default mask 0022 and runs git process as root. That means devs cannot interact with the workspace once in ProwJob, because workspace is owned by root user.
This needs to be fixed in Prow's upstream code. I opted to not use rootless user for now.

Do not use rootless user in Prow images

---

prow/jobs/lifecycle-manager/lifecycle-manager.yaml
templates/data/lifecycle-manager-data.yaml

This PR fixed the `run_if_changed` regex can't detect go file under project root folder

fix run if change regex

---

configs/terraform/environments/prod/prow.tf

With this configuration standard-pool should descale when not in working hours. If the load increases, then cluster should autoscale standard nodes. The price is super low ($9 per month) and if it is going to allow scaling down of a cluster outside working hours, then it's a gain.
/area ci
/kind feature

Add one size node pool for small workloads

---

development/pkg/extractimageurls/terraform.go
development/pkg/extractimageurls/terraform_test.go

Prevent adding paths to sec-scanners-config.yaml by requiring tag for images in terraform
- Require tag for images in terraform

Require tag for images in terraform

---

.ko.yaml
.koapps.yaml
prow/jobs/test-infra/ko-build.yaml

/kind feature
/area ci
This PR tackles down problem of managing multiple Dockerfiles where we usually only need to build small image with a single binary. This leverages the usage of ko as main build tool. To build an image/application it's needed to just add its import path to the .koapps.yaml
Then it will be automatically picked up by ko and built in next ProwJob run.

Switch to ko-based build for go applications

---

prow/jobs/modules/internal/serverless-manager.yaml
templates/data/generic_module_data.yaml

/area ci
The buildkit solution needs more refinement. There are problems with running buildkit safely.

Revert unprivileged mode from buildkit jobs

---

.hadolint.yaml
images/alpine/Dockerfile
images/alpine/git/Dockerfile
images/build-images.sh

Pjtester is using git as a binary due to k8s/test-infra implementation (lol). It's needed to include it with pjtester binary because otherwise job fails.
Additionally followed tree structure in builder. Looks like it's working as expected though the script wil need a bit more tweaking. Tree structure building seems to be working just fine :D
/kind feature
/area ci

Add new alpine-git image

---

configs/terraform/environments/prod/provider.tf
configs/terraform/environments/prod/terraform-executor.tf

Require minimal not strict provider versions.
Add role binding on terraform-executor service account need for service account impersonation after authentication through oidc workload identity federation.
/kind chore

Loose provider versions requirements.

---

prow/jobs/test-infra/gcr-cleaner.yaml
prow/workload-cluster/trusted-workload/trusted_workloadidentity_serviceaccount.yaml

/kind feature
/area ci
Simple "cleanup" policies for ACR.
* Removes all untagged images every hour in working days
* Cleans up cache registry at 3:33 every week
* Removes PR images from dev that are older than 30 days

Add gcr-cleaner to clean up ACR

---

prow/workload-cluster/test-pods_LimitRange.yaml

To not starve other processes if their resource usage exceeds requests, or there are no requests at all.
/kind feature
/area ci

Add K8s default limit ranges for pods

---

prow/jobs/kyma/periodics.yaml

To completely deprecate prow-tools
/kind deprecation
/area ci

Split githubissues and call binary directly

---

prow/config.yaml

So they are not taking up the default limits set in LimitRange
/kind chore
/area ci

Set up limits and requests for pod-utils

---

prow/config.yaml

Podutil containers fail to run
/kind flake
/area ci

More limits

---

prow/cluster/resources/gatekeeper-constraints/workloads/allowedImagesProwProwjobsNamespace.yaml
prow/cluster/resources/gatekeeper-constraints/workloads/kymaBotGithubSapTokenTrustedUsage.yaml
prow/cluster/resources/gatekeeper-constraints/workloads/kymaBotGithubSecretTrustedUsage.yaml
prow/jobs/test-infra/gcr-cleaner.yaml

- Add gcr-cleaner to allowed images
- Disable privilige escalation for gcr cleaner
- Fix regexp for pre-main-check-users-map prowjob
/kind bug
/area security
/test all

Fix OPA Gatekeeper warnings

---

prow/scripts/lib/gardener/azure.sh

Looks like a leftover as it's not present in other gardener lib scripts.
/kind bug
/area ci

Remove docker::init from azure.sh

---

prow/autobump-config/dockerhub-autobump.yaml
prow/cluster/components/monitoring/grafana_deployment.yaml
prow/cluster/components/pushgateway_deployment.yaml
prow/cluster/components/web_server_deployment.yaml
prow/jobs/test-infra/prow-periodics.yaml
prow/staging/cluster/monitoring/grafana_deployment.yaml
prow/staging/cluster/pushgateway_deployment.yaml
templates/data/prow-periodics-data.yaml

And experimentally enable autobumping for docker.io nginx. This change consolidates all nginx images used by our workloads. We need to have less images of the same application, so the triaging process will be easier
/area ci
/kind cleanup

consolidate nginx images

---

images/buildpack-go/Dockerfile

It's missing and CGO requires it
/area ci

Add pkgconf

---

prow/jobs/control-plane/components/provisioner/provisioner-integration-test.yaml

Missing /init.sh invoke
/kind bug
/area ci

Fix pre-main-provisioner-e2e-tests

---

images/e2e-dind-k3d/init.sh

Dumb-init changed the place to /usr/bin/dumb-init. The change wasn't reflected in /init.sh
/kind bug
/area ci

bug: Fix missing dumb-init

---

images/e2e-dind-nodejs/init.sh

It was omitted during syncing 2 scripts
/kind bug
/area ci

Fix bad shebang in e2e-dind-nodejs init script

---

prow/config.yaml
prow/jobs/kyma-project/k8s-prow/k8s-prow-periodics.yaml

Fixes `fatal: refusing to merge unrelated histories` and missing config credentials
/kind bug
/area ci

Fix missing configuration for GitHub user and remove --depth=1 from clone

---

prow/config.yaml

Right now kyma repo has horrendous number of branches that are being protected. This slows down branchprotection to hours. This change will disable protecting all branches except release ones and main
/kind chore
/area ci

Update kyma branchprotection rules

---

prow/config.yaml

It incorrectly applies rules that are supposed to be disabled
/kind bug
/area ci

Update branch protection for k8s-prow

---

configs/terraform/environments/dev/artifact-registry/main.tf
configs/terraform/environments/dev/artifact-registry/provider.tf
configs/terraform/environments/dev/artifact-registry/terraform.tfvars
configs/terraform/environments/dev/artifact-registry/variables.tf
configs/terraform/environments/prod/artifact-registry-variables.tf
configs/terraform/environments/prod/artifact-registry.tf
configs/terraform/environments/prod/provider.tf
configs/terraform/environments/prod/terraform.tfvars
configs/terraform/environments/prod/variables.tf
configs/terraform/modules/artifact-registry/README.md
configs/terraform/modules/artifact-registry/main.tf
configs/terraform/modules/artifact-registry/variables.tf
development/secrets-rotator/cloud-run/rotate-service-account/README.md
development/secrets-rotator/cloud-run/service-account-keys-cleaner/README.md
docs/index.md

According to https://github.tools.sap/kyma/backlog/issues/4079 we applied a solution. (PR: https://github.com/kyma-project/test-infra/pull/8479)
Then we realised on 2023-08-10: Due to test-infra basic config, the modules-internal Artifact Registry has been created in wrong project.
Right project: **kyma-project**
Wrong (current) project: **sap-kyma-prow**
- `immutable_artifact_registry` was renamed to `artifact_registry_immutable_tags`
- Some document related changes
- The entire solution uses a dedicated provider
```yaml
provider "google" {
alias   = "kyma_project_provider"
project = var.kyma_project_gcp_project_id
region  = var.kyma_project_gcp_region
}
```
What does this improvement mean?
- You can create multiple artifact registry in a dedicated …

Artifact Registry in a specified project with dedicated provider

---

prow/jobs/incubator/reconciler/reconciler.yaml
templates/data/incubator-buildpack-data.yaml

since this job test cli and reconciler dependencies based on PR, when breaking change introduced, it will potentially make this job fail, it make no sense config it as required job.

make pre-main-reconciler-publish-pr-cli optional

---

prow/jobs/infrastructure-manager/infrastructure-manager.yaml
templates/data/infrastructure-manager-data.yaml

- renames build jobs from cluster inventory to infrastructure manager
- ...
- ...
- https://github.com/kyma-project/infrastructure-manager/issues/9
/area control-plane
/kind cleanup

renames build jobs from cluster inventory to infrastructure manager

---

prow/jobs/modules/internal/application-connector-manager.yaml
templates/data/generic_module_data.yaml

Removed job application-connector operator tests already migrated to GH Actions
Fixed post submit job to build release image for application-connector-manager

Adding postsubmit job to build application-connector-manager

---

prow/jobs/modules/internal/application-connector-manager.yaml
templates/data/generic_module_data.yaml

Remove application-connector module verify jobs after migration to GH Action
Add post submit job to build application-connector module

Remove application-connector verify jobs after migration to GH Action

---

prow/jobs/modules/internal/application-connector-manager.yaml
templates/data/generic_module_data.yaml

The job post-application-connector-module-build was not configured correctly to run as postsubmit. 
This PR contains a fix.

Fix post-application-connector-module-build job to run as postsubmit

---

prow/jobs/modules/internal/application-connector-manager.yaml
templates/data/generic_module_data.yaml

This job is required by GitHub. 
We cannot merge any code without it.

Restore pre-main-application-connector-manager-verify job 

---

prow/jobs/kyma/tests/serverless/serverless-integration-k3d.yaml
prow/scripts/cluster-integration/kyma-serverless-integration-k3d.sh

- remove "-operator" suffix from names used by serverless jobs and scripts - this is part of moving serverless sources from kyma repo to serverless-manager repo
See also #8991

remove -operator suffix from names used by serverless jobs

---

prow/scripts/reconciler/reconciler-e2e-gardener.sh
prow/scripts/reconciler/reconciler-e2e-nightly-gardener.sh

- Since monitoring will be removed from fast-integration soon and serverless has already been removed, `make ci` target of fast-integration will become obsolete and doesn't test anything anymore: We remove fast-integration execution here from all reconciler e2e pipelines

Remove fast-integration from reconciler e2e pipelines

---

prow/scripts/cluster-integration/helpers/eventing.sh

- ensure serverless installed before running eventing tests
https://github.com/kyma-project/kyma/issues/18255

Ensure serverless installed before serverless dependant FIT tests

---

prow/jobs/kyma-project/k8s-prow/k8s-prow-periodics.yaml

This resulted in release job not running because version tag with a 0 on the beginning is not compatible with semver. Change day in tag to be singular digit for beginning of a month.
/kind bug
/area ci

Fix semver tagging for k8s-prow

---

cmd/image-syncer/external-images.yaml

docker: https://hub.docker.com/layers/library/golang/1.21.3-alpine3.18/images/sha256-27c76dcf886c5024320f4fa8ceb57d907494a3bb3d477d0aa7ac8385acd871ea?context=explore
rel notes: https://go.dev/doc/devel/release#go1.21.minor

add golang image 1.21.3-alpine3.18

---

prow/cluster/resources/gatekeeper-constraints/workloads/kymaAutobumpBotGithubTokenTrustedUsage.yaml

- Fix post-test-infra-markdown-index-autobump "Container test is not allowed to use restricted secret" error
https://github.com/kyma-project/test-infra/pull/9179

Fix post-test-infra-markdown-index-autobump secret constrain

---

prow/cluster/resources/gatekeeper-constraints/workloads/signifySecretTrustedUsage.yaml
prow/jobs/kyma-project/serverless-manager/serverless-manager.yaml
templates/data/generic_module_data.yaml

Adjust jobs to work with new serverless-manager's Dockerfile. 
- Remove operations connected to `module-chart` which is removed
- Adjust path to `Dockerfile` 
- Remove unused `job_build_volumes`
https://github.com/kyma-project/serverless-manager/issues/345

Adjust jobs to work with new serverless-manager's Dockerfile

---

prow/jobs/kyma-project/runtime-watcher/runtime-watcher.yaml
vpath/pjtester.yaml

Change the job configuration so that it can build the image from the defined tag.
- Change the tag used to build the image - it should use the tag defined in the repository
- Renamed the job to be more explicit
See: https://github.com/kyma-project/runtime-watcher/issues/134

Enable publishing watcher images with tags

---

prow/jobs/kyma-project/runtime-watcher/runtime-watcher.yaml

Add `--build-arg` to the runtime-watcher prowjob to support explicit binary version for the watcher.
See also: https://github.com/kyma-project/runtime-watcher/pull/147
The expected result:
I want to have the following docker ARG available: `BUILD_VERSION={{ .Date }}-{{ .ShortSHA }}`, e.g: `BUILD_VERSION=v20231107-140215fd`
This should be configured on the **postsubmit** job.
- Add `--export-tags` to the runtime-watcher prowjob. This exposes the internal `default_tag` of `image_builder` as the docker ARG.
https://github.com/kyma-project/runtime-watcher/issues/134

Add version arg to the runtime-watcher prowjob

---

prow/jobs/kyma-project/serverless/serverless.yaml
templates/data/generic_module_data.yaml

Due to moving `hack/ci` to `components/operator` in `serverless` repo we need to adjust paths in serverless jobs.
- Adjust path to `components/operator/hack/ci` in serverless jobs
- Adjust `run_if_changed` regex for serverless jobs
- Adjust path to `components/operator` `make test` target
https://github.com/kyma-project/serverless/issues/345

Adjust serverless jobs to the new Makefile paths

---

images/e2e-dind-k3d/Dockerfile
images/e2e-dind-nodejs/Dockerfile
images/e2e-garden/Dockerfile

/kind bug
/area ci
Bump k8s version to 1.27.5. 1.27.7 is not compatible with Gardener yet
Fixes #9299

switch k8s to 1.27.5

---

cmd/image-syncer/external-images.yaml

This PR bumps the golang image to v`1.21.4`.
https://go.dev/doc/devel/release#go1.21.0

bump go image

---

prow/jobs/kyma-project/cli/cli.yaml
templates/data/cli-data.yaml
vpath/pjtester.yaml

Because of [jobs failing](https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_cli/1847/pull-cli-unit-test/1725054188628480000/build-log.txt) because of OOM (most likely), there's a need to increase memory limits for the involved pods.
```
github.com/kyma-project/cli/cmd/kyma/sync/function.test: /usr/local/go/pkg/tool/linux_amd64/link: signal: killed
[...]
FAIL	github.com/kyma-project/cli/cmd/kyma/sync/function [build failed]
```
- increase memory limit for the Pods running `pull-cli-unit-test` prowjob

feat: Increase cli unit test memory

---

prow/jobs/kyma-project/keda-manager/keda-manager.yaml
prow/jobs/kyma-project/serverless/serverless.yaml
prow/jobs/kyma-project/warden/warden.yaml
templates/data/generic_module_data.yaml
templates/data/warden.yaml

- adapting golangcli-lint targets to work with configuration files for serverless, keda and warden
- unification of jobs using golangci-lint
- add golangcli-lint target for serverless operator

Add golangci config

---

cmd/image-syncer/external-images.yaml

- Add Istio 1.12.0 distroless images to external-images.yaml for image-syncer

Add Istio 1.12.0 distroless images to external-images.yaml for image-syncer

---

prow/cluster/resources/gatekeeper-constraints/workloads/kymaBotGithubSecretTrustedUsage.yaml

Template-operator release requires GitHub bot token for uploading assets to the release in `release-template-operator-assets` prowjob.
*  Add a new constraint to allow access to kyma-bot github token in prowjob.
resolves #9338

OPA constraints update for release-template-operator-assets prowjob.

---

prow/images/golangci-lint/Dockerfile

Add libgit2 to golangci-lint image - libgit2 is included in serverless code and needs to be installed. 
This change replace PR:
https://github.com/kyma-project/test-infra/pull/9394
because:
https://github.com/kyma-project/test-infra/pull/9394#issuecomment-1827524170

add libgit2 to image golangci-lint

---

prow/plugins.yaml

/kind bug
/area ci
plugin needs to respond on additional webhook events to perform automatic labeling

bug: fix cla assistant autolabeling

---

prow/jobs/kyma-project/test-infra/images.yaml

Updated the 'run_if_changed' patterns for building image-builder for more precise reaction to changes. Furthermore, '--export-tags' option was removed for building image-builder as tags are not used in build process.
A post-build job for image-builder was added. Now, every time changes are detected in the specified paths in 'main' branch, the image-builder image will be built automatically. This reduces manual effort and ensures that the latest code changes are incorporated in the image-builder.

Update image-builder run-if-changed and add post-build job

---

.gitleaks.toml
cmd/cloud-run/scan-logs-for-secrets/kodata/gitleaks.toml

We struggle with false positives detection due to name of our docker images (which contains restricted keywords).
This fix that by adding a regex that matches docker images (and it's field tested in our image-detector) to generic-api-key rule's allowlist.
- Exclude docker images from being a secret value.
Will unblock: https://github.com/kyma-project/test-infra/pull/9483

Ignore docker images based on regexp

---

prow/scripts/reconciler/reconciler-e2e-gardener.sh
prow/scripts/reconciler/reconciler-upgrade-kyma2-latest-to-main-gardener.sh

Just leave the test in place to detect cases when the MS is not even starting anymore.

Ignore reconciler results as no non-migrated modules are left

---

prow/jobs/kyma-project/warden/warden-verify.yaml
templates/data/warden.yaml

- rename post CI job for warden to run tests w/o LM
https://github.com/kyma-project/warden/issues/159

Rename post verify target for warden

---

cmd/image-syncer/external-images.yaml

/kind chore
/area service-mesh
istio components 1.20.0-distroless -> 1.20.1-distroless

chore: bump istio to 1.20.1-distroless

---

prow/scripts/reconciler/common.sh
prow/scripts/reconciler/shoot-template.yaml

The [nightly-main-reconciler](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/nightly-main-reconciler/1742335028223807488) is currently failing because of: 
```
machine image version 'gardenlinux:934.8.0' is expired,
```
- Update machine image version of `nightly-reconciler ` related jobs to `934.11.0`

chore: Update nightly-reconciler machine image version

---

prow/jobs/kyma-project/nats-manager/nats-manager-generic.yaml

- changes the regex that triggers the release build job for nats-manager; before it was triggered by a tag with a leading letter like `v1.1.1`. Now it will be triggered by a ticket that only contains the dot-separated integers like `1.1.1`.

changes the regex that triggers the nats-manager-release-build job

---

prow/jobs/kyma-project/control-plane/components/provisioner/provisioner-subscription-cleanup-job-build.yaml

- Changed location of subscription-cleanup-job builds,
- removed `keb` string occurences.
https://github.com/kyma-project/control-plane/issues/3249
https://github.com/kyma-project/control-plane/pull/3248 - the current PR depends on https://github.com/kyma-project/control-plane/pull/3248 and should be merged only after that PR

Refactored Subscription Cleanup Job Location

---

prow/jobs/kyma-project/nats-manager/nats-manager-generic.yaml

In the nats-manager in PR on `release-` branches we need to be able to run `pull-nats-module-build`, otherwise PRs on these branches will always fail: https://github.com/kyma-project/nats-manager/pull/281
- remove the restriction of `pull-nats-module-build` to only run on `main`

remove restrictions on pull-nats-module-build to only run on main

---

prow/jobs/kyma-project/cli/cli.yaml
templates/data/cli-data.yaml

Because of [jobs failing](https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_cli/1899/pre-kyma-cli/1744648467306778624/build-log.txt) due to OOM (most likely), there's a need to increase memory limits for the involved pods.
- increase memory limit for the Pods running `pre-kyma-cli` prowjob
n/a

feat: Increase 'pre-kyma-cli' job memory limit

---

prow/config.yaml

- we newly introduced a e2e test suite for runtime-watcher on PRs
- make it required to pass to enable merge
* https://github.com/kyma-project/runtime-watcher/issues/176

feat: Add runtime-watcher e2e test as required status check

---

prow/cluster/resources/gatekeeper-constraints/workloads/saKymaPushImagesSecretTrustedUsage.yaml

- Allow image-builder images in kaniko and buildkit versions from production registry to use a restricted secret.

Allow image-builder from prod registry to use restricted secret.

---

prow/jobs/kyma-project/test-infra/images.yaml

- Build different image for buildkit. This allows kaniko and buildkit version automatic bumps as they will have different image name thus avoiding a race condition between prowjobs building two different versions of image on the same commit.
When building image in CI, we always add default tag to image build on main. Without separate image name, a kaniko and buildkit versions of the same image would be tagged with default tag. The value of this tag will be different and image which would be build last will be used for autobump image-builder usages causing a race condition problem.

Build different image for buildkit.

---

cmd/image-syncer/external-images.yaml

Upgrade prometheus-nats-exporter image due to the security issues openssl and zlib libs used in it

Ugrade NATs prometheus-nats-exporter Image

---

configs/terraform/modules/security-dashboard-token/security-dashboard-token.tf

We have experience apply job failing due to same name for different cloud run revision
- Add autogenerate name option set to true to securtiy-dashboard token cloud run
/test all
/kind bug

Update security-dashboard-token module to fix autogenerate_revision_name issue

---

prow/jobs/kyma-project/cp-mod-migrator/cp-mod-migrator.yaml
templates/data/cp-mod-migrator.yaml

Two pairs of jobs for PR and main build for Warden compatible images to be run as init containers  for Connectivity Proxy migrator.
**GH repo**
https://github.com/kyma-project/cp-mod-migrator .
https://github.com/kyma-project/kyma/issues/18482

Adding prow jobs to build backup and cleanup images for Connectivity Proxy migrator

---

prow/scripts/reconciler/reconciler-upgrade-kyma2-latest-to-main-gardener.sh

Create namespace `kyma-system` manually, since it will not be created anymore by the old reconciler.
Fixes:
- `pull-control-plane-rec-upgrade-kyma2-stable-to-main-grdnr`

Fix `pull-control-plane-rec-upgrade-kyma2-stable-to-main-grdnr`

---

images/unified-agent/Dockerfile
images/unified-agent/go/Dockerfile
images/unified-agent/nodejs/Dockerfile

- Bump Node to 20.11.0 and Go to 1.21.7 for unified-agent image. Bump of Node is required to fix security scan pipeline for kcp-bolt module.

Bump Node to 20.11.0 and Go to 1.21.7 for unified-agent image

---

prow/jobs/kyma-project/test-infra/images.yaml

Fix trigger for building image-builder images. Builds should be started on pr or push to main branch. This was causing running post prowjobs on dependabot pull requests.

Bulid image-builder on PR or push to main branch

---

prow/jobs/kyma-project/lifecycle-manager/lifecycle-manager.yaml
templates/data/lifecycle-manager-data.yaml

Build pipelines of lifecycle-manager are flakey due to OOM kills.
Example: https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_lifecycle-manager/1312/pull-lifecycle-mgr-build/1759829575723913216/build-log.txt
This increases the requests and limits for 3 build pipelines.
- Set resources for `release-lifecycle-mgr-build`, `main-lifecycle-mgr-build` and `pull-lifecycle-mgr-build` to:
```
request_memory: 8Gi
request_cpu: 2
limits_memory: 16Gi
limits_cpu: 4
```

fix: Increase resource limits for LM build pipelines

---

.github/workflows/pull-plan-prod-terraform.yaml
configs/terraform/environments/prod/terraform-service-accounts.tf

- Add missin iam. to role binding for terraform planner
- Switch github plan workflow to terraform planner service account
/kind bug

Fix terraform planner workload role

---

prow/jobs/kyma-project/control-plane/components/provisioner/provisioner-integration-test.yaml

There is problem with this job - we disable it temporary until we fix the job

Make job pre-main-provisioner-e2e-tests optional

---

cmd/image-builder/github-workflow-integration.md

During the work on #9976 we have learned that OIDC token doesn't contain all required data to clone proper source code version in oci-image-builder pipeline. This is a blocker for image-builder github workflow integration. This proposal describe how we can use a reusable workflow to collect all required data and pass them in secure way to the oci-image-builder pipeline.

Update docs with details about reusable workflow.

---

prow/cluster/components/cla-assistant.yaml
prow/cluster/resources/gatekeeper-constraints/prow/allowedImagesProwNamespace.yaml
sec-scanners-config.yaml

Gardener moved their images from container registry to artifact registry, so your image of `cla-assistant` is not updated anymore.
- Update image location of `cla-assistant` to the current one (see [here](https://github.com/gardener/ci-infra/blob/03e50185e1ea0e3bb868727499385b36897f806a/config/prow/cluster/cla_assistant_deployment.yaml#L26C16-L26C104)). 

Update image location of `cla-assistant`

---

images/e2e-dind-k3d/test.sh
images/e2e-dind-nodejs/test.sh

/kind bug
/area ci
It seems that running dockerd inside docker-in-docker (docker-in-docker-in-docker?) was a bad idea and resulted in some flakiness where docker ps could not be executed.
Instead, run simple binary existence check without checking if dockerd starts properly until better solution comes to mind.

bug: remove running dockerd in dind-enabled image test

---

images/e2e-dind-k3d/Dockerfile
images/e2e-dind-k3d/init.sh
images/e2e-dind-k3d/test.sh
images/e2e-dind-nodejs/init.sh
images/e2e-dind-nodejs/test.sh

/kind bug
/area ci
In alpine 3.18 and earlier, `iptables` is a symlink to `iptables-legacy`, and in alpine 3.19 `iptables-nft` is the default iptables backend.
https://github.com/docker-library/docker/issues/463
https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.19.0
Docker doesn't work with `nftables` and it was somehow omitted during update.
* Revert removing tests (never remove tests)
* Rewrite checking if docker is enabled to check error code instead of relying on socket response
* Disable NFT backend using ENV variable in alpine Dockerfile.

bug: use iptables-legacy docker in dind-enabled image

---

prow/jobs/kyma-project/docker-registry/docker-registry-build-operator.yaml
prow/jobs/kyma-project/docker-registry/docker-registry-release.yaml
templates/data/docker-registry.yaml

Remove args from `dockerregistry-operator` `dockerfile` because we deleted it in `Docker-Registry` [repo](https://github.com/kyma-project/docker-registry/pull/1/files#diff-ea228318a371bf873e143fb48c41e2f4e66fe83e137ff509d966935e789e11c7R2-R29) 
- Remove args from `dockerregistry-operator` dockerfile
https://github.com/kyma-project/serverless/issues/847

Remove args from dockerregistry-operator dockerfile

---

prow/jobs/kyma-project/test-infra/buildpack.yaml

- Add preset-signify-prod-secret: "true" for post ginkgo image build job
- Add custom tag with use of value from env file for post ginkgo image build job
- ...
https://github.com/kyma-project/test-infra/issues/10413

Add preset-signify-prod-secret and custom tag for ginkgo image

---

prow/jobs/kyma-project/serverless/serverless-release.yaml
templates/data/serverless.yaml

- Add full sha tag for release serverless operator build job
- ...
- ...
Failing tests on release branch

Add full sha tag for release serverless operator build job

---

prow/config.yaml
prow/plugins.yaml

As CMP(UCL) is moving the CI outside of Prow, initial steps are made to provide the transition. The first step being extracting the E2E tests and smoke tests outside of Prow (https://github.com/kyma-project/test-infra/pull/10435). Doing this requires us to block the auto-merging and to add the branch protection to be up-to-date with main branch.
- Enable branch protection to be up-to-date with main branch
- Allow auto-merging only when three labels `lgtm`, `approved` and `ok-tested` are present

Change Tide configurations for compass and ord-service

---

images/e2e-gcloud/Dockerfile

…present.
Following docker-credential-gcr docs, removing vulnerable component as it should not be used.
"Note: docker-credential-gcr is primarily intended for users wishing to authenticate with GCR in the absence of gcloud, though they are [not mutually exclusive](https://github.com/GoogleCloudPlatform/docker-credential-gcr?tab=readme-ov-file#gcr-credentials). For normal development setups, users are encouraged to use [gcloud auth configure-docker](https://cloud.google.com/sdk/gcloud/reference/auth/configure-docker), instead."

Remove docker-credential-gcr

---

images/buildpack/Dockerfile

- add the `binutils-gold`  package to the buildpack image to avoid [this issue](https://github.com/mattn/go-sqlite3/issues/1164) and [this issue](https://github.com/golang/go/issues/22040)
- fix the `post-kyma-cli` job in the `cli` repo ([example](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/post-kyma-cli/1792465912457072640) run)

Add the `binutils-gold` to the buildpack base

---

prow/config.yaml

- Don't manage cli branch protection
- https://github.com/kyma-project/cli/pull/2101

Don't manage cli branch protection

---

configs/autobump-config/test-infra-autobump-config.yaml

- Add missing buildkit-image-builder image to test-infra-autobump-config.yaml

Add buildkit-image-builder to test-infra-autobump-config.yaml

---

prow/jobs/kyma-project/compass-manager/build.yaml

`Compass Manager` must use a semantic version in Docker images.
- Prow post job that builds `CM` release image with semantic version tag
https://github.com/kyma-project/compass-manager/issues/153

Semantic versioning in Compass Manager release images

---

.github/workflows/image-builder.yml

I decided to extract fixes for workflow from #10860 to clearly see which PR fixes which issue.
- Merge jobs into build-image
- Resolve "action.yml not found" error

Fix reusable workflow for oci-image-builder

---

.github/workflows/image-builder.yml
.gitignore
configs/terraform/environments/prod/.terraform.lock.hcl
configs/terraform/environments/prod/gcp-workfload-identity-federation-variables.tf
configs/terraform/environments/prod/gcp-workfload-identity-federation.tf
configs/terraform/environments/prod/github-com.tf
configs/terraform/environments/prod/gitleaks.tf
configs/terraform/environments/prod/image-builder-variables.tf
configs/terraform/environments/prod/image-builder.tf
configs/terraform/environments/prod/provider.tf

- Read ADO PAT from GCP Secret Manager in image-builder reusable workflow.
- Authenticate in GCP using WIF.
- Add Terraform config for image-builder dedicated GCP and GitHub resources.
See: #10702

Read ado pat from gcp secret manager in image-builder reusable workflow.

---

configs/terraform/environments/prod/image-builder-variables.tf

Fix reusable workflow name in a Terraform variable. The name of a workflow is not a file name.

Fix reusable workflow name. The name is not a file name.

---

configs/terraform/environments/prod/gcp-workfload-identity-federation.tf
configs/terraform/environments/prod/image-builder-variables.tf
configs/terraform/environments/prod/image-builder.tf

Grant direct access to the secret manager secret for wif principalSet.
Use attribute.reusable_workflow_ref in principal for granting access to the image-builder-ado-pat secret in secret manager.
We can't use a standard subject based mapping as it contains the name of a workflow, which is unknown and should not be limited. The workflow name is the name of workflow where users will call our reusable workflow. We don't want to have define separate mapping for each such workflow as it will not scale at all.
Additionally, following google recommendations, granting access to the secret directly to the principal instead through service account impresonation.

Use reusable workflow ref and sha in google wif

---

.github/actions/image-builder/action.yml
.github/workflows/image-builder.yml
cmd/image-builder/main.go
cmd/image-builder/main_test.go

- Generate list of built images based on ADO logs
See #9978

Generate output with list of images built by ado

---

cmd/image-builder/main.go
cmd/image-builder/main_test.go

- Add function to validate dockerfile provided for ADO backend
- Add support for detecting usage of `/workspace` working directory
- Add meaningfull error message with links to kaniko issues and proposed solution
See https://github.com/GoogleContainerTools/kaniko/issues/2192
See https://github.com/GoogleContainerTools/kaniko/issues/3176

Detect workspace workdir and provide error

---

cmd/image-builder/main.go
cmd/image-builder/main_test.go

- Fix improper handling of dockerfile path, treat it relative to context instead of as a absolute path

Fix validation of dockerfile

---

cmd/azuredevops/smoke-tests/smoke-tests.go
cmd/image-builder/main.go
configs/kaniko-build-config.yaml
pkg/azuredevops/pipelines/pipelines.go
pkg/azuredevops/pipelines/pipelines_test.go

- Add configurable refresh interval
Fixes #10080
FIxes #10414

Add retry and refresh config

---

cmd/image-builder/main.go

Fixing an image builder reusable workflow images output is empty bug.
- Fixed using local **logs** variable when getting logs from ado. The outer scope variable which was used to search for built images was empty.
- Added checking errors returned from functions setting GitHub outputs.
- Added info logging to track setting GitHub outputs progress.

Fix empty ado logs used to extract built images.

---

cmd/image-builder/main.go
cmd/image-builder/main_test.go
pkg/azuredevops/pipelines/templatesParams.go
pkg/azuredevops/pipelines/templatesParams_test.go

image-builder client always send Tags parameter as base64 encoded string. After switching an oci-image-builder pipeline to always expect Tags parameter as base64 encoded, the additional EncodedTags parameter wont be needed.

Remove EncodedTags param

---

cmd/tools/gcrcleaner/main.go
go.mod
go.sum

- Fix error from https://github.com/kyma-project/test-infra/pull/11038
Fixes https://github.com/kyma-project/test-infra/pull/11038

Bump go-containerregistry to 0.19.2

---

configs/terraform/environments/dev/secrets-rotator/terraform.tfvars
configs/terraform/environments/prod/terraform.tfvars

Often gitleaks misdetec image tag as generic-api-key. 
- Add gitleaks allow to images in tfvars to solve issue.
See: https://github.com/kyma-project/test-infra/pull/11188

Add gitleaks allow to terrform vars

---

cmd/image-syncer/external-images.yaml

- add python:3.12.2-slim-bullseye to external images
- get the sha256 using:
```
docker run --rm mplatform/manifest-tool inspect "python:3.12.2-slim-bullseye" | grep "Digest: sha256" | head -n 1
```

chore: add 3.12.2-slim-bullseye image

---

.github/workflows/pull-image-builder-test.yml

We can't checkout pull request head in the same job where we call reusable workflow. Testing here which version of repo a reusable workflow will use for run.
IssuE: #11614

Test what version of reusable workflow a run will pick up.

---

prow/jobs/kyma-project/template-operator/template-operator.yaml

- template-op-main-build should only run on main

chore: Run template-op-main-build only on main

---

prow/jobs/kyma-project/third-party-images/third-party-images.yaml

- Delete build Prow jobs for cloudsql-proxy
https://github.com/kyma-project/test-infra/issues/11711

Delete build Prow jobs for cloudsql-proxy

---

.github/workflows/pull-sync-external-images.yml

We will maintain a file in main branch only.
Change path definition. Trying to fix the workflow was not triggered on pr event.

Sync images with external-images.yaml on main branch

---

.github/workflows/pull-sync-external-images.yml

Fix error "invalid value workflow reference: cannot specify version when calling local workflows"

Fix sync images workflow does not start

---

.github/workflows/image-syncer.yml

This must be done in reusable workflow to make sure we work with correct list images to sync
Force dry-run mode for runs on pull requests. For push events the values is taken from input.
See #11384

Checkout correct code version for event type. 

---

.github/workflows/image-syncer.yml

The `mergable` field is not required and was always empty.
See #11384

Verify merge commit sha 

---

.github/workflows/image-syncer.yml

Path to google credentials files is passed as variable not secret.
See #11384

Use env variables instead secret

---

.github/workflows/image-syncer.yml

Fixing permission denied error when opening mounted credentials file in docker container.
See #11384

Mount cred.json as read only and with proper context.

---

.github/workflows/image-syncer.yml

KO uses non root user for it's base image. The file must be readable for container user.
See: #11384

Set gcp credentials file read only for all

---

cmd/image-syncer/external-images.yaml

- Remove amd64Only: true flag from image syncer external-images.yaml when it is not needed
- Remove no longer needed images for sync
https://github.com/kyma-project/test-infra/issues/11712

Remove amd64Only flag from external-images.yaml when it is not needed

---

cmd/image-syncer/main.go

Support using access token as bearer token.
See #11384

Support bearer access token authentication.

---

.github/workflows/push-sync-external-images.yml

Added workflow to sync images on push event.
Removed setting dry-run for pr, it is forced to true in reusable workflow.
See #11384 
Depends on #11867

Workflow to sync images on push event

---

cmd/image-syncer/main.go
cmd/image-syncer/util.go
cmd/image-syncer/util_test.go
cmd/image-url-helper/cmd/promote.go
pkg/image-url-helper/promote/externalsyncer.go
pkg/imagesync/common.go

- Do not read a terget repo prefix from yaml file. This must not be controlled by users when using in prod scenario
- The flag has default value europe-docker.pkg.dev/kyma-project/prod/external/
See #11384

Set target repo prefix with flag

---

configs/terraform/environments/prod/image-syncer.tf

The image-syncer run on push event is failing because no permissions to use a service account. The IaC is granting wrong role on a service account for WIF identity.
See #11384

Use correct role to impersonate a service accounts

---

.github/workflows/push-update-security-config.yaml

- Configure git to use github actions identity as default commiter (it's overriden by autobumper)
See: #9767

Set github-actions identity as defautl committer for image-detector

---

.github/workflows/push-update-security-config.yaml

To prevent issues when pushing changes to the autobumper fork, we need to set default commiter.
Ideally it should be the same user as owner of the fork. To achieve that, we need to extract information before actuall bumper run.
- Use autobump config to extract information about committer and set it as default commiter
See: #9767

Extract default committer from autobump config

---

.github/workflows/push-update-security-config.yaml
sec-scanners-config.yaml

As stated in https://stackoverflow.com/a/69979203/23148781, github silently pass $GITHUB_TOKEN in Authorizaiton header during some git operation. That behavior is causing push error when, autobumepr try to push changes into kyma-bot testinfra fork.
- Prevent siletnly pass GITHUB_TOKEN in authorization
See: #9767

Prevent siletnly pass GITHUB_TOKEN in authorization header

---

.github/workflows/pull-ex-buildx-images.yml

- Implement a GitHub workflow which builds images in tree order
- ...
- ...

Simplify and consolidate image building - Adapt buildx to GH workflow

---

prow/config.yaml

- Remove tide job from lifecycle-manager, runtime-watcher & template-operator
- Remove required status-checks config from lifecycle-manager, runtime-watcher & template-operator

chore: Remove tide and status check config from jellyfish components

---

cmd/image-builder/README.md

- Update image-builder README.md for schedule event and signing with Signify
https://github.com/kyma-project/test-infra/issues/11890

Update image-builder README.md for schedule event and signing with Signify

---

configs/terraform/environments/prod/kyma-bots-secrets-variables.tf
configs/terraform/environments/prod/kyma-bots-secrets.tf

In preparation to prow removal.
Both secrets has same permisisons set already, so it's time to update the name in the github vatiable.
- Rename terraform variables to more descirbe purpose and difference between `workloads_defaults_kyma-autobump-bot-github-token` and `kyma-autobump-bot-github-token`.
- Rename prow related variables to contain prow in the name to easy identification during removal process,

Rename autobump token secret for github workflows

---

.github/workflows/autobump-images.yml
.github/workflows/image-autobumper.yml

- Rename `reusable-image-autobumper` to `image-autobumper` to keep consistency
- Rename `access_secrets` to `secrets` step id to keep consistency
See: #12056

Rename image-autobumper reusable workflow, fix secret reference

---

pkg/github/bumper/bumper.go

- Rewrite `gitPush` function to correctly set refspecs.
See: #12056

Update image-autobumper to correctly utilize go-git

---

configs/terraform/environments/prod/output.tf
configs/terraform/environments/prod/provider.tf
configs/terraform/environments/prod/secrets-rotator.tf
configs/terraform/environments/prod/service_accounts.tf
configs/terraform/environments/prod/terraform-executor.tf
configs/terraform/environments/prod/variables.tf
pkg/tools/pjtester/test_artifacts/test-prow-config.yaml
prow/config.yaml
prow/jobs/kyma-project/test-infra/periodics.yaml

- Remove occurencies of "sap-kyma-prow-workloads" in configs
- ...
- ...
https://github.com/kyma-project/test-infra/issues/9771

Remove unused project mentions

---

cmd/oidc-token-verifier/main.go
pkg/oidc/oidc.go
pkg/oidc/oidc_test.go

Due to long queued time of ADO pipelines GitHub oidc tokens passed from Image builder GitHub Actions are expiring. This causes failed image builds. To prevent failed builds when high load on ADO is observed oidc token verifier will verify oidc tokens with extended expiration time.
Example error in failed ADO run: https://dev.azure.com/hyperspace-pipelines/kyma/_build/results?buildId=7329713&view=logs&j=3eaab1e8-b99d-54c2-e3b9-c8d721213979&t=94b89c64-0a6c-5eb1-9ee6-a00128da7d80&l=33
- Verify oidc token against extended expiration time. Added function for this verification.
- Split oidc token standard verification and claims verification. These are two separate functions.
- Added flag for extended expiration time value to make it …

Verify oidc token against extended expiration time

---

cmd/oidc-token-verifier/main.go
pkg/oidc/oidc.go
pkg/oidc/oidc_test.go
pkg/oidc/oidc_unit_test.go

Skip expiry check and run expiration check with 10 minutes expiration time by default for all tokens.
Added options to set expiry check and expiration time values.
Verify method runs own expiration check if upstream expiry check is skipped.
Added expiration check verification.
Applying options only if provided. This allows better logging.
Print oidc verifier config in log messages
Cleanup code comments and unused flags.
Renaming cobra command function to better represent its purpose.

Run expiration check with extended time for all tokens

---

cmd/cloud-run/signifysecretrotator/Dockerfile

To keep consistent with our images switch image from python slim (debian based) image to alpine base image.
During creation of the tool, I used slim image because I cannot find alpine based on image on the docker hub page.
- Rename based image from `python:3.12.6-slim` to `python:3.12.7-alpine3.20`.
See: #12100

Switch signify secret rotator to alpine base image

---

configs/terraform/environments/prod/iam-variables.tf
configs/terraform/environments/prod/iam.tf
configs/terraform/environments/prod/iamt-variables.tf
configs/terraform/environments/prod/service_accounts.tf

Add `logging.viewer` role to identity `kyma_developer_admin` to allow access to audit logs in `kyma-project` GCP project. Using predefined class instead of custom one is dictated that I cannot find list of exact permissions to allow see the logs. See: https://cloud.google.com/logging/docs/audit#roles
- Remove `gcr-cleaner` service account used by Prow.
- Add configuration for `kyma_developer_admins` identity on `kyma-project` GCP project. 
See: #9765

Setup access to audit logs for kyma-project admins

---

configs/terraform/environments/prod/iam.tf

- Add `roles/logging.privateLogViewer` role for GCP project admins
See: #9765

Add required role to see data access logs

---

.github/workflows/pull-go-lint.yaml
pkg/github/bumper/bumper.go

Reverts kyma-project/test-infra#12068
Restore previous version until https://github.com/kyma-project/community/pull/946 is merged
Automaticall bumps are disabled since https://github.com/kyma-project/test-infra/pull/12164

Revert "actions(deps): bump golangci/golangci-lint-action from 6.1.0 to 6.1.1"

---

.github/actions/image-builder/action.yml
.github/workflows/image-builder.yml

- Add option to run image builder with access to go internal modules

Add option to use go internal modules in github actions

---

.github/actions/image-builder/action.yml
cmd/image-builder/main.go
pkg/azuredevops/pipelines/templatesParams.go
pkg/azuredevops/pipelines/templatesParams_test.go

- Rename use-go-internal-modules to use-go-internal-sap-modules

Rename use-go-internal-modules to use-go-internal-sap-modules

---

pkg/securityconfig/securityconfig.go
sec-scanners-config.yaml

- Add rc-tag in the security config pointing to the [rc-tag](https://github.com/kyma-project/test-infra/releases/tag/rc-tag) to test the migration to the Checkmarx One scanner.
- Adjust code to not remove rc-tag from security config by image detector as it was done in https://github.com/kyma-project/test-infra/pull/12346
https://github.com/kyma-project/test-infra/pull/12345

Add rc-tag in the sec-scanners-config.yaml

---

cmd/image-builder/image-builder.md

- Add description of handling go internal modules in ADO backend.

Add description of Go internal modules

---

cmd/image-builder/config.go
cmd/image-builder/main.go
pkg/azuredevops/pipelines/templatesParams.go

- Add support for merge group in image-builder
See: #12116

Add support for merge group in image-builder

---

pkg/securityconfig/securityconfig.go

- Add CheckmarxOne to structure
- ...
- ...

Add CheckmarxOne to security-config structure

---

cmd/image-syncer/README.md
cmd/image-syncer/main.go
pkg/imagesync/common.go

- Remove image-syncer amd64Only flag
- Sync the whole index if possible. Otherwise, sync a single image.
https://github.com/kyma-project/test-infra/issues/11712

Remove image-syncer amd64Only flag

---

cmd/oidc-token-verifier/main.go

We must log information which client and issuer requested an image build. We are going to support three different oidc providers, each with it's uniq clients. Image builder execution must provide audit logs about callers identity.
- Adding context to the logger with issuer url, client id and github url.

Added logger context with details about token issuer.

---

pkg/oidc/oidc.go
pkg/oidc/oidc_test.go

SRE is running an image-builder in Jenkins. The Jenkins and its OIDC provider does not provide a claim with Jenkins pipeline reference. It's SRE team responsibility to restrict access to oidc provider and allow only certain pipeline to build images. The SRE issuer does not provide job workflow ref and this calim is not validated when oidc token is verified.
- Disable job workflow ref claim verification is it's not defined in trusted issuer.
- Added SRE issuer to the trusted issuers.

Add sre oidc provider to the trusted issuers.

---

cmd/image-builder/main.go
go.mod

Currently OIDC token is set in authorizaiton parameter only for Github Actions, we need to set it always to avoid confusions.
The fix implementation was due to some security concerns about leaking the token, but now it's causing confusions. To avoid that let's move repsonsibility for token on user.
- Update condition to check if oidc token is provided instead of if client run in github actions

Set authorization always when oidc token is provided

---

pkg/imagebuilder/report.go
pkg/imagebuilder/report_test.go

SRE wants to know whether image was pushed even if overall status is failed, this change adds that information to build report.
- Add IsPushed field in the buidl report file

Add status of pushing images to registry

---

pkg/imagebuilder/report.go
pkg/imagebuilder/report_test.go

When fectching the logs from API, we receive timestamps that was interferring with current solution.
Strip it out with simple regex right before parsing the logs to find the reprot string.
- Replace timestamps with empty string

Strip timestamps before searching report string

---

.github/actions/image-builder/action.yml
.github/workflows/autobump-docs-index-md.yml
.github/workflows/autobump-security-config.yaml
.github/workflows/image-syncer.yml
.github/workflows/pull-validate-kaniko-build-config.yml
configs/terraform/environments/dev/secrets-rotator/terraform.tfvars
configs/terraform/environments/prod/terraform.tfvars
configs/terraform/modules/cors-proxy/cors-proxy.tf
configs/terraform/modules/github-webhook-gateway/github-webhook-gateway.tf
configs/terraform/modules/secrets-leaks-log-scanner/gcs-bucket-mover.tf
configs/terraform/modules/secrets-leaks-log-scanner/github-issue-creator.tf
configs/terraform/modules/secrets-leaks-log-scanner/github-issue-finder.tf
configs/terraform/modules/secrets-leaks-log-scanner/secrets-leak-log-scanner.tf
configs/terraform/modules/security-dashboard-token/security-dashboard-token.tf
prow/cluster/components/automated-approver_external-plugin.yaml
prow/cluster/resources/external-secrets/external_secrets_checker_prow.yaml

Reverts kyma-project/test-infra#12620

Revert "Update testimages as needed"

---

cmd/image-builder/main.go
pkg/imagebuilder/report.go
pkg/imagebuilder/report_test.go

- Do not search for newliens characters
Fixes: #12622

Fix regex used to retrieve report

---

pkg/securityconfig/securityconfig.go
pkg/securityconfig/securityconfig_test.go
sec-scanners-config.yaml

Due to recent changes in security tools names, we want to update the security config to reflect that changes.
- Add custon UnamrshalYAML method to unmarshal both types in config
- Add test for new structure

Rename fields in security config, support both names by custom unmarshal

---

cmd/external-plugins/automated-approver/README.md
cmd/external-plugins/automated-approver/plugin.go
cmd/external-plugins/automated-approver/plugin_test.go
pkg/image-url-helper/missing/missing_test.go

- Remove tide from the Automated Approver tool
https://github.com/kyma-project/test-infra/issues/11628

Remove tide from Automated Approver

---

.github/workflows/build-cors-proxy.yml
.github/workflows/build-create-github-issue.yml
.github/workflows/build-dashboard-token-proxy.yml
.github/workflows/build-externalsecretschecker.yml
.github/workflows/build-github-webhook-gateway.yml
.github/workflows/build-image-url-helper.yml
.github/workflows/build-markdown-index.yml
.github/workflows/build-move-gcs-bucket.yml
.github/workflows/build-scan-logs-for-secrets.yml
.github/workflows/build-search-github-issue.yml
.github/workflows/build-usersmapchecker.yml
.github/workflows/buildx-images.yml
.github/workflows/pull-build-image-autobumper.yaml
.github/workflows/pull-build-image-builder.yml
.github/workflows/pull-build-image-detector.yml
.github/workflows/pull-build-image-syncer.yml
.github/workflows/pull-build-oidc-token-verifier.yml
.github/workflows/pull-build-rotate-service-account-keys.yml
.github/workflows/pull-build-service-account-keys-cleaner.yml
.github/workflows/pull-build-signify-secret-rotator.yml
.github/workflows/pull-build-slack-message-sender.yml
.github/workflows/push-build-image-autobumper.yaml
.github/workflows/push-build-image-builder.yml
.github/workflows/push-build-image-detector.yml
.github/workflows/push-build-image-syncer.yml
.github/workflows/push-build-oidc-token-verifier.yml
.github/workflows/push-build-rotate-service-account-keys.yml
.github/workflows/push-build-service-account-keys-cleaner.yml
.github/workflows/push-build-signify-secret-rotator.yml
.github/workflows/push-build-slack-message-sender.yml

After changing a default permissions for default GITHUB_TOKEN in GH Actions we must set them explicit on calling workflow level. Otherwise a workflow that calls image-builder reusable workflow will not be triggered due to insufficient token permissions.
This PR fixes building images by adding write permissions for the default token.

Fix building images by adding write permission for the default token

---

configs/terraform/environments/prod/artifact-registry-variables.tf
configs/terraform/environments/prod/artifact-registry.tf
configs/terraform/environments/prod/terraform.tfvars
configs/terraform/modules/artifact-registry/main.tf
configs/terraform/modules/artifact-registry/variables.tf

Existing artifact registry terraform module was setting repoAdmin permissions for service accounts specified in variable for write access. The module was setting location based on authenticated client location if no value was provided in the config. Updated module to behave more predictable.
Remove default values coming from authenticated client.
Update module to allow setting writer access.
Rename resources in module to correctly indicate real resource. Added validation for variables values.
Set default values for module variables providing lists of service accounts. It's not required anymore to define SAs for read access.
Config changes cause destroy of IAM permissions on artifact registry and recreation the same rights with …

Improve artifact-registry module naming and default values.

---

configs/terraform/environments/prod/artifact-registry-variables.tf
configs/terraform/environments/prod/artifact-registry.tf
configs/terraform/environments/prod/modules-submission-variables.tf
configs/terraform/environments/prod/modules-submission.tf
configs/terraform/modules/artifact-registry/main.tf
configs/terraform/modules/artifact-registry/variables.tf

**Description:**  
This pull request introduces Terraform configurations for creating the `dev-kyma-modules` and `kyma-modules` repositories.
Additionally, it includes improvements for better maintainability and scalability of the codebase, such as:  
- Modularizing artifact registry configurations.  
- Adding new variables (e.g., `cleanup_policies`, `repoAdmin_serviceaccounts`) to enhance configurability.  
- Improving validation and error handling for multi-region and non-multi-region setups.  
- Addressing technical debt by moving repetitive configurations into reusable modules.  
These changes aim to enhance clarity, reduce potential misconfigurations, and improve the overall maintainability of the infrastructure code.
Parent: #12816

Add Terraform Configuration for dev-kyma-modules and kyma-modules Repositories  

---

cmd/image-builder/main.go
cmd/image-builder/main_test.go
pkg/azuredevops/pipelines/templatesParams.go
pkg/azuredevops/pipelines/templatesParams_test.go

Default value is set during template parameters preparation as image-builder client will be reduced in [#12850](https://github.com/kyma-project/test-infra/issues/12850). We cannot set default value for `flagSet.Var` function and no other flag type is suitable for our needs.
Support in workflows will be added in separate PR together with changes from #12939 as bot hrequire image bump before.
- Add support for platform parameter in oci image builder
See: https://github.com/kyma-project/test-infra/issues/12829

Add support for multiple platform in image builder client

---

.github/workflows/build-automated-approver.yml
.github/workflows/build-cors-proxy.yml
.github/workflows/build-dashboard-token-proxy.yml
.github/workflows/build-github-webhook-gateway.yml
.github/workflows/build-image-url-helper.yml
.github/workflows/build-markdown-index.yml
.github/workflows/build-usersmapchecker.yml
.github/workflows/pull-build-image-autobumper.yaml
.github/workflows/pull-build-image-detector.yml
.github/workflows/pull-build-image-syncer.yml
.github/workflows/push-build-image-autobumper.yaml
.github/workflows/push-build-image-detector.yml
.github/workflows/push-build-image-syncer.yml

This pull request removes the `print-image` job from multiple GitHub Actions workflow files. The `print-image` job was previously used to print built image information after the `build-image` step. At present the image-builder reusable workflow prints all built images in a workflow summary. This cleanup simplifies the workflows, decrease execution time and cost by eliminating unnecessary steps.
* Removed the `print-image` job from the `.github/workflows/build-automated-approver.yml` workflow.
* Removed the `print-image` job from the `.github/workflows/build-cors-proxy.yml` workflow.
* Removed the `print-image` job from the `.github/workflows/build-dashboard-token-proxy.yml` workflow.
* Removed the `print-image` job from the `.github/workflows/build-github-webhook-gateway.yml` workflow.
* …

Remove print-image steps from multiple build YAML files.

---

docs/guidelines_iac.md

This pull request updates the Infrastructure as Code (IaC) guidelines in the `docs/guidelines_iac.md` file to enhance clarity and enforce agreements for Terraform configurations. The changes include adding a new guideline to avoid dynamic resource generation for better readability and maintainability.
* Added a new guideline to explicitly define multiple instances of resources in Terraform configurations, avoiding the use of `for_each`, `count`, or lists. This change aims to improve readability, simplify change tracking, and reduce complexity in infrastructure code. An example was included to illustrate the recommended approach.
See: #11946

Enhance Infrastructure as Code guidelines

---

configs/terraform/environments/prod/restricted-markets-delivery.tf

Artifact registries that we grant permissions exists in different project than default one comming from provider configuration. Missing project property caused TF to try grant access on registries on a wrong project, where such registries does not exists.
- Specified project where artifact registries exists.
Fix for changes from #12984

fix: specify project for IAM members in restricted markets delivery

---

configs/terraform/environments/prod/image-builder.tf

- According to the [documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/secret_manager_secret_version), we should use .name reference to secret location.
- ...
- ...
[Error in apply tf](https://github.com/kyma-project/test-infra/actions/runs/15018176453/job/42200904977)
https://github.com/kyma-project/test-infra/pull/12929
Implements /kyma/test-infra/issues/626

Use correct attribute reference to get secret path

---

configs/terraform/environments/prod/image-builder.tf

…mage-builder
Currently we use wrong account for image builder pipeline. Thus, We have no access to artifact registry.
- Switch from [kyma-oci-image-builder@sap-kyma-prow.iam.gserviceaccount.com](mailto:kyma-oci-image-builder@sap-kyma-prow.iam.gserviceaccount.com) to [azure-pipeline-image-builder@kyma-project.iam.gserviceaccount.com](mailto:azure-pipeline-image-builder@kyma-project.iam.gserviceaccount.com)
- ...
- ...
https://github.com/kyma-project/test-infra/pull/12929
Implements /kyma/test-infra/issues/626

Switch SA for image builder which uses ArtifactRegistry

---

configs/terraform/environments/prod/image-builder-variables.tf
configs/terraform/environments/prod/image-builder.tf
configs/terraform/modules/artifact-registry/main.tf

Docker Config ruins Remote Repository apply when mode is set to REMOTE_REPOSITORY
- Use dynamic on Docker Config block inside module of artifact registry
- ...
- ...
https://github.com/kyma-project/test-infra/pull/12929
Implements /kyma/test-infra/issues/626

Dynamic Docker Config to fix Remote Repository

---

cmd/image-autobumper/imagebumper/imagebumper.go
cmd/image-autobumper/imagebumper/imagebumper_test.go

When selecting the most recent image tag from a manifest, the logic originally relied on the timeCreatedMs field to determine which image was the latest. However, a discrepancy was observed: newly pushed images have their timeCreatedMs field set to "0", whereas older images contain a valid creation timestamp. As a consequence, the selection algorithm incorrectly identifies older images as the most recent, simply because they have a non-zero timeCreatedMs value.
"sha256:336f304895dc27accaa3bf285f074b477fb6243f52be12487dadc20975d5e0ab": {
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"tag": [
"v20241022-5fa8bfa1"
],
"timeUploadedMs": "1729622564863",
"timeCreatedMs": "1729622563897",
"imageSizeBytes": "21407344"
}, …

Fix Autobumper

---

cmd/cloud-run/signifysecretrotator/Dockerfile
cmd/cloud-run/slack-message-sender/Dockerfile

This pull request includes updates to the Dockerfiles for two services to explicitly specify the full path to the `gunicorn` executable in the `CMD` instruction. This change ensures that the correct version of `gunicorn` is used, avoiding potential issues with path resolution.
Changes to Dockerfiles:
* [`cmd/cloud-run/signifysecretrotator/Dockerfile`](diffhunk://#diff-f97ef8130c0cf0fc5b3b33b8b062b62cadee17e0c7c324f8b34c256ab078ea9cL32-R32): Updated the `CMD` instruction to use the full path `/app/venv/bin/gunicorn` instead of relying on the `PATH` environment variable.
* [`cmd/cloud-run/slack-message-sender/Dockerfile`](diffhunk://#diff-f433bb110ac416e6e379a8f33559068c2ab83fee0aeb0dd58aa4f2ddf905ea24L32-R32): Similarly, updated the `CMD` instruction to use `/app/venv/bin/gunicorn` for …

fix: update CMD in Dockerfile to use full path for gunicorn

---

cmd/cloud-run/signifysecretrotator/Dockerfile
cmd/cloud-run/slack-message-sender/Dockerfile

This pull request introduces changes to the Dockerfiles of two services to explicitly define their entry points. The updates ensure that the Python interpreter is set as the `ENTRYPOINT` for both services and containers use python from virtualenvs.
**Reason:**
This fixes error.
```
Traceback (most recent call last):
File "/app/venv/bin/gunicorn", line 5, in <module>
from gunicorn.app.wsgiapp import run
ModuleNotFoundError: No module named 'gunicorn'
```
**Changes:**
* [`cmd/cloud-run/signifysecretrotator/Dockerfile`](diffhunk://#diff-f97ef8130c0cf0fc5b3b33b8b062b62cadee17e0c7c324f8b34c256ab078ea9cR32): Added an `ENTRYPOINT` directive to specify `/app/venv/bin/python` as the entry point for the `signifysecretrotator` service.
* [`cmd/cloud-run/slack-message-sender/Dockerfile`](diffhunk://#d …

fix: set ENTRYPOINT to use Python from virtual environment in Dockerfile

---

configs/terraform/environments/prod/terraform-executor.tf

- Add member principal to act as terraform planner during service account names verification
See: #12762

Add permissions for service accounts names validation

---

.github/workflows/workflow-controller-build-1.yml
.github/workflows/workflow-controller-build-2.yml

When creating a merge queue, GitHub creates temporary branch (ie. `gh-readonly-queue/main/pr-13159-6dd3f30f2a6227f57893224e113fb03acefdec7d`) we should not trigger a push event on pushes to that branches. The name is dynamic so we need to use a star. See: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onpushbranchestagsbranches-ignoretags-ignore
- Exclude `gh-readonly-*` branches from push event on workflow controllers
See: #12762

Ignore pushes to temporary gh branch

---

.github/actions/checkout/action.yml

Used by us `actions/checkout@v4` is setting the workspace as safe directory while cloning the repository, but before that is setting temporary HOME directory, see [here](https://github.tools.sap/kyma/security-dashboard/actions/runs/15061238/job/69059711?pr=444#step:4:40), that set `HOME` is not persistent between steps and cause git commands run after checkout step to fail.
- Add explicitly current working directory as safe directory in git
See: https://github.com/actions/checkout/issues/766
See: kyma/security-dashboard#446

Add Github workspace to safe.driectory in git

---

configs/terraform/environments/prod/modules-submission.tf

For smooth migration to one identity of kyma submission pipeline, we need to create additional resource with same permissions as current one. To do that I wanna keep naming of the `kyma-project` related resourced to strictly indicate that there are connected with kyma-project GCP project.
Resource relocation and renaming:
* In `configs/terraform/environments/prod/modules-submission.tf`, the resource `google_artifact_registry_repository_iam_member.dev_modules_internal_repo_admin` was renamed to `google_artifact_registry_repository_iam_member.dev_modules_internal_repo_admin_kyma_project` and moved using the `moved` block for better alignment with the `kyma_project` context.
See: #12926

Rename kyma-project submission's identity to indicated kyma-project relation

---

.github/renovate-sharable-config.json

The previous regex was too broad and ended up capturing non-relevant values (like config fields or system paths). The updated version is more restrictive and should now match Docker image references more accurately, without pulling in unrelated strings.

Update regex for dependency name matching

---

.github/renovate-sharable-config.json

I've made some changes. Mainly i wanted to group our custom docker images into one PR. For now regex for those custom images is still removed, due to bad matching our latest tags. Also decided to move npm dependencies to a seperate config in security dashboard repo. 
I noticed that there is no need to seperate gomod matchings based on major/minor versions, because renovate makes it by default.
Works ok on my fork

Refactor Renovate configuration for package rules

---

.github/renovate-sharable-config.json

Tested it on my repo. It bumps go version to the newest one.  For example go 1.20 -> go 1.25.1

Add rangeStrategy to Go dependencies group

---

.github/renovate-sharable-config.json

This pull request updates the shared Renovate configuration to improve security and simplify the configuration for GitHub Actions. The most important changes involve adding a helper to pin GitHub Action digests and removing an explicit rule that disabled updates for several GitHub Actions.
**Security improvement:**
* Added the `helpers:pinGitHubActionDigests` extension to ensure that GitHub Action dependencies are pinned to specific digests, improving supply chain security. (`.github/renovate-sharable-config.json`)
**Configuration simplification:**
* Removed the rule that explicitly disabled updates for several GitHub Actions (`wechuli/allcheckspassed`, `actions/deploy-pages`, `actions/upload-pages-artifact`, and `actions/upload-artifact`), so these actions will now be eligible for …

(chore): Add GitHub Action digest pinning to Renovate config and remove ignoring actions 

---

.github/actions/image-builder/action.yml
.github/workflows/image-builder.yml
cmd/image-builder/github-workflow-integration.md
cmd/image-builder/main.go
cmd/image-builder/main_test.go
pkg/azuredevops/pipelines/templatesParams.go
pkg/azuredevops/pipelines/templatesParams_test.go

This pull request adds support for specifying a target build stage in the Dockerfile when building images using the image-builder. This enhancement allows users to build specific stages from multi-stage Dockerfiles, both in the CLI and GitHub Actions/Workflows. The change is implemented end-to-end: from CLI flags, through workflow and action inputs, to the Azure DevOps pipeline parameters, and is covered by new tests.
**CLI and Core Functionality:**
- Added a new `--target` flag to the `image-builder` CLI, allowing users to specify which build stage in the Dockerfile to use as the target. The value is passed through the application's options and included in the Azure DevOps pipeline parameters if set. [[1]](diffhunk://#diff-a15366436dafd5b402932194d7c809db3f2c060440bee74f69e7d009e965d3dfR6 …

Feat: add target dockerfile support

---

.github/actions/image-builder/action.yml

This pull request makes a minor update to the image builder GitHub Action configuration by removing the `--target` argument from the Docker build command. This is because for now, ImageBuilder image doesn't have this flag
- Removed the `--target` argument from the `args` passed to the image builder step in `.github/actions/image-builder/action.yml`, so the build will no longer specify a target stage.

Hotfix: remove target argument to make image builder build

---

.github/actions/image-builder/action.yml

This pull request updates the image used by the `image-builder` GitHub Action to a newer version. This ensures the build process uses the latest features and fixes provided by the updated image.
Dependency update:
* Updated the `image-builder` Docker image in `.github/actions/image-builder/action.yml` from version `v20251003-c2371fbc` to `v20251003-b9305fe9`.

chore: update image-builder version in action.yml
