kyma-project/test-infra

prow/scripts/cluster-integration/kyma-gke-integration.sh
=> GKE rapid: disable failing tests

prow/jobs/cli/cli-integration.yaml
Disabling notificatoin fro peridodic by sending it to kyma-prow-dev-null channel
=> sending notification to dev-null channel

prow/scripts/cluster-integration/kyma-gke-integration.sh
=> GKE rapid: disable failing core-test-external-solution test

development/image-syncer/external-images.yaml
- Upgrade Loki image version
See https://github.com/kyma-project/kyma/issues/9892
=> Upgrade Loki image version

prow/jobs/kyma/kyma-integration-gardener.yaml, templates/templates/kyma-integration-gardener.yaml
- Disable reporting for parallel installation job
=> Disable reporting for parallel installation job

prow/jobs/incubator/third-party-images/third-party-images.yaml, templates/data/incubator-third-party-images-data.yaml
=> Add console-nginx third party image

prow/scripts/cluster-integration/kyma-aks-long-lasting.sh, prow/scripts/cluster-integration/kyma-gke-integration.sh, prow/scripts/cluster-integration/kyma-gke-long-lasting.sh, prow/scripts/cluster-integration/kyma-upgrade-gardener-azure.sh, prow/scripts/lib/gardener/azure.sh, prow/scripts/resources/kyma-installer-overrides.tpl.yaml, prow/scripts/resources/overrides-dex-and-monitoring.tpl.yaml, prow/scripts/resources/prometheus-cluster-essentials-overrides.tpl.yaml, vpath/pjtester.yaml
=> Remove the installer-config-production.yaml.tpl override

prow/scripts/cluster-integration/kyma-gke-integration.sh
=> gke-integration: fix typo

development/test-log-collector/chart/test-log-collector/files/config.yaml
=> Update channel IDs for test-log-collector

prow/scripts/provision-vm-and-start-kyma-k3s.sh, vpath/pjtester.yaml
=> Junit reports for fast-integration tests - test-infra part

prow/jobs/kyma/kyma-integration.yaml, templates/templates/kyma-integration.yaml
- ...
- ...
- ...
https://github.com/kyma-project/test-infra/issues/3260
=> Enable psp in gke integration

prow/scripts/build-generic.sh, vpath/pjtester.yaml
- add time to each line outputted by make command
#3273
=> build-generic: add time to output

development/tools/cmd/rendertemplates/main.go
Data files used by render templates can be used as templates themselves. This allows to create generic datafilee that are populated by values from `global` field in config.yaml.
- add ability to load the data files as templates
- 
#3176
=> Treat data files as templates in rendertemplates

prow/scripts/build-generic.sh
=> build-generic: add fail on pipe fail

development/test-log-collector/chart/test-log-collector/files/config.yaml
=> Update test-log-collector config for serverless tests

development/image-syncer/external-images.yaml
- Update postgres image to 11.11-alpine to fix security issues
=> Update postgres image in external-images.yaml

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml, templates/templates/kyma-integration.yaml
=> Extend cleanup filter for disk cleaner

prow/jobs/kyma/kyma-integration.yaml, prow/scripts/cluster-integration/kyma-gke-integration.sh, prow/scripts/cluster-integration/kyma-gke-long-lasting.sh, prow/scripts/lib/utils.sh, templates/templates/kyma-integration.yaml, vpath/pjtester.yaml
beacuse every good story starts with one
- generate log file that describes psp policy for each pod and save it to artifacts
#3308
=> PSP: save logs to artifacts

prow/jobs/cli/cli-integration.yaml, prow/jobs/kyma/kyma-gke-external-registry.yaml, prow/jobs/kyma/kyma-release-candidate.yaml, prow/jobs/kyma/kyma-release-upgrade.yaml, templates/templates/kyma-gke-external-registry.yaml, templates/templates/kyma-release-candidate.yaml, templates/templates/kyma-release-upgrade.yaml
=> PSP: remove from non-integration jobs

development/image-syncer/external-images.yaml
=> Update oathkeeper image

prow/scripts/cluster-integration/kyma-integration-gardener.sh, vpath/pjtester.yaml
=> Gardener: test PSP

prow/branchprotector-config.yaml, prow/jobs/incubator/milv/milv.yaml, templates/templates/branchprotector-config.yaml
- ...
- ...
- ...
https://github.com/kyma-project/community/issues/538
=> Add config for milv repo

development/tools/jobs/incubator/podpreset-crd/podpreset_crd_test.go, prow/jobs/incubator/podpreset-crd/podpreset-crd.yaml
- bump podpreset buildpack because of moving to go modules
=> Bump podpreset buildpack (need to move to go modules)

prow/jobs/incubator/milv/milv.yaml
=> Update base image for milv pipeline

prow/jobs/incubator/third-party-images/third-party-images.yaml, templates/data/incubator-third-party-images-data.yaml
- Add python image built from the 3.8.8 rc1 github tag, which will be used temporarily because of CVE-2021-3177 vulnerability affecting serverless that wasn't officially patched yet.
=> Add python third party image

development/tools/jobs/incubator/podpreset-crd/podpreset_crd_test.go, development/tools/jobs/tester/tester.go, prow/jobs/incubator/podpreset-crd/podpreset-crd.yaml
- use kubebuilder buildpack for podpreset
=> Use the newest kubebuilder buildpack for podpreset

prow/config.yaml, templates/templates/prow-config.yaml
- Add presets for compass integration (dev)
=> Add presets for compass integration

prow/scripts/cluster-integration/helpers/install-kyma.sh, prow/scripts/cluster-integration/kyma-gke-release-candidate.sh, prow/scripts/lib/utils.sh
- ...
- ...
- ...
https://github.com/kyma-project/kyma/issues/10603
=> Fix certs regeneration

prow/scripts/cluster-integration/helpers/install-kyma.sh, prow/scripts/cluster-integration/kyma-gke-release-candidate.sh, prow/scripts/lib/utils.sh
- ...
- ...
- ...
It's already fixed on release-1.20 - https://github.com/kyma-project/test-infra/pull/3329
=> Fix certs generation (broken RC cluster)

development/tools/jobs/kyma/kyma_gardener_integration_test.go, prow/jobs/kyma/kyma-integration-gardener.yaml, templates/templates/kyma-integration-gardener.yaml
- Remove parallel installation job
=> Remove parallel installation job

prow/config.yaml, prow/scripts/cluster-integration/kyma-integration-k3s.sh, prow/scripts/lib/utils.sh, prow/scripts/provision-vm-and-start-kyma-k3s.sh, templates/templates/prow-config.yaml
- Prepare scripts for k3s compass integration
=> Prepare scripts for k3s compass integration

development/image-syncer/external-images.yaml
=> Update sb-proxy-k8s to v0.8.15

prow/config.yaml, templates/templates/prow-config.yaml
Renamed "lables" to "labels". This caused bug where unwanted variables were mounted.
- ...
- ...
- ...
=> Fix typo in compass preset

prow/images/buildpack-golang-kubebuilder2/Dockerfile
=> images: bump kubebuilder2 base

prow/config.yaml, templates/templates/prow-config.yaml
=> fix SLACK_CLIENT_WEBHOOK_URL to new Slack URL

development/tools/jobs/incubator/milv/milv_test.go, prow/jobs/incubator/milv/milv.yaml, templates/data/incubator-buildpack-data.yaml
- Add always_run to milv pre job
=> Add always_run to milv pre job

development/tools/jobs/tester/tester.go, development/tools/jobs/testinfra/buildpack_test.go, prow/jobs/test-infra/buildpack.yaml, templates/data/buildpack-data.yaml
=> Remove unused buildpack-golang-kubebuilder image

prow/scripts/lib/gardener/gcp.sh
- remove unused fragments of the script
#3334
=> gardener: remove unused GCP parallel install conditionals

development/tools/jobs/incubator/milv/milv_test.go, prow/jobs/incubator/milv/milv.yaml, templates/data/incubator-buildpack-data.yaml
- Remove ci args from milv jobs
=> Remove ci args from milv jobs

prow/scripts/lib/gardener/gcp.sh
=> gardener: fix gcp library

development/image-syncer/external-images.yaml
=> Update alpine image to 3.12.4

prow/jobs/kyma/releases/kyma-release-121.yaml, prow/jobs/test-infra/image-syncer.yaml, prow/jobs/test-infra/testgrid-automation.yaml, prow/testgrid-default.yaml, templates/data/image-syncer-data.yaml, templates/data/testgrid-automation-data.yaml, templates/templates/generic.tmpl, templates/templates/testgrid-default.yaml
As per the release goals created testgrid dashboard for future experimental jobs.
=> Add kyma_experimental dashboard for experimental jobs

prow/scripts/build-generic.sh
=> Add conditional loading for gcloud and docker init in build-generic.sh

prow/scripts/lib/cli-alpha.sh
- passing global.isBEBEnabled to alpha deploy command
=> beb support in kyma alpha deploy

prow/jobs/test-infra/testgrid-automation.yaml, templates/data/testgrid-automation-data.yaml, vpath/pjtester.yaml
k8s/test-infra introduced some breaking changes which breaks the testgrid config. Before upgrading Prow we have to use older version of transfigure to generate config.
=> Fall back to older version of transfigure image

prow/jobs/kyma/kyma-integration.yaml, templates/templates/kyma-integration.yaml
- disabled reporting
https://github.com/kyma-project/kyma/issues/10810
=> Disable reporting for gke-rapid

development/image-syncer/external-images.yaml
=> Bump Alpine image to 3.13.2

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml, prow/scripts/cluster-integration/kyma-integration-k3s.sh, templates/templates/kyma-integration.yaml, vpath/pjtester.yaml
- Preset for kyma integration compass dev
=> Pipeline for fast-integration kyma with compass

development/image-syncer/external-images.yaml
- Bumped `sb-proxy-k8s` image to latest version
=> Bump sb-proxy-k8s to v0.8.16

prow/scripts/cluster-integration/kyma-gke-integration.sh, prow/scripts/lib/gcloud.sh, vpath/pjtester.yaml
- Enable serverless tests for the `post-master-kyma-gke-rapid-integration` test
- Create rapid clusters with the `cos` image type
https://github.com/kyma-project/kyma/issues/10624
=> Enable serverless tests

prow/scripts/cluster-integration/kyma-gke-integration-cli.sh, vpath/pjtester.yaml
- Name of the function is now get from the `config.yaml` file.
[Failing tests here](https://github.com/kyma-project/cli/pull/775)
=> Improve cli tests

development/tools/jobs/kyma/governance_test.go, prow/jobs/kyma/kyma-governance.yaml, prow/scripts/governance.sh, vpath/pjtester.yaml
=> Bump milv and rename kyma governance

prow/scripts/build-kyma-artifacts.sh
- add components.yaml to artifacts bucket
https://github.com/kyma-project/test-infra/issues/3395
=> add components.yaml to artifacts bucket

prow/jobs/kyma/kyma-integration.yaml, templates/templates/kyma-integration.yaml
- Make kyma k3s compass job mandatory
=> Make kyma k3s compass job mandatory

prow/scripts/cluster-integration/control-plane-gke-integration.sh
-  Add dummy cls config secret to make the test happy
=> add dummy cls config secret

prow/scripts/governance.sh
- Make governance work with branches other than master
#3381
=> Governance: work with main branch

prow/jobs/cli/cli-integration.yaml
- Fix branch that triggers post-kyma-cli-integration-k3s
=> Fix branch that triggers post-kyma-cli-integration-k3s

prow/scripts/lib/utils.sh, prow/scripts/provision-vm-and-start-kyma-minikube.sh, vpath/pjtester.yaml
- ...
- ...
- ...
https://github.com/kyma-project/kyma/issues/10818
=> Test verbose ssh output

prow/scripts/lib/utils.sh
=> ssh: fix verbose flag

development/custom-image/create-custom-image.sh, prow/scripts/minikube-test.sh, prow/scripts/provision-vm-and-start-kyma-k3s.sh, prow/scripts/provision-vm-and-start-kyma-minikube.sh, prow/scripts/provision-vm-and-start-serverless-k3s.sh, prow/scripts/provision-vm-cli.sh, prow/scripts/provision-vm-compass.sh, prow/scripts/provision-vm-control-plane.sh
=> Change boot disk size to 200GB

prow/scripts/cluster-integration/serverless-integration-k3s.sh, vpath/pjtester.yaml
- bump kaniko image so that it reflects the one we're currently using in serverless chart
=> Bump kaniko image

prow/scripts/lib/utils.sh, prow/scripts/provision-vm-and-start-kyma-minikube.sh
- ...
- ...
- ...
kyma-project/kyma#10818
=> ssh: better debug

prow/jobs/kyma/skr-integration.yaml, templates/templates/skr-integration.yaml
SKR integration pipelines for KEB profiles
- azure-lite
- aws
- trial
=> SKR integration for aws, trial and azure-lite

prow/jobs/kyma/skr-integration.yaml, templates/templates/skr-integration.yaml
- disable reporting for SKR jobs, introduced in #3419
=> SKR: disable reporting

prow/jobs/test-infra/buildpack.yaml, templates/data/buildpack-data.yaml
Fixing typo in path in run_if_changed for presubmit for debug-commando
=> fix path in run_if_changed

prow/images/debug-commando/Dockerfile
Building image for oom troubleshooting.
=> Building image.

prow/jobs/kyma/releases/kyma-release-121.yaml
=> Add SCENARIO_TYPE to release job definition

prow/jobs/kyma/skr-integration.yaml, templates/templates/skr-integration.yaml
- Tests are green re-enable reporting disabled in #3432
=> SKR: enable reporting

prow/jobs/kyma/tests/end-to-end/external-solution-integration/external-solution-integration-tests-generic.yaml, templates/config.yaml
- ...
- ...
- ...
https://github.com/kyma-project/kyma/issues/10912
=> Cleanup end-to-end test jobs

prow/jobs/governance.yaml, templates/data/governance-data.yaml
- Fix test-infra governance prowjobs
#3452
=> Governance: fix text-infra job

prow/jobs/kyma/tests/contract/knative-channel-kafka/knative-channel-kafka-tests-generic.yaml, templates/config.yaml
- knative kafka was required by by kyma < 1.21
- 
=> remove knative kafka tests

development/image-syncer/external-images.yaml
Bump of images used in our ORY Oathkeeper chart.
- update `oathkeeper` image version
See also https://github.com/kyma-project/kyma/pull/10968
=> Bump ORY Oathkeeper image

prow/jobs/console/add-ons/add-ons.yaml, prow/jobs/console/core-ui/core-ui.yaml, prow/jobs/console/core/core.yaml, prow/jobs/console/logging/console-logging.yaml, prow/jobs/console/service-catalog-ui/service-catalog-ui.yaml, prow/jobs/console/tests/tests.yaml, templates/config.yaml, templates/templates/generic-component-console.yaml
- Remove pamela folder from console repo
- ...
- ...
https://github.com/kyma-project/console/pull/2164
=> Remove pamela from console repo

prow/jobs/busola/busola-backend/busola-backend.yaml, prow/jobs/busola/busola-core-ui/busola-core-ui.yaml, prow/jobs/busola/busola-core/busola-core.yaml, prow/jobs/busola/busola-service-catalog-ui/busola-service-catalog-ui.yaml, templates/config.yaml
=> Make busola jobs required

development/tools/jobs/kyma/kyma_gardener_cleanup_test.go, prow/jobs/kyma/kyma-gardener-cleanup.yaml, templates/templates/branchprotector-config.yaml
- fixed gardener-cleanup job
- updated branchprotector template (I forgot to do it on previous PR - no idea why I was able to merge it)
https://github.com/kyma-project/test-infra/issues/3381
=> Fix gardener-cleanup job

prow/branchprotector-config.yaml, templates/templates/branchprotector-config.yaml
- disable protection for kyma-2.0-docu branch as it is development branch
=> Disable protector for kyma-2.0-docu branch

prow/jobs/scans/protecode-guard.yaml, templates/data/protecode-guard-data.yaml
=> Add protecode to third-party-images

development/tools/pkg/pjtester/pjtester.go
pjtester need logic to detect if repo is using master or main branch.
=> Fix pjtester

prow/jobs/scans/protecode-guard.yaml, templates/data/protecode-guard-data.yaml
- don't wait in loop for this job
#3475
=> Protecode: fix thirt-party-images job

development/tools/pkg/pjtester/pjtester.go
=> better log message

development/image-syncer/external-images.yaml
Bump of images used in our ORY Oathkeeper chart.
- update `oathkeeper` image version to `0.38.9-alpine`
See also https://github.com/kyma-project/kyma/pull/10968
=> Bump ORY Oathkeeper image to 0.38.9-alpine

prow/jobs/test-infra/validation.yaml, templates/data/validation-data.yaml
- check if branchprotector config was regenerated
=> branchprotector: check if template was rendered

development/image-guard/README.md, development/test-log-collector/Dockerfile, development/tools/cmd/clusterscollector/README.md, development/tools/cmd/clusterscollector/main.go, development/tools/pkg/clusterscollector/collector.go, prow/images/prow-tools/Dockerfile
- remove `whitelist` from clustercollector
https://github.com/kyma-project/community/issues/515
=> Language: remove whitelist from the code

prow/jobs/test-infra/buildpack.yaml, templates/data/buildpack-data.yaml
=> Add jobguard to prow-tools run_if_changed

development/tools/jobs/kyma/kyma_integration_test.go, development/tools/jobs/tester/tester.go, prow/images/debug-commando/Dockerfile, prow/jobs/kyma/kyma-integration.yaml, templates/templates/kyma-integration.yaml
- ...
- ...
- ...
kyma-project/community#515
=> Language: remove whitelist from the jobs

prow/jobs/cli/cli-integration.yaml, templates/data/cli-data.yaml
=> Enable for kyma-cli-alpha-uninstall-gke

prow/jobs/scans/whitesource-periodics.yaml, templates/data/whitesource-periodics-data.yaml
- changed branch name to `main` for `control-plane` repo
#3381
=> Main branch: rename control-plane main branch

prow/scripts/lib/gardener/azure.sh, vpath/pjtester.yaml
- eventhubs is not used anymore in kyma > 1.20, so we need to remove all eventhub related code from the azure test
=> remove all eventhub related specifics from azure.sh

development/jobguard/README.md, development/jobguard/cmd/jobguard/main.go, development/jobguard/go.mod, development/jobguard/go.sum, development/jobguard/pkg/jobguard/v2/jobguard.go, development/jobguard/pkg/jobguard/v2/status.go, development/jobguard/scripts/run.sh, prow/config.yaml, templates/templates/prow-config.yaml, vpath/pjtester.yaml
Rewritten JobGuard to use Prow's GitHub client for fetching, building and updating the statuses. It won't depend on the local prowjob definition yamls, but will build the required contexts based on initial ones that are present on the commit. Then JobGuard will periodically update and check the statuses.
Closes #3454
=> New JobGuard application code

prow/scripts/cluster-integration/control-plane-gke-integration.sh
- Enable KMC in gke integration
=> Enable KMC in control plane gke integration

development/tools/jobs/third-party-images/cloudsql_proxy_test.go, development/tools/jobs/third-party-images/docker_registry_test.go, development/tools/jobs/third-party-images/fluent_bit_test.go, development/tools/jobs/third-party-images/grafana_test.go, development/tools/jobs/third-party-images/jaeger_operator_test.go, development/tools/jobs/third-party-images/kiali_test.go, development/tools/jobs/third-party-images/kiwigrid_sidecar_test.go, development/tools/jobs/third-party-images/minio_mc_test.go, development/tools/jobs/third-party-images/minio_test.go, development/tools/jobs/third-party-images/prometheus_node_exporter_test.go, prow/jobs/third-party-images/third-party-images.yaml, templates/data/third-party-images-data.yaml
=> TPI: rename main branch

development/custom-image/create-custom-image.sh, development/custom-image/install-deps-debian.sh
- `debian9` -> `debian10`
- `docker 18.06.1~ce~3-0~debian` -> `5:20.10.5~3-0~debian-buster`
- kubectl `1.16.3` -> `1.19.7`
=> Update custom VM image (debian 10)

docs/prow/workload-clusters.md
- Correct names incorrectly changed in the previous [PR](https://github.com/kyma-project/test-infra/pull/3501).
=> Correct headings

prow/jobs/kyma/releases/kyma-release-121.yaml, prow/jobs/kyma/releases/kyma-release-122.yaml, templates/data/kyma-release-data.yaml
=> Add labels for post-*-kyma-gke-release-upgrade

development/tools/jobs/third-party-images/cloudsql_proxy_test.go, development/tools/jobs/third-party-images/docker_registry_test.go, development/tools/jobs/third-party-images/fluent_bit_test.go, development/tools/jobs/third-party-images/grafana_test.go, development/tools/jobs/third-party-images/jaeger_operator_test.go, development/tools/jobs/third-party-images/kiali_test.go, development/tools/jobs/third-party-images/kiwigrid_sidecar_test.go, development/tools/jobs/third-party-images/minio_mc_test.go, development/tools/jobs/third-party-images/minio_test.go, development/tools/jobs/third-party-images/prometheus_node_exporter_test.go, prow/jobs/third-party-images/third-party-images.yaml, templates/data/third-party-images-data.yaml
- rename `ci-master` to `ci-main`
#3381
=> third-party-images: rename ci-master to ci-main

prow/jobs/kyma/kyma-integration-gardener.yaml, prow/scripts/cluster-integration/kyma-busola-long-lasting.sh, templates/templates/kyma-integration-gardener.yaml
- run jobs on every day-of-week from Monday through Friday
- changed cluster prefix to mitigate the cert quota
https://github.com/kyma-project/busola/issues/69
=> Update busola schedule

prow/jobs/cli/cli-integration.yaml, templates/data/cli-data.yaml
- fix templates working on only selected branches
#3381
=> Templates: fix cli-integration pre jobs

development/tools/jobs/kyma/kyma_gardener_cleanup_test.go, prow/jobs/kyma/kyma-gardener-cleanup.yaml, templates/data/kyma-gardener-cleanup-data.yaml
=> Update gardener-cleaner exceptions

prow/jobs/kyma/skr-integration.yaml, templates/templates/skr-integration.yaml
Pipelines are constantly failing starting from 01.04.2021.
See https://github.com/kyma-project/kyma/issues/11048
=> set skr pipelines to run once a day

development/tools/jobs/kyma/components_test.go, prow/jobs/kyma/components/busola-migrator/busola-migrator-generic.yaml, templates/config.yaml
- Make busola-migrator job optional
=> Make busola-migrator job optional

prow/images/buildpack-golang-kubebuilder2/Dockerfile
=> Update base image for kubebuilder2

prow/scripts/build-kyma-artifacts.sh
=> Kyma: change artifacts bucket path to main

prow/scripts/cluster-integration/kyma-aks-long-lasting.sh, prow/scripts/cluster-integration/kyma-gke-integration-cli.sh, prow/scripts/cluster-integration/kyma-gke-long-lasting.sh, prow/scripts/cluster-integration/kyma-integration-gardener.sh
- Migrate all kyma install commands in scripts to main
https://github.com/kyma-project/cli/issues/835
=> Main cli install

prow/jobs/scans/whitesource-periodics.yaml, templates/data/whitesource-periodics-data.yaml
=> Kyma: fix missing whitesource main branch renames

prow/labels.yaml, prow/plugins.yaml
Initial label_sync config with labels needed by new prow instance. 
#3429
=> Initial label config for label_sync tool

prow/jobs/kyma/kyma-integration.yaml, templates/templates/kyma-integration.yaml
Reverts kyma-project/test-infra#3525
Issue was fixed on compass and kyma side. Fix on kyma #11070
See https://github.com/kyma-project/kyma/issues/11068
=> Revert "suppress k3s integration with compass"

development/tools/jobs/incubator/hydroform/hydroform_test.go, prow/jobs/incubator/hydroform/hydroform.yaml, prow/jobs/scans/whitesource-periodics.yaml, templates/data/incubator-buildpack-data.yaml, templates/data/whitesource-periodics-data.yaml
=> Update hydroform jobs

development/image-syncer/external-images.yaml
- Adds alpine:3.13.4 to image-syncer
=> Add alpine:3.13.4 to image-syncer

development/jobguard/README.md, development/jobguard/cmd/jobguard/main.go, development/jobguard/go.mod, development/jobguard/go.sum, development/jobguard/pkg/jobguard/v2/jobguard.go, development/jobguard/pkg/jobguard/v2/status.go, development/jobguard/scripts/run.sh, prow/config.yaml, prow/scripts/cluster-integration/kyma-gke-upgrade.sh, templates/templates/prow-config.yaml
Use kyma version 1.20.0 in gke-upgrade job.
=> Use kyma version 1.20.0 in gke-upgrade job.

development/image-syncer/Makefile, development/prow-installer/Makefile, development/test-log-collector/Makefile, prow/jobs/test-infra/watch-pods/watch-pods.yaml, prow/scripts/build-compass-development-artifacts.sh, prow/scripts/build-kcp-development-artifacts.sh, prow/scripts/build-kyma-development-artifacts.sh, stability-checker/Makefile, templates/data/watch-pods-data.yaml, watch-pods/Makefile
=> Replace ci-master with ci-main

development/tools/jobs/incubator/api-gateway/api_gateway_test.go, prow/jobs/incubator/api-gateway/api-gateway.yaml, templates/data/incubator-buildpack-data.yaml
- ...
- ...
- ...
https://github.com/kyma-project/test-infra/issues/3381
=> Update api-gateway job to main

development/tools/jobs/governance/incubator_documentation-component_governance_test.go, prow/jobs/governance.yaml, templates/data/governance-data.yaml
- ...
- ...
- ...
https://github.com/kyma-project/test-infra/issues/3381
=> Update branch name for documentation-component

prow/scripts/cluster-integration/kyma-busola-long-lasting.sh
- use `main` version instead of `master`
- update `workers-count` flag to `concurrency`
=> Busola: fix long lasting

prow/jobs/kyma/components/event-sources/event-sources-generic.yaml, templates/config.yaml
Make event-sources available for rel-1-21.
=> Make event-sources available for rel-1-21

prow/jobs/kyma/kyma-integration-gardener.yaml, templates/templates/kyma-integration-gardener.yaml, vpath/pjtester.yaml
=> postsubmit kyma alpha job

prow/labels.yaml
Fix too long description for label release-pr-approved
#3429
=> Fix too long description for label release-pr-approved

prow/scripts/cluster-integration/helpers/generate-and-export-letsencrypt-TLS-cert.sh, prow/scripts/lib/utils.sh
- remove [deprecated](https://github.com/certbot/certbot/pull/8381) flag
=> Certbot: remove deprecated flag

prow/jobs/scans/whitesource-periodics.yaml, templates/data/whitesource-periodics-data.yaml
- change branch from master to main
=> Whitesource: fix api-gateway job

prow/scripts/cluster-integration/kyma-busola-long-lasting.sh
=> Busola: change cluster name

development/image-syncer/external-images.yaml
- Add golang 1 16 3 alpine to image syncer
=> Add golang 1 16 3 alpine to image syncer

development/tools/jobs/kyma/kyma_gardener_integration_test.go, prow/jobs/kyma/kyma-integration-gardener.yaml, prow/scripts/lib/kyma.sh, templates/templates/kyma-integration-gardener.yaml, vpath/pjtester.yaml
- periodic job for kyma alpha on eval profile
- kyma alpha pipelines on prod profile
=> jobs for kyma alpha

prow/scripts/cluster-integration/control-plane-gke-integration.sh
=> Remove CLS secret

development/tools/jobs/testinfra/branchprotector_test.go, prow/branchprotector-config.yaml, templates/templates/branchprotector-config.yaml
Now merging PRs to the `website` repo is blocked for sites other than `kyma-project` and this PR is provided to fix this issue
- Limit the existing status checking to the main branch
- Add another status checking for the `archive-snapshots` branch
**Related PR(s)**
https://github.com/kyma-project/website/pull/707
=> Update branchprotector config for website

development/tools/jobs/kyma/kyma_gardener_cleanup_test.go, prow/jobs/kyma/kyma-gardener-cleanup.yaml, templates/data/kyma-gardener-cleanup-data.yaml
=> Update gardener cleaner definition

prow/jobs/kyma/kyma-integration-gardener.yaml, prow/scripts/cluster-integration/kyma-busola-long-lasting.sh, prow/scripts/resources/busola/cluster-busola.yaml, prow/scripts/resources/busola/cluster-kyma.yaml, templates/templates/kyma-integration-gardener.yaml
- ...
- ...
- ...
https://github.com/kyma-project/test-infra/issues/3544
=> Split kyma-busola cluster provisioning

prow/scripts/resources/busola/cluster-busola.yaml, prow/scripts/resources/busola/cluster-kyma.yaml
=> disabled hibernation

prow/jobs/kyma/kyma-integration-gardener.yaml, templates/templates/kyma-integration-gardener.yaml
=> We push the cronjobs some hours earlier

prow/jobs/kyma/tests/console-backend-service/console-backend-service-tests-generic.yaml, prow/scripts/cluster-integration/compass-gke-integration.sh, prow/scripts/cluster-integration/control-plane-gke-integration.sh, templates/config.yaml
- Remove Console Backend Service tests
=> Remove Console Backend Service tests

prow/images/whitesource-scanner/Dockerfile
=> Bump whitesource version

development/tools/jobs/kyma/kyma_gardener_cleanup_test.go, prow/jobs/kyma/kyma-gardener-cleanup.yaml, templates/data/kyma-gardener-cleanup-data.yaml
=> Update gardener cleaner - add npkyma

prow/scripts/cluster-integration/kyma-gke-integration.sh, prow/scripts/cluster-integration/kyma-gke-long-lasting.sh, prow/scripts/lib/utils.sh, vpath/pjtester.yaml
- check if any resource in the `kyma-system` namespace is non-compliant
=> GKE-integration: check if cluster is compliant

prow/scripts/cluster-integration/protecode-guard.sh
=> Protecode: end script faster

development/github-slack-connector/githubWebhookGateway/README.md
- Removed the dead link to the removed Event Service
=> Remove dead link to Event Service

prow/jobs/test-infra/branchprotector.yaml, prow/plugins.yaml, prow/workload-cluster/gce-ssd-retain_storageclass.yaml, prow/workload-cluster/ghproxy.yaml
=> Tune branchprotector config

prow/config.yaml, templates/templates/prow-config.yaml
=> Split queries to two orgs

prow/config.yaml, templates/templates/prow-config.yaml
Added `allow_disabled_policies` to the compass and compass-console repositories. The repos are set to `protect: false` but inherit protection configuration from parent level.
=> Add allow_disabled_policies to compass repo

development/tools/cmd/rendertemplates/README.md, prow/config.yaml, templates/data/addons-data.yaml, templates/data/buildpack-data.yaml, templates/data/cli-data.yaml, templates/data/compass-development-artifacts-data.yaml, templates/data/compass-integration-data.yaml, templates/data/control-plane-integration-data.yaml, templates/data/control-plane-kcp-data.yaml, templates/data/control-plane-whitesource.yaml, templates/data/governance-data.yaml, templates/data/incubator-dex-data.yaml, templates/data/kyma-azure-event-hubs-namespaces-cleanup-data.yaml, templates/data/kyma-gardener-cleanup-data.yaml, templates/data/kyma-integration-gardener-data.yaml, templates/data/kyma-release-image-guard-data.yaml, templates/data/kyma-upgrade-gardener-data.yaml, templates/data/rafter-data.yaml, templates/data/skr-integration-data.yaml, templates/templates/prow-config.yaml
=> templates: cleanup

prow/config.yaml, templates/templates/prow-config.yaml
Moved `allow_disabled_policies: true` to root level of branch protection config.
=> Add allow_disabled_policies to root level of branch protection

development/jobguard/scripts/run.sh
Add `(pre.*kyma-artifacts)` regex and disable strict context checking in jobguard
=> FIx jobguard contexts error in release-1.22

prow/jobs/kyma/kyma-integration.yaml, templates/data/kyma-integration-data.yaml
=> Fix pre-main-kyma-integration-k3s job

development/image-syncer/external-images.yaml
=> Bump SC image

development/tools/jobs/control-plane/components_test.go, templates/config.yaml
=> Remove job for metris

development/jobguard/scripts/run.sh
=> Ensure jobguard works on PR commit

prow/config.yaml, templates/templates/prow-config.yaml
Disable batch merging for kyma repository by setting up `batch_size_limit` to -1.
https://github.com/kubernetes/test-infra/blob/1eb7cb0ab2b52a38bb37f2c190dee79df03f940b/prow/tide/tide.go#L1076
=> Disable batch merging for kyma repository

prow/cluster/components/crier_deployment.yaml, prow/cluster/components/deck_deployment.yaml, prow/config.yaml, prow/jobs/test-infra/testgrid-automation.yaml, prow/labels.yaml, prow/plugins.yaml, templates/data/testgrid-automation-data.yaml, templates/templates/prow-config.yaml
After upgrade changes in Prow, labels and transfigure configuration
* Sync transfigure image with the Prow version
* Connect WIP label with the do-not-merge/work-in-progress since they have the same purpose
* enable gas workers in crier to enable podinfo lens
* update plugins.yaml to the new structure
=> Prow configuration updates and fixes

prow/labels.yaml
=> Fix typo in labels.yaml

docs/prow/crier.md
During the recent change to Tide, some resources were removed. Some documentation changes related to the Tide issue are still outstanding, but in the meantime there is a prow job error for a dead link: https://storage.googleapis.com/kyma-prow-logs/logs/test-infra-governance-nightly/1390531930985861120/build-log.txt 
Remove link to non-existing resource
=> Remove link to non-existing resource

prow/scripts/cluster-integration/kyma-upgrade-gardener.sh, prow/scripts/lib/gardener/aws.sh, prow/scripts/lib/gardener/azure.sh, prow/scripts/lib/gardener/gcp.sh, vpath/pjtester.yaml
- run pre and post Kyma upgrade tests in Gardener upgrade script
See https://github.com/kyma-project/kyma/issues/11162
=> Run pre and post Kyma upgrade tests in Gardener upgrade script

development/image-syncer/external-images.yaml
- bump alpine image in external-images from 3.13.4 to 3.13.5
=> Bump alpine image to 3.13.5

prow/jobs/kyma/kyma-integration-gardener.yaml, prow/scripts/cluster-integration/kyma-busola-long-lasting.sh, templates/data/kyma-integration-gardener-data.yaml, vpath/pjtester.yaml
- disable Busola Kyma nightly jobs until it is fixed
- add pipefail
- wait 2 minutes after cluster deletion to avoid Gardener race conditions
=> Busola Kyma: fix jobs

prow/jobs/test-infra/buildpack.yaml, templates/data/buildpack-data.yaml
Adding prowjobs for building pubsub gateway for pubsub connector on skr.
=> build_pubsub_gateway

prow/config.yaml, prow/jobs/kyma/skr-integration.yaml, templates/data/skr-integration-data.yaml, templates/templates/prow-config.yaml
- define SKR AWS fast integration test
=> Define free aws skr fast int test

development/image-syncer/external-images.yaml
=> Add "Cypress" to image-syncer for Busola

development/image-syncer/external-images.yaml
=> Bump sb-proxy image to latest version

prow/scripts/lib/gcloud.sh
=> Scripts: fix gcloud

prow/scripts/lib/azure.sh, prow/scripts/lib/testing-helpers.sh
=> Scripts: fiz Azure lib

prow/scripts/cluster-integration/kyma-upgrade-gardener.sh, vpath/pjtester.yaml
- Update component that should be removed before upgrade
- Add kyma-installer namespace removal
=> Update old kyma components that should be removed

prow/cluster/resources/probot-stale/templates/deployment.yaml, prow/cluster/resources/probot-stale/values-oss.yaml
=> Values for open source Kyma stalebot.

development/pubsub-connector/oomFoundFunction/handler.py
Fix variable name by replacing dashes with underscores.
=> fix variable name

development/gcp/cloud-functions/checkoomevent/checkoomevent.go, development/gcp/cloud-functions/checkoomevent/go.mod, development/pubsub-connector/pubsubConnector/templates/13-pubsubConnectorSlackClientFnSubscription.yaml
Better logging mesages.
Logging messages for all failures and important steps.
Disabled batch publishing.
=> Ack when no oom

development/tools/jobs/third-party-images/etcd_test.go, prow/jobs/third-party-images/third-party-images.yaml, templates/data/third-party-images-data.yaml
A prow pipeline for the etcd rebuilt image: https://github.com/kyma-project/third-party-images/tree/main/etcd
- ...
- ...
- ...
=> Add etcd external image pipeline

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml, templates/data/kyma-integration-data.yaml
- updated regexp to also cover busola vms
=> Update vm-cleaner regexp

development/pubsub-connector/oomFoundFunction/handler.py, development/pubsub-connector/pubsubConnector/values.yaml
Add logging of pubsub message id in kyma function. This allow to identify message flow through all system components.
=> Log message ID in kyma function

development/image-syncer/external-images.yaml
=> add nats server and exporter images

prow/jobs/kyma/kyma-integration.yaml, templates/data/kyma-integration-data.yaml
- Make pre compass integration pipeline optional
=> Make pre compass integration pipeline optional

development/tools/jobs/kyma/kyma_integration_test.go, prow/config.yaml, prow/jobs/kyma/kyma-integration.yaml, prow/scripts/github-issues.sh, templates/data/kyma-integration-data.yaml, templates/templates/prow-config.yaml
=> GitHub issues to bigquery: add prowjob

development/image-syncer/external-images.yaml
=> add nats 2.1.9 and 2.2.4 for testing purpose

development/jobguard/scripts/run.sh
=> FIx jobguard contexts error in release-1.21

prow/jobs/scans/whitesource-periodics.yaml, templates/data/whitesource-periodics-data.yaml
=> remove knative-kafka-whitesource scan

docs/prow/crier.md, docs/prow/prow-architecture.md, docs/prow/prow-monitoring.md
Updated prow documentation with the new way of installing monitoring stack and updated architecture.
#3646
=> New prow docs after upgrade

prow/jobs/kyma/kyma-integration-gardener.yaml, prow/scripts/cluster-integration/helpers/create-eventing-secret.sh, prow/scripts/cluster-integration/kyma-integration-gardener-eventing.sh, templates/data/kyma-integration-gardener-data.yaml
Add infrastructure to run Eventing E2E tests.
=> Add infrastructure to run Eventing E2E tests

prow/jobs/incubator/compass/compass-gke-benchmark.yaml, templates/data/compass-gke-benchmark-data.yaml
=> Dissable benchmark job on hotfix

development/image-syncer/external-images.yaml, prow/scripts/provision-vm-and-start-busola-k3s.sh, vpath/pjtester.yaml
=> Busola tests artifacts

development/image-syncer/external-images.yaml
- bump external golang alpine image
=> bump golang alpine

prow/jobs/kyma/kyma-integration.yaml, templates/data/kyma-integration-data.yaml
- Make k3s-compass job mandatory after compass bugfix
See also https://github.com/kyma-project/kyma/issues/11331
=> Make k3s-compass job mandatory

prow/scripts/cluster-integration/protecode-guard.sh
=> Increase timeout for protecode guard

prow/config.yaml, templates/templates/prow-config.yaml
=> KEB Resolve user (email) of the runtime creator

prow/jobs/kyma/kyma-integration.yaml, prow/scripts/cluster-integration/serverless-integration-k3s.sh, prow/scripts/provision-vm-and-start-serverless-k3s.sh, templates/data/kyma-integration-data.yaml
Use kyma cli to deploy lightweight kyma stack.
- Use kyma cli to deploy lightweight kyma stack.  
**Related issue(s)** https://github.com/kyma-project/kyma/issues/11257
=> Add Serverless integration tests for kyma 2.0 on k3s

prow/scripts/provision-vm-compass.sh, vpath/pjtester.yaml
https://github.com/kyma-incubator/compass/pull/1860
=> Ensure Compass VM job uses data dump

prow/jobs/incubator/compass/compass-gke-benchmark.yaml, templates/data/compass-gke-benchmark-data.yaml
Compass performance tests should be optional and should not block PR merging.
=> Make compass performance tests optional

development/kyma-github-connector/githubWebhookGateway/pkg/httperrors/httperrors.go
Removed not needed case condition.
=> remove not needed case condition

prow/jobs/kyma/kyma-integration.yaml, prow/scripts/cluster-integration/serverless-integration-k3s.sh, templates/data/kyma-integration-data.yaml, vpath/pjtester.yaml
Only run serverless k3s integration tests when serverless is changed.
- changes prow `run_if_changed` for k3s integration tests
- increase wait time after k3s deployment to get configmaps ready.
- ...
=> Run serverless integration tests only when serverless is changed

development/kyma-github-connector/githubConnector/values.yaml, development/kyma-pubsub-connector/pubsubConnector/values.yaml
Using postsubmit builded images.
Using function code from main branch of kyma-project org.
=> switch to main branch

prow/config.yaml, templates/templates/prow-config.yaml
=> Bump k8s version on gardener to 1.20

prow/config.yaml, templates/templates/prow-config.yaml, vpath/pjtester.yaml
Use k8s secret with static ssh key for connection to VMs.
Closes https://github.com/kyma-project/kyma/issues/10818
=> Use static ssh key for gcloud ssh

prow/jobs/kyma/kyma-integration-gardener.yaml, templates/data/kyma-integration-gardener-data.yaml, vpath/pjtester.yaml
Remove knative related config from gardener-azure-integration job.
=> Remove knative related config from gardener-azure-integration job

prow/images/buildpack-golang/Dockerfile, prow/images/buildpack-golang/Makefile, prow/images/buildpack-golang/license-puller.sh
Maintaining multiple images that are derivatives of themselves is tedious and problematic. Consolidate `buildpack-golang` images into one for easier maintainability.
#893
=> Consolidate current buildpack-golang images into one.

prow/scripts/provision-vm-and-start-busola-k3s.sh, vpath/pjtester.yaml
- Don't copy downloads folder. It contains kubeconfig file.
=> Fix permission problem for Cypress downloads folder

development/image-syncer/external-images.yaml
- Upgrade Cypress to 7.5.0 version
=> Upgrade Cypress to 7.5.0 version

prow/scripts/cluster-integration/busola-ui-tests-k3s.sh
=> Busola improve screenshot handling

prow/scripts/resources/busola/cluster-kyma.yaml
- we switch to the kymatest.accounts400.ondemand.com for the nightly clusters
=> switching to kymatest ias tennant for nightly cluster

prow/scripts/cluster-integration/kyma-busola-long-lasting.sh
- kyma is uninstalled before cluster deletion
- change concurrency to 1
=> Delete kyma before cluster deletion in busola pipeline

prow/scripts/provision-vm-compass.sh, vpath/pjtester.yaml
- Disable db dump - it might be the problem for failing compass jobs
=> Temporary disable Compass DB dump

prow/jobs/busola/ui-test.yaml, templates/data/busola-ui-test-data.yaml
=> Make Busola UI tests required

development/tools/jobs/kyma/kyma_gardener_cleanup_test.go, prow/jobs/kyma/kyma-gardener-cleanup.yaml, prow/jobs/kyma/kyma-integration-gardener.yaml, prow/scripts/cluster-integration/helpers/cleanup-gardener.sh, templates/data/kyma-gardener-cleanup-data.yaml, templates/data/kyma-integration-gardener-data.yaml
=> Update gardener cleaner

prow/jobs/kyma/kyma-integration-gardener.yaml, templates/data/kyma-integration-gardener-data.yaml
=> Disable kyma 2.0 nightly and update periodic cron expression

development/image-syncer/external-images.yaml
- Prepare new image for ORY/Oathkeeper
See: https://github.com/kyma-project/kyma/pull/11473
=> Bump oathkepper image version

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml, templates/data/kyma-integration-data.yaml
=> Disable firewall cleaner

development/tools/jobs/third-party-images/oauth2_proxy_test.go, prow/jobs/third-party-images/third-party-images.yaml, templates/data/third-party-images-data.yaml
=> added new jobs for oauth2-proxy image

prow/scripts/lib/gardener/azure.sh
=> Fix azure gardener jobs

prow/scripts/lib/gardener/azure.sh
=> Gardener: fix azure script

prow/jobs/kyma/kyma-integration-gardener.yaml, templates/data/kyma-integration-gardener-data.yaml
- Fixes pre and post submit job to be run only if files under specified path were changed
=> Fix run_if_changed regex for API gateway tests

development/tools/jobs/governance/common_governance_test.go, development/tools/jobs/governance/kyma_governance_test.go, go.sum, prow/jobs/governance.yaml, templates/config.yaml, templates/data/governance-data.yaml, vpath/pjtester.yaml
- add optional job for kyma-2.0-docu branch to find broken links
=> Add new optional governance job for kyma-2.0-docu

prow/jobs/test-infra/prow-periodics.yaml, templates/data/prow-periodics-data.yaml
=> Fix typo in post-test-infra-deploy-prow command

prow/config.yaml, templates/templates/prow-config.yaml
=> Fix branch name in branch-protector (reconciler)

prow/scripts/cluster-integration/kyma-cli-alpha-uninstall.sh
=> Fix tests for kyma alpha uninstall

development/tools/jobs/incubator/milv/milv_test.go, development/tools/jobs/incubator/reconciler/reconciler_test.go, prow/jobs/incubator/milv/milv.yaml, prow/jobs/incubator/reconciler/reconciler.yaml, templates/config.yaml, templates/data/incubator-buildpack-data.yaml
- remove all occurrences of `<<` from `templates/data`
- use configSets to define used image
- `buildpack-golang` image: change tag from `1.16.4` to `v20210607-b7e95d8b`
#3784
=> Templates: don't use susbstitution in data files

prow/scripts/compatibility-cli.sh
- arrays indices start from 1
- ...
- ...
https://github.com/kyma-project/cli/issues/921
=> Fetch correct current version for kyma-cli-compatibility-2 job

prow/autobump-config/prow-cluster-autobump-config.yaml
The `repo` field in auto bumper prefix config should point to the repository where the source images are from, as written in the godoc:
https://github.com/kubernetes/test-infra/blob/34aa2f2aa75bb3f8edc9f6b8942d4d5dc65a1b37/prow/cmd/generic-autobumper/main.go#L138
=> Change repo as per generic-autobumper docs

prow/scripts/cluster-integration/control-plane-gke-integration.sh, vpath/pjtester.yaml
- Don't run compass benchmark tests in Control Plane
- https://github.com/kyma-project/control-plane/pull/782
=> Skip Compass tests in Control Plane integration tests jobs

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml, templates/data/kyma-integration-data.yaml
=> Change schedule for weekly and nightly clusters

prow/jobs/busola/busola-web/busola-web.yaml, templates/config.yaml, templates/data/generic_component_busola_data.yaml
- Add skip_report for busola-web
=> skip_report for busola-web

development/custom-image/install-deps-debian.sh
=> Pre-fetch docker images in VM image

development/tools/jobs/kyma/kyma_gardener_integration_test.go, prow/jobs/kyma/kyma-integration-gardener.yaml, prow/scripts/cluster-integration/kyma-upgrade-gardener.sh, templates/data/kyma-integration-gardener-data.yaml
- changed the order of the test steps by mainly removing the component removal to the end
- introduced a patch before the upgrade which will be added to the installer soon
- reduced interval time to execute the job from 1 hour to 2 hours to save money
=> trying to fix the upgrade-test

prow/jobs/third-party-images/third-party-images.yaml, templates/data/third-party-images-data.yaml
- Remove jobs for console-nginx - they are to be removed in [this PR](https://github.com/kyma-project/third-party-images/pull/99)
=> Remove console nginx jobs

prow/jobs/scans/whitesource-periodics.yaml, templates/data/whitesource-periodics-data.yaml
- Add reconciler whitesource job
See https://github.com/kyma-incubator/reconciler/issues/20
=> Add reconciler whitesource job

development/image-syncer/external-images.yaml
- Upgraded the loki image to 2.2.1
- ...
- ...
=> upgrade to loki 2.2.1

development/tools/jobs/releases/releases.go, prow/jobs/kyma/releases/kyma-release-20.yaml, prow/testgrid-default.yaml, templates/config.yaml, templates/templates/releases.go.tmpl
=> Add job definitions for Kyma 2.0

prow/scripts/cluster-integration/compass-gke-benchmark.sh, prow/scripts/cluster-integration/compass-gke-integration.sh
**Add override for system-fetcher tests**
- For system fetcher tests to run we need some overrides
- Add the overrides for the GKE integration
=> Add override for system-fetcher tests

prow/scripts/cluster-integration/compass-gke-benchmark.sh, prow/scripts/cluster-integration/compass-gke-integration.sh
Currently blocks merging other PRs
=> Revert "Add override for system-fetcher tests (#3840)"

prow/scripts/cluster-integration/kyma-cli-alpha-uninstall.sh, vpath/pjtester.yaml
- change `kyma alpha uninstall` to `kyma alpha delete`
- add `SUITE_NAME`
=> CLI alpha: change command name

prow/autobump-config/test-infra-autobump-config.yaml, prow/jobs/test-infra/prow-periodics.yaml, templates/data/prow-periodics-data.yaml, vpath/pjtester.yaml
Added config and job for autobumping images from `eu.gcr.io/kyma-project/test-infra/`
Might need some followups.
#3498
=> Autobump config for test-infra images

prow/scripts/lib/gcp.sh
=> Scritps: fix gcp lib

prow/scripts/lib/gardener/gardener.sh
=> Scripts: fix gardener lib

prow/scripts/lib/gcp.sh
=> Scripts: fix gcp lib

prow/scripts/cluster-integration/compass-gke-benchmark.sh, prow/scripts/cluster-integration/compass-gke-integration.sh, prow/scripts/cluster-integration/control-plane-gke-integration.sh, prow/scripts/cluster-integration/kyma-gke-long-lasting.sh, prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh, prow/scripts/cluster-integration/kyma-gke-release-candidate.sh, prow/scripts/cluster-integration/kyma-gke-upgrade.sh
=> Scripts: fix gcloud ip function

prow/scripts/cluster-integration/compass-gke-benchmark.sh, prow/scripts/cluster-integration/compass-gke-integration.sh, prow/scripts/cluster-integration/control-plane-gke-integration.sh, prow/scripts/cluster-integration/kyma-gke-long-lasting.sh, prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh, prow/scripts/cluster-integration/kyma-gke-release-candidate.sh, prow/scripts/cluster-integration/kyma-gke-upgrade.sh, prow/scripts/lib/gcloud.sh
=> Scripts: fix variable name

development/image-syncer/external-images.yaml
=> Update postgres image

prow/scripts/lib/utils.sh
=> Scripts: fix common name generation

prow/scripts/lib/gardener/aws.sh, prow/scripts/lib/gardener/azure.sh, prow/scripts/lib/gardener/gcp.sh
- make sure the cluster name is 9 characters long or less
=> Scripts: check gardener cluster name requirements

prow/jobs/kyma/kyma-integration.yaml, templates/data/kyma-integration-data.yaml
We get notifications about OOM issues, but there are no details in the artifacts directory
- oom-debug enabled in pre-main-kyma-gke-upgrade prowjob.
=> Add oom debug to gke upgrade

prow/jobs/kyma/kyma-artifacts.yaml, templates/data/kyma-artifacts-data.yaml
- ...
- ...
- ...
https://github.com/kyma-project/kyma/issues/11616
=> Add artifacts job for release 2.0

prow/jobs/kyma/kyma-integration.yaml, templates/data/kyma-integration-data.yaml
=> Add oom debug to pre-main-kyma-gke-upgrade

prow/scripts/cluster-integration/compass-gke-benchmark.sh, prow/scripts/cluster-integration/compass-gke-integration.sh
**Add overrides for system fetcher in compass**
- Add overrides for system fetcher e2e tests in Compass
=> Add overrides for system fetcher in compass

prow/scripts/cluster-integration/kyma-aks-long-lasting.sh, prow/scripts/cluster-integration/minio/azure-cleaner.sh, prow/scripts/cluster-integration/minio/azure-gateway.sh, prow/scripts/lib/azure.sh, prow/scripts/vpathguard.sh
=> Azure: rewrite library script

prow/scripts/cluster-integration/kyma-aks-long-lasting.sh, prow/scripts/cluster-integration/kyma-upgrade-gardener.sh
- import `gcp.sh` instead of `gcloud.sh`
=> Azure long lasting: fix import

prow/scripts/cluster-integration/kyma-aks-long-lasting.sh, prow/scripts/lib/azure.sh
=> Scritps: fix Azure deprovisioning

prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
=> Scritps: Azure provisioning fix

prow/scripts/cluster-integration/compass-gke-benchmark.sh, prow/scripts/cluster-integration/compass-gke-integration.sh
**Fixes problem in not able to read JSON property override**
=> Do not use slashes in JSON property in override

prow/scripts/cluster-integration/kyma-aks-long-lasting.sh, prow/scripts/lib/azure.sh
=> Scripts: make debug_oom optional for Azure

prow/scripts/cluster-integration/kyma-aks-long-lasting.sh
=> Azure: fix long lasting dns creation

development/tools/jobs/kyma/kyma_gardener_cleanup_test.go, prow/jobs/kyma/kyma-gardener-cleanup.yaml, prow/scripts/cluster-integration/helpers/cleanup-gardener.sh, prow/scripts/lib/gcp.sh, templates/data/kyma-gardener-cleanup-data.yaml
- remove additional `"`
- do not exclude `np[0-9].*` clusters
=> gardener: fix cleanup

docs/prow/prow-architecture.md
Master branch was renamed to `main` and the Kubernetes link has changed.
- Fix a dead link causing governance job error
=> Fix link returning 404 error

development/custom-image/install-deps-debian.sh, development/image-syncer/external-images.yaml, prow/scripts/cluster-integration/busola-integration-test-k3s.sh
=> Upgrade Cypress to 7.7.0 version

prow/scripts/cluster-integration/kyma-upgrade-gardener.sh
- switched back to test upgrade on latest release version instead of main
- removed workaround as it is covered in CLI command now
- ...
=> switching to latest release

prow/scripts/lib/README.md
=> Scripts: update docs

prow/scripts/cluster-integration/helpers/cleanup-gardener.sh, prow/scripts/cluster-integration/kyma-upgrade-gardener-azure.sh, prow/scripts/lib/gardener/aws.sh, prow/scripts/lib/gardener/azure.sh, prow/scripts/lib/gardener/gardener.sh, prow/scripts/lib/gardener/gcp.sh, prow/scripts/unstale-gardener-project.sh
=> Scripts: fix failing

prow/scripts/cluster-integration/kyma-integration-gardener-eventing.sh, prow/scripts/cluster-integration/kyma-integration-gardener.sh
=> Scripts: quickfix

prow/scripts/cluster-integration/helpers/cleanup-cluster.sh
=> Scripts: fix GKE nightly

prow/scripts/lib/gcp.sh
=> Scripts: fix gcp library

development/image-syncer/main.go
=> Image syncer: remove unused check

prow/jobs/test-infra/pjtester.yaml, templates/data/pjtester-data.yaml
=> Pjtester: enable on all branches

prow/jobs/scans/protecode-guard.yaml, templates/data/protecode-guard-data.yaml
=> Add protecode-guard for reconciler repo

prow/jobs/scans/protecode-guard.yaml, templates/data/protecode-guard-data.yaml
=> Remove run_if_changed from protecode guard

prow/scripts/cluster-integration/helpers/cleanup-cluster.sh, prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
Fixing kyma-gke-nightly failure.
=> Deprovision long lasting cluster in synchronous mode

prow/config.yaml, templates/templates/prow-config.yaml
=> Branch protector: disable on website-vuepress

development/custom-image/create-custom-image.sh
Add commit id to image in create-custom-image.sh
=> Add commit id to image in create-custom-image.sh

prow/scripts/cluster-integration/serverless-integration-k3s.sh, prow/scripts/provision-vm-cli.sh
=> Add version to k3d

prow/jobs/scans/protecode-guard.yaml, templates/data/protecode-guard-data.yaml
- Make protecode optional for reconciler
=> Make protecode optional for reconciler

development/tools/jobs/tester/tester.go, prow/jobs/governance.yaml, prow/jobs/incubator/compass/compass-development-artifacts.yaml, prow/jobs/incubator/dex/dex.yaml, prow/jobs/kyma/kyma-artifacts.yaml, prow/jobs/kyma/kyma-release-pr-image-guard.yaml, prow/jobs/test-infra/buildpack.yaml, prow/jobs/test-infra/validation.yaml, prow/jobs/third-party-images/third-party-images.yaml, templates/config.yaml, templates/data/third-party-images-data.yaml
Changing target for pre-main-tpi-k8s-tools to use Cosign.
Adding the pjtester feature.
Signed-off-by: Youssef Azrak <yazrak.tech@gmail.com>
=> Changing target for pre-main-tpi-k8s-tools to use Cosign.

prow/config.yaml, templates/templates/prow-config.yaml
=> Add Kyma-Showcase repo to tide

development/tools/jobs/testinfra/branchprotector_test.go
- add `Kyma-Showcase` to branchprotector
=> Kyma-showcase: add to branchprotector

prow/images/kyma-integration/Dockerfile
- We would like to introduce new kyma integration tests and those require `smctl`
test that will use smctl: https://github.com/kyma-project/test-infra/pull/3913
epic: https://github.tools.sap/kyma/backlog/issues/1656
=> Install smctl for kyma integration tests

prow/images/buildpack-golang/Dockerfile
=> Update bootstrap in buildpack

prow/jobs/kyma/kyma-integration-gardener.yaml, templates/data/kyma-integration-gardener-data.yaml
Make `pre-main-kyma-gardener-gcp-eventing` required.
=> Make pre-main-kyma-gardener-gcp-eventing required

prow/scripts/lib/kyma.sh
=> GKE-upgrade: use fixed version

development/jobguard/scripts/run.sh
=> Remove jobguard-fallback

prow/images/bootstrap/Dockerfile, prow/images/kyma-integration/Dockerfile
=> Update cosign to 0.6.0

prow/images/buildpack-golang/Dockerfile
=> Update bootstrap in buildpack-golang

prow/scripts/cluster-integration/kyma-upgrade-gardener.sh, prow/scripts/lib/kyma.sh
- the latest images in the helm charts not being used. Basically after upgradeKyma would still be using older chart images which are usually changed during an upgrade
=> While upgrading we should not reuse existing values as this can cause

prow/scripts/cluster-integration/kyma-upgrade-gardener.sh
=> add newline

development/image-syncer/external-images.yaml
=> Upgrade Cypress to 8.0.0

prow/scripts/compatibility-cli.sh
- Dont check for kyma 2 as of now as the installer commands are different. This PR fixes issue from this PR: https://github.com/kyma-project/test-infra/pull/3958
=> do not test for kyma 2.0 right now

prow/scripts/cluster-integration/helpers/integration-tests.sh, prow/scripts/cluster-integration/kyma-busola-long-lasting.sh, prow/scripts/lib/kyma.sh
- Removing isBEB flag
Related: https://github.com/orgs/kyma-project/projects/3#card-63833306
=> Removing isBEB flag

development/tools/cmd/externalsecretschecker/README.md
=> External secrets: add checker docs

prow/jobs/test-infra/buildpack.yaml, templates/data/buildpack-data.yaml
Adding prowjob building ciforcebot image.
=> Closefailingtestinstance build prowjob

.gitignore, development/gcp/cloud-functions/getGithubIssue/go.mod, development/gcp/cloud-functions/getfailureinstancedetails/go.mod, go.mod
=> add missing go.mod

prow/images/bootstrap/Dockerfile, prow/images/kyma-integration/Dockerfile
=> Update cosign to 1.0.0

prow/images/buildpack-golang/Dockerfile
=> Update base image in buildpack golang

prow/scripts/cluster-integration/kyma-gke-upgrade.sh
- use `PROVISION_REGIONAL_CLUSTER` during cluster creation
=> GKE upgrade: add missing flag

milv.config.yaml, prow/cluster/resources/external-secrets/README.md
- add readme for external secrets syncer
#3930
=> External secrets: add readme

development/tools/pkg/release/github.go
- ...
- ...
- ...
https://docs.github.com/en/developers/apps/building-github-apps/authenticating-with-github-apps
#3987
=> Github release: use token authorization

development/gcp/pkg/cloudfunctions/logging.go
Init LogEntry map if nil before assignement.
=> init LogEntry.Labels map if nil

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml, templates/data/kyma-integration-data.yaml
=> Fast integration: fix weekly schedule

prow/images/prow-tools/Dockerfile
- Bump Dockerfile base image due to CVE issues reported
- ...
- ...
https://sapjira.wdf.sap.corp/browse/CMP-723
=> Bump golang version in prow-tools

prow/images/buildpack-golang/Dockerfile, prow/images/buildpack-golang/Makefile
- Bump golang version due to CVE issues in the current one
- ...
- ...
https://github.com/kyma-project/test-infra/pull/4000
=> Bump buildpacks for golang

prow/jobs/test-infra/image-syncer.yaml, templates/data/image-syncer-data.yaml
Add required preset for new image-syncer code `preset-kyma-kms-sign-key: "true"` which defines KMS key for signing images.
#3975
=> add preset-kyma-kms-sign-key for image-syncer

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml, templates/data/kyma-integration-data.yaml
- change regexp to include all `^gke-` disks, including `gke-commit` and `gke-pr`
#3915
=> Orphaned disk cleaner: change regexp

prow/cluster/resources/external-secrets/README.md
=> Fix formatting

development/tools/cmd/ipcleaner/main.go
=> IP cleaner: more meaningful regex name

prow/jobs/kyma/kyma-integration-gardener.yaml, templates/data/kyma-integration-gardener-data.yaml
It caused the `run_if_changed` option to not be applied and end up in jobs not executing automatically.
=> Remove extra intendation near run_if_changed field

development/tools/cmd/ipcleaner/README.md
- update documentation for ip cleaner
#4009
=> IP cleaner: update documentation

prow/jobs/kyma/skr-svcat-migration.yaml, templates/data/skr-svcat-migration-data.yaml
=> skr-azure-svcat-migration-dev: run every 4 hours

prow/cluster/resources/external-secrets/external_secrets_workloads.yaml, prow/config.yaml, templates/templates/prow-config.yaml
Added externalSecret for gcp logging client key.
Added gcp logging prow preset.
=> gcp logging client externalSecret and prow preset.

development/gcp/cloud-functions/getGithubIssue/go.mod
Updated test-infra module version.
=> test-infra dependency update

development/gcp/cloud-functions/getfailureinstancedetails/getfailureinstancedetails.go, development/gcp/cloud-functions/getfailureinstancedetails/go.mod, development/gcp/pkg/cloudfunctions/logging.go
Fix bugs.
Prevent assigning nil values.
=> Get failure instance details fix

prow/scripts/unstale-gardener-project.sh
=> Gardener unstale: fix script

prow/scripts/cluster-integration/compass-gke-benchmark.sh, prow/scripts/cluster-integration/compass-gke-integration.sh
**Add new template mappings for compass tests**
- add  new system fetcher template mappings for tests
=> Add new template mappings for compass tests

development/tools/cmd/usersmapchecker/main.go
Removeing link from log message.
=> Remove link from log message.

prow/jobs/cli/cli-integration.yaml, templates/data/cli-data.yaml
- ...
- ...
- ...
https://github.com/kyma-project/test-infra/issues/4033
=> Fix integration jobs for cli

development/tools/cmd/usersmapchecker/main.go
setting correct exit code on success
added comments to the code
=> fixed setting exitcode on success

prow/jobs/test-infra/kyma-bot.yaml, templates/data/kyma-bot-data.yaml
Update to use postsubmit image.
=> Use postsubmit image.

prow/scripts/provision-vm-cli.sh, vpath/pjtester.yaml
=> CLI k3d: fix k3d provisioning

prow/scripts/cluster-integration/compass-gke-benchmark.sh, prow/scripts/cluster-integration/compass-gke-integration.sh
Reverts kyma-project/test-infra#4044
=> Revert "Add new template mappings for compass tests"

development/tools/cmd/rendertemplates/README.md, templates/README.md
- update documentation regarding pre and postConfigs
#4036
=> Rendertemplates: update documentation

development/image-syncer/external-images.yaml
=> Upgrade Cypress to 8.3.0 version

prow/config.yaml, prow/jobs/kyma/skr-integration.yaml, prow/jobs/kyma/skr-svcat-migration.yaml, templates/data/skr-integration-data.yaml, templates/data/skr-svcat-migration-data.yaml, templates/templates/prow-config.yaml, vpath/pjtester.yaml
- configures subaccount id for svcat migration job
=> Configure subaccountid for svcat migration test

prow/config.yaml, templates/templates/prow-config.yaml
Add hydra-login-consent squash method to tide
=> Add hydra-login-consent squash method to tide

development/image-syncer/external-images.yaml
- include fluent-bit image in the external images
=> Add fluent-bit image

development/tools/jobs/kyma/kyma_gardener_integration_test.go, prow/jobs/kyma/kyma-integration-gardener.yaml, prow/jobs/kyma/skr-integration.yaml, templates/data/kyma-integration-gardener-data.yaml, templates/data/skr-integration-data.yaml, test-inventory-integration.md
=> reenable AWS jobs

development/tools/cmd/gcrcleaner/README.md
- add documentation for GCR cleaner
#4061
=> Add GCR cleaner docs

development/tools/jobs/kyma/components_test.go, development/tools/jobs/tester/tester.go, prow/jobs/kyma/components/function-controller/function-controller-generic.yaml, templates/config.yaml, templates/data/generic_component_data.yaml, vpath/pjtester.yaml
- use temporary build buildpack from this [PR](https://github.com/kyma-project/test-infra/pull/4060) to be able to run `pre-main-function-controller` unit tests, because those tests required `libgit2-dev` in version `1.1`
=> Fn controller buildpack change

prow/jobs/kyma/kyma-integration-gardener.yaml, prow/scripts/cluster-integration/helpers/integration-tests.sh, prow/scripts/cluster-integration/kyma-integration-gardener.sh, templates/data/kyma-integration-gardener-data.yaml, vpath/pjtester.yaml
- Since Kyma 2.0 won't include Dex, we need to change our JWT tests in api-gateway.
See also [#11493](https://github.com/kyma-project/kyma/issues/11493)
=> Remove Dex from API-Gateway tests

prow/scripts/cluster-integration/compass-gke-benchmark.sh, prow/scripts/cluster-integration/compass-gke-integration.sh
Reverts kyma-project/test-infra#4052
=> Revert "Revert "Add new template mappings for compass tests""

prow/jobs/kyma/kyma-integration-gardener.yaml, templates/data/kyma-integration-gardener-data.yaml
- Added Kyma major version field
=> add missing kyma major version

prow/jobs/kyma/skr-svcat-migration.yaml, templates/data/skr-svcat-migration-data.yaml
- introducing periodic test that will mimic svcat migration, performed on AWS instead of azure
- https://github.tools.sap/kyma/backlog/issues/1656
=> edit svcat prow job to be run on aws instead of azure

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml, templates/data/kyma-integration-data.yaml
- add Kyma version info for fast-integration tests
- remove Slack channel override
https://github.com/kyma-project/kyma/issues/11777
=> Fast integration: update notifications

prow/jobs/kyma/kyma-integration-gardener.yaml, templates/data/kyma-integration-gardener-data.yaml
- Add kyma major version as 2 for Busola pipelines
=> Add kyma major version for Busola pipelines

prow/images/kyma-integration/Makefile
=> Remove k8s version from tag in kyma-integration

development/tools/jobs/tester/tester.go, prow/jobs/busola/busola-backend/backend-deployment-check.yaml, prow/jobs/busola/busola-web/web-deployment-check.yaml, prow/jobs/busola/integration-test.yaml, prow/jobs/cli/cli-integration.yaml, prow/jobs/control-plane/control-plane-gke-integration.yaml, prow/jobs/control-plane/control-plane-gke-provisioner-integration.yaml, prow/jobs/incubator/compass/compass-gke-benchmark.yaml, prow/jobs/incubator/compass/compass-gke-integration.yaml, prow/jobs/kyma/kyma-gardener-cleanup.yaml, prow/jobs/kyma/kyma-gke-external-registry.yaml, prow/jobs/kyma/kyma-integration-gardener.yaml, prow/jobs/kyma/kyma-integration.yaml, prow/jobs/kyma/kyma-upgrade-gardener.yaml, prow/jobs/kyma/releases/kyma-release-20.yaml, prow/jobs/kyma/skr-integration.yaml, prow/jobs/kyma/skr-svcat-migration.yaml, prow/jobs/scans/protecode-guard.yaml, prow/jobs/test-infra/pjtester.yaml, prow/jobs/test-infra/prow-periodics.yaml, prow/jobs/test-infra/unstale-gardener-project.yaml, templates/config.yaml
Bump `kyma-integration` image to `eu.gcr.io/kyma-project/test-infra/kyma-integration:v20210906-858d6909`. I've didn't edit the old `kyma-release` YAMLs.
=> Bump kyma-integration image

prow/jobs/kyma/kyma-integration.yaml, templates/data/kyma-integration-data.yaml
=> Make pre-main-kyma-integration-k3d-compass-dev optional

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml, templates/data/kyma-integration-data.yaml, vpath/pjtester.yaml
=> Add GCR cleaner job

development/tools/pkg/gcrcleaner/cleaner.go, development/tools/pkg/gcrcleaner/cleaner_test.go
- Make exceptions optional, as expected
#2530
=> GCR cleaner: allow for empty exclude expression

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml, templates/data/kyma-integration-data.yaml
- Remove unneeded exclude list
#2530
=> GCR cleaner: remove excludes

prow/scripts/cluster-integration/compass-gke-benchmark.sh, prow/scripts/cluster-integration/compass-gke-integration.sh, vpath/pjtester.yaml
Kyma installation fails for Compass PRs:
- Additional apply for Kyma installation resources.
This approach is a workaround - the best one would be to apply the CRD first, as a standalone file, and then create the Installation resource.
=> Fix Kyma installation for Compass resources 

prow/scripts/cluster-integration/control-plane-gke-integration.sh, prow/scripts/cluster-integration/kyma-gke-release-candidate.sh, prow/scripts/cluster-integration/kyma-gke-upgrade.sh
=> Workaround for new kubectl version

prow/jobs/helm-broker/helm-broker.yaml, prow/jobs/incubator/dex/dex.yaml, templates/data/helm-broker-data.yaml, templates/data/incubator-dex-data.yaml
=> Add KMS key to jobs

prow/jobs/busola/busola-backend/busola-backend.yaml, prow/jobs/busola/busola-web/busola-web.yaml, prow/jobs/busola/busola.yaml, templates/data/generic_component_busola_data.yaml
=> Make Busola test run on makefile change

prow/jobs/kyma/kyma-preview.yaml, templates/data/kyma-preview-data.yaml
- introducing periodic test that will test kyma preview version with standard skr-test suite
- https://github.tools.sap/kyma/backlog/issues/1686
=> 1686   change preview plan to test skr

development/tools/jobs/incubator/reconciler/reconciler_test.go, prow/jobs/incubator/reconciler/reconciler.yaml, templates/data/incubator-buildpack-data.yaml
- Make e2e job for reconciler optional
=> Make e2e job for reconciler optional

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml, prow/scripts/cluster-integration/cluster-users-integration-k3d.sh, prow/scripts/provision-vm-and-start-cluster-users-k3d.sh, templates/data/kyma-integration-data.yaml, test-inventory-integration.md, vpath/pjtester.yaml
making `cluster-users` ready for Kyma 2
Related issue:
https://github.com/kyma-project/kyma/issues/11643
=> modify cluster-user test jobs to run on kyma2

development/tools/jobs/testinfra/branchprotector_test.go, prow/config.yaml, templates/templates/prow-config.yaml
=> Fix kyma-showcase spelling

development/tools/jobs/incubator/varkes/varkes_test.go, prow/jobs/incubator/varkes/varkes.yaml, templates/data/incubator-buildpack-data.yaml
We will simplify the release process of varkes by simply tagging with release versions instead of using branches
- ...
- ...
- ...
=> adjust varkes release process

prow/jobs/incubator/reconciler/reconciler.yaml, templates/data/incubator-buildpack-data.yaml
- Silence reconciler periodic e2e job until it is stable
=> Silence reconciler periodic e2e job until it is stable

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml, templates/data/kyma-integration-data.yaml
=> Update cleaner regex

prow/scripts/cluster-integration/kyma-aks-long-lasting.sh, prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
=> Fix long-lasting jobs

development/tools/jobs/third-party-images/kaniko_executer_test.go, prow/jobs/third-party-images/third-party-images.yaml, templates/data/third-party-images-data.yaml
- Add build jobs for third-party-images/kaniko_executer
- Add tests for build jobs for third-party-images/kaniko_executer
=> Add build jobs and test for third-party-images/kaniko_executer

prow/jobs/kyma/kyma-preview.yaml, templates/data/kyma-preview-data.yaml
- let prowjob execute every four hours
\-
=> change kyma-preview prow job to execute every four hours

prow/images/bootstrap/Dockerfile
- add spectral tool to validate oapi
=> add spectral tool

development/image-syncer/external-images.yaml
Bump alpine image to 3.14.2
Required to resolve cves
=> bump alpine to 3.14.2

prow/jobs/kyma/releases/kyma-release-124.yaml, prow/scripts/cluster-integration/kyma-gke-release-candidate.sh, vpath/pjtester.yaml
- Call eventing fast integration on release
=> Call eventing fast-integration on release

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml, prow/scripts/cluster-integration/kyma-gke-long-lasting.sh, templates/data/kyma-integration-data.yaml, test-inventory-integration.md
Test prow-job: https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/adamwalach_test_of_prowjob_kyma-gke-nightly/1440705611485417472
- ...
- ...
- ...
=> Re-enable nightly to fix sec scans

prow/jobs/incubator/compass-console/compass/compass-ui.yaml, prow/jobs/incubator/compass/components/connectivity-adapter/connectivity-adapter-generic.yaml, prow/jobs/incubator/compass/components/connector/connector-generic.yaml, prow/jobs/incubator/compass/components/director/director-generic.yaml, prow/jobs/incubator/compass/components/external-services-mock/external-services-mock-generic.yaml, prow/jobs/incubator/compass/components/gateway/gateway-generic.yaml, prow/jobs/incubator/compass/components/operations-controller/operations-controller-generic.yaml, prow/jobs/incubator/compass/components/pairing-adapter/pairing-adapter-generic.yaml, prow/jobs/incubator/compass/components/schema-migrator/schema-migrator-generic.yaml, prow/jobs/incubator/compass/components/system-broker/system-broker-generic.yaml, prow/jobs/incubator/compass/tests/compass-e2e-tests/compass-e2e-tests.yaml, prow/jobs/incubator/ord-service/components/ord-service/ord-service-generic.yaml, templates/data/generic_component_compass_data.yaml, vpath/pjtester.yaml
- Add hotfix branch for Compass components, as needed by Compass hotfix process.
- https://github.com/kyma-incubator/compass/pull/2020
=> Add hotfix branch for Compass components

development/image-syncer/external-images.yaml
bumping postgres to 11.13-alpine
=> bumping postgres to 11.13-alpine

prow/scripts/cluster-integration/helpers/integration-tests.sh
=> Update Kyma installation method

prow/scripts/cluster-integration/helpers/reconciler.sh, vpath/pjtester.yaml
=> Pass domain to components in e2e-test

prow/images/buildpack-golang/Dockerfile
- Benchstat is needed by the Compass benchmark tests, and needs to be explicitly added.
=> Add benchstat to buildpack-golang

prow/cluster/resources/external-secrets/external_secrets_workloads.yaml, prow/config.yaml, templates/templates/prow-config.yaml
=> Add kcp-tech-user secret

development/tools/jobs/incubator/reconciler/reconciler_test.go, prow/jobs/incubator/reconciler/reconciler.yaml, prow/scripts/cluster-integration/helpers/reconciler.sh, prow/scripts/cluster-integration/reconciler-gardener-long-lasting.sh, prow/scripts/lib/gardener/gardener.sh, prow/scripts/resources/reconciler/shoot-template.yaml, templates/data/incubator-buildpack-data.yaml, vpath/pjtester.yaml
- Add reconciler nightly job for cluster creation and deletion which will be in turn used by the reconciler nightly e2e job to periodically test reconciliation flow with fast integration test. 
https://github.com/kyma-incubator/reconciler/issues/75
=> Add reconciler nightly job for cluster

prow/scripts/cluster-integration/helpers/reconciler.sh, vpath/pjtester.yaml
- Changed `exit 0` to `break` inside the loop to stop prow job from terminating.
- [Example job run](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/mfaizanse_test_of_prowjob_periodic-main-kyma-incubator-reconcil/1442473829820534784)
=> Fixed bug for reconciler periodic job

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml, templates/data/kyma-integration-data.yaml, test-inventory-integration.md
=> Reenable fast-integration tests on nightly

prow/images/kyma-integration/Dockerfile
- adds kcp-cli to integration image
- https://github.tools.sap/kyma/backlog/issues/1823
=> add kcp-cli to kyma integration image

prow/images/kyma-integration/Dockerfile
=> add commit id to kcpcli version

prow/jobs/kyma/kyma-integration.yaml, templates/data/kyma-integration-data.yaml
- Make compass jobs optional until they are fixed
=> Temporarily make compass jobs optional

prow/jobs/incubator/compass/compass-gke-benchmark.yaml, prow/scripts/cluster-integration/compass-gke-benchmark.sh, templates/data/compass-gke-benchmark-data.yaml
- use image that have `benchstat` installed
- include `kyma.sh` for missing function
=> fix compass-gke-benchmark jobs

development/tools/jobs/kyma/kyma_gardener_integration_test.go, prow/jobs/kyma/kyma-integration-gardener.yaml, prow/scripts/cluster-integration/helpers/eventing.sh, prow/scripts/cluster-integration/kyma-integration-gardener-eventing.sh, templates/data/kyma-integration-gardener-data.yaml, test-inventory-integration.md, vpath/pjtester.yaml
- added back pre-main-kyma-gardener-gcp-eventing
- Changed job to use Kyma deploy instead of kyma install
- Changed to use Eventing specific E2E fast-integration tests
[Example Job run](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/12156/mfaizanse_test_of_prowjob_pre-main-kyma-gardener-gcp-eventing/1442415497755758592)
- Dependent on PR: https://github.com/kyma-project/kyma/pull/12156
=> added back pre-main-kyma-gardener-gcp-eventing with kyma deploy

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml, templates/data/kyma-integration-data.yaml
=> Fast-integration: use Kyma 2 tests

prow/cluster/resources/external-secrets/external_secrets_workloads.yaml, prow/config.yaml, prow/jobs/kyma/kyma-integration-gardener.yaml, templates/templates/prow-config.yaml
=> Add oidc credentials

development/tools/jobs/kyma/kyma_gardener_integration_test.go, prow/jobs/kyma/kyma-integration-gardener.yaml, templates/data/kyma-integration-gardener-data.yaml
- Made pre-main-kyma-gardener-gcp-eventing job optional
=> Made pre-main-kyma-gardener-gcp-eventing job optional

development/tools/jobs/kyma/kyma_gardener_cleanup_test.go, prow/jobs/kyma/kyma-gardener-cleanup.yaml, templates/data/kyma-gardener-cleanup-data.yaml
- Exclude rec-nightly(which is used for long running tests for reconciler) cluster from deletion
=> Exclude rec-nightly cluster from deletion

development/image-syncer/external-images.yaml
- bump sb-proxy-k8s image version to v0.9.1
=> Bump sb-proxy-k8s to v0.9.1

prow/scripts/resources/reconciler/shoot-template.yaml
- Fine tune cluster size for reconciler nightly job
=> Fine tune cluster size for reconciler nightly job

development/image-syncer/external-images.yaml
=> Upgrade Cypress to 8.5.0 version

prow/scripts/cluster-integration/reconciler-gardener-long-lasting.sh
- Disable istio sidecar for reconciler ns
=> Disable istio sidecar injection for reconciler ns

development/tools/jobs/incubator/reconciler/reconciler_test.go, prow/jobs/incubator/reconciler/reconciler.yaml, prow/scripts/cluster-integration/reconciler-integration-k3d.sh, prow/scripts/provision-vm-and-start-reconciler-k3d.sh, templates/data/incubator-buildpack-data.yaml, vpath/pjtester.yaml
- Create reconciler integration job 
See https://github.com/kyma-incubator/reconciler/issues/206
=> Create reconciler integration job

development/tools/jobs/incubator/reconciler/reconciler_test.go, prow/jobs/incubator/reconciler/reconciler.yaml, prow/scripts/cluster-integration/helpers/reconciler.sh, prow/scripts/cluster-integration/reconciler-e2e-nightly-gardener.sh, templates/data/incubator-buildpack-data.yaml, vpath/pjtester.yaml
- Introduce nightly e2e test job for reconciler
See https://github.com/kyma-incubator/reconciler/issues/75
=> Introduce nightly e2e test job for reconciler

.github/pull-request-template.md, docs/prow/prow-installation-on-forks.md
=> Fixed dead links

prow/scripts/lib/kyma.sh
Fix for https://github.com/kyma-project/kyma/issues/12254
=> Remove reuse-values flag

prow/jobs/kyma/kyma-integration.yaml, templates/data/kyma-integration-data.yaml
- ...
- ...
- ...
https://github.com/kyma-project/kyma/issues/12239
=> Disable reporting for kyma-integration-k3d-compass-dev job

prow/scripts/cluster-integration/kyma-aks-long-lasting.sh, prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
Provisioning fails: https://storage.googleapis.com/kyma-prow-logs/logs/kyma-gke-nightly/1444844850330472448/build-log.txt
I think it was removed in this PR: https://github.com/kyma-project/cli/pull/1000/files
- timeout flag removed
=> Remove timeout flag from CLI

prow/scripts/cluster-integration/serverless-integration-k3s.sh
- ...
- ...
- ...
https://github.com/kyma-project/cli/pull/1000/files
=> Remove atomic flag from serverless script

development/github/pkg/client/client.go
Improved format of creating wrapping github clients and calling it's methods.
=> cleaner composition and methods calls

prow/cluster/resources/external-secrets/external_secrets_workloads.yaml
=> Add tunas secret for event mesh

prow/scripts/cluster-integration/helpers/reconciler.sh, vpath/pjtester.yaml
- Add logs when timeout while reconciliation
- Minor refactor
=> Add logs when timeout while reconciliation

prow/scripts/provision-vm-cli.sh, vpath/pjtester.yaml
Remove k3d installation since it's already a part of the VM image.
=> Fix kyma2 cli integration job

prow/scripts/cluster-integration/kyma-busola-long-lasting.sh
=> Remove init params from Busola

prow/jobs/kyma/releases/kyma-release-20.yaml, templates/data/kyma-release-data.yaml
- Use the new Event Mesh secret for release-candidate Prow job
=> use release testing EMS account

prow/scripts/cluster-integration/serverless-integration-k3s.sh, vpath/pjtester.yaml
- Remove k3d install from pre-main-serverless-integration-alpha-k3s
=> Remove k3d install from pre-main-serverless-integration-alpha-k3s

prow/scripts/build-kyma-artifacts.sh
=> Clean up build kyma artifacts

development/github/pkg/client/client.go
Added missing method for getting commiter for branch HEAD.
=> Added get commit for branch

prow/scripts/cluster-integration/kyma-integration-k3d-compass-components.yaml
- update component list for compass tests
https://github.com/kyma-project/kyma/issues/12304
=> Fix component list (istio-configuration)

prow/scripts/cluster-integration/compass-gke-integration.sh
**Skip ssl for compass connector gke integration tests**
=> Skip ssl for compass connector gke integration tests

prow/scripts/cluster-integration/compass-gke-integration.sh
**Add ord aggregator skip ssl validation for tests**
=> Add ord aggregator skip ssl validation for tests

prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
=> Clean up nightly script

prow/jobs/kyma/kyma-integration.yaml, prow/scripts/cluster-integration/serverless-integration-k3s.sh, prow/scripts/provision-vm-and-start-serverless-k3s.sh, templates/data/kyma-integration-data.yaml, test-inventory-integration.md, vpath/pjtester.yaml
=> Remove old serverless job

development/tools/pkg/pjtester/pjtester_test.go, development/tools/pkg/pjtester/test_artifacts/pjtester.yaml
=> Fix pjtester tests

development/tools/cmd/githubissues/README.md
- Add manual what to do in case of schema inconsistencies
#4307
=> Update githubissues documentation

prow/jobs/kyma/releases/kyma-release-124.yaml, prow/scripts/cluster-integration/kyma-gke-upgrade.sh
=> Update release-1.24 jobs to use container os with Docker

prow/jobs/test-infra/validation.yaml, templates/data/validation-data.yaml
=> Fix hadolint wildcard arg

prow/config.yaml, templates/templates/prow-config.yaml
Add website-vuepress repo to tide
- Added website-vuepress repo to config.yaml
- Added website-vuepress repo to prow-config.yaml
=> Add website-vuepress repo to tide

development/image-syncer/external-images.yaml
- added nats:2.6.1-alpine to image-syncer
=> added nats:2.6.1-alpine to image-syncer

prow/scripts/cluster-integration/kyma-gke-external-registry.sh, vpath/pjtester.yaml
=> GKE-external-registry: fail job if the tests fail

prow/scripts/cluster-integration/kyma-gke-long-lasting.sh, prow/scripts/cluster-integration/kyma-gke-release-candidate.sh
=> Fix image list generation

prow/scripts/cluster-integration/kyma-gke-long-lasting.sh, prow/scripts/cluster-integration/kyma-gke-release-candidate.sh
=> Fix image list generation on release 1.24

prow/scripts/provision-vm-and-start-busola-docker.sh, prow/scripts/provision-vm-and-start-busola-k3s.sh
=> Remove --async argument from gcloud delete command

prow/jobs/kyma/skr-kyma-to-kyma2-upgrade-aws.yaml, templates/data/skr-kyma-to-kyma2-upgrade-aws-data.yaml
=> bump kyma release candidate version for skr-kyma-to-kyma2-upgrade-aws-dev prow job

prow/jobs/test-infra/buildpack.yaml, prow/jobs/test-infra/validation.yaml, templates/data/buildpack-data.yaml, templates/data/validation-data.yaml
=> Add image-url-helper tests

prow/scripts/provision-vm-and-start-busola-docker.sh
=> Fix jobguard for post-busola-smoke-test-docker

prow/jobs/kyma/skr-kyma-to-kyma2-upgrade-aws.yaml, templates/data/skr-kyma-to-kyma2-upgrade-aws-data.yaml
=> switch kyma upgrade version

prow/images/kyma-integration/Dockerfile
=> bump kcp version in kyma-integration image

development/image-url-helper/cmd/list.go, development/image-url-helper/pkg/list/outputjson.go
=> Image-url-helper: exclude test images from list

development/tools/jobs/incubator/reconciler/reconciler_test.go, prow/jobs/incubator/reconciler/reconciler.yaml, prow/scripts/cluster-integration/helpers/reconciler.sh, prow/scripts/cluster-integration/reconciler-e2e-gardener.sh, prow/scripts/cluster-integration/reconciler-e2e-upgrade-gardener.sh, prow/scripts/cluster-integration/reconciler-gardener-long-lasting.sh, templates/config.yaml, templates/data/incubator-buildpack-data.yaml, vpath/pjtester.yaml
- Deploy reconciler charts from control-plane
See https://github.com/kyma-incubator/reconciler/issues/234
=> Deploy reconciler charts from control-plane

development/image-url-helper/README.md
- added documentation for `image-url-helper` tool
=> Add documentation for image-url-helper

development/image-url-helper/cmd/check.go
- Fix excludes not working if the resources path was provided with trailing slash
=> Image-url-helper: fix exclude list

prow/jobs/kyma/kyma-gke-external-registry.yaml, templates/data/kyma-gke-external-registry-data.yaml
=> set gke-external as optional

development/image-syncer/external-images.yaml
- download version 0.9.0 to internal registry
- ...
- ...
=> bump nats exporter image version

development/image-syncer/external-images.yaml
- change image to oryd/hydra-sqlite for the support of in-memory mode
=> Allign Ory Hydra image

development/image-syncer/README.md
- added note about tags being immutable
- ...
- ...
=> Update readme for image-syncer

changelog-generator/app/config-cleanup.sh, changelog-generator/app/config-git.sh, changelog-generator/app/config-setup.sh, changelog-generator/app/generate-full-changelog.sh, changelog-generator/app/generate-release-changelog.sh, changelog-generator/app/push-full-changelog.sh
=> Add double quotes to vars to fix SC2086

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml, templates/data/kyma-integration-data.yaml
- Do not run fast integration tests when the cluster is reprovisioned
=> Update fast-integration nightly cron

development/custom-image/install-deps-debian.sh, prow/scripts/cluster-integration/kyma-integration-k3d.sh, prow/scripts/cluster-integration/reconciler-integration-k3d.sh, prow/scripts/cluster-integration/serverless-integration-k3s.sh, prow/scripts/provision-vm-cli.sh
This reverts commit adce2dc9ae10ffcb0abe5191cf6790bd833fb50a.
- ...
- ...
- ...
=> Revert "Temporary switch to alpha provision cmd to use k3d v5 (#4427)"

changelog-generator/app/generate-full-changelog.sh, prow/scripts/cluster-integration/helpers/cleanup-gardener.sh, prow/scripts/compatibility-cli.sh, prow/scripts/lib/azure.sh
Solving SC2059, SC2213, and SC2206.
=> Fix shellcheck errors 2

prow/jobs/scans/protecode-guard.yaml, templates/data/protecode-guard-data.yaml
=> Add job-guard-for-reconciler

development/image-syncer/external-images.yaml
In order to fix vulnerabilities we update the operator dependency in kyma: prometheus-operator-reloader,
which is using a newer go runtime.
- https://github.com/kyma-project/kyma/pull/12607
=> Get latest prometheus-config-reloader image

prow/scripts/cluster-integration/kyma-gke-long-lasting.sh, prow/scripts/lib/kyma.sh
=> Update Kyma version to 1.24.8

development/image-syncer/external-images.yaml
Upgrade Cypress to 9.0.0 version: docs.cypress.io/guides/references/changelog#9-0-0
https://github.com/kyma-project/busola/issues/554
=> Upgrade Cypress to 9.0.0 version

prow/jobs/busola/integration-docker-test.yaml, templates/data/busola-integration-test-docker-data.yaml
=> Make optional Busola Cypress Docker tests

prow/jobs/kyma/skr-kyma-to-kyma2-upgrade-aws.yaml, templates/data/skr-kyma-to-kyma2-upgrade-aws-data.yaml
=> Bump KYMA_UPGRADE_VERSION to 2.0.0-rc5

development/image-syncer/external-images.yaml
- updated jimmidyson/configmap-reload to 0.5.0
- ...
- ...
=> update to newest configmap reloader for prometheus

prow/scripts/compatibility-cli.sh
=> Fix reading arrays in newline seperated string

changelog-generator/app/config-setup.sh, changelog-generator/app/generate-full-changelog.sh, changelog-generator/app/generate-release-changelog.sh, development/image-syncer/before-commit.sh, development/image-url-helper/before-commit.sh, development/jobguard/scripts/run.sh, development/kyma-ci-force-bot/ciforcebot/before-commit.sh, development/kyma-github-connector/githubWebhookGateway/before-commit.sh, development/kyma-pubsub-connector/pubSubGateway/before-commit.sh, development/prow-installer/before-commit.sh, development/prowjobparser/before-commit.sh, prow/scripts/cluster-integration/helpers/eventing.sh, prow/scripts/cluster-integration/helpers/integration-tests.sh, stability-checker/before-commit.sh, watch-pods/before-commit.sh
Solving SC2164, SC2191, SC2196, SC2112, and SC2034.
=> Fix shellcheck errors 3

development/image-syncer/external-images.yaml
=> Downgrade Cypress to 8.7.0 version

prow/scripts/resources/busola/cluster-busola.yaml, prow/scripts/resources/busola/cluster-kyma.yaml
- Bump Kubernetes to a supported version
=> Bump kubernetes version for Busola jobs

prow/scripts/resources/busola/cluster-kyma.yaml
=> Enable DNS Providers for nkyma

development/image-syncer/external-images.yaml
=> Add Google pause image registry to external

development/image-url-helper/cmd/image_url_helper.go, development/image-url-helper/cmd/promote.go, development/image-url-helper/pkg/promote/promote.go, go.mod
=> Image-url-helper: add promote command

prow/jobs/kyma/skr-kyma-to-kyma2-upgrade-aws.yaml, templates/data/skr-kyma-to-kyma2-upgrade-aws-data.yaml
=> Fix cron expression for skr-kyma-to-kyma2-upgrade-aws-dev

prow/jobs/kyma/skr-kyma-to-kyma2-upgrade-aws.yaml, templates/data/skr-kyma-to-kyma2-upgrade-aws-data.yaml
- bump skr-upgrade test to 2.0.0-rc6
=> bump kyma upgrade test version to 2.0.0-rc6

development/github/pkg/client/types.go
- Add IssueTransferredEvent type to github client package. This add support for correct changed keys in webhook json payload.
See https://github.com/kyma-project/test-infra/issues/4035
=> Add IssueTransferredEvent type to kyma GitHub client.

go.mod, go.sum
Added missing dependency to go.mod.
=> Added go-github/v40. Fixing go compile errors.

prow/jobs/kyma/kyma-integration.yaml, templates/data/kyma-integration-data.yaml
- Jobs are green:
- https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-integration-k3d-compass-dev
- https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-kyma-integration-k3d-central-app-connectivity-compass
#4187
=> Make Compass jobs mandatory

prow/config.yaml, templates/templates/prow-config.yaml
- do not block dependabot from updating its own branches
=> Exclude dependabot branches from being protected

prow/scripts/lib/kyma.sh
=> Fix upgrade pipeline

prow/scripts/cluster-integration/compass-gke-benchmark.sh, prow/scripts/cluster-integration/compass-gke-integration.sh
**apply compass gke integration overrides from compass repo file**
=> apply compass gke integration overrides from compass repo file

development/image-syncer/external-images.yaml
- Update sha for postgresql 11.14
https://github.com/kyma-project/test-infra/pull/4475
https://github.com/kyma-project/kyma/issues/12680
=> Update postgresql 11.14-alpine sha

prow/config.yaml, templates/templates/prow-config.yaml
=> Don't protect dependabot branches

prow/jobs/kyma/components/kyma-operator/kyma-operator-generic.yaml, templates/data/generic_component_data.yaml
=> Enable Kyma Operator jobs for release 1.25

development/image-syncer/external-images.yaml
- update nats server image from 2.6.1 -> 2.6.5
=> update nats to 2.6.5

development/image-syncer/main.go, development/image-syncer/util.go
- Allow retagging when the source  image is not using SHA256
- Authenticate in the target repository, allows for pushing to non-public Artifact registry
https://github.com/kyma-project/test-infra/pull/4443
=> Image syncer: allow retagging tagged images

prow/jobs/scans/whitesource-periodics.yaml, templates/data/whitesource-periodics-data.yaml
Whitesource scans for website are no longer required
- removed job definition for website-whitesource-scan
=> Remove website-whitesource-scan

prow/scripts/cluster-integration/kyma-aks-long-lasting.sh, prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
- use local sources instead of a release
=> Kyma nightly 1.24: use local Kyma sources

development/image-url-helper/cmd/check.go, development/image-url-helper/cmd/list.go, development/image-url-helper/cmd/promote.go, development/image-url-helper/pkg/list/imagelister.go, development/image-url-helper/pkg/list/outputjson.go, development/image-url-helper/pkg/promote/externalsyncer.go, development/image-url-helper/pkg/promote/promote.go
- use maps of images instead of lists
- sort only when necessary
- add slash at the end of the promotion registry path if necessary
=> Image-url-helper: use maps of images

prow/scripts/cluster-integration/kyma-aks-long-lasting.sh, prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
This reverts commit 8b644b84ab1ba7e1597117795c2bcfbc052b5e5f.
- ...
- ...
- ...
=> Revert "Nightly: use local Kuma sources (#4510)"

prow/scripts/cluster-integration/kyma-integration-k3d.sh, prow/scripts/cluster-integration/reconciler-integration-k3d.sh, prow/scripts/cluster-integration/serverless-integration-k3s.sh, prow/scripts/provision-vm-cli.sh
Kyma CLI's `provision k3d` has been updated to work with k3d 5.x and can be used now.
* https://github.com/kyma-project/cli/issues/1092
=> Use new stable provision k3d cmd

prow/images/kyma-integration/Dockerfile
- Added yq and gh tools to kyma-integration image
=> Added yq and gh tools to kyma-integration image

prow/scripts/reconciler-publish-unstable-cli.sh, vpath/pjtester.yaml
- Commit changes so that the release script doesn't fail
=> Fix nightly-main-reconciler-publish-unstable-cli job

prow/scripts/cluster-integration/busola-integration-test-k3s.sh, prow/scripts/provision-vm-and-start-busola-k3s.sh, vpath/pjtester.yaml
We implemented a test for switching clusters in busola, so we need a second `kubeconfig`.
- Added getting `nbusola` kubeconfig,
- Added copying `kubeconfig` to fixture location.
=> Added copy nbusola

prow/scripts/cluster-integration/reconciler-e2e-nightly-gardener.sh, prow/scripts/cluster-integration/reconciler-gardener-long-lasting.sh, vpath/pjtester.yaml
- Use different names for nightly clusters
See https://github.com/kyma-incubator/reconciler/issues/493
=> Use different names for nightly clusters

prow/scripts/resources/debug-container.yaml
=> Enable privileged debug container for AWS and Azure

prow/jobs/kyma/releases/kyma-release-20.yaml, templates/data/kyma-release-data.yaml
Add release jobs that run fast-integration test against k3d clusters on release branches
=> Add release k3d jobs for kyma 2.0

prow/jobs/kyma/kyma-gke-external-registry.yaml, templates/data/kyma-gke-external-registry-data.yaml
- enable post job for kyma-gke-external-registry
-set kyma-gke-external-registry as required
=> Enable post job and make gke-external-registry required.

development/tools/jobs/cli/cli_test.go, prow/jobs/cli/cli.yaml, templates/data/cli-data.yaml
=> Run pre-kyma-cli on release branches

prow/scripts/cluster-integration/compass-gke-benchmark.sh, vpath/pjtester.yaml
Currently, if any benchmark test fails, the results of the next ones won't be printed
- Add "failed" flag in order to show all benchmark results instead of exiting on the first error
=> Analyze multiple benchmark tests in Cоmpass

development/image-url-helper/README.md
=> Image-url-helper: add documentation for promote command

prow/jobs/kyma/skr-kyma-to-kyma2-upgrade-aws.yaml, templates/data/skr-kyma-to-kyma2-upgrade-aws-data.yaml
- allow to explicitly set kymaVersion in upgrade pipeline
=> add kyma_version to upgrade test

development/image-syncer/external-images.yaml
=> update jaeger image to latest 1.29.0

prow/images/debug-commando/Dockerfile
- Bump base image to the latest one
#4558
=> Debug commando: bump base image to Go 1.17.5

development/tools/cmd/githubrelease/README.md
- fix dead link in the githubrealease README.md file for commitish value
- ...
- ...
=> fix dead link for commitish value

prow/cluster/components/monitoring/grafana_deployment.yaml
- ...
- ...
- ...
https://grafana.com/blog/2021/12/10/grafana-8.3.2-and-7.5.12-released-with-moderate-severity-security-fix/
=> Bump Grafana to 7.5.12

development/prowjobparser/main.go, prow/jobs/test-infra/validation.yaml, templates/data/validation-data.yaml
- Add prowjobparser validation job
- Fix prowjobparser compilation
#4576
=> Add prowjobparser job

development/kyma-ci-force-bot/kyma-ci-force-bot/prod-values.yaml, development/kyma-github-connector/githubConnectorChart/global-prod-values.yaml, development/kyma-github-connector/githubConnectorChart/templates/webhookGatewayConfigMap.yaml, development/kyma-github-connector/githubConnectorChart/values/sap.tools.github/backlog/prod-values.yaml, development/kyma-pubsub-connector/pubsubConnectorChart/global-prod-values.yaml, development/kyma-pubsub-connector/pubsubConnectorChart/templates/googleServiceAccountSecret.yaml, development/kyma-pubsub-connector/pubsubConnectorChart/values/oomevent.found/prod-values.yaml, development/kyma-slack-connector/issueLabeledFunction/handler.py, development/kyma-slack-connector/slackConnectorChart/global-prod-values.yaml, development/kyma-slack-connector/slackConnectorChart/templates/functionSubscription.yaml, development/kyma-slack-connector/slackConnectorChart/values/issuesevent.labeled/prod-values.yaml, development/kyma-slack-connector/slackConnectorChart/values/oomevent.found/prod-values.yaml, development/kyma-slack-connector/slackConnectorChart/values/prowjob.failed/prod-values.yaml
Changed subscription direction. Application in subscription is always app who publish events.
- Update image versions.
- Improved logging in slack connector handler for issuesevent.labeled function.
- Changed strategy of using application name in event mesh subscriptions.
=> Update tooling kyma workloads.

development/tools/jobs/kyma/kyma_gardener_integration_test.go, development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration-gardener.yaml, prow/jobs/kyma/kyma-integration.yaml, templates/data/kyma-integration-data.yaml, templates/data/kyma-integration-gardener-data.yaml
Currently the reconciler integration jobs are running between Tuesday and Saturday from 6am to 6pm every two hours. But we want them to run from Monday till Friday from 6am to 6pm every two hours.
=> Run Reconciler integration jobs form Monday till Friday

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml, templates/data/kyma-integration-data.yaml
VMs were not removed and because of that we hit a quota.
=> Add kyma-upgrade regexp for upgrade k3d jobs in VMs cleaner

prow/images/kyma-integration/Dockerfile
- update [smctl](https://github.com/Peripli/service-manager-cli/releases) to the latest version (v1.11.12)
=> Update smctl version to v1.11.12

prow/scripts/cluster-integration/compass-gke-integration.sh, vpath/pjtester.yaml
This PR provides Compass with patches to enable mTLS Prometheus scraping.
=> Add mTLS Prometheus patching

prow/jobs/cli/cli.yaml, prow/jobs/incubator/reconciler/reconciler.yaml, prow/jobs/kyma/kyma-integration-gardener.yaml, prow/jobs/kyma/kyma-integration.yaml, templates/config.yaml, templates/data/cli-data.yaml, templates/data/incubator-buildpack-data.yaml, templates/data/kyma-integration-data.yaml, templates/data/kyma-integration-gardener-data.yaml
- Notify Jellyfish slack channel in case of failures
See https://github.com/kyma-incubator/reconciler/issues/593
=> Notify Jellyfish slack channel in case of failures

.github/dependabot.yml, templates/data/dependabot-config-data.yaml
- Make all prefixes 15 characters long or fewer
https://github.com/kyma-project/test-infra/runs/4616195121
=> Dependabot: fix prefixes length

prow/jobs/test-infra/buildpack.yaml, prow/jobs/test-infra/image-syncer.yaml, prow/jobs/test-infra/test-log-collector.yaml, prow/jobs/test-infra/validation.yaml, templates/data/buildpack-data.yaml, templates/data/image-syncer-data.yaml, templates/data/test-log-collector-data.yaml, templates/data/validation-data.yaml
- Run tools tests when `go.mod`/`go.sum` is changed
- Build prow-tools image on `go.mod`/`go.sum` change
#4573
=> Go.mod: add testing

prow/cluster/resources/external-secrets/README.md
- Update external-secrets docs
=> Update external-secrets docs

development/tools/jobs/incubator/reconciler/reconciler_test.go, prow/jobs/incubator/reconciler/reconciler.yaml, templates/data/incubator-buildpack-data.yaml
adjust cron schedule for nightly-main-reconciler-e2e job
=> adjust cron schedule

development/image-url-helper/cmd/check.go, development/image-url-helper/cmd/list.go, development/image-url-helper/cmd/promote.go, development/image-url-helper/pkg/common/component.go, development/image-url-helper/pkg/common/images.go, development/image-url-helper/pkg/common/valuefile.go, development/image-url-helper/pkg/list/imagelister.go, development/image-url-helper/pkg/list/outputjson.go, development/image-url-helper/pkg/promote/externalsyncer.go, development/image-url-helper/pkg/promote/promote.go
- move parts used by all subcommands into its own `common` package
=> Image-url-helper refactor

prow/jobs/scans/protecode-guard.yaml, templates/data/protecode-guard-data.yaml
- temporary make failing jobs optional
=> temporarily make protecode jobs optional

prow/jobs/kyma/skr-svcat-migration.yaml, templates/data/skr-svcat-migration-data.yaml, vpath/pjtester.yaml
- Added `env` needed for initialising kcp client in fast integration tests 
[ #12941](https://github.com/kyma-project/kyma/pull/12941)
=> Add environmental variables for kcp client in fast integration tests

prow/jobs/scans/protecode-guard.yaml, templates/data/protecode-guard-data.yaml
- revert #4652, since these jobs are working properly now
=> make protecode jobs mandatory

prow/jobs/kyma/kyma-preview.yaml, templates/data/kyma-preview-data.yaml
- add label to kyma-preview prowjob for missing envs
=> Add missing label to kyma-preview prowjob

prow/jobs/kyma/kyma-validation.yaml, prow/scripts/generate-component-descriptors.sh, templates/data/kyma-validation-data.yaml, vpath/pjtester.yaml
- use binary version of the `image-url-helper` tool
- add `run_if_changed`
- use unified definition for both pre- and post-submit jobs
#4608
=> Update component descriptor jobs

prow/images/kyma-integration/Dockerfile
- Bump prow-tools with updated `image-url-helper` tool
#4608
=> Bump prow-tools image in kyma-integration Dockerfile

prow/jobs/kyma/kyma-validation.yaml, templates/data/kyma-validation-data.yaml
- use image that contains all needed tools (`jq`)
#4608
=> Component descriptor: use integration image

prow/config.yaml, templates/templates/prow-config.yaml
- set branch `develop` to protected
Failing job: https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/ci-prow-branchprotector/1480478177959612416
PR that broke this job execution: #4610
=> Branchprotector: fix reconciler protection rules

prow/jobs/kyma/kyma-integration.yaml, prow/jobs/kyma/kyma-validation.yaml, prow/jobs/kyma/releases/kyma-release-20.yaml, prow/jobs/kyma/releases/kyma-release-21.yaml, templates/data/kyma-integration-data.yaml, templates/data/kyma-release-data.yaml, templates/data/kyma-validation-data.yaml
- Fix testgrid tests in https://github.com/kubernetes/test-infra/pull/24156
=> Fix testgrid groups

development/tools/jobs/incubator/reconciler/reconciler_test.go, prow/jobs/incubator/reconciler/reconciler.yaml, prow/scripts/cluster-integration/helpers/reconciler.sh, prow/scripts/cluster-integration/reconciler-e2e-gardener.sh, prow/scripts/cluster-integration/reconciler-e2e-nightly-gardener.sh, prow/scripts/cluster-integration/reconciler-gardener-long-lasting.sh, prow/scripts/cluster-integration/reconciler-periodic-main-kyma-incubator-reconciler-kyma1-kyma2-upgrade.sh, templates/data/incubator-buildpack-data.yaml
- rename misleading function name
- rename command script to consistent with job name
- increase kubectl wait timeout
https://github.com/kyma-incubator/reconciler/issues/652
=> Increase periodic-main-kyma-incubator-reconciler-kyma1-kyma2-upgrade timeout

prow/scripts/resources/busola/cluster-busola.yaml, prow/scripts/resources/busola/cluster-kyma.yaml, prow/scripts/resources/reconciler/shoot-template.yaml
- bump gardenlinux to new version
=> Bump gardenlinux version

prow/scripts/resources/busola/cluster-busola.yaml, prow/scripts/resources/busola/cluster-kyma.yaml, prow/scripts/resources/reconciler/shoot-template.yaml
- Bump k8s version from `1.20.11` to `1.20.12`
#4685
=> Bump k8s version for Busola & Reconciler gardener

development/image-syncer/external-images.yaml
- Import the latest pushgateway image
=> Bump Prometheus pushgateway

prow/jobs/kyma/releases/kyma-release-20.yaml, prow/scripts/cluster-integration/kyma-gke-release-candidate.sh, prow/scripts/minikube-test.sh, prow/scripts/provision-vm-and-start-busola-docker.sh, prow/scripts/provision-vm-and-start-busola-k3s.sh, prow/scripts/provision-vm-and-start-kyma-k3d.sh, prow/scripts/provision-vm-and-start-reconciler-k3d.sh, prow/scripts/provision-vm-and-start-serverless-k3s.sh, prow/scripts/provision-vm-compass.sh, prow/scripts/provision-vm-control-plane.sh, templates/data/kyma-integration-data.yaml, templates/data/kyma-release-data.yaml
Cherry-picked https://github.com/kyma-project/test-infra/commit/f9046b1d66011110e08cb4beb2abc26e463209dd with edits to the scripts and added label fix-up for GCP labels.
=> Fix failing jobs on release branch

development/image-syncer/external-images.yaml
=> update kube-state-metrics image to v2.3.0

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml, templates/data/kyma-integration-data.yaml
=> Fix vm cleaner regexp

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml, templates/data/kyma-integration-data.yaml
=> Fix vm cleaner regexp for Busola

prow/jobs/kyma/skr-kyma-to-kyma2-upgrade-aws.yaml, templates/data/skr-kyma-to-kyma2-upgrade-aws-data.yaml, vpath/pjtester.yaml
The pipeline `skr-kyma-to-kyma2-upgrade-aws-dev` was broken due to a bug in the monitoring chart. This was fixed with https://github.com/kyma-project/kyma/pull/13011/files
- Changed Kyma upgrade version to `2.0.2`. See pipeline results:https://status.build.kyma-project.io/log?container=test&id=1481272953998938112&job=jeremyharisch_test_of_prowjob_skr-kyma-to-kyma2-upgrade-aws-dev
Fixes https://github.com/kyma-project/kyma/issues/12981
=> Upgrade Kyma-Upgrade-Version to 2.0.2 in skr-kyma-to-kyma2-upgrade-aws-dev

prow/images/clonerefs/Dockerfile
Reverts kyma-project/test-infra#4700
=> Revert "clonerefs(deps): bump k8s-prow/clonerefs from v20220107-c0207137f8 to v20220110-28076d3f8c in /prow/images/clonerefs"

development/image-syncer/external-images.yaml
- Add golang:1.17.6-alpine3.15 to external images
=> Add golang:1.17.6-alpine3.15 to external images

development/image-syncer/external-images.yaml
- pin golang image since it's force-pushed on the upstream, and we don't want to force update our images
#4728
=> Pin golang image

development/tools/cmd/vmscollector/main.go, development/tools/jobs/kyma/kyma_integration_test.go, development/tools/pkg/vmscollector/collector.go, development/tools/pkg/vmscollector/collector_test.go, prow/jobs/kyma/kyma-integration.yaml, templates/data/kyma-integration-data.yaml
- Change regexp from include to exclude
=> VMcollector: change regexp to exclude

prow/images/clonerefs/Dockerfile
Reverts kyma-project/test-infra#4725
=> Revert "clonerefs(deps): bump k8s-prow/clonerefs from v20220110-28076d3f8c to v20220112-0a53e24183 in /prow/images/clonerefs"

prow/jobs/test-infra/testgrid-automation.yaml, templates/data/testgrid-automation-data.yaml
- make the job optional until upstream issues are resolved
- #4733
=> Make testgrid job optional

development/tools/cmd/vmscollector/README.md
- Change regexp from include to exclude
- Tool now cleans up much more VMs than just the `kyma-integration` ones
#4718
=> VMcollector: update documentation

prow/jobs/test-infra/testgrid-automation.yaml, templates/data/testgrid-automation-data.yaml
=> Make testgrid job mandatory

prow/config.yaml, prow/plugins.yaml, templates/templates/prow-config.yaml
This PR will enable approve plugin configuration in this repo.
/hold
=> Add `approve` related plugin configuration for kyma-project/test-infra repo

prow/jobs/kyma/skr-kyma-to-kyma2-upgrade-aws.yaml, templates/data/skr-kyma-to-kyma2-upgrade-aws-data.yaml
=> Bump Kyma version to 2.0.3 in upgrade tests

development/tools/jobs/kyma/kyma_integration_test.go, prow/cluster/components/monitoring/dashboards/Makefile, prow/cluster/components/monitoring/dashboards/serverless/serverless-controller-dashboard.json, prow/cluster/components/monitoring/grafana_deployment.yaml, prow/jobs/kyma/kyma-integration.yaml, prow/scripts/cluster-integration/kyma-serverless-metrics-nightly.sh, prow/scripts/cluster-integration/serverless-integration-k3s.sh, prow/scripts/cluster-integration/serverless-metrics-collector.yaml, prow/scripts/lib/serverless-shared-k3s.sh, templates/data/kyma-integration-data.yaml, test-inventory-integration.md, vpath/pjtester.yaml
- Add serverless metrics job
https://github.com/kyma-project/kyma/issues/12849
=> Add serverless metrics job

prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
=> Fix nightly cluster

prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
=> Update kyma nightly to use local sources

prow/jobs/test-infra/prow-plugins.yaml, templates/data/prow-plugins-data.yaml
- Fixing wrong path of docker image for prow plugin
=> Fix test untrusted path

prow/images/whitesource-scanner/Dockerfile
=> Fix whitesource image

development/image-url-helper/excludes_promote.yaml, development/image-url-helper/pkg/promote/promote.go
- update custom `containerRegistryPath` fields
=> Fix promotion for custom container registry

prow/scripts/cluster-integration/kyma-integration-k3d-compass-components.yaml
- new component istio-resources
https://github.com/kyma-project/kyma/issues/13113, https://github.com/kyma-project/kyma/pull/13123
=> new component istio-resources

development/image-url-helper/README.md
- Add documentation for `image-url-helper` components subcommand
=> Add documentation for `image-url-helper` components subcommand

development/tools/jobs/cli/cli_integration_test.go, prow/jobs/cli/cli-integration.yaml, prow/jobs/incubator/compass/compass-development-artifacts.yaml, prow/jobs/incubator/compass/compass-gke-benchmark.yaml, prow/jobs/incubator/compass/compass-gke-integration.yaml, prow/jobs/incubator/compass/compass-integration-no-dump.yaml, prow/jobs/incubator/compass/compass-integration.yaml, prow/scripts/cluster-integration/kyma-integration-minikube.sh, prow/scripts/lib/kyma.sh, templates/data/cli-data.yaml, templates/data/compass-development-artifacts-data.yaml, templates/data/compass-gke-benchmark-data.yaml, templates/data/compass-gke-integration-data.yaml, templates/data/compass-integration-data.yaml, templates/data/compass-integration-no-dump.yaml
The `kyma test` subcommand should be removed in future. By this PR, all tests that depend on this subcommand to interact with Octopus tests should use the latest Kyma 1.x CLI release. Also the `pre-cli-integration-kyma-1` should run only on changes to release-1.x branches in the cli repository.
- Use Kyma 1.x CLI for `kyma test` usage
- Run pre-cli-integration-kyma-1 only on changes to release-kyma-1.x branches
=> Use Kyma 1.x CLI for Octopus tests

development/tools/jobs/kyma/kyma_integration_test.go, prow/jobs/kyma/kyma-integration.yaml, templates/data/kyma-integration-data.yaml
=> Fix cleaner regex

OWNERS_ALIASES
- remove @adamwalach from OWNERS file
=> Update owners_aliases file

prow/jobs/kyma/kyma-integration.yaml, templates/data/kyma-integration-data.yaml
=> Disable testgrid for some jobs

development/tools/jobs/control-plane/control_plane_reconciler_integration_test.go, prow/jobs/control-plane/control-plane-reconciler-integration.yaml, templates/data/control-plane-integration-data.yaml
- it's failing
https://github.com/kyma-project/control-plane/issues/1296
=> Make the `pre-main-control-plane-reconciler-e2e` pipeline optional

development/tools/jobs/control-plane/control_plane_reconciler_integration_test.go, prow/jobs/control-plane/control-plane-reconciler-integration.yaml, templates/data/control-plane-integration-data.yaml
- Revert: https://github.com/kyma-project/test-infra/pull/4809
https://github.com/kyma-project/control-plane/issues/1296
=> Revert: Make the `pre-main-control-plane-reconciler-e2e` pipeline optional

prow/jobs/incubator/reconciler/reconciler.yaml, prow/scripts/cluster-integration/reconciler-component-integration.sh, prow/scripts/cluster-integration/reconciler-component-provision-gardener.sh, prow/scripts/provision-vm-and-start-reconciler-component-integration-k3d.sh, templates/data/incubator-buildpack-data.yaml, vpath/pjtester.yaml
=> Test pipeline for ORY on prod profile

prow/scripts/cluster-integration/kyma-aks-long-lasting.sh, prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
- bump Kyma version in long-lasting scripts to `1.24.9`
=> Bump long-lasting Kyma 1.24 version to 1.24.9

prow/plugins.yaml
=> Remove test-untested-external-plugin from plugins.yaml

prow/jobs/kyma/releases/kyma-release-124.yaml
=> Fix Kyma CLI usage for 1.24 releases

prow/cluster/components/monitoring/grafana_deployment.yaml
=> Bump Grafana to 7.5.13

prow/scripts/cluster-integration/kyma-integration-minikube.sh
- use CLI 1.24.8 which have `kyma test` command
=> Use proper CLI version for Kyma 1.24

prow/jobs/governance.yaml, templates/data/governance-data.yaml
- make kyma-governance job optional
#4848
=> make governance job optional

prow/images/whitesource-scanner/Dockerfile, prow/images/whitesource-scanner/README.md
=> Bump image of wss-agent

prow/jobs/governance.yaml, templates/data/governance-data.yaml
This reverts commit 7117724a1aec1b76f48c5b72b0a02822b0ad8745.
- revert making the job optional in favor of more granular approach (https://github.com/kyma-project/kyma/pull/13233)
=> Revert "make governance job optional (#4847)"

development/image-syncer/external-images.yaml
- Update jaeger operator image to latest to fix security issues
=> Update jaeger image to latest 1.30.0

prow/jobs/third-party-images/third-party-images.yaml, templates/data/third-party-images-data.yaml
- Add job for building `busola-e2e-cleaner` image (https://github.com/kyma-project/third-party-images/pull/177)
=> Add busola-e2e-cleaner

prow/config.yaml, templates/templates/prow-config.yaml, vpath/pjtester.yaml
https://github.com/kyma-project/cli/pull/1171
=> Use unstable=true instead of stable=false

prow/scripts/cluster-integration/helpers/reconciler.sh, vpath/pjtester.yaml
=> add pjtester

prow/scripts/cluster-integration/kyma-upgrade-gardener-kyma2-to-main.sh
Fixing this error https://storage.googleapis.com/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-to-main/1488875059215863808/build-log.txt
- ...
- ...
- ...
=> fixing pipeline error

prow/scripts/cluster-integration/helpers/reconciler.sh, vpath/pjtester.yaml
=> print out mothership reconciler image

development/tools/cmd/rendertemplates/main.go
- make `rendertemplates` work with datafiles in subdirectories
fixes #4819
=> make rendertemplates work with recursive data files

prow/scripts/cluster-integration/kyma-integration-gardener.sh, vpath/pjtester.yaml
- remove unnecessary argument added in https://github.com/kyma-project/test-infra/pull/4868
- fixes #4878
=> Fix Gardener integration jobs

prow/scripts/cluster-integration/reconciler-integration-k3d.sh, vpath/pjtester.yaml
=> Provision Postgres for test pipeline

prow/scripts/cluster-integration/helpers/start-wssagent.sh
- fix one sed replacement
/assign
/kind bug
=> Fix whitesource Go mod scan

prow/scripts/lib/kyma.sh, vpath/pjtester.yaml
- Don't block scripts with `set -u` set
=> Fix Kyma cli install function

prow/cluster/resources/external-secrets/external_secrets_trusted.yaml, prow/cluster/resources/external-secrets/external_secrets_workloads.yaml
- change `serverless-git-auth` external secret name
#4650
=> Update external secrets names

development/image-syncer/external-images.yaml
- update alpine image to latest version 3.15.0
- ...
- ...
=> update to alpine 3.15.0

prow/jobs/incubator/reconciler/reconciler.yaml, prow/scripts/cluster-integration/reconciler-component-integration.sh, templates/data/incubator-buildpack-data.yaml, vpath/pjtester.yaml
=> Introduce integration tests for Istio component on main Kyma

prow/jobs/incubator/reconciler/reconciler.yaml, templates/data/incubator-buildpack-data.yaml
=> Add reconciler dockerfile validation job

prow/scripts/cluster-integration/kyma-aks-long-lasting.sh, prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
- Bump Kyma to 1.24.10 on long-lasting clusters
=> Bump Kyma to 1.24.10 on long-lasting clusters

prow/jobs/incubator/reconciler/reconciler.yaml, prow/scripts/cluster-integration/reconciler-component-integration.sh, prow/scripts/provision-vm-and-start-reconciler-component-integration-k3d.sh, templates/data/incubator-buildpack-data.yaml, vpath/pjtester.yaml
=> Add Istio integration pipelines on latest Kyma

prow/jobs/kyma/kyma-integration.yaml, templates/data/kyma-integration-data.yaml
- ...
- ...
- ...
https://github.com/kyma-project/kyma/issues/13304
=> use k8s 1.22 for the preview job

prow/jobs/incubator/reconciler/reconciler.yaml, templates/data/incubator-buildpack-data.yaml
- Pre and Post image build job for mock reconciler branch
- ...
- ...
=> pre and post jobs for image build mock reconciler

prow/jobs/incubator/reconciler/reconciler.yaml, templates/data/incubator-buildpack-data.yaml
=> Fix run_if_changed for Istio pipelines

prow/config.yaml, templates/templates/prow-config.yaml
- protect `load-test-mock` branch
=> Protect reconciler branch

prow/jobs/incubator/reconciler/reconciler.yaml, templates/data/incubator-buildpack-data.yaml
=> Adjust run_if_changed for Istio pipelines

prow/jobs/incubator/reconciler/reconciler.yaml, templates/data/incubator-buildpack-data.yaml
=> Move dockerfile matching out of first group

prow/scripts/cluster-integration/kyma-gke-upgrade.sh, prow/scripts/cluster-integration/kyma-upgrade-gardener-azure.sh, prow/scripts/cluster-integration/kyma-upgrade-gardener.sh, prow/scripts/lib/kyma.sh
- backport function that correctly selects the latest Kyma 1.24 release
#4996
=> Backport kyma::get_last_release_version to release-1.24

prow/scripts/cluster-integration/kyma-aks-long-lasting.sh, prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
=> Bump long lasting Kyma version in release-1.24

prow/scripts/cluster-integration/reconciler-e2e-gardener.sh
Reconciler pipeline does not fail as it should, it does not finish reconcilation but does not propagate an error.
- change approach how to watch finished reconcilation
https://github.com/kyma-incubator/reconciler/issues/834
=> Fix unexpected reconcilation timeout

development/tools/jobs/control-plane/control_plane_reconciler_integration_test.go, prow/jobs/control-plane/control-plane-reconciler-integration.yaml, prow/scripts/cluster-integration/reconciler-e2e-gardener.sh, templates/data/control-plane-integration-data.yaml, vpath/pjtester.yaml
- Added `pre-main-control-plane-reconciler-e2e-latest-release`.
- Made `pre-main-control-plane-reconciler-e2e` job as `optional: false`.
- [Test job run](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/1355/mfaizanse_test_of_prowjob_pre-main-control-plane-reconciler-e2e/1494592278365212672)
- https://github.com/kyma-incubator/reconciler/issues/803
=> Added pre-submit job for reconciler e2e on kyma latest-release in control-plane PRs

development/image-syncer/external-images.yaml, prow/scripts/cluster-integration/kyma-integration-k3d.sh, vpath/pjtester.yaml
- Remove helm installation of mockserver, this is done in the test itself now
- Add mockserver image to internal registry
* https://github.com/kyma-project/kyma/issues/13305
=> Telemetry operator tests - Remove mockserver provisioning

development/image-syncer/external-images.yaml
=> add golang 1.17.7

prow/jobs/incubator/reconciler/reconciler.yaml, prow/scripts/cluster-integration/reconciler-component-provision-gardener.sh, prow/scripts/provision-vm-and-start-reconciler-component-integration-k3d.sh, templates/data/incubator-buildpack-data.yaml, vpath/pjtester.yaml
=> Determine latest 2.x version of Kyma in reconciler component pipelines

prow/jobs/scans/whitesource-periodics.yaml, templates/data/whitesource-periodics-data.yaml
=> Remove `octopus-whitesource-scan` job

prow/jobs/scans/whitesource-periodics.yaml, templates/data/whitesource-periodics-data.yaml
/cc @aberezovski 
/cc @Sawthis
=> Switch whitesource kyma-mod and cli jobs to release-2.0

prow/jobs/incubator/reconciler/reconciler.yaml, prow/scripts/cluster-integration/reconciler-component-integration.sh, templates/data/incubator-buildpack-data.yaml, vpath/pjtester.yaml
- Check if the mothership binary was built.
- Make component pipelines mandatory in the reconciler.
#5012
=> Fix reconciler components pipeline

prow/scripts/cluster-integration/serverless-integration-k3s.sh
- fix kyma deploy arguments due to failing pipelines [here](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/13348/pre-main-serverless-integration-k3s/1498939816312573952)
- https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/13348/pre-main-serverless-integration-k3s/1498939816312573952
=> Fix the `serverless-integration-k3s` test

prow/scripts/cluster-integration/helpers/start-wssagent.sh, vpath/pjtester.yaml
- don't scan subprojects in `docs` directory
=> Fix whitesource regex

prow/jobs/test-infra/buildpack.yaml, templates/data/buildpack-data.yaml
Removing clonerefs prowjobs. We doesn't use custom clonerefs image anymore. Moreover upstream image recently changed and doesn't use clonerefs shell script.
=> Remove clonerefs prowjobs

development/tools/jobs/kyma/kyma_gardener_cleanup_test.go, prow/jobs/kyma/kyma-gardener-cleanup.yaml, templates/data/kyma-gardener-cleanup-data.yaml
=> exclude rec-main job

prow/scripts/cluster-integration/kyma-upgrade-gardener-kyma2-to-main.sh, prow/scripts/cluster-integration/kyma-upgrade-k3d-kyma2-to-main.sh
- Adapt renamed migration script reference
* https://github.com/kyma-project/kyma/pull/13557
=> Renamed migration script

prow/jobs/test-infra/branchprotector.yaml, prow/jobs/test-infra/prow-periodics.yaml, prow/jobs/test-infra/validation.yaml, prow/staging/jobs/test-infra-jobs.yaml, templates/data/prow-periodics-data.yaml, templates/data/validation-data.yaml
Prow recentry moved to `ko`. That means entrypoints have changed.
=> Fix entrypoints for Prow images

prow/scripts/cluster-integration/reconciler-component-integration.sh, prow/scripts/cluster-integration/reconciler-component-provision-gardener.sh, prow/scripts/provision-vm-and-start-reconciler-component-integration-k3d.sh, vpath/pjtester.yaml
=> Fix Istioctl version in the pipelines

prow/config.yaml, prow/jobs/incubator/reconciler/reconciler.yaml, prow/scripts/reconciler-publish-pr-cli.sh, templates/data/incubator-buildpack-data.yaml, templates/templates/prow-config.yaml, vpath/pjtester.yaml
- Pre-main job to build a kyma-cli based on cli:main and reconciler:PR
- [Test run](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-incubator_reconciler/899/mfaizanse_test_of_prowjob_pre-main-reconciler-publish-pr-cli/1501851604922404864)
- https://github.com/kyma-incubator/reconciler/issues/802
=> Pre-main job to build a kyma-cli based on cli:main and reconciler:PR

prow/scripts/cluster-integration/reconciler-integration-k3d.sh
=> Replace log withe echo in VM script

prow/jobs/incubator/reconciler/reconciler.yaml, templates/data/incubator-buildpack-data.yaml
- Monitoring tests are skipped if KYMA_MAJOR_UPGRADE is true
- Since we don't want to support testing on Kyma 1 anymore, we decide to skip the tests in major upgrade scenarios
=> Skip monitoring tests in reconciler major upgrade pipeline

development/custom-image/install-deps-debian.sh
This didn't let the custom image to build.
=> Add missing / in postgresql installation

development/custom-image/install-deps-debian.sh
=> Fix installation logic for postgresql and migrate

prow/jobs/incubator/reconciler/reconciler.yaml, prow/scripts/cluster-integration/reconciler-integration-with-cli-k3d.sh, prow/scripts/provision-vm-and-test-reconciler-with-cli-k3d.sh, templates/data/incubator-buildpack-data.yaml, vpath/pjtester.yaml
- Added `pre-main-reconciler-cli-integration-kyma-latest-k3d` job. ([Test run](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-incubator_reconciler/899/mfaizanse_test_of_prowjob_pre-main-reconciler-cli-integration-k/1501902051863433216))
- Added `pre-main-reconciler-cli-integration-kyma-main-k3d` job. ([Test run](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-incubator_reconciler/899/mfaizanse_test_of_prowjob_pre-main-reconciler-cli-integration-k/1501906146347192320))
- https://github.com/kyma-incubator/reconciler/issues/807
=> Pre-main jobs for reconciler PR with cli:main

prow/jobs/scans/protecode-guard.yaml, templates/data/protecode-guard-data.yaml
- make Protecode jobs optional until they are fixed
=> Make protecode jobs optional

development/image-syncer/external-images.yaml
- Add natsio/nats-server-config-reloader:0.6.3 image
- 0.6.3 is the last published version, see [docker hub](https://hub.docker.com/r/natsio/nats-server-config-reloader/tags)
- The image is required for https://github.com/kyma-project/kyma/issues/13321
https://github.com/kyma-project/kyma/issues/13321
=> Sync natsio/nats-server-config-reloader:0.6.3 image to Kyma registry

development/image-syncer/external-images.yaml
See release notes here: https://github.com/nats-io/nats-server/releases
Sync nats:2.7.4-alpine image to external registry.
See release notes here: https://github.com/nats-io/nats-server/releases
=> Sync nats:2.7.4-alpine image

prow/jobs/scans/protecode-guard.yaml, templates/data/protecode-guard-data.yaml
- Make protecode jobs required after they are fixed
/hold
=> Make protecode jobs required

prow/jobs/busola/integration-k3s-test.yaml, prow/scripts/cluster-integration/busola-integration-test-k3s.sh, prow/scripts/provision-vm-and-start-busola-k3s.sh, templates/data/busola-integration-test-k3s-cluster-data.yaml, templates/data/busola-integration-test-k3s-namespace-data.yaml, vpath/pjtester.yaml
- ...
- ...
- ...
Resolves https://github.com/kyma-project/busola/issues/912 (part 2)
=> Parallelise busola tests

development/image-syncer/external-images.yaml
- Add golang 1.17.8-alpine3.15 image.
=> Add golang 1.17.8-alpine3.15 image

prow/jobs/incubator/reconciler/reconciler.yaml, prow/scripts/cluster-integration/reconciler-integration-with-cli-upgrade-k3d.sh, prow/scripts/lib/kyma.sh, prow/scripts/lib/utils.sh, prow/scripts/provision-vm-and-test-reconciler-with-cli-k3d.sh, templates/data/incubator-buildpack-data.yaml, vpath/pjtester.yaml
- added `pre-main-reconciler-cli-kyma-prev-to-last-release-upgrade-k3d` ([Test run](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-incubator_reconciler/899/mfaizanse_test_of_prowjob_pre-main-reconciler-cli-kyma-prev-to-/1504435990729592832))
- https://github.com/kyma-incubator/reconciler/issues/807
=> Pre-main upgrade job for reconciler PR with cli:main

prow/scripts/cluster-integration/kyma-gke-release-candidate.sh, prow/scripts/cluster-integration/reconciler-upgrade-kyma2-latest-to-main-gardener.sh, prow/scripts/lib/gardener/aws.sh, prow/scripts/lib/gardener/azure.sh, prow/scripts/lib/gardener/gcp.sh, vpath/pjtester.yaml
- on latest main we have upgraded  prometheus stack and thus we had to implement a migration script to get rid of old unused resources. Execute this script after upgrade is performed.
=> Execute migration script on upgrade

prow/scripts/cluster-integration/reconciler-integration-with-cli-k3d.sh, vpath/pjtester.yaml
- Improved reconciler with cli jobs to reuse helper functions
- `pre-main-reconciler-cli-integration-kyma-latest-k3d` ([Test run](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-incubator_reconciler/899/mfaizanse_test_of_prowjob_pre-main-reconciler-cli-integration-k/1504794805949960192))
- `pre-main-reconciler-cli-integration-kyma-main-k3d` ([Test run](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-incubator_reconciler/950/mfaizanse_test_of_prowjob_pre-main-reconciler-cli-integration-k/1504822172386856960))
- https://github.com/kyma-incubator/reconciler/issues/807
=> Improved reconciler with cli jobs to reuse helper functions

prow/scripts/cluster-integration/helpers/reconciler.sh, prow/scripts/cluster-integration/reconciler-e2e-nightly-gardener.sh
- Remove `reconcile_kyma` function, and use already tested functiosn to stay consistent with other pipelines
- ...
- ...
=> Use different  funcs to stay consistent in Reconciler pipelines
