kyma-project/test-infra

- prow/images/kyma-integration/Dockerfile
- Bump Azure cli to `2.34.1`
- closes #4345
> Bump Azure cli version

- OWNERS_ALIASES
- Add `ammarlakis` to tooling approvers
> Add ammarlakis to tooling approvers

- prow/jobs/kyma/kyma-integration-gardener.yaml
- prow/scripts/cluster-integration/helpers/eventing.sh
- prow/scripts/cluster-integration/kyma-integration-skr-eventing.sh
- templates/data/kyma-integration-gardener-data.yaml
This PR makes the pre-main-skr-eventing pipeline green again. [Here](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/13574/vladislavpaskar_test_of_prowjob_pre-main-kyma-skr-eventing/1506237539831255040) is the green result.
- add the test suffix env variable for fi tests runs on skr
- refactor the pre-skr-eventing-job (add keb/kcp credentials remove unneeded env variables)
https://github.com/kyma-project/kyma/issues/12846
> Refactor skr eventing job

- prow/scripts/cluster-integration/kyma-integration-gardener-eventing.sh
- prow/scripts/cluster-integration/kyma-integration-gardener.sh
- Don't use `VERSION` directly in Gardener script
- replace code with existing utils function
- #4967
/cc @Ressetkk
> Use util function in Gardener scripts

- prow/jobs/kyma/skr-kyma-to-kyma2-upgrade-aws.yaml
- templates/data/skr-kyma-to-kyma2-upgrade-aws-data.yaml
- Removed hardcoded Kyma2 version, since it will already be fetched automatically in job: https://github.com/kyma-project/test-infra/blob/main/prow/scripts/cluster-integration/kyma-upgrade-skr-aws-kyma-to-kyma2.sh#L37
- ...
- ...
> Remove hardcoded Kyma Version

- prow/jobs/cli/cli-compatibility.yaml
- prow/scripts/compatibility-cli.sh
- templates/data/cli-data.yaml
- vpath/pjtester.yaml
- The [kyma-cli-compatibility-1](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-cli-compatibility-1) job is constantly failing because of a missing env setting. This PR is adding the env variable
- Also, this PR fixes the compatibility script to work with 2 latest Kyma versions (not used at the moment)
> Fix kyma cli compatibility 1

- prow/scripts/cluster-integration/helpers/reconciler.sh
We need to differente between different Kyma version: main, 2.0.x, and 2.1.x
Uses different template for each version.
Needs to be merged after: https://github.com/kyma-project/control-plane/pull/1495
> Use correct request reconcile script

- prow/jobs/scans/whitesource-periodics.yaml
- templates/data/whitesource-periodics-data.yaml
- add the `subprojects: "true"` to the jobConfig
> Split hydroform scans into a few subprojects

- prow/scripts/cluster-integration/reconciler-component-integration.sh
> Remove workaround with istio component name in the pipeline

- prow/scripts/cluster-integration/reconciler-component-integration.sh
- prow/scripts/cluster-integration/reconciler-component-provision-gardener.sh
- prow/scripts/provision-vm-and-start-reconciler-component-integration-k3d.sh
- vpath/pjtester.yaml
- Initial removal of conditionals checking istioctl version.
Next step will be: https://github.com/kyma-project/test-infra/issues/5076
> Set the istioctl version in the pipelines

- prow/scripts/cluster-integration/helpers/reconciler.sh
> Exchange example domain with real domain on Kyma 2.1.x

- prow/config.yaml
- prow/plugins.yaml
- templates/templates/prow-config.yaml
First let's enable smaller repos then I'll update Kyma on Friday.
> Enable approve for kyma-project/third-party-images and kyma-project/cli

- prow/jobs/scans/whitesource-periodics.yaml
- prow/scripts/cluster-integration/helpers/start-wssagent.sh
- templates/data/whitesource-periodics-data.yaml
- templates/templates/whitesource-periodics.tmpl
- vpath/pjtester.yaml
- add option to manually exclude folders from scanning
- exclude hydroform examples
> Whitesource: add manual excludes

- prow/scripts/cluster-integration/kyma-integration-k3d-telemetry-components.yaml
- prow/scripts/cluster-integration/kyma-integration-k3d.sh
- prow/scripts/provision-vm-and-start-kyma-k3d.sh
- Install telemetry chart using `kyma deploy`
- Set enable telemetry integration in logging chart
See also https://github.com/kyma-project/kyma/issues/12029
> Enable telemetry integration for logging chart

- prow/scripts/reconciler-publish-unstable-cli.sh
- Fix for the unstable CLI pipeline
> Fix the go get command to bump the reconciler

- prow/config.yaml
- templates/templates/prow-config.yaml
The repos got archived
- ...
- ...
- ...
> remove terraform-provider-kind and terraform-modules

- development/image-syncer/external-images.yaml
> Upgrade alpine image tag to version `1.15.3`

- templates/data/generic_component_data.yaml
- remove unused component jobs used before Kyma 1.20
> Remove unused component jobs

- docs/prow/prow-installation-on-forks.md
Since we changed the way how to [set up a new repository in Kyma](https://kyma-project.io/community/guidelines/repository-guidelines/01-new-repository-settings), some links and sections became outdated. This PR only fixes the broken link, but the whole document needs a further update, especially since [Kubernetes also changed the way of configuring Prow](https://github.com/kubernetes/test-infra/blob/master/prow/getting_started_deploy.md#create-the-github-secrets) and the whole section about the webhook configuration is also outdated. The follow-up will be monitored in [this](https://github.com/kyma-project/test-infra/issues/5215) issue.
- Remove the broken link …
> Remove the broken link

- development/image-syncer/external-images.yaml
- Changed image tag for NATS image in image-syncer
> Changed image tag for NATS image in image-syncer

- development/kyma-slack-connector/slackConnectorChart/values/oomevent.found/prod-values.yaml
- development/kyma-slack-connector/slackConnectorChart/values/prowjob.failed/prod-values.yaml
> Use correct keys for production Slack-connector helm chart

- prow/jobs/kyma/releases/kyma-release-22.yaml
- prow/scripts/cluster-integration/kyma-gke-release-candidate.sh
- templates/data/kyma-release-data.yaml
- send pubsub messages from RC creation script
- https://github.com/kyma-project/test-infra/issues/4906
> Use pubsub with rc clusters

- prow/jobs/kyma/releases/kyma-release-21.yaml
- prow/scripts/cluster-integration/kyma-gke-release-candidate.sh
- templates/data/kyma-release-data.yaml
- send pubsub messages from RC creation script
- closes https://github.com/kyma-project/test-infra/issues/4906
> Use pubsub with rc clusters on release-2.1

- prow/jobs/kyma/releases/kyma-release-22.yaml
- prow/scripts/cluster-integration/kyma-gke-release-candidate.sh
- templates/data/kyma-release-data.yaml
- set proper project for pubsub
- #4906 
/cc @Ressetkk
> Use proper project for pubsub publish

- development/image-syncer/external-images.yaml
- Bumped NATS prometheus exporter image on image-syncer
> Bumped NATS prometheus exporter image on image-syncer

- prow/scripts/cluster-integration/helpers/reconciler.sh
- vpath/pjtester.yaml
- apply a trap to clean damaged cluster and retry with new cluster name in case provisioning of gardener shoot fails
https://github.com/kyma-project/test-infra/issues/5229
> Retry gardener shoot provisioning for reconciler

- prow/images/buildpack-golang/Makefile
- prow/images/kyma-integration/Dockerfile
- prow/images/test-untrusted-plugin/Dockerfile
- prow/images/whitesource-scanner/Dockerfile
- prow/scripts/cluster-integration/reconciler-component-integration.sh
- Leftovers from upgrade from 1.17.8 to 1.18 version
> Go Upgrade Leftovers

- prow/jobs/incubator/reconciler/reconciler.yaml
- prow/scripts/cluster-integration/helpers/integration-tests.sh
- prow/scripts/cluster-integration/reconciler-component-integration.sh
- prow/scripts/cluster-integration/reconciler-component-provision-gardener.sh
- prow/scripts/provision-vm-and-start-reconciler-component-integration-k3d.sh
- templates/data/incubator-buildpack-data.yaml
- vpath/pjtester.yaml
- https://github.com/kyma-project/test-infra/issues/5076
> Fetch Istio version from Helm Chart

- development/image-syncer/external-images.yaml
- Bumped NATS prometheus exporter image to 0.9.2 on image-syncer
> Bumped NATS prometheus exporter image to 0.9.2 on image-syncer

- development/tools/cmd/rendertemplates/main.go
- development/tools/pkg/rendertemplates/rendertemplates.go
- Add flag to enable appending slices.
- Add support for appending slices to merging methods.
> Rendertemplate can append slices instead overwrite.

- .github/stale.yml
Since comments need to be in new line for them to work.
> Edit stalebot configuration to allow comments with multiple lines

- prow/labels.yaml
- fixes failing `ci-prow-label-sync` job
> Fix labels

- development/kyma-pubsub-connector/pubsubConnectorChart/global-prod-values.yaml
- development/kyma-slack-connector/slackConnectorChart/values/pullrequest.automerged/prod-values.yaml
- Update pubsub connector image tag
- pullrequest-merged.v1 get code from main branch
Parent: #4786
> Update slack and pubsub connectors values

- development/kyma-slack-connector/slackConnectorChart/global-prod-values.yaml
- development/kyma-slack-connector/slackConnectorChart/global-stage-values.yaml
- development/kyma-slack-connector/slackConnectorChart/values/issuesevent.labeled/stage-values.yaml
- development/kyma-slack-connector/slackConnectorChart/values/oomevent.found/stage-values.yaml
- development/kyma-slack-connector/slackConnectorChart/values/prowjob.failed/stage-values.yaml
- development/kyma-slack-connector/slackConnectorChart/values/pullrequest.automerged/stage-values.yaml
- development/kyma-slack-connector/slackConnectorChart/values/releasecluster.created/stage-values.yaml
- Move serverless functions into separate repo (https://github.com/kyma-test-infra-dev/tooling-serverless-functions)
- adjust values
#5283
/assign
> Move serverless functions into separate repo

- development/tools/jobs/cli/cli_integration_test.go
- prow/jobs/cli/cli-integration.yaml
- templates/data/cli-data.yaml
- ...
- ...
- ...
https://github.com/kyma-project/cli/issues/1247
> Remove deprecated Kyma 1 CLI job

- prow/jobs/kyma/kyma-integration.yaml
- templates/data/kyma-integration-data.yaml
- Temporarily make app-connectivity compass job optional until fast-integration tests are fixed
- https://github.com/kyma-project/kyma/issues/13415
> Temporarily make app-connectivity compass job optional

- development/external-plugins/needs-tws/plugin.go
- ignore letter case for review author, since we compare against lowercase list
- #5037
> Make need-tws plugin case insensitive

- development/image-syncer/external-images.yaml
> Bump alpine to 3.15.4

- development/tools/jobs/testinfra/branchprotector_test.go
- prow/config.yaml
- prow/plugins.yaml
- templates/templates/prow-config.yaml
Removed settings for prow approval flow in kyma repository.
See: #5319
> Revert prow approval flow in cli

- prow/scripts/cluster-integration/kyma-upgrade-gardener-kyma2-minor-versions.sh
- prow/scripts/lib/kyma.sh
- vpath/pjtester.yaml
- Fix unsupported arithmetic operation
- Include log for version overview
> fix: kyma2 gardener minor versions upgrade

- prow/images/bootstrap/Dockerfile
- prow/images/kyma-integration/Dockerfile
- Bump Docker to 20.10.14
- Required for https://github.com/kyma-project/test-infra/pull/5313
> Bump Docker version

- prow/scripts/cluster-integration/kyma-integration-gardener-eventing-upgrade.sh
- prow/scripts/cluster-integration/kyma-integration-gardener-eventing.sh
- prow/scripts/cluster-integration/kyma-integration-gardener.sh
- prow/scripts/cluster-integration/kyma-upgrade-gardener-kyma2-minor-versions.sh
- prow/scripts/cluster-integration/kyma-upgrade-gardener-kyma2-to-main.sh
- prow/scripts/cluster-integration/reconciler-component-provision-gardener.sh
- prow/scripts/cluster-integration/reconciler-e2e-gardener.sh
- prow/scripts/cluster-integration/reconciler-periodic-main-kyma-incubator-reconciler-kyma1-kyma2-upgrade.sh
- Add `CLEANUP_CLUSTER` variables in Gardener scripts
- 
/retest
/assign
> Cleanup Gardener clusters

- CODEOWNERS
Compass repositories' config CODEOWNERS update.
- Remove users who are no longer in the team
- Add new team members
- Update ORD Service code owners
> Update Compass CODEOWNERS

- prow/jobs/incubator/reconciler/reconciler.yaml
- templates/data/incubator-buildpack-data.yaml
Fix of post-main-istio-reconciler-integration flaky job
- Added lost reference to kyma repo
> Fix post-main-istio-reconciler-integration job

- prow/images/kyma-integration/Dockerfile
Upgrade kcp-cli version to master-1208b417 for integration tests
> upgrade kcp-cli version to master-1208b417 

- development/tools/jobs/kyma/kyma_integration_test.go
- prow/jobs/kyma/kyma-integration.yaml
- templates/data/kyma-integration-data.yaml
- Adjust cleaners exclude list after Kyma version bump
> Adjust cleaners exclude list

- prow/scripts/provision-vm-and-start-serverless-k3s.sh
> Fix serverless job

- prow/jobs/control-plane/control-plane-reconciler-integration.yaml
- templates/data/control-plane-integration-data.yaml
> make pre-main-control-plane-reconciler-e2e-latest-release optional

- prow/jobs/kyma/skr-aws-upgrade-integration-dev.yaml
- templates/data/skr-aws-upgrade-integration-dev-data.yaml
Change kyma input version to 2.1.3
> Change kyma input version to 2.1.3

- prow/cluster/resources/external-secrets/external_secrets_workloads.yaml
- Add btp-admin-credentials secret, it will be used in #5383
> Add btp-admin-credentials secret

- prow/config.yaml
- prow/jobs/kyma/skr-svcat-migration.yaml
- templates/data/skr-svcat-migration-data.yaml
- templates/templates/prow-config.yaml
BTP_SM_ADMIN_CREDS env to reuse SM instance in skr test
> BTP_SM_ADMIN_CREDS env to reuse SM instance in skr test

- prow/scripts/cluster-integration/helpers/reconciler.sh
- prow/scripts/lib/log.sh
- vpath/pjtester.yaml
> fix kyma version condition

- development/kyma-slack-connector/slackConnectorChart/templates/function.yaml
> Fix case in cr

- development/image-syncer/external-images.yaml
- Update prometheus-nats-exporter image to v0.9.3
> Update nats-exporter image

- prow/scripts/cluster-integration/busola-integration-test-k3s.sh
- vpath/pjtester.yaml
> Fix busola k3s

- prow/scripts/cluster-integration/busola-integration-test-k3s.sh
- prow/scripts/cluster-integration/helpers/reconciler.sh
- prow/scripts/cluster-integration/reconciler-e2e-nightly-gardener.sh
- prow/scripts/cluster-integration/reconciler-gardener-long-lasting.sh
- prow/scripts/cluster-integration/reconciler-integration-k3d.sh
- prow/scripts/cluster-integration/serverless-integration-k3s.sh
- prow/scripts/generate-component-descriptors.sh
- prow/scripts/github-stats.sh
- prow/scripts/install-prow.sh
- prow/scripts/kyma-testing.sh
- prow/scripts/lib/azure.sh
- prow/scripts/lib/docker.sh
- prow/scripts/lib/gcp.sh
- prow/scripts/lib/github.sh
- prow/scripts/lib/junit.sh
- prow/scripts/lib/kyma.sh
- prow/scripts/lib/log.sh
- prow/scripts/lib/utils.sh
- prow/scripts/provision-vm-and-test-reconciler-with-cli-k3d.sh
- prow/scripts/provision-vm-cli.sh
- prow/scripts/provision-vm-compass.sh
- prow/scripts/provision-vm-control-plane.sh
- prow/scripts/publish-buildpack.sh
- prow/scripts/reconciler-publish-pr-cli.sh
- prow/scripts/reconciler-publish-unstable-cli.sh
- prow/scripts/validate-config.sh
- prow/scripts/validate-scripts.sh
- prow/scripts/vpathguard.sh
This reverts commit bead4e31
- Revert due to scripts are not copying into the vm. 
**Introduced**
https://github.com/kyma-project/test-infra/pull/5374
> Revert "CI/CD 1005 add traceability to prow (#5374)"

- prow/plugins.yaml
Removing plugins which actions will be not needed or possible after restoring write access to repository.
#5312
> Remove unused plugins

- prow/jobs/incubator/compass/compass-integration-no-dump.yaml
- prow/jobs/incubator/compass/compass-integration.yaml
- templates/data/compass-integration-data.yaml
- templates/data/compass-integration-no-dump.yaml
- Fix typo in CPU request limits in templates
> Fix typo in CPU request limits

- prow/jobs/scans/whitesource-periodics.yaml
- templates/data/whitesource-periodics-data.yaml
- vpath/pjtester.yaml
- Restore api-gateway Whitesource scan
> Restore api-gateway Whitesource scan

- prow/scripts/resources/reconciler/shoot-template.yaml
- Bump gardener cluster image version from 576.1.0 to 576.2.0
> Bump gardener cluster image version from 576.1.0 to 576.2.0

- development/custom-image/install-deps-debian.sh
Add golang installation to k3d vm for executing go tests
https://github.com/kyma-project/test-infra/issues/5411
> Add golang to k3d vm install

- development/custom-image/install-deps-debian.sh
Create a directory before extracting go
> Mkdir for go install

- prow/cluster/components/monitoring/dashboards/quality/quality.json
- Update quality dashboard to show count of jobs in job success rate table
> Update quality dashboard

- development/tools/cmd/rendertemplates/README.md
- templates/README.md
Example usage with all local files added as it's most common used case.
- Add link to Render Template documentation in templates documentation.
- Add all local files example usage.
> Linked templates documentation with Render Templates documentation.

- prow/jobs/kyma/skr-aws-upgrade-integration-dev.yaml
- templates/data/skr-aws-upgrade-integration-dev-data.yaml
- vpath/pjtester.yaml
Refactor `skr-aws-upgrade-integration-dev` test
- Add btp-operator
> Refactor skr-aws-upgrade-integration-dev test

- development/tools/jobs/kyma/kyma_gardener_integration_test.go
- prow/jobs/kyma/kyma-integration-gardener.yaml
- prow/scripts/lib/kyma.sh
- templates/data/kyma-integration-gardener-data.yaml
- vpath/pjtester.yaml
- reduce the execution frequency to 1/day
- increase the concurrency of workers to faster the execution
> Reduce execution frequency: kyma-upgrade-gardener-kyma2-minor-versions

- prow/scripts/provision-vm-compass.sh
- Add more CPU and RAM to integration tests image.
> More resources to tests

- prow/jobs/kyma/kyma-integration.yaml
- templates/data/kyma-integration-data.yaml
Make pipeline execute when changing component tests for Istio
> Add component test dir to istio pipeline

- prow/jobs/kyma/kyma-integration.yaml
- templates/data/kyma-integration-data.yaml
> Make Kyma istio-evaluation pipeline optional

- development/image-url-helper/README.md
- prow/jobs/kyma/kyma-validation.yaml
- templates/data/kyma-validation-data.yaml
- vpath/pjtester.yaml
- add job checking if all images defined in value.yaml files exists
- #5509
> Add missing image check job

- .github/ISSUE_TEMPLATE/github-config-change.md
- Add Github issue template that will allow us to track Github configuration changes.
- It is for the sake of security and transparency.
https://github.com/kyma-project/test-infra/issues/5493
> Track Github configuration changes

- prow/scripts/cluster-integration/compass-gke-benchmark.sh
- prow/scripts/lib/utils.sh
This PR install yq CLI in the compass benchmark script.
> Install yq in compass-benchmark script

- prow/scripts/cluster-integration/compass-gke-benchmark.sh
This PR fixes typo in compass-benchmark script
> Fix typo in compass-benchmark script

- prow/scripts/lib/utils.sh
This PR renames the unarchived yq executable after downloading it.
> Rename yq exec used in compass-benchmark script

- prow/scripts/cluster-integration/compass-gke-benchmark.sh
- prow/scripts/lib/utils.sh
This PR add utils function to install helm CLI and use it in compass-benchmark job.
> Install helm in compass-benchmark script

- prow/scripts/resources/reconciler/shoot-template.yaml
nightly-main-reconciler pipeline failed because of  Unsupported value: core.ShootMachineImage:
https://storage.googleapis.com/kyma-prow-logs/logs/nightly-main-reconciler/1537223483468025856/build-log.txt
> update ShootMachineImage to latest 576.9.0

- prow/jobs/kyma/kyma-integration-gardener.yaml
- templates/data/kyma-integration-gardener-data.yaml
- Made `pre-main-kyma-gardener-gcp-eventing-upgrade` test optional
> Make the eventing upgrade test optional

- prow/scripts/cluster-integration/helpers/reconciler.sh
The new values.yaml file in this PR:
https://github.com/kyma-project/control-plane/pull/1601/files#diff-8d2f6fc4296f16d99c177d56da19b07576a1489ae9bc1dc3981f9b805b39c1ed
> Change grep regex in order to adapt new values.yaml file

- development/tools/jobs/control-plane/control_plane_reconciler_integration_test.go
- development/tools/jobs/control-plane/control_plane_reconciler_upgrade_test.go
- prow/jobs/control-plane/control-plane-reconciler-integration.yaml
- prow/jobs/control-plane/control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener.yaml
- prow/scripts/cluster-integration/helpers/reconciler.sh
- prow/scripts/reconciler-image-autobump.sh
- prow/scripts/resources/control-plane-autobump-reconciler-config.yaml
- templates/data/control-plane-integration-data.yaml
- vpath/pjtester.yaml
To support new values file of reconciler image https://github.com/kyma-project/control-plane/pull/1809/files
> Change kcp value reference

- development/tools/jobs/control-plane/control_plane_reconciler_integration_test.go
- development/tools/jobs/control-plane/control_plane_reconciler_upgrade_test.go
- prow/jobs/control-plane/control-plane-reconciler-integration.yaml
- prow/jobs/control-plane/control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener.yaml
- prow/scripts/cluster-integration/helpers/reconciler.sh
- prow/scripts/reconciler-image-autobump.sh
- prow/scripts/resources/control-plane-autobump-reconciler-config.yaml
- templates/data/control-plane-integration-data.yaml
> revert back detect change from default values file

- prow/jobs/kyma/kyma-integration.yaml
- templates/data/kyma-integration-data.yaml
- Revert Temporarily make app-connectivity compass job optional
- #5304
- https://github.com/kyma-project/kyma/pull/14071
> Revert Temporarily make app-connectivity compass job optional (#5304)

- prow/config.yaml
- templates/templates/prow-config.yaml
- add new errors that should be highlighted
> Update log highlight regexes

- prow/config.yaml
- prow/scripts/cluster-integration/kyma-integration-k3d.sh
- prow/scripts/provision-vm-and-start-kyma-k3d.sh
- prow/staging/config.yaml
- templates/templates/prow-config.yaml
- vpath/pjtester.yaml
- https://github.com/kyma-project/kyma/issues/14578
> Generate Istio component tests report

- prow/jobs/incubator/reconciler/reconciler.yaml
- templates/data/incubator-buildpack-data.yaml
- it is no longer necessary to run those tests on all changes
> Change run_if_changed for Ory reconciler tests

- development/kyma-slack-connector/issueLabeledFunction/README.md
- Remove broken link
- Provide stylistic fixes
> Remove broken link

- prow/jobs/kyma/kyma-integration.yaml
- templates/data/kyma-integration-data.yaml
- test-inventory-integration.md
- Add [post-main-k3d-k8s-preview](https://status.build.kyma-project.io/?job=post-main-k3d-k8s-preview). The job should have been disabled, not removed.
https://github.com/kyma-project/test-infra/issues/5529
> add post-main-k3d-k8s-preview job

- docs/prow/prow-secrets-management.md
- add KMS key and service account key rotation documentation
> add secret rotation documentation

- prow/jobs/test-infra/pjtester.yaml
- templates/data/pjtester-data.yaml
Added prowjob to run pjtesterv2. Need this for tess.
> prowjob for tests of pjetesterv2

- prow/jobs/scans/whitesource-periodics.yaml
- templates/data/whitesource-periodics-data.yaml
- Remove `terraform-provider-gardener-whitesource-scan` Whitesource job, which is unused since Kyma 2.3
> Remove `terraform-provider-gardener-whitesource-scan` Whitesource job

- development/custom-image/install-deps-debian.sh
- Revert minikube binary removal from VM image
- https://github.com/kyma-project/test-infra/pull/5597
> Revert minikube removal from VM image

- prow/jobs/kyma-operator/operator.yaml
- templates/data/kyma-operator-data.yaml
- vpath/pjtester.yaml
> replace with golangci-lint image

- prow/jobs/kyma/kyma-integration.yaml
- templates/data/kyma-integration-data.yaml
> Preview job: Update k8s to 1.24.2

- prow/scripts/cluster-integration/busola-lighthouse.sh
- prow/scripts/cluster-integration/kyma-busola-long-lasting.sh
> Downgrade nginx ingress in the remaining busola pipelines

- prow/cluster/resources/external-secrets/external_secrets_workloads.yaml
- prow/jobs/test-infra/pjtester.yaml
- templates/data/pjtester-data.yaml
Pjtester will call github more often. Using and authenticated calls will increase rate limits.
> Pjtester prowjob use gh token

- prow/jobs/kyma/kyma-integration.yaml
- templates/data/kyma-integration-data.yaml
- Run AC tests also if the tests changed
https://github.com/kyma-project/kyma/issues/14654
> Run AC tests also if the tests changed

- prow/jobs/test-infra/pjtester.yaml
- templates/data/pjtester-data.yaml
Add pjtesterv2 prowjob for kyma repository. This allow test if PR in kyma repo with pjtesterv2.yaml file will trigger correct test prowjob.
> pjtester v2 for kyma repo for further tests

- prow/jobs/kyma/kyma-integration.yaml
- templates/data/kyma-integration-data.yaml
Since Istio pipelines are now stable we are setting them as mandatory.
> Set istio pipelines to mandatory

- prow/config.yaml
- prow/images/bootstrap/Dockerfile
- prow/scripts/resources/busola/cluster-busola.yaml
- prow/scripts/resources/busola/cluster-kyma.yaml
- prow/scripts/resources/reconciler/shoot-template.yaml
- templates/templates/prow-config.yaml
- Update k8s version to 1.23
https://github.com/kyma-project/test-infra/issues/5702
> update k8s to 1.23

- prow/config.yaml
- templates/templates/prow-config.yaml
> Enhance highlight regex for error log

- prow/jobs/kyma/releases/kyma-release-23.yaml
- prow/jobs/kyma/releases/kyma-release-24.yaml
- Revert k8s version for `pre-rel23-kyma-integration-k3d` job
- #5755
> Revert k8s version for broken previous release jobs

- .github/dependabot.yml
- templates/data/dependabot-config-data.yaml
- add `golangci-lint` image to the dependabot configuration
> Autobump golangci-lint base image

- prow/jobs/control-plane/kcp-cli.yaml
- templates/data/control-plane-kcp-data.yaml
- run the `pre-main-kcp-cli` pipeline every change in the `components` dir
https://github.com/kyma-project/control-plane/pull/1886
> Improve kcp cli pipeline

- prow/config.yaml
- templates/templates/prow-config.yaml
- Updates merge method to `squash` for operator relevant repositories
https://github.com/kyma-project/test-infra/issues/5793
> feat: update merge method to squash for operator repos

- prow/jobs/scans/whitesource-periodics.yaml
- templates/data/whitesource-periodics-data.yaml
- Add whitesource scans for
- [kyma-operator](https://github.com/kyma-project/kyma-operator)
- [kyma-watcher](https://github.com/kyma-project/kyma-watcher)
- [manifest-operator](https://github.com/kyma-project/manifest-operator)
- https://github.com/kyma-project/kyma-operator/issues/48
> Add Whitesource Scans for new Kyma components

- prow/jobs/incubator/reconciler/reconciler.yaml
- templates/data/incubator-buildpack-data.yaml
- https://github.com/kyma-project/kyma/issues/14978
> Make two blocking reconciler jobs optional

- prow/jobs/incubator/reconciler/reconciler.yaml
- templates/data/incubator-buildpack-data.yaml
Reverts kyma-project/test-infra#5813
> Revert "Make two blocking reconciler jobs optional"

- docs/prow/production-cluster-configuration.md
- Fix link to the DNS registry
> fix DNS link

- prow/jobs/kyma/releases/kyma-release-25.yaml
- Bump images for Kyma 2.5 jobs
> Bump images for Kyma 2.5 jobs

- prow/scripts/cluster-integration/busola-integration-test-k3s.sh
- prow/scripts/cluster-integration/busola-lighthouse.sh
- prow/scripts/provision-vm-and-start-busola-k3s.sh
- vpath/pjtester.yaml
- Pass `examples` directory to Busola e2e tests
- Fix a typo
> Pass examples folder to busola tests

- development/image-syncer/external-images.yaml
- Update the alpine image version in the image syncer
> Update alpine image version in the image syncer

- prow/cluster/resources/external-secrets/external_secrets_trusted.yaml
- prow/cluster/resources/external-secrets/external_secrets_workloads.yaml
Secret is used by pjtester which is running in trusted cluster.
> Move pjtester github token to trusted cluster.

- prow/jobs/kyma-operator/kyma-operator.yaml
- templates/data/kyma-operator-data.yaml
- vpath/pjtester.yaml
- Setup Image Build for Kyma Operator
Part of https://github.com/kyma-project/test-infra/issues/5859
> Kyma operator IMG build

- prow/jobs/manifest-operator/manifest-operator.yaml
- templates/data/manifest-operator-data.yaml
Description
Setup Image Build for Manifest Operator
Related issue(s)
Part of https://github.com/kyma-project/test-infra/issues/5859
> Manifest operator IMG Build

- development/gcp/cloud-functions/rotateserviceaccount/go.mod
- development/gcp/cloud-functions/rotateserviceaccount/go.sum
> Update SA rotation cloudfunc go.mod

- prow/jobs/kyma-watcher/kyma-watcher.yaml
- templates/data/kyma-watcher-data.yaml
- Setup Image Build for Kyma Watcher SKR
- Setup Image Build for Kyma Watcher KCP
Part of https://github.com/kyma-project/test-infra/issues/5859
> Kyma watcher IMG build 

- development/gcp/cloud-functions/rotateserviceaccount/README.md
> Add service account rotation function documentation

- prow/jobs/incubator/compass-console/compass/compass-ui.yaml
- prow/jobs/incubator/compass/components/connectivity-adapter/connectivity-adapter-generic.yaml
- prow/jobs/incubator/compass/components/connector/connector-generic.yaml
- prow/jobs/incubator/compass/components/director/director-generic.yaml
- prow/jobs/incubator/compass/components/external-services-mock/external-services-mock-generic.yaml
- prow/jobs/incubator/compass/components/gateway/gateway-generic.yaml
- prow/jobs/incubator/compass/components/hydrator/hydrator-generic.yaml
- prow/jobs/incubator/compass/components/operations-controller/operations-controller-generic.yaml
- prow/jobs/incubator/compass/components/pairing-adapter/pairing-adapter-generic.yaml
- prow/jobs/incubator/compass/components/schema-migrator/schema-migrator-generic.yaml
- prow/jobs/incubator/compass/components/system-broker/system-broker-generic.yaml
- prow/jobs/incubator/compass/tests/compass-e2e-tests/compass-e2e-tests.yaml
- prow/jobs/incubator/ord-service/components/ord-service/ord-service-generic.yaml
- templates/data/generic_component_compass_data.yaml
- 15min seemed like too risky - this PR ups the timeout to 20min
> Increase Compass component job timeout

- prow/config.yaml
- templates/templates/prow-config.yaml
- Add `[ERROR] `to log highlights list regex
- ...
- ...
> Add [ERROR] to log highlights list

- prow/config.yaml
- templates/templates/prow-config.yaml
> Fix [ERROR] on log highlights list

- prow/config.yaml
- prow/jobs/kyma/kyma-integration-gardener.yaml
- templates/data/kyma-integration-gardener-data.yaml
- Set api-gateway pipeline to mandatory as it is stable
> Set api-gateway pipeline to mandatory

- prow/scripts/cluster-integration/helpers/reconciler.sh
We are facing connectivity issues to the API server in Gardener and want to verify whether it'S a logic issue on our side or connectivity problem on Gardener side.
Therefore, a few debugging calls are added.
https://github.com/kyma-project/kyma/issues/14992
> Add debug message for reconciler-status check

- configs/gcbuild-config.yaml
- prow/plugins.yaml
> Add gcbuild-config.yaml ConfigMap to workload clusters with autobumps

- prow/scripts/provision-vm-compass-smoke-test.sh
- Use proper commit hash when checkout ORD service sources
> Adjust commit hash

- prow/scripts/provision-vm-compass-smoke-test.sh
Extract ORD commit hash based on the status of the given PR - open or closed.
> Extract ORD commit hash based on PR state

- prow/config.yaml
- prow/jobs/runtime-watcher/runtime-watcher.yaml
- prow/jobs/scans/whitesource-periodics.yaml
- templates/data/runtime-watcher-data.yaml
- templates/data/whitesource-periodics-data.yaml
- templates/templates/prow-config.yaml
- renames `kyma-watcher` to `runtime-watcher`
https://github.com/kyma-project/community/issues/702
> rename kyma-watcher => runtime-watcher

- prow/config.yaml
- prow/jobs/module-manager/module-manager.yaml
- prow/jobs/scans/whitesource-periodics.yaml
- prow/jobs/test-infra/checkconfig.yaml
- templates/config.yaml
- templates/data/manifest-operator-data.yaml
- templates/data/whitesource-periodics-data.yaml
- templates/templates/prow-config.yaml
- rename manifest-operator => module-manager
https://github.com/kyma-project/module-manager/pull/75
> rename manifest-operator => module-manager

- prow/scripts/cluster-integration/helpers/reconciler.sh
Fix wrong resolution of Kyma template json for reconciler.
> Adjust reconciler template resolution

- prow/scripts/cluster-integration/helpers/reconciler.sh
Use main-JSON template as default payload when calling reconciler.
> Use main-template as default when calling reconciler

- prow/scripts/cluster-integration/reconciler-e2e-gardener.sh
Required to provide a test cluster to Gardener team 
https://github.com/gardener/gardener/issues/6588
> Do not cleanup defective Gardener cluster - Analysis of VPN seed issue

- prow/scripts/cluster-integration/kyma-integration-k3d.sh
/priority critical
/kind bug
/area ci
> Remove catting environment variables in load_env

- development/image-syncer/external-images.yaml
- Provide prometheus image v2.38.0
> Bump prometheus image

- prow/config.yaml
- templates/templates/prow-config.yaml
> Set merge method for incubator/migrate

- development/tools/jobs/api-gateway/api_gateway_test.go
- prow/jobs/api-gateway/api-gateway-build.yaml
- templates/data/generic_component_api_gateway_data.yaml
Update job configurations, fix tests.
> Update api-gateway jobs

- development/tools/jobs/cli/cli_compatibility_test.go
- development/tools/jobs/cli/cli_test.go
- prow/jobs/cli/cli-compatibility.yaml
- prow/jobs/cli/cli.yaml
- templates/data/cli-data.yaml
> Update CLI jobs to not use build-generic.sh

- development/image-syncer/external-images.yaml
- Bumped GO image to 1.19.1 in external images
> Bumped GO image to 1.19.1 in external images

- prow/jobs/kyma/kyma-integration.yaml
- prow/scripts/provision-vm-and-start-kyma-k3d.sh
- templates/data/kyma-integration-data.yaml
- test-inventory-integration.md
- vpath/pjtester.yaml
- Setup a pipeline for running reconciler related component tests
https://github.com/kyma-project/kyma/issues/15279
> Istio reconcilation component test pipeline

- development/image-syncer/external-images.yaml
- Bump NATS external image to 2.9.0
> Bump NATS external image to 2.9.0

- prow/jobs/kyma/kyma-integration-gardener.yaml
- templates/data/kyma-integration-gardener-data.yaml
> Make eventing jobs required

- prow/images/gardener-rotate/Dockerfile
- Add executable flag to Gardner rotate tool
- ...
- ...
> Add executable flag to Gardner rotate tool

- prow/scripts/build-kyma-artifacts.sh
- prow/scripts/changelog-generator.sh
and note changelog-generator.sh as deprecated
> remove changelog-generator from kyma-artifacts

- prow/scripts/build-kcp-cli.sh
@kyma-project/gopher would like to build and release the ERS cli tool the same way KCP cli is done.
> Build and release ERS cli along KCP cli

- development/image-syncer/external-images.yaml
- Add istio install-cni image to image registry
- https://github.com/kyma-project/test-infra/issues/5954
> Add istio cni to image syncer

- prow/scripts/build-kcp-cli.sh
followup to https://github.com/kyma-project/test-infra/pull/6031, I used double quotes wrong with globbing...
> Fix quotes with globbing for KCP and ERS tools build script

- prow/jobs/scans/protecode-guard.yaml
- templates/data/protecode-guard-data.yaml
- make Protecode job optional
https://github.com/kyma-project/test-infra/issues/6050
> Make protecoide jobs optional

- development/kaniko-build/config_test.go
- development/kaniko-build/main.go
- prow/jobs/lifecycle-manager/lifecycle-manager.yaml
- prow/jobs/module-manager/module-manager.yaml
- prow/jobs/runtime-watcher/runtime-watcher.yaml
- prow/jobs/test-infra/buildpack.yaml
- templates/data/buildpack-data.yaml
- templates/data/lifecycle-manager-data.yaml
- templates/data/module-manager-data.yaml
- templates/data/runtime-watcher-data.yaml
There was a bug that instead of checking DevRegistry, I've checked Regular registry. That made the builder assume empty DevRegistry value
/kind bug
/area ci
> Fix kaniko build

- prow/jobs/test-infra/pjtester.yaml
- templates/data/pjtester-data.yaml
Fixed image path in registry to align with paths used by kaniko-build.
> Align image path with kaniko-build.

- prow/jobs/lifecycle-manager/lifecycle-manager.yaml
- prow/jobs/module-manager/module-manager.yaml
- prow/jobs/runtime-watcher/runtime-watcher.yaml
- templates/data/lifecycle-manager-data.yaml
- templates/data/module-manager-data.yaml
- templates/data/runtime-watcher-data.yaml
- vpath/pjtester.yaml
- adds "--tag latest" to the image builds on main for all operators to have always up to date latest tag
> setup latest tags for operator builds

- development/tools/cmd/usersmapchecker/main.go
- development/tools/pkg/dnscollector/collector.go
- development/tools/pkg/dnscollector/wrappers.go
- development/tools/pkg/firewallcleaner/cleaner.go
- development/tools/pkg/firewallcleaner/options.go
- development/tools/pkg/firewallcleaner/wrappers.go
- development/tools/pkg/metadata/jsonmetadatavalidator.go
- development/tools/pkg/orphanremover/remover.go
- development/tools/pkg/orphanremover/wrappers.go
- development/tools/pkg/release/options.go
- development/tools/pkg/release/release.go
- Fix issues with `pre-main-test-infra-validate-prow-tools` job by running ` goimports -w -l **/*.go` in development/tools
> Fix linting issues

- prow/scripts/cluster-integration/control-plane-gke-integration.sh
- prow/scripts/lib/kyma.sh
- Controlplane job still uses kyma 1 installation.
> Some jobs still use kyma 1 installation

- prow/jobs/kyma/components/function-controller/function-controller-generic.yaml
- templates/data/generic_component_data.yaml
- vpath/pjtester.yaml
- add function-controller correct build jobs
- ...
- ...
> Fix build jobs for severless components

- prow/jobs/kyma/components/function-runtimes/function-runtimes-generic.yaml
- templates/data/generic_component_data.yaml
- Set correct context for Serverless runtime build jobs
- ...
- ...
> Fix Serverless runtimes build jobs

- prow/jobs/test-infra/buildpack.yaml
- templates/data/buildpack-data.yaml
- add build for gardener-sa-rotate image
- #5749
> Build gardener-sa-rotate

- development/gcp/cloud-run/gardener-sa-rotate/Dockerfile
> Fix gardener-sa-rotate dockerfile

- prow/scripts/cluster-integration/kyma-gke-external-registry.sh
- vpath/pjtester.yaml
* https://github.com/kyma-project/cli/pull/1398
* https://github.com/kyma-project/kyma/pull/15648
> Fix the `kyma-gke-external-registry` pipeline by using the unstable kyma_cli version

- development/gcp/cloud-run/gardener-sa-rotate/README.md
- Add documentation to Gardener SA rotate tool
- #5749
> Add documentation to Gardener SA rotate tool

- prow/jobs/api-gateway/api-gateway-build.yaml
- prow/jobs/api-gateway/api-gateway-release.yaml
- templates/data/api-gateway-build.yaml
- templates/data/api-gateway-release.yaml
- Change `api-gateway` images to `api-gateway-controller`
> Revert api-gateway image names

- prow/jobs/runtime-watcher/runtime-watcher.yaml
- templates/data/runtime-watcher-data.yaml
- KCP runtime-watcher is moved to lifecycle-manager, so removing the relevant jobs. The removed job logic will be covered as part of lifecycle-manager
> remove KCP runtime-watcher jobs

- development/gcp/cloud-functions/serviceaccountcleaner/README.md
- Add documentation for service account cleaner
- #5868
- #5748
> Add documentation for service account cleaner

- development/jobguard/scripts/run.sh
> Add missing `pull` regexp for the jobguard

- prow/jobs/test-infra/go-validation.yaml
- Run linter on go.mod changes
> Run linter on go.mod changes

- prow/jobs/kyma/components/function-runtimes/function-runtimes-generic.yaml
- templates/data/generic_component_data.yaml
Removal of deprecated runtime build jobs
https://github.com/kyma-project/kyma/issues/15771
> Remove nodej12 build jobs

- CODEOWNERS
I do not contribute to the test-infra enough to be a code owner.
> Remove myself from CODEWNERS

- CODEOWNERS
- remove hanngos from CODEOWNERS
> Remove hanngos from CODEOWNERS

- prow/jobs/kyma/components/kyma-components-static-checks.yaml
- templates/data/go-toolkit-validation.yaml
Make Eventing unit-test jobs required:
- pull-event-publisher-proxy-unit-test.
- pull-eventing-controller-unit-test.
> Make Eventing unit-test jobs required

- CODEOWNERS
- removing myself from the pipeline codeowners
> Remove janmedrek from the Application Connector codeowners

- prow/jobs/modules/external/keda-manager/keda-manager-generic.yaml
- templates/data/generic_external_module_data.yaml
- Add new jobs to keda-manager
See also: https://github.com/kyma-project/keda-manager/issues/16
> Add new jobs to keda-manager

- prow/jobs/test-infra/gardener-kubeconfig-rotation.yaml
- templates/data/secret-rotation-data.yaml
- Use trusted cluster for Gardener token rotation
> Use trusted cluster for Gardener token rotation

- development/gcp/cloud-run/kms-rotate/Dockerfile
> Fix path to kms-rotate tool

- development/gcp/cloud-run/kms-rotate/kms-rotate.go
- List only enabled versions of a key
- #5290
> Fix KMS rotation

- prow/jobs/test-infra/triage-jobs.yaml
/kind bug
/area ci
/cc @Halamix2
> fix --updated flag parse error

- prow/jobs/kyma/components/kyma-components-static-checks.yaml
- templates/data/go-toolkit-validation.yaml
Enable Eventing unit-test jobs for all changes:
- pull-eventing-controller-unit-test
- pull-event-publisher-proxy-unit-test
> Enable Eventing unit-test jobs for all changes

- development/gcp/cloud-run/kms-rotate/README.md
- Add documentation for KMS rotation tool
- #5290
> Add documentation for KMS rotation tool

- prow/jobs/kyma/kyma-integration.yaml
- templates/data/kyma-integration-data.yaml
- vpath/pjtester.yaml
- Set  TELEMETRY_TRACING_ENABLED to copy Tracing CRD for `kyma-integration-k3d-telemetry` and `post-main-kyma-integration-k3d-telemetry`
> Fix telemetry periodic and post

- development/image-builder/main.go
> Add initial cache support to buildkit image-builder

- prow/scripts/cli-tests/test-function.sh
- remove deprecated nodejs12
See also https://github.com/kyma-project/kyma/issues/15771
> remove nodejs12

- prow/jobs/control-plane/components/kubeconfig-service/kubeconfig-service-build.yaml
- prow/jobs/control-plane/components/kyma-environment-broker/kyma-environment-broker-build.yaml
- prow/jobs/control-plane/components/kyma-metrics-collector/kyma-metrics-collector-build.yaml
- prow/jobs/control-plane/components/provisioner/provisioner-build.yaml
- prow/jobs/control-plane/components/schema-migrator/schema-migrator-build.yaml
- prow/jobs/modules/external/keda-manager/keda-manager-generic.yaml
- prow/jobs/test-infra/buildpack.yaml
- templates/data/buildpack-data.yaml
- templates/data/control-plane-build.yaml
- templates/data/generic_external_module_data.yaml
> chore: remove deprecated `--directory` flag from build jobs

- prow/jobs/modules/external/keda-manager/keda-manager-generic.yaml
- templates/data/generic_external_module_data.yaml
- changes in `operator/config` directory and in `operator/PROJECT` file should trigger job that builds keda module
See also: https://github.com/kyma-project/keda-manager/issues/41
> update keda-manager triggers

- configs/kaniko-build-config.yaml
> Add missing tag-template to image-builder config file

- prow/jobs/api-gateway/api-gateway-validation.yaml
- templates/data/api-gateway-validation.yaml
- vpath/pjtester.yaml
- Fix lint timeout
- Add html report
> Fix api-gateway lint timeout

- development/image-syncer/external-images.yaml
- Add postgres-exporter [0.11.1-debian-11-r23](https://hub.docker.com/layers/bitnami/postgres-exporter/0.11.1-debian-11-r23/images/sha256-d4118bfaa193f6472e2752443b47755aee695516bce00267a7d7a05fc1e86b33?context=explore)
> Add Postgres-exporter 0.11.1-debian-11-r23 to image refs

- prow/scripts/resources/busola/cluster-busola.yaml
- prow/scripts/resources/busola/cluster-kyma.yaml
- Bump Busola cluster version to a supported one.
> Bump Busola clusters version

- prow/jobs/btp-manager/btp-manager-build.yaml
- templates/data/btp-manager-build.yaml
> change path to dockerfile

- prow/scripts/resources/reconciler/shoot-template.yaml
- Update Gardener shoot version to 1.24.6
> Update shoot version

- .github/dependabot.yml
- Exclude onsi gomeg updates to 1.23.0 version.
Update to this version causing multiple test failed. https://github.com/kyma-project/test-infra/pull/6312
> Exclude onis gomega 1.23.0 from dependabot updates.

- prow/jobs/modules/external/keda-manager/keda-manager-generic.yaml
- templates/data/generic_external_module_data.yaml
- vpath/pjtester.yaml
> Update keda-manager jobs with flattened layout

- CODEOWNERS
- Excluding automatically generated .md file from writers ownership and required reviews.
See #6250
> Exclude automatically generated files from review.

- prow/jobs/test-infra/checkconfig.yaml
- prow/jobs/test-infra/pjtester.yaml
- templates/config.yaml
- templates/data/pjtester-data.yaml
- Modify pjtester prowjob template to generate jobs for all repos defined in templates/config file.
Pjtester will support triggering tests from PRs created in all repos in kyma organisations. Prowjobs for running pjtester must be present for all repos in kyma orgs.
> Generate pjtester prowjobs for all repositories from templates config.

- prow/jobs/test-infra/checkconfig.yaml
- prow/jobs/test-infra/pjtester.yaml
Using newest prow-tools image.
> Use new version of prow-tools.

- development/tools/cmd/githubrelease/Dockerfile
- Bump `lerna-changelog` to 2.2.0
> Bump changelog generator

- prow/cluster/components/monitoring/prometheus_operator_deployment.yaml
- Bump Prometheus operator to 0.60.1
> Bump Prometheus operator

- docs/documentation_guidelines.md
- Add documentation guidelines for Neighbors team and their repositories
- 
[
](https://github.com/kyma-project/test-infra/issues/6147)
> new documentation guidelines

- development/image-syncer/external-images.yaml
According to the comment - https://github.com/kyma-project/test-infra/pull/6182#pullrequestreview-1150605654
adding the perf image to the external-images.yaml
> Adding jmeter-performance image

- .github/dependabot.yml
- templates/data/dependabot-config-data.yaml
- gomod(deps): bump github.com/onsi/ginkgo/v2 from 2.3.0 to 2.5.0 makes multiple jobs to fail with logr api errors, look in the https://github.com/kyma-project/test-infra/issues/6303 issue
Fixes https://github.com/kyma-project/test-infra/pull/6358
> Exclude onsi/ginkgo/v2 from dependabot updates.

- prow/jobs/test-infra/validation.yaml
- templates/data/validation-data.yaml
- remove pre-main-test-infra-validate-prow-jobs
- ...
- ...
> remove pre-main-test-infra-validate-prow-jobs

- prow/jobs/busola/busola-web/periodic-performance-tests-web.yaml
This PR is for adding the performance Tests for busola web application.
- Added a periodic prow job
> Adding kyma-web-performance periodic job

- development/tools/jobs/testinfra/validate_test.go
- remove TestValidateProwJobsPresubmit test
> remove TestValidateProwJobsPresubmit test

- development/tools/jobs/releases/releases.go
- templates/templates/releases.go.tmpl
- fix formatting to unlock `validate-prow-jobs` jobs
> Fix releases Go file

- prow/jobs/kyma/kyma-integration.yaml
- prow/jobs/kyma/releases/kyma-release-210.yaml
- prow/jobs/kyma/releases/kyma-release-29.yaml
- templates/data/kyma-integration-data.yaml
- templates/data/kyma-release-data.yaml
- Starting from Kyma 2.9 we decided to disable Admission Controller on GKE clusters.
https://github.com/kyma-project/kyma/issues/16105
> Remove preset-gke-pod-security-policy for GKE

- CODEOWNERS
> Remove pPrecel, m00g3n and moelsayed from the CODEOWNERS file

- go.mod
- go.sum
- Bump containerregistry dependency
- ...
- ...
- #6383
> Bump containerregistry dependency

- prow/scripts/cluster-integration/kyma-gke-release-candidate.sh
- create token manually (k8s 1.24 won't create one automatically)
> Fix release candidate cluster job

- prow/cluster/components/monitoring/grafana_deployment.yaml
- prow/jobs/test-infra/kyma-bot.yaml
- templates/data/kyma-bot-data.yaml
- Bump outdated images
- grafana
- prow-tools
> Bump images

- prow/cluster/components/monitoring/dashboards/quality/quality.json
- Adjust quality dashboard time frame to display 7 days by default
> Adjust quality dashboard time frame

- prow/jobs/test-infra/buildpack.yaml
- templates/data/buildpack-data.yaml
- Fix bootstrap post build job
> Fix bootstrap build job

- prow/images/debug-commando/Dockerfile
- bump buildpack-golang dependency
> Bump outdated dependencies

- prow/cluster/resources/external-secrets/external_secrets_workloads.yaml
> Remove unused Azure secret

- prow/scripts/cluster-integration/kyma-integration-k3d-telemetry.sh
- prow/scripts/provision-vm-and-start-kyma-k3d.sh
- vpath/pjtester.yaml
- Added new script call to provision script
- Added new script for telemetry
- Added new dry-run check
> Moving telemetry related tests to separate scripts

- prow/jobs/incubator/reconciler/reconciler.yaml
- templates/data/incubator-buildpack-data.yaml
Reverting [this](https://github.com/kyma-project/test-infra/pull/6375/commits/7305bb6b0cbe59870a79e3b0a95c848fe4b6aefc) 
https://github.com/kyma-project/kyma/issues/15994
> Make reconciler-cli-kyma-prev-to-last-release-upgrade-k3d mandatory

- prow/config.yaml
- templates/templates/prow-config.yaml
> Remove protection for luigiless-busola branch in busola

- .github/dependabot.yml
- templates/data/dependabot-config-data.yaml
- Fix dependabot paths for plugins
> Fix dependabot paths

- prow/jobs/test-infra/poc-tekton.yaml
Adding prototype tekton agent prowjob definition for Tekton POC.
> Tekton poc pipeline.

- prow/jobs/kyma/skr-integration.yaml
- templates/data/skr-integration-data.yaml
- test-inventory-integration.md
- vpath/pjtester.yaml
> Enable preview again

- development/markdown-index/bumper/bumper.go
- Fix failing post-test-infra-markdown-index-autobump
> Fix failing post-test-infra-markdown-index-autobump

- prow/jobs/test-infra/poc-tekton.yaml
> starting setup

- prow/cluster/resources/external-secrets/external_secrets_workloads.yaml
> Add signify secret

- prow/jobs/lifecycle-manager/lifecycle-manager.yaml
- templates/data/lifecycle-manager-data.yaml
- templates/data/module-manager-data.yaml
add global kaniko_buildpack to add missing signify-secret volumes
clean up redundant local default config
related failing prow job [https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_lifecycle-manage[…]ull-lifecycle-mgr-build/1597198762441183232/build-log.txt](https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_lifecycle-manager/327/pull-lifecycle-mgr-build/1597198762441183232/build-log.txt)
> Fix sign image

- .gitignore
- ignore Visual Studio Code Go debug binary
> ignore VSC debug files

- prow/images/kyma-integration/Dockerfile
- Install kustomize in kyma-integration image
- https://github.com/kyma-project/kyma/issues/15521
> Install kustomize in kyma-integration image

- prow/config.yaml
- templates/templates/prow-config.yaml
- enable protection for btp-manager
> enable protection

- docs/prow/authorization.md
- docs/prow/production-cluster-configuration.md
> fix prow links

- development/custom-image/install-deps-debian.sh
- change PATH export in VM image to properly escape it
- update Go to 1.19.3
/retest
> Update VM image

- prow/jobs/kyma/components/function-runtimes/function-runtimes-generic.yaml
- templates/data/generic_component_data.yaml
- use correct path to trigger function runtime build
https://github.com/kyma-project/test-infra/issues/6498
> Fix triggering path for serverless runtimes

- CODEOWNERS
- removed a-thaler where not applicable
- ...
- ...
> removed a-thaler from many code ownerships

- prow/jobs/incubator/compass/components/connectivity-adapter/connectivity-adapter-generic.yaml
- prow/jobs/incubator/compass/components/connector/connector-generic.yaml
- prow/jobs/incubator/compass/components/director/director-generic.yaml
- prow/jobs/incubator/compass/components/external-services-mock/external-services-mock-generic.yaml
- prow/jobs/incubator/compass/components/gateway/gateway-generic.yaml
- prow/jobs/incubator/compass/components/hydrator/hydrator-generic.yaml
- prow/jobs/incubator/compass/components/operations-controller/operations-controller-generic.yaml
- prow/jobs/incubator/compass/components/pairing-adapter/pairing-adapter-generic.yaml
- prow/jobs/incubator/compass/components/schema-migrator/schema-migrator-generic.yaml
- prow/jobs/incubator/compass/components/system-broker/system-broker-generic.yaml
- prow/jobs/incubator/compass/tests/compass-e2e-tests/compass-e2e-tests.yaml
- templates/data/generic_component_compass_data.yaml
Reduce the Compass build jobs timeouts. Most of them run for a maximum of 15 minutes, so there's no need for their timeout to be 60.
- Reduce compass build jobs timeouts
> Reduce compass build jobs timeouts.

- prow/scripts/cluster-integration/kyma-integration-k3d-telemetry.sh
- vpath/pjtester.yaml
> Always print telemetry operator logs

- README.md
- Add information about the index page
> Index page

- prow/jobs/scans/whitesource-periodics.yaml
- templates/data/whitesource-periodics-data.yaml
> Add Mend scans for Warden

- prow/jobs/kyma/components/function-runtimes/function-runtimes-generic.yaml
- templates/data/generic_component_data.yaml
- Rename Java11 builds to Java17
https://github.com/kyma-project/kyma/issues/15825
> Rename java11 to java17

- prow/jobs/modules/external/keda-manager/keda-manager-generic.yaml
- templates/data/generic_external_module_data.yaml
- Add new post-submit job to build keda-module
See also:
- https://github.com/kyma-project/keda-manager/issues/58
- https://github.com/kyma-project/keda-manager/pull/62
> Add new post-submit job to build keda-module

- prow/jobs/modules/external/keda-manager/keda-manager-generic.yaml
- templates/data/generic_external_module_data.yaml
- Update artifact registry URLs
> Update artifact registry URLs

- prow/jobs/kyma/kyma-integration-gardener.yaml
- prow/scripts/cluster-integration/helpers/eventing.sh
- prow/scripts/cluster-integration/kyma-integration-gardener-eventing.sh
- templates/data/kyma-integration-gardener-data.yaml
- test-inventory-integration.md
- vpath/pjtester.yaml
- Added `pre-main-kyma-gardener-gcp-eventing-v1alpha2` job.
- https://github.com/kyma-project/kyma/issues/15521
> Add pre-main-eventing job for Subscription v1alpha2 CRD

- docs/prow/label_sync.md
- Add label_sync basic docs.
- 
> label_sync docs

- development/image-syncer/external-images.yaml
> Bump cypress version

- development/custom-image/install-deps-debian.sh
- prow/scripts/cluster-integration/busola-integration-test-k3s.sh
- prow/scripts/cluster-integration/busola-smoke-test-docker.sh
This reverts commit 734afdd23b8e38218225594325d626a5a81b762b.
- Revert cypress version
> Revert "Bump cypress and Node version (#6563)"

- development/image-syncer/external-images.yaml
-bump prometheus image to [2.40.6](https://github.com/prometheus/prometheus/releases) to cover some new security fixes.
> bump prometheus to latest image 2.40.6

- prow/jobs/test-infra/checkconfig.yaml
- prow/jobs/test-infra/pjtester.yaml
- templates/config.yaml
- set `merge_method` to `squash` for btp-manager repo in tide config
> Add btp-manager repo to tide config

- prow/config.yaml
- templates/templates/prow-config.yaml
Reverts kyma-project/test-infra#6571
> Add merge method for btp-manager in tide config

- prow/jobs/kyma/components/function-runtimes/function-runtimes-generic.yaml
- templates/data/generic_component_data.yaml
> Fix java image name

- prow/jobs/governance.yaml
- templates/data/governance-data.yaml
- Disabling addons repo scanns for dead links. Repo is archived.
> Disable scanning for dead links in addons repository.

- prow/jobs/busola/lighthouse.yaml
- templates/data/busola-lighthouse.yaml
> change lighthouse job to optional

- prow/images/kyma-integration/Dockerfile
KCP CLI is under active development and https://github.com/kyma-project/kyma/pull/16370 would like to leverage new `--events` option refined in https://github.com/kyma-project/control-plane/pull/2329 to improve the information available in tests.
> Update kcp to master-8a4162fd

- development/tools/jobs/kyma/kyma_integration_test.go
- development/tools/jobs/tester/tester.go
- prow/cluster/resources/external-secrets/external_secrets_checker_prow.yaml
- prow/jobs/busola/busola-backend/backend-deployment-check.yaml
- prow/jobs/busola/busola-web/web-deployment-check.yaml
- prow/jobs/busola/integration-docker-test.yaml
- prow/jobs/busola/integration-k3s-test.yaml
- prow/jobs/busola/lighthouse.yaml
- prow/jobs/control-plane/control-plane-gke-integration.yaml
- prow/jobs/control-plane/control-plane-reconciler-integration.yaml
- prow/jobs/control-plane/control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener.yaml
- prow/jobs/incubator/reconciler/reconciler.yaml
- prow/jobs/kyma/kyma-gardener-cleanup.yaml
- prow/jobs/kyma/kyma-gke-external-registry.yaml
- prow/jobs/kyma/kyma-integration-gardener.yaml
- prow/jobs/kyma/kyma-integration.yaml
- prow/jobs/kyma/kyma-validation.yaml
- prow/jobs/kyma/releases/kyma-release-210.yaml
- prow/jobs/kyma/skr-aws-upgrade-integration-dev.yaml
- prow/jobs/kyma/skr-integration.yaml
- prow/jobs/test-infra/kyma-bot.yaml
- prow/jobs/test-infra/pjtester.yaml
- prow/jobs/test-infra/prow-periodics.yaml
- prow/jobs/test-infra/unstale-gardener-project.yaml
- prow/scripts/resources/debug-container.yaml
- templates/config.yaml
- Same as  #6602, with fixed tests
> Bumping test-infra

- development/custom-image/install-deps-debian.sh
As title 
https://github.com/kyma-project/serverless-manager/issues/22
> Add Pkg-config to debian vm

- development/custom-image/install-deps-debian.sh
> add libgit 2

- prow/scripts/cluster-integration/serverless-integration-k3s.sh
- vpath/pjtester.yaml
- enable java on serverless pipelines
- https://github.com/kyma-project/kyma/pull/15910
https://github.com/kyma-project/kyma/issues/15660
> Enable java on serverless pipelines

- prow/scripts/resources/kyma-serverless-external-registry-integration-overrides.tpl.yaml
- add override to enable java on gke external registry tests
> Enable java on gke external registry

- development/image-syncer/external-images.yaml
-Bump to latest lts version of prometheus
> bump prometheus image to 2.40.7

- prow/jobs/kyma/components/kyma-components-static-checks.yaml
- templates/data/go-toolkit-validation.yaml
- Made eventing lint jobs required
> Made eventing lint jobs required

- prow/jobs/api-gateway/api-gateway-release.yaml
- prow/jobs/kyma/kyma-gke-external-registry.yaml
- templates/data/api-gateway-release.yaml
- Fix api-gateway release pipeline
- Use tag from PULL_BASE_REF
- Add remote for goreleaser
> Fix API-gateway release pipeline

- prow/config.yaml
- prow/jobs/kyma/kyma-gke-external-registry.yaml
- templates/templates/prow-config.yaml
> add kyma-dashboard to squash

- prow/jobs/api-gateway/api-gateway-release.yaml
- prow/jobs/kyma/kyma-gke-external-registry.yaml
- templates/data/api-gateway-release.yaml
- Remove "/bin/sh" which was missed in https://github.com/kyma-project/test-infra/commit/eee1aae0b5caa9abb7e1933c43d9694c1a598a46
Prow log:
- https://github.com/kyma-project/api-gateway
> Remove "/bin/sh" from api gateway release pipeline

- prow/jobs/btp-manager/btp-manager-build.yaml
- templates/data/btp-manager-build.yaml
Required changes after btp-manager project structure changes.
See: https://github.com/kyma-project/btp-manager/pull/92
> Fix pull-btp-manager-build

- prow/cluster/components/monitoring/dashboards/quality/prstats.json
- Add grafana dashboard with Pull Request statistics
> Pull Request statistics

- configs/tekton/deployments/config_defaults.yaml
- configs/tekton/deployments/dashboard_managedcertificate.yaml
- configs/tekton/deployments/dashboard_release.yaml
- configs/tekton/deployments/pipelines_release.yaml
- configs/tekton/deployments/pipelines_serviceaccount.yaml
Added required configuration files for Tekton pipelines and dashboard
#6621
> add tekton-pipelines and dashboard configuration

- prow/jobs/kyma/kyma-gke-external-registry.yaml
- prow/jobs/modules/external/keda-manager/keda-manager-generic.yaml
- templates/data/generic_external_module_data.yaml
Imgae builder was not able to find a go.mod file with old context.
Fixed context and dockerfile location image builder argument values. With old values go was not able to find a go.mod file and build binary.
> Fix context and dockerfile location paramters for image builder.

- prow/cluster/components/monitoring/grafana_deployment.yaml
> Add Grafana configmaps

- prow/jobs/test-infra/secret-leaks-log-scanner.yaml
- templates/data/secret-leaks-log-scanner.yaml
- Make scanner build jobs optional to unlock other PRs.
> make jobs optional

- docs/prow/prow-monitoring.md
- Update documentation about how to add new dashboard to Grafana.
> Update Grafana documentation

- prow/jobs/busola/busola-backend/busola-backend.yaml
- prow/jobs/busola/busola-web/busola-web.yaml
- prow/jobs/busola/busola.yaml
- templates/data/generic_component_busola_data.yaml
- Update run_if_changed for busola web, backend and local
> Update run_if_changed for busola web, backend and local

- prow/jobs/btp-manager/btp-manager-build.yaml
- templates/data/btp-manager-build.yaml
- vpath/pjtester.yaml
> Btp manager release1

- prow/scripts/resources/busola/cluster-busola.yaml
- prow/scripts/resources/busola/cluster-kyma.yaml
- prow/scripts/resources/reconciler/shoot-template.yaml
> Bump Gardener Linux version

- development/gcp/cloud-run/search-github-issue/Dockerfile
- development/gcp/cloud-run/search-github-issue/search-github-issues.go
- go.mod
- Service search github for open issues for detected secret leaks. Service relay on issue description metadata to find correct issues. Metadata contains a hash value for defined prowjob metadata fields.
- Service use cloudevents format.
> Serach GitHub issue service

- development/gcp/cloud-run/slack-message-sender/Dockerfile
- development/gcp/cloud-run/slack-message-sender/requirements.txt
- development/gcp/cloud-run/slack-message-sender/slack-message-sender.py
Service send slack message to notify users about detected secret leak. Message provide link to github issue with details about leak.
API method is exposed on dedicated path.
Service accept cloudevents format events.
> Send slack message service

- prow/jobs/btp-manager/btp-manager-build.yaml
- templates/data/btp-manager-build.yaml
- vpath/pjtester.yaml
- fix regexp for btp-manager jobs
> Fix btp module regexp

- prow/jobs/btp-manager/btp-manager-build.yaml
- templates/data/btp-manager-build.yaml
- set proper docker registry for post submit btp-manager job
> Btp manager registry settings

- prow/jobs/incubator/compass/components/schema-migrator/schema-migrator-generic.yaml
- templates/data/generic_component_compass_data.yaml
Reverts kyma-project/test-infra#6737
Affected by: https://github.com/docker/buildx/issues/495 
- Revert ARM build for schema migrator
> Revert ARM build for schema migrator

- prow/jobs/kyma/kyma-integration.yaml
- templates/data/kyma-integration-data.yaml
- .Upgrade post-main-k3d- to k8s 1.26
See also #6740
> Upgrade kyma preview job to k8s 1.26

- prow/config.yaml
- templates/templates/prow-config.yaml
- preset for btp-manager-bot github token
> BTP manager preset

- prow/scripts/resources/busola/cluster-busola.yaml
- prow/scripts/resources/busola/cluster-kyma.yaml
- Disallow privileged containers in Busola
> Disallow privileged containers in Busola

- prow/scripts/resources/busola/cluster-busola.yaml
- prow/scripts/resources/busola/cluster-kyma.yaml
- prow/scripts/resources/reconciler/shoot-template.yaml
- Disallow privileged containers in Busola
> Disallow priviledged containers in Busola

- prow/scripts/lib/utils.sh
- Return instead of exiting in utils::receive_from_vm to avoid failing cleanup before it has finished
> Return instead of exiting in utils::receive_from_vm

- prow/jobs/btp-manager/btp-manager-build.yaml
- templates/data/btp-manager-build.yaml
- jobs which makes btp-manager release
> BTP-manager bot preset usage

- prow/cluster/resources/external-secrets/external_secrets_trusted.yaml
> Add btp github bot

- prow/scripts/cluster-integration/kyma-integration-k3d-telemetry-components.yaml
- Tracing component added to the kyma k3d telemetry job
https://github.com/kyma-project/kyma/issues/16514
> Add tracing component to kyma k3d telemetry job

- prow/config.yaml
- templates/templates/prow-config.yaml
> Istio squash merge

- prow/cluster/resources/external-secrets/external_secrets_workloads.yaml
- Add api gateway secrets used in integration pipelines
> Add api gateway secrets

- prow/jobs/btp-manager/btp-manager-build.yaml
- templates/data/btp-manager-build.yaml
- btp-manager release jobs must not rely on run_if_changed
> BTP manager releases jobs without run_if_changed

- development/gcp/cloud-run/slack-message-sender/Dockerfile
Fixed path of files to copy from docker build context. Added missing part from repository root.
> Fixed path of files to copy from context.

- prow/jobs/btp-manager/btp-manager-build.yaml
- templates/data/btp-manager-build.yaml
- add branch rule to post-btp-manager-build job
> Branch setting for post-btp-manager-build

- prow/jobs/kyma-project/warden/warden.yaml
- templates/data/warden.yaml
- mark unit test in warden as required
> Mark unit test as mandatory in warden

- development/gcp/cloud-run/scan-logs-for-secrets/scan-logs-for-secrets.go
- development/types/types.go
Removed usage of deprecated types. All log scanner services are using the same types.
Fixed nill pointer error.
> Removed usage of deprecated types.

- prow/jobs/kyma-dashboard/kyma-dashboard-prod.yaml
- prow/jobs/kyma-dashboard/kyma-dashboard-smoke-test-prod.yaml
- prow/jobs/kyma-dashboard/kyma-dashboard-smoke-test-stage.yaml
- prow/jobs/kyma-dashboard/kyma-dashboard-stage.yaml
- templates/data/generic_component_kyma_dashboard_data.yaml
- templates/data/kyma-dashboard-smoke-test-prod.yaml
- templates/data/kyma-dashboard-smoke-test-stage.yaml
> fix: regexes for run_if_change

- prow/jobs/runtime-watcher/runtime-watcher.yaml
- templates/data/runtime-watcher-data.yaml
Mount secret for kaniko image build, to solve following problem:
```
sign images using services signify-dev
sign encountered error: signer init: open /secret/secret.yaml: no such file or directory
```
> Mount secret for image build - SKR Runtime Watcher

- prow/scripts/cluster-integration/kyma-integration-k3d-telemetry-alpha.sh
- prow/scripts/cluster-integration/kyma-integration-k3d-telemetry.sh
- vpath/pjtester.yaml
- Ignore non-zero error codes of `kubectl logs`
> Workaround: not failing the job regardless of kubectl logs result

- prow/jobs/kyma-project/warden/integration-test.yaml
> Add missing run_if_changed directive

- development/image-syncer/external-images.yaml
> Bump istio images to 1.16.2 in image-syncer

- .github/dependabot.yml
- templates/data/dependabot-config-data.yaml
- Add k8s.io libraries to dependabot ignore
https://github.com/kyma-project/test-infra/pull/6814
https://github.com/kyma-project/test-infra/pull/6815
https://github.com/kyma-project/test-infra/pull/6816
> Add libraries to dependabot ignore

- development/gcp/cloud-run/create-github-issue/create-github-issue.go
- development/gcp/cloud-run/search-github-issue/search-github-issues.go
Github issue creator and finder services read github token from path provided in environment variable.
> Secret path from env

- .github/dependabot.yml
- templates/data/dependabot-config-data.yaml
- Removed ginkgo and gomega from ignored list.
- Added location with dockerfiles for log scanner app.
> Enable dependabot additional updates.

- development/gcp/cloud-run/create-github-issue/Dockerfile
- development/gcp/cloud-run/gardener-sa-rotate/Dockerfile
- development/gcp/cloud-run/kms-rotate/Dockerfile
- development/gcp/cloud-run/move-gcs-bucket/Dockerfile
- development/gcp/cloud-run/scan-logs-for-secrets/Dockerfile
- development/gcp/cloud-run/search-github-issue/Dockerfile
- development/image-builder/images/buildkit/Dockerfile
- development/image-syncer/external-images.yaml
- development/kyma-ci-force-bot/ciforcebot/Dockerfile
- development/kyma-github-connector/githubWebhookGateway/Dockerfile
- development/kyma-pubsub-connector/pubSubGateway/Dockerfile
- development/markdown-index/Dockerfile
- development/test-log-collector/Dockerfile
- prow/images/automerge-notification-external-plugin/Dockerfile
- prow/images/gardener-rotate/Dockerfile
- prow/images/prow-tools/Dockerfile
- prow/images/test-untrusted-plugin/Dockerfile
- Bump Golang and Alpine images
> Bump Golang and Alpine images

- templates/data/api-gateway-validation.yaml
- templates/data/go-toolkit-validation.yaml
- templates/data/istio-validation.yaml
Some prowjob data files were using localSets with the same values as globalSets. Replaced localsets.
> Using globalSets instead localSets with the same settings.

- prow/jobs/scans/whitesource-periodics.yaml
- templates/data/whitesource-periodics-data.yaml
- enable WhiteSource scans for the `keda-manager` repo
https://github.com/kyma-project/keda-manager/issues/10
> Enable security scans for the `keda-manager` repo

- docs/prow/security_commit_scanner.md
- Security Leaks Scanner documentation
> Security Commit Scanner Documentation

- docs/prow/security_commit_scanner.md
> markdown format issue

- development/gcp/cloud-run/create-github-issue/create-github-issue.go
- development/gcp/cloud-run/slack-message-sender/slack-message-sender.py
- development/github/pkg/templates/secretsleak.go
Kyma security team should be aware of detected secrets leaks. Application will mention security team on slack messages and github issues.
Github issue body template is defined as raw string. This makes it more readable.
> Mention security team on secret leak

- prow/jobs/test-infra/terraform-executor.yaml
- templates/data/test-infra/terraform-executor.yaml
Terraform executor build image prowjobs are required.
> Require to build tf executor.

- prow/jobs/test-infra/terraform-executor.yaml
- templates/data/test-infra/terraform-executor.yaml
Added slash at the end of path.
> Fixed run if changed to run on changes any file in a path.

- prow/images/terraform/Dockerfile
This will be upgraded by dependabot.
> Change to trigger build. 

- prow/jobs/kyma/components/function-runtimes/function-runtimes-generic.yaml
- templates/data/generic_component_data.yaml
- add pre and post submit job definitions for new serverless runtime - nodejs18
https://github.com/kyma-project/kyma/issues/16765
https://github.com/kyma-project/kyma/pull/16768
> Add nodejs 18 runtime jobs

- prow/cluster/resources/external-secrets/external_secrets_trusted.yaml
> Add Signify prod secret

- prow/jobs/control-plane/components/kyma-environment-broker/kyma-environment-broker-build.yaml
- templates/data/control-plane-build.yaml
Definition for cronJob retriggering deprovision of not completely deprovisioned instances.
- post and pull jobs for deprovision retriever job
> Initial setup for deprovision retrigger

- prow/jobs/busola/busola-web/web-deployment-check.yaml
- templates/data/busola-web-deployment-check-data.yaml
- adjust `run_if_change` to new file organisation.
> change run if change for deployment check - busola

- prow/config.yaml
- templates/templates/prow-config.yaml
- use squash instead of rebase and merge
> Use Squash in warden

- prow/jobs/scans/whitesource-periodics.yaml
- templates/data/whitesource-periodics-data.yaml
> Switch warden's ws scans to the main branch

- prow/jobs/api-gateway/api-gateway-validation.yaml
- prow/jobs/istio/istio-validation.yaml
- templates/data/api-gateway-validation.yaml
- templates/data/istio-validation.yaml
- Always run pull-istio-test
- Increase CPU for linting jobs as they often have a timeout
> Always run istio test and prevent linting timeout

- development/image-syncer/external-images.yaml
add golang image v1.20.1
[repo](https://hub.docker.com/layers/library/golang/alpine3.17/images/sha256-8e0cab3057642c2e4cbbbc6d02dd5dbcd23eec5fdc5f106bce3a2869abdd2a47?context=explore)
[changelog](https://go.dev/doc/go1.20)
> add golang1.20.1-alpine3.17

- configs/terraform/secrets-leaks-log-scanner/gcs-bucket-mover.tf
- configs/terraform/secrets-leaks-log-scanner/github-issue-creator.tf
- configs/terraform/secrets-leaks-log-scanner/github-issue-finder.tf
- configs/terraform/secrets-leaks-log-scanner/secrets-leak-log-scanner.tf
- configs/terraform/secrets-leaks-log-scanner/slack-message-sender.tf
- prow/jobs/test-infra/run-terraform-config.yaml
- templates/data/test-infra/run-terraform-config.yaml
- Using terraform executor prod images.
- Fixed prowjob service account name.
- Fixed terraform apply arguments.
- Fixed variable name in secret-leak-detector .tf config.
> Use prod images

- prow/cluster/resources/external-secrets/external_secrets_trusted.yaml
- prow/cluster/resources/external-secrets/external_secrets_workloads.yaml
- Adjust `kyma-btp-manager-bot-github-token` secret to the untrusted cluster
> Adjust kyma-btp-manager-bot-github-token secret for untrusted

- development/gcp/workflows/secrets-leak-detector.yaml
Using condition nested steps for better flow representation.
Added step and condition to check if event is for finished prowjob. Workflow will not call services for not finished prowjobs.
Refactored workflow code to better represent flow and decision steps.
> Run workflow on finished prowjob events.

- prow/cluster/resources/external-secrets/external_secrets_trusted.yaml
We need to provide an ADO token to allow pipelines to interact with internal scanners. This PR adds that ability to trusted workloads.
- Add secret that allow access to ADO SA token on trusted workflows
See also #6585
> Add azure token to trusted workload

- prow/jobs/test-infra/presubmit-scanner.yaml
- templates/data/presubmit_scanner_data.yaml
- Gitleaks version is set to a specific tag
> Set specific Gitleaks version

- prow/jobs/kyma-project/warden/integration-test.yaml
> warden-integration-tests: add log fetching

- prow/jobs/test-infra/run-terraform-config.yaml
- templates/data/test-infra/run-terraform-config.yaml
> Fixed tfcmt flags, again.

- prow/jobs/test-infra/secret-leaks-log-scanner.yaml
- prow/jobs/test-infra/terraform-executor.yaml
- templates/data/test-infra/secret-leaks-log-scanner.yaml
- templates/data/test-infra/terraform-executor.yaml
Secret log scanner and tf executor postsubmit builds were running on all branches. This was trigerring post builds on push to dependabot branches and was reported on prs.
> Run postsubmit builds on main branch only.

- development/image-syncer/external-images.yaml
- https://github.com/kyma-project/kyma/issues/16812
> Add Istio 1.17.0 to image syncer

- prow/jobs/kyma/components/telemetry-operator/telemetry-manager-generic.yaml
- templates/data/generic_component_data.yaml
- Signify secret preset configured
> Add Signify secret presets to the post telemetry build job

- development/secrets-rotator/cloud-run/rotate-service-account/README.md
Updated documentation to reflect migration to cloud-run service and adding of terraform config files.
> RotateServiceAccount documentation update.

- prow/config.yaml
- templates/templates/prow-config.yaml
- Add tide squash merge config for new telemetry-manager repository
https://github.com/kyma-project/kyma/issues/16745
> Use tide squash for telemetry-manager repository

- prow/jobs/kyma/kyma-integration-gardener-eventing.yaml
- templates/data/kyma-integration-gardener-data.yaml
- Updated `runIfChanged` for eventing `pre-main-kyma-gardener-gcp-subscription-upgrade` job to the same value as in `pre-main-kyma-gardener-gcp-eventing-upgrade`
> Update `runIfChanged` for eventing `pre-main-kyma-gardener-gcp-subscription-upgrade` job

- prow/jobs/kyma/components/kyma-components-static-checks.yaml
- templates/data/go-toolkit-validation.yaml
- Trigger lint and unit test job when go.mod or go.sum changed
https://github.com/kyma-project/kyma/issues/16745
> Trigger linter and unit test job when go.mod  or go.sum changed

- prow/labels.yaml
The telemetry module will be the only module in regards to observability in future and will cover logging, metrics and traces aspects. It often is not easy to differ between that 3 aspects as there is a lot in common nowadays with the telemetry module.
That why we should introduce a new label for all the new functionality and use the old labels to fade-out the old components.
- added new label for telemetry module
- ...
- ...
> add label for telemetry module

- prow/jobs/test-infra/secrets-rotator.yaml
- templates/data/test-infra/secrets-rotator.yaml
- Fixed terraform commands.
- Added branch definition to run prowjobs on. Preventing running postsubmits on dependabot branches push.
- Added missing volume with secret for signing on postsubmit with prod signify.
> Added prod signify secret for postsubmit builds.

- prow/jobs/api-gateway/api-gateway-validation.yaml
- prow/jobs/istio/istio-validation.yaml
- templates/data/api-gateway-validation.yaml
- templates/data/istio-validation.yaml
- Increase cpu request for istio and api-gateway because they often run into the 10 min timeout
> Increase cpu request for lint jobs

- prow/jobs/kyma/components/function-runtimes/function-runtimes-generic.yaml
- templates/data/generic_component_data.yaml
> Revert nodejs18 build jobs

- prow/labels.yaml
- area/automation label should be used to label issues or prs related to automation.
- auto-approved label should be used by automation to indicate prs approved by them.
> Added new labels for automation purposes.

- CODEOWNERS
- Remove users without write access
- Delete entry for archived console repository
- Remove myself from places where I am no longer code owner
> Cleanup of code owners

- configs/terraform/core/apis.tf
- configs/terraform/secrets-leaks-log-scanner/gcs-bucket-mover.tf
- configs/terraform/secrets-leaks-log-scanner/github-issue-creator.tf
- configs/terraform/secrets-leaks-log-scanner/github-issue-finder.tf
- configs/terraform/secrets-leaks-log-scanner/secrets-leak-detector.tf
- configs/terraform/secrets-leaks-log-scanner/secrets-leak-log-scanner.tf
- configs/terraform/secrets-leaks-log-scanner/slack-message-sender.tf
- development/gcp/workflows/secrets-leak-detector.yaml
- Fixed errors in resources and data definitions.
- Aligned service accounts names.
- Defined missing names and descriptions.
- Replaced hardcoded names with data variables.
- Replaced project IAM resource to non-authoritative to add SA not replace members.
- Fixed workflow syntax errors.
- Added dedicated remote state for core module.
- Changed provider for core module.
> Fix tf apply errors

- development/image-builder/README.md
- development/image-builder/main.go
- development/image-builder/main_test.go
- Possibility to pass build args to the image build.
> Extending Build Args Through Configuration

- prow/images/whitesource-scanner/Dockerfile
- Bump Mend agent to the latest version
- remove dep
> Bump Mend agent

- prow/jobs/scans/whitesource-periodics.yaml
- templates/config.yaml
> Bump Mend image

- prow/images/whitesource-scanner/Dockerfile
> Bump Mend base image

- prow/jobs/kyma/kyma-integration-gardener-eventing.yaml
- templates/data/kyma-integration-gardener-data.yaml
- Made the following jobs required:
- `pre-main-kyma-gardener-gcp-eventing-v1alpha2`
- `pre-main-kyma-gardener-gcp-subscription-upgrade`
- https://github.com/kyma-project/kyma/issues/16251
> Made eventing v1alpha2 pre-main jobs required

- development/image-builder/main.go
- new if statement with map initialisation in case env file that envs are populated with is missing.
https://github.com/kyma-project/test-infra/pull/7023#discussion_r1118393206
> Missing Env File Panic

- prow/config.yaml
- templates/templates/prow-config.yaml
- Add mapping secret to prow config for ADO service user token
Resolves #6585
> Add azure-devops-token mapping in prow config

- prow/jobs/api-gateway/api-gateway-validation.yaml
- prow/scripts/cluster-integration/kyma-integration-gardener.sh
- templates/data/api-gateway-validation.yaml
- vpath/pjtester.yaml
- Cluster provisioning scripts for integration tests in api-gateway repo
https://github.com/kyma-project/api-gateway/issues/213
> Api-gateway integration tests from own repo

- prow/jobs/test-infra/secrets-rotator.yaml
- templates/data/test-infra/secrets-rotator.yaml
- Documenttion update should not trigger build of service images. Updated run if changed value to trigger build on changes of Dockerfile and .go files.
> Updated run if changed to not build images on documentation changes.

- prow/scripts/cluster-integration/compass-gke-benchmark.sh
- vpath/pjtester.yaml
> Fix compass benchmark job

- development/secrets-rotator/cloud-run/service-account-keys-cleaner/README.md
- Update documentation to reflect migration to cloud-run and terraform.
> Updated documentation to reflect migration to cloud run

- prow/jobs/modules/internal/serverless-manager.yaml
- templates/data/generic_module_data.yaml
- add serverless manager integration tests
Related https://github.com/kyma-project/serverless-manager/issues/22
> add serverless manager integration tests

- prow/jobs/eventing-tools/eventing-tools-generic.yaml
- run eventing tools jobs if any file in the repo is changed
> change build trigger for eventing tools jobs

- prow/jobs/kyma/components/kyma-components-static-checks.yaml
- templates/data/go-toolkit-validation.yaml
- Increase the CPU/Mem settings for linting and Unit tests as they are flaky.
> Increase resources for telemetry manager jobs

- prow/jobs/eventing-tools/eventing-tools-generic.yaml
- templates/data/eventing-tools-data.yaml
- add latest-tag to final eventing-tools image
> tag eventing-tools as latest

- .golangci.yaml
Many linter prowjobs failing because of timeout.
> Increase linter timeout.

- development/image-syncer/external-images.yaml
- vpath/pjtester.yaml
- Bump postgres to 11.19-alpine3.17 (openssl CVE issues)
> Bump postgres 11.19 alpine3.17

- prow/jobs/modules/external/keda-manager.yaml
- templates/data/generic_module_data.yaml
> Make Keda Pipe non-optional

- CODEOWNERS
- prow/jobs/kyma-project/telemetry-manager/telemetry-manager-integration-test.yaml
- Add telemetry-manager integration test
https://github.com/kyma-project/kyma/issues/16909
> Add telemetry-manager integration test

- prow/jobs/test-infra/secrets-rotator.yaml
- templates/data/test-infra/secrets-rotator.yaml
- Aligned tf paths in prowjobs args with application tf modules structure. TF runs against prod environment only.
- Aligned tf prowjob run_if_changed paths with application tf modules structure. TF prowjobs are running on prod environment and modules directories changes only.
- Added var-file arg to terraform plan and apply commands in prowjobs to load required values.
See #7126
> Align prowjobs running terraform executor with secrets rotator application tf config.

- development/tools/pkg/pjtester/pjtester.go
This fix missing user labels and annotations in prowjob. User provided labels and annotations are defined in prowjob definitions in yaml files.
- Adding labels and annotations read from prowjob definition yaml files to the prowjob k8s resource.
See #7088
> Adding user provided labels and annotations to prowjob specification.

- prow/jobs/test-infra/go-validation.yaml
- templates/data/test-infra/golang-tests.yaml
Another linter timeout. Increased resources.
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_test-infra/7119/pre-main-test-infra-lint/1631369211508953088
> Increase resources for linter. Hit timeoute again.

- prow/jobs/scans/whitesource-periodics.yaml
- templates/data/whitesource-periodics-data.yaml
- Remove module-manager from Whitesource scans
> Remove module-manager scans

- prow/jobs/kyma/kyma-integration-gardener-eventing.yaml
- templates/data/kyma-integration-gardener-data.yaml
- added env variable EVENTING_UPGRADE_JOB to the eventing upgrade job
https://github.com/kyma-project/kyma/issues/15578
> add env variable EVENTING_UPGRADE_JOB to the eventing upgrade job

- prow/jobs/test-infra/secrets-rotator.yaml
- templates/data/test-infra/secrets-rotator.yaml
- Mount gh token to create comments on PR with Terraform apply command output.
> Add preset label to mount gh token.

- prow/jobs/modules/external/keda-manager.yaml
- templates/data/generic_module_data.yaml
- vpath/pjtester.yaml
Align upgrade test with newest CLI changes
[Successful run](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_keda-manager/108/cortey_test_of_prowjob_pre-main-keda-manager-upgrade-main-to-ch/1633418690634452992)
https://github.com/kyma-project/keda-manager/issues/83
> Update Keda Upgrade pipe

- configs/terraform/secrets-leaks-log-scanner/gcs-bucket-mover.tf
- configs/terraform/secrets-leaks-log-scanner/github-issue-creator.tf
- configs/terraform/secrets-leaks-log-scanner/github-issue-finder.tf
- configs/terraform/secrets-leaks-log-scanner/secrets-leak-log-scanner.tf
- configs/terraform/secrets-leaks-log-scanner/slack-message-sender.tf
- Using latest images with all fixes and changes implemented recently.
> Use latest prod images in secret leak detector.

- configs/gencred-config.yaml
- SA token used to connect from prow to tekton is valid for 365 days. This is workaround till we fix reloading credentials by pipeline controller.
> Generate tekton k8s cluster sa token valid for 365 days.

- development/image-builder/main.go
- development/image-builder/main_test.go
PR tag is supposed to replace the default_tag when the tool is running from presubmit job
> image-builder: Change 'PR' tag name to `default_tag`

- prow/jobs/modules/internal/serverless-manager.yaml
- templates/data/generic_module_data.yaml
- vpath/pjtester.yaml
- change the `make ci-k3d-integration-test` to the `make -C hack/local/serverless run-manual  && make -C hack/ci integration-test` for the `pre-main-serverless-manager-verify` job.
https://github.com/kyma-project/serverless-manager/issues/67
https://github.com/kyma-project/serverless-manager/pull/64
> Use the another make target for the verify job

- development/image-syncer/external-images.yaml
image: https://hub.docker.com/layers/library/golang/1.20.2-alpine3.17/images/sha256-4e6bc0eafc261b6c8ba9bd9999b6698e8cefbe21e6d90fbc10c34599d75dc608?context=explore
> Add external image for `golang:v1.20.2-alpine3.17`.

- development/image-syncer/external-images.yaml
- Add istio 1.17.1 images: https://istio.io/latest/news/releases/1.17.x/announcing-1.17.1/
> Add istio 1.17.1 images

- prow/scripts/provision-vm-and-start-kyma-k3d.sh
- vpath/pjtester.yaml
- Remove dots from labels
https://github.com/kyma-project/kyma/issues/17066
> Remove dots

- docs/how-to/how-to-add-custom-secret.md
> Adding information about labels.

- prow/scripts/provision-vm-and-start-kyma-k3d.sh
- vpath/pjtester.yaml
- Remove dots from labels
https://github.com/kyma-project/kyma/issues/17066
> Remove dots from labels

- prow/cluster/resources/external-secrets/external_secrets_trusted.yaml
- prow/config.yaml
- templates/templates/prow-config.yaml
- Add Tunas bot token
/cc @k15r 
> Add Tunas bot token

- prow/jobs/test-infra/prow-periodics.yaml
- templates/data/prow-periodics-data.yaml
- change configuration for autobump periodic job so that it reads the configuration from the eventing tools repository
> move eventing-tools autobump config to eventing-tools repository

- docs/prow/k3d-no-ssh.md
**Please consider that this is more of a guide than official documentation. Informal language in this file is intended**
Added small documentation about usage of K3d and other Docker related workloads inside ProwJob pod
#5442
> Add guide on how to use K3d in a pod

- prow/labels.yaml
It's added by dependabot for terraform provider updates.
> Added terraform label

- prow/scripts/cluster-integration/kyma-integration-k3d-telemetry.sh
- After removing telemetry production profile kyma-project/kyma#17104, there is no need to dry-run the deployment of kyma with production profile in our telemetry test
#kyma-project/kyma#16853
> Remove verification of telemetry production profile

- development/secrets-rotator/terraform/environments/dev/main.tf
- development/secrets-rotator/terraform/environments/dev/terraform.tfvars
- development/secrets-rotator/terraform/environments/dev/variables.tf
- development/secrets-rotator/terraform/environments/prod/main.tf
- development/secrets-rotator/terraform/environments/prod/terraform.tfvars
- development/secrets-rotator/terraform/environments/prod/variables.tf
- development/secrets-rotator/terraform/modules/rotate-service-account/main.tf
- development/secrets-rotator/terraform/modules/rotate-service-account/variables.tf
- development/secrets-rotator/terraform/modules/service-account-keys-cleaner/main.tf
- development/secrets-rotator/terraform/modules/service-account-keys-cleaner/output.tf
- development/secrets-rotator/terraform/modules/service-account-keys-cleaner/provider.tf
- development/secrets-rotator/terraform/modules/service-account-keys-cleaner/variables.tf
- Added module for service account keys cleaner.
- Updated dev environment root module, to install sa keys cleaner module.
- Updated prod environment root module, to install sa keys cleaner module.
> Add tf module for sa keys cleaner

- prow/jobs/test-infra/pjconfigtests.yaml
- prow/jobs/test-infra/pjtester.yaml
- prow/jobs/test-infra/prow-periodics.yaml
- templates/data/pjtester-data.yaml
- templates/data/prow-periodics-data.yaml
- templates/data/test-infra/pjconfigtests.yaml
- Decreased requested cpu and memory for pjtester and pjconfigtest prowjobs. They were requesting 2 cpu and 1,5Gi memory which looks much to more they need.
- Added extreamly simple orphaned disks cleaner. It doesn't report proper return code. This is temporary solution.
> Clean orphaned disks, decrease resource requests.

- prow/jobs/modules/external/keda-manager.yaml
- templates/data/generic_module_data.yaml
Move the two Keda upgrade jobs to postsubmits
Part of https://github.com/kyma-project/serverless-manager/issues/67
> Move Keda Upgrade to Post

- prow/jobs/kyma/kyma-integration.yaml
- templates/data/kyma-integration-data.yaml
- Our existing orphaned disks cleaner was not cleaning all disks because of to restrictive regex matching disks names. Set it to match all disks.
> Adjust disks cleaner regex.

- prow/jobs/governance.yaml
- templates/data/governance-data.yaml
- Fix for [failing governance job](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_test-infra/7286/pre-main-test-infra-governance/1638512761933664256)
https://github.com/kyma-project/test-infra/pull/7286
> Fix test-infra governance jobs

- development/image-syncer/external-images.yaml
- Add Istio 1.16.3 to image repo (for Kyma 2.12.1 security patch)
> Add istio 1.16.3 to image registry

- prow/autobump-config/test-infra-autobump-config.yaml
- templates/templates/test-infra-autobump-config.yaml
- Remove `development/tools/jobs/tester/tester.go` from the config, unblocking the autobumper
> Fix autobumper config

- prow/images/buildpack-golang/Dockerfile
- prow/images/buildpack-golang/Makefile
> Update go version

- prow/config.yaml
- templates/templates/prow-config.yaml
- Use K8s 1.26.1 (preview) for Gardener clusters
https://github.com/kyma-project/test-infra/issues/7190
> Use K8s 1.26.1 for Gardener clusters

- prow/scripts/resources/busola/cluster-busola.yaml
- prow/scripts/resources/busola/cluster-kyma.yaml
- prow/scripts/resources/reconciler/shoot-template.yaml
- prow/scripts/resources/skr-test/shoot-template.yaml
- Upgrade gardenlinux to 934.6.0
https://github.com/kyma-project/test-infra/issues/7190
> Upgrade gardenlinux to 934.6.0

- development/external-plugins/automerge-notification/main.go
- development/external-plugins/test-untrusted/cmd/main.go
- development/gcbuild/main.go
- development/image-builder/main.go
- development/markdown-index/bumper/bumper.go
- development/tools/cmd/dnscleaner/main.go
- development/tools/cmd/rendertemplates/main.go
- development/tools/pkg/gcscleaner/storage/bucket.go
- development/tools/pkg/release/mock.go
- development/tools/pkg/rendertemplates/rendertemplates.go
> Fix linting

- CODEOWNERS
- prow/jobs/eventing-tools/eventing-tools-generic.yaml
- templates/data/eventing-tools-data.yaml
- build only if .go , go.sum, go.mod or Dockerfile changed
- updated codeownership for eventing-tools related jobs/job-data
> change eventing-tools build trigger

- prow/jobs/modules/external/keda-manager.yaml
- templates/data/generic_module_data.yaml
- change make targets to the right one after refactoring ( [here](https://github.com/kyma-project/keda-manager/pull/112) )
https://github.com/kyma-project/keda-manager/issues/110
> Upgrade kyma manager make targets

- docs/prow/prow-k8s-testgrid.md
- Remove the `transfigure` section, as this tool is no longer used.
> remove transfigure paragraph

- prow/scripts/cluster-integration/kyma-serverless-integration-k3d.sh
- prow/scripts/cluster-integration/kyma-serverless-run-test.sh
- prow/scripts/lib/serverless-shared-k3s.sh
- vpath/pjtester.yaml
- move run serverless tests to separate script
https://github.com/kyma-project/serverless-manager/issues/44
> Unify serverless run script

- prow/jobs/kyma/kyma-integration-gardener.yaml
- templates/data/kyma-integration-gardener-data.yaml
- Run API-Gateway Kyma component tests on `recources/istio` changes
> Run API-Gateway kyma component tests on recources/istio changes

- prow/scripts/resources/skr-test/shoot-template.yaml
- Corrected failed tests by disabling privileged containers in shoot templates.
> Disabled Privileged Containers

- prow/jobs/governance.yaml
- prow/scripts/governance.sh
- templates/data/governance-data.yaml
This reverts commit 097eb5bb429dbf31c67b748f57db946c0950efee.
> Revert "Comparing CRD table in MD files (#7201)"

- development/tools/pkg/pjtester/test_artifacts/test-prow-config.yaml
- prow/config.yaml
- templates/templates/prow-config.yaml
> compass manager

- prow/jobs/test-infra/checkconfig.yaml
- prow/jobs/test-infra/pjconfigtests.yaml
- prow/jobs/test-infra/pjtester.yaml
- prow/jobs/test-infra/presubmit-scanner.yaml
- templates/config.yaml
- Add `compass-manager` repo
#7356
> Add `compass-manager` repo

- CODEOWNERS
- Use GH teams for frog ownership
> Change frogs to team

- CODEOWNERS
- prow/jobs/modules/external/keda-manager.yaml
- templates/data/generic_module_data.yaml
- make sure keda module is built also when `.env` file is changed
https://github.com/kyma-project/keda-manager/pull/126
> Include .env in keda module job triggers

- docs/examples/tekton-demo.yaml
- Added updated version of tekton demo prowjob.
See #6798
> Tekton demo prowjob update

- development/gardener-rotate/gardener-kyma-dev-config.yaml
- development/gardener-rotate/gardener-kyma-prow-config.yaml
- prow/jobs/test-infra/gardener-kubeconfig-rotation.yaml
- templates/data/secret-rotation-data.yaml
- Rotate Kyma-dev kubeconfig secret
> Rotate Kyma-dev kubeconfig

- development/tools/pkg/pjtester/test_artifacts/test-prow-config.yaml
- prow/config.yaml
- templates/templates/prow-config.yaml
- We want merges without squashing
> Change merging policy for compass-manager

- tekton/deployments/dashboard_release.yaml
- tekton/deployments/pipelines_release.yaml
- Upgrade tekton dashboard to version 0.34.0.
- Upgrade tekton pipelines to version 0.45.0
See #6798
> Updated dashboard and pipelines releases to newest versions.

- CODEOWNERS
- Cleanup CODEOWNERS from Goat's perspective
- Remove components that no longer exist
> Adjust CODEOWNERS for Goats

- prow/jobs/incubator/reconciler/reconciler.yaml
- templates/data/incubator-buildpack-data.yaml
- vpath/pjtester.yaml
This PR add a dedicate job for reconciler to only run unit test
> add dedicate unit test job for reconciler

- prow/jobs/api-gateway/api-gateway-validation.yaml
- prow/jobs/istio/istio-validation.yaml
- templates/data/api-gateway-validation.yaml
- templates/data/istio-validation.yaml
- vpath/pjtester.yaml
- Adds code coverage guard for Istio on PRs
> Adds code coverage guard for Istio on PRs

- development/image-syncer/external-images.yaml
- Update external Alpine image to 3.17.3
> Update external Alpine image to 3.17.3

- prow/jobs/governance.yaml
- templates/data/governance-data.yaml
- Updated run_if_changed trigger, so the job is called after changes both in md files and crd files
https://github.com/kyma-project/kyma/issues/15663
> CRD comparison prow job trigger update

- prow/jobs/modules/external/keda-manager.yaml
- templates/data/generic_module_data.yaml
Removes a hack related to old CLI requirements.
> Move upgrade test logic to Keda repo

- prow/jobs/governance.yaml
- templates/data/governance-data.yaml
- Fixed typo in run_if_changed parameter, so the job would trigger for CRD file changes
https://github.com/kyma-project/kyma/issues/15663
> Fixing typo in CRD comparison prow job

- development/gcp/pkg/pubsub/client.go
> Removed unused function.

- CODEOWNERS
- This will request bot for review on PRs changing these files and let it approve them without human activity.
Needed for #7017
> Added neighbors-dev-bot as an owner of auto generated documentation files

- prow/jobs/kyma/kyma-integration.yaml
- templates/data/kyma-integration-data.yaml
- Do not remove `persistentcluster`, it requires troubleshooting from Gardener team.
> Update cleaner regexp

- development/image-syncer/external-images.yaml
Update the golang image to  `golang:1.20.3-alpine3.17`
[release notes](https://go.dev/doc/devel/release#go1.20.minor)
> Bump the golang image to `golang:1.20.3-alpine3.17`

- prow/jobs/kyma/kyma-integration.yaml
- templates/data/kyma-integration-data.yaml
- Do not delete "persist" cluster
-
> Do not delete persist cluster

- prow/jobs/kyma/kyma-integration.yaml
- templates/data/kyma-integration-data.yaml
- Fix cluster cleaner
/cc @kasiakepka
> Fix cluster cleaner

- prow/config.yaml
- templates/templates/prow-config.yaml
- Fix for post-rel213-kyma-release-candidate
> Use k8s 1.25 for GCP clusters

- prow/images/kyma-integration/Dockerfile
- Updating always to the newest KCP CLI version in the fast-integration test image.
> Updated Kcp Cli Version

- prow/jobs/kyma/kyma-gardener-cleanup.yaml
- templates/data/kyma-gardener-cleanup-data.yaml
- Do not remove persist cluster, it has to be investigated by Gardener team
> Do not remove persist cluster

- prow/jobs/kyma-project/compass-manager/golang-linter.yaml
- added pipeline for running golangci linter for compass-manager repository
> Pipeline for GolangCI linter in compass-manager repository

- development/image-syncer/external-images.yaml
- prow/jobs/test-infra/image-syncer.yaml
- templates/data/image-syncer-data.yaml
change target repo for all cloned images to new registry
> Update image-syncer target repository

- prow/config.yaml
- templates/templates/prow-config.yaml
Let's try this out
/cc @kasiakepka
> Reduce time to remove ProwJobs in Sinker

- prow/jobs/scans/whitesource-periodics.yaml
- templates/data/whitesource-periodics-data.yaml
- Add BTP manager to Whitesource scans
> Add BTP manager to Whitesource scans

- prow/jobs/api-gateway/api-gateway-build.yaml
- prow/jobs/kyma/releases/kyma-release-214.yaml
- templates/data/api-gateway-build.yaml
- templates/data/kyma-release-data.yaml
- Report failed post-release jobs to the release channel
- Report failed post api-gateway jobs to the Goat's channel
- 
> send notifications to the slack channel

- development/image-syncer/external-images.yaml
Update the image to the new release: https://github.com/nats-io/prometheus-nats-exporter/releases/tag/v0.11.0
> Image bump prometheus-nats-exporter

- prow/scripts/cluster-integration/kyma-busola-long-lasting.sh
> Fix path to busola-e2e-cleaner.yaml

- prow/jobs/control-plane/tests/provisioner-tests/provisioner-tests-build.yaml
- delete the `e2e` from run path
> Fix invalid catalog path for Provisioner test

- prow/config.yaml
- templates/templates/prow-config.yaml
- set KEB token url as env for fast integration tests
> Configure token url for fast int tests

- sec-scanner-config.yaml
Added security scanner config for whitesource and checkmarx.
> Add security scanner config file

- prow/jobs/kyma/kyma-integration.yaml
- templates/data/kyma-integration-data.yaml
- Make pre-main-kyma-api-gateway-integration-k3d required
> Make pre-main-kyma-api-gateway-integration-k3d required

- CODEOWNERS
Follow up to [this PR](https://github.com/kyma-project/test-infra/pull/7544)
Update code owners of the eventing-webhook buildjobs
[This](https://github.com/orgs/kyma-project/projects/17/views/7?pane=issue&itemId=24763955)
> Update codeowners of eventing build jobs

- prow/labels.yaml
/kind cleanup
/area ci
reorganize labels.yaml for better visibility
move test-infra labels to repo-specific sync options
add kind/chore label for bumps and other chore tasks
> tidy-up labels.yaml

- prow/jobs/kyma-dashboard/kyma-dashboard-dev.yaml
- prow/jobs/kyma-dashboard/kyma-dashboard-prod.yaml
- prow/jobs/kyma-dashboard/kyma-dashboard-stage.yaml
- templates/data/generic_component_kyma_dashboard_data.yaml
- adjust kyma-dashboard to use artifact registry instead of GCR
/area ci
/kind feature
> adjust kyma-dashboard to ar

- prow/scripts/cluster-integration/kyma-dashboard-smoke-test.sh
- prow/scripts/cluster-integration/kyma-dashboard-test.sh
- ...
- ...
- ...
/area ci
/kind bug
> fix image for tests

- configs/kaniko-build-config.yaml
> disable push to eu.gcr.io in image-builder

- .github/dependabot.yml
- templates/data/test-infra/dependabot-config-data.yaml
- Add kind/cleanup label for dependabot pull requests
> Add kind label for dependabot pull requests

- .github/dependabot.yml
- templates/data/test-infra/dependabot-config-data.yaml
- Add kind/chore label for dependabot pull requests
> Add kind label for dependabot

- prow/jobs/test-infra/prow-periodics.yaml
- templates/data/prow-periodics-data.yaml
/area ci
/kind feature
Added labels override for kyma-bot autobumps
> add kind/chore and area/ labels to autobump config

- prow/cluster/components/gcsweb-kyma-prow_managedcertificate.yaml
- prow/cluster/components/monitoring/monitoring-kyma-prow_managedcertificate.yaml
- prow/cluster/components/status-kyma-prow_managedcertificate.yaml
- prow/cluster/resources/probot-stale/templates/managedcert.yaml
- prow/staging/cluster/kyma-prow_managedcertificate.yaml
- prow/staging/cluster/monitoring/monitoring-kyma-prow_managedcertificate.yaml
> migrate to ManagedCertificate v1 version

- prow/jobs/third-party-images/third-party-images.yaml
- templates/data/third-party-images-data.yaml
- Add image build job for alertmanager
- Add image build job for configmap-reload
https://github.com/kyma-project/third-party-images/pull/333
https://github.com/kyma-project/third-party-images/pull/336
https://github.com/kyma-project/kyma/issues/17378
> Add image build jobs

- development/image-syncer/external-images.yaml
- Bump prometheus image to latest 2.43.1
https://github.com/kyma-project/kyma/issues/17378
> Bump prometheus image to latest 2.43.1

- prow/plugins.yaml
- add `chore` label to the help message
/cc @Ressetkk
> Update kind label help

- development/image-syncer/external-images.yaml
- adds golang 1.20.4-alpine3.17 image
> Golang 1.20.4 alpine3.17

- prow/scripts/provision-vm-and-start-kyma-dashboard-smoke-test.sh
- prow/scripts/provision-vm-and-start-kyma-dashboard-test.sh
> export pull number

- prow/jobs/nats-manager/nats-manager-generic.yaml
- templates/data/nats-manager-data.yaml
- Changed nats-manager unit-tests target
> Changed nats-manager unit-tests target

- images/README.md
- images/buildpack-go/Dockerfile
- images/buildpack-go/README.md
- images/e2e-dind-k3d/Dockerfile
- images/e2e-dind-k3d/README.md
- images/e2e-dind-k3d/init.sh
- images/e2e-garden/Dockerfile
- images/e2e-gcloud/Dockerfile
- prow/images/README.md
Initial configuration for new test-infra images
* Alpine-based
* rootless (minus k3d image)
* contain only required binaries
* have least number of layers
#6793
> Initial rework of images

- .github/dependabot.yml
- templates/data/test-infra/dependabot-config-data.yaml
- Add missing kind labels to dependabot
> Add missing labels to dependabot

- development/image-syncer/README.md
- improves the multi-platform part of the documentation
- ...
- ...
> Improves the multi-platform part of the image-syncer documentation

- CODEOWNERS
Prow group owns docs/index.md file in case it is updated in pull request which is not allowed to be automatically approved. In such case a human group member must review pull request. Example scenario #7618
> Prow group owns docs/index.md file.

- prow/scripts/resources/reconciler/shoot-template.yaml
- prow/scripts/resources/skr-test/shoot-template.yaml
- Remove basic auth field for gardener
/kid chore
/area ci
> Remove basic auth field for gardener

- prow/autobump-config/test-infra-autobump-config.yaml
- prow/jobs/cli/cli-integration.yaml
- prow/jobs/control-plane/components/kubeconfig-service/kubeconfig-service-generic.yaml
- prow/jobs/control-plane/components/kyma-environment-broker/kyma-environment-broker-generic.yaml
- prow/jobs/control-plane/components/kyma-metrics-collector/kyma-metrics-collector-generic.yaml
- prow/jobs/control-plane/components/provisioner/provisioner-generic.yaml
- prow/jobs/control-plane/components/schema-migrator/schema-migrator-kcp-generic.yaml
- prow/jobs/control-plane/tests/e2e/provisioning/provisioning-test-generic.yaml
- prow/jobs/control-plane/tests/provisioner-tests/provisioner-tests-generic.yaml
- prow/jobs/kyma/kyma-artifacts.yaml
- prow/jobs/kyma/releases/kyma-release-215.yaml
- prow/jobs/kyma/tests/fast-integration/fast-integration-image-generic.yaml
- prow/jobs/scans/whitesource-periodics.yaml
- templates/config.yaml
> Prepare for Kyma 2.14

- prow/jobs/kyma-project/warden/integration-test.yaml
- Fix Warden limits
/cc @Ressetkk 
/kind bug
/area ci
> Fix Warden limits

- prow/jobs/kyma/kyma-integration-gardener-eventing.yaml
- templates/data/kyma-integration-gardener-data.yaml
Trigger Eventing upgrade job when Eventing CRDs change
> Trigger Eventing upgrade job when Eventing CRDs change

- prow/scripts/cluster-integration/kyma-serverless-metrics-nightly.sh
- prow/scripts/cluster-integration/kyma-serverless-run-test.sh
- vpath/pjtester.yaml
- run tests as binary not as helm chart
https://github.com/kyma-project/test-infra/issues/7684
> Migrate test runner for serverless metrics

- development/image-syncer/external-images.yaml
- Copy keda images to europe-docker.pkg.dev/kyma-project/prod
> Sync keda images into europe-docker.pkg.dev/kyma-project/prod

- prow/jobs/telemetry-manager/telemetry-manager-generic.yaml
- templates/data/telemetry-manager-data.yaml
- `config.yaml` file is removed: [kyma-project/telemetry-maanger#174](https://github.com/kyma-project/telemetry-manager/pull/174), so we should remove it from `run_if_changed` configuration in `pull-telemetry-manager-verify-module` job
> Update pull-telemetry-manager-verify-module job

- prow/jobs/api-gateway/api-gateway-build.yaml
- prow/jobs/api-gateway/api-gateway-release.yaml
- prow/jobs/api-gateway/api-gateway-validation.yaml
- prow/jobs/incubator/reconciler/reconciler.yaml
- prow/jobs/istio/istio-validation.yaml
- prow/jobs/kyma/kyma-integration-gardener.yaml
- prow/jobs/kyma/kyma-integration.yaml
- prow/jobs/modules/internal/istio-manager.yaml
- prow/jobs/third-party-images/third-party-images.yaml
- templates/data/api-gateway-build.yaml
- templates/data/api-gateway-release.yaml
- templates/data/api-gateway-validation.yaml
- templates/data/incubator-buildpack-data.yaml
- templates/data/istio-module-data.yaml
- templates/data/istio-validation.yaml
- templates/data/kyma-integration-data.yaml
- templates/data/kyma-integration-gardener-data.yaml
- templates/data/third-party-images-data.yaml
- Adjust goat's prow integration job names based on the IaaS
- Add description and ownership reference for goat's prow jobs
https://github.com/kyma-project/test-infra/issues/7690
> Goats prow jobs update: names, description and owner

- prow/jobs/modules/external/keda-manager.yaml
- templates/data/generic_module_data.yaml
Job related to Keda automated release process.
https://github.com/kyma-project/keda-manager/issues/129
> Keda Release job

- prow/jobs/kyma/components/kyma-components-static-checks.yaml
- templates/data/go-toolkit-validation.yaml
- mark job  controller-unit-test as required
> Mark job  controller-unit-test as required

- prow/jobs/modules/external/keda-manager.yaml
- templates/data/generic_module_data.yaml
Swap env used for Keda Release
https://github.com/kyma-project/keda-manager/issues/129
> Fix a typo in variable in keda release pipeline

- prow/jobs/kyma-project/telemetry-manager/telemetry-manager-e2e-test.yaml
To mitigate flakiness where no OTLP data was received in backend.
- Increase memory to 4 GB
- Requests 2 CPUs
> Increase resources for telemetry-manager e2e-tests

- development/image-syncer/external-images.yaml
- We are using nginx in our tests so have it also synced to our docker registry to avoid rate limiting from docker and causing unnecessary flakiness in tests
https://github.com/kyma-project/kyma/issues/17157
> have nginx in kyma docker registry

- prow/jobs/test-infra/images.yaml
- templates/data/prowjob-images-data.yaml
> Fix images.yaml

- prow/jobs/test-infra/images.yaml
- templates/data/prowjob-images-data.yaml
> Add missing secret to signify

- prow/jobs/kyma/components/kyma-components-static-checks.yaml
- prow/jobs/kyma/kyma-integration.yaml
- templates/data/go-toolkit-validation.yaml
- templates/data/kyma-integration-data.yaml
- .added missing owner annotation for few jobs
- ...
- ...
> added more ownership annotations

- development/image-syncer/external-images.yaml
- postgres bumped to 11.20-alpine3.18
> bump postgres image

- prow/jobs/kyma/kyma-gardener-cleanup.yaml
- prow/jobs/kyma/kyma-integration.yaml
- prow/jobs/kyma/releases/kyma-release-213.yaml
- prow/jobs/scans/whitesource-periodics.yaml
- prow/jobs/test-infra/checkconfig.yaml
- prow/jobs/test-infra/pjconfigtests.yaml
- prow/jobs/test-infra/pjtester.yaml
- prow/jobs/test-infra/presubmit-scanner.yaml
- prow/jobs/test-infra/prow-periodics.yaml
- prow/jobs/test-infra/test-infra-trusted-jobs.yaml
- prow/jobs/test-infra/triage-jobs.yaml
- prow/staging/jobs/test-infra-jobs.yaml
- templates/data/checkconfig.yaml
- templates/data/kyma-gardener-cleanup-data.yaml
- templates/data/kyma-integration-data.yaml
- templates/data/presubmit_scanner_data.yaml
- templates/data/prow-periodics-data.yaml
- templates/data/test-infra/pjconfigtests.yaml
- templates/data/test-infra/pjtester-data.yaml
- templates/data/whitesource-periodics-data.yaml
Added prowjobs annotations.
/kind chore
/area ci
> Set annotations

- prow/jobs/control-plane/components/provisioner/provisioner-build.yaml
- prow/jobs/control-plane/components/provisioner/provisioner-generic.yaml
- prow/jobs/control-plane/tests/provisioner-tests/provisioner-tests-generic.yaml
- prow/jobs/kyma-project/compass-manager/build.yaml
- prow/jobs/kyma-project/compass-manager/compass-manager-tests.yaml
- prow/jobs/kyma-project/compass-manager/golang-linter.yaml
- prow/jobs/kyma-project/compass-manager/static-checks.yaml
- prow/jobs/kyma/common/common.yaml
- prow/jobs/kyma/components/central-application-connectivity-validator/central-application-connectivity-validator-generic.yaml
- prow/jobs/kyma/components/central-application-gateway/central-application-gateway-generic.yaml
- prow/jobs/kyma/components/compass-runtime-agent/compass-runtime-agent-generic.yaml
- prow/jobs/kyma/components/compass-runtime-agent/compass-runtime-agent-tests.yaml
- prow/jobs/kyma/components/kyma-components-static-checks.yaml
- prow/jobs/kyma/kyma-integration.yaml
- prow/jobs/kyma/tests/application-connector-component-tests/application-connector-component-tests-generic.yaml
- templates/data/control-plane-build.yaml
- templates/data/generic_component_data.yaml
- templates/data/go-toolkit-validation.yaml
- templates/data/kyma-integration-data.yaml
- templates/data/kyma-tools-data.yaml
Adds metadata as it will be required when https://github.com/kyma-project/test-infra/issues/5585 will be done. 
- adds metadata to framefrogs' team prow jobs
- ...
- ...
/kind cleanup
/area application-connector
> Add framefrog team prow jobs metadata

- development/pkg/extractimageurls/prowjob.go
- development/pkg/extractimageurls/prowjob_test.go
- Skip jobs without spec definition (eg. tekton pipeline runs)
- Add unit test case
> Fix image urls extractions from prowjobs without spec

- prow/scripts/cluster-integration/kyma-serverless-integration-k3d.sh
- remove profile during instalation of serverless
> Remove profile for serverless tests

- development/tools/pkg/pjtester/pjtester.go
- go.mod
- go.sum
- Bump yaml dependency to supported one
- replace `github.com/go-yaml/yaml` with `gopkg.in/yaml.v2`
> Bump yaml dependency

- opa/terraform/modules/gatekeeper/main.tf
- make constraints depend on constraint templates
> Fix opa gatekeeper TF dependency

- development/image-detector/README.md
- development/image-detector/main.go
- prow/jobs/test-infra/prow-periodics.yaml
- templates/config.yaml
- Update documentation to match newly added flags for image-detector
- Fix flag description
- Bump image detector image for newest version supporting last changes
> Update documentation and bump image for image detector

- prow/jobs/test-infra/secret-leaks-log-scanner.yaml
- prow/jobs/test-infra/secrets-rotator.yaml
- prow/jobs/test-infra/terraform.yaml
- templates/data/test-infra/secret-leaks-log-scanner.yaml
- templates/data/test-infra/secrets-rotator.yaml
- Set max concurrency to 1 for pull-plan-prod-terraform job
> Set max concurrency to 1 for terraform job

- prow/config.yaml
- prow/jobs/eventing-auth-manager/eam-integration-test.yaml
Run Eventing Auth Manager Integration Tests in k3d cluster. So far not a real cluster is used. 
issue: https://github.com/kyma-project/eventing-auth-manager/issues/20
> Run Eventing Auth Manager Integration Tests in k3d clsuter

- development/image-syncer/external-images.yaml
bump to golang:1.20.5-alpine3.18
> bump golang image

- prow/jobs/btp-manager/btp-manager-build.yaml
- prow/jobs/control-plane/components/kyma-environment-broker/kyma-environment-broker-build.yaml
- prow/jobs/control-plane/components/kyma-environment-broker/kyma-environment-broker-generic.yaml
- prow/jobs/control-plane/components/schema-migrator/schema-migrator-kcp-generic.yaml
- prow/jobs/control-plane/tests/e2e/provisioning/e2e-provisioning-test-build.yaml
- prow/jobs/control-plane/tests/e2e/provisioning/provisioning-test-generic.yaml
- prow/jobs/slack-bot/slack-bot-build.yaml
- templates/data/btp-manager-build.yaml
- templates/data/control-plane-build.yaml
- templates/data/slack-bot/slack-bot-build.yaml
- Add description and owner to gophers owned jobs
- Add missing description and owner to framefrogs keb-subscription-cleanup-job-build
#5585
> Add gophers prow jobs metadata

- prow/jobs/test-infra/secret-leaks-log-scanner.yaml
- prow/jobs/test-infra/secrets-rotator.yaml
- templates/data/test-infra/secret-leaks-log-scanner.yaml
- templates/data/test-infra/secrets-rotator.yaml
Using terraform-executor sa. This is the sa used in our IAC config.
> Using terraform-executor sa. This is the sa used in our IAC config.

- images/e2e-dind-k3d/Dockerfile
- images/e2e-dind-k3d/init.sh
/area ci
/kind bug
Change goarch for future multiplatform build
Added small wait step to wait for Docker daemon to be up and ready
> Fix race condition in init script

- prow/jobs/istio/istio-integration.yaml
- vpath/pjtester.yaml
- Run Istio installation with evaluation cluster
- https://github.com/kyma-project/istio/issues/110
> Add job for running istio installation with evalution profile

- prow/jobs/scans/whitesource-periodics.yaml
- templates/data/whitesource-periodics-data.yaml
- Fix Keda manager Whitesource excludes
- ...
- ...
> Fix Keda manager Whitesource excludes

- development/image-syncer/external-images.yaml
> Add alpine 1.17.4

- prow/jobs/api-gateway/api-gateway-release.yaml
- templates/data/api-gateway-release.yaml
Always run all jobs during release.
> Don't skip api-gateway release jobs

- prow/jobs/test-infra/prow-periodics.yaml
- templates/data/prow-periodics-data.yaml
- Fix image detector job args
- #7807
- 
/cc @KacperMalachowski 
/area ci
/kind chore
> Fix image detector job

- development/image-detector/main.go
- Change variable for github token from inavlid InRepoCOnfig to valid GithubTokenPath
> Fix github token path variable assignment in image detector

- prow/jobs/modules/external/keda-manager.yaml
- templates/data/generic_module_data.yaml
Include
- `keda.yaml` in build triggers
- `docs` folder 
in keda module build triggers
> Include keda manifest file in keda module build triggers

- prow/jobs/kyma-project/telemetry-manager/telemetry-manager-upgrade-test.yaml
- vpath/pjtester.yaml
- Add pull-telemetry-manager-upgrade-test job
kyma-project/telemetry-manager#213
> Add pull-telemetry-manager-upgrade-test job

- prow/scripts/cluster-integration/kyma-serverless-benchmarks-nightly.sh
- remove nodej14 mentions
- ...
- ...
> Remove nodejs 14 mentions

- prow/jobs/kyma/components/kyma-components-static-checks.yaml
- templates/data/go-toolkit-validation.yaml
- run telemetry-manager unit tests when changing Makefile
> run unit-tests when changing Makefile

- prow/jobs/test-infra/prow-periodics.yaml
- templates/config.yaml
- templates/data/prow-periodics-data.yaml
- Add prowjob running at 8am every day
- Bump image-detector to newest version
> Bump security scanner config periodically (daily)

- prow/jobs/control-plane/control-plane-reconciler-integration.yaml
- prow/jobs/control-plane/control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener.yaml
- prow/jobs/incubator/reconciler/reconciler.yaml
- templates/data/control-plane-integration-data.yaml
- templates/data/incubator-buildpack-data.yaml
- Fix privileged mode
/kind chore
/area security
- #7904
> Fix privileged mode in reconciler jobs

- prow/jobs/istio/istio-integration.yaml
- Change image for post istio integration test to: `europe-docker.pkg.dev/kyma-project/prod/testimages/e2e-dind-k3d`
https://github.com/kyma-project/test-infra/issues/7903
> Change image for post istio integration test

- prow/jobs/modules/internal/istio-manager.yaml
- templates/config.yaml
- templates/data/istio-module-data.yaml
- Add extra refs to Istio nightly job
> Add extra refs to istio nightly

- prow/jobs/test-infra/prow-plugins.yaml
- templates/data/prow-plugins-data.yaml
- add privileged mode
/kind chore
/area tests
> Fix post-test-infra-test-untrusted-prow-plugin

- prow/jobs/istio/istio-validation.yaml
- prow/jobs/modules/internal/istio-manager.yaml
- templates/data/istio-module-data.yaml
- templates/data/istio-validation.yaml
- Skip sec scanner config for relevant Istio jobs
- https://github.com/kyma-project/istio/issues/186
> Add skip for sec-scanner-config for Istio jobs

- opa/gatekeeper/constraint-templates/k8sAllowedImages.yaml
Fixed rego builtin function call.
> Fixed rego function name.

- prow/jobs/test-infra/prow-periodics.yaml
- templates/config.yaml
- Update image-detetcor image tag
> Bump Image Detector

- development/image-detector/Dockerfile
- Add git to image-detector image
/area tests
/kind bug
/cc @KacperMalachowski
> Add git to image-detector image

- opa/gatekeeper/constraint-templates/k8sAllowedImages.yaml
Fix parameters order in rego built in function call.
> Fixed params order.

- prow/cluster/resources/gatekeeper-constraints/workloads/allowPrivilegeEscalation.yaml
- prow/cluster/resources/gatekeeper-constraints/workloads/seccomp.yaml
- sync privileged mode image excludes between constraints
/area security
/kind chore
/cc @dekiel
> Adjust privileged mode image excludes

- prow/jobs/istio/istio-validation.yaml
- prow/jobs/modules/internal/istio-manager.yaml
- templates/data/istio-module-data.yaml
- templates/data/istio-validation.yaml
- Fix skip for sec-scanners-config to work as expected
- https://github.com/kyma-project/istio/issues/186
> Fix Istio skip for sec-scanner-config

- prow/image-detector/test-infra-sec-config-autobump-config.yaml
- add kind and area labels via bumper config
> Add labels to security scanner autobump PR

- prow/jobs/kyma-dashboard/kyma-dashboard-smoke-test-prod.yaml
- prow/jobs/kyma-dashboard/kyma-dashboard-smoke-test-stage.yaml
- prow/jobs/kyma-dashboard/kyma-dashboard-test.yaml
- templates/data/kyma-dashboard-smoke-test-prod.yaml
- templates/data/kyma-dashboard-smoke-test-stage.yaml
- templates/data/kyma-dashboard-test.yaml
> Make kyma-dashboard tests optional

- prow/scripts/cluster-integration/helpers/reconciler.sh
- prow/scripts/cluster-integration/kyma-busola-long-lasting.sh
- prow/scripts/provision-vm-and-start-busola-docker.sh
- prow/scripts/provision-vm-and-start-busola-k3s.sh
- prow/scripts/provision-vm-and-start-busola-lighthouse.sh
- prow/scripts/provision-vm-and-start-kyma-dashboard-smoke-test.sh
- prow/scripts/provision-vm-and-start-kyma-dashboard-test.sh
- Fix gardener kubeconfig generation
- #7938
/kind bug
/area tests
> Fix gardener kubeconfig generation

- prow/jobs/test-infra/prow-periodics.yaml
- templates/config.yaml
> Bump markdown-index and image-detector

- development/github/pkg/bumper/bumper.go
Adding yaml tags to options allow us to use both sigs.k8s.io/yaml and gopkg.in/yaml.v3 packages to parse yaml files.
- Add yaml tag to bumper Options struct
> Add yaml tag to bumper Options struct

- prow/scripts/cluster-integration/kyma-busola-long-lasting.sh
- Fix kubeconfig access in Busola nightly job
- #7938
/kind bug
/area security
> Fix Busola nightly job

- prow/scripts/cluster-integration/helpers/reconciler.sh
- prow/scripts/cluster-integration/kyma-busola-long-lasting.sh
- prow/scripts/provision-vm-and-start-busola-docker.sh
- prow/scripts/provision-vm-and-start-busola-k3s.sh
- prow/scripts/provision-vm-and-start-busola-lighthouse.sh
- prow/scripts/provision-vm-and-start-kyma-dashboard-smoke-test.sh
- prow/scripts/provision-vm-and-start-kyma-dashboard-test.sh
- we should create resource
- #7938
> Fix gardener kubeconfig

- prow/labels.yaml
- consolidate area-labels from all kyma-project repositories
- cleanup label list
> update label list

- prow/autobump-config/test-infra-autobump-config.yaml
- prow/jobs/control-plane/components/kubeconfig-service/kubeconfig-service-generic.yaml
- prow/jobs/control-plane/components/kyma-metrics-collector/kyma-metrics-collector-generic.yaml
- prow/jobs/kyma/kyma-artifacts.yaml
- prow/jobs/kyma/releases/kyma-release-217.yaml
- prow/jobs/kyma/tests/fast-integration/fast-integration-image-generic.yaml
- prow/jobs/scans/whitesource-periodics.yaml
- templates/config.yaml
- Update Kyma nextRelease to 2.17
> Update Kyma nextRelease to 2.17

- prow/jobs/test-infra/image-detector.yaml
- templates/data/test-infra/image-detector.yaml
development/github contains autobumper implementation
- Add development/github to run_if_changed for image detector
> Run postsubmit for image detector on github package change

- prow/jobs/istio/istio-validation.yaml
- templates/data/istio-validation.yaml
- Remove Istio lint job, because we run it now in GitHub Actions. This is probably more reliable due to dependency caching.
> Remove istio lint

- prow/jobs/test-infra/prow-periodics.yaml
- templates/config.yaml
It resolved failing autobump job
- Bump image-detector tag
> Bump image-detector tag

- prow/config.yaml
- Use squash method when merging PRs
> Use squash in serverless manager

- images/buildpack-go/Dockerfile
- images/e2e-dind-k3d/Dockerfile
- images/e2e-dind-nodejs/Dockerfile
- images/e2e-gcloud/Dockerfile
/kind chore
/area ci
Usual manual updates, and check if build script is working as expected...
> Update image dependencies

- configs/terraform/environments/prod/opa-gatekeeper-variables.tf
- configs/terraform/environments/prod/opa-gatekeeper.tf
- configs/terraform/environments/prod/output.tf
- configs/terraform/environments/prod/provider.tf
- configs/terraform/environments/prod/variables.tf
- sec-scanners-config.yaml
> Remove tekton v2

- images/e2e-dind-k3d/init.sh
- images/e2e-dind-nodejs/init.sh
/kind feature
/area ci
Small improvement to wait for Docker daemon to be up based on the response from the daemon.
> Add conditional wait to docker daemon to be up.

- prow/jobs/istio/istio-manager.yaml
- templates/data/istio-module-data.yaml
- Use e2e-gcloud image, because we have a dependency on gcloud and Helm
> Fix istio nightly performance job

- prow/config.yaml
- don't protect kyma-environment-broker repo
/kind chore
/area security
> Fix branch protection for kyma-environment-broker

- images/e2e-dind-nodejs/Dockerfile
- Add `jq` to `e2e-dind-nodejs` image
> add jq to dind-node image

- prow/autobump-config/test-infra-autobump-config.yaml
- templates/templates/test-infra-autobump-config.yaml
> Add autobump for new testimages

- prow/cluster/resources/external-secrets/external_secrets_untrusted.yaml
Requested by @VOID404
/area ci
/kind chore
> Add compass-director-secret

- prow/config.yaml
/area ci
/kind chore
/cc @halamix2 
FYI @VOID404
> Add preset-compass-director-secret preset

- prow/cluster/resources/gatekeeper-constraints/workloads/allowPrivilegeEscalation.yaml
- prow/cluster/resources/gatekeeper-constraints/workloads/privilegedContainers.yaml
- prow/cluster/resources/gatekeeper-constraints/workloads/seccomp.yaml
- Add e2e images to allowed list for privileged mode
/kind chore
/area security
/cc @dekiel
> Add e2e images to allowed list for privileged mode

- development/image-syncer/external-images.yaml
- add nats-box image to internal image registry to have it signed
> add nats-box image to internal registry

- development/image-syncer/external-images.yaml
- Add fluentd image to the external image repo list
https://github.com/kyma-project/telemetry-manager/issues/237
> fluentd image added

- prow/config.yaml
- prow/image-detector/inrepo-config.yaml
- prow/jobs/test-infra/checkconfig.yaml
- prow/jobs/test-infra/pjconfigtests.yaml
- prow/jobs/test-infra/pjtester.yaml
- prow/jobs/test-infra/presubmit-scanner.yaml
- templates/config.yaml
- Add kyma-environment-broker repo
https://github.com/kyma-project/kyma-environment-broker/issues/3
> Add KEB repo

- images/e2e-dind-k3d/init.sh
- images/e2e-dind-nodejs/init.sh
/area ci
/kind feature
/cc @halamix2
> Cleanup k3d and docker after run

- prow/jobs/istio/istio-manager.yaml
- templates/data/istio-module-data.yaml
- Use `unsigned` module registry
- Use prod image
> Fix registry path for istio module

- prow/scripts/cluster-integration/kyma-integration-k3d-telemetry-components.yaml
- Remove logging component from telemetry integration job
https://github.com/kyma-project/kyma/issues/17637
> Remove logging component from telemetry integration job

- prow/jobs/istio/istio-integration.yaml
- Create k3s with port mappings for the new test. Also disable Traefik to not interfere
- https://github.com/kyma-project/istio/issues/193
> Update k3s config for istio integration tests

- prow/config.yaml
> Change prowjob age

- prow/jobs/kyma-dashboard/kyma-dashboard-smoke-test-prod.yaml
- prow/jobs/kyma-dashboard/kyma-dashboard-smoke-test-stage.yaml
- fix `run_if_changed`
/area ci
/kind bug
> fix run if change for smoke tests in kyma-dashboard

- prow/jobs/kyma/skr-integration.yaml
- templates/data/skr-integration-data.yaml
- configure Gophers notifications
> Prepare configure notifications

- prow/jobs/kyma/skr-aws-upgrade-integration-dev.yaml
- prow/jobs/kyma/skr-integration.yaml
- templates/data/skr-aws-upgrade-integration-dev-data.yaml
- templates/data/skr-own-cluster-dev.yaml
> Prepare gophers notifications part 2

- prow/config.yaml
Kyma-environment-broker repo has enabled branch protection.
- Protect kyma-environment-broker repo
/kind chore
/area security
> Enable branch protection for kyma-environment-broker repo

- prow/jobs/kyma/skr-integration.yaml
- templates/data/skr-own-cluster-dev.yaml
- change cron expression for own cluster for testing purposes
> Testing gophers notifications

- prow/jobs/busola/busola-integration.yaml
- prow/jobs/incubator/reconciler/reconciler.yaml
- prow/jobs/istio/istio-integration.yaml
- prow/jobs/istio/istio-manager.yaml
- prow/jobs/kyma-project/telemetry-manager/telemetry-manager-e2e-test.yaml
- prow/jobs/kyma-project/telemetry-manager/telemetry-manager-upgrade-test.yaml
- prow/jobs/kyma-project/telemetry-manager/telemetry-manager-verify-module.yaml
- prow/jobs/test-infra/images.yaml
- sec-scanners-config.yaml
- templates/data/incubator-buildpack-data.yaml
- templates/data/istio-module-data.yaml
This reverts commit 715ebf616a90667eaeb9c90a181840bb41ff6fa8.
- ...
- ...
- ...
> Revert "Bumping test-infra and testimages (#8099)"

- prow/cluster/resources/gatekeeper-constraints/workloads/terraformExecutorK8sSaTrustedUsage.yaml
- Fix Terraform constraints
/area security
/kind chore
/cc @dekiel
> Fix terraform constraints

- configs/terraform/environments/prod/dns.tf
- configs/terraform/environments/prod/prow.tf
/kind feature
/area ci
Im not sure if it's going to be correct approach, probably better idea would be to pin one of workloads cluster to this configuration.
> initial prow cluster as terraform resource

- configs/gencred-config.yaml
- configs/terraform/environments/prod/variables.tf
/kind deprecation
/area ci
/cc halamix2
> Change GCP cluster region

- configs/terraform/environments/prod/prow.tf
/kind chore
/area ci
/cc halamix2
> Add required labels to trusted cluster

- prow/jobs/kyma/keb-endpoints-test.yaml
- prow/scripts/keb-endpoints-test.sh
- templates/config.yaml
- templates/data/keb-endpoints-test.yaml
- vpath/pjtester.yaml
The new location of keb-endpoints-test is the kyma-environment-broker repository.
- Change the repository from which the test is run
https://github.com/kyma-project/kyma-environment-broker/issues/3
> Change keb-endpoints-test location

- prow/jobs/kyma/skr-aws-upgrade-integration-dev.yaml
- templates/data/skr-aws-upgrade-integration-dev-data.yaml
Changing skr-aws-upgrade-integration-dev cron job schedule so that it runs at the same time as other skr-tests.
- Change cron job value
/area ci
/kind chore
> Change skr-aws-upgrade-integration-dev cron schedule

- prow/jobs/istio/istio-manager.yaml
- templates/data/istio-module-data.yaml
- Run Istio build and GCP integration test jobs on PRs to release branch
> Run Istio Prow jobs on PRs to release branch

- prow/jobs/kyma/skr-integration.yaml
- templates/data/skr-own-cluster-dev.yaml
- configure skr-aws-own-cluster test to be run once per day
> Configure own cluster skr test once per day

- prow/jobs/governance.yaml
- templates/data/governance-data.yaml
/area ci
Needs to be migrated to other, supported solution #8186
> Make governance jobs optional

- development/image-syncer/external-images.yaml
- Add istio 1.18.1 to external images
> Add istio 1.18.1 to external images

- prow/jobs/test-infra/secret-leaks-log-scanner.yaml
- prow/jobs/test-infra/secrets-rotator.yaml
- prow/jobs/test-infra/terraform-prod-module.yaml
- templates/data/test-infra/secret-leaks-log-scanner.yaml
- templates/data/test-infra/secrets-rotator.yaml
- templates/data/test-infra/terraform-prod-module.yaml
Fixing wrong flags for postsubmit.
/kind bug
> Fixing wrong flags for postsubmit.

- prow/labels.yaml
/area ci
/kind bug
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/ci-prow-label-sync/1680808857623859200
Fixes failing job
> Remove duplicated area/automation label

- prow/config.yaml
> Use squash in keda manager

- CODEOWNERS
- prow/jobs/eventing-manager/eventing-manager-generic.yaml
- templates/data/eventing-manager-data.yaml
- Change the argument to run the unit-test job for eventing-manager
- Add tunas/eventing team as codeowners of eventing-manager files
[Eventing-manager 17](https://github.com/kyma-project/eventing-manager/issues/17)
> Update eventing-manager unit-test job

- prow/scripts/build-kyma-artifacts.sh
- Use correct credentials in Kyma artifacts 2.16 
- #8163
/kind bug
/area tests
> Use correct credentials in Kyma artifacts 2.16

- prow/cluster/resources/gatekeeper-constraints/workloads/kymaBotGithubSecretTrustedUsage.yaml
- prow/cluster/resources/gatekeeper-constraints/workloads/pjtesterSecretsTrustedUsage.yaml
- prow/cluster/resources/gatekeeper-constraints/workloads/signifySecretTrustedUsage.yaml
- Exclude sidecar from secrets constraints
/kind bug
/area security
- #8092
> Exclude sidecar from secrets constraints

- prow/config.yaml
> Fix typo in preset-compass-director-secret definition

- prow/jobs/kyma-project/telemetry-manager/telemetry-manager-e2e-test-logging.yaml
- prow/jobs/kyma-project/telemetry-manager/telemetry-manager-e2e-test-metrics.yaml
- prow/jobs/kyma-project/telemetry-manager/telemetry-manager-e2e-test-tracing.yaml
Split telemetry-manager-e2e-test to a logging, tracing, and metrics test to reduce the execution time.
- Split telemetry-manager-e2e-test
https://github.com/kyma-project/telemetry-manager/pull/266
> Split telemetry-manager-e2e-test

- prow/jobs/nats-manager/nats-manager-generic.yaml
- templates/data/nats-manager-data.yaml
- Enabled always run for NATS manager jobs
> Enabled always run for NATS manager jobs

- configs/terraform/environments/prod/prow.tf
Further reduce footprint of the additional pool that should handle all GKE components. Probably it will more adjustments in the future. Right now I want to move GKE-based workloads into new pool.
/area ci
/kind feature
/cc halamix2
> Add node taint for minimal pool and enable autoscale between 1/2

- prow/jobs/kyma/skr-integration.yaml
- templates/data/skr-integration-data.yaml
Changing skr-preview-dev cron job schedule so that it runs at the same time as other skr-tests.
- Change cron job value
/area ci
/kind chore
> Change skr-preview-dev cron schedule

- prow/jobs/incubator/compass-console/compass/compass-ui.yaml
- templates/config.yaml
- Change node image for compass-console to e2e-dind-nodejs
> Change node image for compass-console

- configs/terraform/environments/prod/prow.tf
- opa/gatekeeper/deployments/gatekeeper.yaml
- prow/cluster/resources/external-secrets/values_trusted.yaml
> Update external secrets configuration to schedule on components pool

- prow/autobump-config/test-infra-autobump-config.yaml
- templates/templates/test-infra-autobump-config.yaml
- Don't fail on inconsistent prod image bumps
/kind bug
/area ci
- #8231
> Don't fail on inconsistent prod image bumps

- prow/cluster/resources/gatekeeper-constraints/workloads/signifySecretTrustedUsage.yaml
- prow/jobs/btp-manager/btp-manager-build.yaml
- templates/data/btp-manager-build.yaml
- Fix constraints warnings for pull-btp-manager-build by changing args order
> Fix constraints warnings for pull-btp-manager-build

- prow/jobs/api-gateway/api-gateway-integration-tests.yaml
- prow/jobs/istio/istio-integration.yaml
- templates/data/api-gateway-integration-tests.yaml
- Run api-gateway integration tests also on release branch
> Run api-gateway integration tests also on release branch

- prow/jobs/test-infra/go-validation.yaml
- templates/data/test-infra/golang-tests.yaml
> Give more CPU to Go linting

- prow/jobs/busola/busola-integration.yaml
- prow/jobs/kyma-dashboard/kyma-dashboard-integration.yaml
- prow/jobs/kyma-dashboard/kyma-dashboard-smoke-test-prod.yaml
- prow/jobs/kyma-dashboard/kyma-dashboard-smoke-test-stage.yaml
- we are struggling with CPU limits.
/area ci
/kind feature
> bump resources

- prow/jobs/kyma/kyma-integration-gardener-eventing.yaml
- templates/data/kyma-integration-gardener-data.yaml
Make eventing-with-auth-manager job required.
> Make eventing-with-auth-manager job required

- .koapps.yaml
/kind chore
/area ci
Add some tools that were present in prow-tools to reuse with ko-based job.
> Add tools to ko build

- docs/security/imagemitigation.json
- docs/security/schema.json
PR includes JSON with mitigated non-trusted images
> Add json with mitigated images

- prow/cluster/resources/gatekeeper-constraints/workloads/signifySecretTrustedUsage.yaml
- Fix Busola secrets constraints
/kind chore
/area security
> Fix Busola secrets constraints

- Makefile
- prow/jobs/kyma/components/eventing-controller/eventing-controller-checks.yaml
- templates/data/go-toolkit-validation.yaml
- test-inventory-integration.md
- update eventing-controller unit test job to use Makefile
> run eventing-controller test using makefile

- development/gcbuild/run.sh
- prow/scripts/kyma-testing.sh
- prow/scripts/lib/kyma.sh
- prow/scripts/lib/testing-helpers.sh
- prow/scripts/lib/utils.sh
- prow/scripts/vpathguard.sh
> fix shellcheck errors

- prow/jobs/eventing-auth-manager/eventing-auth-manager-generic.yaml
- templates/data/eventing-auth-manager-data.yaml
Fix failing unit tests
* the current go test command is not working. It is changed to use make target `make test`
> Fix unit test job

- .ko.yaml
- prow/jobs/test-infra/ko-build.yaml
> Use image bumpers with git image

- development/image-syncer/external-images.yaml
- Add Istio 1.18.2 to image syncer
> Add Istio 1.18.2 to image syncer

- .github/workflows/pull-plan-prod-terraform.yaml
Checkout proper pull request merge commit.
Validate the merged commit did not changed.
/kind feature
> Fix checkout ref

- .github/workflows/pull-plan-prod-terraform.yaml
Sanity check failed with error message: `fatal: ambiguous argument 'HEAD^': unknown revision or path not in the working tree.`
Trying to fetch more commits.
/kind feature
> Fetch more commits

- .github/workflows/pull-plan-prod-terraform.yaml
Compare both merge commit parents
/kind feature
> Compare both merge commit parents.

- .github/workflows/pull-plan-prod-terraform.yaml
Explicit permissions are needed because of workflow running on fork.
/kind feature
> Adding explicit permissions for ID token

- development/tools/cmd/githubrelease/README.md
- Formatting fix
- Minor language correction
> Fix the table

- prow/jobs/kyma-dashboard/kyma-dashboard-stage.yaml
- fix post `kyma-dashboard-stage` job
/area ci
/kind bug
> fix kyma-dashboard-stage job

- configs/terraform/environments/prod/provider.tf
- configs/terraform/environments/prod/prow.tf
> Use google-beta and update cluster to optimize_utilization

- prow/cluster/resources/gatekeeper-constraints/workloads/signifySecretTrustedUsage.yaml
- prow/cluster/resources/gatekeeper-constraints/workloads/terraformExecutorK8sSaTrustedUsage.yaml
- Fix OPA constraint warnings
/kind chore
/area ci
> Fix opa constraint warnings

- prow/jobs/kyma/kyma-integration.yaml
- templates/data/kyma-integration-data.yaml
- Add `simple-api-gateway` argument to the `templates/data/kyma-integration-data.yaml`
https://github.com/kyma-project/kyma/issues/17506
> Adjust to work with new api-gateway test

- .github/workflows/pull-plan-prod-terraform.yaml
tfcmt tool is not able to work with comments because of 403 HTTP response. By default auto generated github token gets only read permissions for pull request events.
/kind feature
> Fix workflow permissions to post comments on pr or issue.

- prow/jobs/modules/external/keda-manager.yaml
- prow/jobs/modules/internal/serverless-manager.yaml
- templates/data/generic_module_data.yaml
> fix limits for otters

- prow/autobump-config/test-infra-autobump-config.yaml
- templates/templates/test-infra-autobump-config.yaml
Disable autobumper on sec-scanners-config.yaml to keep it as source of true about image version running on our infra
- Disable autobumping sec-scanners-config
Resolves #8448
> Disable autobumping sec-scanners-config

- configs/terraform/secrets-leaks-log-scanner/gcs-bucket-mover.tf
- configs/terraform/secrets-leaks-log-scanner/github-issue-creator.tf
- configs/terraform/secrets-leaks-log-scanner/github-issue-finder.tf
- configs/terraform/secrets-leaks-log-scanner/secrets-leak-log-scanner.tf
- configs/terraform/secrets-leaks-log-scanner/slack-message-sender.tf
- Bump images used by terraform
/kind chore
> Update images used by terraform
