- .koapps.yaml
> Add githubissues to .koapps.yaml

- prow/jobs/modules/internal/serverless-manager.yaml
- templates/data/generic_module_data.yaml
Prowjobs building fresh serverless based on release commit.
https://github.com/kyma-project/serverless-manager/issues/167
> Add prowjobs for serverless operator release flow

- prow/jobs/busola/busola-backend/busola-backend.yaml
- prow/jobs/busola/busola.yaml
- add limits to the rest of busola jobs.
/area ci
/kind feature
> add limits to the rest of busola jobs.

- prow/jobs/kyma-dashboard/kyma-dashboard-dev.yaml
- prow/jobs/kyma-dashboard/kyma-dashboard-prod.yaml
- prow/jobs/kyma-dashboard/kyma-dashboard-stage.yaml
- add limits for kyma-dashboard jobs
/area ci
/kind feature
> add limits for kyma-dashboard jobs

- prow/jobs/telemetry-manager/telemetry-manager-generic.yaml
- templates/data/telemetry-manager-data.yaml
- Change the image that is being used for module templates
> Use another image for generating the module releases

- prow/jobs/lifecycle-manager/lifecycle-manager.yaml
- templates/data/lifecycle-manager-data.yaml
- Replaced by Github Action workflow: https://github.com/kyma-project/lifecycle-manager/blob/main/.github/workflows/pull-lifecycle-mgr-lint.yml#L1
> Remove pull-lifecycle-mgr-lint

- prow/jobs/incubator/ord-service/components/ord-service/ord-service-generic.yaml
- templates/data/generic_component_ord_service_data.yaml
- vpath/pjtester.yaml
> Fix ord-service unit test job

- development/gcp/cloud-run/slack-message-sender/requirements.txt
- go.mod
- go.sum
- prow/jobs/test-infra/secret-leaks-log-scanner.yaml
- templates/data/test-infra/secret-leaks-log-scanner.yaml
- Fix pull-build-image-slackmessagesender job
/kind bug
/area ci
> Fix pull-build-image-slackmessagesender job

- prow/jobs/kyma/tests/serverless/serverless-integration-k3d.yaml
- Replace `simple-tracing` with generic `serverless-contract-tests`
https://github.com/kyma-project/kyma/pull/17913
> Use serverless-contract-tests scenario

- prow/cluster/resources/gatekeeper-constraints/workloads/allowedImagesProwProwjobsNamespace.yaml
- prow/cluster/resources/gatekeeper-constraints/workloads/kymaBotGithubSapTokenTrustedUsage.yaml
- prow/cluster/resources/gatekeeper-constraints/workloads/kymaBotGithubSecretTrustedUsage.yaml
- prow/jobs/test-infra/gcr-cleaner.yaml
- Avoid using latest tag in gcr-cleaner
- Add github-issues for internal token
- Fix regexp for github-issues
> Fix OPA Gatekeeper warning

- .ko.yaml
- .koapps.yaml
- prow/jobs/test-infra/ko-build.yaml
> add external plugins to .koapps.yaml

- .github/workflows/pull-plan-prod-terraform.yaml
Use pull request number because the head_ref is different for every new commit in pr. The concurrent group should collect workflow runs for one pr.
/kind bug
> Update workflow concurrent group.

- configs/terraform/modules/secrets-leaks-log-scanner/gcs-bucket-mover.tf
- configs/terraform/modules/secrets-leaks-log-scanner/github-issue-creator.tf
- configs/terraform/modules/secrets-leaks-log-scanner/github-issue-finder.tf
- configs/terraform/modules/secrets-leaks-log-scanner/secrets-leak-log-scanner.tf
- prow/cluster/components/automerge-notification_external-plugin.yaml
- prow/cluster/components/cla-assistant_external-plugin.yaml
- prow/cluster/components/needs-tws_external-plugin.yaml
- prow/jobs/kyma/periodics.yaml
- prow/jobs/test-infra/buildpack.yaml
- templates/data/buildpack-data.yaml
/kind chore
/area ci
effort for better maintainability of the code and images
> Change image for external-plugins

- prow/cluster/resources/gatekeeper-constraints/workloads/kymaAutobumpBotGithubTokenTrustedUsage.yaml
- prow/cluster/resources/gatekeeper-constraints/workloads/signifySecretTrustedUsage.yaml
- prow/jobs/test-infra/gcr-cleaner.yaml
- Fix OPA Gatekeeper warnings
/kind chore
/area security
> Fix opa warn

- prow/jobs/kyma-dashboard/kyma-dashboard-integration.yaml
- prow/jobs/kyma-dashboard/kyma-dashboard-smoke-test-prod.yaml
- prow/jobs/kyma-dashboard/kyma-dashboard-smoke-test-stage.yaml
- allow k3d for kyma-dashboard test jobs.
/area ci
/kind feature
> allow k3d for kyma-dashboard test jobs

- prow/jobs/kyma/periodics.yaml
> Fix github-issues user permissions

- development/tools/cmd/githubissues/table_org_schema.json
- update BQ table schema
/kind bug
/area ci
> update BQ table schema

- prow/cluster/resources/gatekeeper-constraints/prow/allowedImagesProwNamespace.yaml
- prow/cluster/resources/gatekeeper-constraints/prow/allowedImagesProwToolsNamespaces.yaml
- prow/cluster/resources/gatekeeper-constraints/workloads/allowPrivilegeEscalation.yaml
- prow/cluster/resources/gatekeeper-constraints/workloads/allowedImagesProwProwjobsNamespace.yaml
- prow/cluster/resources/gatekeeper-constraints/workloads/allowedImagesProwToolsNamespaces.yaml
- prow/cluster/resources/gatekeeper-constraints/workloads/apparmor.yaml
- prow/cluster/resources/gatekeeper-constraints/workloads/capabilities.yaml
- prow/cluster/resources/gatekeeper-constraints/workloads/hostFilesystem.yaml
- prow/cluster/resources/gatekeeper-constraints/workloads/hostNetworkPorts.yaml
- prow/cluster/resources/gatekeeper-constraints/workloads/kymaAutobumpBotGithubTokenTrustedUsage.yaml
- prow/cluster/resources/gatekeeper-constraints/workloads/kymaBotGithubSapTokenTrustedUsage.yaml
- prow/cluster/resources/gatekeeper-constraints/workloads/kymaBotGithubSecretTrustedUsage.yaml
- prow/cluster/resources/gatekeeper-constraints/workloads/kymaBotTriageTokenTrustedUsage.yaml
- prow/cluster/resources/gatekeeper-constraints/workloads/pjtesterSecretsTrustedUsage.yaml
- prow/cluster/resources/gatekeeper-constraints/workloads/privilegedContainers.yaml
- prow/cluster/resources/gatekeeper-constraints/workloads/pspHostNamespace.yaml
- prow/cluster/resources/gatekeeper-constraints/workloads/seccomp.yaml
- prow/cluster/resources/gatekeeper-constraints/workloads/selinux.yaml
- prow/cluster/resources/gatekeeper-constraints/workloads/signifySecretTrustedUsage.yaml
- prow/cluster/resources/gatekeeper-constraints/workloads/terraformExecutorK8sSaTrustedUsage.yaml
- prow/cluster/resources/gatekeeper-constraints/workloads/users.yaml
- Set enforcement action to deny for all rules
/kind feature
/area security
> Enable intrusive mode for OPA Gatekeeper

- prow/cluster/resources/gatekeeper-constraints/workloads/signifySecretTrustedUsage.yaml
- Two serveless jobs failed due to OPA pod removal due to strict policy
/kind bug
/area security
> Add serverless to trusted signify

- prow/jobs/kyma/kyma-integration-gardener-eventing.yaml
- templates/config.yaml
- templates/data/kyma-integration-gardener-data.yaml
Fix the following Eventing jobs to use the correct buildpack image:
- pre-main-kyma-gardener-gcp-eventing
- pre-main-kyma-gardener-gcp-eventing-upgrade
- kyma-gardener-gcp-eventing-with-auth-manager
**Related issues**
- https://github.com/kyma-project/kyma/issues/17930
> Fix the Eventing jobs

- prow/cluster/resources/gatekeeper-constraints/workloads/kymaAutobumpBotGithubTokenTrustedUsage.yaml
- prow/cluster/resources/gatekeeper-constraints/workloads/signifySecretTrustedUsage.yaml
- Fix OPA Gatekeeper errors for ci-dockerhub-autobump
- Fix OPA Gatekeeper erros for KEB
/kind bug
/area security
> Fix OPA GAtekeeper errors for KEB and ci-dockerhub-autobump

- images/e2e-dind-nodejs/Dockerfile
> Add helm to e2e-dind-nodejs

- prow/cluster/resources/gatekeeper-constraints/workloads/kymaBotGithubSecretTrustedUsage.yaml
- Fix serverless manager module build job
/kind bug
/area security
> Fix serverless manager module build job constraints

- prow/jobs/kyma/releases/kyma-release-215.yaml
- prow/jobs/kyma/releases/kyma-release-216.yaml
- prow/jobs/kyma/releases/kyma-release-217.yaml
- prow/jobs/kyma/releases/kyma-release-218.yaml
- prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
- templates/data/kyma-release-data.yaml
> Fix rc creation

- prow/jobs/kyma/releases/kyma-release-215.yaml
- prow/jobs/kyma/releases/kyma-release-216.yaml
- prow/jobs/kyma/releases/kyma-release-217.yaml
- prow/jobs/kyma/releases/kyma-release-218.yaml
- prow/scripts/cluster-integration/kyma-gke-long-lasting.sh
- prow/scripts/cluster-integration/kyma-gke-release-candidate.sh
- templates/data/kyma-release-data.yaml
- Fix GCP release cluster jobs
> Fix GCP release cluster jobs

- prow/jobs/kyma/components/kyma-components-static-checks.yaml
- templates/data/go-toolkit-validation.yaml
> fix function controller jobs

- prow/jobs/kyma/kyma-integration-gardener.yaml
- templates/data/kyma-integration-gardener-data.yaml
Change build image to include node which is missing as dependency for the pipeline to run
> change build image to jobConfig_buildpack_node

- prow/jobs/incubator/reconciler/reconciler.yaml
- templates/data/incubator-buildpack-data.yaml
- Increase resources for linting job
- Update image for pre-main-reconciler-publish-pr-cli to use a image that has gcloud bundled
> Fix reconciler job issue

- prow/jobs/kyma-dashboard/kyma-dashboard-integration.yaml
- prow/jobs/kyma-dashboard/kyma-dashboard-smoke-test-prod.yaml
- prow/jobs/kyma-dashboard/kyma-dashboard-smoke-test-stage.yaml
- remove k3d label,
- adjust run_if_change
/area ci
/kind feature
> remove k3d label and adjust run if change

- prow/jobs/busola/lighthouse.yaml
- bump lighthouse resources.
/area ci
/kind test-failing
> bump resources for lighthouse:

- prow/jobs/busola/lighthouse.yaml
- enable k3d for lighthouse.
/area ci
/kind feature
> enable k3d for lighthouse

- prow/scripts/cluster-integration/kyma-gke-release-candidate.sh
- Fix GCP release candidate cluster job
> Fix GCP RC cluster job

- prow/jobs/modules/internal/serverless-manager.yaml
- templates/data/generic_module_data.yaml
Job didnt run as expected we needed to fix indentation
https://github.com/kyma-project/serverless-manager/issues/167
> Fix indentation in prowjob

- prow/cluster/resources/gatekeeper-constraints/workloads/seccomp.yaml
- Add e2e-gcloud to seccomp constraint
/kind bug
/area security
> Add e2e-gcloud to seccomp constraint

- prow/jobs/control-plane/components/provisioner/provisioner-integration-test.yaml
This pipeline had invalid regex. Hopefuly it's better now...
> Correct provisioner e2e regex

- prow/cluster/resources/gatekeeper-constraints/workloads/signifySecretTrustedUsage.yaml
- Fix BTP OPA job constraint entrypoint
/area tests
/kind bug
> Fix BTP OPA job constraint

- configs/terraform/modules/slack-message-sender/slack-message-sender.tf
- Bump slack-message-sender image
- ...
- ...
/kind chore
/area tools
> Bump slack-message-sender image

- .koapps.yaml
- configs/terraform/environments/prod/github-webhook-gateway.tf
- configs/terraform/modules/github-webhook-gateway/github-webhook-gateway.tf
- configs/terraform/modules/github-webhook-gateway/main.tf
- configs/terraform/modules/slack-message-sender/slack-message-sender.tf
- development/gcp/cloud-run/github-webhook-gateway/github-webhook-gateway.go
- development/gcp/cloud-run/slack-message-sender/slack-message-sender.py
- Move issue created function to cloud run
/kind feature
/area tools
/retest
> Move issue created function to cloud run

- configs/terraform/modules/github-webhook-gateway/github-webhook-gateway.tf
- Fix github-webhook-gateway image
/cc dekiel
/kind chore
/area tools
> Fix github-webhook-gateway image

- prow/jobs/kyma-dashboard/kyma-dashboard-integration.yaml
- prow/jobs/kyma-dashboard/kyma-dashboard-smoke-test-prod.yaml
- prow/jobs/kyma-dashboard/kyma-dashboard-smoke-test-stage.yaml
- kyma-dashboard tests are not using `nkyma` cluster currently.
/area ci
/kind feature
> remove gardener label from dashboard tests

- configs/terraform/modules/github-webhook-gateway/github-webhook-gateway.tf
- configs/terraform/modules/slack-message-sender/issue-labeled.tf
- configs/terraform/modules/slack-message-sender/main.tf
- configs/terraform/modules/slack-message-sender/slack-message-sender.tf
- development/gcp/cloud-run/github-webhook-gateway/github-webhook-gateway.go
- development/gcp/cloud-run/github-webhook-gateway/github-webhook-gateway_test.go
- development/gcp/cloud-run/slack-message-sender/slack-message-sender.py
- Test slack message sender with different channel to limit spam
- add github - slack eventarc connection
- fix typos
- allow github to access endpoint
> Test slack message sender with different channel

- prow/jobs/kyma/components/kyma-components-static-checks.yaml
- templates/data/go-toolkit-validation.yaml
- The linter job also checks if the autogenerated md files are in sync with the Go struct comments. So we should run it to prevent manual changes to the autogenerated files.
> [Telemetry Manager] Include md files into linter paths

- prow/jobs/modules/internal/serverless-manager.yaml
- templates/data/generic_module_data.yaml
> Add missing label to release job

- prow/jobs/kyma-project/kyma/components/central-application-connectivity-validator/unit-tests-validator.yaml
> change centrall-application-connectivity-validator test job

- configs/terraform/modules/github-webhook-gateway/github-webhook-gateway.tf
- configs/terraform/modules/github-webhook-gateway/main.tf
- development/gcp/cloud-run/github-webhook-gateway/github-webhook-gateway.go
- use correct webhook secret
/area tools
/kind bug
> Fix github webhook gateway token

- prow/cluster/resources/gatekeeper-constraints/workloads/kymaBotGithubSecretTrustedUsage.yaml
- prow/jobs/control-plane/control-plane-validation.yaml
- prow/jobs/incubator/reconciler/reconciler.yaml
- prow/jobs/kyma/kyma-validation.yaml
- prow/jobs/test-infra/validation.yaml
- templates/config.yaml
- templates/data/control-plane-validation.yaml
- templates/data/incubator-buildpack-data.yaml
- templates/data/kyma-validation-data.yaml
- templates/data/validation-data.yaml
- Remove governance-toolkit image
/kind cleanup
/area ci
> Remove governance-toolkit image

- configs/terraform/modules/github-webhook-gateway/github-webhook-gateway.tf
- Bump github-webhook-gateway iamge
/kind chore
/area tools
> Bump github-webhook-gateway iamge

- prow/jobs/nats-manager/nats-manager-generic.yaml
- templates/data/nats-manager-data.yaml
- remove unit test job for nats-manager as it has been converted to a gha
> remove nats-manager-unit-test-job

- development/gcp/cloud-run/slack-message-sender/slack-message-sender.py
- check label value in Slack sender
/kind bug
/area tools
> check label value in Slack sender

- prow/scripts/reconciler/reconciler-e2e-nightly-gardener.sh
- vpath/pjtester.yaml
- Fix ref to script for `nightly-main-reconciler-e2e`
> Fix nightly-main-reconciler-e2e

- development/gcp/cloud-run/github-webhook-gateway/github-webhook-gateway.go
- Fix panic in github gateway when assignee is empty
/kind bug
/area tools
> Fix panic in github gateway when assignee is empty

- .github/dependabot.yml
- templates/data/test-infra/dependabot-config-data.yaml
- Automatically bump GH actions
> Automatically bump GH actions

- .github/dependabot.yml
- templates/data/test-infra/dependabot-config-data.yaml
- templates/templates/dependabot.tmpl
> Fix GH actions autobump

- configs/terraform/modules/github-webhook-gateway/github-webhook-gateway.tf
- Fix pubsub topic name
/kind bug
/area tools
> Fix pubsub topic name in github webhook gateway

- configs/terraform/modules/github-webhook-gateway/github-webhook-gateway.tf
- Add missing permissios to githbug webhook gateway
/kind bug
/area tools
> Add missing permissios to githbug webhook gateway

- .github/dependabot.yml
- .github/workflows/pull-plan-prod-terraform.yaml
- templates/data/test-infra/dependabot-config-data.yaml
- Pin version of gh comments action and tool, as requested by security
- disable automatic approval of GH actions bumps, because we need to pi specific action commits
/kind chore
/area ci
> Use specific version of gh comments action and tool

- prow/jobs/busola/busola-backend/backend-deployment-check.yaml
- prow/jobs/busola/busola-backend/busola-backend.yaml
- prow/jobs/busola/busola-integration.yaml
- prow/jobs/busola/busola-web/busola-web.yaml
- prow/jobs/busola/busola-web/web-deployment-check.yaml
- prow/jobs/busola/busola.yaml
- prow/jobs/busola/lighthouse.yaml
…submit images on ui5 branch
- we are currently working on big feature, and we need have triggered jobs on feature branch. 
> Turn on busola integration tests, deployment-checks and building  presubmit images on ui5 branch

- prow/jobs/kyma-project/kyma/components/central-application-gateway/unit-tests-gateway.yaml
I don't think the giga-cpu works
- Remove giga-cpu
> Remove giga-CPU

- development/gcp/cloud-run/github-webhook-gateway/github-webhook-gateway.go
- development/gcp/cloud-run/github-webhook-gateway/github-webhook-gateway_test.go
- Fix github webhook gateway slack mapping, since we only need one domain for now, and filterring by Host header didn't work as expected
/area tools
/kind chore
> Fix github webhook gateway slack mapping

- development/gcp/cloud-run/slack-message-sender/slack-message-sender.py
> Fix slack message sender

- prow/config.yaml
- remove branch protection for feature branch.
/area ci
/kind feature
> remove branch protection for ui5 branch

- development/image-syncer/external-images.yaml
- Add postgres image 11.21-alpine3.18
> Bump postgres to 11.21-alpine3.18

- .koapps.yaml
- development/gcp/cloud-run/cors-proxy/cors-proxy.go
- Add cors proxy
/kind feature
/area tools
> Add cors proxy

- configs/terraform/environments/prod/cors-proxy.tf
- configs/terraform/modules/cors-proxy/cors-proxy.tf
- configs/terraform/modules/cors-proxy/main.tf
- Add cors proxy module
/kind feature
/area tools
- #8717
> Add cors proxy module

- prow/cluster/resources/gatekeeper-constraints/workloads/kymaBotGithubSecretTrustedUsage.yaml
- prow/cluster/resources/gatekeeper-constraints/workloads/terraformExecutorK8sSaTrustedUsage.yaml
- Fix secret rotator constraints
/kind bug
/area ci
> Fix secret rotator constraints

- prow/jobs/api-gateway/api-gateway-build.yaml
- prow/jobs/api-gateway/api-gateway-integration-tests.yaml
- prow/jobs/api-gateway/api-gateway-validation.yaml
- templates/data/api-gateway-build.yaml
- templates/data/api-gateway-integration-tests.yaml
- templates/data/api-gateway-validation.yaml
- Add LICENSES directory to skip on for prow jobs
> Api gateway tests skip on LICENSES dir changes

- configs/terraform/modules/cors-proxy/cors-proxy.tf
- Don't require authentication for cors-proxy
/kind bug
/area tools
> Don't require authentication for cors-proxy

- prow/jobs/incubator/compass/components/operations-controller/operations-controller-generic.yaml
- Fix for limits of post operations-controller build job.
> Fix for limits of post operations-controller build job

- images/e2e-dind-k3d/init.sh
- images/e2e-dind-nodejs/init.sh
Possibly to fix inotify watch errors that are happening in dind jobs
/kind bug
/area ci
#8473
> Ad cleanup logic of docker after the job exits

- prow/config.yaml
Prow status keeps jobs history only for 1 day and it is hard to rerun jobs for developers.
- Change max_prowjob_age to 7 days
> Increase max_prowjob_age

- CODEOWNERS
- prow/jobs/eventing-auth-manager/eam-integration-test.yaml
- fix broken prow job configuration introduced by refactoring
> fix broken integration test for eam

- prow/jobs/runtime-watcher/runtime-watcher.yaml
- vpath/pjtester.yaml
- folder renaming in ref repo has not considered this post job to break
> Fix docker context of post build runtime-watcher

- prow/cluster/resources/gatekeeper-constraints/workloads/kymaAutobumpBotGithubTokenTrustedUsage.yaml
- prow/jobs/kyma-project/k8s-prow/k8s-prow-periodics.yaml
> Add autobump testimages job for k8s-prow

- development/image-syncer/external-images.yaml
> bump nats config reloader image

- prow/cluster/resources/gatekeeper-constraints/workloads/kymaAutobumpBotGithubTokenTrustedUsage.yaml
- prow/jobs/kyma-project/k8s-prow/k8s-prow-periodics.yaml
Fixed typos and non-working gatekeeper constraint
/kind bug
/area ci
> Fix autobump job for k8s-prow

- prow/config.yaml
Require to pass `run-eslint` Github Action before merging
- Add `run-eslint` status check
> Add required status check for KEB repo

- prow/jobs/governance.yaml
- templates/data/governance-data.yaml
- Remove the job in favor of the Markdown Link Check GitHub Action
> Remove telemetry governance job

- prow/autobump-config/prow-cluster-autobump-config.yaml
- prow/cluster/components/crier_deployment.yaml
- prow/cluster/components/deck_deployment.yaml
- prow/cluster/components/gcsweb.yaml
- prow/cluster/components/ghproxy.yaml
- prow/cluster/components/hook_deployment.yaml
- prow/cluster/components/horologium_deployment.yaml
- prow/cluster/components/prow_controller_manager_deployment.yaml
- prow/cluster/components/sinker_deployment.yaml
- prow/cluster/components/statusreconciler_deployment.yaml
- prow/cluster/components/tide_deployment.yaml
- prow/config.yaml
- prow/jobs/incubator/reconciler/reconciler.yaml
- prow/jobs/kyma-project/k8s-prow/k8s-prow-periodics.yaml
- prow/jobs/test-infra/branchprotector.yaml
- prow/jobs/test-infra/checkconfig.yaml
- prow/jobs/test-infra/prow-periodics.yaml
- prow/jobs/test-infra/triage-jobs.yaml
- prow/scripts/branchprotector-job.yaml
- prow/workload-cluster/ghproxy.yaml
- sec-scanners-config.yaml
- templates/data/checkconfig.yaml
- templates/data/incubator-buildpack-data.yaml
- templates/data/prow-periodics-data.yaml
Those images are based on our alpine testimages and we have full control over vulnerabilities in there. They are updated every week.
/kind feature
/area prow
> Use Prow images from fork

- prow/cluster/resources/gatekeeper-constraints/workloads/kymaAutobumpBotGithubTokenTrustedUsage.yaml
- prow/cluster/resources/gatekeeper-constraints/workloads/kymaBotGithubSecretTrustedUsage.yaml
- prow/cluster/resources/gatekeeper-constraints/workloads/signifySecretTrustedUsage.yaml
/kind bug
/area prow
/priority critical
> Fix gatekeeper constraints for forked images

- prow/config.yaml
Require to pass given Github Actions before merging
- Add `run-unit-tests / build` check
- Add `run-e2e-tests / run-e2e-tests` check
- Add `markdown-link-check` check
- Add `validate-labels` check
> Add required status checks for BTP Manager repo

- sec-scanners-config.yaml
- Exclude files with suffix _test.go from scans.
> Update sec-scanners-config.yaml - exclude tests

- prow/cluster/components/monitoring/grafana_deployment.yaml
- prow/cluster/components/monitoring/prometheus_operator_deployment.yaml
- prow/cluster/components/pushgateway_deployment.yaml
- prow/cluster/components/web_server_deployment.yaml
- prow/jobs/api-gateway/api-gateway-validation.yaml
- prow/jobs/incubator/compass/components/director/director-generic.yaml
- prow/jobs/incubator/compass/components/kyma-adapter/kyma-adapter-generic.yaml
- prow/jobs/incubator/ord-service/components/ord-service/ord-service-generic.yaml
- prow/jobs/incubator/reconciler/reconciler.yaml
- prow/jobs/kyma-project/compass-manager/static-checks.yaml
- prow/jobs/kyma-project/kyma/components/central-application-connectivity-validator/lint-validator.yaml
- prow/jobs/kyma-project/kyma/components/central-application-gateway/lint-gateway.yaml
- prow/jobs/kyma-project/kyma/components/compass-runtime-agent/lint-agent.yaml
- prow/jobs/kyma-project/warden/warden.yaml
- prow/jobs/kyma/components/event-publisher-proxy/event-publisher-proxy-checks.yaml
- prow/jobs/kyma/components/eventing-controller/eventing-controller-checks.yaml
- prow/jobs/kyma/components/kyma-components-static-checks.yaml
- prow/jobs/modules/external/keda-manager.yaml
- prow/jobs/template-operator/template-operator.yaml
- prow/jobs/test-infra/go-validation.yaml
- prow/jobs/test-infra/presubmit-scanner.yaml
- prow/staging/cluster/monitoring/grafana_deployment.yaml
- prow/staging/cluster/pushgateway_deployment.yaml
- sec-scanners-config.yaml
- templates/config.yaml
- templates/data/generic_module_data.yaml
- templates/data/go-toolkit-validation.yaml
- templates/data/presubmit_scanner_data.yaml
- templates/data/template-operator-data.yaml
- templates/data/warden.yaml
> Update official images to the latest versions

- images/unified-agent/Dockerfile
- images/unified-agent/go/Dockerfile
- images/unified-agent/go/go-mod-wss-unified-agent.config
- images/unified-agent/nodejs/Dockerfile
- images/unified-agent/nodejs/javascript-wss-unified-agent.config
- images/unified-agent/start-wssagent.sh
Resolve image vulnerabilities in legacy image
/kind feature
/area prow
> Add new unified-agent image

- images/unified-agent/Dockerfile
> add missing bash to unified-agent

- images/unified-agent/Dockerfile
- images/unified-agent/start-wssagent.sh
> Fix incorrect openjdk version in wss unified agent image

- development/image-syncer/external-images.yaml
https://github.com/kyma-project/keda-manager/issues/269
> Sync latest kedacore images

- prow/jobs/api-gateway/api-gateway-build.yaml
- prow/jobs/eventing-webhook/eventing-webhook-certificates-build.yaml
- templates/data/api-gateway-build.yaml
- templates/data/eventing-webhook-certificates-build.yaml
- Make api-gateway webhook build jobs config to run explicitly on main and release to exclude run on certain dev branch
> Make api-gateway webhook build jobs run on PR to main and release

- development/image-syncer/external-images.yaml
Update external deps:
- golang
- nats-box
- https://github.com/kyma-project/nats-manager/issues/124.
> Update external deps

- development/gcp/cloud-run/cors-proxy/cors-proxy.go
- Filter domains in CORS proxy
/kind feature
/area security
> Filter domains in CORS proxy

- configs/terraform/modules/cors-proxy/cors-proxy.tf
- Bump CORS-proxy image
/kind security
/area ci
> Bump CORS-proxy image

- prow/config.yaml
- Fix branch protection rules
/area ci
/kind bug
-  #8768
> Fix branch protection rules

- development/image-syncer/external-images.yaml
- Add Istio 1.19 to image repo
- Remove unneeded istioctl image
> Add istio 1.19.0 to external images

- prow/jobs/api-gateway/api-gateway-manager-build.yaml
- templates/data/api-gateway-manager-build.yaml
For images of controller/manager created from `mod-dev` branch the name is `api-gateway-manager`
> Invalid image name corrected

- prow/scripts/cluster-integration/helpers/cleanup-gardener.sh
- Add debug info to gardener cleaner
/kind bug
/area cluster
> Add debug info to gardener cleaner

- prow/jobs/kyma/kyma-integration-gardener.yaml
- templates/data/kyma-integration-gardener-data.yaml
> Gardener Azure: Remove Slack notifications

- prow/scripts/cluster-integration/helpers/cleanup-gardener.sh
- fix date to be compatible with Alpine/busybox binary
- #8885
/area ci
/kind bug
> Fix gardener cleanup

- prow/jobs/kyma/kyma-integration-k3d.yaml
- Replace outdated Kyma CLI unstable version from march in  `pre-main-kyma-integration-k3d` with latest release
> Update Kyma CLI version of k3d integration job

- prow/config.yaml
- bring back busola to squash
/area ci
/kind bug 
> allow squash for busola

- development/gcp/cloud-run/create-github-issue/create-github-issue.go
- development/gcp/cloud-run/search-github-issue/search-github-issues.go
- development/tools/cmd/configuploader/main.go
- prow/jobs/incubator/compass/components/instance-creator/instance-creator-generic.yaml
- Add missing error checks
- update linter image usage
/area security
/kind chore
> Fix security issues

- prow/jobs/nats-manager/nats-manager-generic.yaml
- templates/data/nats-manager-data.yaml
- add jobs that react to label creation
> add module release jobs for nats manager

- configs/terraform/modules/cors-proxy/cors-proxy.tf
- configs/terraform/modules/github-webhook-gateway/github-webhook-gateway.tf
- configs/terraform/modules/secrets-leaks-log-scanner/gcs-bucket-mover.tf
- configs/terraform/modules/secrets-leaks-log-scanner/github-issue-creator.tf
- configs/terraform/modules/secrets-leaks-log-scanner/github-issue-finder.tf
- configs/terraform/modules/secrets-leaks-log-scanner/secrets-leak-log-scanner.tf
- Bump cloud run images
/kind chore
/area security
> Bump cloud run images

- prow/jobs/test-infra/ko-build.yaml
- Run ko build on go.mod changes
/area security
/kind bug
> Run ko build on go.mod changes

- prow/jobs/busola/busola-integration.yaml
- prow/jobs/busola/lighthouse.yaml
- Revert to europe-docker.pkg.dev/kyma-project/prod/testimages/e2e-dind-nodejs:v20230907-2ec05714
> Fix jobs for Busola

- prow/jobs/api-gateway/api-gateway-manager-build.yaml
- templates/data/api-gateway-manager-build.yaml
- Add Api-Gateway manager build post job
> Add api gateway manager build post job

- prow/jobs/kyma-environment-broker/kyma-environment-broker-build.yaml
- templates/data/kyma-environment-broker-build.yaml
- Removed unnecessary "new" prefix.
> Removed Unnecessary 'new' Prefix

- prow/jobs/kyma/kyma-integration-k3d.yaml
- prow/jobs/kyma/kyma-preview.yaml
- Use Kyma CLI unstable in pipelines
> Use unstable kyma in pipelines

- prow/jobs/modules/internal/serverless-manager.yaml
- templates/data/generic_module_data.yaml
https://github.com/kyma-project/serverless-manager/issues/275
> Run all serverless-manager jobs on release branches

- prow/cluster/components/crier_deployment.yaml
- prow/cluster/components/deck_deployment.yaml
- prow/cluster/components/gcsweb.yaml
- prow/cluster/components/ghproxy.yaml
- prow/cluster/components/hook_deployment.yaml
- prow/cluster/components/horologium_deployment.yaml
- prow/cluster/components/prow_controller_manager_deployment.yaml
- prow/cluster/components/sinker_deployment.yaml
- prow/cluster/components/statusreconciler_deployment.yaml
- prow/cluster/components/tide_deployment.yaml
- prow/config.yaml
- prow/jobs/incubator/reconciler/reconciler.yaml
- prow/jobs/kyma-project/k8s-prow/k8s-prow-periodics.yaml
- prow/jobs/test-infra/branchprotector.yaml
- prow/jobs/test-infra/checkconfig.yaml
- prow/jobs/test-infra/prow-periodics.yaml
- prow/jobs/test-infra/triage-jobs.yaml
- prow/scripts/branchprotector-job.yaml
- prow/workload-cluster/ghproxy.yaml
- sec-scanners-config.yaml
- templates/data/checkconfig.yaml
- templates/data/incubator-buildpack-data.yaml
- templates/data/prow-periodics-data.yaml
To fix weekly autobumps with generic-autobumper. It doesn't work with semver.
/kind bug
/area prow
> Change k8s-prow tag to v20230918-27dff7fe

- prow/jobs/api-gateway/api-gateway-manager-build.yaml
- templates/data/api-gateway-manager-build.yaml
- post job creating OCI module image after merging to `mod-dev` branch
- job creating OCI module image for release purposes (triggered by tag creation).
> Module image creation jobs for api-gateway

- prow/cluster/resources/gatekeeper-constraints/prow/allowedImagesProwNamespace.yaml
- Fix nginx constraint
/kind bug
/area ci
> Fix nginx constraint

- prow/jobs/api-gateway/api-gateway-release.yaml
- templates/data/api-gateway-release.yaml
- Add security configuration for API Gateway goreleaser job
> Add sec conf for goreleaser

- prow/jobs/third-party-images/third-party-images.yaml
- templates/data/third-party-images-data.yaml
- build job is getting killed with OOM, so increasing the limits
- ...
- ...
> increased resource limits for otel-collector build

- prow/jobs/kyma-project/compass-manager/build.yaml
- add missing parameter `context` in Compass Manager build job
> Add missing parameter in Compass Manager build job

- prow/jobs/api-gateway/api-gateway-manager-build.yaml
- templates/data/api-gateway-manager-build.yaml
- api-gateway module will be tagged with concatenation of release tag and short commit SHA.
> Setting proper tag for api-gateway module while releasing

- .github/workflows/lint-markdown-links-daily.yml
- .github/workflows/lint-markdown-links-pr.yml
- .mlc.config.json
- Add new governance job based on GH actions
- ...
- ...
- #8889
/kind chore
/area ci
> Add new governance job

- prow/config.yaml
- ...
- ...
- ...
https://github.com/kyma-project/test-infra/issues/8889
/kind chore
/area ci
> Remove milv repo

- prow/scripts/reconciler/reconciler-component-provision-gardener.sh
- Fix renamed script reference
> Fix renamed script for Ory reconciler job

- prow/scripts/reconciler/reconciler-component-provision-gardener.sh
- prow/scripts/reconciler/reconciler-ory-production-gardener-integration.sh
- Add explicit script to run Ory reconciler production tests on Gardener
> Add new explicit Ory reconciler script

- prow/config.yaml
- Protect Kyma branches
/kind bug
/area ci
> Protect Kyma branches

- prow/jobs/kyma-project/kyma/components/compass-runtime-agent/unit-tests-agent.yaml
- vpath/pjtester.yaml
There was a problem with envtest setup in compass runtime agents tests.
- call the makefile, instead of inline script in yaml
https://github.com/kyma-project/kyma/pull/18240
/area tests
/area application-connector
> Fix cra tests

- CODEOWNERS
- prow/jobs/api-gateway/api-gateway-manager-build.yaml
- prow/jobs/eventing-auth-manager/eam-integration-test.yaml
- templates/data/api-gateway-manager-build.yaml
- Adjust codeowners file for #8563
- Adjust owners 
> Adjust codeowners file

- prow/jobs/modules/external/keda-manager.yaml
- templates/data/generic_module_data.yaml
- Changed PULL_BASE_SHA to PULL_BASE_REF
**Issue**
https://github.com/kyma-project/serverless-manager/issues/274
> Update Keda Image to use PULL_BASE_REF

- development/tools/cmd/externalsecretschecker/main.go
- prow/cluster/resources/external-secrets/external_secrets_checker_prow.yaml
- Fix external secrets checker
- update list of excluded secrets
/kind bug
/area ci
- #6577
> Fix external secrets checker

- prow/jobs/incubator/reconciler/reconciler.yaml
- templates/data/incubator-buildpack-data.yaml
- Pipeline `nightly-main-reconciler-e2e` only needs to be run once a day
> Reconciler e2e just needs to run once a day

- .koapps.yaml
- Add ko image for externalsecretschecker
/kind bug
/area ci
> Add ko image for externalsecretschecker

- prow/cluster/resources/external-secrets/external_secrets_checker_prow.yaml
- Bump externalsecretschecker image
- adjust prow excludes
/kind chore
/area ci
> Bump externalsecretschecker image

- prow/cluster/resources/external-secrets/external_secrets_prow.yaml
- cleanup prow secrets
/kind chore
/area prow
> cleanup prow secrets

- prow/jobs/modules/internal/serverless-manager.yaml
- templates/data/generic_module_data.yaml
> Update release job to use PULL_BASE_REF

- prow/cluster/resources/external-secrets/external_secrets_checker_prow.yaml
- prow/cluster/resources/external-secrets/external_secrets_prow.yaml
- Exclude prometheus secret from checker
- sync bot secret
/kind chore
/area prow
> Exclude prometheus secret from checker

- prow/jobs/api-gateway/api-gateway-manager-integration-tests.yaml
- templates/data/api-gateway-manager-integration-tests.yaml
- fix bug in env variable (name of image build job)
> bug fix api gateway manager job

- development/tools/cmd/jobguard/README.md
- images/buildpack/go/Dockerfile
- images/e2e-dind-k3d/Dockerfile
- images/e2e-garden/Dockerfile
- images/e2e-gcloud/Dockerfile
- prow/images/README.md
- Fix broken links for index.md
https://github.com/kyma-project/test-infra/pull/8970
> Fix broken links

- configs/kaniko-build-config.yaml
- Disable Signify dev
/area ci
> Disable Signify dev

- configs/terraform/modules/secrets-leaks-log-scanner/secrets-leak-detector.tf
- docs/how-to/how-to-create-standard-terraform-config.md
- Fix terraform job
/area ci
- #8970
> Fix terraform job

- configs/kaniko-build-config.yaml
- remove signify dev comments to avoid confusion
/kind bug
/area ci
> remove signify dev

- .github/dependabot.yml
- .gitignore
- cmd/cloud-run/move-gcs-bucket/Dockerfile
- cmd/cloud-run/slack-message-sender/Dockerfile
- development/tools/pkg/pjtester/test_artifacts/test-job.yaml
- docs/examples/gatekeeper-poc.yaml
- pkg/logging/console.go
- prow/images/automerge-notification-external-plugin/Dockerfile
- prow/images/gardener-rotate/Dockerfile
- prow/images/prow-tools/Dockerfile
- prow/jobs/kyma/kyma-validation.yaml
- prow/jobs/test-infra/build-test-vm-image.yaml
- prow/jobs/test-infra/gardener-kubeconfig-rotation.yaml
- prow/jobs/test-infra/image-syncer.yaml
- prow/jobs/test-infra/ko-build.yaml
- prow/jobs/test-infra/secret-leaks-log-scanner.yaml
- prow/jobs/test-infra/secrets-rotator.yaml
- templates/data/build-test-vm-image.yaml
- templates/data/image-syncer-data.yaml
- templates/data/kyma-validation-data.yaml
- templates/data/secret-rotation-data.yaml
- templates/data/test-infra/secret-leaks-log-scanner.yaml
- templates/data/test-infra/secrets-rotator.yaml
- Fix excludes file path
/area ci
- #8970
> Fix excludes file path

- prow/cluster/resources/gatekeeper-constraints/workloads/signifySecretTrustedUsage.yaml
- prow/jobs/modules/internal/serverless-manager.yaml
- templates/data/generic_module_data.yaml
- vpath/pjtester.yaml
- remove the usage of `generate_module_chart.sh`
- add `cp -r config/serverless module-chart` instead of non-existent script
- adjust `signifySecretTrustedUsage.yaml`
#8991
> Remove usage of generate_module_chart

- prow/scripts/cluster-integration/helpers/integration-tests.sh
- prow/scripts/cluster-integration/kyma-integration-k3d-api-gateway-components.yaml
- prow/scripts/cluster-integration/kyma-integration-k3d-app-connector-components-os.yaml
- prow/scripts/cluster-integration/kyma-integration-k3d-app-connector-components-skr.yaml
- prow/scripts/cluster-integration/kyma-integration-k3d-compass-components.yaml
- prow/scripts/cluster-integration/kyma-integration-k3d-istio-components.yaml
- prow/scripts/cluster-integration/kyma-integration-k3d-telemetry-components.yaml
- prow/scripts/cluster-integration/reconciler-istio-integration.sh
- prow/scripts/reconciler/reconciler-ory-production-gardener-integration.sh
- Remove components that were deleted from Kyma repository
- https://github.com/kyma-project/kyma/issues/18236
> Remove deleted components

- cmd/image-syncer/external-images.yaml
- Add golang 1.21.2 alpine 3.18 to the registry
> Add golang 1.21.2 alpine 3.18 to the registry

- development/tools/pkg/pjtester/test_artifacts/test-prow-config.yaml
- prow/jobs/kyma/tests/serverless/serverless-integration-k3d.yaml
- use env directly from secret
https://github.com/kyma-project/test-infra/issues/8991
> Remove env binding in command

- prow/jobs/eventing-manager/eventing-manager-generic.yaml
- templates/data/eventing-manager-data.yaml
Add Prow jobs to build Eventing module
[#81](https://github.com/kyma-project/eventing-manager/issues/81)
> Eventing Module build job

- prow/scripts/cluster-integration/kyma-serverless-run-test.sh
- vpath/pjtester.yaml
- rename test directory
https://github.com/kyma-project/test-infra/issues/8991
> Rename serverless test directory

- prow/jobs/kyma-project/warden/integration-test.yaml
https://github.com/kyma-project/warden/issues/116
> Add missing argument to the warden dind job

- prow/jobs/kyma/tests/serverless/serverless-integration-k3d.yaml
- prow/jobs/modules/external/keda-manager.yaml
- prow/jobs/modules/internal/serverless-manager.yaml
- templates/data/generic_module_data.yaml
- use `pre-*` or `post-` prefix in all serverless jobs
https://github.com/kyma-project/test-infra/pull/9038
> Unify naming in serverless jobs

- prow/jobs/kyma/tests/serverless/serverless-integration-k3d.yaml
- fix triggering path
https://github.com/kyma-project/test-infra/issues/8991
> Fix run if changed path for serverless integration

- prow/jobs/kyma-project/warden/warden.yaml
- templates/data/warden.yaml
- vpath/pjtester.yaml
- use make test target
https://github.com/kyma-project/warden/issues/116
> Fix `warden-unit-test` job

- prow/images/terraform/Dockerfile
- terraform 1.5.X is the last MPL-licensed minor version with upcoming patches (after that we can use openTofu)
/kind chore
/area security
> Bump terraform image

- configs/terraform/environments/dev/opa-gatekeeper/provider.tf
- configs/terraform/environments/prod/provider.tf
- configs/terraform/modules/opa-gatekeeper/provider.tf
- Use supported version of tf kubectl plugin
/kind chore
/area ci
> Use supported version of tf kubectl plugin

- configs/terraform/environments/prod/prow-external-plugins.tf
- fix tf kubectl apply paths
/kind bug
/area ci
/cc dekiel
> fix tf kubectl apply paths

- prow/jobs/modules/internal/application-connector-manager.yaml
- templates/data/generic_module_data.yaml
> Tag application connector manager images with git SHA

- prow/jobs/kyma-project/warden/warden.yaml
- templates/data/warden.yaml
- unify warden names with serverless names
> Unify job names

- prow/cluster/resources/gatekeeper-constraints/workloads/signifySecretTrustedUsage.yaml
- prow/jobs/modules/internal/serverless-manager.yaml
- templates/data/generic_module_data.yaml
- Fix coping `module-chart` in Serverless-Operator
https://github.com/kyma-project/serverless-manager/issues/344
> Fix coping module-chart in serverless-operator

- prow/jobs/modules/external/keda-manager.yaml
- prow/jobs/modules/internal/serverless-manager.yaml
- templates/data/generic_module_data.yaml
- change regexp pattern for serverless and keda release jobs to be triggered also by sem ver tags w/o `v` prefix
> Allow tags without v prefix

- prow/scripts/cluster-integration/kyma-serverless-integration-k3d.sh
- fix collection of logs after failed tests
https://github.com/kyma-project/serverless-manager/issues/359
> Turn off exit on error in serverless integration

- cmd/image-syncer/external-images.yaml
> Bump Istio images to 1.19.3

- .github/workflows/pull-plan-prod-terraform.yaml
- Pin used GH actions, syncing with https://github.com/kyma-project/community/pull/850
- https://github.com/kyma-project/test-infra/issues/8760
/kind chore
/area security
> Pin used GH actions

- prow/jobs/api-gateway/api-gateway-manager-build.yaml
- templates/data/api-gateway-manager-build.yaml
- change trigger for api gateway release jobs
> change trigger api-gateway release

- prow/jobs/api-gateway/api-gateway-manager-build.yaml
- prow/jobs/api-gateway/api-gateway-manager-integration-tests.yaml
- templates/data/api-gateway-manager-build.yaml
- templates/data/api-gateway-manager-integration-tests.yaml
- Add release branch as a trigger for build jobs
> Api gateway job update

- prow/jobs/api-gateway/api-gateway-manager-build.yaml
- templates/data/api-gateway-manager-build.yaml
- Extend regex for pull build jobs
> extend regex for builds on pull apigateway

- README.md
- cmd/jobguard/README.md
- prow/scripts/cluster-integration/README.md
- Job Guard documentation revert
- Documentation link revert
> Job Guard Documentation fix

- prow/jobs/eventing-manager/eventing-manager-generic.yaml
- templates/data/eventing-manager-data.yaml
Delete letter prefix letter from job trigger pattern as we don't won to add v in front of the version anymore
> Delete letter prefix letter from job trigger pattern

- prow/jobs/kyma-project/warden/warden.yaml
- templates/data/warden.yaml
- vpath/pjtester.yaml
- add `pre` and `post` jobs to build warden moduletemplates and push artifacts to the registry
- https://github.com/kyma-project/warden/issues/108
> Add jobs building warden modules

- prow/config.yaml
- Add required status checks for lifecycle manager and CLI repos
> Add required status checks for CLI and lifecycle manager

- prow/jobs/modules/external/keda-manager.yaml
- prow/jobs/modules/internal/serverless-manager.yaml
- templates/data/generic_module_data.yaml
As in title
https://github.com/kyma-project/test-infra/issues/9121
> Increased lint job timeout

- .github/workflows/pull-plan-prod-terraform.yaml
- Fix GH action commit
- https://github.com/kyma-project/test-infra/issues/8760
/kind bug
/area ci
> Fix GH action commit

- prow/config.yaml
- remove branch protection for `gh-pages` branch for price-calculator.
/area ci
/kind feature
> remove branch protection for price calculator

- prow/jobs/scans/whitesource-periodics.yaml
- templates/config.yaml
- Update nextRelease in prow config to 2.20
> Update nextRelease in prow config to 2.20

- prow/config.yaml
- Add module upgrade to the required state checks
https://github.com/kyma-project/lifecycle-manager/issues/952
> Add module upgrade to the required state checks

- prow/config.yaml
- Remove old CLI status checks
> Remove old CLI checks

- configs/autobump-config/test-infra-markdown-index-autobump-config.yaml
- Add change-record.md to ignore list for index.md autobump job
/area ci
/kind enhancement
> Add change-record.md to ignore list for index.md

- .github/workflows/lint-markdown-links-daily.yml
- Slack API Notification
- ...
- ...
> Consolidation of notifications channels for neighbors team

- prow/jobs/kyma-project/serverless-manager/serverless-manager.yaml
- templates/data/generic_module_data.yaml
Due to renaming `serverless-manager` repo to `serverless` we need to change the jobs.
- Change repo name in jobs to `serverless`
https://github.com/kyma-project/serverless/issues/345
> Change repo name to serverless

- prow/jobs/scans/whitesource-periodics.yaml
- templates/config.yaml
- Update nextRelease to 2.21
/area ci
/kind chore
> Update nextRelease to 2.21

- prow/config.yaml
- Name of required job changed to reflect changes in btp-manger e2e tests
> Name of the final job for btp-manager e2e test changed

- .githooks/pre-commit.d/01-rendertemplates.sh
- experimental/custom-image/create-custom-image.sh
- Remove openssl dependency in VM image building
- fix githook
> Remove openssl dependency in VM image building

- prow/jobs/kyma-project/istio/istio-manager.yaml
- templates/data/istio-module-data.yaml
- Tag Istio ModuleTemplate with release tag
> Tag Istio ModuleTemplate with release tag

- prow/cluster/resources/gatekeeper-constraints/workloads/kymaAutobumpBotGithubTokenTrustedUsage.yaml
- Fix trusted secrets config for the `*test-infra-image-detector-autobump` jobs
/kind bug
/area ci
> Fix trusted secrets config

- prow/jobs/kyma-project/istio/istio-manager.yaml
- templates/data/istio-module-data.yaml
- Add istio integration tests jobs for aws
> Add istio job

- prow/jobs/kyma-project/kyma-environment-broker/kyma-environment-broker-build.yaml
- templates/data/kyma-environment-broker-build.yaml
- KEB release job (triggered by a tag)
Related: https://github.com/kyma-project/kyma-environment-broker/issues/98
> Add KEB release job

- prow/jobs/kyma-project/kyma-environment-broker/kyma-environment-broker-build.yaml
- templates/data/kyma-environment-broker-build.yaml
> Fix KEB post release build

- prow/jobs/kyma-project/warden/warden.yaml
- templates/data/warden.yaml
Removed an error in the arguments
https://github.com/kyma-project/warden/issues/131
> Update Warden Verify job

- prow/cluster/resources/gatekeeper-constraints/workloads/signifySecretTrustedUsage.yaml
- Add keb release build to allowed jobs for signify secret
> Add keb release build to allowed jobs for signify secret

- prow/jobs/kyma-project/serverless/serverless.yaml
- templates/data/generic_module_data.yaml
> Rename post python39 build

- prow/jobs/kyma-project/third-party-images/third-party-images.yaml
- templates/data/third-party-images-data.yaml
- add latest tags for post docker-registry images
- add latest tags for post kaniko images
> Add `latest` tag for post-main tpi otters images

- prow/jobs/kyma-project/kyma-environment-broker/kyma-environment-broker-build.yaml
- templates/data/kyma-environment-broker-build.yaml
- fix tagging keb release builds
> Fix tagging KEB release builds

- prow/scripts/cluster-integration/kyma-serverless-integration-k3d.sh
- fix test pre-serverless-integration-k3s after moving directory hack/ci
> fix test pre-serverless-integration-k3s

- prow/jobs/kyma-project/template-operator/template-operator.yaml
- Fix arg format for release build pipeline of template-operator
> fix: release-build args template-operator

- cmd/cloud-run/scan-logs-for-secrets/kodata/gitleaks.toml
- configs/terraform/modules/secrets-leaks-log-scanner/secrets-leak-log-scanner.tf
- pkg/sign/notary_test.go
- prow/cluster/resources/external-secrets/external_secrets_checker_prow.yaml
- ...
- ...
- ...
/kind bug
/area ci
/retest
> exclude gitleaks

- .gitleaks.toml
- add separate gitleaks config for repo scan
/area security
/kind chore
> add separate gitleaks config for repo scan

- prow/jobs/kyma-project/keda-manager/keda-manager-build.yaml
- prow/jobs/kyma-project/keda-manager/keda-manager-lint.yaml
- prow/jobs/kyma-project/keda-manager/keda-manager-verify.yaml
- prow/jobs/kyma-project/serverless/serverless-build-operator.yaml
- prow/jobs/kyma-project/serverless/serverless-build.yaml
- prow/jobs/kyma-project/serverless/serverless-lint.yaml
- prow/jobs/kyma-project/serverless/serverless-verify.yaml
- prow/jobs/kyma-project/warden/integration-test.yaml
- prow/jobs/kyma-project/warden/warden.yaml
- templates/data/keda-manager.yaml
- templates/data/serverless.yaml
- templates/data/warden.yaml
- adjust (simplify) run_if_changed for serverless, keda-manager and warden jobs
> adjust run_if_changed for serverless, keda-manager and warden jobs

- cmd/cloud-run/slack-message-sender/Dockerfile
- prow/jobs/kyma-project/compass-manager/static-checks.yaml
- prow/jobs/kyma-project/test-infra/presubmit-scanner.yaml
- templates/data/test-infra/presubmit_scanner_data.yaml
> chore: bump slackmessagesender to alpine 3.18

- prow/cluster/resources/gatekeeper-constraints/workloads/kymaAutobumpBotGithubTokenTrustedUsage.yaml
/kind bug
/area ci
/this-is-unbearable
> bug: fix gatekeeper constraint for label-sync

- prow/config.yaml
> Add merge config for template-operator

- prow/jobs/kyma-project/serverless/serverless-build-operator.yaml
- prow/jobs/kyma-project/serverless/serverless-build-runtimes.yaml
- prow/jobs/kyma-project/serverless/serverless-build.yaml
- prow/jobs/kyma-project/serverless/serverless-verify.yaml
- templates/data/serverless.yaml
As in title
https://github.com/kyma-project/serverless/issues/417
> Use Long Sha in build Jobs

- cmd/cloud-run/slack-message-sender/requirements.txt
> Bump PyGithub

- cmd/cloud-run/scan-logs-for-secrets/scan-logs-for-secrets.go
- go.mod
- go.sum
- Bump gitleaks with changed redacted field: https://github.com/gitleaks/gitleaks/pull/1229
- close #9347 
/kind chore
/area ci
> Bump gitleaks

- docs/security/imagemitigation.json
- Remove image mitigation for Grafana
- https://github.com/kyma-project/test-infra/pull/9398
/kind chore
/area security
> Remove image mitigation for Grafana

- prow/jobs/kyma-project/k8s-prow/k8s-prow-periodics.yaml
- Remove success alerts for k8s-prow-periodics to the team kyma-neighbors-alerts Slack channel
/area ci
/kind chore
> Remove success alerts for k8s-prow-periodics

- CODEOWNERS
Change CODEOWNERS for cmp to be groups rather than single users. `team-raptor` and `team-falcon` are actively developing Compass.
- CODEOWNERS for CMP
> CMP Group access

- prow/jobs/kyma-project/kyma/tests/serverless/serverless-integration-k3d.yaml
- prow/jobs/kyma-project/serverless/serverless-build-operator.yaml
- prow/jobs/kyma-project/serverless/serverless-build-runtimes.yaml
- prow/jobs/kyma-project/serverless/serverless-build.yaml
- prow/jobs/kyma-project/serverless/serverless-verify.yaml
- templates/data/serverless.yaml
- Build serverless images more frequently to make it possible to use them in other jobs (to not build them in every job and push them to local registry)
https://github.com/kyma-project/serverless/issues/417
> Build serverless images more frequently

- prow/jobs/kyma-project/serverless/serverless-build-operator.yaml
- prow/jobs/kyma-project/serverless/serverless-build-runtimes.yaml
- prow/jobs/kyma-project/serverless/serverless-build.yaml
- templates/data/serverless.yaml
- remove `--tag` flag for presubmits because this flag is working only for posts
https://github.com/kyma-project/serverless/issues/417
> Remove unused lines for serverless builds

- prow/jobs/kyma-project/keda-manager/keda-manager-build.yaml
- prow/jobs/kyma-project/keda-manager/keda-manager-verify.yaml
- templates/data/keda-manager.yaml
As in title
https://github.com/kyma-project/keda-manager/issues/315
> Support release branches

- prow/config.yaml
- Allow admins to bypass branch protection in community-modules
> Allow admins to bypass branch protection in community-modules

- prow/jobs/kyma-project/serverless/serverless-release.yaml
- templates/data/serverless.yaml
Removing the release job from Prow
https://github.com/kyma-project/keda-manager/issues/315
> Move job run to GH Action

- prow/jobs/kyma-project/busola/busola-backend/busola-backend.yaml
- fix run_if_changed for post backend.
/area ci
/kind bug
> fix run_if_changed for post backend busola

- prow/config.yaml
- Add required status check for KEB
> Add required status check for KEB

- prow/config.yaml
- enable tide on the new eventing-publisher-proxy
> add squash config for epp repository

- prow/jobs/kyma-project/kyma/skr-integration.yaml
- templates/data/skr-integration-data.yaml
- add prowjob for Trial suspension e2e test
See https://github.com/kyma-project/kyma-environment-broker/issues/71
> Add Trial suspension E2E test prowjob

- images/e2e-dind-nodejs-20/Dockerfile
- images/e2e-dind-nodejs-20/init.sh
- images/e2e-dind-nodejs-20/test.sh
- add e2e-dind-nodejs-20 image with node 20
/area ci
/kind feature
> add e2e-dind-nodejs-20 image with node 20.10

- prow/jobs/kyma-project/cli/cli-k3d.yaml
- prow/jobs/kyma-project/cli/cli.yaml
- templates/data/cli-data.yaml
- `rel-kyma-cli` request mem to 8Gi and request cpu to 2
- `post-main-unstable-cli` request mem to 8Gi and request cpu to 2
> fix: Increase resources requests for cli release jobs

- prow/jobs/kyma-project/cli/cli-k3d.yaml
- prow/jobs/kyma-project/cli/cli.yaml
- templates/data/cli-data.yaml
- Omitting limit defaults to less than requests so pods won't start up
> fix: Set resources limits for cli release jobs

- docs/prow/pj-in-kind.md
/kind feature
/area ci
I don't know how long prow is going to stay, but for those who still use it this docs will be useful. Should be added to the repo
> feat: Docs how to run ProwJobs locally

- prow/scripts/reconciler/reconciler-e2e-gardener.sh
- prow/scripts/reconciler/reconciler-upgrade-kyma2-latest-to-main-gardener.sh
Adjust the test execution to wait for the reconciler...
> enable wait for reconciler again

- prow/cluster/resources/gatekeeper-constraints/workloads/privilegedContainers.yaml
- prow/jobs/kyma-project/busola/busola-integration.yaml
- prow/jobs/kyma-project/busola/lighthouse.yaml
- change image for busola to e2e-dind-nodejs-20
/area ci
/kind feature
> change image for busola to e2e-dind-nodejs-20

- prow/jobs/kyma-project/busola/busola-integration.yaml
- prow/jobs/kyma-project/busola/lighthouse.yaml
- change nodejs image for busola jobs
/area ci
/kind feature
> change nodejs image for busola jobs

- prow/jobs/kyma-project/runtime-watcher/runtime-watcher.yaml
- post build img on main has been broken for quite some time
- we need to set up the release pipeline separatly
> fix: post watcher build job

- prow/jobs/kyma-project/kyma/tests/serverless/serverless-integration-k3d.yaml
Bug fix
https://github.com/kyma-project/serverless/issues/417
> Fix brackets in job

- CODEOWNERS
- make sure all Otter's components are covered in the CODEOWNERS file
> Update otters CODEOWNERS

- prow/jobs/kyma-project/serverless/serverless-verify.yaml
- templates/data/serverless.yaml
> Fixed brackets for serverless jobs

- prow/cluster/resources/gatekeeper-constraints/workloads/kymaBotGithubSecretTrustedUsage.yaml
- kyma-upgrade-gardener-kyma2-minor-versions job was removed in https://github.com/kyma-project/test-infra/pull/9333
> Remove not needed OPA Gatekeeper config

- configs/terraform/modules/security-dashboard-token/security-dashboard-token.tf
- Fix name of the security-dashboard-token Cloud Run
https://github.com/kyma-project/test-infra/pull/9586
> Fix name of the security-dashboard-token Cloud Run

- prow/jobs/kyma-project/eventing-publisher-proxy/eventing-publisher-proxy-generic.yaml
- Change trigger of EPP presubmit build job
- Trigger always
- Exclude only docs, `.md`, README and LICENSE file
- Change trigger of EPP postsubmit build job to always
[kyma/#18477](https://github.com/kyma-project/kyma/issues/18477)
> Change trigger of EPP build job

- cmd/image-builder/main.go
- pkg/azuredevops/pipelines/templatesParams.go
- pkg/azuredevops/pipelines/templatesParams_test.go
-  Add option to verify kaniko build config
/kind feature
/area security
/test all
> Add possibility to use kaniko build config from PR in ADO Builder

- prow/jobs/kyma-project/api-gateway/api-gateway-manager-integration-tests.yaml
- templates/data/api-gateway-manager-integration-tests.yaml
- Remove APIGateway job after moving it to Github Actions
> Remove api gateway job

- prow/jobs/kyma-project/telemetry-manager/telemetry-manager-generic.yaml
- templates/data/telemetry-manager-data.yaml
- Add branch name tag to telemetry-mananger post submit build
https://github.com/kyma-project/telemetry-manager/issues/656
> Add branch name tag to telemetry-mananger post submit build

- prow/jobs/kyma-project/eventing-publisher-proxy/eventing-publisher-proxy-generic.yaml
- Use same image in `release-eventing-publisher-proxy-build` as in the other jobs
> Change image

- cmd/external-plugins/automated-approver/test_files/pullRequestReviewRequestedEventPayload
- prow/config.yaml
- prow/plugins.yaml
- Remove area and kind labels check
> Remove area and kind labels check

- prow/jobs/kyma-project/warden/warden-build.yaml
- templates/data/warden.yaml
- Add full SHA tag for warden post-submit builds
- ...
- ...
https://github.com/kyma-project/warden/issues/164
> Add full SHA tag for warden post-submit builds

- prow/cluster/resources/gatekeeper-constraints/workloads/imageBuilderAdoSecretTrustedUsage.yaml
- prow/cluster/resources/gatekeeper-constraints/workloads/pjtesterSecretsTrustedUsage.yaml
- prow/cluster/resources/gatekeeper-constraints/workloads/saKymaPushImagesSecretTrustedUsage.yaml
- prow/cluster/resources/gatekeeper-constraints/workloads/signifySecretTrustedUsage.yaml
- Secure access to sa-kyma-push-images like it is done for kyma-bot-github-token
> Secure access to sa-kyma-push-images

- prow/jobs/kyma-project/serverless/serverless-build-runtimes.yaml
- templates/data/serverless.yaml
- Adjust branches for serverless runtime post build jobs
This is done to disallow post build jobs on dependabot branches
- https://github.com/kyma-project/serverless/issues/540
> Adjust branches for serverless runtime post build jobs

- prow/cluster/resources/gatekeeper-constraints/workloads/saKymaPushImagesSecretTrustedUsage.yaml
- Fix for https://status.build.kyma-project.io/prowjob?prowjob=7843b965-efda-4753-8bc0-a96f8e91cbaa
> Add sidecar image for secured sa-kyma-push-images

- prow/jobs/kyma-project/serverless/serverless-build-runtimes.yaml
- templates/data/serverless.yaml
- Build serverless runtimes only on changes
> Build serverless runtimes only on changes

- prow/jobs/kyma-project/serverless/serverless-build-runtimes.yaml
- templates/data/serverless.yaml
This reverts commit 76029b86eef7e4b940ec2cdf28051718b9e7db74.
- ...
- ...
- ...
> Revert "Build serverless runtimes only on changes (#9640)"

- prow/jobs/kyma-project/serverless/serverless-build-operator.yaml
- prow/jobs/kyma-project/serverless/serverless-release.yaml
- templates/data/serverless.yaml
- Adjust serverless build command to be recognized by `prow/cluster/resources/gatekeeper-constraints/workloads/saKymaPushImagesSecretTrustedUsage.yaml`
> Adjust serverless build command

- prow/jobs/kyma-project/serverless/serverless-build-operator.yaml
- prow/jobs/kyma-project/serverless/serverless-release.yaml
- templates/data/serverless.yaml
- Adjust serverless build command - fix variable
- #9649
> Adjust serverless build command - fix variable

- CODEOWNERS
- Exclude vpath/pjtester.yaml from code owners Review
- ...
- ...
> Exclude vpath/pjtester.yaml from CODEOWNERS

- docs/prow/prow-cluster-update.md
- Fix the link to Prow announcements.
> Fix a broken link

- prow/jobs/kyma-project/serverless/serverless-verify.yaml
- templates/data/serverless.yaml
- This reverts premature commit f5dee2ef560c0bb62bdbeec442c43c737dffad07
https://github.com/kyma-project/test-infra/issues/9463
> Revert "Disable post-submit serverless verification jobs (#9652)"

- prow/jobs/kyma-project/serverless/serverless-release.yaml
- templates/data/serverless.yaml
- Fix serverless release build jobs by settign correct build context
/kind bug
> Fix serverless release build jobs

- cmd/image-syncer/external-images.yaml
- Bump synced Alpine version
/kind chore
/area ci
> Bump synced Alpine version

- prow/cluster/resources/gatekeeper-constraints/workloads/saKymaPushImagesSecretTrustedUsage.yaml
- Add image syncer to allowed sa-kyma-push-images secret usage. post-main-test-infra-image-syncer-run job doesn't start now.
> Add image syncer to allowed sa-kyma-push-images secret usage

- prow/cluster/resources/gatekeeper-constraints/workloads/saKymaPushImagesSecretTrustedUsage.yaml
Allow post-main-builde-testimages prowjob to use protected secret
Resolves #9668
> Allow post-main-builde-testimages prowjob to use protected secret

- prow/jobs/kyma-project/keda-manager/keda-manager-verify.yaml
- templates/data/keda-manager.yaml
- Remove `post-keda-manager-verify` job  (made redundant with `post-keda-manager-upgrade-latest-to-main`)
/kind cleanup
/area keda
- https://github.com/kyma-project/test-infra/issues/9464
> Remove post-keda-manager-verify job

- prow/jobs/kyma-project/test-infra/ko-build.yaml
- Update run_if_changed for ko build to trigger it if images definitions are changed
> Update run_if_changed for ko build

- images/alpine/Dockerfile
- prow/cluster/resources/gatekeeper-constraints/workloads/saKymaPushImagesSecretTrustedUsage.yaml
- prow/jobs/kyma-project/test-infra/ko-build.yaml
- Fix for [CVE-2023-51385](https://bdba.tools.sap/#/vulnerabilities/CVE-2023-51385)
- Fix post-test-infra-ko-build by adding to allowed usage of sa-kyma-push-images secret list
> Update alpine to 3.19.0 and fix post-test-infra-ko-build

- prow/cluster/resources/gatekeeper-constraints/workloads/saKymaPushImagesSecretTrustedUsage.yaml
- Fix image names for sa-kyma-push-images OPA Gatekeeper
> Fix image names for sa-kyma-push-images OPA Gatekeeper

- prow/cluster/resources/gatekeeper-constraints/workloads/saKymaPushImagesSecretTrustedUsage.yaml
- Remove duplicated images from sa-kyma-push-images OPA Gatekeeper config
> Remove duplicated images from sa-kyma-push-images OPA Gatekeeper config

- configs/kaniko-build-config.yaml
- pkg/azuredevops/pipelines/pipelines.go
- pkg/azuredevops/pipelines/pipelines_test.go
- Use production pipeline call to test kaniko config changes.
- Remove test pipeline id from kaniko config
/kind bug
/area ci
/test all
> Test kaniko config using production pipeline

- prow/jobs/kyma-project/eventing-manager/eventing-manager-generic.yaml
- Run post-build job on release branches in eventing-manager, because the github actions on release branches needs an image.
- The job will tag the image as `<branch name>` instead of `latest`.
- https://github.com/kyma-project/eventing-manager/issues/131
> Run post-build job on release branches in eventing-manager

- prow/jobs/kyma-project/test-infra/ado-validation.yaml
- prow/jobs/kyma-project/test-infra/buildpack.yaml
- prow/jobs/kyma-project/test-infra/images.yaml
- sec-scanners-config.yaml
- Upgrade image-builder image version, currently we have 2 different version used
https://github.com/kyma-project/test-infra/pull/9704
> Upgrade image-builder image version

- .koapps.yaml
- cmd/dashboard-token-proxy/main.go
- configs/terraform/modules/security-dashboard-token/security-dashboard-token.tf
- Add code for security-dashbaord token proxy
- Add building to .koapps.yaml
- Add ghURL secret to terraform config
/kind chore
/area security
/test all
> Build security dashboard token proxy using ko and test-infra tooling

- configs/terraform/modules/security-dashboard-token/security-dashboard-token.tf
- Use production image
/kind chore
/area security
/test all
> The patch updates the image used for the security dashboard token proxy to a newer version

- prow/cluster/resources/gatekeeper-constraints/workloads/signifySecretTrustedUsage.yaml
- prow/jobs/kyma-project/api-gateway/api-gateway-manager-build.yaml
- templates/data/api-gateway-manager-build.yaml
- vpath/pjtester.yaml
- Build api-gateway with version param from commit tag
> Build api-gateway with version param from commit tag

- prow/jobs/scans/whitesource-periodics.yaml
- templates/data/whitesource-periodics-data.yaml
- Remove hydroform from Whitesource periodic jobs
> Remove hydroform from Whitesource periodic jobs

- prow/plugins.yaml
- Disable commit message checks
- dependabot for npm creates commits with dependency name, which contains `@` in the name
/kind chore
/area ci
> Disable commit message checks

- prow/jobs/kyma-project/nats-manager/nats-manager-generic.yaml
- Updated `post-nats-manager-build` to tag image as branch name.
- Updated `post-nats-manager-build` to also run on release branches.
> Updated post-nats-manager-build to tag image as branch name

- cmd/image-syncer/external-images.yaml
…syncer
- Add Istio 1.20.2-distroless images to external-images.yaml for istio
https://github.com/kyma-project/istio/issues/567
> Add Istio 1.20.2-distroless images to external-images.yaml for istio

- .github/workflows/stale.yml
- Added a GitHub Actions workflow to automatically mark and close stale issues and pull requests.
> Stale Action instead of Stale Bot

- .github/workflows/post-apply-prod-terraform.yaml
- .github/workflows/pull-plan-prod-terraform.yaml
Migrate to latest stable release of open tofu, unfortunately setup tofu action is still in experimaental.
- Update opentofu to v1.6.1
/kind chore
/area ci
/test all
> Update reference to `opentofu` repository to use the latest version (`v1.6.1`) instead of the previous version (`v1.6.0-alpha5`)

- prow/config.yaml
- Disable managed branch protection for serverless, keda, and warden
/kind chore
/area ci
- https://github.com/kyma-project/serverless/issues/606
> Disable managed branch protection for serverless, keda, and warden

- cmd/image-syncer/external-images.yaml
- Bump Alpine image
/kind chore
/area ci
> Bump Alpine image

- prow/jobs/kyma-project/nats-manager/nats-manager-generic.yaml
Delete pull-nats-module build prow job as it is not used anymore
It is a part of the [issue](https://github.com/kyma-project/eventing-manager/issues/389)
> Delete pull-nats-module build prow job

- prow/jobs/kyma-project/istio/istio-integration.yaml
- prow/jobs/kyma-project/istio/istio-manager.yaml
- templates/data/istio-module-data.yaml
This reverts commit feeb4ddae7896be6512379520cf1f3c288efe2e7.
- Revert #9778
> Revert "Remove goat jobs (#9778)"

- prow/jobs/kyma-project/cloud-resources-manager/cloud-resources-manager-build.yaml
- Build Cloud Resource Manager KCP image on pull request
> presubmit cloud-resources-manager build

- prow/jobs/kyma-project/cloud-resources-manager/cloud-resources-manager-build.yaml
- pull-cloud-resources-manager-build optional
> pull-cloud-resources-manager-build optional

- prow/jobs/kyma-project/istio/istio-manager.yaml
- templates/data/istio-module-data.yaml
/kind feature
/area service-mesh
* add build-arg parameter to build context with PULL_BASE_REF value
* add build-arg parameter to build context with PULL_NUMBER value
https://github.com/kyma-project/istio/issues/548
> feat: pass build arg with pull reference istio

- images/e2e-dind-k3d/Dockerfile
- images/e2e-dind-nodejs/Dockerfile
- images/e2e-garden/Dockerfile
- prow/config.yaml
- prow/scripts/reconciler/common.sh
- prow/scripts/reconciler/shoot-template.yaml
- Update default kubernetes version to 1.28
Se also #9807 
/kind chore
/test all
> Update kubernetes version to 1.28

- configs/terraform/environments/prod/gcp-workfload-identity-federation.tf
- configs/terraform/environments/prod/provider.tf
- configs/terraform/environments/prod/variables.tf
- configs/terraform/modules/gcp-workload-identity-federation/main.tf
- configs/terraform/modules/gcp-workload-identity-federation/outputs.tf
- configs/terraform/modules/gcp-workload-identity-federation/provider.tf
- configs/terraform/modules/gcp-workload-identity-federation/variables.tf
- Add configuration for workload identity federation
- Add configuration for github variables
See also #8594 
/kind feature
/test all
> Tofu config for Workload IDentity Federation

- prow/jobs/kyma-project/serverless/serverless-gitserver.yaml
- templates/data/serverless.yaml
> Add missing gitServer tags

- prow/jobs/kyma-project/compass-manager/static-checks.yaml
- Update trivy from 0.47.0 to 0.49.1
> Update trivy from 0.47.0 to 0.49.1

- prow/jobs/kyma-project/test-infra/presubmit-scanner.yaml
- templates/data/test-infra/presubmit_scanner_data.yaml
> Bump gitleaks to v8.18.2

- prow/cluster/components/pushgateway_deployment.yaml
- prow/cluster/components/web_server_deployment.yaml
- sec-scanners-config.yaml
> Bump nginx to 1.25.3-alpine

- cmd/image-syncer/external-images.yaml
> Sync golang version 1.22.0

- images/unified-agent/Dockerfile
- images/unified-agent/go/Dockerfile
- images/unified-agent/nodejs/Dockerfile
- Run chmod 777 for unified agent images
> Run chmod 777 for unified agent images

- images/unified-agent/Dockerfile
- images/unified-agent/go/Dockerfile
- images/unified-agent/nodejs/Dockerfile
This reverts commit aadf9b37f6bb19d9942d87c16d2899ab58c1ed55.
- Reverts https://github.com/kyma-project/test-infra/commit/aadf9b37f6bb19d9942d87c16d2899ab58c1ed55
> Revert "Run chmod 777 for unified agent (#9889)"

- prow/jobs/kyma-project/istio/istio-manager.yaml
- templates/data/istio-module-data.yaml
- Add trigger to istio operator post build job
> Add trigger to istio operator post build job

- cmd/image-syncer/external-images.yaml
- Adds Istio's ext-authz image for testing
> Adds Istio's ext-authz image for testing

- prow/jobs/kyma-project/lifecycle-manager/lifecycle-manager.yaml
- templates/config.yaml
- templates/data/lifecycle-manager-data.yaml
- add config for kaniko-buildpack without signify-secret
- add lifecycle-manager release build
https://github.com/kyma-project/lifecycle-manager/issues/1240
https://github.com/kyma-project/lifecycle-manager/issues/1283
> add lifecycle-manager release build

- prow/jobs/kyma-project/cloud-resources-manager/cloud-resources-manager-build.yaml
- prow/jobs/kyma-project/cloud-resources-manager/cloud-resources-manager-release.yaml
- postsubmit prowjob for Cloud Resources Manager release image build
- signify-secret
> Cloud Resources Manager image build for a release.

- prow/jobs/kyma-project/busola/busola-integration.yaml
- prow/jobs/kyma-project/busola/lighthouse.yaml
> Fix run if changed for busola integration tests

- prow/config.yaml
- Disable cli v3 branch protection
/area cli
/kind chore
> Disable cli v3 branch protection

- .githooks/README.md
- docs/prow/prow-cluster-update.md
- Disable Lint Markdown Links Daily on  the Apple Stack Exchange website (the link is falsely reported as broken)
> Fix a link

- opa/gatekeeper/constraint-templates/secretTrustedUsage.yaml
- opa/gatekeeper/constraint-templates/test-data/trustedSAUsage_test-data.jsonc
- prow/cluster/resources/gatekeeper-constraints/workloads/allowPrivilegeEscalation.yaml
- prow/cluster/resources/gatekeeper-constraints/workloads/apparmor.yaml
- prow/cluster/resources/gatekeeper-constraints/workloads/privilegedContainers.yaml
- prow/cluster/resources/gatekeeper-constraints/workloads/seccomp.yaml
- prow/cluster/resources/gatekeeper-constraints/workloads/signifySecretTrustedUsage.yaml
- Use regex instead glob to match container image against constraint.
- Allow signify secrets for production image-builder image.
> Opa update new image builder

- prow/jobs/kyma-project/third-party-images/third-party-images.yaml
- templates/data/third-party-images-data.yaml
- Updated prowjobs to use image-builder image from production registry.
> Use prod image-builder

- prow/jobs/kyma-project/api-gateway/api-gateway-manager-build.yaml
- prow/jobs/kyma-project/api-gateway/eventing-webhook/eventing-webhook-certificates-build.yaml
- prow/jobs/kyma-project/api-gateway/eventing-webhook/eventing-webhook-certificates-release.yaml
- prow/jobs/kyma-project/istio/istio-manager.yaml
- templates/data/api-gateway-manager-build.yaml
- templates/data/eventing-webhook-certificates-build.yaml
- templates/data/eventing-webhook-certificates-release.yaml
- templates/data/istio-module-data.yaml
- Updated prowjobs to use image-builder image from production registry.
Depends on #9918
> Use prod image-builder image.

- prow/jobs/kyma-incubator/slack-bot/slack-bot-build.yaml
- prow/jobs/kyma-project/btp-manager/btp-manager-build.yaml
- prow/jobs/kyma-project/control-plane/components/schema-migrator/schema-migrator-build.yaml
- prow/jobs/kyma-project/control-plane/tests/e2e/provisioning/e2e-provisioning-test-build.yaml
- prow/jobs/kyma-project/kyma-environment-broker/kyma-environment-broker-build.yaml
- templates/data/btp-manager-build.yaml
- templates/data/control-plane-build.yaml
- templates/data/kyma-environment-broker-build.yaml
- templates/data/slack-bot/slack-bot-build.yaml
- Updated prowjobs to use image-builder image from production registry.
Depends on #9918
> Use prod image-builder.

- prow/jobs/kyma-project/cp-mod-migrator/cp-mod-migrator.yaml
- templates/config.yaml
- Updated prowjobs to use image-builder image from production registry.
- Use prod image builder in global config set.
closes #9826
> Use prod image builder

- prow/jobs/kyma-project/eventing-auth-manager/eventing-auth-manager-generic.yaml
- templates/data/eventing-auth-manager-data.yaml
The eventing-auth-manager jobs are failing with OOM errors. This PR increases the resource limits for these jobs.
> fix: increase the resource limits for the eventing-auth-manager jobs

- prow/images/ginkgo/Dockerfile
- Update alpine version image Fromm 3.17 to 3.19
- ...
- ...
> Update Dockerfile for gingo image

- prow/jobs/kyma-project/serverless/serverless-build-runtimes.yaml
- prow/jobs/kyma-project/serverless/serverless-release.yaml
- templates/data/serverless.yaml
- Add serverless Python 3.12 build jobs
/kind feature
/joke
- https://github.com/kyma-project/serverless/issues/746
> Add serverless Pyton 3.12 build jobs

- prow/jobs/kyma-project/cloud-manager/cloud-resources-manager-release.yaml
- Changes to postsubmits to always run on main
> Changes postsubmits to run on main

- prow/jobs/kyma-project/serverless/serverless-build-runtimes.yaml
- prow/jobs/kyma-project/serverless/serverless-release.yaml
- templates/data/serverless.yaml
- Add serverless release Python 3.12 build jobs
- rename old build job to legacy to allow creating patch releases
/kind feature
/joke
- https://github.com/kyma-project/serverless/issues/746
> Serverless pyhton312 release build

- prow/jobs/kyma-project/serverless/serverless-build-runtimes.yaml
- templates/data/serverless.yaml
- serverless: remove python39-classic jobs
- make new build jobs required
- https://github.com/kyma-project/serverless/issues/746
/kind cleanup
> serverless: remove python39-classic jobs

- prow/config.yaml
- Disable branch protection for `gh-pages` branch in KEB repo
- Disable branch protection for `sec-scanners-config-*` branches in KEB and BTP manager repo
- Disable branch protection for `bump-keb-*` branch in KEB repo
See also https://github.com/kyma-project/kyma-environment-broker/issues/408
> Disable branch protection for tech user branches in KEB and BTP manager

- prow/jobs/kyma-project/compass-manager/build.yaml
We need to increase the memory request for Compass Manager image-building job because for now, this job is being Out Of Memory killed.
> Increase memory request, CM build job is OOMK

- configs/autobump-config/test-infra-autobump-config.yaml
Add config needed to autobump image-builder images in test-infra repo.
> autobump image-builder images in test-infra

- prow/config.yaml
- Add watcher-metrics as required check for runtime watcher
https://github.com/kyma-project/lifecycle-manager/issues/1225
> Add watcher-metrics as required check for runtime watcher

- prow/jobs/kyma-project/serverless/serverless-build-runtimes.yaml
- prow/jobs/kyma-project/serverless/serverless-release.yaml
- templates/data/serverless.yaml
- Simplify build context - it should be relative, according to documentation
/kind chore
> serverless: Simplify build context

- prow/jobs/kyma-project/busola/busola-backend/busola-backend.yaml
- prow/jobs/kyma-project/busola/busola-web/busola-web.yaml
- prow/jobs/kyma-project/busola/busola.yaml
- add feature branch for busola builds
/area ci
/kind feature
> feat: add feature branch for busola builds

- cmd/image-builder/github-workflow-integration.md
- Mention in Process Flow that PAT token for authentication in ADO API is still needed.
> Clarify process flow

- cmd/dashboard-token-proxy/main.go
- Added response header required to satisfy HSTS.
> Add HSTS related response header.

- prow/jobs/kyma-project/compass-manager/build.yaml
- increase of the requested memory by Compass Manager build job
> Increase memory for CM post-build-job

- docs/documentation_guidelines.md
Doc adjustment according to the [guideline](https://github.com/kyma-project/community/blob/main/docs/guidelines/content-guidelines/03-formatting.md#ordered-and-unordered-lists) 
> use lists to create visual clarity within your content. List items in a category or in a sequence. Use an ordered list for sequential, instructional steps. Unordered lists are appropriate for items that have no sequential order, such as a list of valid file types. Follow these guidelines:
> Unordered lists are appropriate for items that have no sequential order

- prow/jobs/kyma-incubator/ord-service/components/ord-service/ord-service-generic.yaml
- sec-scanners-config.yaml
- use alpine image as opposed to ubuntu-based image
> Change compass ord-service maven image

- prow/jobs/kyma-project/application-connector-manager/application-connector-manager.yaml
- templates/data/generic_module_data.yaml
Remove application-connector-manager verify job.
- application-connector-manager verify job removed
> Remove application-connector-manager verify job

- .github/workflows/pull-plan-prod-terraform.yaml
As mentioned in #10095 we use this change.
- Switch to github planner token, with read only permissions
#10095 is required to merge this one
FIxes #8594 
/kind bug
/hold
> Use planner token

- .github/dependabot.yml
- .github/workflows/gitleaks.yml
- Add gitleask workflow
/kind feature
> Use gitleaks action

- prow/config.yaml
> Add markdown-link-check as required check for lifecycle manager

- prow/config.yaml
- make `Diff manifests` job a required check for lifecycle manager
- https://github.com/kyma-project/lifecycle-manager/issues/1329
> feat: Make `Diff manifests` job a required check for lifecycle manager

- prow/jobs/kyma-project/cloud-manager/cloud-resources-manager-build.yaml
- Removes run_if_changed for presubmits
> Removes run_if_changed for presubmits

- configs/terraform/environments/prod/gitleaks.tf
- FIx binding for gitleaks secret accesor
/kind bug
> Use proper principal binding for gitleaks

- .github/workflows/gitleaks.yml
Blocked by #10114 
- Use secret manager in the workflow
/kind feature
/area security
/hold
> Use created variables in workflow

- .github/workflows/gitleaks.yml
- Add id-token permissions
/kind bug
/area security
> Fix permissions for gitleaks

- cmd/image-syncer/external-images.yaml
- Bump keda version
https://github.com/kyma-project/keda-manager/issues/383
> Bump Keda to 2.13.1

- prow/jobs/kyma-project/kyma-metrics-collector/kyma-metrics-collector-generic.yaml
- Added release build job for KMC
- https://github.com/kyma-project/control-plane/issues/3330
> chore: added release build job for KMC

- prow/config.yaml
- skip unknown contexts for Kyma environment broker and BTP manager.
Resolves [#504](https://github.com/kyma-project/kyma-environment-broker/issues/504)
> Skip unknown contexts

- prow/jobs/kyma-project/kyma-environment-broker/kyma-environment-broker-build.yaml
- templates/data/kyma-environment-broker-build.yaml
- post job (post submit)
- pull job (pre submit)
> Add subaccount-sync jobs 

- prow/config.yaml
> Add required status check for BTP Manager

- prow/jobs/kyma-project/cloud-manager/cloud-resources-manager-build.yaml
- prow/jobs/kyma-project/cloud-manager/cloud-resources-manager-release.yaml
- Set always_run: true since per documentation it must be specified if run_if_changed/skip_if_only_changed are omitted.
> Fixes presubmits trigger

- prow/jobs/kyma-project/serverless/serverless-release.yaml
- templates/data/serverless.yaml
> Fix context for release job

- .ci-config.json
- .github/workflows/pull-gitleaks.yml
- configs/terraform/environments/prod/gitleaks-variables.tf
- Use gitleaks binary instead of dedicated action due to variable pass issue: https://github.com/orgs/community/discussions/44322
- Remove ci-config as it's not needed
/kind bug
/joke
> Switch gitleaks workflow to binary instead of action

- prow/jobs/kyma-project/test-infra/presubmit-scanner.yaml
- templates/config.yaml
- templates/data/test-infra/presubmit_scanner_data.yaml
- Remove prowjob for test infra as it was replaced by pull-gitleaks workflow
/kind deprecation
/joke
> Remove gitleaks prowjob for test-infra

- prow/jobs/kyma-project/kyma-environment-broker/kyma-environment-broker-build.yaml
- templates/data/kyma-environment-broker-build.yaml
> Add expirator build jobs

- prow/jobs/kyma-project/template-operator/template-operator.yaml
- Changed image-builder image used in prowjob to maintained and updated image.
> Use maintained image builder buildkit image.

- .github/workflows/get-oidc-token.yml
- Fix for Error Message: Can't issue ID_TOKEN for audience 'https://github.com/github'.
> Fix Get OIDC token action

- prow/jobs/kyma-project/kyma-environment-broker/kyma-environment-broker-build.yaml
- templates/data/kyma-environment-broker-build.yaml
- fix name of the expirator docker image name
> Fix expirator

- .github/workflows/get-oidc-token.yml
- Remove not needed debug action for get oidc token action
https://github.com/kyma-project/test-infra/issues/9976
> Disable get OIDC token action for pull requests

- images/e2e-dind-nodejs/Dockerfile
- Downgrade nodejs image back to 20.10.0
> build: Downgrade nodejs image back to 20.10.0

- prow/jobs/kyma-project/cloud-manager/cloud-resources-manager-release.yaml
- Updates branch filter to include tags
> Updates branch filter to include tags

- prow/jobs/kyma-incubator/compass/components/connectivity-adapter/connectivity-adapter-generic.yaml
- prow/jobs/kyma-incubator/compass/components/connector/connector-generic.yaml
- prow/jobs/kyma-incubator/compass/components/default-tenant-mapping-handler-generic/default-tenant-mapping-handler-generic.yaml
- prow/jobs/kyma-incubator/compass/components/director/director-generic.yaml
- prow/jobs/kyma-incubator/compass/components/external-services-mock/external-services-mock-generic.yaml
- prow/jobs/kyma-incubator/compass/components/gateway/gateway-generic.yaml
- prow/jobs/kyma-incubator/compass/components/hydrator/hydrator-generic.yaml
- prow/jobs/kyma-incubator/compass/components/ias-adapter/ias-adapter-generic.yaml
- prow/jobs/kyma-incubator/compass/components/instance-creator/instance-creator-generic.yaml
- prow/jobs/kyma-incubator/compass/components/kyma-adapter/kyma-adapter-generic.yaml
- prow/jobs/kyma-incubator/compass/components/operations-controller/operations-controller-generic.yaml
- prow/jobs/kyma-incubator/compass/components/pairing-adapter/pairing-adapter-generic.yaml
- prow/jobs/kyma-incubator/compass/components/schema-migrator/schema-migrator-generic.yaml
- prow/jobs/kyma-incubator/compass/components/system-broker/system-broker-generic.yaml
- prow/jobs/kyma-incubator/compass/tests/compass-e2e-tests/compass-e2e-tests.yaml
- prow/jobs/kyma-incubator/ord-service/components/ord-service/ord-service-generic.yaml
- prow/jobs/kyma-project/busola/busola-backend/busola-backend.yaml
- prow/jobs/kyma-project/serverless/serverless-build-operator.yaml
- prow/jobs/kyma-project/serverless/serverless-release.yaml
- prow/jobs/kyma-project/template-operator/template-operator.yaml
- sec-scanners-config.yaml
- templates/config.yaml
- templates/data/serverless.yaml
Bump buildkit image to newer version.
> bump buildkit image

- configs/autobump-config/test-infra-autobump-config.yaml
- prow/jobs/kyma-incubator/compass/components/connectivity-adapter/connectivity-adapter-generic.yaml
- prow/jobs/kyma-incubator/compass/components/connector/connector-generic.yaml
- prow/jobs/kyma-incubator/compass/components/default-tenant-mapping-handler-generic/default-tenant-mapping-handler-generic.yaml
- prow/jobs/kyma-incubator/compass/components/director/director-generic.yaml
- prow/jobs/kyma-incubator/compass/components/external-services-mock/external-services-mock-generic.yaml
- prow/jobs/kyma-incubator/compass/components/gateway/gateway-generic.yaml
- prow/jobs/kyma-incubator/compass/components/hydrator/hydrator-generic.yaml
- prow/jobs/kyma-incubator/compass/components/ias-adapter/ias-adapter-generic.yaml
- prow/jobs/kyma-incubator/compass/components/instance-creator/instance-creator-generic.yaml
- prow/jobs/kyma-incubator/compass/components/kyma-adapter/kyma-adapter-generic.yaml
- prow/jobs/kyma-incubator/compass/components/operations-controller/operations-controller-generic.yaml
- prow/jobs/kyma-incubator/compass/components/pairing-adapter/pairing-adapter-generic.yaml
- prow/jobs/kyma-incubator/compass/components/schema-migrator/schema-migrator-generic.yaml
- prow/jobs/kyma-incubator/compass/components/system-broker/system-broker-generic.yaml
- prow/jobs/kyma-incubator/compass/tests/compass-e2e-tests/compass-e2e-tests.yaml
- prow/jobs/kyma-incubator/ord-service/components/ord-service/ord-service-generic.yaml
- prow/jobs/kyma-project/busola/busola-backend/busola-backend.yaml
- prow/jobs/kyma-project/serverless/serverless-build-operator.yaml
- prow/jobs/kyma-project/serverless/serverless-release.yaml
- prow/jobs/kyma-project/template-operator/template-operator.yaml
- sec-scanners-config.yaml
- templates/config.yaml
- templates/data/serverless.yaml
Image version bump.
Disable buildkit-image-builder autobump.
Bump image version.
> Disabling buildkit-image-builder autobump.

- go.mod
- Temporarily downgrade go.mod to 1.21
/kind bug
/area prow
https://github.com/kyma-project/test-infra/pull/10349
> Temporarily downgrade go.mod to 1.21

- cmd/image-builder/images/buildkit/Dockerfile
- cmd/image-builder/images/kaniko/Dockerfile
- bump base image-builder image
/kind chore
/area prow
> bump base image-builder image

- configs/automated-approver-rules.yaml
- Fix approver config by allowing tfvars file to be changed in automatically approved PRs
/kind bug
/area prow
> Fix approver config

- prow/cluster/components/automated-approver_external-plugin.yaml
- Set debug log level for approver
/kind chore
/area prow
> Set debug log level to approver

- cmd/external-plugins/automated-approver/plugin.go
- prow/cluster/components/automated-approver_external-plugin.yaml
- revert log setting to info for less clutter
- mark info about file blocking the autoapprove as info
/kind feature
/area prow
> better logs for autoapprover

- cmd/image-builder/README.md
- prow/config.yaml
Migration steps.
- Added preset with ADO_PAT env variables to make it easier to migrate to ADO and make migrated prowjob compatible with rendertemplates.
- Added migration steps to image-builder docs.
> Migration to ado backend docs.

- prow/config.yaml
- Update KEB branch protection rules
> Update KEB branch protection rules

- .github/workflows/oidc-token-hello-world.yml
- Dockerfile
- action.yml
- entrypoint.sh
- images/unified-agent/Dockerfile
- Upgrade UNIFIED_AGENT_VERSION to 24.3.2
- Fix for Error: Invalid or corrupt jarfile /wss/wss-unified-agent.jar
> Upgrade UNIFIED_AGENT_VERSION to 24.3.2

- cmd/image-syncer/external-images.yaml
- Add golang 1.22.2 alpine 3.19
> Add golang 1.22.2 alpine 3.19

- prow/jobs/kyma-project/warden/warden-build.yaml
- templates/data/warden.yaml
- Skip post builds for dependabot branches
/kind bug
> Skip post builds for dependabot branches

- .github/actions/expose-jwt-action/index.js
- .github/workflows/get-oidc-token-test.yml
- .github/workflows/reusable-workflow.yml
- From now, a pipeline which runs the test to verify OIDC Token checks out to a fork
- ...
- ...
https://github.com/kyma-project/test-infra/issues/9976
> Fix action testing pipeline

- CODEOWNERS
- prow/jobs/kyma-project/third-party-images/third-party-images.yaml
- adjusted owners for cloudsql-proxy
- ...
- ...
> adjusted owners for cloudsql-proxy

- prow/config.yaml
- adds list of required checks for ACM
- ...
- ...
Better approach than #10387
> adds list of required checks for ACM

- prow/jobs/kyma-project/third-party-images/third-party-images.yaml
- removed env-files usage in third-party-images job
- ...
- ...
> removed env-files usage in third-party-images job

- prow/jobs/kyma-project/eventing-auth-manager/eventing-auth-manager-generic.yaml
- increase resources for EAM release build job
- https://github.com/kyma-project/eventing-auth-manager/issues/149
> chore: increase resources for EAM release build job

- .github/workflows/stale.yml
- Increase number of days when issues should be marked as stale (180) and closed (21)
> Increase number of days when issues should be marked as stale and closed 

- prow/jobs/scans/whitesource-periodics.yaml
- templates/data/whitesource-periodics-data.yaml
- All Kyma components was migrated to modules so old whitesource scan job can be deleted. 
> Remove ProwJob for Kyma Whitesource scan

- cmd/image-builder/README.md
**Changes**
- Added description which version of mounting ADO_PAT is compatible with rendertemplates.
- Added step about removing unsupported flags.
> Improve migration instruction

- prow/jobs/kyma-incubator/compass/compass-gke-benchmark.yaml
- prow/jobs/kyma-incubator/compass/compass-integration-no-dump.yaml
- prow/jobs/kyma-incubator/compass/compass-smoke-test.yaml
- Revert images for DinD for Compass repo
> Revert images for DinD

- prow/jobs/kyma-incubator/compass/components/schema-migrator/compass-schema-migrator-validate.yaml
- Revert images for DinD 2
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-incubator_compass/3785/pre-main-compass-schema-migrator-validate/1780153060094382080
> Revert images for DinD 2

- cmd/image-syncer/external-images.yaml
- prow/cluster/components/pushgateway_deployment.yaml
- sec-scanners-config.yaml
- Bump prom/pushgateway image
- ...
- ...
> Bump prom/pushgateway image

- prow/jobs/kyma-project/test-infra/test-infra-trusted-jobs.yaml
- sec-scanners-config.yaml
- Bump k8s/gencred image
- ...
- ...
> Bump k8s/gencred image

- prow/config.yaml
- Remove docker-registry from branch protection
/area docker-registry
/kind chore
> Remove docker-registry from branch protection

- prow/config.yaml
- `application-connector-manager` jobs unmanaged
> Unmanage application-connector-manager jobs

- prow/jobs/kyma-project/docker-registry/docker-registry-build-operator.yaml
- prow/jobs/kyma-project/docker-registry/docker-registry-release.yaml
- templates/data/docker-registry.yaml
- Migrate docker-registry to ADO builder
- https://github.com/kyma-project/test-infra/issues/10441
/kind chore
> Migrate docker-registry to ADO builder

- prow/config.yaml
- Use ADO_PAT instead of ADO_TOKEN
/area test-infra
/kind bug
> fix ADO preset key

- prow/config.yaml
- Squash docker-registry commits
/kind bug
> Squash docker-registry commits

- docs/prow/pj-in-kind.md
- docs/prow/prow-jobs-autobump.md
Update paths in links in .md files to match paths in new prow upstram repo.
> Fix deadlinks

- prow/config.yaml
- Exclude some repos from unknown jobs readiness to allow for skipped GH Action jobs
/area cli
/kind bug
> Exclude some repos from unknown jobs readiness

- prow/jobs/kyma-project/busola/busola.yaml
- adjust busola-local build to ado image-builder
/area ci
/kind feature
> feat: adjust busola-local build to ado image-builder

- pkg/logging/types.go
Added smaller and narrow logger interfaces to allow more fine graded implementations and more flexibility in choosing library for implementation.
> Added narrow and smaller interfaces.

- prow/jobs/kyma-project/keda-manager/keda-manager-build.yaml
- templates/data/keda-manager.yaml
- Migrate Keda to ADO
- https://github.com/kyma-project/test-infra/issues/10441
/kind chore
> Migrate Keda to ADO

- prow/jobs/kyma-project/warden/warden-build.yaml
- prow/jobs/kyma-project/warden/warden-release.yaml
- templates/data/warden.yaml
- Migrate Warden to ADO
- https://github.com/kyma-project/test-infra/issues/10441
/kind chore
> Migrate Warden to ADO

- prow/config.yaml
- disable branch protection for `sm-integration` branch in BTP Manager repository
> Exclude sm-integration branch from btp-manager

- prow/jobs/kyma-project/serverless/serverless-build-operator.yaml
- prow/jobs/kyma-project/serverless/serverless-build-runtimes.yaml
- prow/jobs/kyma-project/serverless/serverless-build.yaml
- prow/jobs/kyma-project/serverless/serverless-gitserver.yaml
- prow/jobs/kyma-project/serverless/serverless-release.yaml
- templates/data/serverless.yaml
This reverts commit edcb509ee9229b9a73e1c98e829d47b12ffea7c6.
- Revert "Migrate Serverless to ADO (#10470)"
> Revert "Migrate Serverless to ADO (#10470)"

- prow/jobs/kyma-project/third-party-images/third-party-images.yaml
- revert the switch of 3party-images to ado
- ...
- ...
> revert the switch of 3party-images to ado

- prow/jobs/kyma-project/api-gateway/api-gateway-manager-build.yaml
- prow/jobs/kyma-project/istio/istio-manager.yaml
- templates/data/api-gateway-manager-build.yaml
- templates/data/istio-module-data.yaml
- Trigger jobs only on tags with semvers without additional labels
- Trigger istio experimental job only on tags with semvers with additional "experimental" label
> Update release jobs triggers for api-gateway-manager and istio-manager

- prow/jobs/kyma-project/busola/busola.yaml
- revert busola from ADO
/area ci
/kind feature
> fix: revert busola-local from ADO

- prow/jobs/kyma-project/third-party-images/third-party-images.yaml
> increase memory for building the kaniko image

- cmd/image-syncer/external-images.yaml
- sync [the registry](https://hub.docker.com/layers/library/registry/2.8.3/images/sha256-33c69a810cc314b55c9e1e218ab9eb1b39034b28b023234854f093a207a87154?context=explore) image
- https://github.com/kyma-project/serverless/issues/858
> Add registry to the `external-images.yaml`

- prow/cluster/resources/gatekeeper-constraints/prow/allowedImagesProwNamespace.yaml
- Add gcr.io/k8s-prow for allowed images
> Add gcr.io/k8s-prow for allowed images

- images/e2e-dind-nodejs/Dockerfile
- Bump node image to 20.12.2 in the e2e-dind-nodejs
- Bump kubectl to v1.28.9
- Bump helm to v3.14.4
> Bump node image in the e2e-dind-nodejs

- prow/jobs/kyma-project/istio/istio-manager.yaml
- templates/data/istio-module-data.yaml
- Remove additional -experimental from istio-manager experimental image
> Update istio-manager experimental image after trigger changed

- prow/jobs/kyma-project/docker-registry/docker-registry-build-operator.yaml
- prow/jobs/kyma-project/docker-registry/docker-registry-release.yaml
- templates/data/docker-registry.yaml
- add pre-registry-init-build
- add post-registry-init-build
- add release-registry-init-build
- https://github.com/kyma-project/docker-registry/issues/18
> Add `registry-init` image building jobs

- prow/scripts/lib/kyma.sh
- remove unused lib function which uses deprecated kyma command
- ...
- ...
- https://github.com/kyma-project/kyma/issues/18652
/area tooling
/kind cleanup
> Deprecate kyma provision k3d command

- cmd/image-syncer/external-images.yaml
- Pin SHA of registry image to existing version
- ...
- ...
> Pin SHA of registry image to existing version

- cmd/image-syncer/external-images.yaml
- Add Istio 1.21.2 to the registry
> Add Istio 1.21.2 to the registry

- cmd/oidc-token-verifier/Dockerfile
- prow/jobs/kyma-project/test-infra/oidc-token-validator.yaml
- prow/jobs/kyma-project/test-infra/oidc-token-verifier.yaml
- prowjobs for building oidc-token-verifier image.
See: https://github.com/orgs/kyma-project/projects/22/views/70?pane=issue&itemId=56193547
> Build OIDC verifier

- prow/config.yaml
- Adds configs for new https://github.com/kyma-project/modulectl repo
> Add modulectl repo to prow config

- prow/jobs/kyma-project/compass-manager/build.yaml
- run `post-image-build` job only on main branch
> [Compass Manager] Run `post-job` only on main branch

- cmd/image-builder/README.md
- cmd/image-builder/images/kaniko/Dockerfile
- cmd/image-builder/main.go
- cmd/image-builder/main_test.go
- pkg/azuredevops/pipelines/templatesParams.go
- Allow to use env file in image-builder when buildInADO is true
https://github.com/kyma-project/test-infra/issues/10413
> Allow to use env file in image-builder when buildInADO is true

- configs/terraform/modules/secrets-leaks-log-scanner/secrets-leak-log-scanner.tf
- configs/terraform/modules/security-dashboard-token/security-dashboard-token.tf
- gitleaks.toml
- pkg/sign/notary_test.go
- prow/cluster/resources/external-secrets/external_secrets_checker_prow.yaml
- Instead of custom regex use, native gitleaks:allow comment https://github.com/gitleaks/gitleaks?tab=readme-ov-file#additional-configuration
> Use native gitleaks allow mechanism

- gitleaks.toml
- Gitleaks is failing due to wrong detections in auto-mainted sec-scanners-config.yaml, exclude it from scanning
See also https://github.com/kyma-project/test-infra/actions/runs/9111992354/job/25050309810?pr=10691
See alse https://github.com/kyma-project/test-infra/pull/10691
> Add sec-scanners-config to allow list

- prow/cluster/components/halogen.yaml
- prow/jobs/kyma-project/test-infra/test-infra-trusted-jobs.yaml
- sec-scanners-config.yaml
- Analyze and gencred also use previous version
> Fix prow components verison

- cmd/oidc-token-verifier/Dockerfile
- images/e2e-dind-k3d/Dockerfile
- images/e2e-dind-nodejs/Dockerfile
- images/e2e-garden/Dockerfile
- images/e2e-gcloud/Dockerfile
- Bump golang, k3d, kind, helm, k8s versions in Dockerfiles to fix some CVEs
> Bump golang, k3d, kind, helm, k8s versions in Dockerfiles

- prow/jobs/kyma-project/serverless/serverless-build-runtimes.yaml
- prow/jobs/kyma-project/serverless/serverless-release.yaml
- templates/data/serverless.yaml
This reverts commit 85500621533e1871ea831234aa54bbfa7ad23170.
- ...
- ...
- ...
> Revert "Fix serverless build jobs dockefile path (#10751)"

- prow/jobs/kyma-project/test-infra/gcr-cleaner.yaml
- sec-scanners-config.yaml
- Bump gcr-cleaner-cli to 0.12.0 - hopefully it will fix some CVEs
> Bump gcr-cleaner-cli to 0.12.0

- prow/jobs/kyma-project/kyma-dashboard/kyma-dashboard-integration.yaml
- feat: bump busola resources
/area ci
/kind feature
> feat: bump busola resources

- cmd/image-syncer/external-images.yaml
- Bump alpine & alpine-based golang image
/kind chore
/area ci
> Bump alpine & alpine-based golang image

- cmd/cloud-run/slack-message-sender/Dockerfile
- Bump python image version to python:3.12.3-alpine3.20 for Slack message sender
> Bump python image version for Slack message sender

- prow/jobs/kyma-project/serverless/serverless-gitserver.yaml
- templates/data/serverless.yaml
- Fix gitserver build
- https://github.com/kyma-project/serverless/pull/992
> Fix gitserver build

- prow/jobs/kyma-project/third-party-images/third-party-images.yaml
This reverts commit 51fcb723
- Reverts build of third party images using image builder on ADO
https://github.com/kyma-project/test-infra/issues/10413
> Revert "revert the switch of 3party-images to ado (#10540)"

- cmd/image-builder/images/buildkit/Dockerfile
- cmd/image-builder/images/kaniko/Dockerfile
- Bump dependencies of image-builder images
> Bump dependencies of image-builder images

- CODEOWNERS
We should be able to merge such [image bumps](https://github.com/kyma-project/test-infra/pull/10804) without asking other teams for approve. 
- Update CODEOWNERS - add Prow team to all Prow Jobs
> Update CODEOWNERS - add Prow team to all Prow Jobs

- configs/autobump-config/test-infra-autobump-config.yaml
- Change consistentImages to true for buildkit-image-builder in the generic autobumper config
> Change consistentImages to true for buildkit-image-builder

- cmd/image-builder/config.go
- cmd/image-builder/main.go
- Add support for AzureDevOps CI System
https://github.com/kyma-project/test-infra/issues/10413
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/post-main-tpi-cloudsql-proxy/1793603410172317696
> Add support for AzureDevOps CI System

- prow/config.yaml
- Set api-gateway and istio to unmanaged in prow config
> Set api-gateway and istio to unmanaged in prow config

- prow/jobs/kyma-project/application-connector-manager/application-connector-manager.yaml
- Add `build-in-ado` to ACM release job
> Add `build-in-ado` to ACM release job

- prow/jobs/kyma-incubator/compass/components/schema-migrator/compass-schema-migrator-validate.yaml
Rollback schema migrator image. Validation fails with error: ModuleNotFoundError: No module named 'imp'
> Revert image

- prow/jobs/kyma-project/application-connector-manager/application-connector-manager.yaml
- rollback to changes without `ado`
> [ACM] Rollback to changes without `ado`

- .github/workflows/image-builder.yml
Disable generating credentials for impersonated service account. Instead use direct access.
> Don't use a service account impersontation on GCP.

- .github/workflows/image-builder.yml
- OIDC token must contain valid audience value. The oidc token verifier in oci-image-builder pipeline expect image-builder value as it represent authenticating application.
> Use required image-builder audience in oidc token.

- configs/terraform/environments/prod/gcp-workfload-identity-federation-variables.tf
- configs/terraform/environments/prod/gcp-workfload-identity-federation.tf
- configs/terraform/environments/prod/image-builder-variables.tf
- configs/terraform/environments/prod/image-builder.tf
- We are granting permissions directly to the WIF identities.
- Use variables in workload identity federation module call.
> Remove not needed GCP and GitHub resources for image-builder. 

- prow/config.yaml
- sets kyma-project/cloud-manager merge method to squash
> Set kyma-project/cloud-manager merge method to squash

- .github/actions/image-builder/action.yml
- .github/workflows/pull-build-image-builder.yml
- .github/workflows/pull-build-oidc-token-verifier.yml
- .github/workflows/pull-build-rotate-service-account-keys.yml
- .github/workflows/pull-build-service-account-keys-cleaner.yml
- .github/workflows/pull-build-slack-message-sender.yml
- .github/workflows/pull-image-builder-test.yml
- .github/workflows/push-build-image-builder.yml
- .github/workflows/push-build-oidc-token-verifier.yml
- .github/workflows/push-build-rotate-service-account-keys.yml
- .github/workflows/push-build-service-account-keys-cleaner.yml
- .github/workflows/push-build-slack-message-sender.yml
- Update image in gh action definition to newest one.
- Fix typo in workflow name.
- Fix image build job name.
> Fix job name in workflows.

- prow/jobs/kyma-project/busola/busola.yaml
- feat: add build arg for DOCKER_TAG for busola local build
/area ci
/kind feature
> feat: add build arg for DOCKER_TAG for busola local build

- .github/workflows/image-builder.yml
- image-builder workflow usage outside kyma-project organisation is not supported. Workflow will validate if repository owner is a kyma-project.
> Prevent using image-builder workflow outside kyma-project organisation.

- .github/workflows/image-builder.yml
> fix quotes

- .github/workflows/pull-image-builder-test.yml
- Test input and output of image-builder workflow.
> Test image-builder workflow output

- .github/actions/image-builder/action.yml
- .github/workflows/image-builder.yml
According to https://docs.github.com/en/actions/creating-actions/creating-a-composite-action#creating-an-action-metadata-file we need define which step generates output, similar to how it is done in workflows.
- Set output from build step
See #9978
> Fix github workflow outputs

- .github/actions/image-builder/action.yml
- .github/workflows/pull-image-builder-test.yml
- Github action contains step to debug output, but it not contain shell field so it's failing, remove it.
> Remove invalid debug step

- .github/workflows/image-builder.yml
- Replaced job name with proper value. The outputs were empty.
> Fix job name in workflow outputs definitions. 

- prow/jobs/kyma-project/busola/busola.yaml
- fix: busola build args
/area ci
/kind feature
> fix: busola build args

- prow/config.yaml
- add prow configuration for opentelemetry-collector-components
> chore: enable tide for opentelemetry-collector-components

- prow/jobs/kyma-project/application-connector-manager/components/build-image-agent.yaml
- prow/jobs/kyma-project/application-connector-manager/components/build-image-gateway.yaml
- prow/jobs/kyma-project/application-connector-manager/components/build-image-validator.yaml
> Fix docker image paths for app con

- cmd/image-builder/README.md
- cmd/image-builder/README_deprecated.md
- Added user guide for usage of Image Builder in GitHub workflow.
- Renamed old README.md to indicate it's a deprecated documentation.
- Added deprecation notice to the old documentation.
> Image builder gh integration docs

- prow/jobs/kyma-project/application-connector-manager/components/build-image-agent.yaml
- prow/jobs/kyma-project/application-connector-manager/components/build-image-gateway.yaml
- prow/jobs/kyma-project/application-connector-manager/components/build-image-validator.yaml
Fix Dockerfile paths in post build jobs of ACM components 
> Fix acm post jobs dockerfile paths

- cmd/image-syncer/external-images.yaml
- Update Istio images to 1.22.1
- https://github.com/kyma-project/istio/issues/824
> Update Istio images to 1.22.1

- prow/jobs/kyma-project/busola/busola.yaml
- feat: revert busola from ADO
/area ci
/kind feature
> feat: revert busola from ADO

- .github/actions/image-builder/action.yml
- Use newer image builder image in gh action.
> image-builder image bump in github action

- prow/config.yaml
- Remove client credentials since they are not used any longer.
> Remove API Gateway integration test client credentials

- cmd/image-builder/main.go
- cmd/image-builder/main_test.go
- Fix validaiton by moving it to ado from client
> Move dockerfile validation to ado

- prow/jobs/kyma-incubator/compass/components/schema-migrator/compass-schema-migrator-validate.yaml
- Rollback schema migrator image
> Rollback image for compass schema migrator validation

- configs/terraform/environments/prod/gcp-workfload-identity-federation.tf
- configs/terraform/environments/prod/github-com.tf
- configs/terraform/environments/prod/image-builder.tf
After merge of this PR we need to import existing variables into terraform state.
- Move variabels related to image-builder to organization level
See #10976
> Move github variables to organizaiton level

- .github/actions/image-builder/action.yml
- cmd/image-builder/main.go
- Updating image-buidler image version in gh action to fix empty images gh output. See #11132
> Update image-builder image version in gh action

- prow/config.yaml
- Remove module-status-propagation since it will be removed in https://github.com/kyma-project/lifecycle-manager/pull/1628
> Remove module-status-propagation

- cmd/image-builder/main.go
- cmd/image-builder/main_test.go
- Refactor parse tags only feature for image builder
- Add unit tests for extracted methods
https://github.com/kyma-project/test-infra/issues/10085
> Refactor parse tags only feature for image builder

- cmd/image-syncer/external-images.yaml
- Update Istio images to 1.22.2
- https://github.com/kyma-project/istio/issues/908
> Update Istio images to 1.22.2

- cmd/image-builder/main.go
- cmd/image-builder/main_test.go
- Match any matches not only second one
> Fix getting list of built images on presubmits job

- .github/actions/image-builder/action.yml
- Upgrade image-builder image in the github action
https://github.com/kyma-project/test-infra/issues/10987
> Upgrade image-builder image in the github action

- .github/workflows/pull-validate-kaniko-build-config.yml
- Set correct permisison for getting oidc token
> Add correct permissions for pull-validate-kaniko-build-config workflow

- cmd/image-builder/README.md
- Add link to workflow file into documentaion
> Link example workflow from our repos directly in the documentation

- cmd/image-syncer/external-images.yaml
- update golang version to 1.22.5 in external images
> chore: update go version to 1.22.5 in external images

- prow/config.yaml
- Remove manifest diff pipeline from required status checks because it will be deleted
> chore: Remove manifest diff job from required

- .github/workflows/pull-image-builder-test.yml
- https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> Use non-deprecated variable setup method

- .github/workflows/pull-image-builder-test.yml
- ...
- ...
- ...
/cc @KacperMalachowski
> Fix non-deprecated variable setup method

- .github/workflows/pull-image-builder-test.yml
- Use head ref for image builder Github action test
https://github.com/kyma-project/test-infra/issues/10947
> Use head ref for image builder Github action test

- cmd/image-syncer/external-images.yaml
> Add external images go version for image builder

- cmd/image-syncer/external-images.yaml
> Import golang:1.22.5-bookworm

- cmd/image-syncer/external-images.yaml
- Add golang 1.22.5-alpine to external-images.yaml
> Add golang 1.22.5-alpine to external-images.yaml

- cmd/image-syncer/external-images.yaml
- add alpine 3.20.1 image
- run prettier
/kind feature
/area ci
> feat: add alpine 3.20.1 image

- cmd/image-syncer/external-images.yaml
- use the image-syncer to sync kaniko images
- https://github.com/kyma-project/serverless/issues/942
> Sync kaniko

- cmd/image-syncer/external-images.yaml
- sync two python versions used in the serverless runtimes
- https://github.com/kyma-project/serverless/issues/942
> Sync python images

- cmd/image-syncer/external-images.yaml
- Add fluentbit and node upstream image to external-images.yaml
> chore: add fluentbit and node to external-images

- docs/prow/authorization.md
- Update usage for sa-gcs-plank service account
https://github.com/kyma-project/test-infra/issues/9916
> Update usage for sa-gcs-plank service account

- cmd/image-syncer/external-images.yaml
> add golang:1.21 and gcr.io/distroless/static:nonroot

- configs/terraform/environments/prod/secrets-rotator.tf
- configs/terraform/environments/prod/service_accounts.tf
- Add service accounts to the Terraform config
https://github.com/kyma-project/test-infra/issues/9916
> Add service accounts to the Terraform config

- cmd/image-syncer/external-images.yaml
- add `python:3.12.4-slim-bullseye` to external images
> chore: add new python image in external images

- .github/workflows/pull-image-builder-test.yml
- Use main as ref for image builder Github action test
https://github.com/kyma-project/test-infra/issues/10947
> Use main as ref for image builder Github action test

- configs/terraform/environments/prod/secrets-rotator.tf
- configs/terraform/environments/prod/service_accounts.tf
- Remove already existing accounts(duplicated) in the tf configs
https://github.com/kyma-project/test-infra/issues/9916
> Remove already existing accounts(duplicated) in the tf configs

- configs/terraform/environments/prod/service_accounts.tf
- Add kyma-submission-pipeline Service Account to the Terraform config
https://github.com/kyma-project/test-infra/issues/9916
> Add kyma-submission-pipeline SA to the TF config

- cmd/image-syncer/external-images.yaml
> Add Alpine 3.20.2

- cmd/image-syncer/external-images.yaml
- add golang:1.22 image to image-syncer
> add golang:1.22 image

- configs/kaniko-build-config.yaml
- Add Signify support for workflow_dispatch job type
- ...
- ...
> Add Signify support for workflow_dispatch job type

- .github/workflows/pull-validate-kaniko-build-config.yml
- pull-validate-kaniko-build-config was not getting a config path
- ...
- ...
> concomitant disease

- cmd/image-syncer/external-images.yaml
- Bump external registry image
- ...
> Bump external registry image

- cmd/cloud-run/service-account-keys-cleaner/serviceaccountcleaner.go
- cmd/cloud-run/service-account-keys-cleaner/serviceaccountcleaner_test.go
- Delete Service Accounts keys which are older than 1 hour
https://github.com/kyma-project/test-infra/issues/6307
> Improve Service Accounts keys cleaner

- cmd/image-syncer/external-images.yaml
- Fix for https://status.build.kyma-project.io/?job=post-main-test-infra-image-syncer-run
> Fix post-main-test-infra-image-syncer-run

- prow/config.yaml
- feat: add busola workflows to tide
/kind feature 
/area ci
> feat: add busola workflows to tide

- images/unified-agent/python/Dockerfile
- images/unified-agent/python/python-wss-unified-agent.config
- images/unified-agent/start-wssagent.sh
- Add Python unified agent Docker image
> Add Python unified agent Docker image

- images/unified-agent/python/python-wss-unified-agent.config
- Add needed properties for Python unified agent config
> Add needed properties for Python unified agent config

- prow/config.yaml
- feat: add kyma-dashboard workflows to tide
/kind feature
/area ci
> feat: add kyma-dashboard workflows to tide

- configs/terraform/environments/prod/service_accounts.tf
- Add service account to retrieve secrets in security-scanners and orphaned cleaner pipelines
- Add service account to retrieve secrets in conduit-cli build pipeline
- Add service account to retrieve secrets in compliance pipeline
> Add service accounts to retrieve secrets in pipelines

- prow/config.yaml
Reverts kyma-project/test-infra#11542
/area ci
/kind feature
> Revert "feat: add kyma-dashboard workflows to tide"

- prow/config.yaml
- Fix required status checks for Busola
> Fix required status checks for Busola

- prow/config.yaml
- fix: kyma-dashboard tide
/area ci
/kind feature
> fix: kyma-dashboard tide

- cmd/image-syncer/external-images.yaml
- add golang 1.22.6-alpine3.20 image.
> Add golang 1.22.6 image

- cmd/image-syncer/external-images.yaml
-  Add golang 1.22.6-alpine to external-images.yaml
> Add golang 1.22.6-alpine image

- prow/config.yaml
- disable creation of branch protection rules for telemetry-manager
> chore: Set telemetry repositories to unmanaged

- cmd/image-syncer/external-images.yaml
> Add nginx 1.27-alpine image

- cmd/image-syncer/external-images.yaml
- change nginx 1.27-alpine to nginx-unprivileged
> Change nginx 1.27-alpine to nginx-unprivileged

- cmd/image-syncer/external-images.yaml
- add golang 1.23.0 to image syncer
> Add golang 1.23.0-alpine3.20 image to image syncer

- cmd/image-syncer/external-images.yaml
> update external image fluentbit to 3.1.6

- cmd/image-syncer/external-images.yaml
> Add node 22.3.0 image

- cmd/image-syncer/external-images.yaml
- Add golangci/golangci-lint to external-images.yaml
https://github.com/kyma-project/test-infra/pull/11689
> Add golangci/golangci-lint to external-images.yaml

- prow/config.yaml
- add image build to required status checks.
See also https://github.com/kyma-project/btp-manager/issues/783
> BTP Manager required status check

- prow/config.yaml
> cloud-manager-tests squash merge method

- cmd/cloud-run/rotate-service-account/rotateserviceaccount.go
- cmd/cloud-run/service-account-keys-cleaner/serviceaccountcleaner.go
- cmd/tools/usersmapchecker/main.go
- pkg/gcp/http/http.go
- pkg/oidc/oidc.go
- pkg/tools/gcscleaner/cleaner.go
- Add github.tools.sap to the trusted oidc issuers
- Fix linter issues
> Add github.tools.sap to the trusted oidc issuers

- cmd/image-syncer/external-images.yaml
- Update golangci-lint to v1.60.3 in the image syncer config
https://github.com/kyma-project/test-infra/pull/11706
> Update golangci-lint to v1.60.3 in the image syncer config

- .golangci.yaml
- Show only new issues from linters
> Show only new issues from golangci-lint

- cmd/image-syncer/external-images.yaml
- feat: change nginx image
/area ci
/kind feature 
> feat: change nginx image

- cmd/cloud-run/rotate-service-account/rotateserviceaccount.go
- cmd/cloud-run/service-account-keys-cleaner/serviceaccountcleaner.go
- cmd/tools/usersmapchecker/main.go
- pkg/gcp/http/http.go
- pkg/oidc/oidc.go
- pkg/tools/gcscleaner/cleaner.go
- Fix review comments from #11713 
See #11713
> Fix review comments from PR 11713

- .golangci.yaml
This reverts commit 28e7a921ecf89ace3ad94e16c01cf6a807e4670e.
- Revert "Show only new issues (#11720)"
> Revert "Show only new issues (#11720)"

- images/unified-agent/Dockerfile
- images/unified-agent/start-wssagent.sh
We need to have a git in the image due to go mod list command requirement for one of our module.
- Add git to unified agent images
> Add git to unified agent image

- cmd/image-syncer/external-images.yaml
> feat: Add nodejs to image syncer

- cmd/image-syncer/external-images.yaml
- 3.20.0 https://github.com/search?q=org%3Akyma-project+3.20.0&type=code
- 3.20.1 https://github.com/search?q=org%3Akyma-project+3.20.1&type=code
> Remove unused alpine images

- configs/terraform/environments/prod/gcp-workfload-identity-federation-variables.tf
- configs/terraform/environments/prod/gcp-workfload-identity-federation.tf
- Compare against string representation of owner id
> Fix attribute condition

- .github/workflows/image-syncer.yml
> Use pinned and allowed github action

- prow/config.yaml
- disable tide for terraform-module
> disable tide for terraform-module

- prow/config.yaml
- disable tide for serverless, keda and warden
> disable tide for serverless, keda and warden

- cmd/image-syncer/external-images.yaml
> Bump Keda to 2.15.1

- .github/workflows/image-syncer.yml
Using a builtin support for running docker container.
> Run docker container with uses property.

- configs/terraform/environments/prod/provider.tf
- configs/terraform/environments/prod/variables.tf
- Remove kyma-incubator from the Terraform config
> Remove kyma-incubator from the Terraform config

- .github/workflows/image-syncer.yml
This allow to mount custom volume with gcp credentials file.
See: #11384
> Use docker run command in bash. 

- .github/workflows/image-syncer.yml
Fix failing workflow.
See #11384
> Fix typo in organisation variable name

- .github/workflows/image-syncer.yml
Test container access to the credentials
> Verify container

- .github/workflows/image-syncer.yml
- cmd/image-syncer/Dockerfile
- Use dev image-syncer
- pass access token to syncer
See #11384
> Test using access token

- .github/workflows/image-syncer.yml
Use correct flag name.
See #11384
> Correct flag name.

- .github/workflows/image-syncer.yml
> Impersonate sa.

- .github/workflows/image-syncer.yml
> Fix etnrypoint

- cmd/image-syncer/external-images.yaml
> update fluentbit image to 3.1.8

- cmd/image-syncer/external-images.yaml
- The sha was not updated in https://github.com/kyma-project/test-infra/pull/11922
- ...
- ...
> Update to fluentbit 3.1.8

- .github/workflows/pull-build-image-syncer.yml
- .github/workflows/push-build-image-syncer.yml
- .koapps.yaml
- cmd/image-syncer/Dockerfile
- Added workflows to build image-syncer with image builder on pr and push.
- Added Dockerfile for building image-syncer.
- Building image syncer from scratch base image.
See #11384
> Build image syncer in github workflow.

- .github/workflows/pull-build-image-syncer.yml
- .github/workflows/push-build-image-syncer.yml
- .github/workflows/push-sync-external-images.yml
- configs/terraform/environments/prod/image-syncer.tf
- Fix workflow names.
- Fix github event in principalSet
See 11384
> Fix image-syncer implementation

- cmd/image-syncer/external-images.yaml
- Update Istio images to 1.23.2
- https://github.com/kyma-project/istio/issues/998
> Update Istio images to 1.23.2

- prow/config.yaml
- Disable tide for btp-manager
> Disable tide for btp-manager

- external-images.yaml
This is a proposal of some images to sync. If the images doesn't have to be synced the list can be removed after running push sync tests.
- test-infra local list of images to sync
See #11384
> Initial version of a list of images to sync

- prow/cluster/components/pushgateway_deployment.yaml
- prow/cluster/components/web_server_deployment.yaml
> Bump nginx to 1.27.1

- templates/config.yaml
> Remove unused image sets

- prow/config.yaml
- Set modulectl repository unmanaged in prow config to configure required jobs in Settings
> chore: set modulectl repo unmanaged

- prow/config.yaml
- Start excluding jellyfish repos from tide, starting by smallest
> chore: remove tide for modulectl

- .github/dependabot.yml
- prow/jobs/kyma-project/test-infra/images.yaml
- Remove building buildkit image for image-builder
See: https://github.com/kyma-project/test-infra/pull/11986
> Remove building buildkit image for image-builder

- pkg/sign/notary.go
> Rename gunTargets to trustedCollections to align with signify

- prow/config.yaml
> Disable tide for KEB

- cmd/image-builder/main.go
- pkg/azuredevops/pipelines/templatesParams.go
- Add function to set job type for schedule event
See: #11890
> Set jobtype for schedule event

- pkg/sign/notary.go
- pkg/sign/notary_mocks.go
- pkg/sign/notary_test.go
-  Fix digest format
- ...
- ...
https://github.com/kyma-project/test-infra/pull/11777
> Fix digest format for Signify

- prow/config.yaml
> chore: exclude cloud-manager from tide

- .github/workflows/buildx-images.yml
- Enable workflow to PR and push event
- Switch image builder to native main, without additional check (it was required to test workflow on branch)
- rename to buildx-images.yml
https://github.com/kyma-project/test-infra/issues/9434
> Update and rename pull-ex-buildx-images.yml to buildx-images.yml

- prow/jobs/kyma-project/test-infra/validation.yaml
- templates/config.yaml
The job are failing since the tag and given image-url doesn't exists together.
- Update build-pack go to use newest available tag
> Fix build-pack to use correct tag

- .github/workflows/lint-markdown-links-daily.yml
- .github/workflows/lint-markdown-links-pr.yml
Both PR and daily checks are failing. PR is sending me annoying emails that it didn't start on my PR, so I decided to fix it.
- Use version from https://github.com/kyma-project/community/blob/main/docs/contributing/assets/allowed_actions.json#L75C10-L75C50
> Use static version of markdown-links-check github actions

- prow/config.yaml
> add tide excludes for telemetry-manager repos

- cmd/image-builder/README.md
It's missing in documentation, but it should be there.
- Add schedule to supported signing events in image builder README file
> Add schedule to supported signing events in image builder README file

- .github/workflows/autobump-images.yml
- .github/workflows/reusable-image-autobumper.yml
- Add image autobumper to the github workflows
See: #12056
> Add image autobumper to the github workflows

- .github/workflows/image-autobumper.yml
- Fix reference to autobump config from env to inputs
See: #12056
> Fix the reference to autobump config in steps

- configs/terraform/environments/prod/artifact-registry-variables.tf
- configs/terraform/environments/prod/artifact-registry.tf
- configs/terraform/environments/prod/image-builder-variables.tf
- configs/terraform/environments/prod/image-builder.tf
- configs/terraform/environments/prod/modules-submission-variables.tf
- configs/terraform/environments/prod/modules-submission.tf
- configs/terraform/environments/prod/service_accounts.tf
- Adding resources for submission pipeline.
- Moving resources related to image-builder to dedicated files.
- Cleanup import statements.
> Adding IaC for submission pipeline.

- prow/config.yaml
- Add Istio, APIGateway and networking-dev-tools to tide exclusion
> Add Istio, APIGateway and networking-dev-tools to tide exclusion

- .github/workflows/image-syncer.yml
Using latest production build.
See: #11384
> Use newest production image syncer.

- .github/workflows/image-autobumper.yml
- Update image-autobumper to use newest image
See: #12056
> Bump image autobumper

- .github/dependabot.yml
- Do not update dependency automatically as it must be approved in https://github.com/kyma-project/community/blob/main/docs/contributing/assets/allowed_actions.json
> Disable updates for golangci linter actions

- .github/workflows/image-autobumper.yml
- Bump image autobumper image to the newest version
See: #12056
> Bump image autobumper image to the newest version

- cmd/image-autobumper/Dockerfile
- cmd/image-autobumper/main.go
- cmd/image-detector/main.go
- cmd/markdown-index/main.go
- pkg/github/bumper/bumper.go
The implementation made in https://github.com/kyma-project/test-infra/pull/12162 is not working as expected and fix is harder than expected.
- Switch back to k8s based bumper
- Update bumpers to use updated bumper
See: #12056
> Restore k8s based bumper

- .github/workflows/autobump-docs-index-md.yml
- .github/workflows/autobump-security-config.yaml
- Switch bumper docker to run in privileged mode
- Use drop kernel capabilities for security as recommended by OWASP
- Rename `push-update-security-config` to `autobump-security-config` for consistency
See: #12056
> Fix bumpers don't have permisisons to access global git config in container

- configs/automated-approver-rules.yaml
Currently aut-approver don't approve auto-bumper PRs which change action.yml from image-builder.
- Add .yml to auto-approver config
> Allow auto approver to approve changes in .yml files changed by kyma-bot

- cmd/image-autobumper/README.md
For now, the image autobumper is a tool used internally in test-infra repository. 
The documentation will be used internally for now as well, but we might offer the image-autobumper as a service in the future.
- Add the documentation for the image-autobumper
Fixes: #12056
> Add image autobumper documentation

- configs/terraform/environments/prod/image-builder-variables.tf
- DIsable cleanup policy dry run on cache repository
See: #9765
> Disable dry run on cache repository

- .github/actions/image-builder/action.yml
- Remove flag from current action
> Fix builder is failing due to unknown flag

- cmd/image-builder/main.go
- Rename use-go-interna-sap-modules to use-go-internal-sap-modules
> Fix typo in use-go-internal-sap-modules flag

- .github/actions/image-builder/action.yml
Image is bumped, no more problem from mentioned PR
Reverts kyma-project/test-infra#12340
> Revert "Fix builder is failing due to unknown flag"

- sec-scanners-config.yaml
- Add rc-tag in the security config pointing to the [rc-tag](https://github.com/kyma-project/test-infra/releases/tag/rc-tag) to test the migration to the Checkmarx One scanner.
> Add rc-tag in the sec-scanners-config.yaml

- sec-scanners-config.yaml
- add kind: kyma to test-infra
- add checkmarxone segment in sec scanner config
- ...
> Add CheckmarxOne to sec-scanners-config.yaml

- .github/workflows/pull-image-builder-test.yml
> Add merge group event to image-builder-test

- cmd/image-builder/README.md
- Update documentation with information about support for merge_group event
See #12116
> Update image-builder documentation with merge_group

- cmd/cloud-run/slack-message-sender/requirements.txt
Werkzeug 3.0.6 has fix CVE-2024-49767
> Require werkzeug minimum 3.0.6 version

- cmd/cloud-run/cors-proxy/Dockerfile
- cmd/cloud-run/create-github-issue/Dockerfile
- cmd/cloud-run/github-webhook-gateway/Dockerfile
- cmd/cloud-run/move-gcs-bucket/Dockerfile
- cmd/cloud-run/rotate-service-account/Dockerfile
- cmd/cloud-run/scan-logs-for-secrets/Dockerfile
- cmd/cloud-run/search-github-issue/Dockerfile
- cmd/cloud-run/service-account-keys-cleaner/Dockerfile
- cmd/dashboard-token-proxy/Dockerfile
- cmd/external-plugins/automated-approver/Dockerfile
- cmd/image-autobumper/Dockerfile
- cmd/image-detector/Dockerfile
- cmd/image-syncer/Dockerfile
- cmd/image-url-helper/Dockerfile
- cmd/markdown-index/Dockerfile
- cmd/oidc-token-verifier/Dockerfile
- cmd/tools/externalsecretschecker/Dockerfile
- cmd/tools/usersmapchecker/Dockerfile
- images/e2e-gcloud/Dockerfile
- Unify golang builder images to 1.23.4-alpine3.21
> Unify golang builder images to 1.23.4-alpine3.21

- cmd/cloud-run/signifysecretrotator/Dockerfile
- cmd/cloud-run/slack-message-sender/Dockerfile
- Bump python builder images to 3.13.1-alpine3.21
- Fix found CVEs
> Bump python builder images to 3.13.1-alpine3.21

- images/unified-agent/python/python-wss-unified-agent.config
- Poetry is downloading incompatible software with base image of Unified Agent, as a temporary solution - disabling this step helps - so the projects are scanned
> Disable Python3's Unified Agent poetry pre step

- .github/workflows/all-checks-passed.yml
- Add all-checks-passed workflow
https://github.com/kyma-project/test-infra/issues/12287
> Add all-checks-passed workflow

- cmd/image-builder/main.go
- pkg/imagebuilder/report.go
- pkg/imagebuilder/report_test.go
We need to debug weird behaviour of image builder directly on pipeline
- Add debug logs
- Remove dryRUn if statement that was doing nothing
> Fix getting report

- prow/config.yaml
> chore: Remove tide from busola

- cmd/image-builder/main.go
- pkg/imagebuilder/report.go
- pkg/imagebuilder/report_test.go
- Prepare for migration to new image build report by temporary supporting both
- Mark funcitons that should be deleted when new format is introduced
> Switch to new build report format

- .github/workflows/image-builder.yml
GitHub Context description: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#github-context
- Add temporary step to print workflow ref and verify it in the future.
> Print workflow ref

- .github/workflows/build-automated-approver.yml
> Fix auto approver build

- pkg/imagebuilder/report.go
- pkg/imagebuilder/report_test.go
As a backend structure is updated to new format, the temporary supprot for new and old one is not required anymore.
- Remove temporary support for both versions of report structure
> Remove temporary code

- .github/dependabot.yml
- This change add config of python's pip to dependabot
- ...
- ...
https://github.com/kyma-project/test-infra/issues/12745
> Update dependabot to work with pip requirements files

- prow/cluster/components/cla-assistant.yaml
- Update cla-assistant image to the newest version: v20250307-875cc1f.
https://github.com/kyma-project/test-infra/pull/12768
> Update cla-assistant image to v20250307-875cc1f

- .github/dependabot.yml
- This change add config of python's pip to dependabot
- Previous change was incorrect, because dependabot does not support multi directory https://github.com/kyma-project/test-infra/pull/12771
- ...
https://github.com/kyma-project/test-infra/issues/12745
> Update dependabot to work with pip requirements files (explicit paths)

- .github/dependabot.yml
Prevbiously we had a allowed-actions.json which must be bumped before action bump. 
Since it's not the case now, we can unignore and enable autobump for all actions
- Remove actions from ignore
> Remove ignored actions

- cmd/cloud-run/signifysecretrotator/Dockerfile
- docs/how-to/how-to-manage-follow-up-issues.md
- Add Guidelines for Managing Follow-Up Issues as discussed on the Sprint Retrospective according to the https://github.com/kyma-project/test-infra/blob/main/docs/documentation_guidelines.md. 
> Add Guidelines for Managing Follow-Up Issues

- .github/actions/image-builder/action.yml
- .github/workflows/image-builder.yml
- Add support for platforms parameter to actions
- Add support for switching buildEngine to `buildx`
- Add summary with built images
See: #12829
> Add support for platforms and build engines to github actions

- .github/workflows/post-apply-prod-terraform.yaml
- .github/workflows/pull-plan-prod-terraform.yaml
Setup-tofu action is no longer considered as experimental 
- Switch to dedicated action for setting up tofu in acitons
- Remove code for building tofu binary from source
> Switch to setup-tofu as it is stable now

- .github/workflows/auto-author-assign.yml
- Add [Auto Author Assign](https://github.com/marketplace/actions/auto-author-assign) for pull requests. 
- Github action was tested in https://github.com/Sawthis/test-infra/pull/18 .
> Add Auto Author Assign

- configs/terraform/environments/prod/restricted-markets-delivery.tf
Granting permissions for correct repository. At present permissions are granted on dev repository.
- Update IaC to grant permissions to the correct repository. Restricted markets deliver need access to prod repository with modules.
https://github.com/kyma-project/test-infra/pull/12984
> fix: Grant permissions for correct repository

- cmd/cloud-run/signifysecretrotator/Dockerfile
- cmd/cloud-run/slack-message-sender/Dockerfile
This pull request updates the Dockerfiles for the `signifysecretrotator` and `slack-message-sender` services to improve dependency management and streamline the build process. The changes introduce the use of virtual environments (`venv`) for dependency isolation and switch to Chainguard base images for enhanced security and simplicity.
**Reason:**
These changes fixes sqlite3, busybox and zlib vulnerabilities existing in our current versions of python images.
**Dockerfile Improvements:**
* **Dependency Isolation with Virtual Environments**:
- Added a virtual environment (`venv`) in the build stage to isolate Python dependencies. The `venv` is then copied to the production image and activated via the `PATH` environment variable. (`cmd/cloud-run/signifysecretrotator/Dockerfile`, …
> Use minimal base image and multistage build of python image

- .github/actions/image-builder/README.md
- cmd/image-builder/README.md
- cmd/image-builder/github-workflow-integration.md
- Update Image Builder docs with multiple architectures support.
- Add documentation for BuildEngine and Platforms parameters. 
- Add examples for BuildEngine and Platforms parameters.
https://github.com/kyma-project/test-infra/issues/13004
> Update Image Builder docs with multiple architectures

- .github/workflows/build-automated-approver.yml
- .github/workflows/build-buildpack.yml
- .github/workflows/build-cors-proxy.yml
- .github/workflows/build-dashboard-token-proxy.yml
- .github/workflows/build-github-webhook-gateway.yml
- .github/workflows/build-image-autobumper.yaml
- .github/workflows/build-image-builder.yml
- .github/workflows/build-image-detector.yml
- .github/workflows/build-image-syncer.yml
- .github/workflows/build-image-url-helper.yml
- .github/workflows/build-markdown-index.yml
- .github/workflows/build-oidc-token-verifier.yml
- .github/workflows/build-rotate-service-account-keys.yml
- .github/workflows/build-service-account-keys-cleaner.yml
- .github/workflows/build-signify-secret-rotator.yml
- .github/workflows/build-slack-message-sender.yml
- .github/workflows/build-unified-agent.yml
- .github/workflows/build-usersmapchecker.yml
- Switch reference from `refs/heads/main` to `main`
See: #12762
> Fix workflows reference

- .github/workflows/workflow-controller-build-1.yml
- .github/workflows/workflow-controller-build-2.yml
- .github/workflows/workflow-controller-pull-requests.yml
- Set teh correct permissions in workflows controllers, so reusable workflow can run
See: #12762
> Fix workflows permissions in reusable workflows

- configs/terraform/environments/prod/modules-submission.tf
- Add access for sre group to `kyma-modules` repository in GCP
- ...
- ...
kyma/test-infra/issues/692
> Add kyma_modules_admin_sre resource

- .github/actions/checkout/README.md
- .github/actions/checkout/action.yml
- .github/workflows/lint-markdown-links-pr.yml
- .github/workflows/pull-gitleaks.yml
- .github/workflows/pull-go-lint.yaml
- .github/workflows/pull-plan-prod-terraform.yaml
- .github/workflows/pull-unit-test-go.yaml
- .github/workflows/pull-validate-dockerfiles.yaml
- .github/workflows/pull-validate-scripts.yaml
- .github/workflows/tf-lint.yaml
- .github/workflows/workflow-controller-build-1.yml
- .github/workflows/workflow-controller-build-2.yml
- .github/workflows/workflow-controller-pull-requests.yml
- Add custom checkout action to hide logic of checking out PR codebase
- Update workflows to use that new action
See: #12762
> Add custom checkout action to hide logic of checking out PR codebase

- .github/workflows/code-checks-python.yml
- .github/workflows/image-syncer.yml
- Use custom checkout action instead of steps to verify merge commit sha
See: #12762
> Migrate workflwos to custom checkout action

- .github/actions/checkout/README.md
- .github/actions/checkout/action.yml
- Change default value in the description to 5
- Update link to sanity check description
- Update README
See: #12762
> Improve checkout action inputs

- docs/how-to/how-to_manage_workflow_controller.md
- docs/what-is/what-is_workflow_controller.md
- Add documentation for managing workflow controllers
- Add documentation describing purpose of workflow controllers
See: #13181
> Add workflows controller documentation

- cmd/dashboard-token-proxy/main.go
This pull request introduces a sanitization mechanism to enhance security in the `dashboard-token-proxy` by preventing injection attacks. The key changes include adding a `sanitizeUserInput` function and integrating it into the token handling logic. This fixes a log forging vulnerability.
* **Added input sanitization function**: Introduced the `sanitizeUserInput` function to remove control characters (e.g., newlines and carriage returns) from user input, using a regular expression. This helps mitigate potential injection attacks. [cmd/dashboard-token-proxy/main.goR48-R55](diffhunk://#diff-76c73be3d38c08854196656cf5e67d375e91bff0b39829b465c0471380e586f9R48-R55)
* **Sanitized OAuth code**: Updated the `HandleTokenRequest` function to sanitize the `oauthz_code` parameter before using it in …
> feat: add input sanitization to prevent injection attacks

- prow/cluster/resources/external-secrets/external_secrets_trusted.yaml
- prow/config.yaml
- Remove github-issues secret token for trusted workloads
> Remove unused external-secret

- .github/actions/image-builder/README.md
- cmd/image-builder/README.md
- cmd/image-builder/config.go
- cmd/image-builder/github-workflow-integration.md
- Remove rest of documentation for Image Buiilder with kaniko/buildengine
- ...
- ...
https://github.com/kyma-project/test-infra/issues/12845
> Cleanup documentation

- configs/terraform/environments/prod/provider.tf
- configs/terraform/environments/prod/variables.tf
- Remove kubernetes providers
- Remove data for prow cluster
See #12470
> Remove prow cluster resource

- configs/terraform/environments/prod/modules-submission.tf
- Remove all resources kyma_project_kyma_submission_pipeline identity
https://github.com/kyma-project/test-infra/issues/12926
> Cleanup terraform after removing old submission pipeline

- cmd/cloud-run/cors-proxy/Dockerfile
- cmd/cloud-run/github-webhook-gateway/Dockerfile
- cmd/cloud-run/signifysecretrotator/Dockerfile
- cmd/dashboard-token-proxy/Dockerfile
- cmd/oidc-token-verifier/Dockerfile
- go.mod
This reverts commit fc02080697f2149788f1045334cf91d978066e2a.
- We need to revert this bump and add running unit tests when go.mod and go.sum are changed to unblock pull requests that require running unit tests.
- https://github.com/kyma-project/test-infra/pull/13434
- https://github.com/kyma-project/test-infra/pull/13438
- https://github.com/kyma-project/test-infra/pull/13405
> Revert "bump golang version"

- .github/renovate-sharable-config.json
Add custom manager for regex dependency matching
It creates regex for correctly matching our custom images and custom localization (yaml, sh, json)
> Add custom manager for regex dependency matching
